### PR TITLE
Implements ACLK v2 http message with compression

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Implements `http` v2 message (cloud request) which allows less processing on the cloud side and allows compression of the data.
Additionally following fields are added on request of cloud team:
```
- t-exec - time it took to process the query
- t-rcvd - time at which request was received
```
Additionally rx message handling is moved to separate file `aclk_rx_msgs.c/.h` from `agent_cloud_link,c/.h` in attempt to gradually organize and clean up the code where possible.

- [x] Verify reviewers can test on a staging
- [x] Production allowed as well now

##### Component Name
agent/aclk

##### Test Plan

For testing override version definintions in `aclk_common.h` as follows:
```
#define ACLK_VERSION_MIN 2
#define ACLK_VERSION_MAX 2
```

make sure your agent is connecting to `staging.netdata.cloud`, not to production. After forcing ACLK_VERSION_MIN to 2 agent will use ACLKv2 despite the cloud not sending yet the reply for `hello` version_negotiation message.

Connect your agent with staging and browse the dashboard. All should still work as usual. Verify with your browser debug console chart data are coming with encoding `gzip`.

Screenshot from 2020-09-08 15-54-42

Test to production with:
```
#define ACLK_VERSION_MIN 1
#define ACLK_VERSION_MAX 2
```
In this case ACLK should fall back to version 1 and compression should not be used (this tests backward compatibility)

### CODE REVIEW

**Review by amoss — COMMENTED** [review]
Tested against staging: works fine - all the responses are gzip'd.
Tested against production: node is unreachable.

**Comment by amoss** [comment]
This may be an existing bug, here is the test-sequence:
1. Claim node on staging.
2. Connect node
3. Reclaim under a fresh id on production.
4. Claim succeeds, node appears in room but is unreachable.

```
../dev-install-review/netdata/usr/sbin/netdata-claim.sh -token=ui7FyuDuLu5O7B6w1JskhgbIR2Y59JtfK6NyxzNOlg7oaTTPboWrD4KSF53EZ8TtspZJCugoVStjDnNvhP9db3nMW1FRbXAt2Aofkonp9r4Npi9YJCnojVUuiKpFD6-ev1o-HwA -rooms=30cab618-5ac2-4e8c-afbb-ee9459eac0d4 -url=https://app.netdata.cloud -id=$(uuidgen)
Token: ****************
Base URL: https://app.netdata.cloud
Id: fcd2fac9-a902-4221-8dd1-521294eb34cc
Rooms: 30cab618-5ac2-4e8c-afbb-ee9459eac0d4
Hostname: loki
Proxy: 
Netdata user: amoss
Node was successfully claimed.
```
Relevant log:
```
2020-09-10 09:48:17: netdata ERROR : ACLK_Query_1 : ACLK version negotiation failed. No reply to "hello" with "version" from cloud in time of 3s. Reverting to default ACLK version of 2.
2020-09-10 09:50:20: netdata INFO  : MAIN : Command Clients = 1

2020-09-10 09:50:20: netdata INFO  : MAIN : EOF found in command pipe.
2020-09-10 09:50:20: netdata INFO  : MAIN : COMMAND: Sending reply: "X0"
2020-09-10 09:50:20: netdata INFO  : MAIN : Command Clients = 0

2020-09-10 09:50:20: netdata INFO  : MAIN : Command Clients = 1

2020-09-10 09:50:20: netdata INFO  : MAIN : EOF found in command pipe.
2020-09-10 09:50:20: netdata INFO  : MAIN : COMMAND: Sending reply: "X0"
2020-09-10 09:50:20: netdata INFO  : MAIN : Command Clients = 0

2020-09-10 09:50:21: netdata INFO  : MAIN : Command Clients = 1

2020-09-10 09:50:21: netdata INFO  : MAIN : EOF found in command pipe.
2020-09-10 09:50:21: netdata INFO  : MAIN : write-config cloud|global|enabled|yes
2020-09-10 09:50:21: netdata INFO  : MAIN : write-config conf_file=cloud section=global key=enabled value=yes
2020-09-10 09:50:21: netdata INFO  : MAIN : COMMAND: Sending reply: "X0"
2020-09-10 09:50:21: netdata INFO  : MAIN : Command Clients = 0

2020-09-10 09:50:21: netdata INFO  : MAIN : Command Clients = 1

2020-09-10 09:50:21: netdata INFO  : MAIN : EOF found in command pipe.
2020-09-10 09:50:21: netdata INFO  : MAIN : write-config cloud|global|cloud base url|https://app.netdata.cloud
2020-09-10 09:50:21: netdata INFO  : MAIN : write-config conf_file=cloud section=global key=cloud base url value=https://app.netdata.cloud
2020-09-10 09:50:21: netdata INFO  : MAIN : COMMAND: Sending reply: "X0"
2020-09-10 09:50:21: netdata INFO  : MAIN : Command Clients = 0

2020-09-10 09:50:21: netdata INFO  : MAIN : Command Clients = 1

2020-09-10 09:50:21: netdata INFO  : MAIN : EOF found in command pipe.
2020-09-10 09:50:21: netdata INFO  : MAIN : COMMAND: Reloading Agent Claiming configuration.
2020-09-10 09:50:21: netdata INFO  : MAIN : Agent was already connected to Cloud - forcing reconnection under new credentials
2020-09-10 09:50:21: netdata INFO  : MAIN : File '/home/amoss/netdata/dev-install-review/netdata/var/lib/netdata/cloud.d/claimed_id' was found. Setting state to AGENT_CLAIMED.
2020-09-10 09:50:21: netdata INFO  : MAIN : COMMAND: Sending reply: "X0"
2020-09-10 09:50:21: netdata INFO  : MAIN : Command Clients = 0

2020-09-10 09:50:21: netdata INFO  : ACLK_Main : MQTT disconnected from broker
2020-09-10 09:50:21: netdata ERROR : ACLK_Main : Connection to cloud failed
2020-09-10 09:50:21: netdata INFO  : ACLK_Main : Disconnect detected (0 queued queries)
2020-09-10 09:50:21: netdata ERROR : ACLK_Main : Closing lws connectino due to libmosquitto error.
2020-09-10 09:50:21: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_CLIENT_CLOSED
2020-09-10 09:50:21: netdata INFO  : ACLK_Main : Processing callback LWS_CALLBACK_WSI_DESTROY
2020-09-10 09:50:21: netdata ERROR : ACLK_Main : Unknown LWS callback 28
2020-09-10 09:50:21: netdata INFO  : ACLK_Main : Processing callback unknown
2020-09-10 09:50:21: netdata ERROR : ACLK_Main : Unknown LWS callback 28
2020-09-10 09:50:21: netdata ERROR : ACLK_Main : Unexpected callback from libwebsockets unknown
2020-09-10 09:50:21: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 0.000 seconds
2020-09-10 09:50:21: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-09-10 09:50:21: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: staging.netdata.cloud 443 /api/v1/auth/node/fcd2fac9-a902-4221-8dd1-521294eb34cc/challenge
2020-09-10 09:50:21: netdata INFO  : ACLK_Main : aclk_send_https_request GET
2020-09-10 09:50:22: netdata ERROR : ACLK_Main : Challenge failed: {"errorCode":"TODO trace-id","errorMsgKey":"ErrNodeNotFound","errorMessage":"node not found"}
```

It seems likely that the claim failed but reported success?

**Comment by underhood** [comment]
Hi the production is not ready yet for compression. Only staging works. I will let you know when production is ready. Currently behavior with production is undefined.

**Comment by amoss** [comment]
Ok, so we are still blocked from merging it?

**Comment by underhood** [comment]
Merging is blocked Yes. Review possible with staging. Asked last time yesterday evening about ETA and don't have an answer yet.
I will not merge until cloud gives permission of course.

**Comment by amoss** [comment]
Works fine on staging. I can't approve it without seeing it run on production.

**Review by amoss — APPROVED** [review]
Works on production.

**Comment by stelfrag** [comment]
Setting up to test on production ...

**Review by stelfrag — APPROVED** [review]
Negotiation fails , ACLK defaults to version 2 and compression is enabled

**Pull request merged**
