### PR TITLE
replication fixes #5

### PR DESCRIPTION
**Pull request by ktsaou**
1. Fixed bug in replication which allowed the first BEGIN/SET/END to travel before the replication starts
2. Rewrite in a simpler and more traceable way the logic of the initial replication request for each chart
3. Cleanup plugins.d logic to reuse the same error handling

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @ktsaou ,

I observed that we have PRs addressing replication, so I decided to test this with the following environment: 

#### Parent
- Streaming enabled with compression and replication.
- Connection has TLS (OpenSSL 1.1.1s)
- Host X86_64
- Memory mode `RAM`

On parent I have different error messages like this:

```sh
2022-11-23 17:44:33: netdata IERR  : WEB_SERVER[static4] : (2848@database/rrdcontext.:query_target_cr): QUERY TARGET: query 'chart://host:potinho/instance:system.cpu/dimensions:|iowait/after:-540/before:0/points:197/group:average/options:nonzero,flip,jsonwrap,ms' does not have all the data required. Matched 1 hosts, 1 contexts, 1 instances, 10 dimensions, 0 metrics to query, 10 metrics skipped because they don't have data in the desired time-frame. Aborting it.
2022-11-23 17:44:33: netdata IERR  : WEB_SERVER[static4] : (2848@database/rrdcontext.:query_target_cr): QUERY TARGET: query 'chart://host:potinho/instance:system.cpu/dimensions:|softirq/after:-540/before:0/points:197/group:average/options:nonzero,flip,jsonwrap,ms' does not have all the data required. Matched 1 hosts, 1 contexts, 1 instances, 10 dimensions, 0 metrics to query, 10 metrics skipped because they don't have data in the desired time-frame. Aborting it.
2022-11-23 17:44:33: netdata IERR  : WEB_SERVER[static4] : (2848@database/rrdcontext.:query_target_cr): QUERY TARGET: query 'chart://host:potinho/instance:system.cpu/dimensions:*/after:-540/before:0/points:490/group:average/options:nonzero,flip,jsonwrap,ms' does not have all the data required. Matched 1 hosts, 1 contexts, 1 instances, 10 dimensions, 0 metrics to query, 10 metrics skipped because they don't have data in the desired time-frame. Aborting it.
root@hades:/home/thiago/Netdata/go.d.plugin# grep potinho /var/log/netdata/error.log | wc -l
9298
```

#### Child 1
- Host Armv7 
- Connection with TLS (OpenSSL 1.1.1n )
- Memory mode `dbengine`

On this host I am also having these issues:

```sh
2022-11-23 14:44:30: netdata IERR  : STREAM_SENDER[potinho] : (0762@streaming/replicatio:replication_req): STREAM potinho [send to 192.168.1.10:19999]: REPLAY: 'host:potinho/chart:system.clock_sync_state' adding duplicate replication command received (existing from 1669210564 to 1669211164 [false], new from 1669214660 to 1669214670 [false])
2022-11-23 14:44:30: netdata IERR  : STREAM_SENDER[potinho] : (0879@streaming/sender.c  :execute_command): STREAM potinho [send to 192.168.1.10:19999] received command over connection: REPLAY_CHART "system.clock_status" "false" 1669214660 1669214670
2022-11-23 14:44:30: netdata IERR  : STREAM_SENDER[potinho] : (0762@streaming/replicatio:replication_req): STREAM potinho [send to 192.168.1.10:19999]: REPLAY: 'host:potinho/chart:system.clock_status' adding duplicate replication command received (existing from 1669210564 to 1669211164 [false], new from 1669214660 to 1669214670 [false])
2022-11-23 14:44:30: netdata IERR  : STREAM_SENDER[potinho] : (0879@streaming/sender.c  :execute_command): STREAM potinho [send to 192.168.1.10:19999] received command over connection: REPLAY_CHART "system.clock_sync_offset" "false" 1669214660 1669214670
2022-11-23 14:44:30: netdata IERR  : STREAM_SENDER[potinho] : (0762@streaming/replicatio:replication_req): STREAM potinho [send to 192.168.1.10:19999]: REPLAY: 'host:potinho/chart:system.clock_sync_offset' adding duplicate replication command received (existing from 1669210564 to 1669211164 [false], new from 1669214660 to 1669214670 [false])
root@potinho:/home/thiago/Netdata/netdata# grep stream /var/log/netdata/error.log | wc -l
8090
```
#### Child _2
- Host VM x86_64
- TLS (OpenSSL 3.0.7)
- This child is running PR https://github.com/netdata/netdata/pull/14012 for me to be sure I am not missing nothing.
- The streaming is working as expected.


I will continue running tests while I am improving WMI collector, but it looks like that modifications on child side broke streaming with this PR.

**Comment by thiagoftsm** [comment]
I observed that  missed some commits, and I recompile everything on `parent` and on `arm child`, I am still using my PR to test on VM.

The VM is working as expected and parent is showing everything from it, on the other hand with latest commits I cannot have charts completely filled:

Screenshot_20221123_195312

I am bringing the whole [error.log](https://github.com/netdata/netdata/files/10078803/error.log) from arm host to help.

**Comment by ktsaou** [comment]
We found that `dictionary_flush()` was not deleting all items. All these logs are a side effect of this. I added a commit to fix it.

**Review by stelfrag — APPROVED** [review]

**Comment by thiagoftsm** [comment]
Thank you @ktsaou and @stelfrag I could test now and everything is working!

**Pull request merged**
