### PR TITLE
Overhaul deployment strategies documentation

### PR DESCRIPTION
**Pull request by ralphm**
Provide actual deployment strategies, including configuration examples.

### CODE REVIEW

**Comment by ralphm** [comment]
These are the rendered images:

Standalone:
deployment-standalone

Parent:
deployment-parents

Parents:
deployment-parent

**Review by Ancairon — APPROVED** [review]
The links point to `edit`, but I think we have already accounted for this in the ingest

**Comment by ralphm** [comment]
> The links point to `edit`, but I think we have already accounted for this in the ingest

Yeah, for some reason, when I referenced the image directly, it didn't render properly. 
image

**Comment by Ancairon** [comment]
oh, I was talking about the links to the github md files, but either way it is not a problem, if it proves problematic I will make a PR to fix, but it should work.

**Comment by ralphm** [comment]
Ah! I've fixed the references.

**Review by Ancairon — APPROVED** [review]

**Review by andrewm4894 — APPROVED** [review]

**Pull request merged**
