### PR TITLE
SocketService: set socket operation timeout before connecting

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary
Fixes: #5541

This PR:
 - removes `setblocking` calls

```python
    def setblocking(self, v):
        if v:
            self.settimeout(None)
        else:
            self.settimeout(0.0)
```

 - sets socket timeout before call to `connect`

 - adds separate `connect`, `read` and `write` timeouts. Default is 2 seconds for all.

> socket.settimeout(value)
Set a timeout on blocking socket operations. The value argument can be a nonnegative float expressing seconds, or None. If a float is given, subsequent socket operations will raise a timeout exception if the timeout period value has elapsed before the operation has completed. Setting a timeout of None disables timeouts on socket operations. s.settimeout(0.0) is equivalent to s.setblocking(0); s.settimeout(None) is equivalent to s.setblocking(1).

##### Component Name
[`/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/python_modules/bases/FrameworkServices/SocketService.py)

### CODE REVIEW

**Comment by ilyam8** [comment]
@Steve8291 

i think this PR is fixes your problem, please test it!

**Comment by Steve8291** [comment]
@ilyam8 
Here is a new link to the paste if you still want to see it.
https://pastebin.com/hmR40rLz
I don't know why the other one didn't work.
I'm also not sure how to test a pull request. Do I just make the code changes directly or do I have to compile netdata on my machine or something like that? Sorry for my lack of knowledge here.
Looks like the PR was committed into "master" So can I just run an update to get it?

**Comment by ilyam8** [comment]
> Looks like the PR was committed into "master" So can I just run an update to get it?

Yes. 

> connecting socket to "::1", port XXXX

Will hang only for 2 seconds there.

**Comment by Steve8291** [comment]
@ilyam8 
Thanks for fixing this. All my charts are coming up much faster now after a restart or a reload of netdata. I'm currently running: v1.14.0-11-nightly that has the patch applied.

**Comment by ilyam8** [comment]
@Steve8291 it seems you have configured `ip6tables` with `DROP` by default.

**Comment by Steve8291** [comment]
@ilyam8 
I that a problem?
I do have all ipv6table chains set to DROP temporarily until I can get around to writing more specific rules. Is it the OUTPUT Chain that needs set to ACCEPT?

**Comment by ilyam8** [comment]
> I that a problem?

Ye, i suggest to chage default policy to `REJECT` for `INPUT` chain.

**Pull request merged**
