### PR TITLE
fix lack macOS ram info in system-info.sh

### PR DESCRIPTION
**Pull request by weijing24**
##### Summary
Summary
As talked in  https://github.com/netdata/netdata/issues/9868#issuecomment-686231142, fix macOS lack of ram info in the  system-info.sh script.

##### Component Name
daemon/system-info.sh

### CODE REVIEW

**Comment by weijing24** [comment]
This is the first time I've submitted a pr, and even though I've read the guides for pull requests, I'm still afraid that something is wrong, please don't mind it.

**Comment by ilyam8** [comment]
@weijing24 congratulations on the first PR 🎉 

Please sign the CLA!

**Review by Ferroin — APPROVED** [review]
@weijing24 Looks excellent and you appear to have everything you need other than signing the CLA (see the automated comment on this PR from CLAassistant for info on how to do this).

**Comment by weijing24** [comment]
@ilyam8 @Ferroin done

**Review by ilyam8 — APPROVED** [review]

**Comment by Ferroin** [comment]
@weijing24 Thanks for the contribution. This should be in the next release, as well as the nightlies (once we get the issue currently preventing them from being published fixed).

**Pull request merged**
