### PR TITLE
fix installation for ubuntu 14.04

### PR DESCRIPTION
**Pull request by Ehekatl**
##### Summary

Fix installation issue on Ubuntu 14.04 and before

default systemd dir on early ubuntu system is under `/etc/systemd/system`

### CODE REVIEW

**Comment by Ferroin** [comment]
Please fix the conflicts (preferably via a rebase).

**Comment by Ehekatl** [comment]
@prologic @Ferroin rebased

**Comment by prologic** [comment]
@Ehekatl Thanks! LGTM. One quick question though; Would the fix in #7726 also work for you? Its a bit more of a generic solution that also takes cares of systems like CoreOS with a read-only `/lib`.

**Comment by Ehekatl** [comment]
@prologic unfortunately not, on ubuntu 14.04 /lib/systemd dir does exist, but systemd won't load unit file from that directory

**Comment by redfern-cohere** [comment]
On Ubuntu 14.04.6 LTS, ran ./netdata-installer.sh to update existing Netdata. Error result:
checking for uv_fs_scandir_next in -luv... no
configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.
 FAILED
Installed 'libuv-dev' [not 'libuv1-dev' or 'libuv-devel']
Same error.
ran ./netdata-installer.sh --libs-are-really-here
Same error.

**Comment by Ferroin** [comment]
> On Ubuntu 14.04.6 LTS, ran ./netdata-installer.sh to update existing Netdata. Error result:
> checking for uv_fs_scandir_next in -luv... no
> configure: error: libuv required but not found. Try installing 'libuv1-dev' or 'libuv-devel'.
> FAILED
> Installed 'libuv-dev' [not 'libuv1-dev' or 'libuv-devel']
> Same error.
> ran ./netdata-installer.sh --libs-are-really-here
> Same error.

You're going to need to build a local copy of libuv version 1, it's a hard dependency for Netdata, and Ubuntu 14.04 does not have it (this is part of why we stopped publishing packages for 14.04 a while back).

**Comment by prologic** [comment]
@Ehekatl I hope you don't mind but I rebased and resolved conflicts for you and updated this PR.

@Ferroin Can you take another look please?

**Comment by Ferroin** [comment]
> @Ehekatl I hope you don't mind but I rebased and resolved conflicts for you and updated this PR.
> 
> @Ferroin Can you take another look please?

I think you accidentally pulled in some other unrelated commits.

**Comment by prologic** [comment]
> I think you accidentally pulled in some other unrelated commits.

You are right; I accidentally made a small change on my `master` fork and that's how it got in here. But it's merged now so it won't make a difference. Let's merge this :)

**Pull request merged**
