### PR TITLE
Fixes mqtt_websockets on MacOS

### LINKED ISSUE #10842: ACLK-NG Mac OS compatibility
##### Bug report summary

ACLK-NG can't build on Mac OS due to few small issues:
-> `endian.h` missing including necessary functions like `be16toh`
-> use of undeclared identifier 'CLOCK_BOOTTIME'
-> implicit declaration of function 'pipe2' (mac knows only `pipe`)

##### OS / Environment
```
La wonderful fruity OS
```

##### Component Name
ACLK-NG
##### Steps To Reproduce
`netdata-installer --aclk-ng` on Mac OS

##### Expected behavior
It builds and works automagically

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Fixes problems preventing `mqtt_websockets` to be built on MacOS.
Doesnt yet fix all necessary to build ACLK-NG

on m1 if you install SSL with homebrew you might need:
```
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"
```

Fixes #10842 
##### Component Name
`ACLK-NG/mqtt_websockets`
##### Test Plan
Go to mqtt_websockets subfolder and run `make`. If all build dependencies present it should build now (assuming pkg-config can find all necessary deps).

### CODE REVIEW

**Comment by MrZammler** [comment]
Hi Timo! I had a go at this, on an M1 macbook.

On clone of our current master, mqtt did fail with what I remember was originally reported (an error on `endian.h`). I then updated the folder to your latest from https://github.com/underhood/mqtt_websockets and it indeed built ok (but I had to manually specify the location of openssl and libuv includes and libs). 

So this seems to build netdata with aclk-ng `CFLAGS="-O1 -ggdb -DNETDATA_INTERNAL_CHECKS=1 -I /opt/homebrew/include/ -I /opt/homebrew/opt/openssl@1.1/include/" LDFLAGS="-L /opt/homebrew/lib/ -L/opt/homebrew/opt/openssl@1.1/lib/" ./netdata-installer.sh --dont-start-it --disable-lto --dont-wait --aclk-ng --install /Users/mrzammler/stuff/netdata/install_netdata`

I will try to claim the machine to the cloud and let you know, or any other tests you want.

**Comment by MrZammler** [comment]
Good morning! Seems to work fine, claimed to the cloud:

```
2021-05-17 10:18:00: netdata INFO  : ACLK_Main : HTTPS "GET" request to "app.netdata.cloud" finished with HTTP code: 200
2021-05-17 10:18:00: netdata INFO  : ACLK_Main : Getting Cloud /env successful
2021-05-17 10:18:01: netdata INFO  : ACLK_Main : HTTPS "GET" request to "app.netdata.cloud" finished with HTTP code: 200
2021-05-17 10:18:01: netdata INFO  : ACLK_Main : ACLK_OTP Got Challenge from Cloud
2021-05-17 10:18:02: netdata INFO  : ACLK_Main : HTTPS "POST" request to "app.netdata.cloud" finished with HTTP code: 201
2021-05-17 10:18:02: netdata INFO  : ACLK_Main : ACLK_OTP Got Password from Cloud
2021-05-17 10:18:02: netdata INFO  : ACLK_Main : topic dictionary has unknown topic name "agent-connection"
2021-05-17 10:18:02: netdata INFO  : ACLK_Main : topic dictionary has unknown topic name "create-node-instance"
2021-05-17 10:18:02: netdata INFO  : ACLK_Main : topic dictionary has unknown topic name "node-instance-connection"
2021-05-17 10:18:02: netdata INFO  : ACLK_Main : topic dictionary has unknown topic name "inbox-cmd-v2"
2021-05-17 10:18:02: netdata INFO  : ACLK_Main : [mqtt_wss] I: ws_client: Websocket Connection Accepted By Server
2021-05-17 10:18:03: netdata INFO  : ACLK_Main : MQTTWSS connection succeeded
2021-05-17 10:18:03: netdata ERROR : ACLK_Main : ACLK localhost popocorn finished
2021-05-17 10:18:03: netdata INFO  : ACLK_Main : Starting 4 query threads.
2021-05-17 10:18:03: netdata INFO  : ACLK_Query_0 : thread created with task id 717240
2021-05-17 10:18:03: netdata INFO  : ACLK_Query_1 : thread created with task id 717241
2021-05-17 10:18:03: netdata INFO  : ACLK_Query_2 : thread created with task id 717242
2021-05-17 10:18:03: netdata INFO  : ACLK_Query_3 : thread created with task id 717243
2021-05-17 10:18:03: netdata INFO  : ACLK_Query_0 : set name of thread 717240 to ACLK_Query_0
2021-05-17 10:18:03: netdata INFO  : ACLK_Query_1 : set name of thread 717241 to ACLK_Query_1
2021-05-17 10:18:03: netdata INFO  : ACLK_Query_2 : set name of thread 717242 to ACLK_Query_2
2021-05-17 10:18:03: netdata INFO  : ACLK_Query_3 : set name of thread 717243 to ACLK_Query_3
```

**Comment by underhood** [comment]
> Hi Timo! I had a go at this, on an M1 macbook.
> 
> On clone of our current master, mqtt did fail with what I remember was originally reported (an error on `endian.h` among others). I then updated the folder to your latest from https://github.com/underhood/mqtt_websockets and it indeed built ok (but I had to manually specify the location of openssl and libuv includes and libs - but that could be something on my local setup, and has nothing to do with this PR).
> 
> So this seems to build netdata with aclk-ng `CFLAGS="-O1 -ggdb -DNETDATA_INTERNAL_CHECKS=1 -I /opt/homebrew/include/ -I /opt/homebrew/opt/openssl@1.1/include/" LDFLAGS="-L /opt/homebrew/lib/ -L/opt/homebrew/opt/openssl@1.1/lib/" ./netdata-installer.sh --dont-start-it --disable-lto --dont-wait --aclk-ng --install /Users/mrzammler/stuff/netdata/install_netdata`
> 
> I will try to claim the machine to the cloud and let you know, or any other tests you want.

Thank you. Indeed errors with JSON-C and OpenSSL seem to be netdata `autoconf` related and I plan to address them in separate PRs to keep everything clean.

**Comment by underhood** [comment]
@MrZammler one question for the future (so we know the "test coverage") you did the test with successful claiming on Intel or M1 Mac?

**Comment by MrZammler** [comment]
It's on a M1 macbook air!

**Review by MrZammler — APPROVED** [review]

**Review by vkalintiris — APPROVED** [review]
I did not test this on MacOS but the changes LGTM.

**Pull request merged**
