### PR TITLE
Fix not detecting more than one adapter in hpssa collector

### LINKED ISSUE #7575: hpssa collector: no controllers found
I just tried to test the plugin but it doesn't find any controllers:

```
2019-12-18 12:14:47: python.d INFO: hpssa[hpssa] : Command: ['/usr/bin/sudo', '-n', '/usr/sbin/ssacli', 'ctrl', 'all', 'show', 'config', 'detail']
2019-12-18 12:14:51: python.d ERROR: hpssa[hpssa] : Cannot parse line: Smart Array P410i in Slot 0 (Embedded)
2019-12-18 12:14:51: python.d INFO: hpssa[hpssa] : Discovered adapters: []
2019-12-18 12:14:51: python.d ERROR: hpssa[hpssa] : No adapters discovered
2019-12-18 12:14:51: python.d INFO: plugin[main] : hpssa[hpssa] : check failed
```
I have two controllers but none of them seems to be detected:

```
Smart Storage Administrator CLI 3.30.13.0

Smart Array P212 in Slot 5                (sn: PACCPID11170BVJ)
Smart Array P410i in Slot 0 (Embedded)    (sn: 50123456789ABCDE)
```

_Originally posted by @bobatsar in https://github.com/netdata/netdata/pull/7181#issuecomment-567002583_

### PR DESCRIPTION
**Pull request by gnoddep**
##### Summary
Fixes #7575 

##### Component Name
hpssa python plugin

### CODE REVIEW

**Comment by ilyam8** [comment]
thx @gnoddep 

@bobatsar could you test the fix?

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/hpssa/hpssa.chart.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/netdata/netdata/pullRequest?prid=4701077&bid=15708591)

**Comment by bobatsar** [comment]
@ilyam8 I tested it by manually adding the lines to the python.d/hpssa.chart.py in my server as I'm not running directly from github sources.

It's working now. Thanks for the fix.

This plugin has a lot of potential. I think one of the first thing needed is to set alarms if a disk is missing or failing.

**Comment by ilyam8** [comment]
> This plugin has a lot of potential. I think one of the first thing needed is to set alarms if a disk is missing or failing.

True. 

https://github.com/netdata/netdata/pull/7181#issuecomment-552526500

**Comment by ilyam8** [comment]
> This plugin has a lot of potential.

It would be nice if you open an issue with all suggestions. Not asap ofc.

**Pull request merged**
