### PR TITLE
[project management] add github CODEOWNERS

### PR DESCRIPTION
**Pull request by paulfantom**
This will allow to automatically assign people to review code when PR is opened.

@ktsaou please read this before merging: https://help.github.com/articles/about-codeowners/

### CODE REVIEW

**Comment by ktsaou** [comment]
nice!
can you make freebsd and macos files to be owned by @vlvkobal ?

We could extend this a bit. For example, postgres is also owned by @facetoe, and similarly for the rest of the modules.

What do you think? Having code reviews by the people maintain some code would be very nice. I usually invite them by hand to review the PRs...

**Comment by paulfantom** [comment]
From link I sent you:

> The people you choose as code owners must have write permissions for the repository.

Do they have write access?

**Comment by ktsaou** [comment]
hm... then we need to discuss this a bit.
Only me and @philwhineray (maintainer of firehol) have write access to this repo.
I can enable it for the rest of the team, but first we need to discuss it with the team a bit. (my only problem here is that thousands of people auto-update from this repo, so we should probably setup a procedure to keep it stable).

**Comment by paulfantom** [comment]
> I can enable it for the rest of the team, but first we need to discuss it with the team a bit. (my only problem here is that thousands of people auto-update from this repo, so we should probably setup a procedure to keep it stable).

1. Set master branch as "protected"
2. Require at least 2 code reviews before merge to master branch
3. add CODE OWNERS and require a code owner review
4. admins should also be under the same rules

Basically like here:
screenshot_20180908_233039


CC: @l2isbad @Ferroin @ktsaou and I don't know who else

**Comment by paulfantom** [comment]
Oh and by setting this, comment such as https://github.com/firehol/netdata/pull/4095#issuecomment-419670554 won't be needed anymore :smile:

**Comment by philwhineray** [comment]
I couldn't work out from the docs if PRs from individuals in the codeowners are also subject to the 2 review rule? I would imagine not; if so it makes 2 reviews is a *really* high bar to pass.

If not, then it makes good sense: @ktsaou can wait for an independent review of PRs before applying his own review and merging as now, and it allows a controlled expansion of rights for those trusted to maintain particular areas which should distribute the load.

Should the required status checks option also be enabled? I imagine that most people would look at that first but I've had enough trouble with travis to know a fail isn't always a code problem.

**Comment by paulfantom** [comment]
> I couldn't work out from the docs if PRs from individuals in the codeowners are also subject to the 2 review rule?

Code Owners are also subject to this rule.

> it makes 2 reviews is a really high bar to pass.

At first - yes, but in the long run it increases [bus factor](https://en.wikipedia.org/wiki/Bus_factor) by forcing other people to review code. I wouldn't want to create a situation from about 2 years ago, when there was no one with enough knowledge of python framework and @l2isbad had to learn everything by trial and error after I had to abruptly quit.
Same thing goes for C code part, where now only @ktsaou is able do do anything there.
This high bar will force us to learn how netdata internals work. However lowering it to only 1 review approval instead of 2 will cause that we will always need a code owner review and no one else will learn anything and by extension bus factor won't change

> Should the required status checks option also be enabled?

Not yet. Currently CI is used only for build process and I am starting a refactor of this to include tests etc. After this refactor is complete I would advocate on including travis PR status check as mandatory. Also when reviews are enforced github notifies about it in similar way as status checks (example: https://github.com/cloudalchemy/ansible-grafana/pull/95)

**Comment by paulfantom** [comment]
Yes.

**Comment by ktsaou** [comment]
merged!

**Pull request merged**
