### PR TITLE
nvidia_smi: init version added

### PR DESCRIPTION
**Pull request by l2isbad**
##### Summary

Fix: #4357

I couldn't commit to the #4357, maybe because it's [a fork of a fork](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/).

##### Component Name

:snake: nvidia_smi :snake: module

##### Additional Information

Uses `nvidia_smi` tool to collect GPU statistics.

It produces following charts (per GPU):
 * GPU utilization
 * memory allocation
 * memory utilization
 * fan speed
 * power usage
 * temperature
 * clock speed
 * PCI bandwidth

@madhavajay please test it

### CODE REVIEW

**Comment by l2isbad** [comment]
@madhavajay i made some changes, no we have gpu product name as family and N charts per gpu.

Please  take a look, i am waiting for some feedback from you

**Comment by l2isbad** [comment]
@Ferroin please approve

**Comment by madhavajay** [comment]
@l2isbad sorry I was away for the weekend and didnt see this. I will fire it up on one of my instances from the master branch and try it out. Thanks for your help getting this merged.

**Comment by Svenskunganka** [comment]
I seem to be getting an error with this module:

```
2018-12-01 22:49:21: python.d ERROR: nvidia_smi: nvidia_smi: update() unhandled exception: could not convert string to float: N/A
```

It passes the check though:
`2018-12-01 22:48:50: python.d INFO: nvidia_smi: nvidia_smi: check() => [OK]`

Netdata version (latest at the time of writing):
```
Your netdata version: 1.11.1-60-gd8e317b7
Your netdata commit: d8e317b
```

Please don't hesitate to ask if you need me to provide more information or help testing changes.

**Comment by ilyam8** [comment]
just found

> nvidia-smi --query-gpu=name,index,temperature.gpu,utilization.gpu,utilization.memory,memory.total,memory.free,memory.used --format=csv,noheader,nounits 
GeForce GTX 960, 0, 43, 33, 33, 2000, 1192, 808

(current implementation parses xml :smile: )

**Pull request merged**
