### PR TITLE
/api/v2/contexts

### PR DESCRIPTION
**Pull request by ktsaou**
- [x] `/api/v2/contexts` endpoint (NEW)

   This endpoint returns a flattened list of all contexts, across all the nodes hosted on a parent. Chart title and units have been removed (compared to `/api/v1/contexts`) since the new `/api/v2/data` returns this to every data request. It also includes an identification for the agent responding and the list of hosts it includes.

   The scope of this endpoint can be limited with 2 parameters: `scope_hosts` and `scope_contexts`, much like the new `/api/v2/data` endpoint.

- [x] `/api/v2/nodes` endpoint (NEW)

   This endpoint returns the a list of the nodes - work in progress...

- [x] `/api/v2/q` endpoint (NEW)

   This endpoint does a full case-insensitive text search on all metadata maintained on all hosts of a parent. It searches:
   - [x] host names
   - [x] host machine guids
   - [x] host node ids
   - [x] context names
   - [x] context families
   - [x] context units
   - [x] context titles
   - [x] instance ids
   - [x] instance names
   - [x] alert names
   - [x] alert info strings
   - [x] label keys
   - [x] label values
   - [x] label combinations `key:value`
   - [x] dimension ids
   - [x] dimension names

   It returns the same output with `/api/v2/contexts`, with an additional field to indicate what it matched. To optimize for speed, searched is stopped on first match (so it does not go through all the searches when it something matched).

   Its scope can be limited the same way (same parameters) the `/api/v2/contexts` endpoint does.

- [x] `/api/v2/data` endpoint improvements
   - [x] add anomaly rate information to the summary returned (hosts, contexts, instances, dimensions, label keys, label values)
   - [x] group by `sum-count` is now also applied to the summary statistical data, so that the cloud will be able to aggregate such responses from multiple agents / parents.
   - [x] fixed a bug in PR #14564 that was crashing the agent when `/api/v2/data` was called with `format=ssv`
   - [x] the summary statistics returned per node and context are now updated with instances queried and failed

### CODE REVIEW

**Comment by andrewm4894** [comment]
Can we see if some of this can be improved as part of api/v2/data

https://github.com/netdata/netdata/issues/14040#issuecomment-1379046298

I'd like to be able to really simplify this library and just try use one call to api/v2/data instead of lots of async individual calls like it does at moment. https://github.com/netdata/netdata-pandas

**Comment by ktsaou** [comment]
Yes, I think you can do what you look for with `/api/v2/data`. But to be sure, I think you need to explain your case a bit more. Can you give me an example of what you are looking for?

**Comment by andrewm4894** [comment]
The examples in here show what I'm looking for, basically I want to be able to hit data endpoint once to get pretty much any arbitrary combination of charts data in a nice sort of joined csv type result, ideally netdata look after joining the data and handling if charts are of different update every too.

https://github.com/netdata/netdata-pandas#quickstart

**Comment by ktsaou** [comment]
Yes you can do these grouping with `/api/v2/data`. It works like this:

Use `scope_hosts` and `scope_contexts` (simple patterns) to limit the scope of the query to part of the database. It is important to set `scope_contexts`, otherwise every single context will be queried.

Use `group_by=dimension,instance,node,label` (only these 4 are accepted - order is irrelevant - use any combination) and `group_by_label=label1,label2,label3,...` (any combination of labels, or label `key:value`, as simple patterns - order is preserved). Use `aggregation=min|max|average|sum|sum-count` (one of them) to define the aggregation across metrics.

If you select multiple contexts and they have different units, the query will also group by units automatically.

**Comment by andrewm4894** [comment]
Cool, I'll try a few examples and open a GH discussion if have further questions.

**Comment by ktsaou** [comment]
@andrewm4894 `scope_hosts` and `hosts` have been renamed to `scope_nodes` and `nodes`.

**Review by cakrit — APPROVED** [review]
Approved for docs, the contexts/README.md will be unpublished in learn for now.

**Review by stelfrag — DISMISSED** [review]

**Review by stelfrag — APPROVED** [review]

**Pull request merged**
