### PR TITLE
nvidia_smi: power chart algorithm,mul,div fix

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

Fixes: #5939

Power chart algorithm is missed and divisor is used as multiplier.

##### Component Name

[/collectors/python.d.plugin/nvidia_smi](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/nvidia_smi)

### CODE REVIEW

**Comment by ilyam8** [comment]
@legraphista

could you test the fix?

**Comment by ilyam8** [comment]
ok, the bug is fixed, i tested it

**Comment by legraphista** [comment]
Wow, that was fast! I didn't even had time to check my notifications.
I tip my hat to you!

**Comment by cakrit** [comment]
@ilyam8 rocks! :1st_place_medal:

**Pull request merged**
