### PR TITLE
add CONTRIBUGING.md to netdata/netdata

### PR DESCRIPTION
**Pull request by andrewm4894**
##### Summary

It's standard practice to have a CONTRIBUTING.md file. We actually have a pretty good one here that @odyslam and @joelhans 
 made: https://github.com/netdata/.github/blob/main/CONTRIBUTING.md

(maybe we need to just update a little about discord etc perhaps)

Which gets pulled into here: https://learn.netdata.cloud/contribute/

This PR just also adds it to netdata/netdata as some users would expect to just see a CONTRIBUTING.md in there. 

(we actually had a user who did not seem to realise we had one and asking to make one: https://discord.com/channels/847502280503590932/969271064565809212/1029973408726921256)

So the aim of this PR is just to try give it more visibility by putting it next to the code in the repo and potential contributors maybe more likely to find it that way.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by ilyam8** [comment]
@andrewm4894 I think this is the goal of a [default community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) - you don't create it in every repo, but do it once.

> we actually had a user who did not seem to realise we had one and asking to make one

The repo community link is https://github.com/netdata/netdata/community, we have a link to contribute there.

**Comment by ilyam8** [comment]
@andrewm4894 I think some people are not aware about 'orgname/reponame/**community**' page, so just add it to the main readme. I don't think we need to duplicate the contribute.md file.

**Review by ilyam8 — CHANGES_REQUESTED** [review]
- duplicate of https://github.com/netdata/.github/blob/main/CODE_OF_CONDUCT.md
- not needed because we use [default community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
- all links can be found here: https://github.com/netdata/netdata/community

**Comment by andrewm4894** [comment]
ah i see - i was wondering why it was all in special `netdata/.github` repo. 

Plus it is mentioned in the README (although a good bit down: https://github.com/netdata/netdata#contribute)

closing

**Pull request closed without merging**
