### PR TITLE
Use one transaction to initialize dimension metadata.

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

Prior to this PR, we'd execute multiple transactions for each newly created dimension. This PR bundles each SQL statement we need to execute for a new dimension in a single transaction. To support this workflow, we wrap the collect/query ops and lazily initialize the metadata of dimensions in one go the first time a dimension is accessed.

##### Test Plan

- Local & CI builds
- Run & profiled both single node and parent/child setups.

### CODE REVIEW

**Comment by vkalintiris** [comment]
@stelfrag @MrZammler 

I created this draft PR (as part of investigating https://github.com/netdata/product/issues/2719) just so that you can take a look and let me know if you agree with the approach, before spending more time on cleaning up the code, testing all different corner cases, etc.

- The wrappers around the collect/query ops lazily initialize dimensions to sqlite and dbengine.
- There's only one DB transaction.
- When a dimension is initialized so do the rest of the uninitialized dimensions that have been created so far.

**Comment by ktsaou** [comment]
Commenting here to participate in this PR. Ignore this comment.

**Comment by vkalintiris** [comment]
@stelfrag I think this is ready for review. At this point, I'm interested in getting this reviewed. If we agree that the approach is sound, I want to do one/two more sanity tests before merging the PR.

@MrZammler Is it easy to try once more the stress testing that we did for https://github.com/netdata/product/issues/2719 and check if this fixes partially/entirely some of the problems we had?

**Comment by stelfrag** [comment]
Checking...

**Pull request closed without merging**
