### PR TITLE
Msteams 2

### PR DESCRIPTION
**Pull request by tomcbe**
##### Summary

- Change msteam -> msteams (correct naming)
- Fix nonworking adaptive card designer URL
- Remove slack reference in Teams stanza
- Ensure backwards compatability
- Add documentation for Microsoft Teams

This PR replaces https://github.com/netdata/netdata/pull/8666 and resolves the remaining issues.

Closes: #8666 

##### Component Name

- Alarms / config

##### Test Plan

To test I installed netdata in a Ubuntu 18.04 Vagrant VM (`/vagrant` is the path to the netdata git repository inside the VM):

```
cd /vagrant/packaging/installer
./install-required-packages.sh -i netdata
sudo -i
cd /vagrant/
./netdata-installer.sh
```

I then tested if notifications can be sent to Microsoft Teams with the following configurations for `health_alarm_notify.conf` (effective webhook links obscured in the examples below);

1. Old MS Teams variable names:
```
SEND_MSTEAM="YES"
MSTEAM_WEBHOOK_URL="https://outlook.office.com/webhook/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/IncomingWebhook/CHANNEL/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
DEFAULT_RECIPIENT_MSTEAM="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
role_recipients_msteam[sysadmin]="YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
role_recipients_msteam[webmaster]="ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
```
2. New MS Teams variable names:
```
SEND_MSTEAMS="YES"
MSTEAMS_WEBHOOK_URL="https://outlook.office.com/webhook/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/IncomingWebhook/CHANNEL/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
DEFAULT_RECIPIENT_MSTEAMS="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
role_recipients_msteams[sysadmin]="YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
role_recipients_msteams[webmaster]="ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
```

I then executed the following commands for both configurations:
```
su -s /bin/bash netdata
export NETDATA_ALARM_NOTIFY_DEBUG=1
/usr/libexec/netdata/plugins.d/alarm-notify.sh test
/usr/libexec/netdata/plugins.d/alarm-notify.sh test "sysadmin"
/usr/libexec/netdata/plugins.d/alarm-notify.sh test "webmaster"
```

With both configurations all notifications where sent to the expected Teams channel.

### CODE REVIEW

**Comment by tomcbe** [comment]
Hey @ilyam8 

I also have a screenshot of the notifications in Microsoft Teams to add to the documentation, but I'm not sure where I should commit the image. Can you direct me in the right direction?

**Review by prologic — CHANGES_REQUESTED** [review]
Please resolve the CI failures and possibly rebase this?

**Comment by ilyam8** [comment]
@tomcbe i think you post it on github (OP for example) and copy the link to the PR.

**Comment by tomcbe** [comment]
Netdata-MS-Teams-Integration

**Comment by ilyam8** [comment]
@tomcbe try to avoid force-pushes - if you force push there is no way to understand made changes, we need to look through the whole PR again.

**Comment by tomcbe** [comment]
> @tomcbe try to avoid force-pushes - if you force push there is no way to understand made changes, we need to look through the whole PR again.

Oh, sorry, I didn't realize that. I won't do force pushes in the future.

**Comment by ilyam8** [comment]
@tomcbe please add to the OP test plan, what have been done to ensure this PR is working (new msteams works and backward compatibility is not broken)

**Comment by tomcbe** [comment]
@ilyam8 Ok, thanks. The original PR https://github.com/netdata/netdata/pull/8666 didn't include a test plan, but I will add it here.

Are there unit tests for `health/notifications/alarm-notify.sh.in`? If so, I could also add one for MS Teams integration.

**Comment by ilyam8** [comment]
@tomcbe i think there is no unit tests, what i mean is you do some tests manually:
 - msteams notification method works with new parameters
 - msteams notification method works with old parameters (migration code works)

And do a rebease, i see there are conflicts.

**Comment by ilyam8** [comment]
hey @tomcbe any chance you want to finish this PR?

**Comment by tomcbe** [comment]
> hey @tomcbe any chance you want to finish this PR?

@ilyam8  I would very well like to. I started by resolving the merge conflicts. I plan to test my solution next week and update the PR description with the test plan.

Should I rebase and force push before I test or is it ok to resolve the conflicts by merging master into the PR?

**Comment by ilyam8** [comment]
@tomcbe there are no merge conflicts, so we are good.

> I plan to test my solution next week

If we manage to merge https://github.com/netdata/netdata/tree/alerts-changes-notify-attributes by next week we will have some conflicts.

---

>  I plan to test my solution next week and update the PR description with the test plan.

Yeah, that is the only missing part. The code lgtm, i have no suggestions.

**Comment by tomcbe** [comment]
@ilyam8  I'll see if I can free up some time this week to test.

Is there a possibility to preview the rendered documentation for this PR? I would like to verify the documentation during testing as well.

**Comment by ilyam8** [comment]
What documentation? [Readme](https://github.com/docuteam/netdata/tree/msteams-2/health/notifications/msteams#microsoft-teams)?

**Comment by tomcbe** [comment]
Hi @ilyam8 

I found one variable that I missed to rename before (fixed with commit 7c55d9), refined the documentation for Microsoft Teams integration and tested the changes and added the test plan to the PR description.

Could you take another look and let me know if something is missing?

**Review by ilyam8 — APPROVED** [review]

**Comment by ilyam8** [comment]
@tomcbe thanks for the work and for testing the changes 👍

**Review by thiagoftsm — APPROVED** [review]
The code is OK, and I am also moving forward with @tomcbe tests.

**Review by vlvkobal — APPROVED** [review]

**Comment by ilyam8** [comment]
@joelhans please take a look at the docs

**Comment by ilyam8** [comment]
@joelhans merging this PR so we won't have any merge conflicts when [alerts-changes-notify-attributes](https://github.com/netdata/netdata/tree/alerts-changes-notify-attributes) is merged.

**Comment by ilyam8** [comment]
@tomcbe thanks for the contribution!

**Comment by tomcbe** [comment]
@ilyam8 thanks for the help finishing this PR

**Comment by joelhans** [comment]
@ilyam8 Sorry I missed your notification about reviewing the docs. The docs are deploying now with this addition, and I think it looks OK from my previewing, so I think we're all good. I'll take another look once it's deployed to make sure there isn't anything that needs an immediate change.

**Pull request merged**
