### PR TITLE
Fixed broken changelog link

### PR DESCRIPTION
**Pull request by danshilm**
##### Summary
Simple update of the link to the changelog when an update is available. I'm guessing it wasn't updated when the location of the docs was changed.

##### Component Name
Web GUI

### CODE REVIEW

**Comment by OdysLam** [comment]
Although it appears to redirect, so it doesn't any effect to the user experience, thanks of the fix @danshilm  and welcome to our community!

We are also running a community forum at https://community.netdata.cloud

cc @joelhans

**Review by joelhans — APPROVED** [review]
Thanks for the fix, @danshilm! We may need to make this change over in the netdata/dashboard repo as well.

**Comment by danshilm** [comment]
> Although it appears to redirect, so it doesn't any effect to the user experience, thanks of the fix @danshilm and welcome to our community!
> 
> We are also running a community forum at https://community.netdata.cloud
> 
> cc @joelhans

I hadn't tried navigating to the page, but yes, it does indeed redirect when navigating to the page, but not when using the link that shows up on the dashboard when checking for updates. 


> Thanks for the fix, @danshilm! We may need to make this change over in the [netdata/dashboard](https://github.com/netdata/dashboard) repo as well.

Sure, I'll make a PR on the dashboard repo as well.

**Review by jacekkolasa — APPROVED** [review]

**Comment by ilyam8** [comment]
was fixed in https://github.com/netdata/netdata/pull/10586

**Pull request closed without merging**
