### PR TITLE
feat(docker): Add freeipmi support

### PR DESCRIPTION
**Pull request by stevenh**
##### Summary
Add freeipmi support to the docker image.

##### Component Name
docker container (netdata/netdata)

##### Additional Information
Also speed up docker build by copying dependencies instead of installing them, which eliminates the need to install make and alpine-sdk apk only to run make install for judy and then remove them, which takes a good amount of time.

### CODE REVIEW

**Comment by stevenh** [comment]
This requires https://github.com/netdata/helper-images/pull/22 merged first

**Comment by stevenh** [comment]
Any chance someone can look at https://github.com/netdata/helper-images/pull/22?

**Comment by ilyam8** [comment]
@knatsakis @oxplot please take a look guys

**Comment by stevenh** [comment]
Hi guys sorry to chase, but would like to get this in if possible, so we don't have to maintain custom images.

I've just rebased to fix the conflict with the recent permission changes, only change from base was to fix what looked like a merge issue with a joined line in the comment here:
https://github.com/netdata/netdata/blob/master/packaging/docker/Dockerfile#L91

**Comment by cakrit** [comment]
@Ferroin and @prologic plz review.

**Comment by prologic** [comment]
On it!

**Comment by Ferroin** [comment]
> @Ferroin The CI is failing because [netdata/helper-images#22](https://github.com/netdata/helper-images/pull/22) is not yet merged so the CI job can't use the new `/deps/*` that the `netdata/builder` image will have. We should merge that PR ([netdata/helper-images#22](https://github.com/netdata/helper-images/pull/22)) as I've validated it works then re-run the CI on this PR and approve. I'm approving because I'm pretty sure of the above :)

Merged that and retriggered the build, still appears to be failing though: https://travis-ci.com/netdata/netdata/jobs/269600030

**Comment by prologic** [comment]
> Merged that and retriggered the build, still appears to be failing though: https://travis-ci.com/netdata/netdata/jobs/269600030

You're quite right;

```#!sh
00:00:24.126420   ---> Running in bf42222637d6
00:00:24.575194  cp: can't stat '/deps/*': No such file or directory
00:00:24.786323  The command '/bin/sh -c chmod +x netdata-installer.sh &&    cp -rp /deps/* /usr/local/ &&    ./netdata-installer.sh --dont-wait --dont-start-it' returned a non-zero code: 1
The command "packaging/docker/build.sh" exited with 1.
```

But did we allow/verify enough time for the new image for `netdata/base` to be built and published to the Docker Hub before re-triggering this build? That's the only reason I can _think_ of (_unless there's a bug_) that this could happen.

**Comment by stevenh** [comment]
Just pushed a rebased version no changes, hopefully with the delay between this an the merge of netdata/helper-images#22 we should see a clean build

**Comment by stevenh** [comment]
Looks like that did the trick 😄

**Comment by stevenh** [comment]
Thanks for taking the time to get these changes reviewed, tested and merged in guys, appreciated!

**Pull request merged**
