### PR TITLE
Monitor sensors using libsensors via debugfs.plugin

### PR DESCRIPTION
**Pull request by ktsaou**
- [x] use libsensors to collect data
- [x] support all sensor states
- [x] trigger sensor state transitions based on provided thresholds (when the kernel drivers do not provide alarms)
- [x] have libsensors in a git submodule and use this instead of `lm-sensors`
- [x] log sensor transitions with a message id (add it to journal-plugin)
- [x] add the `device` label

---

- [x] install `sensors3.conf` in `/usr/lib/netdata/conf.d/sensors3.conf` (the stock directory)

### CODE REVIEW

**Comment by Ferroin** [comment]
Somewhat cynical take here, but what benefit does this actually get us over the existing functionality in the Go plugin that’s worth dealing with the much more complicated dependency handling for C code?

**Comment by ilyam8** [comment]
@Ferroin go.d.plugin is not IOT friendly (large size binary, not needed there). The reason is to have this collector in the basic kit.

**Comment by Ferroin** [comment]
> @Ferroin go.d.plugin is not IOT friendly (large size binary, not needed there). The reason is to have this collector in the basic kit.

If the entire reason is to not have to pull in a huge binary, then maybe we need to split the Go plugin?

My main worry here is that we’re going to run into compatibility issues and build problems due to needing to support a bunch of different versions of lm_sensors (just like we had issues with in the Python collector at times) when we have no such issues right now. And the argument for IoT usage compounds that, because IoT usage notoriously does not reliably use current, or even remotely recent in some cases, versions of packages.

**Comment by ktsaou** [comment]
libsensors is a tiny little library, suggested by kernel developers to read sensor data:

Read more about it here:
https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface

Also the library is stable for many years. Check the last changed dates:

https://github.com/lm-sensors/lm-sensors/tree/master/lib

So, my suggestion is to vendor it, ie. make it a git submodule in Netdata and ship it without adding any dependencies.

The way this is implemented today in Netdata (in Go) we have the following problems:

1. Netdata does not provide accurate data, ignoring the user-space calculations needed by many chips. Libsensors handles that.
2. Netdata does not support alarm states apart from `alarm`. But there are also `low critical`, `high critical`, `emergency`, `cap`, and `fault`.
3. Netdata needs a heavy plugin to read sensor data, which is a no-go for IoT (and I remind you that we have many users who embed Netdata into routers and other IoT devices).

Implementing this with libsensors is the only right way forward, to provide accurate measurements under all cases.

Btw, I am finished. Currently testing it. Now we need to vendor `libsensors`.

**Comment by ktsaou** [comment]
libsensors is now vendored.

**Comment by ilyam8** [comment]
@Ferroin we need `flex` and `bison` to build libsensors. What do we need update?

**Comment by k0ste** [comment]
> Is there perhaps a chance to optionally NOT vendor lm_sensors?

The same question, can we use the distro version of lib?

BTW, when go.d/sensors collector will be removed, don't forget revert #18067

**Comment by ilyam8** [comment]
@k0ste you can revert https://github.com/netdata/netdata/pull/18067 - go.d/sensors doesn't use `lm-sensors` but sysfs interface (#18581).

**Pull request merged**
