### PR TITLE
Implements new capability fields in aclk_schemas

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Implements the new `capability` fields of `aclk_schemas`.

Implement #12482

##### Test Plan
Check generated messages

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>

```
Describe the PR affects users: 
- Which area of Netdata is affected by the change?
  ACLK, Agent/Cloud protocol
- Can they see the change or is it an under the hood? If they can see it, where?
  It is under the hood change made by underhood
- How is the user impacted by the change? 
  No direct impact but is necessary prerequisite for some future features.
```
</details>

### CODE REVIEW

**Comment by MrZammler** [comment]
Hi Timo! Should we go ahead and review/merge this? Is the cloud ready, or is it safe to merge on our side? Should we do any cloud tests before merge?

**Comment by underhood** [comment]
Well it was agreed between cloud and agent to use this mechanism so IMHO we should use it

**Comment by MrZammler** [comment]
Ok, tests seem ok. Both `UpdateNodeInfo` and `UpdateAgentConnection` contain the capabilities fields, e.g:

<details> <summary>UpdateAgentConnection</summary>

```
{
         "claimId" => "bf9d3e10-38ae-4d32-a178-ec15d05b76b0",
       "reachable" => true,
       "sessionId" => "1652345262857363",
    "updateSource" => "CONNECTION_UPDATE_SOURCE_AGENT",
       "updatedAt" => "2022-05-12T08:47:43.615322Z",
    "capabilities" => [
        [0] {
               "name" => "json",
            "version" => 2
        },
        [1] {
               "name" => "proto",
            "version" => 1,
            "enabled" => true
        },
        [2] {
               "name" => "ml",
            "version" => 1
        }
    ]
}
```

</details>

<details> <summary>UpdateNodeInfo</summary>

```
{
              "nodeId" => "0c843d3f-d71e-4601-9f07-6fbec014517e",
             "claimId" => "bf9d3e10-38ae-4d32-a178-ec15d05b76b0",
                "data" => {
                      "name" => "6am",
                        "os" => "linux",
                    "osName" => "Gentoo",
                 "osVersion" => "unknown",
                "kernelName" => "Linux",
             "kernelVersion" => "5.15.32-gentoo-r1",
              "architecture" => "x86_64",
                      "cpus" => 6,
              "cpuFrequency" => "2375000000",
                    "memory" => "7793315840",
                 "diskSpace" => "512110190592",
                   "version" => "v1.33.1-281-gc608449a8",
            "releaseChannel" => "nightly",
                  "timezone" => "EEST",
        "virtualizationType" => "none",
             "containerType" => "unknown",
               "machineGuid" => "bf9d3e10-38ae-4d32-a178-ec15d05b76b0",
                "hostLabels" => {
                   "_container_detection" => "none",
                     "_aclk_ng_available" => "true",
            "_aclk_ng_new_cloud_protocol" => "true",
                             "_aclk_impl" => "Next Generation",
                            "_os_version" => "unknown",
                     "_system_disk_space" => "512110190592",
                          "_system_cores" => "6",
                             "_container" => "unknown",
                            "_aclk_proxy" => "none",
                          "_architecture" => "x86_64",
                        "_kernel_version" => "5.15.32-gentoo-r1",
                        "_virt_detection" => "none",
                      "_system_ram_total" => "7793315840",
                             "_is_parent" => "false",
                          "_install_type" => "custom",
                               "_os_name" => "Gentoo",
                       "_system_cpu_freq" => "2375000000",
                 "_aclk_legacy_available" => "false",
                           "_is_k8s_node" => "false",
                        "_virtualization" => "none"
        },
                    "mlInfo" => {
            "mlCapable" => true
        }
    },
           "updatedAt" => "2022-05-12T08:47:47.604933Z",
         "machineGuid" => "bf9d3e10-38ae-4d32-a178-ec15d05b76b0",
              "mlInfo" => {
        "mlCapable" => true
    },
            "nodeInfo" => {
        "capabilities" => [
            [0] {
                   "name" => "ml",
                "version" => 1
            }
        ]
    },
    "nodeInstanceInfo" => {
        "capabilities" => [
            [0] {
                   "name" => "proto",
                "version" => 1,
                "enabled" => true
            },
            [1] {
                   "name" => "ml",
                "version" => 1
            }
        ]
    }
}


```</details>

**Review by MrZammler — APPROVED** [review]
Well, apart from not forgetting to add a new capability to both places which is really not a problem, looks good!

**Review by stelfrag — APPROVED** [review]

**Pull request merged**
