### PR TITLE
Add Debian 11 (Bullseye) to CI.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

Released on 2021-08-14.

This also includes some fixes and cleanup of the package building CI that were done as part of getting Debian 11 DEB package builds working.

##### Component Name

area/ci
area/packaging

##### Test Plan

CI checks pass on this PR.

##### Additional Information

Fixes: #8882

### CODE REVIEW

**Comment by Ferroin** [comment]
Needs https://github.com/netdata/helper-images/pull/126 merged.

**Comment by Ferroin** [comment]
Now blocked waiting on https://github.com/netdata/helper-images/pull/127.

**Comment by Ferroin** [comment]
Closing and reopening to hopefully kick the CI into working properly.

**Comment by Ferroin** [comment]
Ubuntu 16.04 package build failures are orthogonal to this PR and will be fixed by https://github.com/netdata/helper-images/pull/129.

The i386 Debian 11 package build failures are due to caching problems with GHA that we cannot do anything about, but _should_ resolve themselves when this gets merged.

**Review by kaskavel — APPROVED** [review]

**Pull request merged**
