### PR TITLE
Brings pattern to code

### LINKED ISSUE #7863: API info has two patterns in the code.
##### Bug report summary
After we merge the PRs that brought containers to `web/api`, it would be good to have only one pattern for the code.

##### OS / Environment
```
/etc/os-release:NAME=Slackware
/etc/os-release:VERSION="14.2"
/etc/os-release:ID=slackware
/etc/os-release:VERSION_ID=14.2
/etc/os-release:PRETTY_NAME="Slackware 14.2 x86_64 (post 14.2 -current)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:CPE_NAME="cpe:/o:slackware:slackware_linux:14.2"
/etc/os-release:HOME_URL="http://slackware.com/"
/etc/os-release:SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
/etc/os-release:VERSION_CODENAME=current
```

##### Component Name
Web
##### Steps To Reproduce

1. Read the code

##### Expected behavior
To have the same number of elements in the response, independent of what is running on the host.

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes #7863 

Brings back one unique pattern to the code and to response. I am considering that is better to have always the same number of variables as the response, and the previous code was not allowing us to have this.
##### Component Name
web

### CODE REVIEW

**Comment by underhood** [comment]
please update desc. this changes also that variables will be in json with empty values instead of just skippping them

**Comment by thiagoftsm** [comment]
> please update desc. this changes also that variables will be in json with empty values instead of just skippping them

I updated it, thank you!

**Comment by amoss** [comment]
These were intended to be optional fields - i.e. if we are not in a container then they would not be added to the response.

**Comment by thiagoftsm** [comment]
> These were intended to be optional fields - i.e. if we are not in a container then they would not be added to the response.

All right, so I will close the PR. Thank you for the explanation.
@underhood I apologize for the time you expended here.

**Comment by underhood** [comment]
no problem it was very small PR so it was just few minutes anyway

**Comment by amoss** [comment]
> All right, so I will close the PR. Thank you for the explanation.

That's fine - I can explain in advance as well :)

There are two things here which might be slightly wrong, but are not worth spending the time to fix immediately:
1. Although these fields were intended to be optional, there was a later change that filled in default values for the GA reporting. This may have caused them to stop being optional.
2. The existing pattern in the source code violates the coding style (line width) and needs to be reformatted at some point.

**Pull request closed without merging**
