### PR TITLE
Update netdata-overview.xml

### PR DESCRIPTION
**Pull request by andrewm4894**
##### Summary

- fixes https://github.com/netdata/netdata/issues/14192.
- replace "my-netdata.io" with "netdata.cloud".
- standardize arrow and box colors.
- add ML Engine box next to query engine.

can be previewed [here](https://viewer.diagrams.net/index.html?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=netdata-overview.xml#Uhttps%3A%2F%2Fraw.githubusercontent.com%2Fandrewm4894%2Fnetdata%2Fupdate-infographic%2Fdiagrams%2Fnetdata-overview.xml)

image

### CODE REVIEW

**Comment by andrewm4894** [comment]
I have updated this to fix the broken links and so a small bit of cleaning up of the crazy colors from before. 

I propose to merge this and this will at least fix the bug. 

Weather we completely change all this and retire `diagrams/` is a different discussion we can and should have separately.

**Comment by andrewm4894** [comment]
converting to draft while i add some ml awareness

**Review by cakrit — COMMENTED** [review]
It doesn't fix all the broken links. I randomly clicked on nginx (dead link to obsolete python module) and on ntp which has also been migrated to go. 

To consider the reported issue fixed, we should verify that at least the ones we show do have accurate links, though I've already expressed my opposition to listing integrations this way.

**Comment by cakrit** [comment]
I'm approving anyway and will completely remove those logos once the new website with the integrations is launched.

**Comment by cakrit** [comment]
Actually, no reason to wait, merge it and I'll do something to replace all the individual logos with an image with a link to www.netdata.cloud/integrations

**Comment by andrewm4894** [comment]
looks like i need two approvers - will ask. 

@cakrit in meantime you could just copy paste this into same file in your fork: https://raw.githubusercontent.com/andrewm4894/netdata/master/diagrams/netdata-overview.xml

and you'd be in sync with this.

**Review by ilyam8 — APPROVED** [review]

**Pull request merged**
