### PR TITLE
Suppress H2O compilation warnings

### PR DESCRIPTION
**Pull request by stelfrag**
##### Summary
Suppress H2O compilation warnings

### CODE REVIEW

**Review by MrZammler — APPROVED** [review]

**Review by underhood — APPROVED** [review]

**Comment by underhood** [comment]
not sure it comes from this yet but i get a lot of:
```
cc1plus: warning: command-line option '-Wno-old-style-declaration' is valid for C/ObjC but not for C++
  CXX      aclk/schema-wrappers/node_info.o
cc1plus: warning: command-line option '-Wno-old-style-declaration' is valid for C/ObjC but not for C++
  CXX      aclk/schema-wrappers/capability.o
cc1plus: warning: command-line option '-Wno-old-style-declaration' is valid for C/ObjC but not
```

**Review by underhood — CHANGES_REQUESTED** [review]
lot of:
```
cc1plus: warning: command-line option '-Wno-old-style-declaration' is valid for C/ObjC but not for C++
  CXX      aclk/schema-wrappers/node_info.o
cc1plus: warning: command-line option '-Wno-old-style-declaration' is valid for C/ObjC but not for C++
  CXX      aclk/schema-wrappers/capability.o
cc1plus: warning: command-line option '-Wno-old-style-declaration' is valid for C/ObjC but not
```

**Comment by underhood** [comment]
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/12/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-libstdcxx-backtrace --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-12.2.1-20221121/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-offload-defaulted --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.1 20221121 (Red Hat 12.2.1-4) (GCC) 
```

**Review by MrZammler — APPROVED** [review]

**Comment by stelfrag** [comment]
@underhood can you please recheck

**Pull request merged**
