### PR TITLE
Add |nowarn and |noclear notification modifiers

### PR DESCRIPTION
**Pull request by vobruba-martin**
##### Summary

Currently, if you use `|critical` modifier, you always get at least 2 notifications: critical and clear. There is no way how to stop sending clear/warning notifications afterwards.

This patch adds two more modifiers:
 `|nowarn`  = Do not send warning notifications
 `|noclear` = Do not send clear notifications

##### Test Plan

Edit your notification settings in `health_alarm_notify.conf` and check this:
1. `recipient` (no modifier set) - Receive all notifications
2. `recipient|critical` - Same as before. You receive critical notifications and following status changes.
3. `recipient|critical|noclear` - You receive critical notifications and following status changes except clear notifications.
4. `recipient|critical|nowarn` - You receive critical notifications and following status changes except warning notifications.
5. `recipient|critical|nowarn|noclear` or `recipient|nowarn|noclear` - You receive critical notifications only.
6. `recipient|noclear` - Receive all notifications except clears.
7. `recipient|nowarn` - Receive all notifications except warnings.

##### Additional Information

I use paid SMS notifications and this patch helps me to save at least 50 % of money because now I'm able to define that I want critical notifications only.

<details> <summary>For users: How does this change affect me?</summary>
  
No change.
</details>

### CODE REVIEW

**Comment by Ferroin** [comment]
From a cursory look at the changes, everything looks good here. I’ll try to get to testing later today.

---

Irrespective of the testing and code review, I think this is an absolutely brilliant idea, thanks for the PR @vobruba-martin.

**Review by Ferroin — APPROVED** [review]
Code looks good and everything appears to work as the documentation suggests it should.

**Review by thiagoftsm — APPROVED** [review]
Thank you very much @vobruba-martin, everything is working as expected!

**Comment by vobruba-martin** [comment]
Thank you @Ferroin and @thiagoftsm for your time. Cheers!

**Pull request merged**
