### PR TITLE
Fix systemd chart update (eBPF)

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
This PR fix:

```sh
2022-10-23 03:18:30: netdata ERROR : PLUGINSD[ebpf] : (0258@collectors/plugins.d:pluginsd_dimens): requested a DIMENSION, without a CHART, on host 'box'. Disabling it.
2022-10-23 03:18:30: netdata IERR  : PLUGINSD[ebpf] : (0337@parser/parser.c     :parser_action  ): action_function() failed with rc = 2
2022-10-23 03:18:30: netdata IERR  : PLUGINSD[ebpf] : (0348@parser/parser.c     :parser_action  ): parser_action() failed.
2022-10-23 03:18:30: netdata ERROR : PLUGINSD[ebpf] : (0133@collectors/plugins.d:pluginsd_worker): '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 21184) disconnected after 59773 successful data collections (ENDs).
2022-10-23 03:18:34: netdata ERROR : PLUGINSD[ebpf] : (0412@libnetdata/popen/pop:netdata_pclose ): child pid 21184 exited with code 15.
2022-10-23 03:18:34: netdata ERROR : PLUGINSD[ebpf] : (0091@collectors/plugins.d:pluginsd_worker): '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 21184) exited with error code 15, but has given useful output in the past (59773 times). Will not start it again - it is disabled.
2022-10-23 03:18:44: netdata INFO  : PLUGINSD[ebpf] : (0120@libnetdata/threads/t:thread_cleanup ): thread with task id 21167 finished
```

When a service was starting after eBPF plugin is running, it was not recreating properly the dimensions and this could create previous error. This PR is fixing this.

##### Test Plan
I am really sorry for this, but you will need to use `systemd` to test the PR. :smile: 

1. Compile this PR on an environment with `systemd`. I suggest to compile with flag `-DNETDATA_DEV_MODE=1`.
2. Be sure that integration between `eBPF` and `cgroup` inside your `/etc/netdata/ebpf.d.conf`:
```sh
[global]
    apps = yes
    cgroups = yes
```
3. Start netdata.
4. Wait at least 2 minutes and stop a service. 
5. Now start the service again, and wait few minutes.  
6. After these steps the plugin should not stop anymore.
##### Additional Information
It is not necessary to test on different kernels.

A quick update, I ran this PR during 10 hours without any issue. I was not able to run too long with current master on Arch Linux.

<details> <summary>For users: How does this change affect me?</summary>
Describe the PR affects users: 
- Which area of Netdata is affected by the change? eBPF.plugin
- Can they see the change or is it an under the hood? If they can see it, where? Yes, the plugin won't fail when a service is stopped.
- How is the user impacted by the change?  A better plugin
- What are there any benefits of the change? eBPF will monitor systemd without issues.
</details>

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @MrZammler ,

Are you running `netdata`/`eBPF.plugin' as root or do you have special permissions like this:
```sh
root@hades:/home/thiago/Netdata/netdata# ls -l /usr/libexec/netdata/plugins.d/ebpf.plugin 
-rwsr-x--- 1 root netdata 3298016 Oct 26 01:29 /usr/libexec/netdata/plugins.d/ebpf.plugin*

```
?

The error `: Setrlimit(RLIMIT_MEMLOCK) (errno 1, Operation not permitted)` means that on your system the process did not have permissions to adjust is own memory limit.

Best regards!

**Comment by MrZammler** [comment]
As far as I see, yes, it should be running as root (e.g. apps.plugin does).

```
ls -l /usr/libexec/netdata/plugins.d/ebpf.plugin 
-rwsr-x--- 1 root netdata 3376352 Oct 26 09:00 /usr/libexec/netdata/plugins.d/ebpf.plugin
```

**Comment by MrZammler** [comment]
> Do you start netdata using `sudo`? thinking , If yes, probably you need to do [this](https://unix.stackexchange.com/questions/578949/sudo-setrlimitrlimit-core-operation-not-permitted)

Thanks! I'm starting from the systemd service :thinking: ok let me check a bit and will let you know. Will check on the same system current master to see if it behaves the same.

**Comment by MrZammler** [comment]
Yes, happens on build from master and the package, so something system related. I'll dig a bit into it if I can find something.

**Comment by MrZammler** [comment]
Most likely appears to be a problem with the container I was using to test. Sorry to bother, will test on another VM!

**Comment by thiagoftsm** [comment]
No problem @MrZammler I am happy you could discover. I was thinking that you run direct on a host.

**Review by MrZammler — APPROVED** [review]
Tested with stopping, starting cron via systemd, charts appear to behave correctly, no errors in log!

**Comment by Dim-P** [comment]
Hey @thiagoftsm . When testing on `Ubuntu 22.04.1 LTS (Jammy Jellyfish)` (having `cgroups = yes`), I am seeing the following crash:
```
2022-10-31 18:24:48: netdata ERROR : PLUGIN[proc netdev] : (1023@collectors/proc.plug:do_proc_net_dev): Cannot refresh interface wlo1 speed by reading '/sys/class/net/wlo1/speed'. (errno 22, Invalid argument)
2022-10-31 18:24:50: netdata ERROR : PLUGIN[proc netdev] : (1023@collectors/proc.plug:do_proc_net_dev): Cannot refresh interface wlo1 speed by reading '/sys/class/net/wlo1/speed'. (errno 22, Invalid argument)
2022-10-31 18:24:52: netdata ERROR : PLUGIN[proc netdev] : (1023@collectors/proc.plug:do_proc_net_dev): Cannot refresh interface wlo1 speed by reading '/sys/class/net/wlo1/speed'. (errno 22, Invalid argument)
2022-10-31 18:24:54: netdata ERROR : PLUGIN[proc netdev] : (1023@collectors/proc.plug:do_proc_net_dev): Cannot refresh interface wlo1 speed by reading '/sys/class/net/wlo1/speed'. (errno 22, Invalid argument)
2022-10-31 18:24:56: netdata ERROR : PLUGIN[proc netdev] : (1023@collectors/proc.plug:do_proc_net_dev): Cannot refresh interface wlo1 speed by reading '/sys/class/net/wlo1/speed'. (errno 22, Invalid argument)
=================================================================
==63883==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x603000012190 in thread T1
2022-10-31 18:24:58: netdata ERROR : PLUGIN[proc netdev] : (1023@collectors/proc.plug:do_proc_net_dev): Cannot refresh interface wlo1 speed by reading '/sys/class/net/wlo1/speed'. (errno 22, Invalid argument)
    #0 0x5583898ed847 in __interceptor_free (/usr/libexec/netdata/plugins.d/ebpf.plugin+0xdc847)
    #1 0x5583899c6a59 in freez libnetdata/libnetdata.c:406
    #2 0x55838998bde9 in cleanup_variables_from_other_threads collectors/ebpf.plugin/ebpf_apps.c:978
    #3 0x55838998caa7 in collect_data_for_all_processes collectors/ebpf.plugin/ebpf_apps.c:1134
    #4 0x55838995b5ce in process_collector collectors/ebpf.plugin/ebpf_process.c:1143
    #5 0x55838995bc4b in ebpf_process_thread collectors/ebpf.plugin/ebpf_process.c:1353
    #6 0x5583899ee15d in thread_start libnetdata/threads/threads.c:203
    #7 0x7fca6bbafb42 in start_thread nptl/pthread_create.c:442
    #8 0x7fca6bc419ff  (/lib/x86_64-linux-gnu/libc.so.6+0x1269ff)

0x603000012190 is located 16 bytes to the right of 32-byte region [0x603000012160,0x603000012180)
allocated by thread T11 here:
    #0 0x5583898edd67 in __interceptor_calloc (/usr/libexec/netdata/plugins.d/ebpf.plugin+0xdcd67)
    #1 0x5583899c6b07 in callocz libnetdata/libnetdata.c:416
    #2 0x558389949c94 in ebpf_fd_allocate_global_vectors collectors/ebpf.plugin/ebpf_fd.c:1093
    #3 0x55838994c39b in ebpf_fd_thread collectors/ebpf.plugin/ebpf_fd.c:1155
    #4 0x5583899ee15d in thread_start libnetdata/threads/threads.c:203
    #5 0x7fca6bbafb42 in start_thread nptl/pthread_create.c:442

Thread T1 created by T0 here:
    #0 0x5583898919d5 in pthread_create (/usr/libexec/netdata/plugins.d/ebpf.plugin+0x809d5)
    #1 0x5583899ee7b8 in netdata_thread_create libnetdata/threads/threads.c:217
    #2 0x55838993940f in main collectors/ebpf.plugin/ebpf.c:2203
    #3 0x7fca6bb44d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Thread T11 created by T0 here:
    #0 0x5583898919d5 in pthread_create (/usr/libexec/netdata/plugins.d/ebpf.plugin+0x809d5)
    #1 0x5583899ee7b8 in netdata_thread_create libnetdata/threads/threads.c:217
    #2 0x55838993940f in main collectors/ebpf.plugin/ebpf.c:2203
    #3 0x7fca6bb44d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: bad-free (/usr/libexec/netdata/plugins.d/ebpf.plugin+0xdc847) in __interceptor_free
==63883==ABORTING
2022-10-31 18:24:59: netdata ERROR : PLUGINSD[ebpf] : (0228@parser/parser.c     :parser_next    ): read failed: end of file (errno 9, Bad file descriptor)
2022-10-31 18:24:59: netdata ERROR : PLUGINSD[ebpf] : (0133@collectors/plugins.d:pluginsd_worker): '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 63883) disconnected after 146 successful data collections (ENDs).
2022-10-31 18:25:00: netdata ERROR : PLUGINSD[ebpf] : (0412@libnetdata/popen/pop:netdata_pclose ): child pid 63883 exited with code 1.
2022-10-31 18:25:00: netdata ERROR : PLUGINSD[ebpf] : (0091@collectors/plugins.d:pluginsd_worker): '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 63883) exited with error code 1, but has given useful output in the past (2868 times). Waiting a bit before starting it again.
```

I am installing with:
```
sudo CFLAGS="-Og -ggdb -Wall -Wextra -fsanitize=address -static-libasan -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -DNETDATA_DEV_MODE=1 -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1 -Wformat-truncation=2 -Wunused-result" ./netdata-installer.sh --dont-wait --disable-telemetry --disable-cloud --disable-ml --disable-go --disable-lto --use-system-protobuf
```

**Comment by thiagoftsm** [comment]
Hello @Dim-P ,

Thanks for your report. This issue is not related with this PR, I will try to recreate it. Is this happening when you stop netdata?

Best regards!

**Comment by Dim-P** [comment]
> Hello @Dim-P ,
> 
> Thanks for your report. This issue is not related with this PR, I will try to recreate it. Is this happening when you stop netdata?
> 
> Best regards!

No, it's happening a little while after I restart the Netdata service.

**Review by Dim-P — APPROVED** [review]
Could not reproduce the crash that this PR fixes (on Ubuntu 22.04 with systemd), but I am approving it since I tested it and eBPF works fine (so that it goes into the next release if merged in time).

**Pull request merged**
