### PR TITLE
health: make alarms less sensitive

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

Fixes: #10687

The goal of this PR is to adapt our ~top noisy system alarms to general cases:
 - relax trigger conditions.
 - remove `crit` level if the event is not really critical for a system.

Working on this i realized that `warn` and `crit` levels require you to be really careful and doesn't allow to notify about some events you want to notify - using `warn` level for them makes Netdata health kind of annoying and noisy and, as a result, you stop pay attention to all those warnings - having `notice` level would be nice!

| Alarm       | Change      | Reason      |
| ----------- | ----------- | ----------- |
| [used_file_descriptors](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/apps_plugin.conf#L5-L15)      | Removed       | Cleanup. Was commented out.             |
| [bcache_cache_errors](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/bcache.conf#L2-L11)   | Tuned `lookup`, added `delay up`        | Not errors, but read races. Not harmful. Meaning is number of times data was being read from the cache, the bucket was reused and invalidated => increase read races counter, reread data. ❗ **The metric doesn't look useful, the alarm could be deleted**...  |
| [cluster_space_usage](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/ceph.conf#L3-L12)      | Changed calculation from avail to used, tune `every`       | Kind of cleanup. Make it consistent with other disk usage alarms.             |
| [out_of_disk_space_time](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/disks.conf#L68-L80)      | Commented out       | High chance to be false positive (netowrks and disks are fast these days, making assumption based on write rate (if that write rate last for N hours...) seems not good **in general**). Disk purpose is to store data. **If there is enough space we are ok**. We have `disk_space_usage` alarm. ❗ Not removed, so users can use it as an example.  |
| [out_of_disk_inodes_time](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/disks.conf#L109-L121)      | Commented out       | Same arguments as above. We have `disk_inode_usage` alarm. ❗ Not removed, so users can use it as an example. |
| [10min_disk_utilization](https://github.com/netdata/netdata/blob/51b57dc0a5997cc8203ede0a7e67884c0ef72a34/health/health.d/disks.conf#L131-L145)      | Changed `to` to `silent`       | If this is 100%, it doesn’t always mean that the device is saturated. Depends on a number of oustanding requests and the number of concurrent requests the device can handle. For instance, if the device is able to handle 8 concurrent requests and there are 2 we would see 100% untilization, but there is no problem at all.
| [10min_disk_backlog](https://github.com/netdata/netdata/blob/51b57dc0a5997cc8203ede0a7e67884c0ef72a34/health/health.d/disks.conf#L153-L167)      | Changed `to` to `silent`       | This one is tricky. I am not sure we can use the value as it is for the alarm with hardcoded trigger limits. Looks like a high chance to be false positive in general. I find that this metric is being used (`aqu-sz` iostat) to calculate average queue length (num of operations waiting to be serviced), which gives a better representation of the backlog. |
| [netfilter_last_collected_secs](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/netfilter.conf#L4-L15)      | Removed       | No reason to track this specific internal data collector availability. The alarm is up if there are problem with data collection in general (gaps).   |
| [netfilter_conntrack_full](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/netfilter.conf#L17-L29)      | Tuned warn/crit trigger limits.       | Just common sense. Less criticals, more warnings.    |
| [30min_ram_swapped_out](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/swap.conf#L4-L17)      | Removed `crit`, tuned `warn` trigger limits       | Not a critical event in general. |
| [ram_in_swap](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/swap.conf#L19-L30)      | Removed `crit`, tuned `warn` trigger limits       | Not a critical event in general. Perhaps not even `warn`, but we have no `notice` 😞 |
| [ipv4_tcphandshake_last_collected_secs](https://github.com/netdata/netdata/blob/db9db41bc8a3234b24f1468cd7172b719505cfa0/health/health.d/tcp_resets.conf#L6-L17)      | Removed       | No reason to track this specific internal data collector availability. The alarm is up if there are problem with data collection in general (gaps).  |
| [ipv4_udperrors_last_collected_secs](https://github.com/netdata/netdata/blob/51b57dc0a5997cc8203ede0a7e67884c0ef72a34/health/health.d/udp_errors.conf#L6-L17)      | Removed       | No reason to track this specific internal data collector availability. The alarm is up if there are problem with data collection in general (gaps).  |
| [1m_ipv4_udp_receive_buffer_errors](https://github.com/netdata/netdata/blob/51b57dc0a5997cc8203ede0a7e67884c0ef72a34/health/health.d/udp_errors.conf#L22-L33)      | Removed `crit`, tuned `warn` trigger limits       |  Not a critical event in general.  |
| [1m_ipv4_udp_send_buffer_errors](https://github.com/netdata/netdata/blob/51b57dc0a5997cc8203ede0a7e67884c0ef72a34/health/health.d/udp_errors.conf#L38-L49)      | Removed `crit`, tuned `warn` trigger limits       |  Not a critical event in general.  |
| [1m_ipv4_udp_send_buffer_errors](https://github.com/netdata/netdata/blob/51b57dc0a5997cc8203ede0a7e67884c0ef72a34/health/health.d/udp_errors.conf#L38-L49)      | Removed `crit`, tuned `warn` trigger limits       |  Not a critical event in general.  |
| [load_average_15](https://github.com/netdata/netdata/blob/43ba84b4ef3f1a602e79fbcd9d31748d9868a530/health/health.d/load.conf#L19-L30)      | Removed `crit`      |  Not a critical event in general. It doesn't reflect current state, but a state in the past (15+ minutes before)  |
| [load_average_5](https://github.com/netdata/netdata/blob/43ba84b4ef3f1a602e79fbcd9d31748d9868a530/health/health.d/load.conf#L32-L43)      | Removed `crit`      |  Not a critical event in general. ❗ Our current logic is  we don't care about `load5` until it is high (4 * normal/expected), we care about `load15` |
| [load_average_1](https://github.com/netdata/netdata/blob/43ba84b4ef3f1a602e79fbcd9d31748d9868a530/health/health.d/load.conf#L45-L56)      | Removed `crit`      |  Not a critical event in general. ❗ Our current logic is  we don't care about `load1` until it is high (8 * normal/expected), we care about `load15`  |

---

##### Component Name

`health/`

##### Test Plan

- [x] install this PR, ensure there is no syntax errors and all alarms are loaded and working.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
@ilyam8 thanks `eBPF` I have serious problems with [this alarm](https://github.com/netdata/netdata/issues/10687#issuecomment-786100090) and I saw you did not touch it. Another way to have this alarm raising so much alarms in a short period of time is to multiply a a matrix 1000 x 1000. Why did you not consider it? :thinking:

**Comment by ilyam8** [comment]
@thiagoftsm what alarm are you referring to? The link redirects to your post.

**Review by vlvkobal — DISMISSED** [review]

**Comment by thiagoftsm** [comment]
> @thiagoftsm what alarm are you referring to? The link redirects to your post.

It was related with number of alarms, but we already clarify in our meeting.

**Review by thiagoftsm — APPROVED** [review]

**Comment by ilyam8** [comment]
Related https://community.netdata.cloud/t/slack-notification-is-recurring/1028/6?u=ilyam8

Noticed that those 2 alarms are very strict, warn >1, (!) crit > 5.
- `1m_tcp_accept_queue_drops` 
- `1m_tcp_syn_queue_cookies`

They are not top active (reason why we dont change them in this PR), but definitely deserve some attention @vlvkobal

**Review by vlvkobal — APPROVED** [review]

**Pull request merged**
