### PR TITLE
Ebpf btrfs

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
I am waiting for https://github.com/netdata/kernel-collector/pull/243 to be merged before to give instructions to test.

##### Component Name
ebpf.plugin
##### Test Plan
1 - Format a partition with ` mkfs.btrfs` to create a `btrfs` partition
2 - Mount your new partition
3 - Configure your `/etc/netdata/ebpf.d.conf`:

```conf
[ebpf programs]
     filesystem = yes
```

You do not need to to configure `/etc/netdata/ebpf.d/filesystem.conf`, because all filesystem by default are monitored.

4 - Compile this branch
5 - Copy data to directory you mount file system and edit them. This will be enough to generate data for all charts.

##### Additional Information
This PR was tested on:

| Linux Distribution | kernel version |
|-------------------|----------------|
| Slackware Current | 5.13.2  |
| Manajaro | 5.10.49 |
| Ubuntu 18.04 | 5.4.119 |
| Debian 10.10 | 4.19.171 |
| Ubuntu 18.04 | 4.15.18 |
| Slackware Current | 4.14.239 |

### CODE REVIEW

**Review by UmanShahzad — APPROVED** [review]
Tested:

image

**Review by UmanShahzad — APPROVED** [review]

**Comment by ilyam8** [comment]
@thiagoftsm consider using 

https://github.com/netdata/netdata/blob/d10fead9978880a71e328a4176f9c5a5ef4e157b/web/gui/dashboard_info.js#L643-L648

This way you can have common info for a section (latency), so you don't need to repeat it for every chart.

**Comment by thiagoftsm** [comment]
> @thiagoftsm consider using

Thank you @ilyam8! I will bring another PR merging all texts, because we have 5 different filesystems. The unique change among them is the function name.

**Review by vlvkobal — APPROVED** [review]

**Comment by thiagoftsm** [comment]
> @thiagoftsm consider using
> 
> https://github.com/netdata/netdata/blob/d10fead9978880a71e328a4176f9c5a5ef4e157b/web/gui/dashboard_info.js#L643-L648
> 
> This way you can have common info for a section (latency), so you don't need to repeat it for every chart.

@ilyam8 I received the approval, I will bring a PR during this week for we move forward with your suggestion.

**Pull request merged**
