### PR TITLE
ZRAM info collector module (proc.plugin)

### PR DESCRIPTION
**Pull request by RaZeR-RBI**
##### Summary
Implemented ZRAM collector module (#2578) in ```proc.plugin```.

The module gets the ZRAM device list by reading /proc/devices, obtaining an device ID from it, then enumerating the devices in /dev filtering them by corresponding major device number it got from previous step.

It takes the data from ```/sys/block/{name}/mm_stat```.

##### Component Name
netdata/collectors

##### Additional Information
Here is a screenshot (a bit zoomed out, but you should get the idea):
[Click me!](https://i.imgur.com/HCzrwWS.png)

My C is a little bit rusty, I hope I haven't missed something important. Feedback and criticism is very welcome :wink:

Fixes: #2578

### CODE REVIEW

**Comment by Ferroin** [comment]
Not exactly the best person to review C code, but a quick look reveals nothing that looks particularly out of place to me.

I'll look at getting this tested on a couple of my systems by the end of the week.

**Comment by vlvkobal** [comment]
@RaZeR-RBI Please get rid of all the warnings. We follow a zero warning policy. Use the following command to compile Netdata:
```
sudo CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-lto --dont-wait
```
Warnings I've got:
```
In file included from collectors/proc.plugin/../../daemon/../libnetdata/libnetdata.h:307,
                 from collectors/proc.plugin/../../daemon/common.h:6,
                 from collectors/proc.plugin/plugin_proc.h:6,
                 from collectors/proc.plugin/sys_block_zram.c:3:
collectors/proc.plugin/sys_block_zram.c: In function 'try_get_zram_major_number':
collectors/proc.plugin/../../daemon/../libnetdata/procfile/procfile.h:95:47: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
   95 | #define procfile_linewords(ff, line) (((line) < procfile_lines(ff)) ? (ff)->lines->lines[(line)].words : 0)
      |                                               ^
collectors/proc.plugin/sys_block_zram.c:44:13: note: in expansion of macro 'procfile_linewords'
   44 |         if (procfile_linewords(file, i) < 2)
      |             ^~~~~~~~~~~~~~~~~~
collectors/proc.plugin/../../daemon/../libnetdata/procfile/procfile.h:104:52: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
  104 | #define procfile_lineword(ff, line, word) (((line) < procfile_lines(ff) && (word) < procfile_linewords((ff), (line))) ? procfile_word((ff), (ff)->lines->lines[(line)].first + (word)) : "")
      |                                                    ^
collectors/proc.plugin/sys_block_zram.c:46:16: note: in expansion of macro 'procfile_lineword'
   46 |         name = procfile_lineword(file, i, 1);
      |                ^~~~~~~~~~~~~~~~~
collectors/proc.plugin/../../daemon/../libnetdata/procfile/procfile.h:95:47: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
   95 | #define procfile_linewords(ff, line) (((line) < procfile_lines(ff)) ? (ff)->lines->lines[(line)].words : 0)
      |                                               ^
collectors/proc.plugin/../../daemon/../libnetdata/procfile/procfile.h:104:85: note: in expansion of macro 'procfile_linewords'
  104 | #define procfile_lineword(ff, line, word) (((line) < procfile_lines(ff) && (word) < procfile_linewords((ff), (line))) ? procfile_word((ff), (ff)->lines->lines[(line)].first + (word)) : "")
      |                                                                                     ^~~~~~~~~~~~~~~~~~
collectors/proc.plugin/sys_block_zram.c:46:16: note: in expansion of macro 'procfile_lineword'
   46 |         name = procfile_lineword(file, i, 1);
      |                ^~~~~~~~~~~~~~~~~
collectors/proc.plugin/../../daemon/../libnetdata/procfile/procfile.h:104:52: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
  104 | #define procfile_lineword(ff, line, word) (((line) < procfile_lines(ff) && (word) < procfile_linewords((ff), (line))) ? procfile_word((ff), (ff)->lines->lines[(line)].first + (word)) : "")
      |                                                    ^
collectors/proc.plugin/sys_block_zram.c:49:24: note: in expansion of macro 'procfile_lineword'
   49 |             id = str2i(procfile_lineword(file, i, 0));
      |                        ^~~~~~~~~~~~~~~~~
collectors/proc.plugin/../../daemon/../libnetdata/procfile/procfile.h:95:47: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
   95 | #define procfile_linewords(ff, line) (((line) < procfile_lines(ff)) ? (ff)->lines->lines[(line)].words : 0)
      |                                               ^
collectors/proc.plugin/../../daemon/../libnetdata/procfile/procfile.h:104:85: note: in expansion of macro 'procfile_linewords'
  104 | #define procfile_lineword(ff, line, word) (((line) < procfile_lines(ff) && (word) < procfile_linewords((ff), (line))) ? procfile_word((ff), (ff)->lines->lines[(line)].first + (word)) : "")
      |                                                                                     ^~~~~~~~~~~~~~~~~~
collectors/proc.plugin/sys_block_zram.c:49:24: note: in expansion of macro 'procfile_lineword'
   49 |             id = str2i(procfile_lineword(file, i, 0));
      |                        ^~~~~~~~~~~~~~~~~
collectors/proc.plugin/sys_block_zram.c: In function 'init_devices':
collectors/proc.plugin/sys_block_zram.c:139:12: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
  139 |     while (de = readdir(dir))
      |            ^~
collectors/proc.plugin/sys_block_zram.c:147:31: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  147 |         if (major(st.st_rdev) == zram_id)
      |                               ^~
collectors/proc.plugin/sys_block_zram.c: In function '_collect_zram_metrics':
collectors/proc.plugin/sys_block_zram.c:188:47: warning: unused parameter 'name' [-Wunused-parameter]
  188 | static inline int _collect_zram_metrics(char *name, void *entry, int advance) {
      |                                         ~~~~~~^~~~
collectors/proc.plugin/sys_block_zram.c: In function 'collect_first_zram_metrics':
collectors/proc.plugin/sys_block_zram.c:221:70: warning: unused parameter 'data' [-Wunused-parameter]
  221 | static int collect_first_zram_metrics(char *name, void *entry, void *data) {
      |                                                                ~~~~~~^~~~
collectors/proc.plugin/sys_block_zram.c: In function 'collect_zram_metrics':
collectors/proc.plugin/sys_block_zram.c:226:64: warning: unused parameter 'data' [-Wunused-parameter]
  226 | static int collect_zram_metrics(char *name, void *entry, void *data) {
      |                                                          ~~~~~~^~~~
```

**Comment by vlvkobal** [comment]
If I run `rmmod zram` when Netdata is displaying zram charts it crashes:
```
2019-06-26 12:09:30: netdata ERROR : PLUGIN[proc] : PROCFILE: Cannot read from file '<F0><F2><84><BE>^?U' on fd 1585 (errno 9, Bad file descriptor)
free(): invalid pointer
```
It was a huge report from `valgrind`, so I'm sending just a part of it:
```
==20579== Invalid read of size 8
==20579==    at 0x1F5414: read_mm_stat (sys_block_zram.c:175)
==20579==    by 0x1F5414: _collect_zram_metrics (sys_block_zram.c:192)
==20579==    by 0x1F5414: collect_zram_metrics (sys_block_zram.c:228)
==20579==    by 0x142B14: dictionary_walker_name_value (dictionary.c:305)
==20579==    by 0x142B31: dictionary_walker_name_value (dictionary.c:310)
==20579==    by 0x143782: dictionary_get_all_name_value (dictionary.c:324)
==20579==    by 0x1F571E: do_sys_block_zram (sys_block_zram.c:270)
==20579==    by 0x1C6AAD: proc_main (plugin_proc.c:125)
==20579==    by 0x15E646: thread_start (threads.c:126)
==20579==    by 0x525957E: start_thread (in /usr/lib/libpthread-2.29.so)
==20579==    by 0x536D0E2: clone (in /usr/lib/libc-2.29.so)
==20579==  Address 0x132fe140 is 16 bytes inside a block of size 176 free'd
==20579==    at 0x48399AB: free (vg_replace_malloc.c:530)
==20579==    by 0x14DCCF: freez (libnetdata.c:172)
==20579==    by 0x153A67: pflines_free (procfile.c:126)
==20579==    by 0x153A67: procfile_close (procfile.c:138)
==20579==    by 0x153CBB: procfile_readall (procfile.c:284)
==20579==    by 0x1F53F9: read_mm_stat (sys_block_zram.c:170)
==20579==    by 0x1F53F9: _collect_zram_metrics (sys_block_zram.c:192)
==20579==    by 0x1F53F9: collect_zram_metrics (sys_block_zram.c:228)
==20579==    by 0x142B14: dictionary_walker_name_value (dictionary.c:305)
==20579==    by 0x142B31: dictionary_walker_name_value (dictionary.c:310)
==20579==    by 0x143782: dictionary_get_all_name_value (dictionary.c:324)
==20579==    by 0x1F571E: do_sys_block_zram (sys_block_zram.c:270)
==20579==    by 0x1C6AAD: proc_main (plugin_proc.c:125)
==20579==    by 0x15E646: thread_start (threads.c:126)
==20579==    by 0x525957E: start_thread (in /usr/lib/libpthread-2.29.so)
==20579==  Block was alloc'd at
==20579==    at 0x483877F: malloc (vg_replace_malloc.c:299)
==20579==    by 0x14DD02: mallocz (libnetdata.c:176)
==20579==    by 0x153F78: pflines_new (procfile.c:111)
==20579==    by 0x153F78: procfile_open (procfile.c:416)
==20579==    by 0x1F5345: init_devices (sys_block_zram.c:151)
==20579==    by 0x1F5891: do_sys_block_zram (sys_block_zram.c:261)
==20579==    by 0x1C6AAD: proc_main (plugin_proc.c:125)
==20579==    by 0x15E646: thread_start (threads.c:126)
==20579==    by 0x525957E: start_thread (in /usr/lib/libpthread-2.29.so)
==20579==    by 0x536D0E2: clone (in /usr/lib/libc-2.29.so)

==20579==
==20579== Invalid free() / delete / delete[] / realloc()
==20579==    at 0x483AD7B: realloc (vg_replace_malloc.c:826)
==20579==    by 0x14DDC9: reallocz (libnetdata.c:188)
==20579==    by 0x1537D5: pflines_add (procfile.c:94)
==20579==    by 0x1537D5: procfile_parser (procfile.c:199)
==20579==    by 0x153B9F: procfile_readall (procfile.c:300)
==20579==    by 0x1F53F9: read_mm_stat (sys_block_zram.c:170)
==20579==    by 0x1F53F9: _collect_zram_metrics (sys_block_zram.c:192)
==20579==    by 0x1F53F9: collect_zram_metrics (sys_block_zram.c:228)
==20579==    by 0x142B14: dictionary_walker_name_value (dictionary.c:305)
==20579==    by 0x143782: dictionary_get_all_name_value (dictionary.c:324)
==20579==    by 0x1F571E: do_sys_block_zram (sys_block_zram.c:270)
==20579==    by 0x1C6AAD: proc_main (plugin_proc.c:125)
==20579==    by 0x15E646: thread_start (threads.c:126)
==20579==    by 0x525957E: start_thread (in /usr/lib/libpthread-2.29.so)
==20579==    by 0x536D0E2: clone (in /usr/lib/libc-2.29.so)
==20579==  Address 0x132cbb20 is 6,080 bytes inside an unallocated block of size 7,936 in arena "client"
```

**Comment by vlvkobal** [comment]
The complete report:
[valgrind_report.txt](https://github.com/netdata/netdata/files/3329527/valgrind_report.txt)

**Comment by RaZeR-RBI** [comment]
@vlvkobal Thank you very much for your feedback!
Compilation warnings and crash on device removal should be fixed now.

**Comment by vlvkobal** [comment]
It is much better now 👍. But there are still some [memory leaks](https://github.com/netdata/netdata/files/3344481/valgrind.txt) to be addressed.

**Comment by RaZeR-RBI** [comment]
@vlvkobal Memory leaks should be fixed now.
[valgrind.txt](https://github.com/netdata/netdata/files/3358471/valgrind.txt)

**Comment by cakrit** [comment]
Thanks @RaZeR-RBI !

**Comment by paulkatsoulakis** [comment]
FYI/FYA this change had to be reverted, report in #6412 
The change needs to be revisited to figure out what was the root cause of that crash that was identified

**Pull request merged**
