### PR TITLE
fix: CPU frequency detection of FreeBSD

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

ssia

##### Test Plan

Tested on `FreeBSD freebsd 12.3-RELEASE FreeBSD 12.3-RELEASE r371126 GENERIC  amd64`:

- master branch

```cmd
wget -q -O system-info.sh https://raw.githubusercontent.com/netdata/netdata/master/daemon/system-info.sh; sh system-info.sh | grep -i freq; rm system-info.sh
NETDATA_SYSTEM_CPU_FREQ=unknown
```

- this PR

```cmd
wget -q -O system-info.sh https://raw.githubusercontent.com/ilyam8/netdata/fix_cpu_freq_freebsd/daemon/system-info.sh; sh system-info.sh | grep -i freq; rm system-info.sh
NETDATA_SYSTEM_CPU_FREQ=2400069742
```

### CODE REVIEW

**Comment by thiagoftsm** [comment]
@ilyam8 the PR is getting CPU frequency, but I also observed two important differences for my CPU. The CPU vendor is set on FreeBSD as `unknown`, and the frequency on Linux has a round value:

### FREEBSD
```sh
NETDATA_SYSTEM_CPU_VENDOR=unknown
NETDATA_SYSTEM_CPU_MODEL=Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
NETDATA_SYSTEM_CPU_FREQ=2904071733
```

### Linux

```sh
NETDATA_SYSTEM_CPU_VENDOR=GenuineIntel
NETDATA_SYSTEM_CPU_MODEL=Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
NETDATA_SYSTEM_CPU_FREQ=2700000000
```

For the CPU frequency it is easy to justify, but are we going to fix the vendor in another PR?
For these tests I used `FreeBSD 13.0-RELEASE-p8` and `Slackware 15.0`, both were running on VirtualBox.

**Comment by ilyam8** [comment]
> For the CPU frequency it is easy to justify, but are we going to fix the vendor in another PR?

Yes. I am not sure if that is an important field.

**Review by thiagoftsm — APPROVED** [review]
After last answer I am approving based in tests described [here](https://github.com/netdata/netdata/pull/12440#issuecomment-1070892569).

**Comment by Ferroin** [comment]
> > For the CPU frequency it is easy to justify, but are we going to fix the vendor in another PR?
> 
> Yes. I am not sure if that is an important field.

We should ideally be reporting correctly, but we need to confirm if this is an issue in our script or in FreeBSD itself (given that the test system in question was a VM, it would not surprise me if FreeBSD just doesn’t provide the info there).

**Comment by thiagoftsm** [comment]
> > > For the CPU frequency it is easy to justify, but are we going to fix the vendor in another PR?
> > 
> > 
> > Yes. I am not sure if that is an important field.
> 
> We should ideally be reporting correctly, but we need to confirm if this is an issue in our script or in FreeBSD itself (given that the test system in question was a VM, it would not surprise me if FreeBSD just doesn’t provide the info there).

I will update my FreeBSD on host, and I will retest this PR again, to complement  my answer this is the complete output I received on VM:

```sh
NETDATA_CONTAINER_OS_NAME=none
NETDATA_CONTAINER_OS_ID=none
NETDATA_CONTAINER_OS_ID_LIKE=none
NETDATA_CONTAINER_OS_VERSION=none
NETDATA_CONTAINER_OS_VERSION_ID=none
NETDATA_CONTAINER_OS_DETECTION=none
NETDATA_CONTAINER_IS_OFFICIAL_IMAGE=false
NETDATA_HOST_OS_NAME=FreeBSD
NETDATA_HOST_OS_ID=FreeBSD
NETDATA_HOST_OS_ID_LIKE=FreeBSD
NETDATA_HOST_OS_VERSION=13.0-RELEASE-p8
NETDATA_HOST_OS_VERSION_ID=unknown
NETDATA_HOST_OS_DETECTION=uname
NETDATA_HOST_IS_K8S_NODE=false
NETDATA_SYSTEM_KERNEL_NAME=FreeBSD
NETDATA_SYSTEM_KERNEL_VERSION=1300139
NETDATA_SYSTEM_ARCHITECTURE=amd64
NETDATA_SYSTEM_VIRTUALIZATION=none
NETDATA_SYSTEM_VIRT_DETECTION=none
NETDATA_SYSTEM_CONTAINER=unknown
NETDATA_SYSTEM_CONTAINER_DETECTION=none
NETDATA_SYSTEM_CPU_LOGICAL_CPU_COUNT=2
NETDATA_SYSTEM_CPU_VENDOR=unknown
NETDATA_SYSTEM_CPU_MODEL=Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
NETDATA_SYSTEM_CPU_FREQ=2904071733
NETDATA_SYSTEM_CPU_DETECTION=sysctl
NETDATA_SYSTEM_TOTAL_RAM=1038655488
NETDATA_SYSTEM_RAM_DETECTION=sysctl
NETDATA_SYSTEM_TOTAL_DISK_SIZE=15591567360
NETDATA_SYSTEM_DISK_DETECTION=df
```

**Comment by ilyam8** [comment]
>  I will retest this PR again

This PR fixes **only** CPU freq detection.

**Review by vlvkobal — APPROVED** [review]

**Comment by thiagoftsm** [comment]
@Ferroin when I run direct on host, the `Processor` is correctly identified:

``` 
NETDATA_CONTAINER_OS_NAME=none
NETDATA_CONTAINER_OS_ID=none
NETDATA_CONTAINER_OS_ID_LIKE=none
NETDATA_CONTAINER_OS_VERSION=none
NETDATA_CONTAINER_OS_VERSION_ID=none
NETDATA_CONTAINER_OS_DETECTION=none
NETDATA_CONTAINER_IS_OFFICIAL_IMAGE=false
NETDATA_HOST_OS_NAME=FreeBSD
NETDATA_HOST_OS_ID=FreeBSD
NETDATA_HOST_OS_ID_LIKE=FreeBSD
NETDATA_HOST_OS_VERSION=13.0-RELEASE-p8
NETDATA_HOST_OS_VERSION_ID=unknown
NETDATA_HOST_OS_DETECTION=uname
NETDATA_HOST_IS_K8S_NODE=false
NETDATA_SYSTEM_KERNEL_NAME=FreeBSD
NETDATA_SYSTEM_KERNEL_VERSION=1300139
NETDATA_SYSTEM_ARCHITECTURE=amd64
NETDATA_SYSTEM_VIRTUALIZATION=none
NETDATA_SYSTEM_VIRT_DETECTION=none
NETDATA_SYSTEM_CONTAINER=unknown
NETDATA_SYSTEM_CONTAINER_DETECTION=none
NETDATA_SYSTEM_CPU_LOGICAL_CPU_COUNT=4
NETDATA_SYSTEM_CPU_VENDOR=Intel(R) Corporation
NETDATA_SYSTEM_CPU_MODEL=Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
NETDATA_SYSTEM_CPU_FREQ=2600000000
NETDATA_SYSTEM_CPU_DETECTION=dmidecode
NETDATA_SYSTEM_TOTAL_RAM=17051623424
NETDATA_SYSTEM_RAM_DETECTION=sysctl
NETDATA_SYSTEM_TOTAL_DISK_SIZE=127906705408
NETDATA_SYSTEM_DISK_DETECTION=df
``` 

@ilyam8 ignore the previous message, because looks like something related with virtual machine.

**Pull request merged**
