### PR TITLE
Add experimental support for running under runit.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This PR adds experimental support for installing the Netdata agent as a system service on systems which use runit as their init system. This is only used if we see no other init system and the user does not explicitly request it. Only supports Linux right now (FreeBSD support may be added later).

##### Test Plan

This is most easily tested on a clean install of Void Linux, which uses runit as it’s primary service management tool and init system. Alternatively, an install of Artix, Devuan, or Gentoo with runit set up as the service manager and init system can also be used for testing.

Without this PR, attempting to install on such systems should throw a warning about not being able to install Netdata as a system service.

With the changes in this PR, installing on such systems should instead install Netdata as a system service and enable it by default in the current runlevel.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @Ferroin ,

After to make a static build I am getting this with your PR:

```sh
Stopping all netdata threads
[/opt/netdata]# stop_all_netdata 
fail: netdata: unable to change to service directory: file does not exist
 OK  ''

Starting netdata using command 'sv start netdata'
[/opt/netdata]# sv start netdata 
fail: netdata: unable to change to service directory: file does not exist
 FAILED  ''

Attempting another netdata start using command 'sv start netdata'
[/opt/netdata]# sv start netdata 
fail: netdata: unable to change to service directory: file does not exist
 FAILED  ''

 WARNING  Netdata service still not started, attempting another forced restart by running '/opt/netdata/bin/netdata '
```

when I run on `VoidLinux`. I did not see any `netdata` directory inside `/etc/sv`. 

Please, also rebase your PR, because I still got a 1.36 version from it.

Best regards!

**Comment by Ferroin** [comment]
@thiagoftsm The issue you reported _should_ be fixed now.

**Comment by thiagoftsm** [comment]
Hello @Ferroin ,

I still have these warnings:

```sh
Starting netdata using command 'sv start netdata'
[/opt/netdata]# sv start netdata 
warning: netdata: unable to open supervise/ok: file does not exist
 FAILED  ''

Attempting another netdata start using command 'sv start netdata'
[/opt/netdata]# sv start netdata 
warning: netdata: unable to open supervise/ok: file does not exist
 FAILED  ''

 WARNING  Netdata service still not started, attempting another forced restart by running '/opt/netdata/bin/netdata '
```

I suspect that this can have relationship with directory structure that I have on my Void Linux:

```sh
bash-5.1# 
bash-5.1# ls -l /etc/sv/netdata/
total 8
-rwxr-xr-x 1 root root  397 Jan  5 12:18 run
drwx------ 2 root root 4096 Jan  5 12:37 supervise
bash-5.1# ls -l /etc/runit/
total 32
-rwxr-xr-x 1 root root  629 Mar 17  2021 1
-rwxr-xr-x 1 root root  887 Mar 17  2021 2
-rwxr-xr-x 1 root root 1399 Mar 17  2021 3
drwxr-xr-x 2 root root 4096 May 14  2021 core-services
-rw-r--r-- 1 root root 3862 Mar 17  2021 crypt.awk
-rwxr-xr-x 1 root root  297 Mar 17  2021 ctrlaltdel
-rw-r--r-- 1 root root 1228 Mar 17  2021 functions
lrwxrwxrwx 1 root root   17 Mar 17  2021 reboot -> /run/runit/reboot
drwxr-xr-x 4 root root 4096 May 14  2021 runsvdir
lrwxrwxrwx 1 root root   17 Mar 17  2021 stopit -> /run/runit/stopit
bash-5.1# 
```

or with a command that is still running after installation:

```sh
bash-5.1# ps aux| grep netdata
root       519  0.0  0.0    916     4 ?        Ss   12:29   0:00 runsvdir -P /run/runit/runsvdir/current log: ata/usr/lib/netdata/conf.d/netdata.conf'. Running with internal defaults. 2023-01-05 12:37:10: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults. .2023-01-05 12:45:01: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults. 
root      1962  0.0  0.0    896     4 ?        Ss   12:37   0:00 runsv netdata
root      2994  0.0  0.0   1736   580 pts/0    S+   12:46   0:00 grep netdata
bash-5.1# 
```

I cannot give more details, because it is my first time with this init system.

Finally, after the installation I can control `netdata` using `sv`:

```sh
bash-5.1# sv start netdata
ok: run: netdata: (pid 2996) 0s
bash-5.1# ps aux| grep netdata
root       519  0.0  0.0    916     4 ?        Ss   12:29   0:00 runsvdir -P /run/runit/runsvdir/current log: data/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults. .2023-01-05 12:45:01: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults. 2023-01-05 12:46:54: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults. 
root      1962  0.0  0.0    896     4 ?        Ss   12:37   0:00 runsv netdata
netdata   2996  5.6  4.0 251408 40124 ?        SNl  12:46   0:00 /opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid/netdata.pid -D
netdata   3000  0.0  0.2  44776  2812 ?        SNl  12:46   0:00 /opt/netdata/bin/srv/netdata --special-spawn-server
root      3180  0.5  0.2   6480  2148 ?        SNl  12:46   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/apps.plugin 1
netdata   3191 11.0  4.6 773900 46900 ?        SNl  12:46   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/go.d.plugin 1
root      3202 25.0  0.6  16636  6896 ?        SNl  12:46   0:00 /opt/netdata/usr/libexec/netdata/plugins.d/ebpf.plugin 1
netdata   3209  0.0  0.1   1912  1400 ?        SN   12:46   0:00 bash /opt/netdata/usr/libexec/netdata/plugins.d/tc-qos-helper.sh 1
root      3407  0.0  0.0   1736   560 pts/0    S+   12:46   0:00 grep netdata
bash-5.1# sv stop netdata
ok: down: netdata: 0s, normally up
bash-5.1# ps aux| grep netdata
root       519  0.0  0.0    916     4 ?        Ss   12:29   0:00 runsvdir -P /run/runit/runsvdir/current log: data/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults. .2023-01-05 12:45:01: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults. 2023-01-05 12:46:54: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/opt/netdata/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults. 
root      1962  0.0  0.0    896     4 ?        Ss   12:37   0:00 runsv netdata
root      3430  0.0  0.0   1736   552 pts/0    S+   12:47   0:00 grep netdata
bash-5.1# 
```

**Comment by Ferroin** [comment]
Rebased to pick up CI changes.

**Review by thiagoftsm — APPROVED** [review]
After a chat with @Ferroin , I am considering [this](https://github.com/netdata/netdata/pull/13841#issuecomment-1372602929) issue a small issue and approving the PR, LGTM!

**Comment by Ferroin** [comment]
Rebased to pick up latest CI changes.

**Comment by Ferroin** [comment]
Rebased again to drop unnecessary commit.

**Review by thiagoftsm — APPROVED** [review]
I created another static binary on my host and test it on Void Linux VM. Everything worked as expected, LGTM!

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Review by thiagoftsm — APPROVED** [review]

**Comment by Ferroin** [comment]
Rebased to resolve merge conflict, again...

**Review by thiagoftsm — DISMISSED** [review]
Well, @netdata/agent I am approving the PR that we test on Void Linux. :smile:

**Comment by Dim-P** [comment]
Tried to test the PR on Devuan but [I found some reports](https://www.reddit.com/r/linuxquestions/comments/wieht0/devuan_runit_why_does_runit_not_find_services/) that `runsv`  doesn't work properly. `sudo sv status netdata` for example returns `fail: netdata: unable to change to service directory: file does not exist`, not only for Netdata, but for every other service I tried starting.

I will need to set up Artix as it seems, as it should work fine there.

**Review by Dim-P — COMMENTED** [review]
OK, finally managed to get it tested on Artix. 

First time I ran the installer:
```
Stopping all netdata threads
[/home/dimitris/netdata]# stop_all_netdata 
warning: netdata: unable to open supervise/ok: file does not exist
 OK  ''

Starting netdata using command 'sv start netdata'
[/home/dimitris/netdata]# sv start netdata 
warning: netdata: unable to open supervise/ok: file does not exist
 FAILED  ''

Attempting another netdata start using command 'sv start netdata'
[/home/dimitris/netdata]# sv start netdata 
warning: netdata: unable to open supervise/ok: file does not exist
 FAILED  ''

 WARNING  Netdata service still not started, attempting another forced restart by running '/usr/sbin/netdata '

[/home/dimitris/netdata]# stop_all_netdata 
warning: netdata: unable to open supervise/ok: file does not exist
 OK  ''

[/home/dimitris/netdata]# /usr/sbin/netdata 
2023-03-06 16:39:59: netdata INFO  : MAIN : CONFIG: cannot load cloud config '/var/lib/netdata/cloud.d/cloud.conf'. Running with internal defaults.
2023-03-06 16:39:59: netdata INFO  : MAIN : Found 0 legacy dbengines, setting multidb diskspace to 256MB
2023-03-06 16:39:59: netdata INFO  : MAIN : Created file '/var/lib/netdata/dbengine_multihost_size' to store the computed value
 OK  ''

 OK  netdata started!

Downloading default configuration from netdata...
[/home/dimitris/netdata]# /usr/bin/curl -sSL --connect-timeout 10 --retry 3 http://localhost:19999/netdata.conf 
 OK  ''

[/home/dimitris/netdata]# mv /etc/netdata/netdata.conf.new /etc/netdata/netdata.conf 
 OK  ''

 OK  New configuration saved for you to edit at /etc/netdata/netdata.conf

[/home/dimitris/netdata]# chmod 0644 /etc/netdata/netdata.conf 
 OK  ''

 --- Check KSM (kernel memory deduper) --- 

Memory de-duplication instructions

You have kernel memory de-duper (called Kernel Same-page Merging,
or KSM) available, but it is not currently enabled.

To enable it run:

    echo 1 >/sys/kernel/mm/ksm/run
    echo 1000 >/sys/kernel/mm/ksm/sleep_millisecs

If you enable it, you will save 40-60% of netdata memory.

 --- Check version.txt --- 
 --- Check apps.plugin --- 
 --- Copy uninstaller --- 
 --- Basic netdata instructions --- 

netdata by default listens on all IPs on port 19999,
so you can access it with:

  http://this.machine.ip:19999/

To stop netdata run:

  sv stop netdata

To start netdata run:

  sv start netdata

Uninstall script copied to: /usr/libexec/netdata/netdata-uninstaller.sh

 --- Installing (but not enabling) the netdata updater tool --- 
Update script is located at /usr/libexec/netdata/netdata-updater.sh

 --- Wrap up environment set up --- 
Preparing .environment file
[/home/dimitris/netdata]# chmod 0644 /etc/netdata/.environment 
 OK  ''

Setting netdata.tarball.checksum to 'new_installation'

The following warnings and non-fatal errors were encountered during the installation process:

  - 
  - Command 'sv start netdata' failed with exit code 1.
  - 
  - Command 'sv start netdata' failed with exit code 1.
  - Netdata service still not started, attempting another forced restart by running '/usr/sbin/netdata '


 --- We are done! --- 

  ^
  |.-.   .-.   .-.   .-.   .-.   .  netdata  .-.   .-.   .-.   .-.   .-.   .-
  |   '-'   '-'   '-'   '-'   '-'               '-'   '-'   '-'   '-'   '-'   
  +----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+--->

 --- is installed and running now! --- 
  enjoy real-time performance and health monitoring...
```

*but*, if I run `netdata-uninstaller.sh -f -y -e /etc/netdata/.environment`  and the installer again, it seems to install the service correctly:
```
 --- Install netdata at system init ---                                                                                                                                                                                                       
Installing runit service file.                                                                                                                                                                                                                
 --- Restarting netdata instance ---                                                                                                                                                                                                          
                                                                                                                                                                                                                                              
Stopping all netdata threads                                                                                                                                                                                                                  
[/home/dimitris/netdata]# stop_all_netdata                                                                                                                                                                                                    
ok: down: netdata: 0s, normally up                                                                                                                                                                                                            
 OK  ''                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
Starting netdata using command 'sv start netdata'                                                                                                                                                                                             
[/home/dimitris/netdata]# sv start netdata                                                                                                                                                                                                    
ok: run: netdata: (pid 1829) 1s                                                                                                                                                                                                               
 OK  ''                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                              
 OK  netdata started!                                                                                                                                                                                                                         
```

and `pstree`:
```
      │          └─runsv───netdata─┬─apps.plugin───{apps.plugin}
      │                            ├─bash
      │                            ├─cups.plugin
      │                            ├─ebpf.plugin───7*[{ebpf.plugin}]
      │                            ├─go.d.plugin───14*[{go.d.plugin}]
      │                            ├─netdata───{netdata}
      │                            └─56*[{netdata}]
```

BTW, after running `netdata-uninstaller.sh -f -y -e /etc/netdata/.environment`, these are left behind, so I guess that's why the installer succeeds without errors the second time it's run:
```
/usr/lib/netdata/system/initd/init.d/netdata                                                                           
/usr/lib/netdata/system/freebsd/rc.d/netdata                                                                           
/usr/lib/netdata/system/logrotate/netdata                                                                              
/usr/lib/netdata/system/lsb/init.d/netdata                                                                             
/usr/lib/netdata/system/openrc/init.d/netdata                                                                          
/usr/lib/netdata/system/openrc/conf.d/netdata                                                                          
/usr/lib/netdata
/etc/runit/sv/netdata                                      
/etc/runit/runsvdir/default/netdata                        
/run/netdata 
```

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Comment by Ferroin** [comment]
Given that:

- This is functionally a tech-preview anyway.
- It’s adding support for an uncommon case we don’t yet support at all.
- All the CI is passing consistently (or failing in ways that have nothing to do with this PR).

I think it’s safe to merge despite being a bit buggy, so I’m going to just merge this and deal with any fallout that may occur.

**Pull request merged**
