### PR TITLE
Fix handling of vendored eBPF code in CMake.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

- Fix a logic error in the handling of the kernel version detection code.
- Add code to detect the kernel version based on the contents of `linux/version.h` and use that in preference to running `uname -r` (this way we get correct behavior in containers).
- Properly pull in the static version of the legacy eBPF code on static builds.
- Explicitly use the same C compiler for building libbpf that CMake has been told to use.
- Force use of legacy libbpf for CentOS 7 and AL 2 package builds.
- Fix a typo in the FORCE_LEGACY_LIBBPF option declaration.

##### Test Plan

CI passes on this PR.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
@Ferroin ,

After your last commits, I began to have kernel not detected again:

```sh
-- Determining host kernel version
-- Determining host kernel version - unknown
```

This was initially fixed with the two initial commits.

Best regards!

**Comment by thiagoftsm** [comment]
@Ferroin ,

When I am compiling directly with `netdata-installer.sh` everything is working as expected, and I am getting `glibc` binaries. On the other hand, when I use `cmake` on my `host or a `Qemu-VM` I observed two unexpected results:

- Host
```sh
-- Downloading...
   dst='/home/thiago/Netdata/tests_netdata/build/ebpf-code-legacy-prefix/src/netdata-kernel-collector-musl-v1.4.0.tar.xz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/netdata/kernel-collector/releases/download/v1.4.0/netdata-kernel-collector-musl-v1.4.0.tar.xz'
-- [download 2% complete]
```
- Qemu
```sh
-- Downloading...
   dst='/home/thiago/Netdata/netdata/mytest/ebpf-code-legacy-prefix/src/netdata-kernel-collector-static-v1.4.0.tar.xz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/netdata/kernel-collector/releases/download/v1.4.0/netdata-kernel-collector-static-v1.4.0.tar.xz'
```

In both scenarios, I was expecting to have `glibc`.

**Comment by Ferroin** [comment]
@thiagoftsm For the first case, can you share the output of `ldd --version`.

The second case is an oversight on my part, I’ll have a fix for it pushed shortly.

**Comment by Ferroin** [comment]
@thiagoftsm Disregard my previous comment, both issues were oversights on my end and should be fixed with the latest commits.

**Review by thiagoftsm — APPROVED** [review]
PR is working as expected on 5 different environments, LGTM!

**Review by thiagoftsm — APPROVED** [review]
After chat on Slack, and last commit, I am reapproving PR after retest it on different scenarios, LGTM!

**Pull request merged**
