### PR TITLE
Add high precision timer support for plugins such as idlejitter.

### LINKED ISSUE #8409: Obviously bogus values reported for idlejitter.
##### Bug report summary
The idle jitter collector is reporting obviously bogus values on my home server system. Hardware is a Ryzen 9 3950X with 64GB of DDR4-2666 RAM.

The `min` dimension is stuck reporting 0, `max` is stuck reporting -1, and `average` is seemingly randomly jumping between 0 and 361701000000000000.

screenshot-7503b3bf

I've looked on a couple of other systems, and do not see the same behavior, but I've ruled out most of the likely hardware issues that could cause something like this (RAM and CPU appear to be perfectly fine, PSU is working correctly (and has plenty of excess capacity)).

##### OS / Environment
```
Linux home-one 5.5.1-ahferroin7+ #146 SMP Sun Mar 15 11:35:16 EDT 2020 x86_64 AMD Ryzen 9 3950X 16-Core Processor AuthenticAMD GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.7
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:HOME_URL="https://www.gentoo.org/"
/etc/os-release:SUPPORT_URL="https://www.gentoo.org/support/"
/etc/os-release:BUG_REPORT_URL="https://bugs.gentoo.org/"
```

##### Netdata version
netdata v1.20.0-171-g161ba159, but I've also verified this on the 1.20 release on the same system.

##### Component Name
area/collectors

##### Steps To Reproduce
None so far.

##### Expected behavior
Properly sensible values for idle jitter.

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #8409
##### Component Name
libnetdata
collectors
##### Test Plan
Test idlejitter plugin in the affected systems.

### CODE REVIEW

**Comment by amoss** [comment]
@mfundul I don't think that I have affected hardware to test this.

**Comment by mfundul** [comment]
Me neither, so we'll have to rely on code review for now and wait for the 2 known affected cases to report back to me.

**Comment by Ferroin** [comment]
@mfundul I'll try and check this either today or tomorrow. Based on looking at the code though, I suspect that this should indeed fix things.

**Comment by Ferroin** [comment]
@mfundul Let me know if you want me to force merge this PR. The Netlify checks appear to be stuck, but don't really matter here.

**Pull request merged**
