### PR TITLE
added byte unit scaling

### PR DESCRIPTION
**Pull request by AndCycle**
##### Summary
as we have unit scaling now,
added byte unit seems easier to deal with than fiddling with divisor.

##### Component Name
web/gui

### CODE REVIEW

**Comment by gmosx** [comment]
@paulfantom you mean we should change all the abbreviations to be pedantic? even the existing ones?

**Comment by paulfantom** [comment]
Yes, we should change them.

**Comment by gmosx** [comment]
@ktsaou what do you think about this?

**Comment by gmosx** [comment]
I guess we can merge this PR and then I will go and rename the rest of the abbreviations, to be standards-compliant.

**Comment by ktsaou** [comment]
> I guess we can merge this PR and then I will go and rename the rest of the abbreviations, to be standards-compliant.

yes, let's do it that way.

> As those are multipliers of 1024, then according to IEC standard their unit should be represented in kibibytes (KiB), mebibytes (MiB) and so on. KB, MB and alike are reserved for multipliers of 1000 so there is no confusion with SI standards of unit naming.
> Standard was also implemented by IEEE in 2002 as IEEE 1541-2002.

@paulfantom 	please open a new issue and post a link of the standard. Most users are not familiar, this change may lead to confusion when comparing netdata with console tools and I would like to check whether there is such a reservation.

In general, netdata today uses:

- 1000 multiplier / divider for network traffic and units are `kilobits/s`.
- 1024 multiplier / divider for memory and the units are `MB` for sizes and `MB/s` for rates.
- 1024 multiplier / divider for disk space and the units are `GB` and `KB/s` for rates.

The above are then scaled by the dashboard.

According to this: https://en.wikipedia.org/wiki/Kilobyte netdata is already doing the right thing:

- `kB` is 1000 bytes
- `KB` is 1024 bytes

Anyway, let's discuss this on a different issue.

**Comment by ktsaou** [comment]
@gmosx 	this PR modified `dashboard.js` not the files it is composed from.
So, this change is overwritten by `make` and it is not actually installed by the installer.

**Comment by ktsaou** [comment]
@paulfantom 	can we have travis fail the generated dashboard.js and one in the repo do not match?

The check is very simple. Just a `diff`. Copy `web/gui/dashboard.js` to `/tmp/XXX` before installing netdata and run `diff -q /tmp/XXX web/gui/dashboard.js` after installing it. If it returns non-zero, the PR is broken.

**Comment by paulfantom** [comment]
@ktsaou implemented in https://github.com/netdata/netdata/pull/4715. However I had to revert this PR due to failing test.

**Comment by ktsaou** [comment]
> @ktsaou implemented in #4715. However I had to revert this PR due to failing test.

yes, thanks!

**Comment by ktsaou** [comment]
The code in this PR is also missing a `}`.

**Comment by gmosx** [comment]
@ktsaou Created new PR: https://github.com/netdata/netdata/pull/4724

**Pull request merged**
