### PR TITLE
CPU frequency (Windows)

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
This PR adds CPU frequency to Microsoft Windows dashboard.

cpufreq

##### Test Plan

1. Compile this branch on Linux and on Windows
2. Verify you have charts on both OS.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by ilyam8** [comment]
This doesn't look like the processor's real-time clock speed. As you can see, the value is (almost always) constant. @stelfrag can you test on your PC?

**Comment by thiagoftsm** [comment]
> This doesn't look like the processor's real-time clock speed. As you can see, the value is (almost always) constant. @stelfrag can you test on your PC?

According to Microsoft official description:

```sh
 "Help": "Processor Frequency is the frequency of the current processor in megahertz. Some processors are capable of regulating their frequency outside of the control of Windows. Processor Frequency will not accurately reflect actual processor frequency on these systems. Use % Processor Performance instead."
```

I did not use `% Processor Performance`, for users have conditions to compare our results with other projects like [Windows Exporter](https://github.com/prometheus-community/windows_exporter/blob/fddb92a9d53d279cd5a51962c0aff887dd41d9e5/pkg/collector/cpu/cpu.go#L312). 

I am going to push a commit changing the metric, and our users will have to use our API to get the same value present on other software.

**Comment by ilyam8** [comment]
> > This doesn't look like the processor's real-time clock speed. As you can see, the value is (almost always) constant. @stelfrag can you test on your PC?
> 
> According to Microsoft official description:
> 
> ```shell
>  "Help": "Processor Frequency is the frequency of the current processor in megahertz. Some processors are capable of regulating their frequency outside of the control of Windows. Processor Frequency will not accurately reflect actual processor frequency on these systems. Use % Processor Performance instead."
> ```
> 
> I did not use `% Processor Performance`, for users have conditions to compare our results with other projects like [Windows Exporter](https://github.com/prometheus-community/windows_exporter/blob/fddb92a9d53d279cd5a51962c0aff887dd41d9e5/pkg/collector/cpu/cpu.go#L312).
> 
> I am going to push a commit changing the metric, and our users will have to use our API to get the same value present on other software.

According to your screenshot - I see no value in this metric. Do you understand why?

**Comment by thiagoftsm** [comment]
This last commit still does not bring the final version, I am working with the different options to verify what can give results near we have on Linux. This is the current state:

Screenshot_20240722_144625

**Comment by stelfrag** [comment]
After latest commit

image

**Comment by stelfrag** [comment]
Something still does not make sense. 

My CPU can't drop below 3.8G

image

**Comment by thiagoftsm** [comment]
@stelfrag as I had commented, I updated the algorithm for one that has been reported in different forums:

Freq

Now the frequency is following an expected pattern.

**Comment by thiagoftsm** [comment]
> Something still does not make sense.
> 
> My CPU can't drop below 3.8G
> 

It should be fixed with last commit.

**Comment by thiagoftsm** [comment]
@stelfrag ,

In my environment, using the recommended Microsoft algorithm, I’m getting the following frequency results:

freq

When using other variables that have been mentioned, the results differ, but I prefer to stick with the recommended approach.

Selecting specific CPUs sometimes leads to further variations.

If we use % of Maximum Frequency, the results become even more unstable.

Best regards!

**Comment by ilyam8** [comment]
Judging by the latest screenshot - this PR is wontfix.

**Comment by thiagoftsm** [comment]
Considering difference between expectation and available data, I will proceed with metrics defined by @shyamvalsan.

**Pull request closed without merging**
