### PR TITLE
fix  #14841 Exception funktion call Rados.mon_command()

### LINKED ISSUE #14841: [Bug]: ceph.chart.py - cluster.mon_command -  TypeError: Argument 'inbuf' has incorrect type (expected bytes, got str)
### Bug description

got TypeError while call cluster.mon_command() 

```
netdata@pve_5:/usr/lib/netdata/plugins.d$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)

>>> import rados, json
>>> cluster = rados.Rados(conffile='/etc/ceph/ceph.conf', conf=dict(keyring='/etc/ceph/ceph.client.admin.keyring'))
>>> cluster.connect()
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Argument 'inbuf' has incorrect type (expected bytes, got str)
```

### Expected behavior

```python
# works if replace inbuf value '' by b''
# see https://docs.ceph.com/en/latest/rados/api/python/#rados.Rados.mon_command
>>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), b'')[1])
{'stats': {'total_bytes': 10000611567206 ...
```

### Installation method

manual setup of official DEB/RPM packages

### System info

```shell
Linux pve_5 5.15.39-4-pve #1 SMP PVE 5.15.39-4 (Mon, 08 Aug 2022 15:11:15 +0200) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=debian

netdata@pve_5:/usr/lib/netdata/plugins.d$ dpkg -l proxmox-ve
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  proxmox-ve     7.2-1        all          Proxmox Virtual Environment

netdata@pve_5:/usr/lib/netdata/plugins.d$ ceph -v
ceph version 16.2.9 (a569859f5e07da0c4c39da81d5fb5675cd95da49) pacific (stable)
```

### Netdata build info

```shell
root@pve_5:/etc/netdata# dpkg -l | rg netdata
ii  netdata                  1.29.3-4   all    real-time performance monitoring (metapackage)
ii  netdata-core             1.29.3-4   amd64  real-time performance monitoring (core)
ii  netdata-plugins-bash     1.29.3-4   all    real-time performance monitoring (bash plugins)
ii  netdata-plugins-nodejs   1.29.3-4   all    real-time performance monitoring (nodejs plugins)
ii  netdata-plugins-python   1.29.3-4   all    real-time performance monitoring (python plugins)
ii  netdata-web              1.29.3-4   all    real-time performance monitoring (web)
```

### PR DESCRIPTION
**Pull request by farax4de**
##### Summary

Fix Exception TypeError: Argument 'inbuf' has incorrect type (expected bytes, got str) in ceph.chart.py
function call  Rados.mon_command()

```python
Reproduce exception:
    >>> import rados, json
    >>> cluster = rados.Rados(conffile='/etc/ceph/ceph.conf', conf=dict(keyring='/etc/ceph/ceph.client.admin.keyring'))
    >>> cluster.connect()
    >>> json.loads(cluster.mon_command(json.dumps({'prefix': 'df', 'format': 'json'}), '')[1])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: Argument 'inbuf' has incorrect type (expected bytes, got str)
```

##### Additional Information

related librados documenation: https://docs.ceph.com/en/latest/rados/api/python/#rados.Rados.mon_command

example from ceph docs:

```python
    import json
    c = Rados(conffile='/etc/ceph/ceph.conf')
    c.connect()
    cmd = json.dumps({"prefix": "osd safe-to-destroy", "ids": ["2"], "format": "json"})
    c.mon_command(cmd, b'')

```

### CODE REVIEW

**Comment by ilyam8** [comment]
Hey, @farax4de. [Signing the CLA](https://github.com/netdata/netdata/pull/14844#issuecomment-1490803277) is needed to accept the contribution.

**Comment by farax4de** [comment]
> 

i thin it is now done

**Review by thiagoftsm — APPROVED** [review]

**Comment by ilyam8** [comment]
Thanks for the fix, @farax4de 👍

**Comment by thiagoftsm** [comment]
Thank you very much @farax4de !

**Pull request merged**
