### PR TITLE
dashboard v1.5.2

### PR DESCRIPTION
**Pull request by jacekkolasa**
##### Summary
New Dashboard version.

The only new change related to Agent Dashboard is https://github.com/netdata/dashboard/pull/124:
- add new social media links section below right hand sidebar
- move "Privacy policy" & "Terms and conditions" links from sidebar to the bottom of the dashboard
- leave only "Copyright 2020, Netdata, Inc" in Copyright section in the bottom of the dashboard

### CODE REVIEW

**Comment by ilyam8** [comment]
I see the changes, i think the style a little bit strange, do we deliberately use that background to highlight social media links?

Screenshot 2020-09-10 at 15 31 09

**Comment by thiagoftsm** [comment]
> I see the changes, i think the style a little bit strange, do we deliberately use that background to highlight social media links?
> 

I agree with all @ilyam8 words and also I have doubts:
1 -  why are we not adding all social network listed [here](https://github.com/netdata/netdata/#community)? 
2 - I think the second sentence `Give us a start?` should not have the interrogation. Am I correct @joelhans ?

**Comment by jacekkolasa** [comment]
Yes, that's deliberate. The design looks like this: 
image

I agree it can be a little distracting, but maybe that's only because we are so used to the same sidebar? I'm not sure. @manos-saratsis what do you think?

**Comment by ilyam8** [comment]
@jacekkolasa i see you the angles are roundish on your screenshot which looks better, indeed.

**Comment by joelhans** [comment]
@thiagoftsm I don't think this is really my call but rather product's, but yes, I would end that sentence with an exclamation point or a period.

Give us a star!
Give us a star.

**Review by prologic — APPROVED** [review]

**Comment by manos-saratsis** [comment]
Give us a star! It was a mistake on the design. Also we should make the Github star a bit more prominent,

**Comment by jacekkolasa** [comment]
closing, will be replaced by newer version

**Pull request closed without merging**
