### PR TITLE
.travis.yml: Prevent nightly jobs from timing out (again)

### PR DESCRIPTION
**Pull request by knatsakis**
#### Summary
Prevent nightlies from timing out (again). Using a different approach this time because the first attempt was not good enough.

##### Component Name
.travis.yml

##### Additional Information
[Test build output](https://travis-ci.org/knatsakis/netdata/jobs/605792730)

### CODE REVIEW

**Comment by cosmix** [comment]
What was the problem with `travis_wait`?

**Comment by knatsakis** [comment]
The problem was that 20 minutes were not enough after all for building the arm64 docker image.

I decided to spend the time needed in order to fix this in a more proper way. We should be ok until we reach the 60 minute time limit.

**Comment by cosmix** [comment]
> The problem was that 20 minutes were not enough after all for building the arm64 docker image.
> 
> I decided to spend the time needed in order to fix this in a more proper way. We should be ok until we reach the 60 minute time limit.

If so, why not `travis_wait xx` where `xx` > `20`?

**Comment by knatsakis** [comment]
I suppose I could have used travis_wait 60 (maximum time limit for the whole job) and be done with it.

If I recall correctly though, travis_wait was causing wrong timestamps (with #7239) because it buffers the output until the commands exits.

**Pull request merged**
