### PR TITLE
Fix compilation warnings in FreeBSD

### LINKED ISSUE #12797: [Bug]: Warnings when compiled on FreeBSD (plugins)
### Bug description

When we compile Netdata on `FreeBSD` the following warnings are shown:

```sh
[/home/thiago/Netdata/removeme]# gmake -j2 
collectors/apps.plugin/apps_plugin.c: In function 'read_global_time':
collectors/apps.plugin/apps_plugin.c:1643:56: warning: unused variable 'gtime_raw' [-Wunused-variable]
 1643 |     static kernel_uint_t utime_raw = 0, stime_raw = 0, gtime_raw = 0, ntime_raw = 0;
      |                                                        ^~~~~~~~~
In file included from ./aclk/aclk_proxy.h:4,
                 from ./aclk/aclk_api.h:7,
                 from ./daemon/common.h:72,
                 from ./collectors/all.h:6,
                 from collectors/apps.plugin/apps_plugin.c:9:
collectors/apps.plugin/apps_plugin.c: In function 'read_pid_file_descriptors':
collectors/apps.plugin/apps_plugin.c:2001:27: warning: comparison of integer expressions of different signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
 2001 |         if (unlikely(fdid >= p->fds_size)) {
      |                           ^~
./config.h:404:41: note: in definition of macro 'unlikely'
  404 | #define unlikely(x) __builtin_expect(!!(x), 0)
      |                                         ^
At top level:
collectors/apps.plugin/apps_plugin.c:1643:56: warning: 'gtime_raw' defined but not used [-Wunused-variable]
 1643 |     static kernel_uint_t utime_raw = 0, stime_raw = 0, gtime_raw = 0, ntime_raw = 0;
      |                                                        ^~~~~~~~~
collectors/apps.plugin/apps_plugin.c:3852:13: warning: 'send_proc_states_count' defined but not used [-Wunused-function]
 3852 | static void send_proc_states_count(usec_t dt)
      |             ^~~~~~~~~~~~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c: In function 'read_pid_file_descriptors':
collectors/apps.plugin/apps_plugin.c:2058:51: warning: '%s' directive writing up to 1023 bytes into a region of size 1013 [-Wformat-overflow=]
 2058 |                     sprintf(fdsname, "other: shm: %s size: %lu", fds->kf_path, fds->kf_un.kf_file.kf_file_size);
      |                                                   ^~
collectors/apps.plugin/apps_plugin.c:2058:21: note: 'sprintf' output between 21 and 1063 bytes into a destination of size 1025
 2058 |                     sprintf(fdsname, "other: shm: %s size: %lu", fds->kf_path, fds->kf_un.kf_file.kf_file_size);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libnetdata/libnetdata.c: In function 'madvise_mergeable':
libnetdata/libnetdata.c:988:43: warning: unused parameter 'mem' [-Wunused-parameter]
  988 | static inline int madvise_mergeable(void *mem, size_t len) {
      |                                     ~~~~~~^~~
libnetdata/libnetdata.c:988:55: warning: unused parameter 'len' [-Wunused-parameter]
  988 | static inline int madvise_mergeable(void *mem, size_t len) {
      |                                                ~~~~~~~^~~
collectors/freebsd.plugin/freebsd_sysctl.c: In function 'do_system_ram':
collectors/freebsd.plugin/freebsd_sysctl.c:1004:24: warning: unused variable 'rd_cache' [-Wunused-variable]
 1004 |                       *rd_cache = NULL, *rd_buffers = NULL;
      |                        ^~~~~~~~
collectors/freebsd.plugin/freebsd_sysctl.c:976:16: warning: unused variable 'mib_cache_count' [-Wunused-variable]
  976 |                mib_cache_count[4] = {0, 0, 0, 0}, mib_vfs_bufspace[2] = {0, 0}, mib_free_count[4] = {0, 0, 0, 0};
      |                ^~~~~~~~~~~~~~~
At top level:
collectors/freebsd.plugin/freebsd_sysctl.c:976:16: warning: 'mib_cache_count' defined but not used [-Wunused-variable]
collectors/freebsd.plugin/freebsd_sysctl.c:1004:24: warning: 'rd_cache' defined but not used [-Wunused-variable]
 1004 |                       *rd_cache = NULL, *rd_buffers = NULL;
      |                        ^~~~~~~~
collectors/freebsd.plugin/freebsd_ipfw.c: In function 'do_ipfw':
collectors/freebsd.plugin/freebsd_ipfw.c:236:45: warning: format '%d' expects argument of type 'int', but argument 3 has type 'uint32_t' {aka 'unsigned int'} [-Wformat=]
  236 |                     sprintf(rule_num_str, "%d_%d", rule->rulenum, rule->id);
      |                                            ~^      ~~~~~~~~~~~~~
      |                                             |          |
      |                                             int        uint32_t {aka unsigned int}
      |                                            %d
collectors/freebsd.plugin/freebsd_ipfw.c:236:48: warning: format '%d' expects argument of type 'int', but argument 4 has type 'uint32_t' {aka 'unsigned int'} [-Wformat=]
  236 |                     sprintf(rule_num_str, "%d_%d", rule->rulenum, rule->id);
      |                                               ~^                  ~~~~~~~~
      |                                                |                      |
      |                                                int                    uint32_t {aka unsigned int}
      |                                               %d
 OK  ''

```

### Expected behavior

Compile Netdata without warnings.

### Steps to reproduce

1. Clone Netdata
2. Compile `master` branch using the flags `CFLAGS="-O1 -ggdb -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1"`

...

### Installation method

from source

### System info

```shell
FreeBSD freebsd 13.0-RELEASE-p11 FreeBSD 13.0-RELEASE-p11 #0: Tue Apr  5 18:54:35 UTC 2022     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
```

### Netdata build info

```shell
Version: netdata v1.34.0-69-nightly
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--disable-lto' '--disable-ml' '--disable-dependency-tracking' '--with-bundled-protobuf' '--with-bundled-libJudy' 'CFLAGS=-O1 -ggdb -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1' 'LDFLAGS='
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES 
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           NO
    Stream Compression:         YES
Libraries:
    protobuf:                YES (bundled)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: NO
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
SSIA

Fixes #12797

### CODE REVIEW

**Comment by stelfrag** [comment]
I still get 

```
collectors/apps.plugin/apps_plugin.c:2064:38: warning: '%s' directive writing up to 1023 bytes into a region of size 1013 [-Wformat-overflow=]
collectors/freebsd.plugin/freebsd_ipfw.c:236:43: warning: format '%d' expects argument of type 'int', but argument 4 has type 'uint32_t' {aka 'unsigned int'} [-Wformat=]
```

**Comment by thiagoftsm** [comment]
I have the same warnings that @stelfrag reported, I am also copying my alerts here, because I am using different flags, so my comments will be a complement for his comments:

```sh
collectors/apps.plugin/apps_plugin.c: In function 'read_pid_file_descriptors':
collectors/apps.plugin/apps_plugin.c:2064:38: warning: '%s' directive writing up to 1023 bytes into a region of size 1013 [-Wformat-overflow=]
 2064 |                         "other: shm: %s size: %lu",
      |                                      ^~
collectors/apps.plugin/apps_plugin.c:2064:25: note: directive argument in the range [0, 1024]
 2064 |                         "other: shm: %s size: %lu",
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:2062:21: note: 'sprintf' output between 21 and 1047 bytes into a destination of size 1025
 2062 |                     sprintf(
      |                     ^~~~~~~~
 2063 |                         fdsname,
      |                         ~~~~~~~~
 2064 |                         "other: shm: %s size: %lu",
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2065 |                         fds->kf_path,
      |                         ~~~~~~~~~~~~~
 2066 |                         (FILENAME_MAX < fds->kf_un.kf_file.kf_file_size) ? FILENAME_MAX :
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 2067 |                                                                            fds->kf_un.kf_file.kf_file_size);
      |                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
collectors/freebsd.plugin/freebsd_ipfw.c: In function 'do_ipfw':
collectors/freebsd.plugin/freebsd_ipfw.c:236:43: warning: format '%d' expects argument of type 'int', but argument 4 has type 'uint32_t' {aka 'unsigned int'} [-Wformat=]
  236 |                     sprintf(rule_num_str, "%"PRIu32"_%d", (uint32_t)rule->rulenum, rule->id);
      |                                           ^~~                                      ~~~~~~~~
      |                                                                                        |
      |                                                                                        uint32_t {aka unsigned int}
collectors/freebsd.plugin/freebsd_ipfw.c:236:55: note: format string is defined here
  236 |                     sprintf(rule_num_str, "%"PRIu32"_%d", (uint32_t)rule->rulenum, rule->id);
      |                                                      ~^
      |                                                       |
      |                                                       int
      |                                                      %d
 OK  ''

```

**Comment by vlvkobal** [comment]
BTW, we don't encourage to use GCC on FreeBSD. Should we? Clang doesn't report the warnings mentioned in the comments.

**Review by stelfrag — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
I tested on `FreeBSD 13.0-RELEASE-p11` and I did not have more warnings. LGTM!

**Pull request merged**
