### PR TITLE
Refactor `install-required-packages.sh` and remove unnecessary confusiong logic.

### LINKED ISSUE #9380: install-required-packages.sh and CentOS 8
##### Bug report summary
Today I had to install on CentOS 8 a Netdata client and I decided to use `install-required-packages.sh`, I observed that at the end the packages installed did not allow me to use the `dbengine`, because we are missing packages and the libuv installed is not recognized. I had to run the following commands to be able to compile Netdata:

```bash
# ./packaging/installer/install-required-packages.sh --dont-wait --non-interactive
# dnf remove -y libuv1 
# dnf -y install libuv-devel zlib-devel libuuid-devel 
# ./netdata-installer.sh --dont-wait 
```

##### OS / Environment
```
Linux malta2183.startdedicated.com 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
/etc/centos-release:CentOS Linux release 8.2.2004 (Core) 
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="8 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="8"
/etc/os-release:PLATFORM_ID="platform:el8"
/etc/os-release:PRETTY_NAME="CentOS Linux 8 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:8"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-8"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="8"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="8"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 8.2.2004 (Core) 
/etc/system-release:CentOS Linux release 8.2.2004 (Core) 
```

##### Netdata version
netdata v1.22.1-297-g13624215
 

##### Component Name
Installer

##### Steps To Reproduce
1. Install CentOS 8 with the minimum possible
2.Run the commands described on top.

##### Expected behavior
After to use `install-required-packages.sh`, it is expected to have conditions to compile Netdata with `dbengine`.

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

ssia

This simplifes greatly the code we have for installing required packages
and aggressively removes a bunch of things we either no longer user, are
outdated or simply don't work (_or otherwise a bit silly_).

- Fixes #9380

##### Component Name

- area/packaging

##### Test Plan

TBD

##### Additional Information

### CODE REVIEW

**Comment by thiagoftsm** [comment]
I created a container from scratch and I am getting this error when I used this PR:

```
./packaging/installer/install-required-packages.sh: line 1112: [: : integer expression expected

The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   yum update  

yum install Judy-devel autoconf autoconf-archive autogen automake cmake gcc json-c-devel libmnl-devel libuuid-devel libuv-devel lm_sensors lz4-devel make nmap-ncat nodejs openssl-devel pkgconfig python3 zlib-devel 


yum install Judy-devel autoconf autoconf-archive autogen automake cmake gcc json-c-devel libmnl-devel libuuid-devel libuv-devel lm_sensors lz4-devel make nmap-ncat nodejs openssl-devel pkgconfig python3 zlib-devel 
Last metadata expiration check: 0:00:08 ago on Tue Jun 23 20:15:39 2020.
Error: 
 Problem: package Judy-devel-1.0.5-18.el8.x86_64 requires Judy = 1.0.5-18.el8, but none of the providers can be installed
```

**Comment by prologic** [comment]
Thanks @thiagoftsm Fixed with latest commit. I forgot some code :)

**Comment by thiagoftsm** [comment]
A new error now:

```
WARNING
package python3-pymongo is not available in this system.
You may try to install without it.


The following command will be run:

 >> IMPORTANT << 
    Please make sure your system is up to date
    by running:   yum update  

yum install Judy-devel autoconf autoconf-archive autogen automake cmake gcc git json-c-devel libmnl-devel libuuid-devel libuv-devel lm_sensors lz4-devel make nmap-ncat nodejs openssl-devel pkgconfig python3 zlib-devel 


yum install Judy-devel autoconf autoconf-archive autogen automake cmake gcc git json-c-devel libmnl-devel libuuid-devel libuv-devel lm_sensors lz4-devel make nmap-ncat nodejs openssl-devel pkgconfig python3 zlib-devel 
Last metadata expiration check: 0:00:09 ago on Wed Jun 24 14:43:45 2020.
Error: 
 Problem: package Judy-devel-1.0.5-18.el8.x86_64 requires Judy = 1.0.5-18.el8, but none of the providers can be installed
  - conflicting requests
  - package Judy-1.0.5-18.el8.x86_64 is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by prologic** [comment]
Which system is this @thiagoftsm ? I've seen this before I think think its the blasted CentOS 8.x error I haven't fixed yet :/

**Comment by thiagoftsm** [comment]
> Which system is this @thiagoftsm ? I've seen this before I think think its the blasted CentOS 8.x error I haven't fixed yet :/

I do not have CentOS 8 on bare metal without Netdata, so I used a LXC with the following configuration

```
netdata11:/# cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core)                                                                                                                                                                                                                                           
netdata11:/# uname -a                                                                                                                                                                                                                                                          
Linux netdata11 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux     
```

**Comment by prologic** [comment]
@thiagoftsm Ahh yes I think this is #8602 if I'm not mistaken. I would not test this PR on CentOS 8.x at all for this reason. But if this PR works everywhere else we're good as it significantly cleans up a bunch of stuff we really just don't need IHMO and reduces confusion.

**Comment by prologic** [comment]
This is also well tested in our CI too btw, and the only failing test is expected there until I fix #8602

**Pull request closed without merging**
