### PR TITLE
Remove Python OpenLDAP implementation

### PR DESCRIPTION
**Pull request by Ancairon**
##### Summary

Remove the collector, replaced from #18625

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]

**Review by Kimmon322 — CHANGES_REQUESTED** [review]
Leave

**Review by Kimmon322 — CHANGES_REQUESTED** [review]
Leave 30

**Review by Kimmon322 — COMMENTED** [review]
Leave 30

**Review by Kimmon322 — APPROVED** [review]
Leave 30

**Pull request merged**
