### PR TITLE
Pass the child machine's guid to the goto_url link

### LINKED ISSUE #12376: [Bug]: Alert email for a child re-directs to the parent
### Bug description

**Preconditions:**
- 2 nodes in a parent/child setup
- Child streams data through the parent
- alert configuration for the child lives on the parent
- alert is raised for the child in the parent
- smtp settings are configured in parent so it can send emails for alerts

When a user clicks the Go To Chart CTA button inside the alert email for an alert raised for the child, she gets re-directed to parent's url instead of the childs.

Email re-direct is using machine guid, referenced as agentId and it seems to be using the parent's machine guid instead of the child's

### Expected behavior

User should be re-directed to child's dashboard, to the affected by the alert chart

### Steps to reproduce

1. Setup a parent and a child streaming through the parent
2. Setup proper smtp settings in parent so it can send emails for alerts
3. Trigger an alert for the child in the parent
4.  Access user's email and follow the Go To Chart CTA inside the email for the raised alert

### Installation method

docker

### System info

```shell
/etc/alpine-release:3.15.0
/etc/os-release:NAME="Alpine Linux"
/etc/os-release:ID=alpine
/etc/os-release:VERSION_ID=3.15.0
/etc/os-release:PRETTY_NAME="Alpine Linux v3.15"
```

### Netdata build info

```shell
Version: netdata v1.33.1-140-gd5baf4ca5
Configure options:  '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libexecdir=/usr/libexec' '--libdir=/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--without-bundled-protobuf' '--with-bundled-libJudy' '--disable-ebpf' 'CFLAGS=' 'LDFLAGS='
Install type: oci
    Binary architecture: x86_64
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    YES
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 YES
    Prometheus Remote Write: YES
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Together with changes from the cloud, it should fix #12376.

If the alert is raised by a parent for a child, it will also pass the child's machine guid to the constructed link for the `Go to chart` button. It should help create a correct redirect to view the child's chart.

##### Test Plan

Will be tested with the cloud.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by stelfrag** [comment]
@MrZammler will we proceed with this one?

**Comment by MrZammler** [comment]
Yes we will. @jacekkolasa has already done some tests with it but I haven't being able to check and close it. Will update soon, sorry.

**Comment by MrZammler** [comment]
Fresh tests:

1) Single agent with this PR, not claimed. Alert link for an alert redirects to cloud, then I'm presented with a link back to the agent dashboard. Works ok.

2) Parent agent with this PR, not claimed. Parent raises an alert for the child. Notification link (generated by the parent) contains also the `childId`. Clicking the link goes to `app.netdata.cloud` where it provides a new link back to the parent, but now contains `/host/childhostname` in the link. Clicking it takes me to the dashboard of the parent showing the dashboard of the child. Works ok.

In both cases I'm shown the correct chart for the alert.

**Comment by MrZammler** [comment]
Doing the same tests with a claimed parent, I get some mixed results...

Clicking the link from an alert for a child takes me to the cloud, but it's reported that the chart does not exist any more on the node. However this could be a result of my flawed tests or another problem, since if I remove the `childId` from the link of the alert I get the same behavior.

I think that as far as the original problem is concerned this PR along with @jacekkolasa changes fixes it, but we need to have a look in general. cc @dimko

**Comment by dimko** [comment]
@MrZammler let's sync so we can test it together

**Review by thiagoftsm — APPROVED** [review]
I put the child to compile Linux kernel and when I accessed the cloud I could see the alert clicking on link. LGTM!

**Review by vlvkobal — APPROVED** [review]

**Comment by MrZammler** [comment]
Thanks!

**Pull request merged**
