### PR TITLE
Extend aclk-state

### LINKED ISSUE #12409: [Feat]: When ACLK is not connected, it should state when it will reconnect
### Problem

When a node is not online, `aclk-state` should indicate when it will be the next time to reconnect:

```sh
# /opt/netdata/bin/netdatacli aclk-state
ACLK Available: Yes
ACLK Version: 2
Protocols Supported: Legacy, Protobuf
Protocol Used: Legacy
Claimed: Yes
Claimed Id: fdb94188-9730-11ec-aab7-dca632bb8656
Cloud URL: https://app.netdata.cloud
Online: No
Reconnect count: 69
```

Also, it would be useful to state:

1. The time it was last connected
2. The time it last attempted to connect and
3. The reason of the last disconnection or last failed connection attempt

Something like:

```sh
# /opt/netdata/bin/netdatacli aclk-state
ACLK Available: Yes
ACLK Version: 2
Protocols Supported: Legacy, Protobuf
Protocol Used: Legacy
Claimed: Yes
Claimed Id: fdb94188-9730-11ec-aab7-dca632bb8656
Cloud URL: https://app.netdata.cloud
Online: No
Reconnect count: 69

Last Connection: DATETIME
Last Disconnection: DATETIME
Last Disconnection Message: connection refused | disconnected from cloud | other error

Reconnection exponential backoff: DURATION
Next Connection Attempt: DATETIME
```

### Description

As above.

### Importance

must have

### Value proposition

Users should have visibility on cloud connection attempts and failures

### Proposed implementation

As above

### PR DESCRIPTION
**Pull request by underhood**
Fixes #12409

##### Summary
Adds information about last connection time(if any), when was previous connection closed (if any), information when next connection attempt will be made(if offline and delaying reconnection)

##### Test Plan
hit `/api/v1/aclk-state`

### CODE REVIEW

**Comment by stelfrag** [comment]
> hit `/api/v1/aclk-state`

Did you mean `/api/v1/aclk` or the `aclk-state` cli option?

**Comment by underhood** [comment]
> The `/api/v1/aclk` provides node instance information when the connection is "down". The CLI `aclk-state` command does not. Is this intentional?

There is also `aclk-state json` which is same as the api/v1 and yes it is intentional: Idea is the non-JSON version is meant for humanz, while JSON is geared more towards machine processing. For same reason the values are null in JSON while text version just skips irrelevant values.

**Comment by underhood** [comment]
> > hit `/api/v1/aclk-state`
> 
> Did you mean `/api/v1/aclk` or the `aclk-state` cli option?

It is more or less the same the `cli` option allows you to choose `aclk-state` (human version) and `aclk-state json`. API/V1 is the same thing but uses json.

**Comment by stelfrag** [comment]
Please make a new issue with anything that was asked but was not implemented in this PR (because it required more extensive work / changes etc)

**Review by MrZammler — APPROVED** [review]
Looks good!

**Pull request merged**
