### PR TITLE
add netdata demo rooms to the list of demo urls

### PR DESCRIPTION
**Pull request by andrewm4894**
##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by tkatsoulas — DISMISSED** [review]

**Comment by Ancairon** [comment]
@andrewm4894 nice addition, while we are at it, where should this file live on Learn? Currently it is in the Misc section at the bottom, as I didn't find any fitting place..

**Comment by andrewm4894** [comment]
Not really sure tbh - i think it could merit its own top level section or maybe be part of getting started - not sure though

hidden in misc is not great alrite but not too sure

**Comment by ilyam8** [comment]
@Ancairon @Ancairon should we just add one link to "All nodes" (the same as "Live Demo" on the website), otherwise this list will be out of sync pretty soon.

**Comment by andrewm4894** [comment]
eg as a user id love to end up on list like this and will be more likley then to click on one of those links that interests me most https://github.com/andrewm4894/netdata/blob/demo-docs/docs/Demo-Sites.md

**Comment by Ancairon** [comment]
@andrewm4894 what about putting it here:

image

Pretty high up, as it has nothing to do with the bottom-most stuff

**Comment by andrewm4894** [comment]
@Ancairon i like that idea and was thinking same - its shop window so should be near top

**Review by Ancairon — APPROVED** [review]

**Review by Dim-P — APPROVED** [review]

**Pull request merged**
