### PR TITLE
Fix pandas category

### PR DESCRIPTION
**Pull request by shyamvalsan**
Fix pandas category

### CODE REVIEW

**Comment by andrewm4894** [comment]
this PR seems to do a lot of other stuff too?

**Comment by shyamvalsan** [comment]
> this PR seems to do a lot of other stuff too? need to update it from upstream/master maybe?

Those other things are already merged, guess I re-used the branch is why they show up

**Comment by andrewm4894** [comment]
i think you will need to do a fresh PR as i still see 15 files being changed

**Comment by andrewm4894** [comment]
i can do this one in a clean PR

**Pull request closed without merging**
