### PR TITLE
eBPF cgroup and mutex

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
This PR address an issue with previous PRs and also rename charts to have a unique pattern when we work with `systemd`. It is fixing:
-  Wrong dimensions for network charts:
```sh
Jun 10 11:27:48 pve-deb-work netdata[2951725]: PLUGINSD: 'host:pve-deb-work/chart:systemd.systemd_fail2banoutbound_conn_v4/dim:connections' got a SET but dimension does not exist.
Jun 10 11:27:48 pve-deb-work netdata[2951725]: PLUGINSD: parser_action('SET') failed on line 6662: { 'SET' 'connections' '0' } (quotes added to show parsing)
```
- Remove suffixes that are not used in other charts made by `cgroup.plugin`. Renaming charts from `systemd.systemd_systemd-homedoutbound_conn_v4` to `systemd_systemd-homed.outbound_conn_v4`.
- Cgroup labels
- Context name.

This PR also fix issues with mutex that created wrong dimensions.

##### Test Plan

1. Take a look on CI
2. Compile this branch on an environment that has cgroup v2.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by ilyam8** [comment]
This is not fixed.

Screenshot 2024-06-17 at 15 23 20

---

Can you tell me what you are fixing in this PR? It would be nice to update the description. It is not clear what this PR is doing.

**Comment by ilyam8** [comment]
Cloud you pay attention to https://github.com/netdata/netdata/pull/17915#issuecomment-2173259696 and fix the problem on the screenshot? Or do you not see any problems there?

**Comment by ilyam8** [comment]
And label values look strange (double "systemd")

Screenshot 2024-06-18 at 20 51 12

**Comment by ktsaou** [comment]
@thiagoftsm we need ebpf fixed please.

ebpf.plugin stops on my system with:

```
time=2024-06-28T22:58:35.507+03:00 comm=netdata source=daemon level=error tid=131422 thread=PD[ebpf] module=plugins.d[ebpf.plugin] node=costa-desktop instance=systemd.systemd_containerdoutbound_conn_v4 context=systemd.services.net_conn_ipv4 src_transport=pluginsd request="'SET' 'connections' '0'" msg="PLUGINSD: 'host:costa-desktop/chart:systemd.systemd_containerdoutbound_conn_v4/dim:connections' got a SET but dimension does not exist."
time=2024-06-28T22:58:35.507+03:00 comm=netdata source=daemon level=error tid=131422 thread=PD[ebpf] module=plugins.d[ebpf.plugin] node=costa-desktop instance=systemd.systemd_containerdoutbound_conn_v4 context=systemd.services.net_conn_ipv4 src_transport=pluginsd request="'SET' 'connections' '0'" msg="PLUGINSD: parser_action('SET') failed on line 41185: { 'SET' 'connections' '0' } (quotes added to show parsing)"
```

Please fix it asap.

**Comment by ktsaou** [comment]
@stelfrag please make sure ebpf plugin works as expected.

**Comment by ktsaou** [comment]
What is the status of this?

**Comment by thiagoftsm** [comment]
> What is the status of this?

I began to work with it last night again, and I already addressed some issues with `cgroup v1`. I am going to test on other environments and either fix it or set ready for review.

Best regards!

**Comment by thiagoftsm** [comment]
> @thiagoftsm we need ebpf fixed please.
> 
> ebpf.plugin stops on my system with:
> 
> ```
> time=2024-06-28T22:58:35.507+03:00 comm=netdata source=daemon level=error tid=131422 thread=PD[ebpf] module=plugins.d[ebpf.plugin] node=costa-desktop instance=systemd.systemd_containerdoutbound_conn_v4 context=systemd.services.net_conn_ipv4 src_transport=pluginsd request="'SET' 'connections' '0'" msg="PLUGINSD: 'host:costa-desktop/chart:systemd.systemd_containerdoutbound_conn_v4/dim:connections' got a SET but dimension does not exist."
> time=2024-06-28T22:58:35.507+03:00 comm=netdata source=daemon level=error tid=131422 thread=PD[ebpf] module=plugins.d[ebpf.plugin] node=costa-desktop instance=systemd.systemd_containerdoutbound_conn_v4 context=systemd.services.net_conn_ipv4 src_transport=pluginsd request="'SET' 'connections' '0'" msg="PLUGINSD: parser_action('SET') failed on line 41185: { 'SET' 'connections' '0' } (quotes added to show parsing)"
> ```
> 
> Please fix it asap.

I do not have anymore this issue with this branch when I am running on Arch or Debian. I am also reorganizing chart names to be more readable:

```sh
"systemd_dbus.outbound_conn_v4":{
            "id":"systemd_dbus.outbound_conn_v4",
            "name":"systemd_dbus.outbound_conn_v4",
            "type":"systemd_dbus",
            "family":"net",
            "context":"systemd.service.net_conn_ipv4",
            "title":"Calls to tcp_v4_connection (systemd_dbus.outbound_conn_v4)",
            "priority":20080,
            "plugin":"ebpf.plugin",
            "module":"socket",
            "units":"connections/s",
            "data_url":"/api/v1/data?chart=systemd_dbus.outbound_conn_v4",
            "chart_type":"stacked",
            "duration":1160580,
            "first_entry":1718686895,
            "last_entry":1719847470,
            "update_every":5,
            "dimensions":{
                "connections":{
                    "name":"connections"
                }
            },
            "chart_variables":{
            },
            "green":null,
            "red":null,
            "alarms":{
            },
            "chart_labels":{
                "_collect_module":"socket",
                "service_name":"dbus",
                "_collect_plugin":"ebpf.plugin"
            },
            "functions":{
            }
        },
```

I am proceeding with tests to do possible adjusts, before set PR ready for review.

**Comment by thiagoftsm** [comment]
@ilyam8 ,

On Arch I have normal labels when I compare ebpf chargs with cgroup charts:

Screenshot_20240701_232905

I am going to test now on other distributions to confirm and set this PR ready for review.

**Comment by ilyam8** [comment]
Still a mess: 

1. systemd services oom chart context is `cgroup.oomkills`
2. systemd service network traffic context is ` total_bandwidth` which makes it appear as a top-level section

Screenshot 2024-07-02 at 12 15 38


This was a quick check, I didn't check each chart.

**Comment by thiagoftsm** [comment]
>     1. systemd services oom chart context is `cgroup.oomkills` (3rd time reporting this problem smh)
> 
>     2. systemd service network traffic context is ` total_bandwidth` which makes it appear as a top-level section

Last commit addressed these, now I am going to set the PR as draft, to start a last round of tests, before to set it ready for review again.

**Comment by thiagoftsm** [comment]
I am going to keep this PR running few hours before set it ready for review, to be sure nothing is missed.

**Review by stelfrag — APPROVED** [review]

**Pull request merged**
