### PR TITLE
Set CFLAGS appropriately so all warnings are treated as errors during CI buidls

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

SSIA

##### Component Name

- area/ci

##### Test Plan

- CI

##### Additional Information

### CODE REVIEW

**Comment by vlvkobal** [comment]
I've tried to test it with #8567. It should trigger the following warning
```
claim/claim.c:7:14: warning: 'test_ci_checks' defined but not used [-Wunused-variable]
    7 | static char *test_ci_checks = "test";
      |              ^~~~~~~~~~~~~~
```
But the output of `run_install_with_dist_file.sh` is [clean](https://github.com/netdata/netdata/pull/8567/checks?check_run_id=551517225).

**Comment by vlvkobal** [comment]
To treat warnings as errors we should also add `-Werror`, but if we do that, the `./configure` step can't be completed:
```
checking for pthread-config... no
configure: error: Cannot initialize pthread environment
 FAILED
```

**Comment by prologic** [comment]
> To treat warnings as errors we should also add `-Werror`, but if we do that, the `./configure` step can't be completed:

Ahh I will add that now.

> ```
> checking for pthread-config... no
> configure: error: Cannot initialize pthread environment
>  FAILED
> ```

How do we address this?

**Comment by mfundul** [comment]
We can't treat warnings as errors, there is at least one case where the warnings cannot be avoided:
https://github.com/netdata/netdata/issues/2504

**Comment by vlvkobal** [comment]
I'm not sure it is possible to address the `configure` error. `config.log`:
```
| /* end confdefs.h.  */
| #include <pthread.h>
|                         static void routine(void *a) { a = 0; }
|                         static void *start_routine(void *a) { return a; }
| int
| main ()
| {
| pthread_t th; pthread_attr_t attr;
|                         pthread_create(&th, 0, start_routine, 0);
|                         pthread_join(th, 0);
|                         pthread_attr_init(&attr);
|                         pthread_cleanup_push(routine, 0);
|                         pthread_cleanup_pop(0) /* ; */
|   ;
|   return 0;
| }
configure:7341: result: no
configure:7252: checking for pthread-config
configure:7280: result: no
configure:7528: error: Cannot initialize pthread environment
```

**Comment by prologic** [comment]
Closing as per comments about; this will not work currently as `./configure` bombs out and there are serious warnings we cannot work around (_allegedly_).

**Pull request closed without merging**
