### PR TITLE
Fix missing NETDATA_STOP_CMD in netdata-installer.sh

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

ssia

##### Component Name

- area/packaging

##### Test Plan

- [x] Test on a SystemD system
- [x] Test on macOS
- [x] Test on FreeBSD
- [ ] Test on a SysV system
- [x] Test on something non-standard

##### Additional Information

Looks like this was always missing in our packaging tooling :/

### CODE REVIEW

**Comment by prologic** [comment]
<details>
<summary>
Tested on non-Standard systems (_plain 'ol install with no supervisor/init managing Netdata_):
</summary

```
$ ./netdata-installer.sh --dont-wait --dont-start-it --disable-go --install /tmp/netdata
.
.
.
To stop netdata run:

  /tmp/netdadta/netdata/usr/bin/netdatacli shutdown-agent

To start netdata run:

  /tmp/netdadta/netdata/usr/sbin/netdata
.
.
.
```
</details>

**Comment by thiagoftsm** [comment]
@prologic `shellcheck` continues giving error:

```
          NETDATA_STOP_CMD="rc-service netdata stop"
          ^--------------^ SC2034: NETDATA_STOP_CMD appears unused. Verify use (or export if used externally).

```

**Comment by thiagoftsm** [comment]
Everything worked as expected on Slackware current, when you finish the work I will retest and approve it.

**Comment by prologic** [comment]
<details>
<summary>
Tested on a SystemD system (_Debian Buster_):
</summary>

```#!sh
$ sudo ./netdata-installer.sh --dont-wait --disable-go
.
.
.
To stop netdata run:

  systemctl stop netdata

To start netdata run:

  systemctl start netdata
.
.
.
```
</details>

**Comment by prologic** [comment]
<details>
<summary>
Tested on FreeBSD:
</summary>

```#!sh
root@freebsd:~/netdata # ./netdata-installer.sh --dont-wait --disable-go
.
.
.
To stop netdata run:

  service netdata stop

To start netdata run:

  service netdata start
.
.
.

```
</details>

**Comment by prologic** [comment]
Rebasing...

**Pull request merged**
