### PR TITLE
[wip] extract OpenVZ container names; 

### LINKED ISSUE #2474: Question: Is netdata capable of monitoring openVZ containers?
We see that netdata is good for monitoring LXD containers but having googled for a while we cannot see if it is possible for us to monitor OpenVZ containers.

If this is the case then is there a guide or tutorial as to how this is done? We'd really like to use your system as it appears head and shoulders above the others in terms of usability (in terms of end user as well as from our developers point of view).

Sorry, not sure how to tags this as a question.

### PR DESCRIPTION
**Pull request by ktsaou**
##### Summary

Collect OpenVZ container names.

fixes #2474

##### Component Name

collectors/cgroups.plugin

### CODE REVIEW

**Comment by yoorshop** [comment]
No change at the moment

**Comment by ktsaou** [comment]
> No change at the moment

hm... could you please provide the output of:

```
grep cgroup-name.sh /var/log/netdata/error.log
```

I probably misspelled something.

**Comment by yoorshop** [comment]
[root@vps ~]# grep cgroup-name.sh /opt/netdata/var/log/netdata/error.log
[root@vps ~]#

**Comment by ktsaou** [comment]
hm... do you have any containers monitored by this netdata?

**Comment by yoorshop** [comment]
There is 45 VM on this node, and netdata see ID correctly, only all process numbers

**Comment by ktsaou** [comment]
hm... may be the log has been rotated. Could you please restart netdata and `grep` it again?

**Comment by yoorshop** [comment]
No...

Here is an overview of log content :

2018-12-04 10:32:43: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/memory' (errno 13, Permission denied)
2018-12-04 10:32:43: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/devices' (errno 13, Permission denied)
2018-12-04 10:32:54: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/cpu,cpuacct' (errno 13, Permission denied)
2018-12-04 10:32:54: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/blkio' (errno 13, Permission denied)
2018-12-04 10:32:54: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/memory' (errno 13, Permission denied)
2018-12-04 10:32:54: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/devices' (errno 13, Permission denied)
2018-12-04 10:33:05: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/cpu,cpuacct' (errno 13, Permission denied)
2018-12-04 10:33:05: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/blkio' (errno 13, Permission denied)
2018-12-04 10:33:05: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/memory' (errno 13, Permission denied)
2018-12-04 10:33:05: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/devices' (errno 13, Permission denied)
2018-12-04 10:33:15: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/cpu,cpuacct' (errno 13, Permission denied)
2018-12-04 10:33:15: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/blkio' (errno 13, Permission denied)
2018-12-04 10:33:15: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/memory' (errno 13, Permission denied)
2018-12-04 10:33:15: netdata ERROR : PLUGIN[cgroups] : CGROUP: cannot read directory '/sys/fs/cgroup/devices' (errno 13, Permission denied)
2018-12-04 10:33:25: netdata LOG FLOOD PROTECTION too many logs (201 logs in 524 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 676 seconds.

**Comment by yoorshop** [comment]
Bonjour,
Re,

netdata show nothing about users that could be identified as containers

This is the reason of the feature/ bug request, and it seems that it 
works for proxmox or else (no proof except orignal request from another 
user)

You could setup a test server with ISO openvz7 + trial Virtualizor /ie, 
and see by yourself...

Cordialement, Yours faithfully,
Johann Carnevali

**Comment by cakrit** [comment]
Closing and @vlvkobal will attempt to provide a proper fix

**Pull request closed without merging**
