### PR TITLE
Overhaul build CI.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This makes a number of changes to our various build and updater checks:

* The release-build.yml workflow has been renamed to just build.yml
* The updater.yml and build-and-install.yml workflows have been consolidated into the build.yml workflow.
* The updater checks now use the dist tarball produced by the dist tarball build instead of building one for each matrix job.
* The updater and build checks now use a set of jobs for generating their test environments that allow the environments to be generated once for both sets of checks.
* The updater and build checks and their shared test environment builds now use a unified build matrix, handled in an external data file (`.github/data/build-matrix.json`).
* Nightly artifact uploads and release creation are now dependent on the updater and build checks passing.

Overall, this will reduce duplication of work in CI (improving overall CI speed somewhat), reduce the risk of publishing broken nightlies or releases, and somewhat simplify maintenance of the build checks.

##### Component Name

area/ci

##### Test Plan

New CI checks show up as expected on this PR, and all pass properly.

### CODE REVIEW

**Review by iigorkarpov — DISMISSED** [review]

**Comment by Ferroin** [comment]
Rebased to pick up Alpine 3.11 removal from CI.

**Review by iigorkarpov — APPROVED** [review]

**Comment by Ferroin** [comment]
Rebased to pick up Fedora 35 CI jobs.

**Review by maneamarius — APPROVED** [review]
Looks good!

**Review by iigorkarpov — DISMISSED** [review]

**Comment by Ferroin** [comment]
OK, this _finally_ should all be working correctly (except for the bogus eslint run and the handful of known broken package builds that are unrelated to these changes.

**Review by iigorkarpov — APPROVED** [review]

**Review by maneamarius — APPROVED** [review]
looks good :)

**Pull request merged**
