### PR TITLE
Fix time_t format

### LINKED ISSUE #11830: netdata(V1.30.1) plugin  segfault  on openwrt(LEDE x86_32) with musl 1.2.2
[   56.036301] PLUGIN[diskspac[5977]: segfault at 4b0 ip b7f5aee6 sp b764c140 error 4 in libc.so[b7f58000+50000]
[   56.036553] Code: 00 8d 76 00 0f b6 08 39 d9 74 5a 83 c0 01 83 ea 01 a8 03 74 0f 85 d2 75 eb 31 c9 5b 89 c8 5e 5f c3 8d 76 00 31 c9 85 d2 74 f1 <0f> b6 08 39 d9 74 34 69 f3 01 01 01 01 83 fa 03 77 13 eb 27 8d b6

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
`time_t` type may be different on different platforms. We should cast it to a definite type before printing.

Fixes #11830

Thank you @WYC-2020!

##### Test Plan
The PR was tested on the `openwrt/openwrt` master branch.
1. Prepare an OpenWrt build for 32bit architecture (x86 generic). It's a very lo-o-ong and space-consuming process 😉.
```
git clone https://git.openwrt.org/openwrt/openwrt.git
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig
make -j8
```
2. Make changes to the netdata package
- `Makefile`
```
PKG_VERSION:=time_t-format
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_SOURCE_URL:=https://codeload.github.com/vlvkobal/netdata/tar.gz/$(PKG_VERSION)?
PKG_HASH:=4c9615cde21e427c0ab3d900a6acdb0ba7468b89507e8ab480e699f182b8d86a

DEPENDS:=+zlib +libuuid +libuv +libmnl +libjson-c +libopenssl

TARGET_LDFLAGS += -Wl,--gc-sections,-lssl,-lcrypto
```
- Remove patches for `index.html`
- Add a patch for `database/sqlite/sqlite_functions.h`
```
--- a/database/sqlite/sqlite_functions.h
+++ b/database/sqlite/sqlite_functions.h
@@ -3,6 +3,7 @@
 #ifndef NETDATA_SQLITE_FUNCTIONS_H
 #define NETDATA_SQLITE_FUNCTIONS_H

+#include <openssl/evp.h>
 #include "daemon/common.h"
 #include "sqlite3.h"

```
3. Rebuild the netdata package and make sure all the warnings for `time_t` are gone. 
```
make -j1 V=sc
```

### CODE REVIEW

**Comment by vlvkobal** [comment]
@WYC-2020, could you test the PR on your OpenWrt system?

**Comment by WYC-2020** [comment]
@vlvkobal You can give me a patch, I will test it

**Comment by vlvkobal** [comment]
@WYC-2020 isn't it easier just to checkout the PR?
```
git fetch origin pull/11897/head:pr/vlvkobal/11897
git checkout pr/vlvkobal/11897
```
Anyway, if you like it better, here's the [patch](https://github.com/netdata/netdata/commit/462b70c051478da59463374bc630cd2367558475.patch).

**Review by thiagoftsm — DISMISSED** [review]
I tested with gcc 11.2 and on CentOS 7.9 to get an old gcc version, and I did not observe any error. LGTM!

**Comment by WYC-2020** [comment]
@vlvkobal Test, you can

**Comment by vlvkobal** [comment]
> @vlvkobal Test, you can

@WYC-2020 it looks like your message is incomplete. Could you please write it in full?

**Review by thiagoftsm — APPROVED** [review]
I retest with gcc 11.2 on Slackware current, on CentOS 7.9 to get an old gcc version, and on Alpine 3.15.

Everything worked as expected!

**Review by erdem2000 — APPROVED** [review]
Compiling and running in the PC without error.

**Pull request merged**
