### PR TITLE
Move the `contrib/debian` directory to the repo root.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This is where essentially all Debian tooling actually expects it to be found, and it’s not been ‘contrib’ code for a very long time now so keeping it in `contrib` makes no sense.

As this is the last thing that’s actually _in_ `contrib`, also remove the `contrib` directory.

##### Test Plan

CI passes on this PR.

##### Additional Information

This PR has a hard dependency on https://github.com/netdata/helper-images/pull/270, CI will not pass here until after that is merged and the new package builder images are deployed. Once that’s merged, CI should be re-run for this PR.

### CODE REVIEW

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts, no functional changes.

**Comment by vkalintiris** [comment]
@Ferroin @ktsaou, I, and (I believe) @stelfrag want to minimize the amount of top-level directories (for various reasons, one among them is to make the repo less scary to people who look at it in Github). Do you think this could live under `packaging/` or some other place?

**Comment by Ferroin** [comment]
> @Ferroin @ktsaou, I, and (I believe) @stelfrag want to minimize the amount of top-level directories (for various reasons, one among them is to make the repo less scary to people who look at it in Github). Do you think this could live under `packaging/` or some other place?

The standard location is at the root of the repo. We have to jump through hoops currently to make Debian tooling work with the way it is now, and having it at some other location also makes it objectively less obvious that we handle this in the repo itself.

To clarify, this is not some project specific thing or mysterious cryptically named directory like a majority of the other stuff we currently have in the top level of the repo is, so I fail to see how having this _where it should be per Debian packaging standards_ will make the repo ‘scary’ to contributors.

**Comment by vkalintiris** [comment]
@Ferroin I understand your points. My question is if it's possible from a technical point of view to make this work under `packaging/`.

**Comment by Ferroin** [comment]
> @Ferroin I understand your points. My question is if it's possible from a technical point of view to make this work under `packaging/`.

It is possible, but it also adds additional complexity that it would be greatly preferable to not have because it makes it harder for new people to contribute to this area.

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Comment by Ferroin** [comment]
Closing as we have simply removed this directory.

**Pull request closed without merging**
