### PR TITLE
Fix exporting config

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
The `prefix` and `send names instead of ids` options didn't work in the `prometheus:exporter` section of `exporting.conf`. The options should also inherit values from the `backend` section of `netdata.conf` if they are not set in `exporting.conf`. The PR fixes the issue.

##### Component Name
exporting engine, Web API

##### Test Plan
Check the `http://localhost:19999/api/v1/allmetrics?format=prometheus` endpoint with different settings of `prefix` and `send names instead of ids` in `exporting.conf` and `netdata.conf`.

### CODE REVIEW

**Comment by fayak** [comment]
Will it also fix the lack of exported `host tags` / `send configured labels` as per discussed brievly in https://github.com/netdata/netdata/issues/10165 ?

**Comment by vlvkobal** [comment]
I tested `send configured labels` and other options as well. I didn't find any problems with them.

**Review by thiagoftsm — APPROVED** [review]
I tested all combinations suggested now and I had `prefix` for all options.

**Comment by fayak** [comment]
Awesome, thanks a lot !

**Comment by pickfire** [comment]
Do we have to wait for the next version to get this?

**Comment by OdysLam** [comment]
@pickfire welcome to the community!

A new release is just around the corner, but I am not sure if this PR will be included. Let's see what the rest of the team has to say. cheers :)

**Review by stelfrag — APPROVED** [review]

**Review by stevenans9859 — APPROVED** [review]

**Pull request merged**
