### PR TITLE
cleanup updater script and no `/opt` usage

### PR DESCRIPTION
**Pull request by paulfantom**
##### Summary
- Moving code around to have function declarations at the top.
- Adding `eval` when running `${REINSTALL_COMMAND}...`
- More robust download
- Use `$(pwd)` instead of `/opt`

##### Component Name
packaging

### CODE REVIEW

**Comment by paulfantom** [comment]
I can see that there is a conflict GitHub already says it. A proper code review looks at what is going to be submitted and not at merge conflicts.

Also I made this on purpose to have a merge conflict so it won't accidentally be merged before v1.12.0 release.

**Comment by cakrit** [comment]
So it should be WIP. Let me know when to review again...

**Comment by paulfantom** [comment]
ready to review

**Comment by cakrit** [comment]
I ran it both from crontab and shell, tested it with curl and wget, with /tmp and /pwd. I didn't find any problems. I wasn't able to add to the automated test suite, that needs some more time.

**Pull request merged**
