### PR TITLE
netdata/packaging: Refine devel packaging pipeline, update .travis/README.md

### PR DESCRIPTION
**Pull request by paulkatsoulakis**
##### Summary
This PR is about updating our .travis/README. to become more up to date with the latest developments.

It also includes a change in our pipelines, so that binary package publishing to `netdata/netdata-devel` becomes easier for the developer.

I have modified a guard condition on the deployment provider for package cloud, so that when the repository is NOT `netdata/netdata` and the trigger is basically a commit push, then the guard would simple be set to the branch name. With this change if a developer has issued a packaging trigger on a branch on his own git repository, the pipeline will attempt to publish the package to netdata-devel after building it, provided that the developer's Travis CI is properly linked to his forked repository.

**Note**: @knatsakis i will need your help on bringing this on your own repo, then push it to your own forked remote and verify it works because i have removed all set ups from my accounts. I will be available for any questions or any walkthroughs you might need on this.

@joelhans As usual i will need your valuable input on the readme changes. I am open to discuss overall the structure of this document since i went in update it, so anything you see except the actual changes feel free to propose.

##### Component Name
netdata/packaging

##### Additional Information
**Note**: I have pushed in this PR a minor typo i found when troubleshooting a packaging issue.
It's the most recent commit seen.

### CODE REVIEW

**Comment by paulkatsoulakis** [comment]
I am not sure what is happening with CLA assistant, the page refuses to load.
I have changed the emails that is why i need to re-sign.
I will try later tonight from home, might be something with the public network, i got some 502 from cloudflare at some point

**Comment by joelhans** [comment]
A question before I spend time diving in: Is this internal documentation? Would a user ever need to or be able to use this README to solve some issue of theirs?

**Comment by cosmix** [comment]
@joelhans this is mostly for the team and contributors, not end-users.

**Comment by Ferroin** [comment]
Closing this as it’s not likely to ever be merged at this point for multiple reasons (the biggest of which being that we’re migrating to GitHub Actions for CI).

**Pull request closed without merging**
