### PR TITLE
Fix compilation warnings

### PR DESCRIPTION
**Pull request by stelfrag**
##### Summary
Fix compilation warnings when compiling with NETDATA_INTERNAL_CHECKS or NETDATA_DEV_MODE

### CODE REVIEW

**Review by vkalintiris — APPROVED** [review]

**Comment by vkalintiris** [comment]
@stelfrag okay to merge this at the end of the day? I and @Ferroin are both modifying the https://github.com/netdata/netdata/pull/15996 PR and CI won't run if there are merge conflicts.

**Comment by stelfrag** [comment]
> @stelfrag okay to merge this at the end of the day? I and @Ferroin are both modifying the #15996 PR and CI won't run if there are merge conflicts.

okay!

**Review by thiagoftsm — APPROVED** [review]
PR was compiled without warnings, LGTM!

**Comment by thiagoftsm** [comment]
> @stelfrag okay to merge this at the end of the day? I and @Ferroin are both modifying the #15996 PR and CI won't run if there are merge conflicts.

PR is ready to be merged @vkalintiris !

**Comment by vkalintiris** [comment]
@stelfrag we can actually merge this now.

**Pull request merged**
