### PR TITLE
Remove netdatacli response size limitation

### LINKED ISSUE #14755: [Feat]: Provide a way to dump current `netdata.conf` without needing to use the REST API.
### Problem

Right now, the only way to get a ‘default’ `netdata.conf` file is to start the agent and query the `/netdata.conf` API endpoint. This works well enough for checking the effective configuration of a running agent, but it also means that `edit-config netdata.conf` doesn’t work as users expect if there is no `netdata.conf` file, and that you can’t check the effective configuration if you have the web server disabled.

### Description

We should have a way to fetch the same data that is provided by the `/netdata.conf` endpoint.

In an ideal situation, this would be an option for the agent like `-W dumpconfig` which simply writes the same data to `stdout`.

In a less ideal situation, a similar command for `netdatacli` would also work, as that would still allow us to dump the configuration without needing to hit the API directly.

### Importance

really want

### Value proposition

1. Once actually implemented, this can be integrated with the `edit-config` script to better handle the case of a user going to edit `netdata.conf` when it does not already exist.
2. Users who do not have the web server enabled can still check the effective configuration locally.
3. If the `-W` option approach is taken, this can also be used as a primitive config validation tool for `netdata.conf`.

### Proposed implementation

_No response_

### PR DESCRIPTION
**Pull request by stelfrag**
##### Summary

- Removes the 4K char response size limitation
- Add a `netdatacli dumpconfig` command to get the current `netdata.conf`

Fixes #14755

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @stelfrag ,

Your PR is working as expected:

```sh
[root@192 netdata]# curl -o http.json http://localhost:19999/netdata.conf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24906  100 24906    0     0  4244k      0 --:--:-- --:--:-- --:--:-- 4864k
[root@192 netdata]# netdatacli dumpconfig > cli.json
[root@192 netdata]# diff cli.json http.json
799d798
< 
[root@192 netdata]# netdatacli reload-health
[root@192 netdata]# netdatacli help

The commands are (arguments are in brackets):
help
    Show this help menu.
reload-health
    Reload health configuration.
reload-labels
    Reload all labels.
save-database
    Save internal DB to disk for memory mode save.
reopen-logs
    Close and reopen log files.
shutdown-agent
    Cleanup and exit the netdata agent.
fatal-agent
    Log the state and halt the netdata agent.
reload-claiming-state
    Reload agent claiming state from disk.
ping
    Return with 'pong' if agent is alive.
aclk-state [json]
    Returns current state of ACLK and Cloud connection. (optionally in json).
dumpconfig
    Returns the current netdata.conf
version
    Returns the netdata version.
```

As you can see the major difference between the two `netdata.conf` I got is a blank line, and it is not necessary to modify nothing in my understand. I will only do a small requirement, please, modify the sentence `Returns the current netdata.conf` for something like `Returns the current netdata.conf on stdout`. I have concerns that users when read the actual help would understand that we would return a `netdata.conf` file instead to write on `stdout`.

Thanks!

**Comment by stelfrag** [comment]
> As you can see the major difference between the two `netdata.conf` I got is a blank line, and it is not necessary to modify nothing in my understand. I will only do a small requirement, please, modify the sentence `Returns the current netdata.conf` for something like `Returns the current netdata.conf on stdout`. I have concerns that users when read the actual help would understand that we would return a `netdata.conf` file instead to write on `stdout`.

I changed the message and added `on stdout.` .. :+1: :smiley:

**Review by thiagoftsm — APPROVED** [review]
As I said yesterday, the PR is working as expected and with latest commit it is ready to go, LGTM!

**Review by MrZammler — APPROVED** [review]
Tested the commands, works fine!

**Pull request merged**
