### PR TITLE
[WIP] Allow netdata configuration using HTTP API, for UI configuration using agent or cloud dashboard

### PR DESCRIPTION
**Pull request by underhood**
Update on 12/06/2023 based on meeting result.

*This PR serves as both documentation/design and implementation of what as an end goal will be - netdata dynamic configuration.
Few lines of code have been written. API and persistence is partially working now*

# Summary
Allow configuration using HTTP API.
Point is to allow stuff like adding monitoring of `URL x` uptime to agent using GUI (cloud or agent). Without need to get hands dirty editing some arcane configs somewhere in `/etc`

Initial version has to work with internal netdata webserver, h2o support will be added later.

### BIG OPEN DESIGN QUESTIONS:
- authentication/rights/users (TBD) - currently it just trusts everyone

### Persistence
Folder structure based on the plugin/module hierarchy, file per config.
~JSON in the file as default.~ Agent will not care about contents of the file for the plugins.
For internal configs it will be JSON?

Location is planned to be: `/var/lib/netdata/config/[plugin][/module][/job_unique_id]`

### PLUGINS INTERFACE
    - send the contents of the configuration file which has been updated to the plugin trough streaming
    - plugin has to verify validity of the config and reply OK/FAIL
    - if OK agent will update the file on disk with new configuration (persist it)

- commands (bi-dir), NEW, UPDATED, DELETED JOB (with OK/FAIL response)
- commands (bi-dir), CONFIGURATION of plugin/module updated (with OK/FAIL response)
- command (plugin->netdata) to register
- command (plugin->netdata) report status of job

### Job status tracking
As the dynamic configuration will have to keep track of all plugins, their modules and jobs in netdata dictionaries, it is also good place to store the status of every job.

Status is an object with bool (ok/fail) and string (reason of failure).

This is to be exported trough HTTP API so that it can be presented to user in the UI.

### Configuration API:
New endpoint `/api/v2/config`

#### URLs and their meanings
General format `/api/v2/config/[plugin]/[module]/[unique_job_id]`
Plugins/parts of netdata etc. can register zero, one or more `modules`. Module can report whether it accepts jobs (array of configurable items).

Imagine as use case a http endpoint pinger who will register under name as `http_check`

- `GET /api/v2/config` - list of all configurable modules and general info about them (like config format)

from here I use (for now imaginary) http_check module of go_d plugin for example

- `GET /api/v2/config/go_d` - get configuration of go_d plugin
- `GET /api/v2/config/go_d/schema` - get schema of go_d plugin configuration **IN WHAT LANGUAGE** ? This should allow UI to build form to modify the configuration automatically without hard-coding anything *(originally when JSON was enforced i wanted to use json shcema see https://json-schema.org/implementations.html#web-ui-generation)*. Now no idea
- `GET /api/v2/config/go_d/http_check` - get current configuration of http_check module (JSON)
- `PUT /api/v2/config/go_d/http_check` - update configuration of http_check module (JSON)
- `GET /api/v2/config/go_d/htto_check/schema` - get schema of http_check module configuration **IN WHAT LANGUAGE** ? This should allow UI to build form to modify the configuration automatically without hard-coding anything *(originally when JSON was enforced i wanted to use json shcema see https://json-schema.org/implementations.html#web-ui-generation)*. Now no idea
- `GET /api/v2/config/go_d/modules` - gets list of configurable modules of the `go_d` plugin and **whether they accept jobs**.

from here sample of how to configure jobs for `go_d/http_check`

- `GET /api/v2/config/go_d/http_check/jobs` - Get list of all configured jobs and their total count
- `GET /api/v2/config/go_d/http_check/1234-567-890` - Get configuration of individual monitor by its unique ID (this can be anything as long as it is unique per job
- `POST /api/v2/config/go_d/http_check/job` - adds new monitor for http_check (in case of this module this is new URL to be monitored), agent will assign new unique identifier to it and return it in reply
- `GET /api/v2/config/go_d/http_check/job/schema` - returns the SCHEMA that UI can use to build form used to add new monitor and/or modify existing monitor. **WHAT FORMAT**
- `PUT /api/v2/config/go_d/http_check/1234-567-890` - updates configuration of existing monitor
- `DELETE /api/v2/config/go_d/http_check/1234-567-890` - self explanatory

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by underhood** [comment]
updated info about on disk persistence

**Comment by underhood** [comment]
@Ferroin any comments about the persistence section? What would right path be, any potential issues you see (permissions?)

**Comment by ktsaou** [comment]
Netdata Plugins Configuration drawio

**Comment by underhood** [comment]
superseded by https://github.com/netdata/netdata/pull/15486 (which is cleaned up mergable version without h2o support for now)

**Pull request closed without merging**
