### PR TITLE
Docker-based packaging workflow in GitHub Actions.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This implements a new Docker-based packaging CI workflow in GitHub Actions. It still uses the same trigger commits as the existing LXC-based workflow we have in Travis so that minimal changes are needed to have it work correctly.

This requires the addition of two secrets to the repository itself:

* `PACKAGE_CLOUD_REPO`: This specifies which PackageCloud repository to push the packages to.
* `PACKAGE_CLOUD_API_KEY`: This specifies the PackageCloud API key to use when uploading packages.

This leverages GitHub Actions' matrix build feature to keep overall code in the workflow file to a minimum.

##### Component Name

area/ci
area/packaging

##### Additional Information

Fixes: #7346 
Fixes: #7822 

The only remaining testing needed for this to be ready for review is verification that the package upload logic works correctly.

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- .github/commit-filter-action/node_modules/pump/index.js  7
- .github/commit-filter-action/node_modules/lodash.uniq/index.js  17
- .github/commit-filter-action/node_modules/node-fetch/lib/index.es.js  38
- .github/commit-filter-action/node_modules/once/once.js  2
- .github/commit-filter-action/node_modules/is-stream/index.js  4
- .github/commit-filter-action/node_modules/isexe/test/basic.js  7
- .github/commit-filter-action/node_modules/isexe/mode.js  11
- .github/commit-filter-action/node_modules/wrappy/wrappy.js  4
- .github/commit-filter-action/node_modules/signal-exit/index.js  4
- .github/commit-filter-action/node_modules/isexe/windows.js  7
- .github/commit-filter-action/node_modules/pump/test-node.js  4
- .github/commit-filter-action/node_modules/p-finally/index.js  2
- .github/commit-filter-action/node_modules/execa/lib/stdio.js  10
- .github/commit-filter-action/node_modules/execa/index.js  10
- .github/commit-filter-action/node_modules/isexe/index.js  6
- .github/commit-filter-action/node_modules/pump/test-browser.js  4
- .github/commit-filter-action/node_modules/shebang-command/index.js  4
- .github/commit-filter-action/node_modules/strip-eof/index.js  5
- .github/commit-filter-action/node_modules/node-fetch/browser.js  4
- .github/commit-filter-action/node_modules/node-fetch/lib/index.js  38
- .github/commit-filter-action/node_modules/which/which.js  14
- .github/commit-filter-action/node_modules/semver/semver.js  28
- .github/commit-filter-action/node_modules/nice-try/src/index.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=4991415&bid=16477389)

**Comment by prologic** [comment]
Can we split the custom github action out into its own `netdata/filter-commit-action` repo?

**Comment by Ferroin** [comment]
> Can we split the custom github action out into its own `netdata/filter-commit-action` repo?

Yeah, I can do so if desired. I was hesitant to do it until we were certain that this is how we wanted things to work though, so at least a quick review here of the code for it would be nice.

**Comment by prologic** [comment]
> > Can we split the custom github action out into its own `netdata/filter-commit-action` repo?
> 
> Yeah, I can do so if desired. I was hesitant to do it until we were certain that this is how we wanted things to work though, so at least a quick review here of the code for it would be nice.

Oh yeah no I'm fine with this! I just can't review this properly because there are too many files :/

Can you maybe at least split the PR into two so I can largely ignore the one that adds the action to `.github/actions`?

**Comment by Ferroin** [comment]
@prologic I've restructured things so that it's two commits, the first one adding the new action, and the second adding the workflow. If you still need it split into two PR's please let me know.

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- .github/commit-filter-action/node_modules/shebang-command/index.js  4
- .github/commit-filter-action/node_modules/nice-try/src/index.js  2
- .github/commit-filter-action/node_modules/isexe/mode.js  11
- .github/commit-filter-action/node_modules/node-fetch/browser.js  4
- .github/commit-filter-action/node_modules/wrappy/wrappy.js  4
- .github/commit-filter-action/node_modules/once/once.js  2
- .github/commit-filter-action/node_modules/node-fetch/lib/index.es.js  38
- .github/commit-filter-action/node_modules/isexe/test/basic.js  7
- .github/commit-filter-action/node_modules/node-fetch/lib/index.js  38
- .github/commit-filter-action/node_modules/execa/index.js  10
- .github/commit-filter-action/node_modules/isexe/windows.js  7
- .github/commit-filter-action/node_modules/isexe/index.js  6
- .github/commit-filter-action/node_modules/which/which.js  14
- .github/commit-filter-action/node_modules/lodash.uniq/index.js  17
- .github/commit-filter-action/node_modules/strip-eof/index.js  5
- .github/commit-filter-action/node_modules/pump/test-node.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=4991415&bid=16477389)

**Comment by prologic** [comment]
I can't easily review this from the Github UI unless you split the PR into two :/ 

So I will leave some comments here as I've had to resort to `git show -r 790728a4` on the command-line to just focus on the important changes:

- Do we need to drag in Python just to parse some JSON API endpoint? Can we just grep it? See similar stuff I've done for the NetData Installer grep'ing the Github API endpoints.
- Where you use `+on: [push]` do we want to restrict this to tags?

Otherwise this looks fantasic!

Let's get this PR ready for review and internal testing -- Via our own forks?

**Comment by Ferroin** [comment]
> I can't easily review this from the Github UI unless you split the PR into two :/

For future reference, you actually can step through individual commits in the GitHub UI, it's just a bit hidden and not well documented.  Just above the first diff there should be a thing that looks like just text but is a dropdown which says 'Changes from **all commits**'. If you click on it, you'll get a dropdown menu that lets you pick out individual commits to view. If you select only one through this, you can even step through the commits in either direction using buttons on the top right just below the 'Review Changes' button.
> 
> So I will leave some comments here as I've had to resort to `git show -r 790728a4` on the command-line to just focus on the important changes:
> 
> * Do we need to drag in Python just to parse some JSON API endpoint? Can we just grep it? See similar stuff I've done for the NetData Installer grep'ing the Github API endpoints.

Using Python in this case is more reliable because it looks at the actual structure of the data. It's also guaranteed to be there in the GHA runners, and should be there on any custom runners we set up as well.
> * Where you use `+on: [push]` do we want to restrict this to tags?

For the moment, we can't, because this needs to work with the existing Travis CI workflow for releases for the moment, which does not tag nightlies.

**Comment by prologic** [comment]
> For future reference, you actually can step through individual commits in the GitHub UI, it's just a bit hidden and not well documented. Just above the first diff there should be a thing that looks like just text but is a dropdown which says 'Changes from all commits'. If you click on it, you'll get a dropdown menu that lets you pick out individual commits to view. If you select only one through this, you can even step through the commits in either direction using buttons on the top right just below the 'Review Changes' button.

TIL! I _totally_ did not know you could Review individual commits like this in the UI :/ Gah :) Thanks!

**Comment by prologic** [comment]
> Using Python in this case is more reliable because it looks at the actual structure of the data. It's also guaranteed to be there in the GHA runners, and should be there on any custom runners we set up as well.

Yeah okay fair. I would use `jq` though if you cn :)

**Comment by prologic** [comment]
> For the moment, we can't, because this needs to work with the existing Travis CI workflow for releases for the moment, which does not tag nightlies.

Got it!

**Comment by Ferroin** [comment]
> > Using Python in this case is more reliable because it looks at the actual structure of the data. It's also guaranteed to be there in the GHA runners, and should be there on any custom runners we set up as well.
> 
> Yeah okay fair. I would use `jq` though if you cn :)

I actually tried a couple of times with `jq` with test data originally, but I couldn't get it to work consistently for some reason.

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- .github/commit-filter-action/node_modules/which/which.js  14
- .github/commit-filter-action/node_modules/strip-eof/index.js  5
- .github/commit-filter-action/node_modules/lodash.uniq/index.js  17
- .github/commit-filter-action/node_modules/shebang-command/index.js  4
- .github/commit-filter-action/node_modules/execa/index.js  10
- .github/commit-filter-action/node_modules/node-fetch/lib/index.js  38
- .github/commit-filter-action/node_modules/pump/test-node.js  4
- .github/commit-filter-action/node_modules/nice-try/src/index.js  2
- .github/commit-filter-action/node_modules/node-fetch/browser.js  4
- .github/commit-filter-action/node_modules/once/once.js  2
- .github/commit-filter-action/node_modules/isexe/test/basic.js  7
- .github/commit-filter-action/node_modules/wrappy/wrappy.js  4
- .github/commit-filter-action/node_modules/isexe/windows.js  7
- .github/commit-filter-action/node_modules/node-fetch/lib/index.es.js  38
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=4991415&bid=16477389)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- .github/commit-filter-action/node_modules/node-fetch/lib/index.es.js  38
- .github/commit-filter-action/node_modules/once/once.js  2
- .github/commit-filter-action/node_modules/shebang-command/index.js  4
- .github/commit-filter-action/node_modules/execa/index.js  10
- .github/commit-filter-action/node_modules/lodash.uniq/index.js  17
- .github/commit-filter-action/node_modules/node-fetch/lib/index.js  38
- .github/commit-filter-action/node_modules/strip-eof/index.js  5
- .github/commit-filter-action/node_modules/node-fetch/browser.js  4
- .github/commit-filter-action/node_modules/which/which.js  14
- .github/commit-filter-action/node_modules/wrappy/wrappy.js  4
- .github/commit-filter-action/node_modules/nice-try/src/index.js  2
- .github/commit-filter-action/node_modules/pump/test-node.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=4991415&bid=16477389)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- .github/commit-filter-action/node_modules/shebang-command/index.js  4
- .github/commit-filter-action/node_modules/pump/test-node.js  4
- .github/commit-filter-action/node_modules/once/once.js  2
- .github/commit-filter-action/node_modules/lodash.uniq/index.js  17
- .github/commit-filter-action/node_modules/nice-try/src/index.js  2
- .github/commit-filter-action/node_modules/node-fetch/lib/index.js  38
- .github/commit-filter-action/node_modules/node-fetch/browser.js  4
- .github/commit-filter-action/node_modules/which/which.js  14
- .github/commit-filter-action/node_modules/wrappy/wrappy.js  4
- .github/commit-filter-action/node_modules/strip-eof/index.js  5
- .github/commit-filter-action/node_modules/execa/index.js  10
- .github/commit-filter-action/node_modules/node-fetch/lib/index.es.js  38
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=4991415&bid=16477389)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- .github/commit-filter-action/node_modules/wrappy/wrappy.js  4
- .github/commit-filter-action/node_modules/node-fetch/lib/index.es.js  38
- .github/commit-filter-action/node_modules/node-fetch/browser.js  4
- .github/commit-filter-action/node_modules/which/which.js  14
- .github/commit-filter-action/node_modules/pump/test-node.js  4
- .github/commit-filter-action/node_modules/strip-eof/index.js  5
- .github/commit-filter-action/node_modules/node-fetch/lib/index.js  38
- .github/commit-filter-action/node_modules/shebang-command/index.js  4
- .github/commit-filter-action/node_modules/lodash.uniq/index.js  17
- .github/commit-filter-action/node_modules/nice-try/src/index.js  2
- .github/commit-filter-action/node_modules/once/once.js  2
- .github/commit-filter-action/node_modules/execa/index.js  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=4991415&bid=16477389)

**Pull request closed without merging**
