### PR TITLE
Use CPack to generate Debian packages

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

This PR introduces all the relevant changes that will allow us to use
CPack in order to build debian packages.

##### Test Plan

- CI jobs

### CODE REVIEW

**Comment by Ferroin** [comment]
Closing and reopening to force CI to re-run properly.

**Comment by vkalintiris** [comment]
@Ferroin I'm marking this as ready for review to allow folks to test it if the want.

**Comment by Ferroin** [comment]
For anybody looking to review this, the current (as of this comment) failures for openSUSE Leap 15.5 packages on all arches, and Fedora and Amazon Linux 2023 on 64-bit ARM, are expected failures in master and are not related to this PR.

**Comment by vkalintiris** [comment]
> @vkalintiris The only remaining issue from my perspective is cleaning up the scripts being added to the root of the repository (I would argue that we don’t need them at all, but if we _really_ need to keep them for some reason they should be under the packaging directory). There are a few other minor things, but they’re either cosmetic or related to long-term maintenance, so I can just take care of those in a later PR instead of delaying this one further.

I removed them. They were meant to be used only while we were developing this branch.

**Review by Ferroin — APPROVED** [review]

**Pull request merged**
