### PR TITLE
Fix streaming scaling

### LINKED ISSUE #8218: Netdata streaming web api stops working after a while
##### Bug report summary
We have a centralized netdata monitoring with 250 streaming servers and a Prometheus server which collects the data from the central netdata server every 60 minutes.
Everything was working fine until an hour ago when our Prometheus server stopped receiving the metrics from the central netdata. We didn't any changes on the central server's configuration for about 1 month, so I doubt if it's related to any misconfiguration on the server-side, however we still get some of the alerts generated by netdata in our rocket chat. 
This is what I get when I try to connect to the web interface using my browser:
image

Here is the netdata central `netdata.conf` file:
```
[global]
        hostname = Netdata-Central
	memory mode = dbengine
	dbengine disk space = 2048
        page cache size = 128
	debug log = /opt/netdata/var/log/netdata/debug.log
	error log = /opt/netdata/var/log/netdata/error.log
	access log = /opt/netdata/var/log/netdata/access.log
        

[web]
	default port = 19999

[registry]
    enabled = True
    registry to announce = http://172.16.76.7:19999
```
Here is the netdata central `stream.conf` file:
```
[a-b-c-d-e]
    enabled = True

    allow from = *

    health enabled by default = auto

    multiple connections = allow

    default memory mode = dbengine
``` 
here is the file descriptors opened by the netdata process:
```
root@netdata-central:~# pidof netdata
18996
root@netdata-central:~# ls -l /proc/18996/fd/ | wc -l
5837
```
It hasn't reached the limit for the file descriptors:
```
root@netdata-central:~# cat /lib/systemd/system/netdata.service | grep LimitNOFILE
LimitNOFILE=65536
```
And here is the resouce usage on the central server:
image

In the last four hours we didn't have any `ERROR` or `CRITICAL` message on the central server:
```
root@netdata-central:~# cat /opt/netdata/var/log/netdata/error.log | grep -i STREAM | grep CRITICAL
root@netdata-central:~# cat /opt/netdata/var/log/netdata/error.log | grep -i STREAM | grep ERROR
root@netdata-central:~# 
```

Here is the sample `netdata.conf` of one of the slaves:
```
[global]
        update every = 2
    memory mode = none
        error log = False
        debug log = False
        access log = False

[web]
        mode = none

[registry]
    enabled = False
    registry to announce = http://172.16.76.7:19999
```
All of the slaves have the same configuration except in the `update every` parameter.
Sample `stream.conf` on the slaves:
```
[stream]
    enabled = True
    destination = 172.16.76.7:19999
    api key = a-b-c-d-e

    buffer size bytes = 10485760

    reconnect delay seconds = 5
```

##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.1 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.1 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 netdata v1.20.0

##### Component Name
web

### LINKED ISSUE #8251: Netdata takes too long to give the metrics to the Prometheus server
##### Bug report summary
We have a Prometheus server that collects `average` and `as-collected` metrics every 90 seconds with the timeout of 75 seconds from our master netdata server which is monitoring 250 slaves. 
The problem is most of the time the scrape duration from the master netdata is bellow 20 seconds but sometimes the scrape duration reaches the timeout (75s) hence we lose the metrics on our grafana dashboards.
I tried to download the metrics manually via `wget` in the Prometheus server and here is the results:
image
As you can see, the metrics are downloaded in 1.5s but it took about 50 seconds to establish the connection to the master netdata.
And here is the network graph in the central netdata (the only process which may cause the network output is either we opening the web UI and the Prometheus server reading the metrics and the 777 Mb/s out peak is when I run the `wget` command):
image
 
##### OS / Environment

```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=18.04
/etc/lsb-release:DISTRIB_CODENAME=bionic
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="18.04.1 LTS (Bionic Beaver)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 18.04.1 LTS"
/etc/os-release:VERSION_ID="18.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=bionic
/etc/os-release:UBUNTU_CODENAME=bionic
```

##### Netdata version

 netdata v1.20.0

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #8218
Related to #8251
##### Component Name
database
streaming
health
daemon
##### Description of testing that the developer performed
Set-up a bare metal server with 500 lxc containers as netdata slaves connected to the master in the host. Used `dbengine` as `memory mode` for both `netdata.conf` and `stream.conf`.

### CODE REVIEW

**Comment by vlvkobal** [comment]
```
sudo make check
...
  CC       web/api/tests/web_api.o
web/api/tests/web_api.c:187:35: error: ‘struct config’ has no member named ‘sections’
  187 | struct config netdata_config = { .sections = NULL,
      |                                   ^~~~~~~~
make[3]: *** [Makefile:4423: web/api/tests/web_api.o] Error 1

```

**Comment by mfundul** [comment]
> 
> 
> ```
> sudo make check
> ...
>   CC       web/api/tests/web_api.o
> web/api/tests/web_api.c:187:35: error: ‘struct config’ has no member named ‘sections’
>   187 | struct config netdata_config = { .sections = NULL,
>       |                                   ^~~~~~~~
> make[3]: *** [Makefile:4423: web/api/tests/web_api.o] Error 1
> ```

Fixed, but I see linker errors for some reason:
```
/tmp/ccvmg0HF.ltrans0.ltrans.o: In function `web_client_api_request':
/home/mfundul/Development/netdata/netdata/web/server/web_client.c:604: undefined reference to `__wrap_web_client_api_request_v1'
```

**Comment by vlvkobal** [comment]
```
sudo CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --enable-plugin-nfacct --enable-plugin-freeipmi --enable-backend-kinesis --enable-backend-prometheus-remote-write --disable-cloud --disable-go --disable-lto --dont-wait --dont-start-it
sudo make check
```
works fine.

**Comment by amoss** [comment]
> > ```
> > sudo make check
> > ...
> >   CC       web/api/tests/web_api.o
> > web/api/tests/web_api.c:187:35: error: ‘struct config’ has no member named ‘sections’
> >   187 | struct config netdata_config = { .sections = NULL,
> >       |                                   ^~~~~~~~
> > make[3]: *** [Makefile:4423: web/api/tests/web_api.o] Error 1
> > ```
> 
> Fixed, but I see linker errors for some reason:
> 
> ```
> /tmp/ccvmg0HF.ltrans0.ltrans.o: In function `web_client_api_request':
> /home/mfundul/Development/netdata/netdata/web/server/web_client.c:604: undefined reference to `__wrap_web_client_api_request_v1'
> ```
> 
> is this a C++ configuration issue?

No - it's because the code being tested has changed but the unit-tests were not updated.

**Comment by mfundul** [comment]
> 
> 
> > > ```
> > > sudo make check
> > > ...
> > >   CC       web/api/tests/web_api.o
> > > web/api/tests/web_api.c:187:35: error: ‘struct config’ has no member named ‘sections’
> > >   187 | struct config netdata_config = { .sections = NULL,
> > >       |                                   ^~~~~~~~
> > > make[3]: *** [Makefile:4423: web/api/tests/web_api.o] Error 1
> > > ```
> > 
> > 
> > Fixed, but I see linker errors for some reason:
> > ```
> > /tmp/ccvmg0HF.ltrans0.ltrans.o: In function `web_client_api_request':
> > /home/mfundul/Development/netdata/netdata/web/server/web_client.c:604: undefined reference to `__wrap_web_client_api_request_v1'
> > ```
> > 
> > 
> > is this a C++ configuration issue?
> 
> No - it's because the code being tested has changed but the unit-tests were not updated.

After the fix it builds fine for @vlvkobal so I merged.

**Pull request merged**
