### PR TITLE
GitHub action markdown link check update

### PR DESCRIPTION
**Pull request by jsoref**
##### Summary
Tolerate GitHub `429`s as hit in https://github.com/netdata/netdata/pull/10428

This upgrades the action per gaurav-nelson/github-action-markdown-link-check#75

##### Component Name
area/ci

### CODE REVIEW

**Review by joelhans — APPROVED** [review]
Been wondering about how to get around the 429 errors before. Nice!

Pardon my GHA ignorance—does specifying `@v1` mean we're always running the latest `v.1.X` version of the action? As in, right now, [1.0.12](https://github.com/gaurav-nelson/github-action-markdown-link-check/releases/tag/1.0.12)?

**Comment by ilyam8** [comment]
> does specifying @v1 mean we're always running the latest v.1.X version of the action?

Yes, to be specific - not version, but tag.

https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning

> Binding to a major version is the latest of that major version ( e.g. v1 == "1.*" )

**Comment by jsoref** [comment]
@joelhans: Technically how `@v1` behaves is up to the project maintainer (@gaurav-nelson). But yes, the convention is that it's a tag which will float forward on its own within `1.*` releases.

Instead of using that, you could enable [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) for GitHub Actions and have it try to drag you forward.

I picked `v1` because that's what the maintainer suggested.

I personally am manually bringing projects forwards for my own GitHub Action (and using a prerelease branch while developing spelling branches for others). It means upgrades are slower (as here), but it gives me a bit more control of rollout (and I don't have enough test coverage to know that I won't break something).

**Review by Ferroin — APPROVED** [review]
We’ve actually mostly been keying off of major versions for our own workflows, so I’m not 100% certain how this ended up specifying a full version in the first place. Definitely improves consistency with the rest of our workflows to fix this one.

Given that and that this appears to fix the issue correctly, I’m going to go ahead and approve and merge. Thank you @jsoref for this fix!

**Comment by jsoref** [comment]
Oops. I just realized that the other PR _is_ dependabot, so you're already using it. -- Too many things in the air.

**Comment by Ferroin** [comment]
@jsoref It’s OK, the other changes here actually fix a problem, and in general we do probably want this tracking major versions instead of an exact patch release.

**Pull request merged**
