### PR TITLE
[WIP] Overhaul of installation documentation

### PR DESCRIPTION
**Pull request by joelhans**
##### Summary

I was tasked by @ktsaou and @cakrit to overhaul the way our documentation guides users through installation. We all agreed that because so many people visit and reference the installation documentation, it needs to be as professional and simple as possible.

The goals of this project:

- [x] Highlight one-line installer, binaries, and Docker as "best" installation methods for most users
- [x] Separate installation instructions into multiple files
- [x] General overhaul and cleanup of language and syntax on installation page(s)
- [x] Address the nightly vs. stable release pros/cons

TODOs:

- [ ] Figure out if I need to add GA tags to the new pages (and how)
- [ ] Collect feedback from team

I'm leaving this as a WIP to collect feedback, as this is a pretty dramatic overhaul from the existing structure for installation docs.

I also want to give the update/uninstall pages a similar overhaul, but will likely tackle that in a separate PR unless everyone agrees it's better to do everything all at once.

##### Component Name

docs

### CODE REVIEW

**Comment by cakrit** [comment]
I have only started checking, but I could have sworn we had a `copy` button on the one line installer to copy it to clipboard. I started looking for the change that removed it (or at least to see when we had it), but can't find it. Will need to get an older version of the docs to see if we indeed had it... It MAY have something to do with CSS but I don't know.

**Comment by cakrit** [comment]
@paulkatsoulakis please check why the md5sum check for kickstart fails so we can either change the script that does the check, or the change on `packaging/installer/README.md`

**Comment by cakrit** [comment]
I added @paulkatsoulakis as a reviewer. I won't be here to complete the review, no time until I'm off. If it works, go ahead and merge it @paulkatsoulakis

**Comment by joelhans** [comment]
@cakrit re: the copy button—you're right, there was one. I noticed the same thing yesterday myself. I think it was lost in the switch to the new syntax highlighter, but I spent a few minutes yesterday figuring out how to restore it. I have the fix on another WIP branch, but maybe I'll update this one as well to get the copy button back earlier rather than later.

**Comment by joelhans** [comment]
@cakrit @paulkatsoulakis Sorry guys, not exactly sure what happened, but I did a rebase this morning to fix some conflicts and things got messy. This PR has some other commits in it now, so I'm going to start a new PR from a clean slate.

**Pull request closed without merging**
