### PR TITLE
python.d.plugin update

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary
Fix: #4756

`python.d.plugin` updates:
  * remove `retries` option 
  * make `penalty` configurable (enabled by default, max is 10 minutes)

> penalty indicates whether to apply penalty to update_every in case of failures.
> Penalty will increase every 5 failed updates in a row. Maximum penalty is 10 minutes.
> penalty: yes

##### Component Name

`python.d.plugin`

### CODE REVIEW

**Comment by ilyam8** [comment]
@jakk2809 i believe #4756 is fixed in this PR, please test it

**Comment by cakrit** [comment]
Looks good

**Comment by jakk2809** [comment]
@ilyam8 Thank you for working on this. Setting `penalty: no` in the .conf file results in the expected behavior (get_data will run at a constant interval). 

When the `penalty` is enabled, it seems like a penalty is added every iteration. Is the expected behavior to add a penalty only on `PENALTY_EVERY` iterations? Please see the screenshot below and take note of the timestamps:

image

**Comment by ilyam8** [comment]
@jakk2809 

> Is the expected behavior 

!expected :smile:

**Comment by ilyam8** [comment]
@cakrit

**Pull request merged**
