### PR TITLE
Add class, type, component to stock alarms configs

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Add default `class`, `type` & `component` attributes to stock alarms configs as per in: https://docs.google.com/spreadsheets/d/1I-9RuX_Sr3bB-W-C2zzZ5TOkMgBBqbbjoNvApZIw2AY

##### Component Name

Health

##### Test Plan

These values should be loaded under this branch. We'll need to check them for correct values, etc.

### CODE REVIEW

**Comment by ilyam8** [comment]
I installed this PR and got zero configuration loading/parsing errors, looks good!

**Review by ilyam8 — APPROVED** [review]

**Comment by ilyam8** [comment]
ok, i didn't check class/component/type values in the `/api/v1/alarms?all`

These are `Uknown`

```cmd
[ilyam@pc netdata]$ curl -s http://192.168.50.130:19999/api/v1/alarms?all | jq '.alarms[] | "[\(.name)] class=\(.class), component=\(.component), type=\(.type)"' | grep Unknown
"[10min_cpu_usage] class=Unknown, component=Unknown, type=Unknown"
"[10min_cpu_iowait] class=Unknown, component=Unknown, type=Unknown"
"[20min_steal_cpu] class=Unknown, component=Unknown, type=Unknown"
"[disk_space_usage] class=Unknown, component=Unknown, type=Unknown"
"[disk_inode_usage] class=Unknown, component=Unknown, type=Unknown"
"[docker_unhealthy_containers] class=Unknown, component=Unknown, type=Unknown"
"[disk_space_usage] class=Unknown, component=Unknown, type=Unknown"
"[disk_inode_usage] class=Unknown, component=Unknown, type=Unknown"
"[disk_space_usage] class=Unknown, component=Unknown, type=Unknown"
"[disk_inode_usage] class=Unknown, component=Unknown, type=Unknown"
"[interface_speed] class=Unknown, component=Unknown, type=Unknown"
"[1m_received_traffic_overflow] class=Unknown, component=Unknown, type=Unknown"
"[1m_sent_traffic_overflow] class=Unknown, component=Unknown, type=Unknown"
"[inbound_packets_dropped_ratio] class=Unknown, component=Unknown, type=Unknown"
"[outbound_packets_dropped_ratio] class=Unknown, component=Unknown, type=Unknown"
"[1m_received_packets_rate] class=Unknown, component=Unknown, type=Unknown"
"[10s_received_packets_storm] class=Unknown, component=Unknown, type=Unknown"
"[inbound_packets_dropped] class=Unknown, component=Unknown, type=Unknown"
"[outbound_packets_dropped] class=Unknown, component=Unknown, type=Unknown"
"[10min_fifo_errors] class=Unknown, component=Unknown, type=Unknown"
"[interface_speed] class=Unknown, component=Unknown, type=Unknown"
"[1m_received_traffic_overflow] class=Unknown, component=Unknown, type=Unknown"
"[1m_sent_traffic_overflow] class=Unknown, component=Unknown, type=Unknown"
"[wifi_inbound_packets_dropped_ratio] class=Unknown, component=Unknown, type=Unknown"
"[wifi_outbound_packets_dropped_ratio] class=Unknown, component=Unknown, type=Unknown"
"[1m_received_packets_rate] class=Unknown, component=Unknown, type=Unknown"
"[10s_received_packets_storm] class=Unknown, component=Unknown, type=Unknown"
"[inbound_packets_dropped] class=Unknown, component=Unknown, type=Unknown"
"[outbound_packets_dropped] class=Unknown, component=Unknown, type=Unknown"
"[10min_fifo_errors] class=Unknown, component=Unknown, type=Unknown"
"[interface_speed] class=Unknown, component=Unknown, type=Unknown"
"[1m_received_traffic_overflow] class=Unknown, component=Unknown, type=Unknown"
"[1m_sent_traffic_overflow] class=Unknown, component=Unknown, type=Unknown"
"[inbound_packets_dropped_ratio] class=Unknown, component=Unknown, type=Unknown"
"[outbound_packets_dropped_ratio] class=Unknown, component=Unknown, type=Unknown"
"[1m_received_packets_rate] class=Unknown, component=Unknown, type=Unknown"
"[10s_received_packets_storm] class=Unknown, component=Unknown, type=Unknown"
"[inbound_packets_dropped] class=Unknown, component=Unknown, type=Unknown"
"[outbound_packets_dropped] class=Unknown, component=Unknown, type=Unknown"
"[10min_fifo_errors] class=Unknown, component=Unknown, type=Unknown"
"[interface_speed] class=Unknown, component=Unknown, type=Unknown"
"[1m_received_traffic_overflow] class=Unknown, component=Unknown, type=Unknown"
"[1m_sent_traffic_overflow] class=Unknown, component=Unknown, type=Unknown"
"[inbound_packets_dropped_ratio] class=Unknown, component=Unknown, type=Unknown"
"[outbound_packets_dropped_ratio] class=Unknown, component=Unknown, type=Unknown"
"[1m_received_packets_rate] class=Unknown, component=Unknown, type=Unknown"
"[10s_received_packets_storm] class=Unknown, component=Unknown, type=Unknown"
"[inbound_packets_dropped] class=Unknown, component=Unknown, type=Unknown"
"[outbound_packets_dropped] class=Unknown, component=Unknown, type=Unknown"
"[10min_fifo_errors] class=Unknown, component=Unknown, type=Unknown"
"[10min_disk_backlog] class=Unknown, component=Unknown, type=Unknown"
"[10min_disk_utilization] class=Unknown, component=Unknown, type=Unknown"
"[mdstat_last_collected] class=Unknown, component=Unknown, type=Unknown"
"[mdstat_disks] class=Unknown, component=Unknown, type=Unknown"
"[mdstat_last_collected] class=Unknown, component=Unknown, type=Unknown"
"[mdstat_disks] class=Unknown, component=Unknown, type=Unknown"
"[mdstat_last_collected] class=Unknown, component=Unknown, type=Unknown"
"[mdstat_disks] class=Unknown, component=Unknown, type=Unknown"
"[mdstat_last_collected] class=Unknown, component=Unknown, type=Unknown"
"[mdstat_disks] class=Unknown, component=Unknown, type=Unknown"
```

**Comment by stelfrag** [comment]
> Since we update almost all of the stock alarms with class/component/type i expect to see those values in the `/api/v1/alarms?all` response. However, it is not the case. There are a lot of Uknown's

This is probably due to `rrdcalc_create_from_template` affecting all templates.

**Comment by ilyam8** [comment]
@stelfrag correct! It works if it is `alarms` and doesn't if it is `template`.

**Comment by MrZammler** [comment]
Good morning!

I've updated the conf files, and put the 3 attrributes after the on attribute.

While doing a check, I've noticed:

1) In `exporting.conf', `exporting_last_buffering` doesn't seem to have the new attributes.
2) In `mysql.conf`, `mysql_galera_cluster_state` & `mysql_galera_cluster_status` don't have a type attribute.
3) In `unbound.conf`, `unbound_request_list_overwritten` & `unbound_request_list_dropped` don't have a type attribute.
4) In 'vcsa.conf`, `vcsa_database_storage_health`, `vcsa_applmgmt_health`, `vcsa_software_updates_health`  don't have a type attribute.

Don't know if they are intentional, just mentioning it in case we need to fill them?

**Comment by MrZammler** [comment]
I'll try to fix `rrdcalc_create_from_template` before we merge this to the feature branch

**Pull request merged**
