### PR TITLE
dashboard v1.0.16

### PR DESCRIPTION
**Pull request by jacekkolasa**
- fixed navbar icons styling (alarm indicators above bell, fixed margins)
- slightly preciser way to resize dygraph after toggling left menu (fixed rare scenario when there was empty space in dygraph)
- leave door open for logout dropdown - no visible UI now but we'll be able to add dropdown in iframes without the need for dashboard update
- fix a rare issue with lost timeframe setting, which was happening when first panning was done on agent with high latency
- fix registry when Do Not Track is enabled
- support whitespaces in replicated-nodes urls
- add trailing slash in replicated-nodes links
- disable loop when checking for ACLK status (check just once, as in design)
- small performance improvement - less dependencies-loading cycles on init

includes:
https://github.com/netdata/dashboard/pull/81
https://github.com/netdata/dashboard/pull/82
https://github.com/netdata/dashboard/pull/84

### CODE REVIEW

**Comment by underhood** [comment]
I don't know if you intend to fix also #9043 but my agent still makes requests to app.netdata.cloud even though:
```
	"cloud-enabled": false,
	"cloud-available": false,
	"agent-claimed": false,
	"aclk-available": false
```

**Comment by jacekkolasa** [comment]
@underhood no, fix for that is not added, we wanted first to finish the first iteration of Custom Dashboards in the Cloud. cc @manos-saratsis

**Comment by amoss** [comment]
It seems to be very broken on Debian 10. Panning a chart freezes the dashboard and then it becomes very unstable.

**Comment by jacekkolasa** [comment]
i'm closing this PR. I haven't done any updates here because i spotted a place where there could be one bug and i didn't wanted it to be merged. I didn't had time to fix it since then, but I'll probably release a new version in next week.

**Pull request closed without merging**
