### PR TITLE
allow to alias the interfaces names

### LINKED ISSUE #2317: alias network interfaces
Some machines are using eno0 some eno3 others eth0, I need to aggregate those data and it would be very convenient to be able to alias the interface name so they get to the same serie in the influxdb database.

### PR DESCRIPTION
**Pull request by dcharbonnier**
Proposal to close #2317 

```
[plugin:proc:/proc/net/dev:eth0]
    alias = public
```

### CODE REVIEW

**Comment by dcharbonnier** [comment]
In production on a lot of machines since 4 days and it works like a charm ;-)

**Comment by ktsaou** [comment]
seems good. nice work!

What bothers me is that the original information is lost from the charts.

Another solution would be to set this (already existing option):

```
[net.wlp2s0]
	# history = 3996
	# enabled = yes
	# cache directory = /var/cache/netdata/net.wlp2s0
	# chart type = area
	# type = net
	# family = wlp2s0
	# units = kilobits/s
	# context = net.net
	# priority = 7000
	# gap when lost iterations above = 1
	# name = net.wlp2s0    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<< THIS
	# title = Bandwidth
	# dim received name = received
	# dim received algorithm = incremental
	# dim received multiplier = 8
	# dim received divisor = 1024
	# dim sent name = sent
	# dim sent algorithm = incremental
	# dim sent multiplier = -8
	# dim sent divisor = 1024
```

and add an option in the `[backend]` section to send names instead of IDs.
That way, the same chart could be accessed by both names.

The only reason I am so sceptical about this, is that I have a few todo items related to network interfaces, like: somehow assign network interfaces to containers, add more plugins to parse interface related metrics from other sources, etc. I am not sure if the change you suggest will complicate our future.

What do you think?

**Comment by dcharbonnier** [comment]
For me maintaining a different behavior and allowing to send names instead of IDs looks like more complicated to maintain.
My idea is to completely make eth0 disappear, at the root and that's what the PR do on a very simple and efficient way.
The fact that we "loose" information from the chart is not an issue, the same would happen if you change the interface names on the system, you have to design your system before running it.
For some infrastructures it's ok to graph eth0 or eno0 but when you run a multi provider / datacenter / operating system infrastructure this become a real issue.

Changing the interfaces names on a system, only for statistics seams like an anti-pattern for a monitoring system and netdata is really good at just observing, I think this PR goes in this direction.

**Comment by ktsaou** [comment]
netdata has already been modified to send names by default instead of IDs, to backends. This was required for a lot of reasons - mainly because for several cases, like interrupts, QoS classes, sensors, etc the IDs were really meaningless.

So, with the current state of netdata, changing the `name` at the chart options in `netdata.conf` will do the job you need.

**Comment by csch42** [comment]
I hate to re-open such old wounds, but I have just tried the "solution" above - and **both** succeeded and failed! 🤷🏼‍♂️

How? Well, "naming" a device (a network interface in particular) results indeed in a renamed item - on a _local_ dashboard. Even _local_ exports to a Prometheus backend retains this info well enough to be able to select upon it in sub-sequent Grafana queries, so "Yeah!" so far!

`netdata_net_net_kilobits_persec_average{chart="foo",family="br3000",dimension="received"} 1.5004709 1575994671000`
(→ chart="foo")

**However** ... in my main use-case (potentially hundreds of routers run netdata on a minimal footprint →  memory mode = none, web mode = none) where I _stream_ all data to a pair of central netdata servers, this info is _completely_ lost, unfortunately (as witnessed by tcptumping into the stream, where the new name is nowhere to be seen 🤷🏼‍♂️ .. yes, I have restarted everything multiple times)

So "somewhere" this information is lost; if by bug or by design I presently cannot tell exactly - I'll have to read myself in deeper into the development history of netdata for this.

But, coming back to the original intent (mine and that of the initiator of this thread), I'd like to make a suggestion: Instead of _renaming_ objects (and all the havoc it ensues) I would just want to _tag_ objects - and not just network interfaces. But taking those as example: If I can just tag an interface with a list of arbitrary tags, (i.e., "the upstream link") I would really not care any more which "name" it carries or would even appreciate it retaining it's original ("real") name!

I would want to "find" the metric later in a netdata-dashboard, though, by referring to it's tag (or better: "to one of it's tags") and these tags _must survive streaming_, of course, and _be exported to backends_, like Prometheus, et.al.

It would also prove to be tremendously valuable in aggregation functions ("Show summary of all interfaces tagged 'WLAN', etc.")

Again, I think this would be a valuable addition overall - for all kinds of metrics!

Just my 2¢ ... hoping for some enlightening feedback ... 😉

**Comment by amoss** [comment]
Hi @csch42 ,

Thanks for your feedback, we love to see users with complex use-cases digging into what Netdata can do. I think that your comments are valuable to help us improve Netdata. It is difficult for us to track comments on closed issue. Please help us by splitting your feedback into two separate parts. 
1. If you have a specific use-case for renaming the interfaces that causes the labels to be dropped from the stream, please open a bug report with the details. We can talk to you on that issue about replicating your issue and then we can fix it.
2. The work to bring the first version of #6503 is happening currently and should land in a release after Christmas. (It will be in the nightlies long before the release). This first version won't quite do what you want (the granularity of the labels will be per-host) but we plan to iterate quickly and add more labelling support until #6503 is delivered. Please feel welcome to add comments / ideas to the discussion in #6503 to let us know how it matches your target use-case: this kind of direct feedback from users who want the feature is incredibly valuable to us in defining how it should work.

**Comment by csch42** [comment]
Hello @amoss,

1) thanks, will do
2) ... too :-)

**Pull request closed without merging**
