### PR TITLE
Use CMake generated config.h also in out of tree CMake build

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Fixes problem identified during review of https://github.com/netdata/netdata/pull/13656 

CMake build was still using the autotools generated config.h in case of out of tree build.

We cannot rely on autotools anymore (we still have to rely on installer though)

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @underhood ,

I cloned from scratch `netdata` and after this I initialize `modules` and I got your branch. After to run next commands:

```sh
#  autoreconf -ivf
#  ./configure --disable-cloud
#  mkdir cmake-build-debug; cd cmake-build-debug
#  cmake -DCMAKE_BUILD_TYPE="Debug" -DUNIT_TESTING=ON ..
```

I got an unexpected result:

```sh
-- prometheus remote write exporting: disabled (requires protobuf and snappy libraries)
-- mongodb exporting: enabled
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindProtobuf.cmake:650 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:1206 (find_package)
```

I am also adding the [CMakeOutput.log](https://github.com/netdata/netdata/files/9618311/CMakeOutput.log) to help you.

**Comment by underhood** [comment]
Do you have system dev package for protobuf and protoc ? if i am not mistaken cmake do not support static protobuf yet (i will have to change that)

**Comment by thiagoftsm** [comment]
> Do you have system dev package for protobuf and protoc ? if i am not mistaken cmake do not support static protobuf yet (i will have to change that)

No, I do not have:

```sh
[root@archlinux ~]# pacman -Qqe | grep proto
[root@archlinux ~]# pacman -S protobuf
resolving dependencies...
looking for conflicting packages...

Packages (1) protobuf-21.6-1

Total Download Size:   2.01 MiB
Total Installed Size:  8.89 MiB

:: Proceed with installation? [Y/n] ^C
Interrupt signal received

[root@archlinux ~]# 

```

**Review by thiagoftsm — APPROVED** [review]
After a direct talk with @underhood about the issues I am having, I am approving this PR expecting that `protobuf` issues will be addressed with other PRs. LGTM!

**Review by vlvkobal — APPROVED** [review]

**Pull request merged**
