### PR TITLE
normalized plugin names on all plugins; 

### PR DESCRIPTION
**Pull request by ktsaou**
#4379

This PR:

1. normalizes the plugin names reported for all charts. netdata reports `name.plugin`, the dashboard strips the `.plugin` and reports only `name` (to save some space at the tooltip).

2. normalizes the module names, where possible

3. normalizes `error.log` entries to match the plugin names (without `.plugin`)

4. it covers a significant part of the census required to unify the chart priorities across the internal plugins (freebsd is incomplete, macos has not started yet)

### CODE REVIEW

**Comment by vlvkobal** [comment]
You broke formatting in some of `freebsd_` files

**Comment by paulfantom** [comment]
@vlvkobal why did you approve this in code review if you found some issues with this PR?

**Comment by vlvkobal** [comment]
Because I found them after I approved the PR.

**Comment by ktsaou** [comment]
fixed them with #4398

**Pull request merged**
