### PR TITLE
[WIP] pythond_refactor

### PR DESCRIPTION
**Pull request by l2isbad**
**!Do not merge this!**
Not really tested (did it mostly last night :sleeping: )

This is an attempt to reduce `pythondplugin` memory usage.

Current version imports all packages during autodetection and there is no way to clean it up.

This PR adds additional process (not thread), which does initial autodetection:

- loads module configuration
- builds jobs configs from it
- loads module source
- runs `job.check()` for every job, if job return `True` it stops and module considered as active. 
- returns to main list of jobs config to run (list started from the one that returned `True` )

All unused imports dies with that process.

Diff on vm with `python-musqldb, python-pymongo` installed packages: 22MB => 10,5 MB.

### CODE REVIEW

**Comment by ktsaou** [comment]
This pull request **fixes 6 alerts** when merging 3072f27e4cfac401541d99fdd84480a03b3d3a82 into 57d0392f1da6791f38641366255b5c98e1094600 - [view on LGTM.com](https://lgtm.com/projects/g/firehol/netdata/rev/pr-c18e372005a03021abcea15533d91c6e7a8b910d)

**fixed alerts:**

* 6 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by l2isbad** [comment]
Oh, i think we need separate account for LGTM comments or something. These automated messages from @ktsaou freaks me out :smile:

**Comment by paulfantom** [comment]
I just said the same in https://github.com/firehol/netdata/issues/4203#issuecomment-421939333 :smile:

**Comment by ktsaou** [comment]
I don't know how to fix that.
Create a new account?

**Comment by ktsaou** [comment]
> This PR adds additional process (not thread), which does initial autodetection

@l2isbad have in mind that in the future we may need to run auto-detection again. I see most solutions support auto-discovery, running every a few minutes. It would be nice to support this - though we need to give it a second thought, since this is a really expensive operation in terms of system resources utilization.

**Comment by paulfantom** [comment]
> Create a new account?

Don't we have a firehol-automation account?

**Comment by ktsaou** [comment]
> Don't we have a firehol-automation account?

yes, we do.
@philwhineray we want to use the `firehol-automation` account for LGTM.com, so that the comments it makes on this repo will appear from `firehol-automation`, not me.

Also, as @paulfantom suggested on https://github.com/firehol/netdata/issues/3912 we would like to use the firehol logo as the profile picture of it.

I search my emails, but I don't have any credentials for this account.
Could you please help?

**Comment by paulfantom** [comment]
Let's move discussion about LGTM comments to https://github.com/firehol/netdata/issues/4203 there is also a response to last @ktsaou comment.

**Comment by l2isbad** [comment]
Will be implemented later.

Current version memory usage is a big problem which should be fixed.

Additional process for autodetection gives huge improvements
> Diff on vm with python-musqldb, python-pymongo installed packages: 22MB => 10,5 MB.

We need to discuss it @Ferroin

**Pull request closed without merging**
