### PR TITLE
Add localhost hostname to the edit_command

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This PR, extends the `edit_command` field of an alert event, to include also the localhost's host name, e.g.:

`sudo /home/evas/stuff/netdata/install_netdata_ng_13//netdata/etc/netdata/edit-config health.d/linux_power_supply.conf=3=winterland`

The `edit_command` field is transferred to cloud and is used in the part of the notification email (and in other parts of cloud UI) to indicate which file needs to be edited to adjust the current alarm, .ie:

image

In case the alert is raised by a parent, on metrics from a child, we need to display to the user to login to the parent to edit this alert's config. This change will help with that, as in the cloud will display the hostname of whatever we include in the `edit_command` field.

##### Component Name

Health

##### Test Plan

Can be tested by running an agent, and observing the `command` field from `api/v1/alarm_log`. If needed, check the same endpoint for a child (e.g. `/host/A_HOST/api/v1/alarm_log`).

Will be tested with the cloud backend team. <- Done.

Best check is to setup a child/parent, claim the parent to the cloud, and raise an alert on the parent on behalf of the child. Observe that notifications from the cloud now contain the parent's hostname. Observe the same on agent alerts.

The cloud backend team will merge this in production in the following days, but it can be tested on staging.

##### Additional Information

Tested with the cloud backend team on staging.

### CODE REVIEW

**Comment by stelfrag** [comment]
Will this be a release blocker?

**Comment by MrZammler** [comment]
> Will this be a release blocker?

No, I don't consider it a blocker, but should go afterwards...

**Comment by MrZammler** [comment]
We did some tests with the backend team on staging, and we're ok.

They will support this for both old agents (which the item is missing), and new agents connected to the old architecture (which they contain it).

**Comment by MrZammler** [comment]
Hey guys! Can we perhaps check this to merge? Thanks!!

**Review by stelfrag — APPROVED** [review]

**Review by siamaktavakoli — APPROVED** [review]

**Comment by MrZammler** [comment]
Thanks!

**Pull request merged**
