### PR TITLE
.travis.yml: Fix some yamllint errors

### PR DESCRIPTION
**Pull request by knatsakis**
Only white space changes, related to comments and indentation

##### Summary
Make .travis.yml use consistent indentation
Use two blank lines instead of three, as per yamllint suggestion
Use two spaces before EOL comments as per yamllint suggestion

##### Component Name
.travis.yml

##### Additional Information
Please accept some cosmetic changes to .travis.yml

### CODE REVIEW

**Comment by cakrit** [comment]
Thanks @knatsakis, please sign the CLA.

**Comment by knatsakis** [comment]
@cakrit: CLA signed.

**Comment by paulkatsoulakis** [comment]
Good morning @knatsakis thanks for your PR!
It's funny how travis linter doesn't validate in that aspect.

I have a general question, i can't see a side-by-side comparison of the change, which is very peculiar if only spacing was modified. I suspect it may be because of the empty lines removed.

Could you re-instate all empty lines though? I used specific number of spacing between stages to help me easily isolate each stage and for this PR i 'm gonna need to have an easy visual comparison to make sure nothing is missed

**Comment by cakrit** [comment]
> I have a general question, i can't see a side-by-side comparison of the change, which is very peculiar if only spacing was modified. I suspect it may be because of the empty lines removed.

I've seen that many times with GitHub, it often gets confused with white space changes and doesn't highlight anything on the new line.

**Comment by knatsakis** [comment]
Hi @paulkatsoulakis,

There is a github setting for viewing non-whitespace only changes. Please check [Ignore white space in code review](https://github.blog/2018-05-01-ignore-white-space-in-code-review/).

Regarding blank lines, I guess it's a matter of personal preference. I find 2 consecutive blank lines enough for readability. In any case I have reverted this particular change.

**Comment by paulkatsoulakis** [comment]
> Seems that travis linter is complaining also.
> I think i would seriously reconsider the change.
> 
> ```
> $ travis lint .travis.yml 
> Warnings for .travis.yml:
> [x] syntax error: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1
> ```
> 
> I can't say that i fully trust their tool, since it doesn't catch all problems, but for sure is not good when it's complaining

BTW i don't see travis responding either, i am suspecting it has collapsed due to that issue without reporting anything. It's a very vintage travis behaviour when it doesn't like the syntax

**Comment by knatsakis** [comment]
Both problems where caused by some indentation missing around the _RPM_TEMPLATE and _DEB_TEMPLATE keys, that I didn't fix along with the other corrections.

travis lint stopped complaining after fixing this, and travis seems to be building properly now.

I'm sorry I didn't catch this earlier. I think the pull request is ready now.

**Comment by paulkatsoulakis** [comment]
Hi @knatsakis, you also seem to have merge conflicts.
Could you attend them please? I think it may be due to one recent change i pushed, apologies for that

**Comment by knatsakis** [comment]
Hi @paulkatsoulakis,

I have rebased the pull request in order to resolve the merge conflicts.

**Pull request merged**
