### PR TITLE
Fix passing of version to GHA release workflow.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

Fixes an issue with how we’re generating tags for releases.

##### Component Name

area/ci

##### Test Plan

n/a

### CODE REVIEW

**Review by iigorkarpov — APPROVED** [review]

**Comment by ilyam8** [comment]
@maneamarius tagging you so we don't forget this PR

**Comment by Ferroin** [comment]
CI failures are unrelated to the changes being made here.

**Comment by Ferroin** [comment]
@stelfrag This is a blocker for the release, without it the release process will not work entirely correctly.

**Review by maneamarius — APPROVED** [review]
Looks good.

**Pull request merged**
