### PR TITLE
fix(cgroups.plugin): use Docker API for name resolution when Docker is a snap package

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

[Docker containers name resolution doesn’t work](https://discord.com/channels/847502280503590932/976961124157243414) when Docker is installed as a snap package. The problem is snap + AppArmor + home dir outside of /home.

I tried to google, found [this advice](https://forum.snapcraft.io/t/how-can-i-use-snap-when-i-dont-use-home-user/3352/2), applied it - no luck.

- Netdata installed from git

  - Netdata error.log
  > cannot create user data directory: /opt/netdata/var/lib/netdata/snap/docker/1779: 
  Permission denied

  - Journal logs
  > Aug 15 18:32:01 ilyam-ubnt2204-1 audit[1943]: AVC apparmor=“DENIED” operation=“open” 
  profile=“/usr/lib/snapd/snap-confine” name=“/opt/” pid=1943 comm=“snap-confine” 
  requested_mask=“r” denied_mask=“r” fsuid=998 ouid=0
  Aug 15 18:32:01 ilyam-ubnt2204-1 kernel: audit: type=1400 audit([1660588321](tel:1660588321).555:45): apparmor=“DENIED” operation=“open” profile=“/usr/lib/snapd/snap-confine” name=“/opt/” pid=1943 comm=“snap-confine” requested_mask=“r” denied_mask=“r” fsuid=998 ouid=0

- Native package install (deb)

   > Sorry, home directories outside of /home are not currently supported.
    See https://forum.snapcraft.io/t/11209 for details.

**I assume there are some ways to fix that problem (e.g. changing the AppArmor config), but I didn't find any**.

---

Suggested solution:

- Check if Docker is a snap package.
- If so, prefer querying Docker API.

> **Warning**: querying Docker API directly require `jq`.

##### Test Plan

Check name resolution on Ubuntu 22.04 with the snap version of Docker and `jq` installed.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by Ferroin** [comment]
Just a thought, but is there any reason not to try this as a fallback if the regular `docker` command approach doesn0t work?

**Comment by ilyam8** [comment]
@Ferroin the way you've described will work too. I didn't implement it like that because:

 - using `docker` **always** fails when Docker is a snap package.
 - it means that we always will be doing that meaningless attempts (and writing log messages twice).
 - `command -v snap >/dev/null && snap list docker >/dev/null` seems to be very lightweight

   > cm@ilyam-ubnt2204-1:~$ time command -v snap >/dev/null && snap list docker >/dev/null
   real	0m0.000s
   user	0m0.000s
   sys	0m0.000s

**Comment by ilyam8** [comment]
@Ferroin we need to think about that, probably a better approach is just to prefer querying the Docker API over using `docker` if `jq` is installed.

**Review by thiagoftsm — APPROVED** [review]

**Review by vlvkobal — APPROVED** [review]

**Comment by Ferroin** [comment]
> @Ferroin we need to think about that, probably a better approach is just to prefer querying the Docker API over using `docker` if `jq` is installed.

Agreed, that’s probably the better approach here given that it ensures we’re querying Docker running on the local system.

**Pull request merged**
