### PR TITLE
Prevent command_to_be_logged from overflowing

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This PR tries to prevent the variable `command_to_be_logged` from overflowing. If it happens, it can result in corruption and random crashes.

I believe this is the crash reported in #12880.

The analytics commands tend to be more than 2048 bytes that the variable `command_to_be_logged` is defined. During tests the crash is pretty reproducible when analytics tries to execute the external script with many parameters that span more than 2048 bytes. It is more evident in FreeBSD/arm.

The crash is actually reported in line https://github.com/netdata/netdata/blob/4616491f1a2561285197126fe4683edc71001455/daemon/analytics.c#L1018 but actually is caused by previous corruption.

With either this patch, or by using `popen` instead of `mypopen`, I could no longer trigger the crash.

##### Test Plan

Try it if possible on FreeBSD arm. Most likely it's the most finicky system to observe. Let it run at least for 2 minutes until the agent tries to send a `META_START` event. It should crash. Using this PR it should not.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by ilyam8** [comment]
@MrZammler we use `snprintfz` which should take care of it, I think the problem is the following:

- `custom_popene`
  - `convert_argv_to_string`
    - `snprintfz`
      -  `vsnprintfz`
        - `vsnprintf`


https://github.com/netdata/netdata/blob/4616491f1a2561285197126fe4683edc71001455/libnetdata/libnetdata.c#L1113-L1123

=>

```c
int vsnprintfz(char *dst, size_t n, const char *fmt, va_list args) {
    int size = vsnprintf(dst, n, fmt, args);

    if (unlikely((size_t) size >= n)) {
        // truncated
        size = (int)n;
        dst[size - 1] = '\0';
    }

    return size;
}
```

> return the number of characters that would have been printed if the size were unlimited (again, not including the final ‘\0’).

**Comment by ktsaou** [comment]
I suggest this:

```c
int vsnprintfz(char *dst, size_t n, const char *fmt, va_list args) {
    int size = vsnprintf(dst, n, fmt, args);
    dst[n - 1] = '\0';

    if (unlikely((size_t) size > n)) size = (int)n;

    return size;
}
```

**Comment by ilyam8** [comment]
> I believe this is the crash reported in https://github.com/netdata/netdata/issues/12880.

I think I have the same problem on an RPi4:
 - static build
 - crashes when telemetry is enabled


```c
Core was generated by `/opt/netdata/bin/srv/netdata -P /opt/netdata/var/run/netdata/netdata.pid -D'.
Program terminated with signal SIGILL, Illegal instruction.
#0  a_crash () at ./arch/arm/atomic_arch.h:77
77	./arch/arm/atomic_arch.h: No such file or directory.
[Current thread is 1 (LWP 18050)]
(gdb) bt
#0  a_crash () at ./arch/arm/atomic_arch.h:77
#1  __stack_chk_fail () at src/env/__stack_chk_fail.c:17
#2  0x0003143a in custom_popene ()
#3  0x000316d2 in mypopen ()
#4  0x0001bfb0 in send_statistics ()
#5  0x0001c258 in analytics_main ()
#6  0x00037f72 in thread_start ()
#7  0x0052f71c in start (p=0xa5de1bb4) at src/thread/pthread_create.c:203
#8  0x0052e86e in __clone () at src/thread/arm/clone.s:23
#9  0x0052e86e in __clone () at src/thread/arm/clone.s:23
#10 0x0052e86e in __clone () at src/thread/arm/clone.s:23
#11 0x0052e86e in __clone () at src/thread/arm/clone.s:23
```

**Comment by MrZammler** [comment]
Ok, thanks guys! Both of these suggestions work, because in the end we stop trying to do this https://github.com/netdata/netdata/blob/4616491f1a2561285197126fe4683edc71001455/libnetdata/libnetdata.c#L1121

It seems we get away with it just because we always have an extra byte available than we tell snprintfz (e.g. https://github.com/netdata/netdata/blob/4616491f1a2561285197126fe4683edc71001455/collectors/proc.plugin/proc_mdstat.c#L67-L78)

We should not be using the return value of `vsnprintf` to access the array. `dst[n - 1] = '\0';` should also be already done by `vsnprintf` as well, but doesn't hurt. I'll commit Costa's version.

**Review by ilyam8 — APPROVED** [review]

**Review by vlvkobal — APPROVED** [review]

**Review by erdem2000 — APPROVED** [review]

**Pull request merged**
