### PR TITLE
Update md5sum

### PR DESCRIPTION
**Pull request by drconopoima**
##### Summary
It's missing the md5sum for script validation

##### Test Plan
only documentation

### CODE REVIEW

**Comment by ilyam8** [comment]
Hi, @drconopoima. `<checksum-will-be-added-in-documentation-processing>` gets replaced on [ingesting documentation](https://github.com/netdata/learn/blob/da85a7cd2856af3886b9c8b349ced25b5b3879fd/.github/workflows/ingest.yml#L28-L34). See [Verify script integrity](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#verify-script-integrity), it has valid md5sum.

**Comment by drconopoima** [comment]
Has it been updated recently? I'm getting a mistmatch
```sh
[ "8cea198becaf00dea0f8a784e58805ed" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"
FAILED, INVALID
```
What I download, has md5sum: "872dcb111f63daa8042e9f03d4e5563c"

**Comment by ilyam8** [comment]
You are right. It is because https://github.com/netdata/learn/pull/1204 hasn't been merged yet (it has the correct md5sum).

**Comment by ilyam8** [comment]
I reported the problem, should be merged soon.

**Pull request closed without merging**
