### PR TITLE
add api/v1/info endpoint to swagger

### LINKED ISSUE #3540: [web api] Add /api/v1/version
Currently, we can get netdata version from /api/v1/charts, but this API contains too much info.
I suggest add `/api/v1/version` to only contain version and git commit SHA.
`/api/v1/version` is useful to service discovery.

ref: #3217

### PR DESCRIPTION
**Pull request by Wing924**
##### Summary
Fixes #3540
ref: #4770

##### Component Name
web

### CODE REVIEW

**Comment by ktsaou** [comment]
thank you!
You rock!

**Comment by ktsaou** [comment]
also a minor thing:

I usually compile netdata will all the compiler warnings enabled, like this:

```
CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto --dont-wait
```

PR #4470 introduced these warnings:

```
  CC       backends/prometheus/backend_prometheus.o
In file included from ./daemon/../libnetdata/libnetdata.h:292,
                 from ./daemon/common.h:6,
                 from web/api/web_api_v1.h:6,
                 from web/api/web_api_v1.c:3:
web/api/web_api_v1.c: In function 'web_client_api_request_v1_info_summary_alarm_statuses':
./database/rrd.h:606:52: warning: passing argument 4 of 'netdata_rwlock_rdlock_debug' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 #define rrdhost_rdlock(host) netdata_rwlock_rdlock(&((host)->rrdhost_rwlock))
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
./daemon/../libnetdata/locks/locks.h:52:104: note: in definition of macro 'netdata_rwlock_rdlock'
 #define netdata_rwlock_rdlock(rwlock)    netdata_rwlock_rdlock_debug(__FILE__, __FUNCTION__, __LINE__, rwlock)
                                                                                                        ^~~~~~
web/api/web_api_v1.c:621:5: note: in expansion of macro 'rrdhost_rdlock'
     rrdhost_rdlock(host);
     ^~~~~~~~~~~~~~
./daemon/../libnetdata/locks/locks.h:34:125: note: expected 'netdata_rwlock_t *' {aka 'union <anonymous> *'} but argument is of type 'const netdata_rwlock_t *' {aka 'const union <anonymous> *'}
 extern int netdata_rwlock_rdlock_debug( const char *file, const char *function, const unsigned long line, netdata_rwlock_t *rwlock);
                                                                                                           ~~~~~~~~~~~~~~~~~~^~~~~~
./database/rrd.h:608:52: warning: passing argument 4 of 'netdata_rwlock_unlock_debug' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 #define rrdhost_unlock(host) netdata_rwlock_unlock(&((host)->rrdhost_rwlock))
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
./daemon/../libnetdata/locks/locks.h:54:104: note: in definition of macro 'netdata_rwlock_unlock'
 #define netdata_rwlock_unlock(rwlock)    netdata_rwlock_unlock_debug(__FILE__, __FUNCTION__, __LINE__, rwlock)
                                                                                                        ^~~~~~
web/api/web_api_v1.c:637:5: note: in expansion of macro 'rrdhost_unlock'
     rrdhost_unlock(host);
     ^~~~~~~~~~~~~~
./daemon/../libnetdata/locks/locks.h:36:125: note: expected 'netdata_rwlock_t *' {aka 'union <anonymous> *'} but argument is of type 'const netdata_rwlock_t *' {aka 'const union <anonymous> *'}
 extern int netdata_rwlock_unlock_debug( const char *file, const char *function, const unsigned long line, netdata_rwlock_t *rwlock);
                                                                                                           ~~~~~~~~~~~~~~~~~~^~~~~~
web/api/web_api_v1.c: In function 'web_client_api_request_v1_info':
web/api/web_api_v1.c:656:86: warning: unused parameter 'url' [-Wunused-parameter]
 inline int web_client_api_request_v1_info(RRDHOST *host, struct web_client *w, char *url) {
                                                                                ~~~~~~^~~
```

I think they are mainly due to the `const` parameter of the function call and unused function parameters.

Could you please fix them too?

**Comment by Wing924** [comment]
@ktsaou I'm not sure which variable needs `const` and I compiled it in docker with given flags but got no warning. Could you help me?

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/pull/4911

**Comment by ktsaou** [comment]
> @ktsaou I'm not sure which variable needs `const` and I compiled it in docker with given flags but got no warning. Could you help me?

It is ok, I fixed it with #4911 
On fedora it didn't even compile with this:

```sh
CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto --dont-wait
```

Generally, when I compile netdata, I enable all checks the compiler could do and I fix all warnings.

**Pull request merged**
