### PR TITLE
Use print macros

### LINKED ISSUE #13872: [Bug]: Segmentation fault using static builds on Raspbian 11 (32-bit)
### Bug description

When installing the latest nightly on a 32-bit Raspbian, the agent keeps restarting and hitting a segmentation fault.

### Expected behavior

Not to crash.

### Steps to reproduce

Install `netdata v1.36.0-257-g19f023c11` on a 32-bit Raspbian using a static build (default on Raspberry Pi).

### Installation method

kickstart.sh

### System info

```shell
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
```

### Netdata build info

```shell
Version: netdata v1.36.0-257-g19f023c11
Configure options:  '--prefix=/opt/netdata/usr' '--sysconfdir=/opt/netdata/etc' '--localstatedir=/opt/netdata/var' '--libexecdir=/opt/netdata/usr/libexec' '--libdir=/opt/netdata/usr/lib' '--with-zlib' '--with-math' '--with-user=netdata' '--enable-cloud' '--without-bundled-protobuf' '--disable-dependency-tracking' 'CFLAGS=-static -O2 -I/openssl-static/include -pipe' 'LDFLAGS=-static -L/openssl-static/lib' 'PKG_CONFIG_PATH=/openssl-static/lib/pkgconfig'
Install type: kickstart-static
    Binary architecture: armv7l
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK:                       YES
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    NO
    EBPF:                    YES
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
Debug/Developer Features:
    Trace Allocations:       NO
```

### Additional info

Core dump:
```
#0  0x00563db4 in memchr (src=src@entry=0x1, c=c@entry=0, n=n@entry=2147483647) at src/string/memchr.c:16
#1  0x005642ae in strnlen (s=s@entry=0x1 <error: Cannot access memory at address 0x1>, n=2147483647) at src/string/strnlen.c:5
#2  0x00562310 in printf_core (f=f@entry=0xb533d238, fmt=fmt@entry=0x5a4d3c "chart://host:%s/instance:%s/dimensions:%s/after:%ld/before:%ld/points:%zu/group:%s%s/options:%s%s%s", ap=ap@entry=0xb533d134,
    nl_arg=nl_arg@entry=0xb533d160, nl_type=<optimized out>, nl_type@entry=0xb533d138) at src/stdio/vfprintf.c:594
#3  0x00562df8 in vfprintf (f=0xb533d238, fmt=fmt@entry=0x5a4d3c "chart://host:%s/instance:%s/dimensions:%s/after:%ld/before:%ld/points:%zu/group:%s%s/options:%s%s%s", ap=..., ap@entry=...)
    at src/stdio/vfprintf.c:683
#4  0x0056379c in vsnprintf (s=<optimized out>, n=255, fmt=0x5a4d3c "chart://host:%s/instance:%s/dimensions:%s/after:%ld/before:%ld/points:%zu/group:%s%s/options:%s%s%s", ap=...) at src/stdio/vsnprintf.c:54
#5  0x00037268 in snprintfz ()
#6  0x00105bac in query_target_generate_name ()
#7  0x00585cec in ?? ()
```

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Fixes #13872 

Uses print macros where needed, to keep 32bit static builds from crashing.

##### Test Plan

I have tested this on a static build for 32bit arm7vl under Raspbian 10. Currently arm 32bit static builds crash during `query_target_generate_name`.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]

**Review by Ferroin — DISMISSED** [review]
Tested locally in assorted 32-bit ARM Docker images and 32-bit ARM chroots.

**Review by thiagoftsm — CHANGES_REQUESTED** [review]
Hello @MrZammler ,

I tested your PR now on `armvl7` using : 

```sh
root@potinho:/home/thiago/Netdata/netdata# uname -a; grep -HvE "^#|URL" /etc/*release
Linux potinho 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
/etc/os-release:PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
/etc/os-release:NAME="Raspbian GNU/Linux"
/etc/os-release:VERSION_ID="11"
/etc/os-release:VERSION="11 (bullseye)"
/etc/os-release:VERSION_CODENAME=bullseye
/etc/os-release:ID=raspbian
/etc/os-release:ID_LIKE=debian
root@potinho:/home/thiago/Netda
```

and I am still observing some [warnings](https://github.com/netdata/netdata/files/9855815/err.txt) and crash persists. I am sending the backtrace:

```sh
#0  strlen () at ../sysdeps/arm/armv6/strlen.S:26
#1  0xb68493f0 in __vfprintf_internal (s=0xb4fb9268, s@entry=0x0, format=format@entry=0x631188 "chart://host:%s/instance:%s/dimensions:%s/after:%lld/before:%lld/points:%zu/group:%s%s/options:%s%s%s", ap=..., ap@entry=..., 
    mode_flags=mode_flags@entry=0) at vfprintf-internal.c:1688
#2  0xb685b36c in __vsnprintf_internal (string=string@entry=0xb4fba640 "chart://host:potinho/instance:system.load/dimensions:load15/after:4294967236/before:28668941060538369/points:6255672/group:unaligned/options:{%s} = ", 
    maxlen=<optimized out>, maxlen@entry=255, format=0x631188 "chart://host:%s/instance:%s/dimensions:%s/after:%lld/before:%lld/points:%zu/group:%s%s/options:%s%s%s", args=..., args@entry=..., mode_flags=2) at vsnprintf.c:114
#3  0xb68dd10c in ___vsnprintf_chk (s=s@entry=0xb4fba640 "chart://host:potinho/instance:system.load/dimensions:load15/after:4294967236/before:28668941060538369/points:6255672/group:unaligned/options:{%s} = ", maxlen=maxlen@entry=255, 
    flag=flag@entry=1, slen=slen@entry=4294967295, format=0x2 <error: Cannot access memory at address 0x2>, format@entry=0xb4fb93a4 "0\326\033", ap=...) at vsnprintf_chk.c:34
#4  0x00053bf4 in vsnprintf (__ap=..., __fmt=0xb4fb93a4 "0\326\033", __n=255, 
    __s=0xb4fba640 "chart://host:potinho/instance:system.load/dimensions:load15/after:4294967236/before:28668941060538369/points:6255672/group:unaligned/options:{%s} = ") at /usr/include/arm-linux-gnueabihf/bits/stdio2.h:80
#5  vsnprintfz (dst=dst@entry=0xb4fba640 "chart://host:potinho/instance:system.load/dimensions:load15/after:4294967236/before:28668941060538369/points:6255672/group:unaligned/options:{%s} = ", n=n@entry=255, 
    fmt=fmt@entry=0x631188 "chart://host:%s/instance:%s/dimensions:%s/after:%lld/before:%lld/points:%zu/group:%s%s/options:%s%s%s", args=..., args@entry=...) at libnetdata/libnetdata.c:1367
#6  0x00053c70 in snprintfz (dst=dst@entry=0xb4fba640 "chart://host:potinho/instance:system.load/dimensions:load15/after:4294967236/before:28668941060538369/points:6255672/group:unaligned/options:{%s} = ", n=n@entry=255, 
    fmt=0x631188 "chart://host:%s/instance:%s/dimensions:%s/after:%lld/before:%lld/points:%zu/group:%s%s/options:%s%s%s") at libnetdata/libnetdata.c:1379
#7  0x001bd630 in query_target_generate_name (qt=qt@entry=0xb4fba640) at database/rrdcontext.c:2631
#8  0x001bd8d0 in query_target_create (qtr=qtr@entry=0xb4fb9554) at database/rrdcontext.c:2689
#9  0x00075abc in rrd2rrdr_legacy (owa=owa@entry=0x4df5d30, st=st@entry=0x4570350, points=points@entry=1, after=after@entry=-60, before=before@entry=0, group_method=RRDR_GROUPING_MAX, resampling_time=0, 
    options=RRDR_OPTION_NOT_ALIGNED, dimensions=0x43361f0 "load15", group_options=0x0, timeout=0, tier=0) at web/api/queries/query.c:1954
#10 0x00078e08 in rrdset2value_api_v1 (st=st@entry=0x4570350, wb=wb@entry=0x0, n=n@entry=0x426ac58, dimensions=0x43361f0 "load15", points=points@entry=1, after=-60, before=0, group_method=RRDR_GROUPING_MAX, 
    group_options=group_options@entry=0x0, resampling_time=resampling_time@entry=0, options=4096, db_after=db_after@entry=0x426ac80, db_before=db_before@entry=0x426ac84, db_points_read=db_points_read@entry=0x0, 
    db_points_per_tier=db_points_per_tier@entry=0x0, result_points_generated=result_points_generated@entry=0x0, value_is_null=value_is_null@entry=0xb4fb976c, anomaly_rate=anomaly_rate@entry=0x0, timeout=timeout@entry=0, 
    tier=tier@entry=0) at web/api/formatters/rrd2json.c:83
#11 0x00090180 in health_main (ptr=0x3593b88) at health/health.c:1036
#12 0x00065df8 in thread_start (ptr=0x2987570) at libnetdata/threads/threads.c:203
#13 0xb6b71310 in start_thread (arg=0xb4fba040) at pthread_create.c:477
#14 0xb68ceda8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```

**Comment by thiagoftsm** [comment]
@MrZammler to generate previous logs I used these CFLAGS:

```sh
CFLAGS="-Og -ggdb -Wall -Wextra -fno-omit-frame-pointer -Wformat-signedness -fstack-protector-all -Wformat-truncation=2 -Wunused-result -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh
````

and I compiled last commit:

```sh
thiago@potinho:~/Netdata/netdata $ git log
commit 672b33219d811dccc2c3c351cd30869c5282db1c (HEAD -> pr13876)
Author: Emmanuel Vasilakis <mrzammler@mm.st>
Date:   Mon Oct 24 22:22:42 2022 +0300

    use print macros
```

**Comment by MrZammler** [comment]
Ok, thanks guys. Seems that using print macros would have problems in local build on 32bit arm.

Instead, since musl's time_t is always long long (32 and 64), the safest way seems for now to cast our time_t to long long.

I have this running now as a static musl build on arm 32bit, tried also local 32bit arm build, both look ok, but more tests are welcome.

**Review by ilyam8 — APPROVED** [review]

**Comment by MrZammler** [comment]
Thanks!

**Pull request merged**
