### PR TITLE
eBPF ZFS monitoring

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
This PR has relationship with issue https://app.zenhub.com/workspaces/product-5ea1534e9ff5df7daace00d5/issues/netdata/product/2142.

This PR is bringing latency monitoring for [ZFS](https://zfsonlinux.org/). I tested the PR with versions [2.0.5](https://github.com/openzfs/zfs/releases/download/zfs-2.0.5/zfs-2.0.5.tar.gz) and [2.1.0](https://github.com/openzfs/zfs/releases/download/zfs-2.1.0/zfs-2.1.0.tar.gz).  I did not test with `0.8.x`, because it is not compiling on my environments. 

##### Component Name
ebpf.plugin
##### Test Plan

1 - I did not have `ZFS` compiled, so I am starting with the environment. Compile `ZFS`:

```bash
# sh autogen.sh 
# ./configure 
# make -s -j4
# make install
# ldconfig 
# depmod
```
2 - Load module:

```bash
#  /sbin/modprobe zfs
```

3 - Create a pool. This example assumes that you are using only a partition.

```bash
# zpool create -d -o ashift=12 test /dev/sdc4
```

4 - Enable `filesystem` thread inside `/etc/netdata/ebpf.d.conf`

```conf
[ebpf programs]
    filesystem = yes
```

5 - Compile this Branch and start netdata
6 - The step 3 made a directory `/test/  where we need to create content to generate data, I suggest to copy files from `/var/log/netdata` to the cited directory and after this you can open a file, remove few lines and save. This is enough to show data on all charts.

##### Additional Information

ZFS is not merged on kernel, it is a module that we compile, so it is not necessary to use different kernel versions.

### CODE REVIEW

**Comment by MrZammler** [comment]
Tested here with zfs 2.0.5, kernel 5.10, works fine, graph from editing a big (30M) file inside a zfs pool and saving:

zfs_ebpf_text

**Review by MrZammler — APPROVED** [review]

**Comment by UmanShahzad** [comment]
I will review this tomorrow; finally got my local stack running eBPF/apps.plugin properly thanks to @thiagoftsm.

**Comment by underhood** [comment]
LGTM on FC34

**Review by underhood — APPROVED** [review]

**Review by UmanShahzad — APPROVED** [review]
Did a test and it works:

```bash
$ while [ true ] ; do sleep "0.$(shuf -i 1-1000 -n 1)" ; sudo cp -r /var/log/netdata/ /test/ ; cat /test/netdata/error.log > /dev/null ; done
```

image

**Pull request merged**
