### PR TITLE
remove vneg from ACLK-NG

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Removes version negotiation code `hello`/`version` messages which have been obsoleted in favor of feature flags/capabilities mechanism in new cloud architecture

##### Component Name
ACLK-NG
##### Test Plan
Should still work OK with cloud as before

### CODE REVIEW

**Comment by underhood** [comment]
I am keeping the inbound msgtype resolution there as there will be new message types in future PRs.
```
    for (int i = 0; aclk_incoming_msg_types[i].name; i++) {
        if (strcmp(cloud_to_agent.type_id, aclk_incoming_msg_types[i].name) == 0) {
            if (likely(!aclk_incoming_msg_types[i].fnc(&cloud_to_agent, payload))) {
                // in case of success handler is supposed to clean up after itself
                // or as in the case of aclk_handle_cloud_request take
                // ownership of the pointers (done to avoid copying)
                // see what `aclk_queue_query` parameter `internal` does

                // NEVER CONTINUE THIS LOOP AFTER CALLING FUNCTION!!!
                // msg handlers (namely aclk_handle_version_responce)
                // can freely change what aclk_incoming_msg_types points to
                // so either exit or restart this for loop
                freez(cloud_to_agent.type_id);
                return 0;
            }
            goto err_cleanup;
        }
    }
    ```

**Review by stelfrag — DISMISSED** [review]
Looks good -- needs to go after the new https client otherwise will deadlock

**Review by vkalintiris — DISMISSED** [review]
LGTM. FYI, there's a comment reference to `version_neg` in aclk_tx_msgs.c

**Comment by underhood** [comment]
@vkalintiris thx I removed the reference in the comment

**Review by stelfrag — APPROVED** [review]

**Review by vkalintiris — APPROVED** [review]

**Pull request merged**
