### PR TITLE
yamllint: ignore swagger file

### PR DESCRIPTION
**Pull request by jsoref**
##### Summary
w/o this change, yamllint complaints about very long lines in the swagger yaml file.

##### Component Name
build

##### Test Plan

a PR into this branch that changes a yaml file, or the swagger yaml file

##### Additional Information
I believe that swagger yaml files should be linted w/ a swagger 3 targeted linter.

### CODE REVIEW

**Comment by jsoref** [comment]
I can't tell if the yaml is a generated thing or a source and similarly for the json.

If the yaml is canonical and the json is generated, then it's possible the right thing to do is to just wrap the yaml file entries at reasonable points instead of what this change does. I could do that.

Right now, the swagger yaml file triggers errors if one touches the file, which is less than ideal.

**Review by knatsakis — DISMISSED** [review]

**Review by Stevenans66 — DISMISSED** [review]

**Comment by jsoref** [comment]
@Ferroin: do I need to do anything for this?

**Comment by jsoref** [comment]
Or @ilyam8 ?

**Comment by vlvkobal** [comment]
This one also has to be rebased.

**Comment by Ferroin** [comment]
@netdata/agent Can anyone confirm whether the JSON or YAML Swagger file is the primary source of truth? If the former, then this Pr is correct and should be merged, if the latter we should fix the YAML file to not have excessively long lines instead of ignoring it.

**Comment by vlvkobal** [comment]
YAML is the primary one.

**Comment by ilyam8** [comment]
> I believe that swagger yaml files should be linted w/ a swagger 3 targeted linter.

I think that is the question. 

Perhaps https://github.com/stoplightio/spectral-action fits better?

```cmd
[ilyam@pc ~]$ docker run --rm -it -v $(pwd)/netdata:/netdata stoplight/spectral lint "/netdata/web/api/netdata-swagger.yaml"
OpenAPI 3.x detected

/netdata/web/api/netdata-swagger.yaml
   1:1    warning  openapi-tags                   OpenAPI object should have non-empty `tags` array.
   2:6    warning  info-contact                   Info object should contain `contact` object.
   8:9    warning  operation-operationId          Operation should have an `operationId`.
   8:9    warning  operation-tags                 Operation should have non-empty `tags` array.
   31:9   warning  operation-operationId          Operation should have an `operationId`.
   31:9   warning  operation-tags                 Operation should have non-empty `tags` array.
   43:9   warning  operation-operationId          Operation should have an `operationId`.
   43:9   warning  operation-tags                 Operation should have non-empty `tags` array.
   67:9   warning  operation-operationId          Operation should have an `operationId`.
   67:9   warning  operation-tags                 Operation should have non-empty `tags` array.
   97:9   warning  operation-operationId          Operation should have an `operationId`.
   97:9   warning  operation-tags                 Operation should have non-empty `tags` array.
  301:9   warning  operation-operationId          Operation should have an `operationId`.
  301:9   warning  operation-tags                 Operation should have non-empty `tags` array.
  550:9   warning  operation-operationId          Operation should have an `operationId`.
  550:9   warning  operation-tags                 Operation should have non-empty `tags` array.
  676:9   warning  operation-operationId          Operation should have an `operationId`.
  676:9   warning  operation-tags                 Operation should have non-empty `tags` array.
  705:9   warning  operation-operationId          Operation should have an `operationId`.
  705:9   warning  operation-tags                 Operation should have non-empty `tags` array.
  736:9   warning  operation-operationId          Operation should have an `operationId`.
  736:9   warning  operation-tags                 Operation should have non-empty `tags` array.
  761:9   warning  operation-operationId          Operation should have an `operationId`.
  761:9   warning  operation-tags                 Operation should have non-empty `tags` array.
  807:9   warning  operation-operationId          Operation should have an `operationId`.
  807:9   warning  operation-tags                 Operation should have non-empty `tags` array.
 1282:15  warning  oas3-unused-components-schema  Potentially unused components schema has been detected.
 1303:15  warning  oas3-unused-components-schema  Potentially unused components schema has been detected.
 1311:16  warning  oas3-unused-components-schema  Potentially unused components schema has been detected.
 1320:23  warning  oas3-unused-components-schema  Potentially unused components schema has been detected.
 1333:20  warning  oas3-unused-components-schema  Potentially unused components schema has been detected.

✖ 31 problems (0 errors, 31 warnings, 0 infos, 0 hints)
```

**Comment by Ferroin** [comment]
Hmm, yeah, we probably should use a more specific linter here. If we do go that way, I _think_ that we should indeed ignore the swagger file for yamllint, but I’m not certain on that.

**Comment by ilyam8** [comment]
Closing because we don't want to exclude `netdata-swagger.yaml`. 

The correct fix, I think, is:

- use [stoplightio/spectral-action](https://github.com/stoplightio/spectral-action) for linting `netdata-swagger.yaml`.
- exclude `netdata-swagger.yaml` from yamllint.

**Pull request closed without merging**
