### PR TITLE
Removed extra printed `\n`

### PR DESCRIPTION
**Pull request by Jiab77**
##### Summary

When running the installation script, a lot of `\n` got printed before the return status `[OK]` or `[ERROR]`.

##### Component Name

Installer

##### Description of testing that the developer performed

Ran the install script locally

### CODE REVIEW

**Comment by prologic** [comment]
@Jiab77 Please update the SHA256 checksum in our docs. See [these logs](https://travis-ci.com/netdata/netdata/jobs/295169928)

**Comment by prologic** [comment]
@Jiab77 Actually hold that thought... This _may_ not be the result of your PRs. Let me see what's going on here.

**Comment by prologic** [comment]
@Jiab77 Ahh yes. You need to update the md5sum of `kickstart.sh` in `packaging/installer/methods/kickstart.md`. Please do so. It _might_ be better if you combine the changes in this PR along with #8325 and #8326 like I did in #8328 to test your changes :)

**Comment by Jiab77** [comment]
@prologic, thanks a lot for the review. Not sure how to merge all PR into one... but yes I can quickly update the sha256sum in the given file. Should I create another PR?

**Comment by Jiab77** [comment]
@prologic for what I have seen / tested, the issue was at first in `packaging/installer/functions.sh` then I went further and found similar issues in `netdata-installer.sh` and `packaging/installer/kickstart.sh` but I totally forgot the checksum file :sweat_smile:

**Comment by prologic** [comment]
Its okay I fixed it for you :) And once all tests pass I'll merge all 3 PRs

**Comment by Jiab77** [comment]
Thank you so much @prologic

**Pull request merged**
