### PR TITLE
Add document outlining our versioning policy and public API.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

To go into effect with the release of v2.0.0.

This is intended to specifically cover when breaking changes may happen, and indicate when they are guaranteed not to happen.

##### Test Plan

n/a

### CODE REVIEW

**Comment by thiagoftsm** [comment]
@Ferroin,

Should we also explain versioning that we are using in other repos like `go.d.plugin` and `kernel-collector`? For eBPF, for example, I am following `libbpf` version numbers to keep track with kernel changes.

I am expecting possible changes with other PRs.

Best regards!

**Comment by Ferroin** [comment]
> Should we also explain versioning that we are using in other repos like `go.d.plugin` and `kernel-collector`? For eBPF, for example, I am following `libbpf` version numbers to keep track with kernel changes.

I think we should be documenting that, but IMO it should be documented in the respective repos, not in this document.

**Comment by thiagoftsm** [comment]
> I think we should be documenting that, but IMO it should be documented in the respective repos, not in this document.

I will prepare documentation for them.

**Review by thiagoftsm — DISMISSED** [review]
After received answer, LGTM!

**Pull request merged**
