### PR TITLE
[area/collectors] Added support for libvirtd LXC containers to the `cgroup-name.sh` cgroup name normalization script

### PR DESCRIPTION
**Pull request by endreszabo**
Signed-off-by: git@end.re <git@end.re>

##### Summary

Added support for libvirtd LXC containers to the `cgroup-name.sh` cgroup name normalization helper script found in `netdata/collectors/cgroups.plugin`.

##### Component Name

area/collectors

##### Description of testing that the developer performed

The bash script `cgroup-name.sh`, a "Script to find a better name for cgroups" had support for libvirtd QEMU VMs but not for LXC containers. This PR adds support to get the libvirtd LXC container names normalized as well.

##### Additional Information

Example outputs:

```
$ ./cgroup-name.sh.in 'machine.slice_machine-lxc/x2d9192/x2datvie0ximta01.scope'     
2020-03-05 09:32:22: cgroup-name.sh.in: INFO: cgroup 'machine.slice_machine-lxc/x2d9192/x2datvie0ximta01.scope' is called 'lxc/atvie0ximta01'
lxc/atvie0ximta01
$ ./cgroup-name.sh.in 'machine.slice_machine-lxc/x2d3353752/x2datvie0xifsr01.scope'
2020-03-05 09:32:45: cgroup-name.sh.in: INFO: cgroup 'machine.slice_machine-lxc/x2d3353752/x2datvie0xifsr01.scope' is called 'lxc/atvie0xifsr01'
lxc/atvie0xifsr01
```

### CODE REVIEW

**Review by vlvkobal — DISMISSED** [review]
LGTM.
I haven't tested it though.

**Comment by ilyam8** [comment]
@endreszabo hey 👋 

> 'machine.slice_machine-lxc/x2d9192/x2datvie0ximta01.scope' is called 'lxc/atvie0ximta01'

What about uniqueness? Could it be like

- machine.slice_machine-lxc/**x2d9192**/x2datvie0ximta01.scope
- machine.slice_machine-lxc/**x2d9193**/x2datvie0ximta01.scope

**Comment by endreszabo** [comment]
Thanks for asking.

> What about uniqueness?

Uniqueness is 'provided' by how `libvirt` works. With `libvirt` (frontend for LXC et al.) you can't launch multiple containers with the same name. The number in the middle is only the PID of the 'supervising' process.

```
[e@ip-172-30-0-48 ~]$ systemctl | grep lxc
  machine-lxc\x2d669\x2diedub0xians01.scope                                 loaded active     running      Container lxc-669-iedub0xians01
[e@ip-172-30-0-48 ~]$ machinectl
MACHINE               CLASS     SERVICE     OS   VERSION ADDRESSES       
lxc-669-iedub0xians01 container libvirt-lxc arch -       

1 machines listed.
[e@ip-172-30-0-48 ~]$ ps aux | grep 669
root         669  0.0  1.9 357516 18864 ?        Sl   13:26   0:00 /usr/lib/libvirt/libvirt_lxc --name iedub0xians01 --console 29 --security=none --handshake 32 --veth vnet0
```

**Comment by ilyam8** [comment]
@endreszabo Thanks for the answer!

There are merge conflicts, could you fix them? Also likely you will need a rebase to fix ci checks.

**Comment by endreszabo** [comment]
> endreszabo wants to merge 425 commits into netdata:master 

Wow, not sure if this is what I wanted. Actually, this my first time git rebase, conflict resolved, pulled, pushed.

**Comment by endreszabo** [comment]
> what I wanted

It might be better reopening the PR.

**Comment by ilyam8** [comment]
@endreszabo yeah, sounds good 👍

**Pull request closed without merging**
