### PR TITLE
Persist `$TMPDIR` from installer to updater.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This updates the installer to persist the value of the `$TMPDIR` environment variable so that it will be used automatically by the updater.

By default this persisted value is used in preference to any setting for `$TMPDIR` at runtime unless the path is not usable (doesn’t exist, or doesn’t allow both writing and executing files).

##### Component Name

area/packaging

##### Test Plan

Behavior verified locally.

##### Additional Information

Fixes: #10377

### CODE REVIEW

**Review by knatsakis — APPROVED** [review]

**Review by stevenans9859 — APPROVED** [review]

**Comment by therealgilles** [comment]
Does this fix mean we need to define NETDATA_TMPDIR in /etc/netdata/.environment when /tmp has the noexec atttribute, like this:
`NETDATA_TMPDIR=/root/tmp # or some other executable directory`
?

**Comment by Ferroin** [comment]
@therealgilles The first successful update to a version with this fix _should_ set the variable correctly without needing any user intervention unless none of the default locations we check (`$TMPDIR`, `/tmp`, and then the current working directory) meet the requirements for our usage.

Manually setting the variable would work also though.

**Comment by therealgilles** [comment]
Trying to run the cron job manually, I get this:

```
> /etc/cron.daily/netdata-updater 
Checking if a newer version of the updater script is available.
Downloading newest version of updater script.
/root/tmp/netdata-updater-ppQAIwvx9X/netdata-updater.sh: line 354: THIS_SHOULD_BE_REPLACED_BY_INSTALLER_SCRIPT: No such file or directory
```

**Comment by therealgilles** [comment]
It's now working after re-running: `bash <(curl -Ss https://my-netdata.io/kickstart.sh) --stable-channel --reinstall`
Weird that it did not work after I ran it yesterday, unless there was a fix/update since then.

**Comment by Ferroin** [comment]
The `ENVIRONMENT_FILE` thing is an unrelated bug that will be fixed by #10447.

**Comment by therealgilles** [comment]
Thank you for the response. I would personally call that a related bug due to its effect.

**Pull request merged**
