### PR TITLE
Adds missing files for streaming changes into cmake build

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Adds missing streaming related files to cmake.
This was causing cmake build to fail after the recent changes to streaming.

Additionally, it removes check for nonexistent feature flag (env var $ACLK) for ACLK build

##### Component Name
build/cmake
##### Test Plan
during build with cmake you should not see streaming related build errors anymore

### CODE REVIEW

**Comment by vlvkobal** [comment]
```
sudo CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-go --disable-lto --dont-wait --dont-start-it
mkdir cmake-build-debug; cd cmake-build-debug
cmake -DCMAKE_BUILD_TYPE="Debug" -DUNIT_TESTING=ON ..
make -j8
```
```
[100%] Linking CXX executable netdata
/usr/bin/ld: CMakeFiles/netdata.dir/daemon/main.c.o:(.data.rel+0x238): undefined reference to `aclk_main'
/usr/bin/ld: CMakeFiles/netdata.dir/web/api/web_api_v1.c.o: in function `web_client_api_request_v1_info_fill_buffer':
/home/vlad/test/netdata/web/api/web_api_v1.c:885: undefined reference to `aclk_connected'
/usr/bin/ld: CMakeFiles/netdata.dir/health/health.c.o: in function `health_reload':
/home/vlad/test/netdata/health/health.c:224: undefined reference to `aclk_single_update_disable'
/usr/bin/ld: /home/vlad/test/netdata/health/health.c:235: undefined reference to `aclk_single_update_enable'
/usr/bin/ld: /home/vlad/test/netdata/health/health.c:236: undefined reference to `aclk_alarm_reload'
/usr/bin/ld: CMakeFiles/netdata.dir/health/health_log.c.o: in function `health_alarm_log_save':
/home/vlad/test/netdata/health/health_log.c:157: undefined reference to `aclk_update_alarm'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrdcalc_link_to_rrddim':
/home/vlad/test/netdata/database/rrddim.c:188: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrddim_add_custom':
/home/vlad/test/netdata/database/rrddim.c:433: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrddim_free':
/home/vlad/test/netdata/database/rrddim.c:490: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrddim_hide':
/home/vlad/test/netdata/database/rrddim.c:512: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrddim_unhide':
/home/vlad/test/netdata/database/rrddim.c:530: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o:/home/vlad/test/netdata/database/rrddim.c:542: more undefined references to `aclk_update_chart' follow
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrdset.c.o: in function `rrdset_delete':
/home/vlad/test/netdata/database/rrdset.c:429: undefined reference to `aclk_del_collector'
/usr/bin/ld: /home/vlad/test/netdata/database/rrdset.c:430: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrdset.c.o: in function `rrdset_create_custom':
/home/vlad/test/netdata/database/rrdset.c:774: undefined reference to `aclk_add_collector'
/usr/bin/ld: /home/vlad/test/netdata/database/rrdset.c:775: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/claim/claim.c.o: in function `claim_agent':
/home/vlad/test/netdata/claim/claim.c:71: undefined reference to `aclk_get_proxy'
/usr/bin/ld: CMakeFiles/netdata.dir/claim/claim.c.o: in function `load_claiming_state':
/home/vlad/test/netdata/claim/claim.c:142: undefined reference to `aclk_connected'
/usr/bin/ld: /home/vlad/test/netdata/claim/claim.c:145: undefined reference to `aclk_kill_link'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/netdata.dir/build.make:2348: netdata] Error 1
make[1]: *** [CMakeFiles/Makefile2:773: CMakeFiles/netdata.dir/all] Error 2
make: *** [Makefile:115: all] Error 2
[vlad@arch-esxi cmake-build-debug]$

```

**Comment by underhood** [comment]
OK i will take a look also on the ACLK errors.

**Comment by underhood** [comment]
ahh i see i think in `CMAKE` we didnt remove the environment variable `IF("$ENV{ACLK}")` as we did in `autotools`

but on my system that variable is still defined :D

**Comment by underhood** [comment]
@vlvkobal I removed that check of ACLK env var
is still not perfect for ACLK but it should work for now (i will have to make PR in future that fixes this properly)

**Pull request merged**
