### PR TITLE
typo fixed in gen_docs_integrations.py

### PR DESCRIPTION
**Pull request by khalid586**
##### Summary
**Typo has been fixed.**
##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by khalid586** [comment]
@ktsaou  can you please tell me if there is any problem in this PR? If not then when will it be merged?

**Review by Ancairon — APPROVED** [review]

**Review by ilyam8 — APPROVED** [review]

**Comment by ilyam8** [comment]
Hey, @khalid586. If you notice any other typos, please add them to this PR.

**Comment by khalid586** [comment]
> Hey, @khalid586. If you notice any other typos, please add them to this PR.

Sure.Can you tell me when will it be merged?

**Comment by ilyam8** [comment]
Yes, as soon as you answer https://github.com/netdata/netdata/pull/16288#issuecomment-1784833021. If there are any other typos you want to fix - please update this PR. If there are no other typos you want to fix - we will merge this PR.

**Comment by khalid586** [comment]
> Yes, as soon as you answer [#16288 (comment)](https://github.com/netdata/netdata/pull/16288#issuecomment-1784833021). If there are any other typos you want to fix - please update this PR. If there are no other typos you want to fix - we will merge this PR.

I haven't found any other typo.You can merge the PR.

**Pull request merged**
