### PR TITLE
updated configs.signatures

### PR DESCRIPTION
**Pull request by ktsaou**

### CODE REVIEW

**Comment by paulfantom** [comment]
What is this?

**Comment by ktsaou** [comment]
Well another annoyance we have to fix.

the installer installs config files in `/etc/netdata`. To update them, it keeps track of MD5 hashes for all of them, so when it updates netdata, it checks if the files are stock. If they are, it updates them. If they are not, it keeps the old ones.

There has been a suggestion to install all default config files in `/usr/lib/netdata` and modify all the plugins to look first at `/etc/netdata` and if a config file is not found there for them, use `/usr/lib/netdata` to load the default. So, `/etc/netdata` will be mostly empty.

**Comment by paulfantom** [comment]
> There has been a suggestion to install all default config files in /usr/lib/netdata and modify all the plugins to look first at /etc/netdata and if a config file is not found there for them, use /usr/lib/netdata to load the default. So, /etc/netdata will be mostly empty.

That is a way to go. Essentially `/etc` was designed to be used in this way.

**Comment by ktsaou** [comment]
Yes I agree.

**Pull request merged**
