### PR TITLE
Integrations Documentation

### PR DESCRIPTION
**Pull request by netdatabot**
Generate Documentation from `integrations/integrations.js` based on the latest code.

This PR was auto-generated by
`.github/workflows/generate-integrations-docs.yml`.

### CODE REVIEW

**Comment by Ancairon** [comment]
This is a test PR and should not be merged as of now.

**Comment by Ancairon** [comment]
This is working. We need to close https://github.com/netdata/learn/issues/1784 as most READMEs get overriden to then be able to start merging this action's PRs

cc @sashwathn as a status update

**Comment by sashwathn** [comment]
@Ancairon : I will get to this today.

**Comment by Ancairon** [comment]
Result looks like the expected, we need to wrap preserving info from READMEs and then merge a PR like this one coming from the action. Then I will need to go to Learn and do the Learn part of merging PRs

**Pull request closed without merging**
