### PR TITLE
dashboard@2.7.4

### PR DESCRIPTION
**Pull request by jacekkolasa**
##### Summary
New Dashboard version:

- add new social media links section below right hand sidebar
- move "Privacy policy" & "Terms and conditions" links from sidebar to the bottom of the dashboard
- leave only "Copyright 2020, Netdata, Inc" in Copyright section in the bottom of the dashboard
- fixed hamburger icon for smaller screens
- fixed icons in white theme
- "Sign in to cloud" buttons text
- added spinners which are shown when api request takes more than 2 seconds
- moved legend below the charts
- respect after/before url params when printing (netdata/netdata#9009)
- update all header icons
- prevent expanding first family in "all" tab of alarms modal (netdata/netdata#8240)

##### Component Name
web/dashboard

### CODE REVIEW

**Review by novykh — APPROVED** [review]

**Comment by thiagoftsm** [comment]
@jacekkolasa when I am accessing the dashboard using `Firefox 78.4.0 ESR` and I move to the end of the page, I am not able to access again the `System Overview` options until I return to top again, because the new bar is hidden the option:

top

**Comment by ilyam8** [comment]
And the bar size is huge, i guess it is something not easy to fix? 🤔

**Comment by jacekkolasa** [comment]
@ilyam8 @thiagoftsm thanks for checking! We talked with @cakrit , @dim08 and @manos-saratsis and decided to not put that bar on dashboard for now. Instead, we'll spend some time to adapt Cloud's date-time-range-picker to Dashboard, and there won't be any additional bars anymore, it will be put probably on the existing top bar.

I'll update this pr with new version later

**Comment by thiagoftsm** [comment]
About the white theme, I observed that when I changed from `black` to it, the icons are fine, but when I decided to return from white to black, I observed that the text is almost not visible at settings:

white

**Comment by thiagoftsm** [comment]
After to change themes, independent of the direction (`white` to `black` or `black` to `white`), during few seconds I am seeing all alarms like this:

alarms

but, after few seconds it returns for the correct values.

**Comment by jacekkolasa** [comment]
> About the white theme, I observed that when I changed from `black` to it, the icons are fine, but when I decided to return from white to black, I observed that the text is almost not visible at settings:

I was wondering about it too, actually! But i didn't changed it because on my monitor it was readable, and that's how it was on old dashboard: http://frankfurt.my-netdata.io/old/#menu_system;theme=white;help=true.
But since it's an issue for you too, then i guess it won't hurt if we'll make it a little darker. Thanks @thiagoftsm!

**Comment by jacekkolasa** [comment]
@thiagoftsm @ilyam8 please check again, i've removed the time-frame-bar, and added few other changes from https://github.com/netdata/dashboard/pull/159. I'll edit the note on top

**Comment by thiagoftsm** [comment]
@jacekkolasa I executed some tests now and I liked the final result, but I have one concern. I observed that we are moving from the original position the chart legends, this is good, because the previous space was short for dimensions with big length, on the other hand, it is possible people would like to keep the legends at right. Is it possible to add a selector for the legend position?

**Comment by jacekkolasa** [comment]
@thiagoftsm i agree with you that it would be very helpful to have an option to toggle this, but the UI for the switch is not yet build yet, so we realised that having legend only on the bottom is an improvement and worth getting merged in this state. Hopefully we'll be able to add a setting for it before we'll make next stable release

**Review by thiagoftsm — DISMISSED** [review]
After to receive the [answer](https://github.com/netdata/netdata/pull/10122#issuecomment-716616601) for my concern, I am approving the PR.

**Review by VLegakis — DISMISSED** [review]

**Review by ilyam8 — APPROVED** [review]

**Comment by ilyam8** [comment]
I installed the branch, no problems for me.

One minor(?) thing:

See `<< |> >> + -` panel covers dimenstion name.

Screenshot 2020-10-27 at 16 08 49

**Review by VLegakis — APPROVED** [review]

**Comment by jacekkolasa** [comment]
> One minor(?) thing:
> 
> See `<< |> >> + -` panel covers dimension name.

Indeed, @ilyam8 , this can happen in one case. I'll make a fix for that now, thx!

**Review by VLegakis — APPROVED** [review]

**Comment by ilyam8** [comment]
https://github.com/netdata/netdata/pull/10122#issuecomment-717234645 is fixed in 2.7.4

**Review by ilyam8 — APPROVED** [review]

**Pull request merged**
