### PR TITLE
`ml - machine learning` to just `machine learning`

### PR DESCRIPTION
**Pull request by andrewm4894**
##### Summary

rename NETDATA_ML_CHART_FAMILY from `ml - machine learning` to just `machine learning`

this would look a little cleaner if was just "machine learning" and more in line with all the other chart families within "Netdata Monitoring"

image

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]

**Comment by ktsaou** [comment]
This will create a family in the dashboard called `[x]` when both old and new agents are there.
This is why I kept `ml` prefix. With this prefix, it creates a section called `ml[x]`.

**Comment by andrewm4894** [comment]
> This will create a family in the dashboard called `[x]` when both old and new agents are there. This is why I kept `ml` prefix. With this prefix, it creates a section called `ml[x]`.

i see got it will close and revisit at some much later time then.

**Comment by ilyam8** [comment]
I think that is not a big problem considering that is an internal metric.

**Comment by andrewm4894** [comment]
> I think that is not a big problem considering that is an internal metric.

true and agree...maybe worth doing now such that docs etc all cleaner if we do start directing people to these diagnostic charts for whatever reason as we work on the ml more.

**Comment by andrewm4894** [comment]
reopening for further discussion

**Comment by ktsaou** [comment]
I am ok to merge this

**Pull request merged**
