### PR TITLE
Replace ? with ✗ on distro support matrix

### PR DESCRIPTION
**Pull request by ncmans**
Question marks are used on tables in https://docs.netdata.cloud/packaging/distributions with no definite meaning.

Fixes https://github.com/netdata/netdata/issues/7432

### CODE REVIEW

**Comment by ncmans** [comment]
> This replaces all question marks with Xs. In certain columns, the question mark does make sense, it means that we haven't tested it yet. In CI: Smoke testing and CI: Testing it doesn't make sense, either we have it in there, or not.

@cakrit Where does it make sense?

**Comment by cakrit** [comment]
> @cakrit Where does it make sense?

Where we haven't tested the installation method. e.g. for RHEL 8.x, we haven't tested kickstart.sh (or apparently haven't tested much of anything), so we don't know if it works or not => We can't put a check or an X, as X means that it was tested and doesn't work.

**Comment by cosmix** [comment]
I think @cakrit has a point here, but I also find that the original description by @ncmans is valid:

> with no definite meaning.

is something we should improve. This does not mean replacing the question marks with ✗, but it does mean clarifying the semantics. A small legend perhaps?

**Comment by ncmans** [comment]
Closing as I don't have time ATM to look at this — please re-open if need to

**Pull request closed without merging**
