### PR TITLE
Add diagrams for internal data structures of netdata

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
Diagrams of the main internal data structures of `netdata` were added in `SVG` format. Sources are included in [draw.io](http://draw.io) format (`XML` files).

##### Component Name
Documentation

##### Additional Information
`SVG` files are quite big. Are we OK with them (related to #4439)?

### CODE REVIEW

**Comment by gmosx** [comment]
I don't think that SVG files are _that_ big. Maybe we should skip the .xml files? Or just add all the diagrams in a separate repo?

**Comment by ktsaou** [comment]
These are editable in draw.io?

Is it possible to post a few images of them to make review easier?

**Comment by vlvkobal** [comment]
> These are editable in draw.io?

XMLs in `src` directory are editable in `draw.io`

> Is it possible to post a few images of them to make review easier?

You can view SVGs from the PR's "File changed" tab, and they are scalable. Or do you want to have them right in the conversation?

**Comment by ktsaou** [comment]
ok. Merged! Thank you!

**Pull request merged**
