### PR TITLE
Reword calculator presentation in change-metrics-storage.md

### PR DESCRIPTION
**Pull request by DShreve2**
##### Additional Information
Seems like removing it would really hurt the presentation of tiering in general, but if we want to do that, just let me know @cakrit , @andrewm4894

### CODE REVIEW

**Review by andrewm4894 — APPROVED** [review]
i think make sense to leave up even a rough version while it gets fixed. kinda depends how "wrong" it actually is at the moment which i think @cakrit has a more clear idea on than me. If dangerously wrong then i guess makes sense to just remove for now. dont feel too strong either way

**Comment by cakrit** [comment]
It's stirage space and memory utilization. They are both very wrong

Storage space is underestimated, because the compressed max size setting doesn't account for the metadata files, but only concenrs the dbengine file.

Memory usage overestimated, because the version in the master branch that is getting released has very significant improvements.

You can add these two disclaimers on the UI of the calculatir.

So not sure what the value of a calculator is now, but add t

**Comment by DShreve2** [comment]
> So not sure what the value of a calculator is now, but add t

I think you hit Enter too early. @cakrit

**Comment by cakrit** [comment]
Oops, yes, my suggestion was to merge the PR, but also add these disclaimers about mem and disk that I wrote in the calculator's UI.

**Pull request closed without merging**
