### PR TITLE
update old log to new one

### PR DESCRIPTION
**Pull request by OdysLam**

### CODE REVIEW

**Comment by OdysLam** [comment]
With the kind help of @Yannis-San, I will also PR new icons for the alert (clear, warning, critical). ✌️

**Comment by OdysLam** [comment]
Okay, I just figured out that the alerts should be replaced in the netdata/dashboard repo. 

@jacekkolasa can you verify?

**Comment by jacekkolasa** [comment]
@OdysLam have you tested if this change works? I think this icon is used only by old agents, accessible with `/old` suffix, for example http://frankfurt.my-netdata.io/old

**Comment by OdysLam** [comment]
Actually, you are correct @jacekkolasa. Sorry for the fuss.

The notify-script wills source the icon from this link: https://registry.my-netdata.io/images/banner-icon-144x144.png

**Comment by jacekkolasa** [comment]
@OdysLam It's me who was actually confused :)
Now i understand we were talking about notifications. /old uses https://frankfurt.my-netdata.io/images/netdata-logomark.svg and notifications use https://frankfurt.my-netdata.io/static/img/netdata-logomark.svg (ie. that file which you changed).

I think we can actually merge your pr

**Review by jacekkolasa — APPROVED** [review]

**Comment by jacekkolasa** [comment]
Regarding your question about other icons - all of them are on this repo, because this is not related to dashboard. I'll make a research later and can help to point to exact icons

**Review by novykh — APPROVED** [review]

**Pull request merged**
