### PR TITLE
Improve guideline docs

### PR DESCRIPTION
**Pull request by Ancairon**
##### Summary

Related to: https://github.com/netdata/learn/issues/1469

This PR includes:

- Format `docs/guidelines.md`, break lines at ".".
- Add info from https://github.com/netdata/learn/blob/master/github_styling_reference.md into `docs/contributing/style-guide.md`
- Remove `/contribution-guidelines.md` as it contained duplicate information

### CODE REVIEW

**Review by cakrit — COMMENTED** [review]
I want to revisit the use of the Info/Tip/Warning . It's very difficult to work with them. We'll discuss today and see.

**Comment by Ancairon** [comment]
@cakrit a straightforward way to tackle this would be omitting the emojis, and making the text bold, on GitHub it renders like:

> **Note**
>
> a note

> **Warning**
> 
> a warning

But docusaurus just displays it with a bold text, no icons.

The current proposed way would need to recall the emoji name, and wrap it with semicolons

:bookmark_tabs: -> bookmark_tabs

:bulb: -> bulb

:warning: -> warning

If we keep the number of emojis we use to those three it is manageable IMO, what do you think?

**Review by cakrit — CHANGES_REQUESTED** [review]
As discussed, plz find another way for us to do info, warning etc.

**Comment by Ancairon** [comment]
@cakrit if we don't want to deal with signs, unicode stuff and emojis, we can only use text, so:

### Proposal 1
GitHub places icons for "Note" and "Warning", but Docusaurus doesn't support this way of doing it, so it will be without the icon and the color.

so:
```
> **Note**
> Note text
```
Which renders as

> **Note**
> Note text

And on Docusaurus it would be like:

image

### Proposal 2
(I think this is the best way of doing this out of the two)

After fiddling with the comment box of markdown I figured we can use hashtags inside it that control the wright of the font. Also it does not render it in the right sidebar, which is nice. It is uniform around both platforms as GitHub doesn't mess with this syntax

```
> ### Note
> This is a note
```

> ### Note
> This is a note

```
> ## Note
> This is a note
```

> ## Note
> This is a note


both of these render as such in Docusaurus:

image

This route also doesn't require anyone to place a newline after "Note" as the size of the font adds a bigger line separation margin.

(they are italics for some reason, but that doesn't matter)

**Comment by cakrit** [comment]
Ok, let's do proposal 2. It's definitely not as sexy as the other one, but the whole point was to be able to see the code that's behind the UI, on a browser and be able to copy/paste it. You can't do that with those - too smart for their own good - icons.

**Comment by ilyam8** [comment]
@Ancairon since you decided to use headings (`#`) for notes:

- Will they show up as (right) menu sections in learn?
- Why headings? Do you think that notes are so important that they should be much larger than the surrounding text?

**Comment by Ancairon** [comment]
> Will they show up as (right) menu sections in learn?

I have ran it locally, and it seems they don't render.

> Why headings? Do you think that notes are so important that they should be much larger than the surrounding text?

I think we just need to have a bit of emphasis on the block's text, other than bold.

If you got a better alternative, we are open to suggestions, headings felt that they were the most easy way of doing it, and the most consistent across Docusaurus and GitHub, if we do bold, GitHub renders it differently from Docusaurus.

**Review by cakrit — APPROVED** [review]

**Pull request merged**
