### PR TITLE
Add integration testing for the new replication code

### PR DESCRIPTION
**Pull request by amoss**
##### Summary
This PR adds high-level integration testing to the agent.
* Testing sits on top of docker, the test-driver defines collections of nodes.
* Nodes can have a mixture of static configuration parameters and parameters that are enumerated to walk over valid configurations.
* Scenarios are a series of high-level steps on the nodes (e.g. start, stop, disconnect network etc) and predicates to check for specific results (e.g. presence of steps in the timeline, appearance of data on the node API etc)
* Tester generates the `docker-compose` for each node with associated configuration files, runs the test-sequence and checks the results.

##### Component Name
streaming

##### Test Plan

* Take the copy of the agent with the replication code (https://github.com/netdata/netdata/pull/9832)
* Replace the `build_external` directory tree with the copy from this PR.
* Run the test driver (`python3 build_external/scenarios/gaps_hi/test_scenario.py`)

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- build_external/scenarios/gaps_hi/AgentTest/misc.py  3
- build_external/scenarios/gaps_hi/AgentTest/State.py  16
- build_external/scenarios/gaps_hi/test_scenario.py  18
- build_external/scenarios/gaps_hi/AgentTest/Node.py  20
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6135636&bid=20063144)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           

Complexity increasing per file
==============================
- build_external/scenarios/gaps_hi/AgentTest/State.py  16
- build_external/scenarios/gaps_hi/AgentTest/misc.py  3
- build_external/scenarios/gaps_hi/AgentTest/Node.py  20
- build_external/scenarios/gaps_hi/test_scenario.py  18
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6135636&bid=20063144)

**Comment by amoss** [comment]
The Codacy reports are wrong. The point of the lambda is to defer the call until later, and we don't have a common interface to the deferred calls so we need to wrap a closure in the code. I had a way to turn off the warning in a comment, will apply...

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- build_external/scenarios/gaps_hi/AgentTest/State.py  16
- build_external/scenarios/gaps_hi/AgentTest/Node.py  20
- build_external/scenarios/gaps_hi/test_scenario.py  18
- build_external/scenarios/gaps_hi/AgentTest/misc.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6135636&bid=20063144)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- build_external/scenarios/gaps_hi/AgentTest/Node.py  20
- build_external/scenarios/gaps_hi/AgentTest/misc.py  3
- build_external/scenarios/gaps_hi/AgentTest/State.py  16
- build_external/scenarios/gaps_hi/test_scenario.py  18
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6135636&bid=20063144)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- build_external/scenarios/gaps_hi/test_scenario.py  18
- build_external/scenarios/gaps_hi/AgentTest/State.py  16
- build_external/scenarios/gaps_hi/AgentTest/misc.py  3
- build_external/scenarios/gaps_hi/AgentTest/Node.py  20
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6135636&bid=20063144)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- build_external/scenarios/gaps_hi/AgentTest/Node.py  20
- build_external/scenarios/gaps_hi/test_scenario.py  18
- build_external/scenarios/gaps_hi/AgentTest/State.py  16
- build_external/scenarios/gaps_hi/AgentTest/misc.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6135636&bid=20063144)

**Review by prologic — APPROVED** [review]
LGTM

**Review by kaskavel — DISMISSED** [review]

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- build_external/scenarios/gaps_hi/test_scenario.py  18
- build_external/scenarios/gaps_hi/AgentTest/Node.py  20
- build_external/scenarios/gaps_hi/AgentTest/State.py  16
- build_external/scenarios/gaps_hi/AgentTest/misc.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6135636&bid=20063144)

**Review by prologic — APPROVED** [review]

**Review by kaskavel — APPROVED** [review]

**Comment by ilyam8** [comment]
Closing in favor of #13048

**Pull request closed without merging**
