### PR TITLE
Fix incorrect response format

### PR DESCRIPTION
**Pull request by jonapoul**
##### Summary

Made a change to the swagger YAML file so it now correctly describes the format of the response to the `api/v1/alarms` endpoint. The `alarms` parameter in this response actually returns a map/dictionary, with the keys determined by the chart/name parameters of the alarm - but the docs said that it returned a single sub-object named `chart-name.alarm-name`. If you run this through a code generator, or otherwise just read it literally, this is misleading.

##### Test Plan
N/A (as far as I'm aware?)

##### Additional Information
This was only an issue for me because I ran the YAML through [OpenAPI Generator](https://openapi-generator.tech/) and it gave me some erroneous model classes because of this issue.

| Before | After |
|--|--|
| firefox_oztcDiXDji | firefox_N9NP2xv3uP |

<details> <summary>For users: How does this change affect me?</summary>

More accurate docs!

### CODE REVIEW

**Review by thiagoftsm — COMMENTED** [review]
Thank you @jonapoul !

**Review by thiagoftsm — APPROVED** [review]

**Comment by ilyam8** [comment]
I think netdata-swagger.json should be updated too, right?

**Comment by ilyam8** [comment]
cc @netdata/agent  Not a problem of this PR, but related: if I open netdata-swagger.yaml using swaggerapi/swagger-ui

```bash
docker run -d -p 80:8080 -e URL=https://raw.githubusercontent.com/jonapoul/netdata/master/web/api/netdata-swagger.yaml swaggerapi/swagger-ui
```

I see the following error:

> {"messages":["attribute components.schemas.data_json2.items is missing"],"schemaValidationMessages":[]}

**Comment by jonapoul** [comment]
@ilyam8 Gotcha, didn't realise that was there! Just pushed a fix

**Pull request closed without merging**
