### PR TITLE
ilert Integration

### PR DESCRIPTION
**Pull request by DaTiMy**
##### Summary
This PR brings the integration between Netdata and ilert.

##### Test Plan
1. Create a Netdata alert source in ilert [documentation link](https://docs.ilert.com/inbound-integrations/netdata)
2. Following variables have to be set in health_alarm_notify.conf config file:
```
SEND_ILERT="YES"
ILERT_ALERT_SOURCE_URL="<alert source url of your netdata alert source in ilert>"
```

### CODE REVIEW

**Comment by ilyam8** [comment]
Hey, @DaTiMy. See [src/health/notificaions](https://github.com/netdata/netdata/tree/master/src/health/notifications): add a directory + metadata file (readme will be generated from the metadata file).

**Comment by DaTiMy** [comment]
@ilyam8 Thank you for your review. I've just added the directory and the metadata.

I will also include our logo:
ilert

**Comment by ilyam8** [comment]
@DaTiMy hey, can you [sign the CLA](https://github.com/netdata/netdata/pull/18447#issuecomment-2320812157)?

**Review by ilyam8 — APPROVED** [review]

**Comment by ilyam8** [comment]
@DaTiMy thanks, lgtm 👏 

@Ancairon, can you help add [logo](https://github.com/netdata/netdata/pull/18447#issuecomment-2321195599)?

**Pull request merged**
