### PR TITLE
dashboard v1.3.1

### PR DESCRIPTION
**Pull request by jacekkolasa**
##### Summary
Contains new Dashboard version - https://github.com/netdata/dashboard/releases/tag/v1.3.0

Fix dynamic dimension colors
https://github.com/netdata/dashboard/pull/109

Stacked chart with negative/positive values at the same time
https://github.com/netdata/dashboard/pull/110

Clicking the row in alarms log no longer redirects unnecessary through cloud/registry
https://github.com/netdata/dashboard/pull/111

Fix a case where a pending call to registry was delaying charts rendering
https://github.com/netdata/dashboard/pull/112

##### Component Name
Dashboard

### CODE REVIEW

**Review by prologic — APPROVED** [review]

**Comment by vlvkobal** [comment]
If I select dimensions in a stacked chart with negative/positive values, I can't see any data in the chart.

**Comment by jacekkolasa** [comment]
@vlvkobal thanks! There was a bug, i've pushed a patch release

**Review by vlvkobal — APPROVED** [review]
The first three issues are resolved. I haven't checked the last one (a pending call to registry was delaying charts rendering).

**Review by ilyam8 — APPROVED** [review]

**Comment by ilyam8** [comment]
@jacekkolasa good work 👍

**Pull request merged**
