### PR TITLE
web/gui: Added support for per series styling for dygraphs

### PR DESCRIPTION
**Pull request by dpsy4**
##### Summary
This change adds support for specifying custom styles for each series on a dygraph when creating a custom dashboard. The rationale for this change was to make different line series represented not only by different colors, but also different series types. With this change, a dygraph could support series types of `area`, `line` and `dot` on the same plot. 

The syntax proposed for this graph attribute was inspired by the syntax used by the `data-dimensions` attribute.

##### Component Name
web/gui

##### Test Plan
I tested this locally by setting up this custom graph:
```
<div
      data-netdata="system.ram"
      data-dygraph-type="area"
      data-dimensions="active|compressor|wired"
      data-dygraph-per-series-style="active:line|compressor:dot|wired:area"
      data-dygraph-pointsize="2"
      data-before="0"
      data-after="-300"
      data-points="300"
      data-height="225px"
    ></div>
```

Once the page was loaded with this graph, I tried the following:
- filtered the graph by clicking on the series name in the legend. Confirmed that the other series are removed and the styling is still applied correctly
- changed the `data-dygraph-pointsize` value to make sure that the value is getting applied to the series as well
- tried applying this to different `data-dygraph-type`'s like `area` and `stacked`. Confirmed that the styling is working as expected
- confirmed that leaving `data-dygraph-per-series-style` undefined does not impact any previous behavior.

### CODE REVIEW

**Comment by ilyam8** [comment]
@dpsy4 that sounds cool! Could you share a screenshot?

**Comment by dpsy4** [comment]
> @dpsy4 that sounds cool! Could you share a screenshot?

Sure, here is an image of it in action.

Screen Shot 2020-04-09 at 4 49 12 PM

**Comment by dpsy4** [comment]
Do I need to manually regenerate the `dashboard.js` file for this PR? I noticed that the checks for the `Dashboard` failed.

I'm also not sure how my changes impacted the Netlify checks. Should I have checked in something else with this PR?

**Comment by ilyam8** [comment]
@jacekkolasa take a look

**Comment by joelhans** [comment]
@dpsy4 The Netlify issues are not your fault, but rather a breakage that occurred last week with the documentation site.

If you're ambitious, you can try rebasing so that you have the file that fixes the Netlify builds. Otherwise we can have one of our admins merge this despite the failed checks once there's enough approvals.

**Comment by dpsy4** [comment]
> @dpsy4 The Netlify issues are not your fault, but rather a breakage that occurred last week with the documentation site.
> 
> If you're ambitious, you can try rebasing so that you have the file that fixes the Netlify builds. Otherwise we can have one of our admins merge this despite the failed checks once there's enough approvals.

Thanks, I just rebased my branch.

**Comment by dpsy4** [comment]
@ilyam8, what is netdata's stance on using ES6 syntax? I see some use of arrow functions and a mix of `var`, `let` and `const` in the code base. 

Is the goal for new code submissions to use the newer syntax?

**Comment by ilyam8** [comment]
> Is the goal for new code submissions to use the newer syntax?

I assume so, but i would say use same style as code around. @jacekkolasa knows better but he is on vacation.

**Comment by dejero-dave** [comment]
Bumping for visibility.

**Comment by dpsy4** [comment]
Bumping for visibility.

**Comment by ilyam8** [comment]
@jacekkolasa please take a look. At least we need to understand if we want/wantfix it @dim08

**Review by jacekkolasa — DISMISSED** [review]

**Comment by dpsy4** [comment]
Thanks @jacekkolasa.

I'm working on an app that is using netdata charts from the old `dashboard.js` library. Will the current `dashboard.js` be getting deprecated in the near future?

**Comment by jacekkolasa** [comment]
@dpsy4 no, not at all, dashboard.js will stay, with DOM parser, already documented configuration options, etc. Just internal logic will change. We need to build a separate bundler with webpack to build new dashboard.js bundle for the Agent. Also - there will be a way to add charts, as React Components

**Comment by dpsy4** [comment]
> Also - there will be a way to add charts, as React Components

That sounds pretty cool. Is there a timeline for when that would be available?

**Comment by dpsy4** [comment]
Is there anything else needed for this PR?

**Comment by dpsy4** [comment]
@jacekkolasa, should I close this PR and open a new one targeting https://github.com/netdata/dashboard?

**Comment by jacekkolasa** [comment]
Thanks @dpsy4! We can merge this change, as this is the only place we host partial .js files which are used to create dashboard.js. But unfortunately we'll need additional PR for dashboard repo to update https://github.com/netdata/dashboard/blob/master/public/dashboard.js file. If you can do it, that would be great. 

I know it's a little messy, we'll try to fix it when we'll have more time.

In Dashboard repo we also have a typescript/react version of dashboard which is right now used only for main Agent Dashboard and Cloud App. We plan to build dashboard.js file from it in the future, and when that time will come, we will need to rewrite your addition, which shouldn't be big problem.

**Review by jacekkolasa — APPROVED** [review]

**Comment by dpsy4** [comment]
> Thanks @dpsy4! We can merge this change, as this is the only place we host partial .js files which are used to create dashboard.js. But unfortunately we'll need additional PR for dashboard repo to update https://github.com/netdata/dashboard/blob/master/public/dashboard.js file. If you can do it, that would be great.
> 
> I know it's a little messy, we'll try to fix it when we'll have more time.
> 
> In Dashboard repo we also have a typescript/react version of dashboard which is right now used only for main Agent Dashboard and Cloud App. We plan to build dashboard.js file from it in the future, and when that time will come, we will need to rewrite your addition, which shouldn't be big problem.

Thanks @jacekkolasa. When submitting to https://github.com/netdata/dashboard, do I just need to check in the `dashboard.js` from this PR or would I need to add more that PR?

**Comment by jacekkolasa** [comment]
@dpsy4 i missed the notification again - you can just copy dashboard.js file which you build to netdata/dashboard repo

**Comment by dpsy4** [comment]
> @dpsy4 i missed the notification again - you can just copy dashboard.js file which you build to netdata/dashboard repo

Thanks @jacekkolasa. I'll wait until this gets merged before opening the second PR with the copy of dashboard.js from this one.

**Review by novykh — APPROVED** [review]

**Pull request merged**
