### PR TITLE
fix streaming bug

### LINKED ISSUE #4370: stream client connected to server but constantly failed to read
I found a very strange bug which only occurs on very few of my instances. 
Somehow client connected to server but wasn't able to send data, and the problem persist until I restart netdata service.

Here is the log on client side:
```
2018-10-09 09:26:16: netdata INFO  : STREAM_SENDER[************] : STREAM ************ [send to ***************]: connecting...
2018-10-09 09:26:16: netdata INFO  : STREAM_SENDER[************] : STREAM ************ [send to ***************]: initializing communication...
2018-10-09 09:26:16: netdata INFO  : STREAM_SENDER[************] : STREAM ************ [send to ***************]: waiting response from remote netdata...
2018-10-09 09:26:16: netdata INFO  : STREAM_SENDER[************] : STREAM ************ [send to ***************]: established communication - ready to send metrics...
2018-10-09 09:26:16: netdata ERROR : STREAM_SENDER[************] : STREAM ************ [send]: discarding 468704 bytes of metrics already in the buffer. (errno 22, Invalid argument)
2018-10-09 09:26:19: netdata INFO  : STATSD : STREAM ************ [send]: sending metrics...
2018-10-09 09:26:48: netdata ERROR : STREAM_SENDER[************] : STREAM ************ [send to ***************]: could not send metrics for 30 seconds - closing connection - we have sent 0 bytes on this connection.
2018-10-09 09:26:49: netdata ERROR : STATSD : STREAM ************ [send]: not ready - discarding collected metrics. (errno 22, Invalid argument)
2018-10-09 09:26:51: netdata Too many logs (201 logs in 862 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 338 seconds.
2018-10-09 09:32:35: netdata Resuming logging from process 'netdata' (prevented 78 logs in the last 1200 seconds).
2018-10-09 09:32:35: netdata ERROR : STREAM_SENDER[************] : STREAM ************ [send to ***************]: could not send metrics for 30 seconds - closing connection - we have sent 0 bytes on this connection.
2018-10-09 09:32:38: netdata INFO  : STREAM_SENDER[************] : STREAM ************ [send to ***************]: connecting...
2018-10-09 09:32:39: netdata INFO  : STREAM_SENDER[************] : STREAM ************ [send to ***************]: initializing communication...
2018-10-09 09:32:39: netdata INFO  : STREAM_SENDER[************] : STREAM ************ [send to ***************]: waiting response from remote netdata...
2018-10-09 09:32:39: netdata INFO  : STREAM_SENDER[************] : STREAM ************ [send to ***************]: established communication - ready to send metrics...
2018-10-09 09:32:39: netdata ERROR : STREAM_SENDER[************] : STREAM ************ [send]: discarding 468718 bytes of metrics already in the buffer. (errno 22, Invalid argument)
```

And the server side:
```
2018-10-09 09:30:35: 86449: 11 '[*****************]:38792' 'CONNECTED'
2018-10-09 09:30:35: 86449: 1622 '[*****************]:38792' 'STREAM' (sent/all = 0/0 bytes -0%, prep/sent/total = 1539077435884.23/1539077435884.38/0.14 ms) 200 'key=*******&hostname=*******************&registry_hostname=*******************&machine_guid=************&update_every=5&os=linux&timezone=UTC&tags=ip="**********"'
2018-10-09 09:30:35: STREAM: 1623 '[*****************]:38792' 'CONNECTED' host '*******************' api key '*******' machine guid '************'
2018-10-09 09:31:06: STREAM: 1623 '[*****************]:38792' 'DISCONNECTED' host '*******************' api key '*******' machine guid '************'
2018-10-09 09:31:31: 86449: 11 '[*****************]:38792' 'DISCONNECTED'
2018-10-09 09:34:32: 86471: 11 '[*****************]:41375' 'CONNECTED'
2018-10-09 09:34:32: 86471: 1650 '[*****************]:41375' 'STREAM' (sent/all = 0/0 bytes -0%, prep/sent/total = 1539077672866.19/1539077672866.34/0.15 ms) 200 'key=*******&hostname=*******************&registry_hostname=*******************&machine_guid=************&update_every=5&os=linux&timezone=UTC&tags=ip="**********"'
2018-10-09 09:34:32: STREAM: 1651 '[*****************]:41375' 'CONNECTED' host '*******************' api key '*******' machine guid '************'
2018-10-09 09:35:03: STREAM: 1651 '[*****************]:41375' 'DISCONNECTED' host '*******************' api key '*******' machine guid '************'
2018-10-09 09:35:31: 86471: 11 '[*****************]:41375' 'DISCONNECTED'
2018-10-09 09:36:51: 86483: 11 '[*****************]:42876' 'CONNECTED'
2018-10-09 09:36:51: netdata INFO  : WEB_CLIENT[86483,[*****************]:42876] : clients wants to STREAM metrics.
2018-10-09 09:36:51: 86483: 1677 '[*****************]:42876' 'STREAM' (sent/all = 0/0 bytes -0%, prep/sent/total = 1539077811510.16/1539077811510.40/0.24 ms) 200 'key=*******&hostname=*******************&registry_hostname=*******************&machine_guid=************&update_every=5&os=linux&timezone=UTC&tags=ip="**********"'
2018-10-09 09:36:51: netdata INFO  : STREAM_RECEIVER[*******************,[*****************]:42876] : thread created with task id 1678
2018-10-09 09:36:51: netdata INFO  : STREAM_RECEIVER[*******************,[*****************]:42876] : STREAM ******************* [*****************]:42876: receive thread created (task id 1678)
2018-10-09 09:36:51: netdata INFO  : STREAM_RECEIVER[*******************,[*****************]:42876] : STREAM ******************* [receive from [*****************]:42876]: initializing communication...
2018-10-09 09:36:51: netdata INFO  : STREAM_RECEIVER[*******************,[*****************]:42876] : STREAM ******************* [receive from [*****************]:42876]: receiving metrics...
2018-10-09 09:36:51: STREAM: 1678 '[*****************]:42876' 'CONNECTED' host '*******************' api key '*******' machine guid '************'
2018-10-09 09:37:23: STREAM: 1678 '[*****************]:42876' 'DISCONNECTED' host '*******************' api key '*******' machine guid '************'
2018-10-09 09:37:23: netdata ERROR : STREAM_RECEIVER[*******************,[*****************]:42876] : read failed
2018-10-09 09:37:23: netdata ERROR : STREAM_RECEIVER[*******************,[*****************]:42876] : STREAM ******************* [receive from [*****************]:42876]: disconnected (completed 0 updates).
2018-10-09 09:37:23: netdata INFO  : STREAM_RECEIVER[*******************,[*****************]:42876] : STREAM ******************* [receive from [*****************]:42876]: receive thread ended (task id 1678)
2018-10-09 09:37:23: netdata INFO  : STREAM_RECEIVER[*******************,[*****************]:42876] : thread with task id 1678 finished
```

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #4370 

There was a bug in the streaming functionality of the slaves:

If for any reason the connection from the slave to the master was interrupted, the slave was randomly unable to recover and push metrics to the master.

The reason was that a local variable was not reset to zero, when the slave discarded the buffer of data to be sent. In more detail:

The slave runs data collection in multiple threads. All these threads append data to a buffer. They lock it, append their data, they release the lock. So, the buffer is continuously increasing in size.

Another thread of the slave attempts to push the buffer to the remote netdata, as fast as the network can do it. So, the buffer is being streamed from the other end:

```
+ <<< The sending thread sends from here
|
++++++++++++++++++
|     BUFFER     |
++++++++++++++++++
                 |
                 + <<< Collection threads append here
```

The sending thread keeps a local variable tracking the next `begin` point.

(btw, if the network cannot push metrics at the rate they are collected, the buffer will become full and will be discarded).

On disconnects, we flush the buffer, so that the slave will start sending everything from the beginning. Since we don't know if the master server was restarted, the slave needs to send all the metadata about the metrics again.

The bug was that on disconnects, the `begin` variable was not reset. So it was random if the slave will recover, depending on the last value of the `begin` variable.

This PR fixes it.

### CODE REVIEW

**Comment by marcelmfs** [comment]
Which released version has this fix? I'm using 1.11 and I'm experiencing this issue.

**Comment by paulfantom** [comment]
At least v1.11.1

**Comment by marcelmfs** [comment]
Using 1.11.1-68-g0fad9bf5 and seeing a lot of disconnects

**Comment by paulfantom** [comment]
I don't know why this is happening. Could you create a bug report issue so we could properly track it? Also it would be good to try it with v1.12.1

**Comment by KyleFromOhio** [comment]
I was having a similar issue... 
**PROBLEM:** When cloning a box, you notice the netdata service starts dropping data like you have some sort of conflict going on.  
**SOLUTION:** Make sure your streaming machine uid (not the central master) is unique for all your streaming servers.  # uuidgen > /var/lib/netdata/registry/netdata.public.unique.id;

**Comment by cakrit** [comment]
Indeed @KyleFromOhio , see also https://docs.netdata.cloud/streaming/#netdata-unique-id

#5511 is also related, but there we only check for the master GUID vs the slave GUID.

**Pull request merged**
