### PR TITLE
New jitsi videobridge python plugin

### PR DESCRIPTION
**Pull request by ctrlaltdel**
##### Summary

A new netdata plugin for collecting metric from the Jitsi videobridge daemon.

It implements the metrics mentioned in https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md.

##### Component Name

jitsi python plugin

### CODE REVIEW

**Comment by ilyam8** [comment]
Hi @ctrlaltdel, thx for the contribution!

There are some things missing, like config file, makefile, etc., see https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#pull-request-checklist-for-python-plugins

**Comment by OdysLam** [comment]
Hey @ctrlaltdel ,

Thanks for the contribution and welcome to our community :) If you want to engage further with us, head over to our forum and join the discussion at https://community.netdata.cloud !

**Comment by ctrlaltdel** [comment]
> Hi @ctrlaltdel, thx for the contribution!
> 
> There are some things missing, like config file, makefile, etc., see https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#pull-request-checklist-for-python-plugins

Thanks for the feedback, I'll add these missing things in this PR.

**Comment by ctrlaltdel** [comment]
Hi @ilyam8,

> There are some things missing, like config file, makefile, etc., see https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin#pull-request-checklist-for-python-plugins

These missing files were added in the last commit, ready for review.

**Comment by ctrlaltdel** [comment]
Hi @ilyam8 @Ferroin @joelhans, this PR is ready for your review, thanks!

**Review by Ferroin — CHANGES_REQUESTED** [review]
This needs a README.md describing what data si collected and how to configure the plugin.

Other than that, LGTM.

**Pull request closed without merging**
