### PR TITLE
WIP: nvidia_smi_csv plugin

### PR DESCRIPTION
**Pull request by Kerleyark**
##### Summary

Created in collaboration with @mikerenfro
Creates a new plugin for pulling GPU metrics. It was noted that on our cluster nvidia_smi was using significant amounts of CPU while running. 

There was a suggestion on #10362 that using  `--query-gpu=... --format=csv` would reduce resource usage.
This plugin now collects fewer metrics and uses less resources.

Addresses #10362

##### Test Plan

We ran the plugin on our cluster and noted that:
 - The nvidia-smi executable uses little CPU and runs very quickly during data collection for this plugin
 - The results appear on our Netdata graphs
 - Acts as a drop-in replacement for the other nvidia_smi plugin

We haven't written any tests specific to this plugin, but if we need to and someone can point us at resources to make tests, we can do so. 

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
The script gives less metrics overall than the main nvidia_smi plugin. It is effectively an under-the-hood change that makes the plugin use less resources to run. Because it uses less resources, a user would be able to make use of more of the resources on a core with Netdata competing for less. This allows for user-facing work to run faster with less interference from Netdata. 
</details>

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @Kerleyark ,

Firstly thank you for your initial contribution. 
Please, sign our [CLA](https://github.com/netdata/netdata/pull/14099#issuecomment-1341161886) for us to have conditions to merge your PR.
A small suggestion, while your PR is `WIP`, please, click on `covert to draf`, and when it is ready, click in another link that will say `Ready for review`.

Best regards!

**Comment by ilyam8** [comment]
@Kerleyark hi. Big thanks for the PR, but we plan to deprecate the python version in favor of the [golang version](https://github.com/netdata/go.d.plugin/tree/master/modules/nvidia_smi). I've already implemented parsing XML output so only need to add CSV parsing.

> NVIDIA_SMI_COMMAND = 'nvidia-smi --query-gpu=name,temperature.gpu,power.draw,utilization.gpu,utilization.memory --format=csv'

It is a bit more complex than this. First, we need to check all the metrics exposed (using `--help-query-gpu` if I remember it correctly), parse and create the `--query-gpu` afterwards).

---

Thanks for the PR again, but it is wontfix.

**Comment by Kerleyark** [comment]
@andrewm4894 Feel free to take and merge this into the community repository. Also, make any modifications you would need to make for that to happen there. Message if you need any help with the code.

@ilyam8 Closing this pull request. Thanks and I am excited for the golang version of nvidia_smi collector!

**Comment by andrewm4894** [comment]
Sweet! Do you notice a difference in terms of overhead of the Nvidia cli?

**Comment by ilyam8** [comment]
The difference can be seen in https://github.com/netdata/netdata/issues/10362#issue-761138032. But I don't get that huge difference (388ms vs 7ms) on a GCP VM. Also, the XML format returns process information and you need a separate query (`--query-compute-apps` I think) when using the CSV format. That makes it 1 (XML) exec vs 2 execs (CSV).

**Pull request closed without merging**
