### PR TITLE
Send the cloud protocol used to posthog

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This PR adds a new posthog attribute called `host_aclk_protocol` and sends which cloud protocol the agent is using to connect to the cloud. It is not an indication of whether the agent is capable of a protocol, but rather which one it uses while connected. It will be evaluated for each META event.

The attribute `host_aclk_available` has also been moved to be evaluated at each META event, instead of just at the META_START event.

Possible values for `host_aclk_protocol` is null when the agent is not connected, `Legacy` when using the json (old) protocol, and `New` when using the protobuf (new) one. Values correspond to the same as running `netdatacli aclk-state`.

In a similar fashion, `aclk-available-protocol` is added to `/api/v1/info` to indicate the architecture that the agent has connected to the cloud with.

##### Component Name

Analytics

##### Test Plan

There are a few cases, all can be tested by compiling this PR, and running the agent with debug_flags `0x0000000080000000`. `debug.log` will then show what attributes and values it has picked up.

1) No cloud support (`--disable-cloud`), or not connected to the cloud. We should indicate `null` for `host_aclk_protocol` and `false` for `host_aclk_available`.
2) No protobuf support, claimed and connected to non-whitelisted space. We should indicate `Legacy` for `host_aclk_protocol` and `true` for `host_aclk_available`.
3) Protobuf support, claimed and connected to a non-whitelisted space. We should indicate `Legacy` for `host_aclk_protocol` and `true` for `host_aclk_available`.
4) Protobuf support, claimed and connected to a whitelisted space. We should indicate `New` for `host_aclk_protocol` and `true` for `host_aclk_available`.
5) No protobuf support, claimed and connected to whitelisted space. Should fall back to json protocol, so we should indicate `Legacy` for `host_aclk_protocol` and `true` for `host_aclk_available` if the agent 

| Cloud support  | Protobuf Support | Space connected | host_aclk_protocol | host_aclk_available |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| No  | No  | No | null | false
| Yes | No | Non-whitelisted | Legacy | true
| Yes | Yes | Non-whitelisted | Legacy | true
| Yes | Yes | Whitelisted | New | true
| Yes | No | Whitelisted | Legacy | true

### CODE REVIEW

**Review by thiagoftsm — DISMISSED** [review]

**Review by stelfrag — DISMISSED** [review]

**Comment by andrewm4894** [comment]
@MrZammler will this also be made available at /api/v1/info?

If not, I think maybe we might also want it available for the frontend pageviews etc too perhaps since is aclk related.

Once available in info I can make the pr to the dashboard repo to add it to frontend events too.

**Comment by MrZammler** [comment]
> @MrZammler will this also be made available at /api/v1/info?
> 
> If not, I think maybe we might also want it available for the frontend pageviews etc too perhaps since is aclk related.
> 
> Once available in info I can make the pr to the dashboard repo to add it to frontend events too.

Hey @andrewm4894 ! We have a similar thing, but not quite the same. We indicate in `info` if we have built support for new architecture (`aclk-ng-new-cloud-protocol true/false`) but it's not an indication that the agent has actually connected using the new architecture.

I'll add it as part of this PR, to be consistent. Sorry guys for the reviews, I should have added it in the first place.

**Comment by MrZammler** [comment]
Ok, it has been added to `/api/v1/info` as `aclk-available-protocol`. Same possible values.

Properties doc -> https://docs.google.com/document/d/1apOC6Dwbn9xvtdDwq6ifXnMcyzOU9iHaIPqNoyIKhJk
Sheet with list -> https://docs.google.com/spreadsheets/d/1vZVN7zC4MvA8qJLsncPCNt77vh6MPwU_GcncV3cMnW4

have been updated.

**Comment by underhood** [comment]
> @MrZammler will this also be made available at /api/v1/info?
> 
> If not, I think maybe we might also want it available for the frontend pageviews etc too perhaps since is aclk related.
> 
> Once available in info I can make the pr to the dashboard repo to add it to frontend events too.

we have the new `api/v1/aclk` for details about ACLK (not to polute info endpoint anymore), this is also accessible trough `netdatacli aclk-state`

**Comment by MrZammler** [comment]
> > @MrZammler will this also be made available at /api/v1/info?
> > If not, I think maybe we might also want it available for the frontend pageviews etc too perhaps since is aclk related.
> > Once available in info I can make the pr to the dashboard repo to add it to frontend events too.
> 
> we have the new `api/v1/aclk` for details about ACLK (not to polute info endpoint anymore), this is also accessible trough `netdatacli aclk-state`

Agree, yes. @andrewm4894 is it ok if dashboard would pick this value instead from `http://localhost:19999/api/v1/aclk`, attribute is `used-cloud-protocol`. If yes, I will remove from `/api/v1/info`.

**Comment by andrewm4894** [comment]
> > > @MrZammler will this also be made available at /api/v1/info?
> > > If not, I think maybe we might also want it available for the frontend pageviews etc too perhaps since is aclk related.
> > > Once available in info I can make the pr to the dashboard repo to add it to frontend events too.
> > 
> > 
> > we have the new `api/v1/aclk` for details about ACLK (not to polute info endpoint anymore), this is also accessible trough `netdatacli aclk-state`
> 
> Agree, yes. @andrewm4894 is it ok if dashboard would pick this value instead from `http://localhost:19999/api/v1/aclk`, attribute is `used-cloud-protocol`. If yes, I will remove from `/api/v1/info`.

Yep - fine by me. 

Would mean that if we wanted to add to frontend PH events we'd need to add another call here: https://github.com/netdata/dashboard/blob/master/src/domains/global/sagas.ts#L60

But i think that probably would be fine if we ended up wanting to do that. 

(will defer to @jacekkolasa on this one though :) )

**Comment by stelfrag** [comment]
@MrZammler please rebase

**Comment by stelfrag** [comment]
Before rebase the info shows

```
"cloud-enabled": true,
"cloud-available": true,
"aclk-ng-available": true,
"aclk-ng-new-cloud-protocol": true,
"aclk-legacy-available": true,
"aclk-implementation": "Next Generation",
"agent-claimed": true,
"aclk-available": true,
"aclk-available-protocol": "New",
```

After the rebase the info shows

```
"cloud-enabled": true,
"cloud-available": true,
"aclk-ng-available": false,
"aclk-ng-new-cloud-protocol": false,
"aclk-legacy-available": false,
"aclk-implementation": "Next Generation",
"agent-claimed": true,
"aclk-available": true,
"aclk-available-protocol": "New",
```

**Comment by MrZammler** [comment]
Hi!, Ok, @stelfrag rebased, I will do the changes to remove checks for legacy/New architecture aclk.

**Review by stelfrag — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
During my tests, I could replicate all values expected. LGTM!

**Comment by MrZammler** [comment]
Thank you guys!

**Comment by MrZammler** [comment]
We should eventually clean up `/api/v1/info` as @underhood suggested, and perhaps use another endpoint for the analytics attributes, and only leave there info stuff, and also to not duplicate information to more than one endpoint.

**Pull request merged**
