### PR TITLE
Update dashboard to version v2.20.17.

### PR DESCRIPTION
**Pull request by netdatabot**
See https://github.com/netdata/dashboard/releases/tag/v2.20.17 for changes.

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]

**Review by thiagoftsm — CHANGES_REQUESTED** [review]
I am waiting for this [comment](https://github.com/netdata/netdata/pull/12105#issuecomment-1034143599) to be addressed.

**Comment by underhood** [comment]
The date should be 1st March 2022
URL is coming ASAP

**Comment by underhood** [comment]
URL should be https://www.netdata.cloud/blog/netdata-clouds-new-architecture

**Comment by jacekkolasa** [comment]
This is replaced by https://github.com/netdata/netdata/pull/12117, all missing points had been added

**Pull request closed without merging**
