### PR TITLE
add support for monitoring thp, ballooning, zswap, ksm cow

### PR DESCRIPTION
**Pull request by ktsaou**
Modified the `vmstat` module of `proc` module to monitor:

- [x] transparent huge pages (THP, many charts, including allocations, compaction, splitting, swapout, etc)
- [x] memory ballooning (when Linux runs as guest VM on a host that supports memory ballooning) 
- [x] zswap operations
- [x] KSM copy-on-write operations (COW)

Especially the THP is very important since it seems enabled on most Linux distros by default.

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]
lgtm, but a small note:

Usually having "events/s" as units is a red flag because it means we are aggregating (chart level) _non-aggregatable_ metrics - grouping by host/system w/o selecting a dimension (the Cloud UI) will give useless values. E.g.

> **thp_swpout**
	is incremented every time a huge page is swapout in one
	piece without splitting.

> **thp_swpout_fallback**
	is incremented if a huge page has to be split before swapout.
	Usually because failed to allocate some continuous swap space
	for the huge page.

The sum of these events doesn't seem useful/correct to me.

**Comment by ktsaou** [comment]
> Usually having "events/s" as units is a red flag because it means we are aggregating (chart level) _non-aggregatable_ metrics - grouping by host/system w/o selecting a dimension (the Cloud UI) will give useless values

How do you suggest to do it?
I am not sure why they are useless when grouped. Why they are?

**Comment by ilyam8** [comment]
I propose to go with the current implementation, which is why I approved the PR. We do such aggregations pretty often. By "such aggregations" I mean correct when grouped by dimension, wrong when grouped by anything else without selecting a dimension (some obvious examples: system load average, system pressure).

cc @ralphm 

> Why they are?

I don't find them useful because the sum of:
 - huge page swapout events
 - huge page split events

doesn't seem to make sense to me, they look like 2 completely different metrics. But my understanding can be wrong because it is based only on metrics description, I am not a specialist.

**Review by ilyam8 — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]

**Comment by ktsaou** [comment]
@cakrit this needs to go into the release notes. The description is in the document I shared with you about hugepages.

**Pull request merged**
