### PR TITLE
Make sign-in functionality more visible

### PR DESCRIPTION
**Pull request by gmosx**
An info banner is introduced.

### CODE REVIEW

**Comment by ktsaou** [comment]
I installed this. I can see the "Sign In" button having dark background, but I can't see the banner. Are there any conditions for it to appear?

**Comment by gmosx** [comment]
> I installed this. I can see the "Sign In" button having dark background, but I can't see the banner. Are there any conditions for it to appear?

If you sso once it will not show it again.

Make sure you clear the `signInBannerClosed` variable in localStorage.

**Comment by gmosx** [comment]
> I see that a user closes it once, it will never appear again. If that was the intention, it works.

That's the intension. Obviously, we don't want to annoy the user, only inform him.

**Comment by gmosx** [comment]
@ktsaou, fix for 'white' theme:

image

**Pull request merged**
