### PR TITLE
Add Prometheus custom labels

### PR DESCRIPTION
**Pull request by gillg**
##### Summary
Add Prometheus custom labels support for all metrics
- Fix part of #6503

##### Component Name
Prometheus Backend

##### Description of testing that the developer performed
A new config field `host labels` in `backend` section is available for Prometheus backend.
You can put a list of statics labels (such as `host tags`). 
If it's defined, they will be append to each metric on `/api/v1/allmetrics?format=prometheus`

It's very usefull to automate installation of netdata and feedback host informations to prometheus

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- database/rrdhost.c  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5059529&bid=16652458)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- database/rrdhost.c  1
         

Clones removed
==============
+ database/rrd.h  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5059529&bid=16652458)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- database/rrdhost.c  1
         

Clones removed
==============
+ database/rrd.h  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5059529&bid=16652458)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- database/rrd.h  1
- database/rrdhost.c  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5059529&bid=16652458)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- database/rrd.h  1
- database/rrdhost.c  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5059529&bid=16652458)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- database/rrdhost.c  2
- database/rrd.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5059529&bid=16652458)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- database/rrd.h  1
- database/rrdhost.c  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5059529&bid=16652458)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- database/rrdhost.c  2
- database/rrd.h  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5059529&bid=16652458)

**Comment by ktsaou** [comment]
@ilyam8 @vlvkobal do we need this work merged? If yes, please update it and merge it. Otherwise, close it.

**Comment by vlvkobal** [comment]
I'm closing this because the PR is no longer applicable as far as the backends subsystem was removed from Netdata. We also have support for labels in the exporting engine.

**Pull request closed without merging**
