### PR TITLE
added whoisquery health templates

### PR DESCRIPTION
**Pull request by yasharne**
##### Summary
This template is for the netdata whoisquery plugin written in Go.
##### Component Name
health
##### Test Plan
A domain which expires in 365 days with `days_until_expiration_critical` of the default (30 days)
A domain which expires in 45 days with `days_until_expiration_critical` of 50 days

### CODE REVIEW

**Comment by ilyam8** [comment]
@yasharne 

add the alarm to the

https://github.com/netdata/netdata/blob/983a26d1a2c110b35db252b4b79c3f03eb4eeb4b/health/Makefile.am#L25-L107

**Comment by yasharne** [comment]
@ilyam8 Done

**Comment by ilyam8** [comment]
@yasharne you will need to do a rebase when we fix our ci, ill ping you

**Comment by ilyam8** [comment]
@yasharne rebase!

**Pull request merged**
