### PR TITLE
Cleanup docker packaging and contrib

### LINKED ISSUE #4608: Remove old packaging scripts
##### Feature idea summary

Since we have a new mechanism for releases, we should cleanup repository from dead code related to old release mechanism.

##### Expected behavior

Removed files related to old packaging without breaking new process.

### PR DESCRIPTION
**Pull request by paulfantom**
##### Summary

Remove some unused code and move `docker` to `packaging`. Also exclude `contrib` from build system.

Fixes #4608
Relates to #4611

##### Component Name

docker
build system

##### Additional Information

- remove stale packaging code which is not used anymore
- move `docker` to `packaging`
- exclude `contrib` from build system

```paste below

```

### CODE REVIEW

**Comment by cakrit** [comment]
Two questions: 
You're leaving the docker directory there just for the README? Do you want me to move it somewhere or are you going to do it in another PR?

packaging/README.md is incorrect now?

**Comment by paulfantom** [comment]
I moved docker README.md to packaging/docker/. As for `packaging/README.md` it describes a process which is not used anymore.

**Comment by paulfantom** [comment]
Fixed

**Comment by cakrit** [comment]
There are a few more complaints from checklinks.sh: 
-- ERROR: ./README.md - ./docker/README.md does not exist
-- ERROR: ./README.md - ./docker/README.md does not exist
-- ERROR: ./installer/README.md - ./installer/../docker/README.md does not exist
So you'll need to update the 2 relative links in README.md and the one in installer/README.md

I added a fix to buildhtml.sh to exit with code 1, in #4773, so that the netlify checks can fail accordingly.

**Comment by paulfantom** [comment]
There are no such links, they were fixed in previous commits.

**Pull request merged**
