### PR TITLE
Group Apple Filing Protocol daemons into a AFP group

### LINKED ISSUE #12075: [Bug]: Doesn't categorise the afpd process
### Bug description

My NAS uses [netatalk](https://en.wikipedia.org/wiki/Netatalk) to provide a [AFP](https://en.wikipedia.org/wiki/Apple_Filing_Protocol) server.  The process that does the actual I/O is `afpd` but this gets categorised as _other_ in the process charts.

### Expected behavior

`afpd` is categorised as _nfs_, or pulled out into its own category.

### Steps to reproduce

1. run netatalk
2.
3.
...

### Installation method

native binary packages (.deb/.rpm)

### System info

```shell
Debian 11
```

### Netdata build info

```shell
netdata 1.29.3
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by rossburton**
Group all of the AFP daemons into a single group.

Fixes #12075.

### CODE REVIEW

**Comment by rossburton** [comment]
Is there a CLA exception for _trivial_ changes?

**Comment by ilyam8** [comment]
@rossburton signed CLA is required to merge the PR. If you don't feel like signing it for some reason - we will have to close this PR and I will open a new one with your changes (if you don't mind).

**Comment by rossburton** [comment]
A CLA means talking to my employer… as it’s a trivial change if you’re
happy to recreate the PR then that would be great.

**Comment by ilyam8** [comment]
Closing in favor of #12078

Thanks, @rossburton!

**Pull request closed without merging**
