### PR TITLE
Switch e-mail threading to be enabled by default.

### PR DESCRIPTION
**Pull request by Ferroin**
As discussed in PR #3768, email threading will be the default behavior after release 1.11.  This PR includes that change, and is intended to be merged once 1.11 has been released.  I've created it here simply so it doesn't get forgotten (and to hopefully make things a bit simpler for @ktsaou).

### CODE REVIEW

**Comment by Ferroin** [comment]
Rebased to fix merge conflict and fix incomplete Travis CI check.

**Comment by Ferroin** [comment]
Do not merge this yet, it's going to get rebased again.

**Comment by Ferroin** [comment]
OK, correctly rebased now.  @ktsaou, ready for review.

**Comment by ktsaou** [comment]
thank you!

**Pull request merged**
