### PR TITLE
Reimplemented mypopen() function family

### LINKED ISSUE #6335: netdata does not send notifications for alarms which fail with (errno 12, Out of memory)
##### Bug report summary
I am running Netdata in a docker container. After several days of uninterrupted running I have noticed that at some time notifications are no longer send to my services. In the docker logs I see the following errors (the errors where cause by restarting another server which streams to this server):
```
netdata_1  | 2019-06-24 09:18:38: netdata ERROR : HEALTH : HEALTH: Cannot popen("exec /usr/libexec/netdata/plugins.d/alarm-notify.sh 'silent' 'XXXXXXXX' '1560932661' '1560931251' '8' '1561367918' 'lowest_entropy' 'system.entropy' 'entropy' 'WARNING' 'CLEAR' '35' '3228' '6@/usr/lib/netdata/conf.d/health.d/entropy.conf' '355200' '0' 'entries' 'minimum entries in the random numbers pool in the last 10 minutes' '35 entries' '3228 entries' '$this < (($status >= $WARNING) ? (200) : (100))' '[ $this = 35 ] [ $status = 1 ] [ $WARNING = 3 ] ' '2' '0'", "r"). (errno 12, Out of memory)
....
netdata_1  | 2019-06-24 09:18:40: STREAM: 2229 '[10.0.1.4]:51036' 'DISCONNECTED' host 'XXXXXXXX' api key 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' machine guid 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
netdata_1  | 2019-06-24 09:18:40: netdata ERROR : STREAM_RECEIVER[XXXXXXXX,[10.0.1.4]:51036] : read failed
netdata_1  | 2019-06-24 09:18:40: netdata ERROR : STREAM_RECEIVER[XXXXXXXX,[10.0.1.4]:51036] : STREAM XXXXXXXX [receive from [10.0.1.4]:51036]: disconnected (completed 1965197 updates). (errno 22, Invalid argument)
netdata_1  | 2019-06-24 09:18:40: netdata INFO  : STREAM_RECEIVER[XXXXXXXX,[10.0.1.4]:51036] : STREAM XXXXXXXX [receive from [10.0.1.4]:51036]: receive thread ended (task id 2229)
netdata_1  | 2019-06-24 09:18:40: netdata INFO  : STREAM_RECEIVER[XXXXXXXX,[10.0.1.4]:51036] : thread with task id 2229 finished
....
netdata_1  | 2019-06-24 09:18:53: netdata ERROR : HEALTH : HEALTH: Cannot popen("exec /usr/libexec/netdata/plugins.d/alarm-notify.sh 'sysadmin' 'XXXXXXXX' '1560932664' '1560931246' '6' '1561367933' 'ipv4_tcphandshake_last_collected_secs' 'ipv4.tcphandshake' 'tcp' 'WARNING' 'CLEAR' '15' '5' '6@/usr/lib/netdata/conf.d/health.d/tcp_resets.conf' '436215' '0' 'seconds ago' 'number of seconds since the last successful data collection' '00:00:15 ago' '00:00:05 ago' '$this > (($status >= $WARNING) ? ($update_every) : ( 5 * $update_every))' '[ $this = 15 ] [ $status = 1 ] [ $WARNING = 3 ] [ ${update_every} = 2 ] ' '5' '0'", "r"). (errno 12, Out of memory)
netdata_1  | 2019-06-24 09:18:53: netdata ERROR : HEALTH : HEALTH: Cannot popen("exec /usr/libexec/netdata/plugins.d/alarm-notify.sh 'sysadmin' 'XXXXXXXX' '1560932663' '1560931236' '6' '1561367933' 'ipv4_udperrors_last_collected_secs' 'ipv4.udperrors' 'udp' 'WARNING' 'CLEAR' '15' '5' '6@/usr/lib/netdata/conf.d/health.d/udp_errors.conf' '436215' '0' 'seconds ago' 'number of seconds since the last successful data collection' '00:00:15 ago' '00:00:05 ago' '$this > (($status >= $WARNING) ? ($update_every) : ( 5 * $update_every))' '[ $this = 15 ] [ $status = 1 ] [ $WARNING = 3 ] [ ${update_every} = 2 ] ' '5' '0'", "r"). (errno 12, Out of memory)
netdata_1  | 2019-06-24 09:18:53: netdata ERROR : HEALTH : HEALTH: Cannot popen("exec /usr/libexec/netdata/plugins.d/alarm-notify.sh 'sysadmin' 'XXXXXXXX' '1560932662' '1560931229' '6' '1561367933' 'netfilter_last_collected_secs' 'netfilter.conntrack_sockets' 'conntrack' 'WARNING' 'CLEAR' '15' '5' '4@/usr/lib/netdata/conf.d/health.d/netfilter.conf' '436215' '0' 'seconds ago' 'number of seconds since the last successful data collection' '00:00:15 ago' '00:00:05 ago' '$this > (($status >= $WARNING) ? ($update_every) : ( 5 * $update_every))' '[ $this = 15 ] [ $status = 1 ] [ $WARNING = 3 ] [ ${update_every} = 2 ] ' '5' '0'", "r"). (errno 12, Out of memory)
```
In the logs netdata states it is out of memory. In contrast to this netdata shows me that the server it is running on only uses 81% of 4gb of memory, and there are ~500 MiB available to the system (mem.available).

Restarting the docker container seems to solve the problem. Nevertheless it highly annoying that the notifications fail here. Additionally if you brows to the node which causes the unsent alarms, the notifications are displayed in the browser.

##### OS / Environment
Ubuntu, running netdata in docker-container pulled from https://hub.docker.com/r/netdata/netdata/

##### Netdata version (ouput of `netdata -V`)
v1.15.0-103-gc5ab8255

##### Component Name
idk

##### Steps To Reproduce
Run netdata for multiple days within docker and stream data to it.
Trigger an alarm.

##### Expected behavior
Do not fail sending error messages when there is still memory left. Or free memory elsewhere as alarm messages are very important to use netdata for monitoring servers.

### PR DESCRIPTION
**Pull request by mfundul**
Reimplemented mypopen() function family based on posix_spawn() instead of fork() and execl().

##### Summary
Fixes #6335
##### Component Name
daemon
##### Additional Information
Reimplemented `mypopen()` function family based on `posix_spawn()` instead of `fork()` and `execl()`.

The problem with `fork()` is that if the parent process has a large address space then the `fork()` may fail due to insufficient free memory in the system if memory overcommit is not enabled.

`posix_spawn()` does not call `fork()` and does not suffer from this problem. It is also more portable than `vfork()` which is deprecated and `clone()` which is linux only.

### CODE REVIEW

**Comment by mfundul** [comment]
I have to stop development for now, somebody will need to debug this, otherwise we wait until I can resume work on this.

**Comment by thiagoftsm** [comment]
I am beginning the debug now!

**Comment by mfundul** [comment]
@ktsaou what about `DETACH_PLUGINS_FROM_NETDATA`? This looks like dead code at this point, should we remove this functionality altogether? This definition is also used in `collectors/tc.plugin/plugin_tc.c`.

**Comment by mfundul** [comment]
This change needs to be tested in Mac OS as well.

**Comment by mfundul** [comment]
> 
> 
> Perhaps a stupid question, but I don't have time to check. Does the new implementation carry over the environment variables to pass them to the executed script? We need that.

The implementation uses a general purpose function that handles the environment regardless of whether you need to set it or not as shown below:
```
FILE *mypopen(const char *command, volatile pid_t *pidptr) { 
    return custom_popene(command, pidptr, environ); 
}

FILE *mypopene(const char *command, volatile pid_t *pidptr, char **env) { 
    return custom_popene(command, pidptr, env); 
} 
```
For the simple case `environ` is used that is inherited from the parent process as explained [here](https://linux.die.net/man/3/environ). We had already been using `execl()` for which the following is true:
_"For those forms not containing an envp pointer ( execl(), execv(), execlp(), and execvp()), the environment for the new process image shall be taken from the external variable environ in the calling process."_

**Comment by paulkatsoulakis** [comment]
On my macOS mojave 10.14.5, i executed with success all of the following with this branch:

10186  7/3/2019 14:57  autoreconf -ivf
10191  7/3/2019 15:00  ./netdata-installer.sh --install /tmp/netdata

Then netdata started successfully, no suspicious errors found and the dashboard loaded correctly.
I haven't checked any console errors from Developer Tools of Chrome though, but the error log was showing the various calls for data retrieval with no problems

**Pull request merged**
