### PR TITLE
! fix debian postinstall and postrm

### PR DESCRIPTION
**Pull request by voldemarpanso**
statoverride was not cleaned after uninstall and I don't understand the change: 64048c23a2f8dd207268af9bf55513784f722468

### CODE REVIEW

**Comment by ktsaou** [comment]
@voldemarpanso thanks!

@lhw @FedericoCeratto please review this.

**Comment by cakrit** [comment]
Kind reminder for @lwh and @FedericoCeratto .
@paulkatsoulakis any chance you can review and approve this instead?

**Comment by FedericoCeratto** [comment]
The official Debian packaging files are hosted at https://salsa.debian.org/debian/netdata/tree/master/debian

**Comment by FedericoCeratto** [comment]
See the dir overrides: https://salsa.debian.org/debian/netdata/blob/master/debian/netdata-core.postinst#L20

**Comment by cakrit** [comment]
So we're closing this one.

**Pull request closed without merging**
