### PR TITLE
RPM spec and patches for sles 11

### PR DESCRIPTION
**Pull request by veksh**
Spec and some patches and additions to build netdata RPM for SLES 11. This LTS distribution is rather old (python is 2.6.9), but is still supported and popular in enterprise. Everything is relatively easy to backport except maybe alarm notification script: without bash4 and associative arrays I've just managed to make mail notifications work. 

There is ongoing effort to maintain RPM spec for [sles12](https://build.opensuse.org/package/show/network/netdata), and SLES 11 is mostly legacy, so integrating those changes in main .spec.in seems to be a waste of effort.

### CODE REVIEW

**Comment by ktsaou** [comment]
hm... are you sure alarm-notify.sh will work in bash v3? It uses associative arrays that do not exist in bash v3.

**Comment by veksh** [comment]
> hm... are you sure alarm-notify.sh will work in bash v3? 

Yes, for some definition of "work" -- like "well it mostly works for me" :)
I've mentioned that in README -- only for mails and only for one destination; 
actually thats what I needed (mb just syslog would be even better).

> It uses associative arrays that do not exist in bash v3.

Yes, and it would be too hard to backport it in all the glory, with hipchat and stuff.
So basically it is just a quick hack for mail notification method to work.

I'll try to come with something less horrible in a day.

**Comment by veksh** [comment]
I've cleaned up bash3-compatible `alarm-notify-basic.bash3.sh` and added syslog notification method (in addition to email). For both, only one (default) destination is supported. Functionality is very basic but that is better than nothing :)

**Comment by paulfantom** [comment]
This looks good to me. It is in `contrib/` so it doesn't have any influence on main codebase and/or packaging and others could maintain it if they want. Exactly what contrib is for.

@ktsaou can we merge it? There is no need for CI to kick in.

**Comment by ktsaou** [comment]
ok, approved it.

**Pull request merged**
