### PR TITLE
Added ARM binary package builds to CI.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This adds ARMv7 and ARMv8 binary package builds to our CI for all the platforms we can support them on. These still need some testing, but are ready enough to be released as an open beta.

##### Component Name

area/packaging.

##### Test Plan

CI passes correctly (ensures that packages build and are successfully installable).

##### Additional Information

Fixes: #7824 (wow, I did not realize how old this issue was)
Relevant to: #7826, #10481

### CODE REVIEW

**Comment by Ferroin** [comment]
Closing and reopening to hopefully kick the CI into working properly.

**Comment by Ferroin** [comment]
Marking this ready for review as it is essentially ready. The yamllint complaints are just about long lines and can be ignored (I need to get around to getting a PR put together to just disable that check). The two package build failures for Ubuntu are due to caching problems in GitHub Actions itself (it’s using cached Docker images that are suffering from bitrot, causing `cmake` to be broken in both).

**Review by vkalintiris — DISMISSED** [review]

**Comment by Ferroin** [comment]
Rebased to pick up removal of Ubuntu 16.04 from CI.

**Comment by Ferroin** [comment]
Rebased to pick up CI improvements to simplify testing (check the ‘artifacts0 dropdown on the Packages CI check details pages).

**Comment by Ferroin** [comment]
@DShreve2 This one should ideally be a headline item for the release notes for the next release.

**Comment by odidev** [comment]
It's really nice to see [#11463](https://github.com/netdata/netdata/pull/11463) merged.
May i know when are you planning to release the binary package (netdata-v1.32.0.gz.run) for Arm64 platform and updating `kickstart-static64.sh` to support detecting the system architecture and using the correct binary is also the part of your next release plan?

**Comment by Ferroin** [comment]
> It's really nice to see [#11463](https://github.com/netdata/netdata/pull/11463) merged. May i know when are you planning to release the binary package (netdata-v1.32.0.gz.run) for Arm64 platform and updating `kickstart-static64.sh` to support detecting the system architecture and using the correct binary is also the part of your next release plan?

The per-arch `.gz.run` files will be published alongside the normal release of v1.32.0 (it was going to be at the end of last month but got delayed for a number of reasons, though it should be some time soon).

As far as support in the installer, the existing `kickstart-static64.sh` code is getting completely replaced in the near future by the code currently found in `packaging/installer/kickstart-ng.sh`, which unifies the install handling for native packages, static builds, and local builds (it will use whichever works on your system automatically. `kickstart-ng.sh` is curently in a tech preview state (essentially an open-beta), with the formal release (and replacement of both `kickstart.sh` and `kickstart-static64.sh`) tentatively planned for some time before the end of the year.

**Pull request merged**
