### PR TITLE
Overhaul of installation documentation

### PR DESCRIPTION
**Pull request by joelhans**
##### Summary

Trying this again...

I was tasked by @ktsaou and @cakrit to overhaul the way our documentation guides users through installation. We all agreed that because so many people visit and reference the installation documentation, it needs to be as professional and simple as possible.

The goals of this project:

- [x] Highlight one-line installer, binaries, and Docker as "best" installation methods for most users
- [x] Separate installation instructions into multiple files
- [x] General overhaul and cleanup of language and syntax on installation page(s)
- [x] Address the nightly vs. stable release pros/cons
- [x] Restore the copy button on code blocks

TODOs:

- [ ] Figure out if I need to add GA tags to the new pages (and how)
- [ ] Collect feedback from team

I'm leaving this as a WIP to collect feedback, as this is a pretty dramatic overhaul from the existing structure for installation docs.

I also want to give the update/uninstall pages a similar overhaul, but will likely tackle that in a separate PR unless everyone agrees it's better to do everything all at once.

##### Component Name

docs

##### Additional Information

This is the same as #6535, plus a few extra fixes I just found today.

### CODE REVIEW

**Comment by joelhans** [comment]
@paulkatsoulakis, when you have a minute, could you help me figure out why Travis gives me an error on the checksum of the `kickstart-static64.sh` binary?

**Comment by paulkatsoulakis** [comment]
> @paulkatsoulakis, when you have a minute, could you help me figure out why Travis gives me an error on the checksum of the `kickstart-static64.sh` binary?

in file `packaging/installer/README.md ` we expect to find the following lines, so that we validate the values are legitimate:

```
$ grep kickstart ./packaging/installer/README.md | grep md5sum
[ "8a2b054081a108dff915994ce77f2f2d" = "$(curl -Ss https://my-netdata.io/kickstart.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"
[ "8779d8717ccaa8dac18d599502eef591" = "$(curl -Ss https://my-netdata.io/kickstart-static64.sh | md5sum | cut -d ' ' -f 1)" ] && echo "OK, VALID" || echo "FAILED, INVALID"
```

We extract the md5 value with the following command:
```
README_MD5=$(grep "$file" $README_DOC | grep md5sum | cut -d '"' -f2)
```

So if those two lines are moved/changed we need to adjust `./tests/installer/checksums.sh` to look for the md5 values with a different way

**Comment by paulkatsoulakis** [comment]
hm the line is still there from what i see, i 'll pull the branch and examine it closer.
I 'll get back on this

**Comment by paulkatsoulakis** [comment]
Here's the patch to fix the above issue.

[0001-netdata-packaging-adopt-checksum-validator-to-the-ne.txt](https://github.com/netdata/netdata/files/3485799/0001-netdata-packaging-adopt-checksum-validator-to-the-ne.txt)

Please rename the file from `.txt` to `.patch` (GIT didn't allow me to upload .patch)

To apply the patch:
```
git am --3way 0001-netdata-packaging-adopt-checksum-validator-to-the-ne.patch
```

**Comment by joelhans** [comment]
Closing this to work on a more ambitious project around per-method/per-OS installation pages, with some kind of selector tool to help people choose the preferred method for their OS+version.

**Pull request closed without merging**
