### PR TITLE
Skip ML initialization when it's been disabled in netdata.conf

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

This PR applies again the changes introduced in https://github.com/netdata/netdata/pull/14810. This time we properly skip ML initialization when ML has been disabled in netdata.conf.

##### Test Plan

- CI jobs
- Disable ML in netdata.conf and make sure the agent starts successfully without crashing

### CODE REVIEW

**Comment by andrewm4894** [comment]
testing now

**Comment by andrewm4894** [comment]
@vkalintiris im seeing strange unexpected highly elevated anomaly rates for some reason 

image

also the dimensions names seem to be missing for some reason too which is a new issue:

image

[link](https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/overview#after=1681812794000&before=1681819994000&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&modal=alertDetailsModal&modalTab=&modalParams=chartId%3Danomaly_detection.anomaly_rate_on_dd6c1346-ddd5-11ed-a3c1-2d5627ea054b%2CalertId%3Danomaly_detection.anomaly_rate_on_dd6c1346-ddd5-11ed-a3c1-2d5627ea054b.anom_rate_node_5min%3A%3A%3Ac1893ab7-bd84-462c-a9f9-859f804dd942%2CalertName%3Danom_rate_node_5min%2CnodeId%3Dc1893ab7-bd84-462c-a9f9-859f804dd942&metrics_correlation=false&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-c1893ab7-bd84-462c-a9f9-859f804dd942-chartName=menu_anomaly_detection_submenu_anomaly_rate&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-overview-chartName=menu_anomaly_detection_submenu_dimensions&6045dc92-0a0c-48d8-960c-d2e0f31aa95d--selectedNodeIds=89cd873d-7faf-4aa4-a927-febde2983759%2C1373d4a8-3cda-4f19-bb47-405dc987abdb%2Cb1f8c771-a6d4-4df3-8b57-1fed45a3e47b%2C6bd72657-3cca-46eb-b18a-7e231c3fc2ba%2Cc1893ab7-bd84-462c-a9f9-859f804dd942%2C577fe886-cc51-477b-bc33-eac7a0982f08&highlight_after=1681814405000&highlight_before=1681816448000)

**Comment by andrewm4894** [comment]
seems like maybe data calls by node failing for some reason 
image

**Comment by andrewm4894** [comment]
issue seems to be that `dimension_names` seems to be "" strings for some reason 

image

**Comment by vkalintiris** [comment]
> im seeing strange unexpected highly elevated anomaly rates for some reason

Fixed in latest push. 

> issue seems to be that dimension_names seems to be "" strings for some reason

Don't think this is caused by this PR, but I'll try to check.

**Comment by andrewm4894** [comment]
seems like spikes around every 3 mins or something - not sure if means anything 

image

**Review by andrewm4894 — APPROVED** [review]
all looking good to me now

**Review by stelfrag — APPROVED** [review]

**Pull request merged**
