### PR TITLE
Fix collectors on MacOS and FreeBSD to ignore archived charts.

### LINKED ISSUE #9485: MacOS/Catalina memory, swap and net info graphs disappear - after reboot or netdata service restart
##### Bug report summary
MacOS/Catalina memory, swap and net info graphs disappear - after reboot or netdata service restart. It works all good after brand new installation but after reboot they are gone.

##### OS / Environment
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
ProductName:    Mac OS X
ProductVersion: 10.15.5
BuildVersion:   19F101

##### Netdata version

 v1.23.1

##### Component Name

I guess charts component.
##### Steps To Reproduce

1. Install > brew install netdata
2. Restart service > brew services restart netdata
or full system reboot

I have several times uninstalled and reinstalled netdata just to make sure. My uninstalls are complete removal as in rm -rf all netdata directories. It works after new installation but again after rebooting the service or full system they are gone.

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #9485
##### Component Name
collectors
##### Test Plan
Have users with macOS and FreeBSD verify the fix.

### CODE REVIEW

**Comment by stelfrag** [comment]
This looks OK, should it go to master or develop branch?

**Comment by mfundul** [comment]
This should go to master as it's a pretty critical bugfix. Ideally it would have made it into the release.

**Comment by amoss** [comment]
On MacOS `brew` can no longer `libjudy` so I don't have any way to test that this works.

**Comment by amoss** [comment]
I can't replicate the problem using the latest master on MacOS. Steps:
1. Install libjudy manually using defaults for their `./configure`
2. Install netdata and verifiy that dbengine is in use
3. Stop netdata using `kill -s SIGINT`
4. Restart netdata

All of the charts are still there.

**Pull request merged**
