### PR TITLE
Update dashboard to version v2.21.9.

### PR DESCRIPTION
**Pull request by netdatabot**
In this release the following updates are included:
* Update color of NetData's logo on left sidebar
* Update **Community** section buttons and the links for opening a new issue on GitHub in **Need Help?** modal

See https://github.com/netdata/dashboard/releases/tag/v2.21.9 for changes.

### CODE REVIEW

**Comment by ilyam8** [comment]
@burbuli8ra 

I think 
"Open a new issue in github" (https://github.com/netdata/netdata/issues/new?labels=bug%2C+needs+triage&template=bug_report.md)

should be


"Open a new issue on GitHub" (https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2Cneeds+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+)

**Comment by odynik** [comment]
Hi @burbuli8ra,
Few review comments from my side.

Button text: `Read more about netdata's community`
Suggested: `Read more about our community` or `Read more about the community` - This way will fit also in the button borders.
I clicked the buttons below and I was directed to a forum page that "[didn't exist or was private](https://community.netdata.cloud/c/support/agent-support/14)". 
Note: I am logged-in in the forum page.

Screenshots for your convenience.
image

**Comment by burbuli8ra** [comment]
@odynik thank you for your review, but the **Community** section has been updated and includes only a single button now with the label "Join the Community" and it links to https://www.netdata.cloud/community/.

**Comment by odynik** [comment]
> @odynik thank you for your review, but the **Community** section has been updated and includes only a single button now with the label "Join the Community", which links to https://www.netdata.cloud/community/.

Hi @burbuli8ra. You are right. Ignore my previous comments.
Probably I had compiled another PR or never clear the browser cache.

**Comment by burbuli8ra** [comment]
@ilyam8 the requested change is included on [v2.21.10](https://github.com/netdata/netdata/pull/12599)

**Pull request closed without merging**
