### PR TITLE
ACLK  cmake fixes

### LINKED ISSUE #8271: CMake build is broken
##### Bug report summary
When Netdata is built using CMake the process terminates with the following error
```
[ 74%] Building C object CMakeFiles/netdata.dir/aclk/mqtt.c.o
In file included from /home/vlad/netdata/aclk/mqtt.c:6:
/home/vlad/netdata/aclk/aclk_lws_wss_client.h:4:10: fatal error: libwebsockets.h: No such file or directory
    4 | #include <libwebsockets.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/netdata.dir/build.make:1189: CMakeFiles/netdata.dir/aclk/mqtt.c.o] Error 1
make[2]: Leaving directory '/home/vlad/netdata/cmake-build-debug'
make[1]: *** [CMakeFiles/Makefile2:942: CMakeFiles/netdata.dir/all] Error 2
make[1]: Leaving directory '/home/vlad/netdata/cmake-build-debug'
make: *** [Makefile:95: all] Error 2

```

##### OS / Environment
Arch Linux

##### Netdata version
commit e72044548fb241f41104f834edaa73192c1fef34

##### Component Name
packaging, ACLK

##### Steps To Reproduce
Build Netdata using CMake

##### Expected behavior
CMake should build Netdata

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Fixes #8271. If you change env var ACLK state you must run `autotools` before running `cmake` to regenerate `confg.h` properly (as cmake doesn't do that now)

##### Component Name
agent/cmake

##### Description of testing that the developer performed
Test with ACLK disabled and enabled

### CODE REVIEW

**Comment by vlvkobal** [comment]
When I run
```
sudo ACLK="yes" CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-go --disable-lto --dont-wait --dont-start-it
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE="Debug" -DUNIT_TESTING=ON ..
make
```
I get linker errors
```
[ 98%] Linking CXX executable netdata
/usr/bin/ld: CMakeFiles/netdata.dir/daemon/main.c.o:(.data.rel+0x238): undefined reference to `aclk_main'
/usr/bin/ld: CMakeFiles/netdata.dir/health/health.c.o: in function `health_reload':
/home/vlad/test/netdata/health/health.c:183: undefined reference to `aclk_single_update_disable'
/usr/bin/ld: /home/vlad/test/netdata/health/health.c:193: undefined reference to `aclk_single_update_enable'
/usr/bin/ld: /home/vlad/test/netdata/health/health.c:194: undefined reference to `aclk_alarm_reload'
/usr/bin/ld: CMakeFiles/netdata.dir/health/health_log.c.o: in function `health_alarm_log_save':
/home/vlad/test/netdata/health/health_log.c:156: undefined reference to `aclk_update_alarm'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrdcalc_link_to_rrddim':
/home/vlad/test/netdata/database/rrddim.c:187: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrddim_add_custom':
/home/vlad/test/netdata/database/rrddim.c:431: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrddim_free':
/home/vlad/test/netdata/database/rrddim.c:487: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrddim_hide':
/home/vlad/test/netdata/database/rrddim.c:508: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o: in function `rrddim_unhide':
/home/vlad/test/netdata/database/rrddim.c:525: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrddim.c.o:/home/vlad/test/netdata/database/rrddim.c:536: more undefined references to `aclk_update_chart' follow
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrdset.c.o: in function `rrdset_delete':
/home/vlad/test/netdata/database/rrdset.c:428: undefined reference to `aclk_del_collector'
/usr/bin/ld: /home/vlad/test/netdata/database/rrdset.c:429: undefined reference to `aclk_update_chart'
/usr/bin/ld: CMakeFiles/netdata.dir/database/rrdset.c.o: in function `rrdset_create_custom':
/home/vlad/test/netdata/database/rrdset.c:769: undefined reference to `aclk_add_collector'
/usr/bin/ld: /home/vlad/test/netdata/database/rrdset.c:770: undefined reference to `aclk_update_chart'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/netdata.dir/build.make:2108: netdata] Error 1
make[2]: Leaving directory '/home/vlad/test/netdata/cmake-build-debug'
make[1]: *** [CMakeFiles/Makefile2:942: CMakeFiles/netdata.dir/all] Error 2
make[1]: Leaving directory '/home/vlad/test/netdata/cmake-build-debug'
make: *** [Makefile:95: all] Error 2
```

**Comment by vlvkobal** [comment]
With ACLK disabled it works well.

**Comment by underhood** [comment]
```
sudo ACLK="yes" CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-go --disable-lto --dont-wait --dont-start-it
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE="Debug" -DUNIT_TESTING=ON ..
make
```

If you do that cmake will think ACLK is off -> if installer and cmake think ACLK has different value it will not work!

**Comment by vlvkobal** [comment]
Thank you for the explanation. I've made a test in the way you described - it works. I'm approving the PR.

**Comment by Ferroin** [comment]
This will require a rebase or merge of the most recent master branch to trigger Travis checks to run.

**Comment by underhood** [comment]
rebased on latest based on @Ferroin request. No other changes

**Comment by amoss** [comment]
I see errors that I do not understand (the CMakeLists.txt looks valid to me) :
```
export ACLK="yes"; CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-go --disable-lto --dont-wait --install /home/amoss/netdata/dev-install3
# Installer works fine, verified that the aclk is built and that the correct header is used.
mkdir build2 ; cd build2
ACLK="yes" cmake -DCMAKE_BUILD_TYPE="Debug" -DUNIT_TESTING=ON ..

... [ Trimmed output ] ....

-- agent-cloud-link: enabled
CMake Error at CMakeLists.txt:798 (IF):
  if given arguments:

    "LINUX" "AND"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!

```

**Comment by vlvkobal** [comment]
Rebuilt it from scratch. No errors. Just warnings I already reported about.

**Comment by amoss** [comment]
You are both testing on a system with libcap installed and my debian box does not have it. CMake is weird, and it does weird things. The expansion of CAP_FOUND is empty so:
```
IF( LINUX AND ${CAP_FOUND} )
```
gets substituted directly to the output shown:
```
IF( True AND)
```
which is, of course, a syntax error :)

The standard advice is "don't do that". Use something like this instead:
```
IF(${LINUX} AND "${CAP_FOUND}" MATCHES "Yes")
```
I can't see where `CAP_FOUND` is set so the appropriate value might be something else.

**Comment by underhood** [comment]
Thanks, good catch, the var is coming from `pkg_check_modules` didn't know it will stay empty in this case.

**Comment by underhood** [comment]
With latest commit it works for me on debian with and without `-lcap` (dont forget to run installer to rebuild libwebsockets with and without libcap if you install/uninstall that lib)

**Pull request merged**
