### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by thoggs**
Hello,
I would like to participate in the project, and for this reason I took the liberty of including myself in the list of contributors

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hi @thoggs ,

Thank you for your contribution! 
Please, sign our CLA for the reviewers have condition to merge your work.

**Comment by thoggs** [comment]
> Hi @thoggs ,
> 
> Thank you for your contribution!
> Please, sign our CLA for the reviewers have condition to merge your work.

hi, @thiagoftsm, yes, i already did it!

**Comment by thoggs** [comment]
> As I've seen multiple PRs from you already. Approved.

I haven't really done a lot of PRs yet, but I like the project and I would like to help, but if I have any problems, with all due respect, I remove my name.

**Comment by ilyam8** [comment]
Is [`CONTRIBUTORS.md`](https://github.com/netdata/netdata/blob/master/CONTRIBUTORS.md) a thing?

We dont use it anymore, i think it shouldnt be updated

> Since Sep 17th 2018, we use cla-assistant.io/netdata/netdata for signing the CLA, on all pull requests. Old contributors can sign the CLA at any time using this link.

**Comment by prologic** [comment]
After having read [CONTRIBUTORS.md](/CONTRIBUTORS.md) I agree with @ilyam8 -- We don't need to update this file anymore. Just singing the CLA is enough.

**Pull request closed without merging**
