### PR TITLE
Alerta.io notification improvements

### PR DESCRIPTION
**Pull request by satterly**
Enhance support of Alerta notifications  …
 * use 'indeterminate' severity as catch-all
 * move $family to "resource"
 * set "service" to 'Netdata' not $host
 * set "group" to "Performance'
 * set "value" to $value_sting not $alarm
 * add $alarm_id as a "tag"
 * add $roles, $name, $chart, $familty and $src as "attributes"
 * don't set auth header unless $ALERTA_API_KEY is set
 * log suppressed alerts (202 Accepted) as info not error
 * use $chart as resource for httpcheck alarms

Update and simplify the wiki page for alerta.

/cc @kattunga

### CODE REVIEW

**Comment by Ferroin** [comment]
@ktsaou I'll try to get it tested at some point later today.  From a quick look over the [Alerta.io documentation](http://docs.alerta.io/en/latest/) though, the changes appear to be correct as far as I can tell.

**Comment by ktsaou** [comment]
@Ferroin 	thank you!

**Comment by Ferroin** [comment]
OK, finally got this tested.  It appears here to be working as advertised.

**Comment by ktsaou** [comment]
merged!
thank you @satterly 	for implementing this and @Ferroin 	for verifying it!

**Pull request merged**
