### PR TITLE
install go.d.plugin only if there is new version

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

Fixes: #7799

##### Component Name

netdata-installer

##### Additional Information

Tests:

download latest if:

- [x] no go.d.plugin
- [x] go.d.plugin actual version is less then latest
- [x] error during checking/parsing versions

skip downloading if:
- [x] NETDATA_DISABLE_GO param is set
- [x] go.d.plugin actual version is equal to the latest
- [x] go.d.plugin actual version is greater then the latest

### CODE REVIEW

**Comment by ilyam8** [comment]
@Ferroin i assume it is not enough to fix it in the `netdata-installer.sh`, i see `install_go` function exists in the 4 different files:

> https://github.com/netdata/netdata/search?q=install_go&unscoped_q=install_go

Could you help me?

The fix seems to be working, at least for installer (which i use prettry often)

**Comment by ilyam8** [comment]
i understand that i need to copy paste the fix to the
- [/contrib/debian/install_go.sh](https://github.com/netdata/netdata/blob/cf6e42273c64fdfdf7a11254d9983b3cff87849c/contrib/debian/install_go.sh)
- [netdata.spec.in](https://github.com/netdata/netdata/blob/1477784048319e84127e466add6eb4a092c235e1/netdata.spec.in)

but i dont know how to test the changes there

**Comment by ilyam8** [comment]
@Ferroin if those 2 files are used for building i guess i dont need to modify them, if so the PR is ready

**Comment by Ferroin** [comment]
> @Ferroin if those 2 files are used for building i guess i dont need to modify them, if so the PR is ready

You're correct, the spec file and stuff under `contrib/debian/` are only used for package builds.

**Pull request merged**
