### PR TITLE
Fix error > emerge openssl-devel

### LINKED ISSUE #9140: Fail installation in Gentoo Linux
##### Bug report summary
When executing the installation with `bash <(curl -Ss https://my-netdata.io/kickstart.sh)` the following error occurs:
```
emerge: there are no ebuilds to satisfy "openssl-devel".
```
A `emerge --sycn` was run just before starting the installation.

##### OS / Environment
```
Linux cuernavilla 5.4.28-gentoo-x86_64 #2 SMP Tue Mar 31 11:01:04 CEST 2020 x86_64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz GenuineIntel GNU/Linux
/etc/gentoo-release:Gentoo Base System release 2.6
/etc/lsb-release:DISTRIB_ID="Gentoo"
/etc/os-release:NAME=Gentoo
/etc/os-release:ID=gentoo
/etc/os-release:PRETTY_NAME="Gentoo/Linux"
/etc/os-release:ANSI_COLOR="1;32"
/etc/os-release:HOME_URL="https://www.gentoo.org/"
/etc/os-release:SUPPORT_URL="https://www.gentoo.org/support/"
/etc/os-release:BUG_REPORT_URL="https://bugs.gentoo.org/"

```

##### Netdata version
Not installed.
 

##### Steps To Reproduce
1. Run: `bash <(curl -Ss https://my-netdata.io/kickstart.sh)`

##### Dump Process
```
#  bash <(curl -Ss https://my-netdata.io/kickstart.sh)
System            : Linux
Operating System  : GNU/Linux
Machine           : x86_64
BASH major version:
 --- Fetching script to detect required packages... ---
[/tmp/netdata-kickstart-RbtXtd]# curl -sSL --connect-timeout 10 --retry 3 https://raw.githubusercontent.com/netdata/netdata/master/packaging/installer/install-required-packages.sh  OK

 --- Running downloaded script to detect required packages... ---
[/tmp/netdata-kickstart-RbtXtd]# /bin/bash /tmp/netdata-kickstart-RbtXtd/install-required-packages.sh netdata Loading /etc/os-release ...

/etc/os-release information:
NAME            : Gentoo
VERSION         :
ID              : gentoo
ID_LIKE         :
VERSION_ID      :

We detected these:
Distribution    : gentoo
Version         :
Codename        :
Package Manager : install_emerge
Packages Tree   : gentoo
Detection Method: /etc/os-release
Default Python v: 3

Searching for distro_sdk ...
Searching for autoconf_archive ...
Searching for libz_dev ...
Searching for libuuid_dev ...
Searching for libmnl_dev ...
Searching for json_c_dev ...
Searching for libuv ...
Searching for lz4 ...
Searching for openssl ...
Searching for judy ...
Searching for python3_pymongo ...

The following command will be run:

 >> IMPORTANT <<
    Please make sure your system is up to date
    by running:   emerge --sync  or   eix-sync

emerge --ask -v --noreplace app-arch/lz4 dev-libs/json-c dev-libs/judy dev-libs/libuv dev-python/pymongo net-libs/libmnl openssl-devel sys-apps/util-linux sys-devel/autoconf-archive sys-libs/zlib


Press ENTER to run it >
emerge --ask -v --noreplace app-arch/lz4 dev-libs/json-c dev-libs/judy dev-libs/libuv dev-python/pymongo net-libs/libmnl openssl-devel sys-apps/util-linux sys-devel/autoconf-archive sys-libs/zlib

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "openssl-devel".

emerge: searching for similar names...
emerge: Maybe you meant any of these: dev-libs/openssl, dev-ruby/openssl-ccm, net-fs/openafs-kernel?



We are very sorry!

Installation of required packages failed.

What to do now:

  1. Make sure your system is updated.
     Most of the times, updating your system will resolve the issue.

  2. If the error message is about a specific package, try removing
     that package from the command and run it again.
     Depending on the broken package, you may be able to continue.

  3. Let us know. We may be able to help.
     Open a github issue with the above log, at:

           https://github.com/firehol/netdata/issues


 FAILED

 WARNING  It failed to install all the required packages, but installation might still be possible.

Press ENTER to attempt netdata installation >
```

### PR DESCRIPTION
**Pull request by vsc55**
##### Summary

Add the correct package name for gentoo linux.

- Fixes #9140

##### Component Name
Installer

##### Test Plan
```
 # emerge -s dev-libs/openssl
[ Results for search key : dev-libs/openssl ]
Searching...

*  dev-libs/openssl
      Latest version available: 1.1.1g
      Latest version installed: 1.1.1g
      Size of files: 9.572 KiB
      Homepage:      https://www.openssl.org/
      Description:   full-strength general purpose cryptography library (including SSL and TLS)
      License:       openssl
```

### CODE REVIEW

**Comment by prologic** [comment]
@Ferroin Please review

**Comment by vsc55** [comment]
> 
> 
> LGTM. Are you able to also make changes to `.github/workflows/build-and-install.yml` to include support for Gentoo in our CI using one of [these images](https://hub.docker.com/search?q=gentoo&type=image)? That would be awesome if you are familiar enough with Gentoo to do this.

I'm going to look at it to see what we can do.

**Comment by vsc55** [comment]
Hi,
I've updated `.github/workflows/build-and-install.yml` to support the gentoo image.
As soon as you finish doing the LGTM test you will be ready.

Do I add it to this pull or do I create a new pull?

https://github.com/vsc55/netdata/tree/workflows-gentoo

**Comment by prologic** [comment]
@vsc55 Adding it here in this PR is fine. Thank you!

**Comment by vsc55** [comment]
I'm happy to help

**Pull request merged**
