### PR TITLE
Use LVM UUIDs in chart ids for logical volumes

### LINKED ISSUE #9554: Incorrect display of LVM volume names in dashboard sidebar
##### Bug report summary
After creating/removing volumes in LVM netdata shows previous (deleted) names instead of actual ones, while in chart itself it is correct.

I could not reproduce it with regular volumes so I believe this is LVM-bound (though I maybe wrong).

##### OS / Environment
```
Linux xub 5.4.0-40-generic #44~18.04.1-Ubuntu SMP
Ubuntu 18.04 fully updated, running in KVM
```

##### Netdata version
`v1.23.1-93-g8677f158` (stable) and `v1.23.1-100-gf4826b08` (latest nightly)

Plugins disabled, dead simple config, as usual:
```
[global]
        history = 90000
        memory mode = dbengine
        timezone = CET
        dbengine disk space = 1024
        page cache size = 256

[plugins]
        enable running new plugins = no
```

##### Steps To Reproduce
Create test LVM group & volumes (substitute /dev/sdX to your test disk):
```bash
# All commands are executed succesfully unless noted otherwise
pvcreate /dev/sdX
vgcreate vg /dev/sdX
# thin pool
lvcreate -L 1G -T vg/thin
lvcreate -V 1G -n t1 lvg/thin
lvcreate -V 1G -n t1 vg/thin
# regular volume
lvcreate -n lv1 -L 1G vg
```

After refreshing UI netdata shows on sidebar (under "Disks") all created volumes:
image

Now get rid of them:
```bash
lvremove -y vg/lv1
lvremove -y vg/t1
lvremove -y vg/thin
```

After refresh netdata shows no LVM volumes anymore, as expected, so we create one again:
```bash
lvcreate -n v1 -L 1G vg
```
and re-check what we actually have:
```
# lvs -a

  LV      VG Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  v1      vg owi-a-s--- 1,00g                                                    

# lsblk -i

NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0  100G  0 disk 
|-sda1    8:1    0    4G  0 part [SWAP]
`-sda2    8:2    0   96G  0 part /
sdb       8:16   0   10G  0 disk 
`-vg-v1 253:0    0    1G  0 lvm  
```

Now after refreshing netdata UI... now on sidebar netdata show one of volumes which was created previously but does not exist:

image

Looks like as this "phantom" has replaced `vg-v1` as any attempt to access `vg-v1` show activity on `vg-thin tmeta`, and no wonder, as chart name (on the left) shows _proper_ name:
image

##### Expected behavior

Correct display of volume names on sidebar.

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
Removing old LVM volumes and adding new ones causes the reuse of the devices with the lowest serial numbers. That leads to the reuse of obsolete charts with old metadata. The solution is to distinguish devices by LVM UUIDs, not by names. The UUIDs for `dm-*` (device mapper) devices can be found in `/sys/devices/virtual/block/dm-*/dm/uuid`.

Fixes #9554

##### Test Plan
1. Create a virtual block device
```
$ dd if=/dev/zero of=/tmp/lvm.test.file bs=1k count=100k
$ sudo losetup /dev/loop0 /tmp/lvm.test.file
```
2. Create an LVM Volume Group
```
$ sudo pvcreate /dev/loop0
$ sudo vgcreate vg /dev/loop0
```
3. Create/remove/create logical volumes with different names
```
$ sudo lvcreate -L 1M -n vol1 vg
$ sudo lvremove vg/vol1
$ sudo lvcreate -L 1M -n vol2 vg
...
```
4. Check if families and chart names are correct.

### CODE REVIEW

**Comment by Ferroin** [comment]
@vlvkobal Would it be possible to generalize this to all devices (thinking we would use hardware serial numbers for physical disks)?

Asking because the original issue is not really unique to device-mapper targets, as even device names for physical storage devices are not guaranteed stable across reboots. For example, It’s not unusual for servers with multiple storage controllers to enumerate devices across them in parallel, in which case the name a given device gets depends on when it happens to get enumerated relative to each other device.

**Comment by vlvkobal** [comment]
> Would it be possible to generalize this to all devices

I couldn't find the information we can use as uuid for other devices. It needs further investigation.

**Comment by Ferroin** [comment]
> > Would it be possible to generalize this to all devices
> 
> I couldn't find the information we can use as uuid for other devices. It needs further investigation.

Point taken. We’ll probably have to leverage udev for this.

**Review by thiagoftsm — APPROVED** [review]
I did not have issues while compiling and PR runs as expected, LGTM!

**Review by ilyam8 — APPROVED** [review]

**Pull request merged**
