### PR TITLE
go.d smartctl

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

Fixes: #15032
Fixes: #7388

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by mailinglists35** [comment]
@ilyam8 will the new smart monitoring enabled by default, or it needs manual activation and configuration?

**Comment by ilyam8** [comment]
Enabled by default.

**Comment by kYwzor** [comment]
@ilyam8 My SMART charts disappeared after updating to v1.46.0. Could this have introduced some bug? Running ` ./go.d.plugin -d -m smartctl` results in one error `dockerd/docker.go:112 Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? component="service discovery" discoverer=docker`. I'm not running Netdata with Docker though, so not sure if it's related.

**Comment by ilyam8** [comment]
This log line is not related.

**Comment by EoinD123** [comment]
I am receiving this error on launch of Netdata in docker as well as when I attempt tdebug:
```
ERR smartctl/smartctl.go:112 failed to scan devices: '/usr/libexec/netdata/plugins.d/ndsudo smartctl-json-scan' execution failed: exit status 4 collector=smartctl job=smartctl
ERR module/job.go:238 check failed collector=smartctl job=smartctl

```
My docker compose contains the correct entries afaik:
```
          cap_add:
               - SYS_PTRACE
               - SYS_ADMIN
               - SYS_RAWIO
          devices:
               - /dev/sda:/dev/sda
               - /dev/sdb:/dev/sdb
               - /dev/sdc:/dev/sdc
               - /dev/sdd:/dev/sdd
```
On my noob attempts at debugging, running /usr/libexec/netdata/plugins.d/ndsudo smartctl-json-scan returns `smartctl: not available in PATH`.  I confirmed that smartctl isn't in any of the default image env paths. It seems like this is the issue, that smartmontools aren't even in the image?

I am on the latest Docker image, Debian 12.
Thanks for any assistance.

**Comment by ilyam8** [comment]
Correct, it is not in the image.

**Pull request merged**
