### PR TITLE
rabbitmq: api/nodes requests fix

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary
Fixes: #5118

##### Component Name
https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/rabbitmq

##### Additional Information

@vpapas please test it

### CODE REVIEW

**Comment by vpapas** [comment]
Hello,

Thanks, for the fix.
I replaced the rabbitmq.chart.py file with new one and after restarting netdata i am getting an error that netdata can not connect to rabbitmq:

2019-01-09 14:53:40: python.d ERROR: rabbitmq: socket: _get_data() failed. Url: http://127.0.0.1:15672. Error:
2019-01-09 14:53:40: python.d INFO: rabbitmq: socket: check() => [FAILED]

I've change the IP in config file with server's IP but the error continues.

**Comment by vpapas** [comment]
Now i have the following:

2019-01-09 15:37:38: python.d ERROR: plugin: main: module load source: 'rabbitmq' => [FAILED]

**Comment by ilyam8** [comment]
@vpapas how did you install it? please try again, there is no `module load source`, i double checked it.

And please run `python.d.plugin` in debug mode.

`./python.d.plugin rabbitmq debug trace`

**Comment by vpapas** [comment]
You are correct. It works! 
I re-installed netdata using this version and everything seems to work as expected.

Thanks a lot,
Vasso

**Pull request merged**
