### PR TITLE
Don't check for ebpf dependencies if ebpf is disabled.

### LINKED ISSUE #9750: 1.24.0 can not be crosscompiled due to libbpf (externaldep)
##### Bug report summary
```
checking if perf.plugin should be enabled... yes
checking for libelf... yes
checking for struct bpf_prog_info... yes
checking for externaldeps/libbpf/libbpf.a... configure: error: cannot check for file existence when cross compiling
```

##### OS / Environment
My OS:
```
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=20.04
/etc/lsb-release:DISTRIB_CODENAME=focal
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION="20.04.1 LTS (Focal Fossa)"
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.1 LTS"
/etc/os-release:VERSION_ID="20.04"
/etc/os-release:HOME_URL="https://www.ubuntu.com/"
/etc/os-release:SUPPORT_URL="https://help.ubuntu.com/"
/etc/os-release:BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
/etc/os-release:PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
/etc/os-release:VERSION_CODENAME=focal
/etc/os-release:UBUNTU_CODENAME=focal
```

##### Steps To Reproduce

1. Download SDK for OpenWrt
2. Use this Makefile https://github.com/openwrt/packages/commit/2de28dd95b8c92e2e76038314cab2e180a4cd554
and change version and hash

##### Expected behavior
It should be compiled even when cross compiling, because package libbpf is not available in OpenWrt
https://github.com/openwrt/packages/pull/12949 

Also, why ebpf plugin can not be disabled as others like nfacct/freeipmi and so on?

### PR DESCRIPTION
**Pull request by KickerTom**
Fixes cross compilation by properly disabling ebpf detection. Fixes #9750.

### CODE REVIEW

**Comment by BKPepe** [comment]
@OdysLam hey, yo! You were wondering why there isn't the latest version of netdata in OpenWrt and this is what I need to be able cross-compile. Thank you, @KickerTom to fixing this issue.

**Review by vlvkobal — APPROVED** [review]

**Comment by vlvkobal** [comment]
@thiagoftsm Please have a look.

**Review by thiagoftsm — APPROVED** [review]
Thank you @KickerTom !

I tested your PR on a VM using Alpine and Kernel 5.4 without the `bpf` syscall and I can confirm that it is not installing the `ebpf.plugin`.

I also tested it on Slackware current with modified kernel and I could install the plugin.

@Ferroin, please, take a look to be sure that I did not miss nothing.

Best regards!

**Review by Ferroin — APPROVED** [review]

**Comment by Ferroin** [comment]
@KickerTom Thanks for fixing this. PRs like this from FOSS contributors such as yourself are a large part of what makes Netdata so awesome.

**Pull request merged**
