### PR TITLE
add dictionary support to statsd

### PR DESCRIPTION
**Pull request by ktsaou**
1. extends the statsd protocol to support automatically building stacked charts based on the values it receives. It is like sets, but instead of reporting just the unique items in the set, it reports a counter (events/s) for every item in the set as a stacked chart. For synthetic charts, only the number of items in the dictionary is reported - there is currently no logic to cherry pick dictionary metrics into synthetic charts.
   
2. do not render the `sum` dimension of histograms and timers on private statsd charts - it was "hidding" all the others and people had to unselect it to see the detail. The `sum` is still available to be used in synthetic charts.
   
3. support statsd tags (using the datadog format https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics) for assigning units of private charts, families and dimension names in private charts (example: `bytes.received:+28520c|#units:bytes,family:traffic,name:bandwidth`)
   
4. parses all statsd tags but it doesn't currently do anything more (other than the units and names above) with them

TODO:

- [x] Update the documentation
- [x] Automatically create private statsd sections on the dashboard for each application that is pushing metrics
- [ ] Find a way for synthetic charts to cherry pick dictionary dimensions
- [ ] Convert tags into chart labels
- [ ] Support labels in synthetic charts

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @ktsaou ,

Are you going to update our [documentation](https://learn.netdata.cloud/docs/agent/collectors/statsd.plugin) with  this PR too? Or do you consider what we have there it is enough?

Best regards!

**Review by surajnpn — APPROVED** [review]

**Review by thiagoftsm — DISMISSED** [review]
I tested locally the plugin with a python client. I tested without the dictionary and with dictionary and everything is working. LGTM!

**Comment by thiagoftsm** [comment]
Our documentation is saying to use `nc -u -w 0`, but when I ran this command with `nc` version `1.10` it fails:

```sh
bash-5.1# nc -h
[v1.10]
connect to somewhere:   nc [-options] hostname port[s] [ports] ... 
listen for inbound:     nc -l -p port [-options] [hostname] [port]
options:
        -e prog                 program to exec after connect [dangerous!!]
        -b                      allow broadcasts
        -g gateway              source-routing hop point[s], up to 8
        -G num                  source-routing pointer: 4, 8, 12, ...
        -h                      this cruft
        -i secs                 delay interval for lines sent, ports scanned
        -l                      listen mode, for inbound connects
        -n                      numeric-only IP addresses, no DNS
        -o file                 hex dump of traffic
        -p port                 local port number
        -r                      randomize local and remote ports
        -q secs                 quit after EOF on stdin and delay of secs
        -s addr                 local source address
        -t                      answer TELNET negotiation
        -u                      UDP mode
        -v                      verbose [use twice to be more verbose]
        -w secs                 timeout for connects and final net reads
        -z                      zero-I/O mode [used for scanning]
port numbers can be individual or ranges: lo-hi [inclusive]
bash-5.1# printf "metric1:10|g\nmetric2:10|c\n" | nc -u -w 1 localhost 8125
bash-5.1# printf "metric1:10|g\nmetric2:10|c\n" | nc -u -w 0 localhost 8125
invalid wait-time 0
```

**Comment by thiagoftsm** [comment]
Hello @ktsaou ,

I observed that your PR is working as expected:

Screenshot_20220524_200231

I am only waiting for a commit that will fix [this](https://github.com/netdata/netdata/pull/12980#issuecomment-1136374493) comment or your netcat version, because with the version tested, I cannot use `-w 0`.

Best regards!

**Comment by ktsaou** [comment]
@thiagoftsm which netcat package you have installed?

**Comment by thiagoftsm** [comment]
I forgot to add the source used to compile, it is available [here](https://mirrors.slackware.com/slackware/slackware64-current/source/n/nc/) together with the scripts.

**Comment by ktsaou** [comment]
`-w 1` will have a one second timeout, which is bad.
Also you don't have `-N`.

As I said in the document, you need `openbsd-netcat`.

**Comment by ktsaou** [comment]
This PR is complemented with https://github.com/netdata/dashboard/pull/405

**Review by thiagoftsm — APPROVED** [review]
After explanation received, and another round of tests, this time including the `tags`, I observed that I have all the charts as expected. LGTM!

**Pull request merged**
