### PR TITLE
github/workflow: disable `document-start` yamllint check

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

ssia

> https://yamllint.readthedocs.io/en/stable/configuration.html#extending-the-default-configuration

##### Component Name

`github/workflow`

### CODE REVIEW

**Comment by prologic** [comment]
Yes okay fine :)

**Comment by ilyam8** [comment]
> .yamllint.yml in the top-level repo instead.

somehow i missed that we have it 😅 thx!

**Comment by Ferroin** [comment]
@ilyam8 Can you provide some reasoning for wanting to disable this check? I've not seen any complaints regarding it, and it does help prevent a real issue (namely, some YAML parsers choke if they don't see a proper document start).

**Comment by ilyam8** [comment]
Reasoning is lack of sense in our case, all our yaml files have no `---`

https://github.com/netdata/netdata/pull/8521

> some YAML parsers choke if they don't see a proper document start

Not good parsers or some strict mode.

**Comment by ilyam8** [comment]
> all our yaml files 

i mean python/go configurations, i personally see no sense to use them, but if it really good thing (havent seen use case when it is needed) i am totally ok.

**Comment by prologic** [comment]
@Ferroin Whist you are right, Is there any YAML tools, parsers or services we use that would break if we disabled this check? If no, I'm okay merging this. If yes then I'll happily go and en-mass fix this across our entire codebase across every repo.

**Comment by Ferroin** [comment]
I've seen complaints from GitHub Actions when the workflow files don't have a proper document start, but I've ot seen issues from anything else.

**Comment by prologic** [comment]
> I've seen complaints from GitHub Actions when the workflow files don't have a proper document start, but I've ot seen issues from anything else.

Hmmm 🤔any recent examples? Perhaps Github fixed their parser? :)

**Comment by ilyam8** [comment]
@prologic @Ferroin can i merge this? or code freeze affects this PR?

**Comment by prologic** [comment]
This is fine to merge as it fixes a bug in our CI checks.

**Pull request merged**
