### PR TITLE
Support for aggregate node view

### PR DESCRIPTION
**Pull request by gmosx**
Adds support for the Aggregated view.

### CODE REVIEW

**Comment by cakrit** [comment]
I installed it and signed in, using the manifest... cloud base URL. I don't see anything different on the UI, what am I supposed to do?

**Comment by cakrit** [comment]
Never mind, I found the link under the name. It opens a blank page for me.

**Comment by gmosx** [comment]
> Never mind, I found the link under the name. It opens a blank page for me.

It was not ready for review yet.
BTW, I just pushed a new version which should probably work. Please try again and let me know.

**Comment by cakrit** [comment]
1. Direct access via localhost:19999 gives the following:
```
Access to script at 'https://my-netdata.io/dashboard.js?v=3' from origin 'http://localhost:19999' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://netdata.domain.tld' that is not equal to the supplied origin.
```
Not sure where it found `netdata.domain.tld`, that's how I access it via the proxy.

2. Tried to access it via `http://netdata.domain.tld:82/netdata/` and got 404 not found. The browser requested `http://netdata.domain.tld:82/console/index.html`, though it should have requested `http://netdata.domain.tld:82/netdata/console/index.html#/`. I had this test handy, because we have a person with such an open issue now.

3. Tried to access it via `http://netdata.domain.tld` and got the following:
Screenshot from 2019-04-30 11-50-00

So I can't get it to work at all.

**Comment by gmosx** [comment]
> 1. Tried to access it via `http://netdata.domain.tld:82/netdata/` and got 404 not found. The browser requested `http://netdata.domain.tld:82/console/index.html`, though it should have requested `http://netdata.domain.tld:82/netdata/console/index.html#/`. I had this test handy, because we have a person with such an open issue now.

Good catch, I will have a look at this.

**Comment by gmosx** [comment]
@cakrit , @ktsaou please review for merging.

**Pull request merged**
