### PR TITLE
Tiering statistics API endpoint

### PR DESCRIPTION
**Pull request by ktsaou**
Tiering statistics for the calculator

### CODE REVIEW

**Comment by ktsaou** [comment]
rebased to master

**Comment by ktsaou** [comment]
This is safe to be merged. It adds a new endpoint which we only need for the calculator. New PRs will probably follow.
Can you review it please?

**Comment by ktsaou** [comment]
rebased to master

**Comment by thiagoftsm** [comment]
@ktsaou sorry for the delay, I saw that you already merged the PR. The code is OK, and I tested the current master branch with different memory modes and I observed the endpoint working.

**Pull request merged**
