### PR TITLE
Print INTERNAL BUG messages only when NETDATA_INTERNAL_CHECKS is enabled

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Prints `INTERNAL BUG` messages only when compiled with `NETDATA_INTERNAL_CHECKS`.

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]

**Review by vkalintiris — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]

**Comment by ktsaou** [comment]
You saw them printed?

**Comment by MrZammler** [comment]
> You saw them printed?

Hi Costa, yes, during some tests with @dimko . All of them came from health, we're checking...

**Comment by ktsaou** [comment]
Can I see these log lines please?
They should never happen - we may have a bug in dbengine if they do. Or may have missed a case in dbengine we should handle.

**Comment by dimko** [comment]
@ktsaou I am attaching part of the logs. I can send you the full log if needed. 

> 2022-06-23 14:11:34: netdata ERROR : MAIN : child pid 1139 exited with code 1.
> 2022-06-23 14:11:35: cgroup-name.sh: INFO: cgroup 'systemreserved_ntpd' is called 'systemreserved_ntpd'
> 2022-06-23 14:11:36: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : Using host prefix directory '/host'
> 2022-06-23 14:11:36: /usr/libexec/netdata/plugins.d/cgroup-network INFO  : MAIN : running: exec /usr/libexec/netdata/plugins.d/cgroup-network-helper.sh --cgroup '/host/sys/fs/cgroup/cpuacct/systemreserved/ntpd'
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/102 requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/netdata requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/root requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:37: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/1200 requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:37: alarm-notify.sh: WARNING: Cannot find file '/etc/netdata/health_alarm_notify.conf'.
> 2022-06-23 14:11:37: cgroup-network-helper.sh: INFO: searching for network interfaces of cgroup '/host/sys/fs/cgroup/cpuacct/systemreserved/ntpd'
> 2022-06-23 14:11:38: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : child pid 1182 exited with code 1.
> 2022-06-23 14:11:38: /usr/libexec/netdata/plugins.d/cgroup-network ERROR : MAIN : Cannot find a cgroup PID from cgroup '/host/sys/fs/cgroup/cpuacct/systemreserved/ntpd'
> 2022-06-23 14:11:38: netdata ERROR : MAIN : child pid 1158 exited with code 1.
> 2022-06-23 14:11:38: alarm-notify.sh: ERROR: failed to send email notification for: e2c819d0e42f users.mem.custom_warning_dkpjapungzo is WARNING to 'root' with error code 1 (sendmail: can't connect to remote host (127.0.0.1): Connection refused).
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/102 requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/netdata requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/root requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:38: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/1200 requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:38: netdata ERROR : GLOBAL_STATS : heartbeat clock: woke up 41882 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/102 requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, netdata) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/netdata requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, root) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/root requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point end time 1655982659, before the last point end time 1655982660 (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 1200) returned point 1655982658 to 1655982660, before now (now = 1655982661, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1)
> 2022-06-23 14:11:39: netdata ERROR : HEALTH : QUERY: INTERNAL ERROR: query on users.mem/1200 requested 1 points, but RRDR added 0. (errno 22, Invalid argument)
> 2022-06-23 14:11:39: netdata ERROR : ANALYTICS : heartbeat clock: woke up 42274 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: netdata ERROR : PLUGIN[diskspace] : heartbeat clock: woke up 40922 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: netdata ERROR : PLUGIN[cgroups] : heartbeat clock: woke up 41623 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: netdata ERROR : MAIN : heartbeat clock: woke up 42410 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: netdata ERROR : PLUGIN[proc netdev] : heartbeat clock: woke up 42449 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: netdata ERROR : ACLK_Stats : heartbeat clock: woke up 32268 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: netdata ERROR : STATSD : heartbeat clock: woke up 42395 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: netdata ERROR : PLUGIN[proc] : heartbeat clock: woke up 42348 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:39: cgroup-name.sh: INFO: cgroup 'dns-forwarder' is called 'dns-forwarder'
> 2022-06-23 14:11:39: apps.plugin ERROR : MAIN : heartbeat clock: woke up 41686 microseconds earlier than expected (can be due to the CLOCK_REALTIME set to the past).
> 2022-06-23 14:11:40: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point start time 1655982659, end time 1655982659, that are both equal
> 2022-06-23 14:11:40: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point 1655982658 to 1655982659, before now (now = 1655982660, after_wanted = 1655982660, before_wanted = 1655982661, dt = 1) (errno 22, Invalid argument)
> 2022-06-23 14:11:40: netdata ERROR : HEALTH : QUERY: INTERNAL BUG: next_metric(users.mem, 102) returned point start time 1655982659, end time 1655982659, that are both equal

**Comment by ktsaou** [comment]
Guys, this log is about health queries on chart `users.mem`, but I can't find such an alarm.
Can you give me the configuration please?
Also, are these nodes running dbengine or something else?

**Comment by dimko** [comment]
This is a custom alert with dummy values, just for testing reasons.

it's on **chart: users.mem** with **lookup: average -1m percentage of netdata** and **units: %**, **every 1 second**

all other values are dummy. 

The problem was that the log was becoming too big after a while, exceeding 500Mb

**Comment by ktsaou** [comment]
@dimko please paste here the exact alarm configuration. I need to reproduce this.

**Comment by ktsaou** [comment]
And please let me know the memory mode you have been using for the test.

**Comment by dimko** [comment]
Sorry for the delay. 

@ktsaou alert config:
         

>  template: dq1o4l16ksq
>           on: users.mem
>           hosts: *
>           lookup: average -1m percentage of netdata
>           units: %
>           class: Utilization
>           type: System
>           component: CPU
>           every: 1s
>           crit: $this != $this
>           warn: $this > 0
>           delay: up 0s down 0s multiplier 1.0 max 1h
>           info: custom warning alert two


it's dbengine. the agent has the default configuration setting we provide in a docker container

**Comment by dimko** [comment]
> crit: $this != $this

> hm... I don't think this will ever be true.

That's what I want, don't want critical to be triggered 😛 

I am not really relying on the correct functionality of this alert. It's just some negative testing to verify that all data are synced to cloud.

However, a new question arises. Should we allow alerts that aren't correct? Should they trigger an alert and be synced to cloud? how can a user know if a custom alert he has created is correct or wrong?

and the most important. incorrect configurations passed by the user shouldn't break netdata, it should be evaluated, dropped and ignore with proper error messages. So a number of negative scenarios is needed to ensure this.

**Pull request merged**
