### PR TITLE
fix(kickstart.sh): detect existing "custom" installation under /opt

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

That is a pretty common case when we (at least I do it always) build Netdata from source using `--install /opt`.

- before this PR we can't detect an existing installation and **are trying to install Netdata**

  <details>
  <summary>kickstart log</summary>

  ```cmd
  $ sudo ./kickstart.sh

   --- Using /tmp/netdata-kickstart-XJzUdAUZWl as a temporary directory. ---
   --- Checking for existing installations of Netdata... ---
   --- No existing installations of netdata found, assuming this is a fresh install. ---
   --- Attempting to install using native packages... ---
   --- Checking for availability of repository configuration package. ---
  [/tmp/netdata-kickstart-XJzUdAUZWl]# curl --fail -q -sSL --connect-timeout 10 --retry 3 --output /tmp/netdata-kickstart-XJzUdAUZWl/netdata-repo-edge_1-1_all.deb https://packagecloud.io/netdata/netdata-repoconfig/packages/debian/bullseye/netdata-repo-edge_1-1_all.deb/download.deb
   OK

  [/tmp/netdata-kickstart-XJzUdAUZWl]# env apt-get update
  Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
  Hit:2 http://deb.debian.org/debian bullseye InRelease
  Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
  Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
  Hit:5 https://download.docker.com/linux/debian bullseye InRelease
  Hit:6 https://apt.releases.hashicorp.com bullseye InRelease
  Hit:7 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
  0% [Connected to packagecloud.io (52.52.85.114)]^C ERROR  Installer exited unexpectedly (2-0)
  ```

  </details>

- after this PR we find an existing install and **are NOT trying to install Netdata**

  <details>
  <summary>kickstart logs</summary>

  ```cmd
  $ sudo ./kickstart.sh
  
   --- Using /tmp/netdata-kickstart-X9GNfsxoPL as a temporary directory. ---
   --- Checking for existing installations of Netdata... ---
   ABORTED  Found an existing netdata install at /opt/netdata, but the install type is 'custom', which is not supported, refusing to proceed.
  ```

  </details>

---

@netdata/agent-sre If that is expected behavior I am ok with won't fix that.

##### Test Plan

Run the script, ensure it finds an existing install, and doesn't try to install Netdata.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by Ferroin** [comment]
This is not expected behavior, but I would argue that this is not the correct fix. I would rather modify the `searchpath` variable so that we are actually looking here instead of adding yet another special case. I’ve been meaning to update it anyway to check the ‘common’ prefixes in addition to `$PATH` and any specified install prefix.

**Comment by ilyam8** [comment]
> I would rather modify the searchpath variable so that we are actually looking here instead of adding yet another special case

My modification is according to the current code:
 - we update `searchpath` **only** when INSTALL_PREFIX is set (not the case this PR fixes).
 - there is already a special case for static, so I added another one.

I don't say it is the best way, just following the current implementation.

**Review by iigorkarpov — COMMENTED** [review]
What about something like this?

```
location=$(find / -maxdepth 3 -name .install-type -type f 2>&1 | grep -v "Permission denied")
echo "$(dirname $location)"
```

**Comment by Ferroin** [comment]
I had actually meant to leverage `$searchpath` even in the normal case for this, but I honestly like the approach suggested by @iigorkarpov better. It would need to be something like this though:

```sh
location=$(find / -name .install-type -type f 2>&1 | grep -v "Permission denied" | head -n 1)
abspath="$(cd "$(dirname "${location}"; pwd)"
echo "$(dirname "$(dirname "$location")")"
```

We can’t use `-maxdepth` on `find` because prefixes other than `/` simply won’t work with it set. We would obviously want appropriate exclusions on the `find` command to skip things like `/proc` as well. We also need the path canonicalization of the second line of the above to handle people doing strange things with symlinks properly.

That could (mostly, with additional checks looking for the agent binary itself to confirm the path) replace the complex logic we0re currently using for searching for an existing install, and would fix the particular case this PR sets out to fix as well as a number of other edge cases.

**Comment by ilyam8** [comment]
Ok, closing this PR is not getting merged (@Ferroin doesn't like it!)

**Pull request closed without merging**
