### PR TITLE
Make netdata-updater.sh POSIX compliant.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

Split out from #11753 as requested.

This is needed for portability reasons for support for binary packages.

More specifically, the changes involve:

* Updating `source` to `.`. This is a functional no-op given how we are using `source`.
* Replacing `==` in conditionals with `=`. This is also a functional no-op for our current usage in the script.
* Remove usage of `local`. We’ve got things set up so that there is no overlap in variable names so there is no need to declare variables as local.
* Replaced regex-based conditionals with equivalents using `grep`. These are slightly less efficient, but functionally somewhat more flexible.
* Replaced instances of array usage with equivalents using a temporary file and individual variables. The net result is more compact, but arguably easier to understand.
* Completely eliminated the somewhat questionable array usage around line 330.
* Replaced the usage of `$RANDOM` with a `awk` call to get a random number.

##### Component Name

area/packaging

##### Test Plan

CI passes on this PR.

Local testing can be done by running the updater script from this PR with the `--no-updater-self-update`.

### CODE REVIEW

**Review by vkalintiris — CHANGES_REQUESTED** [review]
> Remove usage of local. We’ve got things set up so that there is no overlap in variable names so there is no need to declare variables as local.

AFAICT, dash supports `local`. The first thing I'm doing when seeing a non-`local` variable being set in a function is to look for all the other places where it might get used.

**Review by iigorkarpov — APPROVED** [review]

**Comment by Ferroin** [comment]
> > Remove usage of local. We’ve got things set up so that there is no overlap in variable names so there is no need to declare variables as local.
> 
> AFAICT, dash supports `local`. The first thing I'm doing when seeing a non-`local` variable being set in a function is to look for all the other places where it might get used.

First off, that rigorous checking _is still needed with local variables_. Scoping in shell script is dynamic, not lexical (that is, variables declared `local` in a given scope still propagate down into narrower scopes within that scope, _including functions called from that scope_). This type of checking is an inherent cost of using shell script, you can’t completely eliminate it.

Secondly, _if_ we can prove that all platforms we care about guarantee that `/bin/sh` will support `local`, I’d be fine with adding a global shellcheck exception for the file and re-adding usage of `local`. It was just easier to remove usage than verify this though. The big issue here is busybox, because last I checked at least one of the shell implementations there allows support for `local` to be disabled at build time, and the updater code needs to work on systems which use busybox for `/bin/sh` because it needs to work for static installs _and_ cannot rely on the static build of bash provided by the static install.

**Comment by vkalintiris** [comment]
> The big issue here is busybox, because last I checked at least one of the shell implementations there allows support for local to be disabled at build time, and the updater code needs to work on systems which use busybox for /bin/sh because it needs to work for static installs and cannot rely on the static build of bash provided by the static install.

We can't and shouldn't support everything and forever. Based on the officially supported distros/platforms what is the lowest common denominator that will make our scripts run? This should be documented somewhere so that we can understand what is available for use during development and isn't.

**Comment by Ferroin** [comment]
> > The big issue here is busybox, because last I checked at least one of the shell implementations there allows support for local to be disabled at build time, and the updater code needs to work on systems which use busybox for /bin/sh because it needs to work for static installs and cannot rely on the static build of bash provided by the static install.
> 
> We can't and shouldn't support everything and forever. Based on the officially supported distros/platforms what is the lowest common denominator that will make our scripts run? This should be documented somewhere so that we can understand what is available for use during development and what isn't.

It’s not _just_ official support that matters. If there is community demand for something, we should not stand in the way of the community supporting it unless it actually does cause problems for us. There is _significant_ community demand for running Netdata on routers and other network appliances (note all the talk about pfSense and OPNSense, as well as the numerous cases of people asking for ipkg binary packages), and most of the Linux distros built for that use busybox as their shell. We _do_ need to care about whether the major ones (OpenWRT, DD-WRT, IPFire, and OpenWall) actually provide the functionality we want to use, because if they don’t we will be dealing with users asking for this functionality.

**Review by marius-locomotion — DISMISSED** [review]

**Comment by vkalintiris** [comment]
@Ferroin please rebase and I'll approve once CI's ok.

**Review by iigorkarpov — APPROVED** [review]

**Review by vkalintiris — APPROVED** [review]

**Comment by Ferroin** [comment]
Delaying this until 24h after the release to make sure people on stable releases can safely update.

**Pull request merged**
