### PR TITLE
Update web server options for respecting browser DNT

### LINKED ISSUE #7465: Registry feature needs "Do Not Track" disabled in the browser
##### Bug report summary

You mention in the registry docs that the browser needs to be configured to allow cross-site cookies. You may say that implicitely this means also to "disable the Do Not Track setttings". Please mention explicitely in the docs to disable DNT and to allow cross-site cookies.

At least Chrome shows in the developer console that the request is not send due to DNT.

### PR DESCRIPTION
**Pull request by joelhans**
##### Summary

Fixes #7465

This PR provides more explanation for how the `respect do not track policy` works and provides some context for how users can enable blocked features by disabling DNT in their browser and changing this option to `yes`.

##### Component Name

area/docs
area/web

### CODE REVIEW

**Comment by joelhans** [comment]
@jacekkolasa Ping on this! Let me know if this looks good to you, and if so, I'll find another reviewer.

**Comment by jacekkolasa** [comment]
@joelhans thanks for pinging. Maybe we should add a note describing that it applies also to `connecting to registry`? Also, shouldn't we explicitly state that users will not be able to login to Netdata Cloud on their Agent Dashboards? Sentence "users will not be able to connect their nodes to Netdata Cloud." can be confusing, because one can think this is related to claiming and that it has something to do with DNT. Please correct me if i'm wrong.

**Comment by ilyam8** [comment]
@joelhans do we want to merge it?

**Comment by joelhans** [comment]
@ilyam8 Yeah, I think that after my latest change this is OK to merge.

**Review by ilyam8 — DISMISSED** [review]

**Comment by jacekkolasa** [comment]
The only problem is that this feature is not yet implemented. We don't restrict access to Netdata Cloud this way.
CC @allelos

**Comment by jacekkolasa** [comment]
@joelhans @ilyam8 I was wrong, we actually do it! I just tested it. It's working this way a little "by accident", that's why I wasn't sure.
In other words, we can merge that

**Review by jacekkolasa — DISMISSED** [review]

**Comment by ilyam8** [comment]
@joelhans please rebase the PR to fix ci checks

**Review by ilyam8 — APPROVED** [review]

**Review by jacekkolasa — APPROVED** [review]

**Comment by ilyam8** [comment]
close/open to fix license/cla check

**Pull request merged**
