### PR TITLE
Move ACLK Legacy into subfolder

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Moves ACLK into `aclk/legacy` subfolder making space for ACLK-NG in the next PR.

ACLK-NG allows MQTT over WSS communication with OpenSSL only and getting rid of need for libmosquitto and libwebsockets.

##### Component Name
agent/aclk

##### Test Plan
Should not break anything (build methods). Should work as before.

### CODE REVIEW

**Comment by underhood** [comment]
rebased on latest master after the ClaimingMVP1 got merged

**Comment by underhood** [comment]
rebased on latest master (fix merge conflicts)

**Review by mfundul — APPROVED** [review]

**Comment by underhood** [comment]
rebased on latest master for CentOS 8 CI fixes

**Comment by underhood** [comment]
rebased on latest master for CentOS 8 CI fixes

**Review by mfundul — DISMISSED** [review]

**Comment by underhood** [comment]
force push due to rebasing to solve merge conflict that was created after this PR was already passing CI

**Comment by underhood** [comment]
rebased again to be able to solve conflicts on ACLK-NG branch which is based on this branch (there wa s conflict in CI files meanwhile modified by austin

**Review by stelfrag — APPROVED** [review]

**Review by vkalintiris — APPROVED** [review]
I suspect a `git mv aclk aclk-legacy` followed by a relative symlink `ln -s aclk-legacy aclk` would have suffice.

**Pull request merged**
