### PR TITLE
rabbitmq: survive lack of vhosts

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

fixes: #7018

##### Component Name
[`/collectors/python.d.plugin/rabbitmq`](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/elasticsearch/rabbitmq.chart.py)

##### Additional Information

bug was added in https://github.com/netdata/netdata/pull/6976

### CODE REVIEW

**Comment by ilyam8** [comment]
@mahamafzar

please test the PR

**Comment by mahamafzar** [comment]
I get following response during debugging

`2019-10-08 15:37:50: python.d INFO: plugin[main] : using python v2
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : looking for 'python.d.conf' in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : loading '/usr/lib/netdata/conf.d/python.d.conf'
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : '/usr/lib/netdata/conf.d/python.d.conf' is loaded
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : looking for 'pythond-jobs-statuses.json' in /var/lib/netdata
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : loading '/var/lib/netdata/pythond-jobs-statuses.json'
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : '/var/lib/netdata/pythond-jobs-statuses.json' is loaded
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : [rabbitmq] looking for 'rabbitmq.conf' in ['/etc/netdata/python.d', '/usr/lib/netdata/conf.d/python.d']
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : [rabbitmq] loading '/etc/netdata/python.d/rabbitmq.conf'
2019-10-08 15:37:50: python.d DEBUG: plugin[main] : [rabbitmq] '/etc/netdata/python.d/rabbitmq.conf' is loaded
2019-10-08 15:37:50: python.d INFO: plugin[main] : [rabbitmq] built 1 job(s) configs
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : urllib3 version: 1.21.1
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : doing http request to 'http://127.0.0.1:53000/api/overview'
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : found node name: 'general@29ba689e3680'
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : number of metrics: 7
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : doing http request to 'http://127.0.0.1:53000/api/nodes/general@29ba689e3680'
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : number of metrics: 6
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : doing http request to 'http://127.0.0.1:53000/api/vhosts'
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : number of vhosts: 1, metrics: 0
2019-10-08 15:37:50: python.d INFO: plugin[main] : rabbitmq[remote] : check success
CHART netdata.runtime_rabbitmq_remote '' 'Execution time for rabbitmq_remote' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : started, update frequency: 1
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : doing http request to 'http://127.0.0.1:53000/api/overview'
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : found node name: 'general@29ba689e3680'
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : number of metrics: 7
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : doing http request to 'http://127.0.0.1:53000/api/nodes/general@29ba689e3680'
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : number of metrics: 6
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : doing http request to 'http://127.0.0.1:53000/api/vhosts'
2019-10-08 15:37:50: python.d DEBUG: rabbitmq[remote] : number of vhosts: 1, metrics: 0
CHART rabbitmq_remote.erlang_processes '' 'Erlang Processes' 'processes' 'overview' 'rabbitmq.processes' line 60005 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'proc_used' 'used' absolute 1 1 ' '

BEGIN rabbitmq_remote.erlang_processes 0
SET 'proc_used' = 650
END

CHART rabbitmq_remote.file_descriptors '' 'File Descriptors' 'descriptors' 'overview' 'rabbitmq.file_descriptors' line 60003 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'fd_used' 'used' absolute 1 1 ' '

BEGIN rabbitmq_remote.file_descriptors 0
SET 'fd_used' = 99
END

CHART rabbitmq_remote.queued_messages '' 'Queued Messages' 'messages' 'overview' 'rabbitmq.queued_messages' stacked 60000 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'queue_totals_messages_ready' 'ready' absolute 1 1 ' '
DIMENSION 'queue_totals_messages_unacknowledged' 'unacknowledged' absolute 1 1 ' '

BEGIN rabbitmq_remote.queued_messages 0
SET 'queue_totals_messages_ready' = 0
SET 'queue_totals_messages_unacknowledged' = 0
END

CHART rabbitmq_remote.socket_descriptors '' 'Socket Descriptors' 'descriptors' 'overview' 'rabbitmq.sockets' line 60004 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'sockets_used' 'used' absolute 1 1 ' '

BEGIN rabbitmq_remote.socket_descriptors 0
SET 'sockets_used' = 7
END

CHART rabbitmq_remote.memory '' 'Memory' 'MiB' 'overview' 'rabbitmq.memory' area 60007 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'mem_used' 'used' absolute 1 1048576 ' '

BEGIN rabbitmq_remote.memory 0
SET 'mem_used' = 112062464
END

CHART rabbitmq_remote.global_counts '' 'Global Counts' 'counts' 'overview' 'rabbitmq.global_counts' line 60002 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'object_totals_channels' 'channels' absolute 1 1 ' '
DIMENSION 'object_totals_consumers' 'consumers' absolute 1 1 ' '
DIMENSION 'object_totals_connections' 'connections' absolute 1 1 ' '
DIMENSION 'object_totals_queues' 'queues' absolute 1 1 ' '
DIMENSION 'object_totals_exchanges' 'exchanges' absolute 1 1 ' '

BEGIN rabbitmq_remote.global_counts 0
SET 'object_totals_channels' = 21
SET 'object_totals_consumers' = 21
SET 'object_totals_connections' = 7
SET 'object_totals_queues' = 48
SET 'object_totals_exchanges' = 27
END

CHART rabbitmq_remote.disk_space '' 'Disk Space' 'GiB' 'overview' 'rabbitmq.disk_space' area 60008 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'disk_free' 'free' absolute 1 1073741824 ' '

BEGIN rabbitmq_remote.disk_space 0
SET 'disk_free' = 220386787328
END

CHART rabbitmq_remote.erlang_run_queue '' 'Erlang Run Queue' 'processes' 'overview' 'rabbitmq.erlang_run_queue' line 60006 1 '' 'python.d.plugin' 'rabbitmq'
DIMENSION 'run_queue' 'length' absolute 1 1 ' '

BEGIN rabbitmq_remote.erlang_run_queue 0
SET 'run_queue' = 0
END

BEGIN netdata.runtime_rabbitmq_remote 0
SET run_time = 37
END`

**Comment by ilyam8** [comment]
I see it works, you need to restart netdata service, refresh browser page

**Comment by mahamafzar** [comment]
I did it but still not visible in the dashboard, While other enabled plugins are visible.

**Comment by ilyam8** [comment]
@mahamafzar check errors logs

 - cd to log dir
 - cp /dev/null error.log
 - restart netdata service
 - wait a bit
 - grep rabbitmq error.log

**Comment by mahamafzar** [comment]
Than you @ilyam8, I was moved old `rabbitmq.chart.py` to `.rabbitmq.chart.py` (hidden file), After checking the logs that you mentioned, I saw the Netdata still reading the hidden `.rabbitmq.chart.py` file.  
I removed it and the problem has been solved and I have the charts in the dashboard now.

**Comment by ilyam8** [comment]
>  I saw the Netdata still reading the hidden .rabbitmq.chart.py

ye ye, plugin reads `*.chart.py`

**Pull request merged**
