### PR TITLE
Remove old docs generation tooling

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

ssia

##### Component Name

- area/docs

##### Test Plan

None -- Migration happened already.

##### Additional Information

### CODE REVIEW

**Comment by prologic** [comment]
> I don't know about any of the CI/Docker stuff, but removing all the content in `docs/generator/` is the right way to go, so I'm approving from that perspective. Thanks @prologic!

Latest commit should fix the Build/CI errors. I had no idea it was tied into our actual Build system that is typically used to build the actual Agent written in C :)

**Comment by prologic** [comment]
@joelhans Is there an issue for this I can connect to? if not can you create one?

**Comment by joelhans** [comment]
@prologic Just wrote up my plan on #8990 based on our conversation and some things I thought up this morning. Feel free to drop feedback there.

**Comment by prologic** [comment]
Already done :) And on some of your PRs.

**Pull request merged**
