### PR TITLE
[github/templates] Add samples cmds to get OS env

### PR DESCRIPTION
**Pull request by Saruspete**
When reporting bugs, users doesn't seem to know what information to
report for the line "OS / Environment".

- `uname -a`: Provide the arch + kernel (which has the dist tag name)
- `grep -Hv ^# /etc/*release`: most of distribution provide some sort
of /etc/*release file. Adding -H to get the filename too. And -v ^#
to remove comments if any

Example on my Fedora:

```
uname -a; grep -Hv ^# /etc/*release
Linux munin 5.2.18-100.fc29.x86_64 #1 SMP Tue Oct 1 13:32:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/etc/fedora-release:Fedora release 29 (Twenty Nine)
/etc/os-release:NAME=Fedora
/etc/os-release:VERSION="29 (Twenty Nine)"
/etc/os-release:ID=fedora
/etc/os-release:VERSION_ID=29
/etc/os-release:VERSION_CODENAME=""
/etc/os-release:PLATFORM_ID="platform:f29"
/etc/os-release:PRETTY_NAME="Fedora 29 (Twenty Nine)"
/etc/os-release:ANSI_COLOR="0;34"
/etc/os-release:LOGO=fedora-logo-icon
/etc/os-release:CPE_NAME="cpe:/o:fedoraproject:fedora:29"
/etc/os-release:HOME_URL="https://fedoraproject.org/"
/etc/os-release:DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
/etc/os-release:SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
/etc/os-release:BUG_REPORT_URL="https://bugzilla.redhat.com/"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT="Fedora"
/etc/os-release:REDHAT_BUGZILLA_PRODUCT_VERSION=29
/etc/os-release:REDHAT_SUPPORT_PRODUCT="Fedora"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION=29
/etc/os-release:PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
/etc/redhat-release:Fedora release 29 (Twenty Nine)
/etc/system-release:Fedora release 29 (Twenty Nine)
```

### CODE REVIEW

**Comment by Saruspete** [comment]
@joelhans @cosmix could one of you review / validate this so new tickets could have this information ?

**Comment by ilyam8** [comment]
how about to devnull errors? @Saruspete 

```console
11 ilyam:~ $ uname -a; grep -Hv ^# /etc/*release
Darwin Ilyas-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
grep: /etc/*release: No such file or directory
```

vs

```console
12 ilyam:~ $ uname -a; grep -Hv ^# /etc/*release 2>/dev/null
Darwin Ilyas-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
13 ilyam:~ $
```

**Comment by Saruspete** [comment]
@ilyam8 yes that was a possibility but I thought having the error was more useful than having nothing and think user didn't exec the command.
If you think it'll confuse user, we can remove error indeed.

**Comment by ilyam8** [comment]
> I thought having the error was more useful than having nothing and think user didn't exec the command.

Yes, but there is no guarantee user will copy the error message. 

macOS is `sw_vers`

> https://developer.apple.com/documentation/installerjs/system/1812284-version

**Comment by ilyam8** [comment]
I agree that error is nice to have. Probably we need to make it clear that all output should be copied - error too if there is any.

**Comment by ilyam8** [comment]
I think we need to merge it

https://github.com/netdata/netdata/issues/7650#issuecomment-570080020

> grep -Hv ^# /etc/*release

doesnt work on macOS, we need to execute `sw_vers`.

Something like that

```bash
uname -a; if [[ -x "$(command -v sw_vers)" ]]; then sw_vers; else grep -Hv "^#" /etc/*release; fi
```

but it looks ugly

@prologic what do you think?

**Comment by prologic** [comment]
We could probably shorten this a bit and use less Bash(isms) like this:

```#!sh
# My Mac
$ uname -a; command sw_vers && sw_vers || grep -Hv "^#" /etc/*release
Darwin Jamess-iMac.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64 i386 iMac19,2 Darwin
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57

# My CRUX NAS
$ uname -a; command sw_vers && sw_vers || grep -Hv "^#" /etc/*release
Linux data 3.12.24 #11 SMP Mon Aug 10 22:25:23 AEST 2015 x86_64 Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz GenuineIntel GNU/Linux
-bash: sw_vers: command not found
grep: /etc/*release: No such file or directory

# My Scientific Linux PBX
root@IncrediblePBX:~ $ uname -a; command sw_vers && sw_vers || grep -Hv "^#" /etc/*release
Linux IncrediblePBX.local 2.6.32-573.3.1.el6.i686 #1 SMP Thu Aug 13 12:35:03 CDT 2015 i686 i686 i386 GNU/Linux
-bash: sw_vers: command not found
/etc/lsb-release:LSB_VERSION=base-4.0-ia32:base-4.0-noarch:core-4.0-ia32:core-4.0-noarch
/etc/redhat-release:Scientific Linux release 6.7 (Carbon)
/etc/system-release:Scientific Linux release 6.7 (Carbon)
WARNING: Always run Incredible PBX behind a secure hardware-based firewall.
```

What do you think?

**Comment by ilyam8** [comment]
@prologic 👍 

> uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release

- linux

```bash
test@DEB10-1:~$ uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release
Linux DEB10-1 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
/etc/os-release:PRETTY_NAME="Debian GNU/Linux 10 (buster)"
/etc/os-release:NAME="Debian GNU/Linux"
/etc/os-release:VERSION_ID="10"
/etc/os-release:VERSION="10 (buster)"
/etc/os-release:VERSION_CODENAME=buster
/etc/os-release:ID=debian
/etc/os-release:HOME_URL="https://www.debian.org/"
/etc/os-release:SUPPORT_URL="https://www.debian.org/support"
/etc/os-release:BUG_REPORT_URL="https://bugs.debian.org/"
```

- macos

```bash
36 ilyam:~ $ uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release
Darwin Ilyas-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
/usr/bin/sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57
```


@Saruspete if you are ok please update the PR, let's get it merged 😄

**Comment by prologic** [comment]
I _still_ feel like there _has_ to be a better way to do this; but 🤷‍♂️

**Comment by Saruspete** [comment]
@prologic Should we make a full script to gather relevant details to be joined to the case ? Kinda like an `sosreport` ?

**Comment by ilyam8** [comment]
i see our bug template

```
<!---
When creating a bug report please:
- Verify first that your issue is not already reported on GitHub
- Test if the latest release and master branch are affected too.
- Provide a clear and concise description of what the bug is in "Bug report 
  summary" section.
- Try to provide as much information about your environment (OS distribution,
  running in container, etc.) as possible to allow us reproduce this bug faster.
- Write which component is affected. We group our components the same way our
  code is structured so basically:
  component name = dir in top level directory of repository
- Describe how you found this bug and how we can reproduce it. Preferable with
  a minimal test-case scenario. You can paste gist.github.com links for larger
  files
- Provide a clear and concise description of what you expected to happen.
-->

##### Bug report summary

##### OS / Environment (output of `uname -a; command -v sw_vers && sw_vers || grep -Hv "^#" /etc/*release`)

##### Netdata version (ouput of `netdata -V`)

##### Component Name

##### Steps To Reproduce

##### Expected behavior
```

I assume most of the people dont read text between `<!---  -->`

I think we need to add relevant description to every `####` section, like

```
##### section name
<!-- description-->

##### section name
<!-- description-->

...
```

**Comment by prologic** [comment]
> @prologic Should we make a full script to gather relevant details to be joined to the case ? Kinda like an `sosreport` ?

That's what some products like Mikrotik's RouterOS does; you type a command and it generates a "support file".

**Comment by stelfrag** [comment]
There could be a new switch (like netdata -v) that runs a script and produces all the info (as described above)

**Pull request merged**
