### PR TITLE
apps.plugin function add max value on all value columns

### PR DESCRIPTION
**Pull request by ktsaou**
speed up the UI by providing the max value per column at the fields list.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @ktsaou ,

When I compiled your code I got these warnings on `x86_64`:

```sh
mqtt_websockets/src/mqtt_wss_client.c: In function 'http_proxy_connect':
mqtt_websockets/src/mqtt_wss_client.c:565:5: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  565 |     write(client->sockfd, r_buf_ptr, strlen(r_buf_ptr));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mqtt_websockets/src/mqtt_wss_client.c:598:9: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  598 |         write(client->sockfd, r_buf_ptr, strlen(r_buf_ptr));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mqtt_websockets/src/mqtt_wss_client.c:601:5: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  601 |     write(client->sockfd, HTTP_ENDLINE, strlen(HTTP_ENDLINE));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mqtt_websockets/src/mqtt_wss_client.c: In function 'util_clear_pipe':
mqtt_websockets/src/mqtt_wss_client.c:1004:11: warning: ignoring return value of 'read' declared with attribute 'warn_unused_result' [-Wunused-result]
 1004 |     (void)read(fd, throwaway, THROWAWAY_BUF_SIZE);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mqtt_websockets/src/mqtt_wss_client.c: In function 'mqtt_wss_wakeup':
mqtt_websockets/src/mqtt_wss_client.c:997:5: warning: ignoring return value of 'write' declared with attribute 'warn_unused_result' [-Wunused-result]
  997 |     write(client->write_notif_pipe[PIPE_WRITE_END], " ", 1);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c: In function 'apps_plugin_function_processes':
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'LWrites_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4421:25: note: 'LWrites_max' was declared here
 4421 |             LReads_max, LWrites_max
      |                         ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'LReads_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4421:13: note: 'LReads_max' was declared here
 4421 |             LReads_max, LWrites_max
      |             ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'FDs_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4416:70: note: 'FDs_max' was declared here
 4416 |             , TimerFDs_max, SigFDs_max, EvPollFDs_max, OtherFDs_max, FDs_max
      |                                                                      ^~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'OtherFDs_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4416:56: note: 'OtherFDs_max' was declared here
 4416 |             , TimerFDs_max, SigFDs_max, EvPollFDs_max, OtherFDs_max, FDs_max
      |                                                        ^~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'EvPollFDs_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4416:41: note: 'EvPollFDs_max' was declared here
 4416 |             , TimerFDs_max, SigFDs_max, EvPollFDs_max, OtherFDs_max, FDs_max
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'SigFDs_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4416:29: note: 'SigFDs_max' was declared here
 4416 |             , TimerFDs_max, SigFDs_max, EvPollFDs_max, OtherFDs_max, FDs_max
      |                             ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'TimerFDs_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4416:15: note: 'TimerFDs_max' was declared here
 4416 |             , TimerFDs_max, SigFDs_max, EvPollFDs_max, OtherFDs_max, FDs_max
      |               ^~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'EventFDs_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4415:64: note: 'EventFDs_max' was declared here
 4415 |             , Files_max, Pipes_max, Sockets_max, iNotiFDs_max, EventFDs_max
      |                                                                ^~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'iNotiFDs_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4415:50: note: 'iNotiFDs_max' was declared here
 4415 |             , Files_max, Pipes_max, Sockets_max, iNotiFDs_max, EventFDs_max
      |                                                  ^~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'Sockets_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4415:37: note: 'Sockets_max' was declared here
 4415 |             , Files_max, Pipes_max, Sockets_max, iNotiFDs_max, EventFDs_max
      |                                     ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'Pipes_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4415:26: note: 'Pipes_max' was declared here
 4415 |             , Files_max, Pipes_max, Sockets_max, iNotiFDs_max, EventFDs_max
      |                          ^~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'Files_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4415:15: note: 'Files_max' was declared here
 4415 |             , Files_max, Pipes_max, Sockets_max, iNotiFDs_max, EventFDs_max
      |               ^~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'WCalls_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4414:27: note: 'WCalls_max' was declared here
 4414 |             , RCalls_max, WCalls_max
      |                           ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'RCalls_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);   
collectors/apps.plugin/apps_plugin.c:4414:15: note: 'RCalls_max' was declared here
 4414 |             , RCalls_max, WCalls_max
      |               ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'PWrites_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4413:27: note: 'PWrites_max' was declared here
 4413 |             , PReads_max, PWrites_max
      |                           ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'PReads_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4413:15: note: 'PReads_max' was declared here
 4413 |             , PReads_max, PWrites_max
      |               ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'TMajFlt_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4412:40: note: 'TMajFlt_max' was declared here
 4412 |             , MajFlt_max, CMajFlt_max, TMajFlt_max
      |                                        ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'CMajFlt_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4412:27: note: 'CMajFlt_max' was declared here
 4412 |             , MajFlt_max, CMajFlt_max, TMajFlt_max
      |                           ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'MajFlt_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4412:15: note: 'MajFlt_max' was declared here
 4412 |             , MajFlt_max, CMajFlt_max, TMajFlt_max
      |               ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'TMinFlt_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4411:40: note: 'TMinFlt_max' was declared here
 4411 |             , MinFlt_max, CMinFlt_max, TMinFlt_max
      |                                        ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'CMinFlt_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4411:27: note: 'CMinFlt_max' was declared here
 4411 |             , MinFlt_max, CMinFlt_max, TMinFlt_max
      |                           ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'MinFlt_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4411:15: note: 'MinFlt_max' was declared here
 4411 |             , MinFlt_max, CMinFlt_max, TMinFlt_max
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'Uptime_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4410:43: note: 'Uptime_max' was declared here
 4410 |               Processes_max, Threads_max, Uptime_max
      |                                           ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'Threads_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4410:30: note: 'Threads_max' was declared here
 4410 |               Processes_max, Threads_max, Uptime_max
      |                              ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4298:40: warning: 'Processes_max' may be used uninitialized [-Wmaybe-uninitialized]
 4298 |     key ## _max = (rows == 0) ? (_tmp) : MAX(key ## _max, _tmp);                                                \
      |                                        ^
collectors/apps.plugin/apps_plugin.c:4410:15: note: 'Processes_max' was declared here
 4410 |               Processes_max, Threads_max, Uptime_max
      |               ^~~~~~~~~~~~~
In file included from ./daemon/common.h:6,
                 from ./collectors/all.h:6,
                 from collectors/apps.plugin/apps_plugin.c:9:
./libnetdata/libnetdata.h:222:32: warning: 'MemPcnt_max' may be used uninitialized [-Wmaybe-uninitialized]
  222 | #define MAX(a,b) (((a)>(b))?(a):(b))
      |                                ^
collectors/apps.plugin/apps_plugin.c:4406:15: note: 'MemPcnt_max' was declared here
 4406 |             , MemPcnt_max
      |               ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'Swap_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4405:15: note: 'Swap_max' was declared here
 4405 |             , Swap_max
      |               ^~~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'Shared_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4404:15: note: 'Shared_max' was declared here
 4404 |             , Shared_max
      |               ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'RSS_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4403:15: note: 'RSS_max' was declared here
 4403 |             , RSS_max
      |               ^~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'VMSize_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4402:15: note: 'VMSize_max' was declared here
 4402 |             , VMSize_max
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'CPU_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4401:15: note: 'CPU_max' was declared here
 4401 |             , CPU_max
      |               ^~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'CGuestCPU_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4400:15: note: 'CGuestCPU_max' was declared here
 4400 |             , CGuestCPU_max
      |               ^~~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'CSysCPU_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4399:15: note: 'CSysCPU_max' was declared here
 4399 |             , CSysCPU_max
      |               ^~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'CUserCPU_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4398:15: note: 'CUserCPU_max' was declared here
 4398 |             , CUserCPU_max
      |               ^~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'GuestCPU_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4397:15: note: 'GuestCPU_max' was declared here
 4397 |             , GuestCPU_max
      |               ^~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'SysCPU_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4396:15: note: 'SysCPU_max' was declared here
 4396 |             , SysCPU_max
      |               ^~~~~~~~~~
collectors/apps.plugin/apps_plugin.c:4284:7: warning: 'UserCPU_max' may be used uninitialized [-Wmaybe-uninitialized]
 4284 |     if(!isnan((NETDATA_DOUBLE)(max)))                                                                           \
      |       ^
collectors/apps.plugin/apps_plugin.c:4395:15: note: 'UserCPU_max' was declared here
 4395 |               UserCPU_max
      |               ^~~~~~~~~~~
libnetdata/libnetdata.c:34:2: warning: #warning NETDATA_TRACE_ALLOCATIONS ENABLED [-Wcpp]
   34 | #warning NETDATA_TRACE_ALLOCATIONS ENABLED
      |  ^~~~~~~
 OK  ''
```

**Comment by thiagoftsm** [comment]
Except for the warnings, PR is running as expected.

**Comment by ktsaou** [comment]
The warnings are false, but anyway I fixed them.

**Review by thiagoftsm — APPROVED** [review]
API and `plugin` is working as expected. LGTM!

**Pull request merged**
