### PR TITLE
Java-Plugin with JMX module

### LINKED ISSUE #364: JMX collector
JVM based application are widely used so be able to monitor their stats can be very useful

### PR DESCRIPTION
**Pull request by simonnagl**
Integrate project [netdata-plugin-java-daemon ](https://github.com/simonnagl/netdata-plugin-java-daemon) into netdata.

## How to contribute

This is a very huge merge request and I can not spent enough time for this to this to resolve all issues alone quickly. If you want to help just open a pull request at [my netdata fork](https://github.com/simonnagl/netdata/pulls). For feedback/wishes/discussion just comment here or at one of the open issues of the task list.

## Task List

- [x] Move content of  [netdata-plugin-java-daemon ](https://github.com/simonnagl/netdata-plugin-java-daemon) into `java.d`
- [x] Write (auto)make files to install the plugin when java is present
- [x] Run tests and build the plugin with `travis`
-  ~~Optional: Report code coverage to codacy.~~
- [x] Migrate open issues of  [netdata-plugin-java-daemon ](https://github.com/simonnagl/netdata-plugin-java-daemon) to netdata.
- [x] Add documentation to the netdata wiki.
- [ ] Delete  [netdata-plugin-java-daemon ](https://github.com/simonnagl/netdata-plugin-java-daemon)

- [x] #2808 CompositeData support
- [ ] #2790 Use a (shorter) timeout for JMX operations
- [ ] #3047 Monitory new Java Processes
- [ ] #2798 Mark dead java processes obsolete
- [ ] #3046 Authentication support
- [ ] #2807 Health alarms
- [ ] #2806 CPU usage per thread
- [ ] #2792 Optimize collection performance (partial solved)
- [ ] #2791 Configuration option (disable JMX module)
## Open Discussions

- [x] License headers.

netdata-plugin-java-daemon has a license header in every source file as suggested [here](https://www.gnu.org/licenses/gpl-howto.en.html). netdata has not.
@ktsaou Should I keep those headers or remove them?

## Closes
Closes #364

### CODE REVIEW

**Comment by simonnagl** [comment]
Today I moved configuration files and the plugin runner script to the present directories and adapted the makefiles.

There is one job left for automake, but I think I will need some help/instructions how to do this:

- Automake needs to check if we have a java compiler.
- If yes it needs to run `java.d/.mvnw package`
- This will generate `java.d/target/java-plugin.java`
- This file needs to be installed under `/usr/libexec/netdata/java.d/java-plugin.jar`

@ktsaou Can you help or know somebody who can help? Thank you!

**Comment by simonnagl** [comment]
Today I managed to move a step further. I completed these goals:

- Automake integration
- Travis integration

Now running the installer with javac and java installed should enable the java-plugin and autodetect local java processes per default. I invite everybody to test.

Next I will add documentation to the wiki and migrate the issues of netdata-java-plugin-daemon to the `netdata` issue tracker.

Least I want to improve the code a bit and fix some of the issues found by codacy. I will not be able to fix all because some are false positives.

**Comment by ktsaou** [comment]
nice!

Regarding the license headers, of course you can add your name to all your files. netdata does not have its license on all its files, but I think we should add it, so keep yours there.

Regarding `LICENSE-REDISTRIBUTE.md` I suggest to add a section named `key netdata contributors` and add your name there (you can also add the rest if you want, or I'll do it after merging this).

**Comment by simonnagl** [comment]
Today I added basic documentation to the wiki and updated the readme. The links in the wiki may be needed to be updated after merging this. Also I refactored some code to remove some codacy warnings. From my point of view this is now ready to be merged. Migrating the issue and deleting the old repository won't affect this PR.

There are many things to improve but the basic woks and on my few machines it runs stable.

@ktsaou Feel free to review and tell me if you want me to do/improve something before merging this.

If you do not want to merge this into master (for example you want to test it longer or merge when more features are added) I would to suggest to merge it to an new branch at this repo. This enables others to contribute and not getting this PR bigger and bigger.

**Comment by simonnagl** [comment]
Just finished the migration of the issues to `netdata`. I will now stop implementing further until I get some input If you want me to change something in this pull request. Thank you for having the opportunity participating this project!

**Comment by ktsaou** [comment]
@simonnagl I am little bit noob with java (my little experience is on android development).
So, is it possible to provide an example setup for monitoring 1-2 java apps (please suggest the apps too).

**Comment by simonnagl** [comment]
Generally, this plugin provides auto-detection. So, running any java program should appear as a section on the `netdata` dashboard after restarting `netdata`. (Identified by PID)

Some programs I checked (Eclipse, jconsole, tomcat)

It is also possible to configure and name a imx connection. You can test this with http://docs.oracle.com/javase/tutorial/jmx/remote/custom.html. Just run the server.
```
java -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false com.example.Main
```

And add this to property `jmxServers` of `imx.conf`
```
{
     "name": "SimpleServer",
     "serviceUrl": "service:jmx:rmi:///jndi/rmi://:9999/jmxrmi"
}
```

You can now also start the client of the tutorial and monitor the changes of threads/etc on the server.

@ktsaou If you need more help reproducing this please tell me.

PS: Initialization of the connections may tike a while. You may wait some time until you see the JMX sections.

**Comment by ktsaou** [comment]
@simonnagl Atlassian found you: https://bitbucket.org/wkennedy/netdataforatlassian/wiki/Home

**Comment by sebbrandt87** [comment]
anything I could help with, maybe just with a big 👍

**Comment by itn3rd77** [comment]
Is there anything missing apart from lack of time to get this merged?

**Comment by ktsaou** [comment]
@simonnagl we miss you...

**Comment by simonnagl** [comment]
@sebbrandt87, @itn3rd77, thank you for participating.

@ktsaou, sorry, I had some busy time.

Of course the actual state of this plugin is not perfect. These Issues are known:

- https://github.com/firehol/netdata/issues/3047 
- https://github.com/firehol/netdata/issues/3046
- https://github.com/firehol/netdata/issues/2807
- https://github.com/firehol/netdata/issues/2806
- https://github.com/firehol/netdata/issues/2798
- https://github.com/firehol/netdata/issues/2792 (partial solved)
- https://github.com/firehol/netdata/issues/2791
- https://github.com/firehol/netdata/issues/2790

@ktsaou: I think it would be easier for others to push this plugin forward if we could merge this. I can not guarantee any time for this project :(
What about disabling the java plugin per default and merging this? What do you think?

If you do not want this into `netdata` yet I could merge it into my fork of `netdata` and others like @sebbrandt87 could participate there via pull requests. Then when we think it is ready I would open a fresh MR. What do you think?

**Comment by ktsaou** [comment]
Well, you have done a lot of work already.

If we merge it, we will need support - and I am not familiar with this. So, it will stress you a bit.

It is probably better to work off production and then merge it when you believe it is ready for general use.

**Comment by simonnagl** [comment]
Thank you for your feedback. I made the branch of this MR the default branch of my fork. This makes it easier for people to contribute. Second, I updated the initial comment of this MR to keep track of the progress of this MR. I am looking forward for people to join!

**Comment by simonnagl** [comment]
I want to thank @illes here for his/her contribution to this MR.

**Comment by simonnagl** [comment]
I will not be able to work on it myself in the bear feature. If you/somebody wants to work on it I woulf be verry happy to see it growing. Also, I am sure I will be able to help with code reviews.

**Comment by cakrit** [comment]
Thanks @simonnagl. For now, could just verify that I've correctly put all related [issues under the project](https://github.com/netdata/netdata/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+project%3Anetdata%2Fnetdata%2F23)?

**Comment by simonnagl** [comment]
> could just verify that I've correctly put all related issues under the project?

Maybe also these could be relevant:

- #3101 - Cassandra DB
- #2799 MBean array size monitoring
- #2074 Spring Boot Plugin

**Comment by cakrit** [comment]
Thanks. A springboot collector exists now, so I closed that one. The others were added to the project.

**Comment by simonnagl** [comment]
I like how you integrated the go orchestrator. I think the java plugin should go the same way. I want to spend some time to bring this forward.

Are you (@Ferroin @ilyam8 @ktsaou @paulfantom @vlvkobal) willing to provide a repository at `netdata/java-orchestrator`? If not I will integrate the changes from this PR into https://github.com/simonnagl/netdata-plugin-java-daemon and continue development there. With `netdata/java-orchestrator` I may get more feedback from the community.

**Comment by cakrit** [comment]
> Are you willing to provide a repository at `netdata/java-orchestrator`?

We discussed it a bit (basically with @ilyam8) and we don't really want to officially support another language at this point. We're already trying to deprecate the bash and node.js collectors, so that we don't need experts in so many languages. So our suggestion is to keep it as a separate project for now. If the Java orchestrator gets traction and manages to get sufficient contributor involvement, we'll certainly be willing to reconsider. I will ensure we mention it in the `third party collectors` in our official docs of course. Is it ok with you @simonnagl ? We definitely don't want to discourage you, there are more than enough devs out there whose main language is Java, so it could fly.

**Comment by simonnagl** [comment]
This is good for me. I understand your decision. The only reason for doing this plugin in java is JMX. Please leave this open until integrated the improvements from here back. After that I will close this. 

I also will open a issue to discuss if you want me to migrate the open issues relating to the java orchestrator back to my repo. Please leave them open at least until I closed this.

**Comment by simonnagl** [comment]
@illes You contributed some code to this branch. I want to migrate the changes to https://github.com/simonnagl/netdata-plugin-java-daemon. I want to migrate most of your commits and use you (`Illes Solt <illes@gravityrd.com>`) as the author. Is this OK for you?

If you do not want me to move you're contributions or just do want me to do it another way just tell me.

**Comment by cakrit** [comment]
@simonnagl I'd say just do the migration, so we can close this. It's been around long enough.

**Comment by simonnagl** [comment]
The migration is done in https://github.com/simonnagl/netdata-plugin-java-daemon/pull/53. I am closing this now.

@illes I did not migrate the custom plugin loading logic (for now). If you want to do this in my repository just open a pull request for it.

**Pull request closed without merging**
