### PR TITLE
Use llvm's ar and ranlib when compiling with clang

### LINKED ISSUE #13527: [Bug]: netdata v1.36.1 fails to link libJudy correctly with LTO enabled on FreeBSD
### Bug description

Netdata uses plain `ar` to link libJudy, which causes the build to fail due to LTO link errors under FreeBSD[^1][^2].

This can be fixed by setting `AR` to the output of `cc --print-prog-name=llvm-ar`[^3] when compiling with Clang. It has the added benefit of working even when multiple clang/llvm versions are installed.

In theory this should be reproducible under Linux too. Unfortunately I have not been able to test whether it's the case.

references:
[^1]: https://github.com/netdata/netdata/issues/13520
[^2]: https://github.com/netdata/netdata/issues/13522
[^3]: https://bugzilla.mozilla.org/show_bug.cgi?id=1480005 and https://bugzilla.mozilla.org/show_bug.cgi?id=1539280

### Expected behavior

netdata uses llvm-ar to link libJudy when compiling with Clang.

### Steps to reproduce

1.
2.
3.
...

### Installation method

from source

### System info

```shell
FreeBSD localhost 13.1-RELEASE-p1 FreeBSD 13.1-RELEASE-p1 GENERIC amd64
1301000
```

### Netdata build info

```shell
Version: netdata v1.36.1
Configure options:  '--disable-unit-tests' '--disable-cloud' '--disable-plugin-cups' '--enable-dbengine' '--disable-plugin-freeipmi' '--enable-lto' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd13.1' 'build_alias=amd64-portbld-freebsd13.1' 'CC=cc' 'CFLAGS=-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing ' 'LDFLAGS= -Wl,-rpath,/usr/local/lib -fstack-protector-strong ' 'LIBS=' 'CPPFLAGS=-D_WANT_VMMETER' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  ' 'PKG_CONFIG=pkgconf' 'PKG_CONFIG_LIBDIR=/usr/ports/net-mgmt/netdata/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig' 'CPP=cpp'
Install type: custom
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              NO (by user request)
    ACLK Next Generation:       NO
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: NO
    CUPS:                    NO
    EBPF:                    NO
    IPMI:                    NO
    NFACCT:                  NO
    perf:                    NO
    slabinfo:                NO
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: NO
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Fixes #13527 

This PR check for the C compiler vendor, and if it's `clang` sets `ar` and `ranlib` to `llvm-ar` and `llvm-ranlib`. It should fix the linker problem on FreeBSD with clang and lto enabled.

##### Test Plan

Need to cover various compile setups, i.e. a mix of Systems (FreeBSD/Linux) with compilers (clang/gcc) and enabled or disabled LTO.

Compiling on FreeBSD with gcc and LTO enabled, doesn't work. I think it's because `ar` and `ranlib` are not linked to gcc's one (whereas on Linux I believe it does). When installing gcc it includes e.g. `gcc-ar11` but not sure if we need to explicitly set configure to use that...

##### Additional Information

Not a configure expert, so if there is a better way to do it, please let me know!

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by MrZammler** [comment]
> Hello @MrZammler ,
> 
> When I compiled with `clang v14` on Linux I observed a lot warnings [err.txt](https://github.com/netdata/netdata/files/9821129/err.txt). Are you going to address them in another PR?
> 
> I am going to test on FreeBSD now.

Yes, thanks Thiago, we should look at them later. Thank you!

**Comment by thiagoftsm** [comment]
Hello @MrZammler,

On the other hand, on FreeBSD we have the expected results without warnings. I am waiting for other commits to retest. :)

Best regards!

**Review by underhood — APPROVED** [review]

**Comment by vkalintiris** [comment]
FYI, I think this breaks macos builds. After rebasing:

```
cru libjudy.a libnetdata/libjudy/src/JudyCommon/libjudy_a-JudyMalloc.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLByCount.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLCascade.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLCount.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLCreateBranch.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLDecascade.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLDel.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLFirst.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLFreeArray.o libnetdata/libjudy/src/JudyL/libjudy_a-j__udyLGet.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLGet.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLInsArray.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLIns.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLInsertBranch.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLMallocIF.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLMemActive.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLMemUsed.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLNext.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLNextEmpty.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLPrev.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLPrevEmpty.o libnetdata/libjudy/src/JudyHS/libjudy_a-JudyHS.o libjudy_a-JudyLTables.o
make[2]: cru: No such file or directory
make[2]: *** [libjudy.a] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by MrZammler** [comment]
> FYI, I think this breaks macos builds. After rebasing:
> 
> ```
> cru libjudy.a libnetdata/libjudy/src/JudyCommon/libjudy_a-JudyMalloc.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLByCount.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLCascade.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLCount.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLCreateBranch.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLDecascade.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLDel.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLFirst.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLFreeArray.o libnetdata/libjudy/src/JudyL/libjudy_a-j__udyLGet.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLGet.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLInsArray.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLIns.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLInsertBranch.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLMallocIF.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLMemActive.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLMemUsed.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLNext.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLNextEmpty.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLPrev.o libnetdata/libjudy/src/JudyL/libjudy_a-JudyLPrevEmpty.o libnetdata/libjudy/src/JudyHS/libjudy_a-JudyHS.o libjudy_a-JudyLTables.o
> make[2]: cru: No such file or directory
> make[2]: *** [libjudy.a] Error 1
> make[1]: *** [all-recursive] Error 1
> make: *** [all] Error 2
> ```

Yes, didn't test, thanks Vasili... will get a fix for this...

**Pull request merged**
