### PR TITLE
Specify paths to source files for out-of-tree build.

### PR DESCRIPTION
**Pull request by KickerTom**
##### Summary
Out-of-tree builds are good to keep sources clean and easier to work with, and allows multiple builds with different configurations to be done from the same sources without dist-cleaning, e.g. for multiplatform cross-compilation.

Autotools allows to do out-of-tree builds. E.g.:

```
git clone <URL> src
cd src
autoreconf -ivf
cd ..
mkdir build
cd build
../src/configure
make
```

For netdata, this is broken on a few places where other tools (cat, sh) are called. This patch should fix this and allow out-of-tree build capability.

##### Component Name
Build system

##### Test Plan
Tested with both in-tree and out-of-tree builds.

### CODE REVIEW

**Comment by KickerTom** [comment]
Note, the web/gui/dashboard/Makefile.am file claims to be generated by generate-dashboard-makefile.py, but I haven't found this script to update it.

**Comment by ilyam8** [comment]
@KickerTom I think it is [bundle_dashboard.py](https://github.com/netdata/netdata/blob/master/web/gui/bundle_dashboard.py)

**Comment by KickerTom** [comment]
> @KickerTom I think it is [bundle_dashboard.py](https://github.com/netdata/netdata/blob/master/web/gui/bundle_dashboard.py)

You are right, thanks, updated.

**Review by Ferroin — APPROVED** [review]

**Comment by Ferroin** [comment]
@KickerTom Thanks for this PR. This is something that’s been on my list of things to fix for some time now, but I’ve just not had the time to actually sit down and do it.

**Comment by vkalintiris** [comment]
@KickerTom thanks for the PR. It LGTM, do you want to rebase it so that we can approve it and merge it?

**Comment by KickerTom** [comment]
Sorry for the delay. Rebased to latest master.

**Comment by ilyam8** [comment]
@KickerTom, hey 👋 This needs another rebase.

**Comment by KickerTom** [comment]
Rebased again.

**Review by Dim-P — CHANGES_REQUESTED** [review]
Hey @KickerTom , apologies for the delay. I just tested it locally and it looks good to me. Can you please fix the merge conflicts one last time? 

I will prompt the team so we can get this merged asap, so that you don't have to keep rebasing!

**Review by Ferroin — APPROVED** [review]

**Comment by KickerTom** [comment]
Rebased to latest master. Thanks for the support.

**Review by Dim-P — APPROVED** [review]

**Review by Ferroin — APPROVED** [review]

**Pull request merged**
