### PR TITLE
mongodb: ssl connection

### PR DESCRIPTION
**Pull request by ilyam8**
### Summary

Fixes: #5884, #6464

The PR adds ssl connection support to the `mongodb` python collector.

Ref: https://api.mongodb.com/python/current/examples/tls.html#certificate-verification-policy

Following config options were added:

```yaml
  ssl: yes                             # connect to the server using TLS
  ssl_cert_reqs: yes                   # require a certificate from the server when TLS is enabled
  ssl_ca_certs: '/path/to/ca.pem'      # use a specific set of CA certificates
  ssl_crlfile: '/path/to/crl.pem'      # use a certificate revocation lists
  ssl_certfile: '/path/to/client.pem'  # use a client certificate
  ssl_keyfile: '/path/to/key.pem'      # use a specific client certificate key
  ssl_pem_passphrase: 'passphrase'     # use a passphrase to decrypt encrypted private keys
```

##### Component Name
[collectors/python.d.plugin/mongodb](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/mongodb)

##### Additional Information
Module doesnt do any check/validation, it passes all ssl params (which are set) to the [`MongoClient`](https://api.mongodb.com/python/current/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient) class.

Tests:
 - i didnt do any tests myself, @mlyborg will test it (i hope).

### CODE REVIEW

**Comment by ilyam8** [comment]
@mlyborg

Could you test the PR?

**Comment by ilyam8** [comment]
@fmercier-almerys please test the PR too

**Comment by thiagoftsm** [comment]
Hi @ilyam8 ,

I tested your PR now, firstly I used it without the authentication, for this I ran the following steps:

1 - I started the mongodb without authentication:

$ /usr/bin/mongod --dbpath=/var/lib/mongodb --fork --pidfilepath=/var/state/mongodb.pid --logappend --logpath=/var/log/mongodb --nohttpinterface

I configured the mongodb.conf with the following parameters:

uri = mongodb://localhost:27017
database = test
collection = test

And I ran the Python plugin with:

$ /usr/libexec/netdata/plugins.d/python.d.plugin debug trace mongodb
2019-07-31 22:55:24: python.d INFO: plugin[main] : using python v2
2019-07-31 22:55:24: python.d INFO: plugin[main] : starting setup
2019-07-31 22:55:24: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-07-31 22:55:24: python.d INFO: plugin[main] : config found, loading config '/etc/netdata/python.d.conf'
2019-07-31 22:55:24: python.d INFO: plugin[main] : config successfully loaded
2019-07-31 22:55:24: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2019-07-31 22:55:24: python.d INFO: plugin[checker] : starting...
2019-07-31 22:55:24: python.d INFO: plugin[checker] : mongodb : checking
2019-07-31 22:55:25: python.d INFO: plugin[checker] : mongodb : source successfully loaded
2019-07-31 22:55:25: python.d INFO: plugin[checker] : mongodb : found config file '/usr/lib/netdata/conf.d/python.d/mongodb.conf'
2019-07-31 22:55:25: python.d INFO: plugin[checker] : mongodb : created 1 job(s) from the config
2019-07-31 22:55:25: python.d DEBUG: mongodb[local] : creating connection, connection params: ['host', 'port', 'serverselectiontimeoutms']
2019-07-31 22:55:25: python.d DEBUG: mongodb[local] : skip authenticating, user and password are not set
2019-07-31 22:55:25: python.d INFO: plugin[checker] : mongodb[local] : check successful
2019-07-31 22:55:25: python.d INFO: plugin[checker] : terminating...
2019-07-31 22:55:25: python.d INFO: plugin[main] : stopping checker process
2019-07-31 22:55:25: python.d INFO: plugin[main] : setup complete, 1 active module(s) : '['mongodb']'
2019-07-31 22:55:25: python.d INFO: plugin[main] : mongodb : created 1 job(s)
2019-07-31 22:55:25: python.d INFO: plugin[main] : mongodb[local] : init successful
2019-07-31 22:55:25: python.d DEBUG: mongodb[local] : creating connection, connection params: ['host', 'port', 'serverselectiontimeoutms']
2019-07-31 22:55:25: python.d DEBUG: mongodb[local] : skip authenticating, user and password are not set
2019-07-31 22:55:25: python.d INFO: plugin[main] : mongodb[local] : check successful
CHART netdata.runtime_mongodb_local '' 'Execution time for mongodb_local' 'ms' 'python.d' netdata.pythond_runtime line 145000 1
DIMENSION run_time 'run time' absolute 1 1

2019-07-31 22:55:25: python.d INFO: plugin[main] : mongodb[local] : started in thread
2019-07-31 22:55:25: python.d DEBUG: mongodb[local] : started, update frequency: 1
CHART mongodb_local.locks_database '' 'Database lock. Number of times the lock was acquired in the specified mode' 'locks' 'locks metrics' 'mongodb.locks_database' stacked 60015 1 '' 'python.d.plugin' 'mongodb'
DIMENSION 'Database_R' 'shared' incremental 1 1 ' '
DIMENSION 'Database_W' 'exclusive' incremental 1 1 ' '
DIMENSION 'Database_r' 'intent_shared' incremental 1 1 ' '
DIMENSION 'Database_w' 'intent_exclusive' incremental 1 1 ' '

BEGIN mongodb_local.locks_database 0
SET 'Database_R' = 66
SET 'Database_W' = 8
SET 'Database_r' = 251
SET 'Database_w' = 2
END

CHART mongodb_local.record_moves '' 'Number of times documents had to be moved on-disk' 'number' 'resource saturation' 'mongodb.record_moves' line 60010 1 '' 'python.d.plugin' 'mongodb'
DIMENSION 'moves' 'moves' incremental 1 1 ' '

BEGIN mongodb_local.record_moves 0
SET 'moves' = 0
END

CHART mongodb_local.admin_dbstats '' 'admin: size of all documents, indexes, extents' 'KB' 'storage size metrics' 'mongodb.dbstats' line 60023 1 '' 'python.d.plugin' 'mongodb'
DIMENSION 'admin_dataSize' 'documents' absolute 1 1024 ' '
DIMENSION 'admin_indexSize' 'indexes' absolute 1 1024 ' '
DIMENSION 'admin_storageSize' 'extents' absolute 1 1024 ' '

BEGIN mongodb_local.admin_dbstats 0
SET 'admin_dataSize' = 756
SET 'admin_indexSize' = 98304
SET 'admin_storageSize' = 65536
END

2 - for the second test I enabled the authentication with SSL and I ran mongodb with the following parameters:

/usr/bin/mongod --dbpath=/var/lib/mongodb --fork --pidfilepath=/var/state/mongodb.pid --logappend --logpath=/var/log/mongodb --nohttpinterface --auth --sslMode requireSSL --sslPEMKeyFile /etc/mongodb/mongodb.pem --sslAllowInvalidCertificates

And I set the following parameters inside the file /usr/lib/netdata/conf.d/python.d/mongodb.conf:
    name : 'local'
    host : '127.0.0.1'
    port : 27017
    ssl: yes                             # connect to the server using TLS
    ssl_cert_reqs: yes                   # require a certificate from the server when TLS is enabled
    ssl_ca_certs: '/etc/mongodb/cert.pem'      # use a specific set of CA certificates

After this I ran:

$ /usr/libexec/netdata/plugins.d/python.d.plugin debug trace mongodb
2019-07-31 23:27:03: python.d INFO: plugin[main] : using python v2
2019-07-31 23:27:03: python.d INFO: plugin[main] : starting setup
2019-07-31 23:27:03: python.d INFO: plugin[main] : checking for config in ['/etc/netdata', '/usr/lib/netdata/conf.d']
2019-07-31 23:27:03: python.d INFO: plugin[main] : config found, loading config '/etc/netdata/python.d.conf'
2019-07-31 23:27:03: python.d INFO: plugin[main] : config successfully loaded
2019-07-31 23:27:03: python.d INFO: plugin[main] : starting checker process (1 module(s) to check)
2019-07-31 23:27:03: python.d INFO: plugin[checker] : starting...
2019-07-31 23:27:03: python.d INFO: plugin[checker] : mongodb : checking
2019-07-31 23:27:03: python.d INFO: plugin[checker] : mongodb : source successfully loaded
2019-07-31 23:27:03: python.d INFO: plugin[checker] : mongodb : found config file '/usr/lib/netdata/conf.d/python.d/mongodb.conf'
2019-07-31 23:27:03: python.d INFO: plugin[checker] : mongodb : created 1 job(s) from the config
2019-07-31 23:27:03: python.d DEBUG: mongodb[local] : creating connection, connection params: ['host', 'port', 'serverselectiontimeoutms', 'ssl', 'ssl_ca_certs', 'ssl_cert_reqs']
2019-07-31 23:27:03: python.d DEBUG: mongodb[local] : skip authenticating, user and password are not set
2019-07-31 23:27:04: python.d ERROR: mongodb[local] : hostname '127.0.0.1' doesn't match u'www.example.com'
2019-07-31 23:27:04: python.d INFO: plugin[checker] : mongodb[local] : check failed, skipping the job
2019-07-31 23:27:04: python.d INFO: plugin[checker] : mongodb : all jobs failed, skipping module
2019-07-31 23:27:04: python.d INFO: plugin[checker] : terminating...
2019-07-31 23:27:04: python.d INFO: plugin[main] : stopping checker process
2019-07-31 23:27:04: python.d INFO: plugin[main] : no modules to run

I used self-signed certificate to test. Please check the PR #6524, there I described the steps that I used to work with self-signed certificate. The mongodb accepts this only case I give two parameters for it on the client side, and one of the parameters is a PEM file with certificate and key together. I could not find this in your PR.

**Comment by ilyam8** [comment]
>  The mongodb accepts this only case I give two parameters for it on the client side, and one of the parameters is a PEM file with certificate and key together. I could not find this in your PR.

all options from the [`TLS/SSL and PyMongo` page](https://api.mongodb.com/python/current/examples/tls.html#basic-configuration) were added

thx for testing :heart:

**Comment by vlvkobal** [comment]
Tested it with a MongoDB server running in a container:
```
docker run --name mongo-ssl -p 27017:27017 -v /etc/mongodb.pem:/etc/mongodb.pem mongo --sslMode requireSSL --sslPEMKeyFile /etc/mongodb.pem
```
It works with the following parameters for the mongodb python plugin
```
local:
    name : 'local'
    host : '127.0.0.1'
    port : 27017
    ssl: yes
    ssl_cert_reqs: no
```

**Comment by fmercier-almerys** [comment]
> 
> 
> @fmercier-almerys please test the PR too

Hi

I tested with the conf bellow :
`
mongo_repo:
  name: 'mongo-db'
  host: 'apim-mongo1-dev'
  port: 27017
  authdb: 'mongo-dev'
  user: 'admin'
  pass: 'toto'
  ssl: yes
  ssl_cert_reqs: yes
  ssl_ca_certs: '/etc/ssl/apim-mongo1-dev/apim-mongo1-dev.pem'
  ssl_certfile: '/etc/ssl/apim-mongo1-dev/apim-mongo1-dev.crt'
  ssl_keyfile: '/etc/ssl/apim-mongo1-dev/apim-mongo1-dev.key'

`
Mongo 3.2.22 and it does not work

**Comment by ilyam8** [comment]
> 2019-09-16 10:15:14: python.d DEBUG: mongodb[local] : creating connection, connection params: ['host', 'port', 'ssl', 'ssl_ca_certs', 'ssl_cert_reqs', 'ssl_certfile', 'ssl_keyfile']
Enter PEM pass phrase:
2019-09-16 10:15:17: python.d DEBUG: mongodb[local] : authenticating, user: admin, password: almerys0
2019-09-16 10:15:17: python.d ERROR: mongodb[local] : command SON([('authenticate', 1), ('user', u'admin'), ('nonce', u'cfb8591dc9627b30'), ('key', u'4aeddc1073cd14eaf1727eeb12a29d13')]) failed: auth failed

Not a specialist, but it looks that connection was created but auth failed. And

> Enter PEM pass phrase:

doesnt look good to me. Maybe you need to provide `ssl_pem_passphrase`.

**Comment by thiagoftsm** [comment]
Hi @fmercier-almerys ,

I remember when we were testing the integration with MongoDB,  we used only one PEM file that had both key and certificate. Depending of your MongoDB version, it will be necessary to do some adjusts, please, see the official documentation https://docs.mongodb.com/manual/tutorial/configure-ssl/ . The information there can help you to configure your side.

**Comment by fmercier-almerys** [comment]
Yes When I run without passphrase it prompts it and it works but if I add this to the mongodb.conf file the debug mode return : 

2019-09-16 12:09:35: python.d ERROR: mongodb[repo] : Unknown option ssl_pem_passphrase

**Comment by ilyam8** [comment]
I checked [python-pymongo changelog](https://api.mongodb.com/python/current/changelog.html):

 - `ssl_pem_passphrase` was added in [3.3](https://api.mongodb.com/python/current/changelog.html#changes-in-version-3-3)
 - `ssl_pem_passphrase` was deprecated in https://api.mongodb.com/python/current/changelog.html#changes-in-version-3-9-0 (in favor of `tlsCertificateKeyFilePassword`)

**Comment by ilyam8** [comment]
> When I run without passphrase it prompts it and it works

Wait, what do you mean by `it works`? what works?

**Comment by ilyam8** [comment]
btw, all those ssl options were changes in 3.9 😢 	

> ssl_cert_reqs has been deprecated in favor of tlsAllowInvalidCertificates. Instead of ssl.CERT_NONE, ssl.CERT_OPTIONAL and ssl.CERT_REQUIRED, the new option expects a boolean value - True is equivalent to ssl.CERT_NONE, while False is equivalent to ssl.CERT_REQUIRED.

>ssl_match_hostname has been deprecated in favor of tlsAllowInvalidHostnames.

> ssl_ca_certs has been deprecated in favor of tlsCAFile.

> ssl_certfile has been deprecated in favor of tlsCertificateKeyFile.

> ssl_pem_passphrase has been deprecated in favor of tlsCertificateKeyFilePassword.

https://api.mongodb.com/python/current/changelog.html#changes-in-version-3-9-0

**Comment by fmercier-almerys** [comment]
Yes I unencrypted my key file and now I works :-) 
Not really safe but Mongo is now monitored

In case of a cluster it can only monitor master so how can you specify a list of servers in the mongodb.conf ?

**Comment by ilyam8** [comment]
> Yes I unencrypted my key file and now I works :-)

Upgrading python-pymongo to 3.3+ (but not to 3.9) will do, you will be able to use  `ssl_pem_passphrase`

**Comment by ilyam8** [comment]
> In case of a cluster it can only monitor master so how can you specify a list of servers in the mongodb.conf ?

you can add any number of jobs to the module configuration file

```yaml
local:
    host : '127.0.0.1'
    port : 27017

remote1:
    host : '10.0.0.1'
    port : 27017

remote2:
    host : '10.0.0.2'
    port : 27017
```

**Comment by fmercier-almerys** [comment]
> ssl_pem_passphrase

not rely I upgrade to pymongo 3.9.0 and I have : Support for ssl_pem_passphrase requires python 2.7.9+ (pypy 2.5.1+) or 3.3+

I need also upgrade to python 2.7.9+

**Comment by fmercier-almerys** [comment]
Last question how do you can check mongo server is UP . When I stop it metrics are not collected but there is no status DOWN/UP

**Pull request merged**
