### PR TITLE
rename "Pid" to "PID" in functions

### PR DESCRIPTION
**Pull request by andrewm4894**
##### Summary

I think it would be better for the case of "Pid" if we stuck to generally expected convention of "PID"

image

some more reasoning in here: https://netdata-cloud.slack.com/archives/C04A4T32C4R/p1671027277570239

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @andrewm4894 ,

You still need to change code, please, take a look on this output:

```sh
bash-5.2$ grep -r PPid collectors/apps.plugin/*
collectors/apps.plugin/apps_plugin.c:                                       "\n         \"columns\":[ \"PPid\" ]"
collectors/apps.plugin/apps_plugin.c:                                       "\n         \"columns\":[ \"Category\", \"PPid\" ]"
collectors/apps.plugin/apps_plugin.c:                                       "\n         \"columns\":[ \"User\", \"PPid\" ]"
collectors/apps.plugin/apps_plugin.c:                                       "\n         \"columns\":[ \"Group\", \"PPid\" ]"
grep: collectors/apps.plugin/apps_plugin.o: binary file matches
bash-5.2$ grep -r PPID collectors/apps.plugin/*
collectors/apps.plugin/apps_plugin.c:        add_table_field(wb, "PPID", "Parent Process ID", false, "integer", NULL, NAN, "ascending", true, false, false, "Pid", "count_unique", false);
grep: collectors/apps.plugin/apps_plugin.o: binary file matches
```

I also think that we need to change more code, because when I had local tests I still have lower case for some PPid:

```sh
"group_by": {
     "pid": {
         "name":"Process Tree by PID",
         "columns":[ "PPid" ]
     },
     "category": {
         "name":"Process Tree by Category",
         "columns":[ "Category", "PPid" ]
     },
     "user": {
         "name":"Process Tree by User",
         "columns":[ "User", "PPid" ]
     },
     "group": {
         "name":"Process Tree by Group",
         "columns":[ "Group", "PPid" ]
     }
   },
```

You can check this accessing http://localhost:19999/api/v1/function?function=processes .

Best regards!

**Comment by ilyam8** [comment]
@andrewm4894 use `git grep`

```cmd
$ git grep -n PPid
collectors/apps.plugin/apps_plugin.c:4600:        add_table_field(wb, "PPid", "Parent Process ID", false, "integer", NULL, NAN, "ascending", true, false, false, "Pid", "count_unique", false);
collectors/apps.plugin/apps_plugin.c:4751:                                       "\n         \"columns\":[ \"PPid\" ]"
collectors/apps.plugin/apps_plugin.c:4755:                                       "\n         \"columns\":[ \"Category\", \"PPid\" ]"
collectors/apps.plugin/apps_plugin.c:4759:                                       "\n         \"columns\":[ \"User\", \"PPid\" ]"
collectors/apps.plugin/apps_plugin.c:4763:                                       "\n         \"columns\":[ \"Group\", \"PPid\" ]"
``

**Comment by ktsaou** [comment]
PPid needs to be renamed 3-4 more times, at the the `group_by` section, a few lines below.

**Comment by andrewm4894** [comment]
Think this should be ready now

**Review by ilyam8 — APPROVED** [review]

**Review by ktsaou — APPROVED** [review]

**Pull request merged**
