### PR TITLE
Fix(snmp): fix parse oidname and santilize dimension name

### PR DESCRIPTION
**Pull request by Ehekatl**
##### Summary

this is a quickfix to make oidname replacement working in node.d snmp plugin.

##### Component Name

node.d snmp plugin

### CODE REVIEW

**Comment by ktsaou** [comment]
@Ehekatl thank you!

This change seems simple, but could you please describe the motivation behind it? Why do we need this? What was the problem you solved?

**Comment by Ehekatl** [comment]
@ktsaou before this change, use oidname in dimension will parse as float and result in `NaN` if oidname it's not a number,  I also sanitize the value to replace space/special character as underscore, make sure the dimension name is valid.

**Comment by Ehekatl** [comment]
actually, I didn't get why there is case that `net_snmp.ObjectType.OctetString` need parse as float...

**Comment by ktsaou** [comment]
oh, I see.

The reason for parsing strings as float: https://github.com/netdata/netdata/issues/1236

I guess you are trying to solve this: https://github.com/netdata/netdata/issues/4512

@agross can you check if this PR fixes your issue?

**Comment by agross** [comment]
@ktsaou Yes, it fixes the issue with `oidname` being treated as a "string parsed as float".

**Comment by ktsaou** [comment]
perfect!
So, I am merging it.

**Comment by ktsaou** [comment]
Thank you @Ehekatl 	!

**Pull request merged**
