### PR TITLE
smartd_log refactor plus SCSI support

### PR DESCRIPTION
**Pull request by l2isbad**
##### Summary

attempt to Fix: #4285

- scsi support
- change grouping/processing attributes (https://github.com/netdata/netdata/issues/4285#issuecomment-425654443)

##### Component Name

:snake: `smartd_log` :snake: 

##### Additional Information
todo:
- [x] attribute value preprocessing (like https://github.com/netdata/netdata/issues/4285#issuecomment-428556760)
- [x] readme update
- [ ] alarms
- [x] hadle log rotation

problems:
- netdata doesn't suppport deletion of dimension deletion in runtime

### CODE REVIEW

**Comment by Ferroin** [comment]
Overall LGTM, though I haven't had a chance yet to look in-depth at it.

@l2isbad I just posted a Python snippet in https://github.com/netdata/netdata/issues/4285#issuecomment-434668314 that should be a reasonable approximation of the logic used by smartctl to decode the raw temperature values.  Not sure if you want to use it or not, but it's there if you want it.

**Comment by l2isbad** [comment]
> temperature, minimum, maximum, and over-temperature count

Why do we need all this? What should we do with minimum and maximum? how to chart it?

**Comment by Ferroin** [comment]
I don't think they need to be charted, but the data is there, so I see no reason not to expose it in some way.  If we don't want that data at all though, then we don't need to parse the raw values either.

**Comment by l2isbad** [comment]
It's not `want/don't want`. I don't know how to use it, `min/max` is not important data for me, but i may be wrong.

My proposal is to use `194` normalized for temperature. We can rewrite it later if the need arises. I will add `NOTE` and your code snippet as comments.

**Comment by Ferroin** [comment]
Sounds good to me.  I can see uses for the data, but can't think of any way that it makes sense to expose it through Netdata (chart variables come to mind, but that only makes sense if we do attributes as dimensions or one attribute per chart).

**Comment by l2isbad** [comment]
@Ferroin It seems that some attrs have to be decoded depending on disk type/vendor. [Example](https://github.com/netdata/netdata/issues/4285#issuecomment-434531577) `Power On Hours`. 

So if you have the opportunity to test this PR in your env please do

**Comment by Ferroin** [comment]
@l2isbad I plan to do so, but it may be this weekend before I get the chance to do it properly.  I don't know how interesting the results may be though, I don't have any particularly exotic disks.

**Comment by Ferroin** [comment]
Error rates are more useful than total error counts, both for creating alarms, and for actually seeing device health.  Put simply, on a healthy disk, they should not change almost ever.  On a disk that's starting to fail, they will be consistently high.  In contrast, for total counts, a non-zero value just tells you an error happened at some point, not that they are continuing to happen. 

Given this, I think incremental is correct here, provided that the charts are annotated in such a way that it's obvious that they're displaying the error rate, not the total error count.

**Comment by l2isbad** [comment]
> On a disk that's starting to fail, they will be consistently high. 

If the behaviour is 
> On a disk that's starting to fail, they will be consistently high

 then yes, `incremental` is OK.

**Comment by Ferroin** [comment]
> If the behaviour is
>
>> On a disk that's starting to fail, they will be consistently high
>
> then yes, incremental is OK.

Put simply, if the disk failure isn't indicated by high error rates, then it won't realistically be indicated by high error counts either.

**Comment by l2isbad** [comment]
@ScrumpyJack 
please test, this version supports SCSI devices

**Comment by l2isbad** [comment]
ok, i am waiting for some feedback from you @ScrumpyJack

@Ferroin please review when you have time

**Comment by Ferroin** [comment]
LGTM so far, though I still haven't had a chance to test it (it looks like I might get a chance this evening, but if not I will get it tested this weekend).  Are the two remaining items in the 'todo' list planned for this PR, or is the intent to work on them longer term?

**Comment by l2isbad** [comment]
btw @Ferroin you have time please look at 
https://github.com/netdata/netdata/issues/4285#issuecomment-425654443
one more time

I added only attrs with `family`. We might miss something.

**Comment by Ferroin** [comment]
> About the alarms. I hope for your help. Feel free to add them (you can add commits to this PR)

I'll try and look into getting some written up.  It's going to be interesting figuring out what makes sense for some of them though.  There's a lot of people who run unhealthy disks until they die instead of replacing them early, and it would be good not to annoy them, but if the thresholds are too high, the alarms just won't be useful.

**Comment by l2isbad** [comment]
>  There's a lot of people who run unhealthy disks until they die

Haha, it's me

**Comment by Ferroin** [comment]
Regarding attributes:, ATA attributes 1, 7, and 206 might be worth providing graphs for.  While their raw values are vendor-specific in format, their normalized values are reasonably consistent across vendors, they start at 100, and decrease towards 0 as the error rates go up.

**Comment by l2isbad** [comment]
>  ATA attributes 1, 7, and 206

Please add missing values to the table and i will add right after that

**Comment by Ferroin** [comment]
I've updated the table.

**Comment by l2isbad** [comment]
@Ferroin We can add alarms in a separate PR. Please review/approve.

**Comment by Ferroin** [comment]
@l2isbad Sorry about the delayed review, I meant to review this last week but got sidetracked by other things.

**Pull request merged**
