### PR TITLE
Make CMake options for platform-dependent plugins depend on being build for a supported platform.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

A large number of our external data collection plugins are Linux-specific, and a handful are dependent on specific UNIX-like platforms. This PR ensures that configuration options for these plugins do not show up if we are not building for a platform they support instead of failing configuration later on or silently disabling them.

No functional changes other than not being able to enable these options on unsupported platforms.

##### Test Plan

CI passes on this PR.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
@Ferroin ,

Please, rebase the PR.
It is working as expected on Linux, in few hours I will take a look on FreeBSD.

Best regards!

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Comment by thiagoftsm** [comment]
@Ferroin ,

I understand we also want to avoid installing these files on FreeBSD:

```
configure_file(src/collectors/cgroups.plugin/cgroup-network-helper.sh.in
               src/collectors/cgroups.plugin/cgroup-network-helper.sh @ONLY)
install(PROGRAMS
        ${CMAKE_BINARY_DIR}/src/collectors/cgroups.plugin/cgroup-network-helper.sh
        COMPONENT netdata
        DESTINATION usr/libexec/netdata/plugins.d)

configure_file(src/collectors/cgroups.plugin/cgroup-name.sh.in
               src/collectors/cgroups.plugin/cgroup-name.sh @ONLY)
```

Best regards!

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Review by thiagoftsm — DISMISSED** [review]
PR is working as expected, on:

- Slackware Current
- FreeBSD 14
- Windows 11

LGTM!

**Comment by Ferroin** [comment]
Rebased to resolve merge conflict.

**Review by thiagoftsm — APPROVED** [review]
I repeated [these](https://github.com/netdata/netdata/pull/17517#pullrequestreview-2064214765) tests and everything continue working. LGTM!

**Pull request merged**
