### PR TITLE
Fix upgrade path from v1.17.1 to v1.18.x for deb packages

### LINKED ISSUE #7067: Debian/Ubuntu stable package is broken
#### Bug report summary

After upgrading my netdata from 1.17 to 1.18 today, I've got the same error as the #6925 when trying to open netdata in my browser:
`ERROR 101: Cannot load jQuery: https://netdata.hostname/lib/jquery-2.2.4.min.js`

##### OS / Environment

Ubuntu 18.04 LTS, using stable packagecloud branch of netdata.

##### Netdata version (ouput of `netdata -V`)

`netdata v1.18.0`

##### Component Name

netdata/packaging/deb

##### Steps To Reproduce

Upgrade netdata from 1.17 to 1.18 using stable packagecloud branch.

##### Expected behavior

Web UI should keep its working state.

##### Temporary solution

Got www directory path from full config:
```
[global]
	# I'm not overriding the default value, so can't tell if did it change since the 1.17?
	# web files directory = /var/lib/netdata/www
```
It had some stuff in the root directory (`/var/lib/netdata/www`) but not in its subdirectories like `images` or `lib`.

At first I was about to just copy the files like in #6925 by doing `cp -a /usr/share/netdata/www/* /var/lib/netdata/www/`, but after checking the #6930 I've decided to remove empty directories:
```
rm -rf /var/lib/netdata/www/.well-known
rm -rf /var/lib/netdata/www/css
rm -rf /var/lib/netdata/www/fonts
rm -rf /var/lib/netdata/www/images
rm -rf /var/lib/netdata/www/lib
rm -rf /var/lib/netdata/www/static
```
To replace them with the next proper symlinks:
```
ln -s /usr/share/netdata/www/.well-known /var/lib/netdata/www/.well-known
ln -s /usr/share/netdata/www/css         /var/lib/netdata/www/css
ln -s /usr/share/netdata/www/fonts       /var/lib/netdata/www/fonts
ln -s /usr/share/netdata/www/images      /var/lib/netdata/www/images
ln -s /usr/share/netdata/www/lib         /var/lib/netdata/www/lib
ln -s /usr/share/netdata/www/static      /var/lib/netdata/www/static
```

That resolved the issue for me.

P.S.: Same actions in one-liner by @borisdigital https://github.com/netdata/netdata/issues/6925#issuecomment-541026780:
`for dn in ".well-known" css fonts images lib static; do rmdir /var/lib/netdata/www/${dn}; ln -s /usr/share/netdata/www/${dn} /var/lib/netdata/www/${dn}; done`

P.P.S.: Posting this issue because it seems like the closed state of #6925 does mute notifications for developers.

### PR DESCRIPTION
**Pull request by knatsakis**
##### Summary
Fix upgrade path from v1.17.1 to v1.18.x for deb packages

##### Component Name
contrib/debian

##### Additional Information
Fixes #7067

### CODE REVIEW

**Comment by knatsakis** [comment]
@cakrit 'Pre-Depends' is needed to ensure the availability of the `
￼ dpkg-maintscript-helper dir_to_symlink` command. (for reference: [man dpkg-maintscript-helper](http://manpages.ubuntu.com/manpages/bionic/man1/dpkg-maintscript-helper.1.html))

**Comment by cakrit** [comment]
> @cakrit 'Pre-Depends' is needed to ensure the availability of the ` ￼ dpkg-maintscript-helper dir_to_symlink` command. (for reference: [man dpkg-maintscript-helper](http://manpages.ubuntu.com/manpages/bionic/man1/dpkg-maintscript-helper.1.html))

Ok, got it, so the 1.17.14 looking like a netdata release is a coincidence. I was wondering about the .14! :)

**Comment by knatsakis** [comment]
Regarding the 1.18.1~ version, it's meaning is this:
The version of the netdata package, where the change of dir-to-symlink occurred.

No, we won't have to change it in later releases.
This is so that dpkg knows, for which upgrade paths it has to take special care and do the dir-to-symlink change 

Quoting from the man page:

>  prior-version
>              Defines  the  latest  version  of  the  package  whose  upgrade  should trigger the
>              operation. It is  important  to  calculate  prior-version  correctly  so  that  the
>              operations  are  correctly  performed  even  if the user rebuilt the package with a
>              local version. If prior-version is empty or omitted, then the operation is tried on
>              every  upgrade  (note:  it's safer to give the version and have the operation tried
>              only once).
>
>              If the conffile has not  been  shipped  for  several  versions,  and  you  are  now
>              modifying  the  maintainer  scripts  to  clean  up the obsolete file, prior-version
>              should be based on the version of the package that you are now preparing,  not  the
>              first  version  of  the package that lacked the conffile. This applies to all other
>              actions in the same way.
>
>              For example, for a conffile removed in version 2.0-1 of  a  package,  prior-version
>              should  be  set  to  2.0-1~. This will cause the conffile to be removed even if the
>              user rebuilt the previous version 1.0-1 as 1.0-1local1. Or a  package  switching  a
>              path  from  a symlink (shipped in version 1.0-1) to a directory (shipped in version
>              2.0-1), but only performing the actual switch in the maintainer scripts in  version
>              3.0-1, should set prior-version to 3.0-1~.

**Comment by knatsakis** [comment]
.deb packages for testing have been deployed to [https://packagecloud.io/netdata/netdata-devel](netdata-devel) with version v1.18.1.

@thiagoftsm please test the following paths:
- clean v1.18.1 installation
- apt-get purge
- apt-get remove
- upgrade from v1.17.1
- upgrade from v1.18.0
- clean v1.17.1 installation, upgrade to v1.18.0, upgrade to v1.18.1

Thanks!

**Pull request merged**
