### PR TITLE
eBPF (memory, NV, basis for functions)

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes https://github.com/netdata/netdata/issues/13904
Fixes https://github.com/netdata/netdata/issues/13751
Fixes https://github.com/netdata/netdata/issues/13922
It also address issues reported [here](https://community.netdata.cloud/t/ebpf-network-connection-chart-is-not-what-im-expecting/3500/5), but the work with network viewer/functions are not completely ready. We are few step away to reach what is necessary to have the features. I am keeping the final steps for another PR.

Screenshot_20221220_163451

##### Test Plan

1. Compile this branch on a host.
2. Adjust your `/etc/netdata/ebpf.d.conf` to monitor connections for a specific host:
```sh
[ebpf programs]
   network connections = yes
[network connections]
    maximum dimensions = 50
    resolve hostnames = no
    resolve service names = no
    ips = 192.168.121.123
```

##### Additional Information
This PR was tested on : 

| Distribution | kernel version |
|-------------------|-----------------------|
| Slackware current | 5.19.17 |
| Arch Linux | 6.0.12-arch1-1 |
|Ubuntu 22.04 | 5.15.0-33-generic |
|Alma 9 | 5.14.0-162.6.1.el9_1.x86_64 |
| Debian 11 | 5.10.149-2 |
|Oracle 8.6 | 5.4.17-2136.314.6.3.el8uek.x86_64 | 
| Alma 8.6 | 4.18.0-425.3.1.el8.x86_64 |
| Ubuntu 18.04 | 4.15.0-180-generic |
| Slackware current | 4.14.290 |
| CentOS 7.9 | 3.10.0-1160.81.1.el7.x86_64 | 

<details> <summary>For users: How does this change affect me?</summary>
Describe the PR affects users: 
- Which area of Netdata is affected by the change? ebpf.plugiin
- Can they see the change or is it an under the hood? If they can see it, where? Only if they are running eBPF on RH family or enable by hand a feature disabled by default.
- How is the user impacted by the change? A more stable plugin on cited environments.
- What are there any benefits of the change? Basis for a new feature.
</details>

### CODE REVIEW

**Review by Dim-P — COMMENTED** [review]
Hey @thiagoftsm . First of all, I cannot reproduce any of the linked issues, building latest `master` or this PR (some of them are really random from what it seems, I guess depending on the kernel version?). However, when enabling network connections:
```
[ebpf programs]
   network connections = yes
```
to test this PR and running `ab -n 1000 -c 100 http://192.168.1.151/test` to generate some outbound network traffic (`192.168.1.151` is another VM), the `ebpf.plugin` ended up consuming 200MB of memory and the `eBPF` section wasn't showing on the dashboard. Are the logs of any help?
```
2022-12-22 23:47:42: ebpf.plugin INFO  : MAIN : (2107@collectors/ebpf.plug:update_listen_t): The network viewer is monitoring inbound connections for port 22
2022-12-22 23:47:42: ebpf.plugin INFO  : MAIN : (2107@collectors/ebpf.plug:update_listen_t): The network viewer is monitoring inbound connections for port 19999
2022-12-22 23:47:42: ebpf.plugin INFO  : MAIN : (2107@collectors/ebpf.plug:update_listen_t): The network viewer is monitoring inbound connections for port 8125
2022-12-22 23:47:42: ebpf.plugin INFO  : MAIN : (2107@collectors/ebpf.plug:update_listen_t): The network viewer is monitoring inbound connections for port 53
2022-12-22 23:47:42: ebpf.plugin INFO  : MAIN : (2107@collectors/ebpf.plug:update_listen_t): The network viewer is monitoring inbound connections for port 5355
2022-12-22 23:47:42: ebpf.plugin INFO  : MAIN : (2107@collectors/ebpf.plug:update_listen_t): The network viewer is monitoring inbound connections for port 9090
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF SOCKET : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57671
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF SOCKET : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57671 to EBPF SOCKET
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF PROCESS : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57670
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF SYNC : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57672
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF SYNC : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57672 to EBPF SYNC
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF PROCESS : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57670 to EBPF PROCESS
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF FD : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57677
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF FD : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57677 to EBPF FD
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF HARDIRQ : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57678
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF HARDIRQ : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57678 to EBPF HARDIRQ
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF VFS : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57673
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF VFS : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57673 to EBPF VFS
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF SOFTIRQ : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57679
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF SOFTIRQ : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57679 to EBPF SOFTIRQ
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF SOCKET : (1834@collectors/ebpf.plug:fill_last_nv_di): Last inbound dimension added: ID = 24, IP = OTHER, NAME = other,
 DIM1 = other:ALL_recv, DIM2 = other:ALL_sent, DIM3 = other:ALL
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF SOCKET : (1834@collectors/ebpf.plug:fill_last_nv_di): Last outbound dimension added: ID = 24, IP = OTHER, NAME = other
, DIM1 = ALL:other_recv, DIM2 = ALL:other_sent, DIM3 = ALL:other
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF MOUNT : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57674
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF MOUNT : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57674 to EBPF MOUNT
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF OOMKILL : (0191@libnetdata/threads/t:thread_start   ): thread created with task id 57680
2022-12-22 23:47:42: ebpf.plugin INFO  : EBPF OOMKILL : (0153@libnetdata/threads/t:thread_set_name): set name of thread 57680 to EBPF OOMKILL
```

**Comment by thiagoftsm** [comment]
Hello @Dim-P ,

Thank you for your report, I will take a look on this tomorrow. It looks like that when we only enable network connections, it is not setting any network to monitor, this is the motive you only have `ALL` as dimension.

Best regards!

**Comment by thiagoftsm** [comment]
Hello @Dim-P ,

The issue was completely fixed with latest commits.

Best regards!

**Review by underhood — APPROVED** [review]

**Comment by Dim-P** [comment]
Hi @thiagoftsm . I don't see the previous issues anymore, but now I am having these errors in the logs:
```
2023-01-02 23:21:35: ebpf.plugin INFO  : EBPF SOCKET READ : (1923@collectors/ebpf.plug:store_socket_in): New outbound dimension added: ID = 1, IP = 192.168.42.129, NAME = 192.168.42.129, DIM1 = TCP:192.168.42.129_recv, DIM2 = TCP:192.168.42.129_sent, DIM3 = TCP:192.168.42.129
2023-01-02 23:21:36: ebpf.plugin ERROR : EBPF SOCKET READ : (1918@collectors/ebpf.plug:store_socket_in): Internal error, cannot insert the AVL tree. (errno 2, No such file or directory)
2023-01-02 23:21:36: ebpf.plugin INFO  : EBPF SOCKET READ : (1923@collectors/ebpf.plug:store_socket_in): New outbound dimension added: ID = 2, IP = 192.168.42.129, NAME = 192.168.42.129, DIM1 = TCP:192.168.42.129_recv, DIM2 = TCP:192.168.42.129_sent, DIM3 = TCP:192.168.42.129
2023-01-02 23:21:37: ebpf.plugin ERROR : EBPF SOCKET READ : (1918@collectors/ebpf.plug:store_socket_in): Internal error, cannot insert the AVL tree. (errno 2, No such file or directory)
2023-01-02 23:21:37: ebpf.plugin INFO  : EBPF SOCKET READ : (1923@collectors/ebpf.plug:store_socket_in): New outbound dimension added: ID = 3, IP = 192.168.42.129, NAME = 192.168.42.129, DIM1 = TCP:192.168.42.129_recv, DIM2 = TCP:192.168.42.129_sent, DIM3 = TCP:192.168.42.129
2023-01-02 23:21:37: ebpf.plugin ERROR : EBPF SOCKET READ : (1918@collectors/ebpf.plug:store_socket_in): Internal error, cannot insert the AVL tree. (errno 2, No such file or directory)
```

This is with just enabling:
```
[ebpf programs]
   network connections = yes
```
and not setting a specific IP to monitor.

**Comment by thiagoftsm** [comment]
Hello @Dim-P ,

We can merge with this specific error, because I will discard AVL and convert them to dictionary in a new PR that will also bring functions.

Best Regards!

**Review by Dim-P — APPROVED** [review]

**Pull request merged**
