### PR TITLE
Fix crash on FreeBSD due to do_dev_cpu_temperature stack corruption

### LINKED ISSUE #7010: NetData is crashing on FreeBSD plugin during startup
##### Bug report summary
NetData is crashing on FreeBSD plugin during startup

##### OS / Environment
```
# uname -a
FreeBSD bunny 11.3-RELEASE-p3 FreeBSD 11.3-RELEASE-p3 #0: Mon Aug 19 21:08:43 UTC 2019     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

##### Netdata version (ouput of `netdata -V`)
```
# netdata -V
netdata v1.17.1
```
##### Component Name

FreeBSD plugin

##### Steps To Reproduce

- Enable FreeBSD plugin in the config
- Run netdata

##### Expected behavior

- Netdata is up and running.

##### LLDB debug

```
lldb /usr/local/sbin/netdata
(lldb) target create "/usr/local/sbin/netdata"
Current executable set to '/usr/local/sbin/netdata' (x86_64).
(lldb) run -D
Process 21691 launching
Process 21691 launched: '/usr/local/sbin/netdata' (x86_64)
Process 21691 stopped
* thread #2, name = 'PLUGIN[freebsd]', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x0000000000000000
error: Bad address
(lldb) bt all
  thread #1, name = 'netdata'
    frame #0: 0x0000000802328aba
    frame #1: 0x000000080222d127
    frame #2: 0x0000000000429659 netdata`custom_popene(command="/usr/local/libexec/netdata/plugins.d/anonymous-statistics.sh 'START' '-' '-'", pidptr=0x00007fffffffe7ac, env=0x0000000802c62000) at popen.c:71:13
    frame #3: 0x0000000000429565 netdata`mypopen(command="/usr/local/libexec/netdata/plugins.d/anonymous-statistics.sh 'START' '-' '-'", pidptr=0x00007fffffffe7ac) at popen.c:128:12
    frame #4: 0x000000000040c26a netdata`send_statistics(action="START", action_result="-", action_data="-") at main.c:769:16
    frame #5: 0x000000000040f6d6 netdata`main(argc=2, argv=0x00007fffffffeb38) at main.c:1234:5
    frame #6: 0x000000000040766d netdata`_start + 141
* thread #2, name = 'PLUGIN[freebsd]', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x000000000047d09e netdata`rrdset_done_interpolate(st=0x00000008008f6000, update_every_ut=1000000, last_stored_ut=1570452102000000, next_store_ut=1570452103000000, last_collect_ut=1570452102500000, now_collect_ut=1570452103214315, store_this_entry='\x01', storage_flags=16777216) at rrdset.c:1082:17
    frame #2: 0x000000000047c38e netdata`rrdset_done(st=0x00000008008f6000) at rrdset.c:1590:5
    frame #3: 0x00000000004a7885 netdata`do_kern_cp_time(update_every=1, dt=1041563) at freebsd_sysctl.c:360:13
    frame #4: 0x00000000004a61c4 netdata`freebsd_main(ptr=0x00000000006eee80) at plugin_freebsd.c:117:28
    frame #5: 0x000000000043602f netdata`thread_start(ptr=0x0000000802d5fe50) at threads.c:153:19
    frame #6: 0x0000000801fc1036
  thread #3, name = 'PLUGIN[idlejitt'
    frame #0: 0x00000008022c7aca
    frame #1: 0x000000000041e5fe netdata`sleep_usec(usec=20000) at clocks.c:178:12
    frame #2: 0x0000000000462fb1 netdata`cpuidlejitter_main(ptr=0x00000000006eeeb8) at plugin_idlejitter.c:58:13
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x0000000802d5fe80) at threads.c:153:19
    frame #4: 0x0000000801fc1036
  thread #4, name = 'STATSD'
    frame #0: 0x00000008022c7aca
    frame #1: 0x000000000041e5fe netdata`sleep_usec(usec=997964) at clocks.c:178:12
    frame #2: 0x000000000041e476 netdata`heartbeat_next(hb=0x00007fffdfbfbc80, tick=1000000) at clocks.c:134:9
    frame #3: 0x000000000049654b netdata`statsd_main(ptr=0x00000000006eeef0) at statsd.c:2463:24
    frame #4: 0x000000000043602f netdata`thread_start(ptr=0x0000000802d5feb0) at threads.c:153:19
    frame #5: 0x0000000801fc1036
  thread #5, name = 'WEB_SERVER[stat'
    frame #0: 0x00000008022d9a7a
    frame #1: 0x0000000000431d6f netdata`poll_events(sockets=0x00000000006fa140, add_callback=(netdata`web_server_add_callback at static-threaded.c:140), del_callback=(netdata`web_server_del_callback at static-threaded.c:222), rcv_callback=(netdata`web_server_rcv_callback at static-threaded.c:243), snd_callback=(netdata`web_server_snd_callback at static-threaded.c:300), tmr_callback=(netdata`web_server_tmr_callback at static-threaded.c:320), access_list=0x0000000802d5f910, data=0x0000000000000000, tcp_request_timeout_seconds=60, tcp_idle_timeout_seconds=3600, timer_milliseconds=1000, timer_data=0x0000000803611000, max_tcp_sockets=29431) at socket.c:1591:18
    frame #2: 0x00000000004a463b netdata`socket_listen_main_static_threaded_worker(ptr=0x0000000803611000) at static-threaded.c:389:13
    frame #3: 0x00000000004a576e netdata`socket_listen_main_static_threaded(ptr=0x00000000006eef60) at static-threaded.c:497:13
    frame #4: 0x000000000043602f netdata`thread_start(ptr=0x0000000802d5ff10) at threads.c:153:19
    frame #5: 0x0000000801fc1036
  thread #6, name = 'PLUGINSD'
    frame #0: 0x00000008022c7aca
    frame #1: 0x000000080224c16b
    frame #2: 0x00000000004678ba netdata`pluginsd_main(ptr=0x00000000006eefd0) at plugins_d.c:873:9
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x0000000802d5ff40) at threads.c:153:19
    frame #4: 0x0000000801fc1036
  thread #7, name = 'HEALTH'
    frame #0: 0x00000008022c7aca
    frame #1: 0x000000000041e5fe netdata`sleep_usec(usec=10000000) at clocks.c:178:12
    frame #2: 0x0000000000457c63 netdata`health_main(ptr=0x00000000006ef008) at health.c:940:13
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x0000000802d5ff70) at threads.c:153:19
    frame #4: 0x0000000801fc1036
  thread #8, name = 'PLUGINSD[fping]'
    frame #0: 0x0000000802328aba
    frame #1: 0x000000080222d127
    frame #2: 0x0000000000429659 netdata`custom_popene(command="exec /usr/local/libexec/netdata/plugins.d/fping.plugin 1 ", pidptr=0x000000080381f404, env=0x0000000802c62000) at popen.c:71:13
    frame #3: 0x0000000000429565 netdata`mypopen(command="exec /usr/local/libexec/netdata/plugins.d/fping.plugin 1 ", pidptr=0x000000080381f404) at popen.c:128:12
    frame #4: 0x0000000000466850 netdata`pluginsd_worker_thread(arg=0x000000080381e000) at plugins_d.c:732:20
    frame #5: 0x000000000043602f netdata`thread_start(ptr=0x000000080382d000) at threads.c:153:19
    frame #6: 0x0000000801fc1036
  thread #9, name = 'PLUGINSD[charts'
    frame #0: 0x0000000802328aba
    frame #1: 0x000000080222d127
    frame #2: 0x0000000000429659 netdata`custom_popene(command="exec /usr/local/libexec/netdata/plugins.d/charts.d.plugin 1 ", pidptr=0x0000000803820c04, env=0x0000000802c62000) at popen.c:71:13
    frame #3: 0x0000000000429565 netdata`mypopen(command="exec /usr/local/libexec/netdata/plugins.d/charts.d.plugin 1 ", pidptr=0x0000000803820c04) at popen.c:128:12
    frame #4: 0x0000000000466850 netdata`pluginsd_worker_thread(arg=0x000000080381f800) at plugins_d.c:732:20
    frame #5: 0x000000000043602f netdata`thread_start(ptr=0x000000080382d030) at threads.c:153:19
    frame #6: 0x0000000801fc1036
  thread #10, name = 'PLUGINSD[python'
    frame #0: 0x0000000802328aba
    frame #1: 0x000000080222d127
    frame #2: 0x0000000000429659 netdata`custom_popene(command="exec /usr/local/libexec/netdata/plugins.d/python.d.plugin 1 ", pidptr=0x0000000803822404, env=0x0000000802c62000) at popen.c:71:13
    frame #3: 0x0000000000429565 netdata`mypopen(command="exec /usr/local/libexec/netdata/plugins.d/python.d.plugin 1 ", pidptr=0x0000000803822404) at popen.c:128:12
    frame #4: 0x0000000000466850 netdata`pluginsd_worker_thread(arg=0x0000000803821000) at plugins_d.c:732:20
    frame #5: 0x000000000043602f netdata`thread_start(ptr=0x000000080382d060) at threads.c:153:19
    frame #6: 0x0000000801fc1036
  thread #11, name = 'PLUGINSD[freeip'
    frame #0: 0x0000000802328aba
    frame #1: 0x000000080222d127
    frame #2: 0x0000000000429659 netdata`custom_popene(command="exec /usr/local/libexec/netdata/plugins.d/freeipmi.plugin 1 ignore 202,203", pidptr=0x0000000803823c04, env=0x0000000802c62000) at popen.c:71:13
    frame #3: 0x0000000000429565 netdata`mypopen(command="exec /usr/local/libexec/netdata/plugins.d/freeipmi.plugin 1 ignore 202,203", pidptr=0x0000000803823c04) at popen.c:128:12
    frame #4: 0x0000000000466850 netdata`pluginsd_worker_thread(arg=0x0000000803822800) at plugins_d.c:732:20
    frame #5: 0x000000000043602f netdata`thread_start(ptr=0x000000080382d090) at threads.c:153:19
    frame #6: 0x0000000801fc1036
  thread #12, name = 'PLUGINSD[apps]'
    frame #0: 0x0000000802328aba
    frame #1: 0x000000080222d127
    frame #2: 0x0000000000429659 netdata`custom_popene(command="exec /usr/local/libexec/netdata/plugins.d/apps.plugin 1 ", pidptr=0x0000000803825404, env=0x0000000802c62000) at popen.c:71:13
    frame #3: 0x0000000000429565 netdata`mypopen(command="exec /usr/local/libexec/netdata/plugins.d/apps.plugin 1 ", pidptr=0x0000000803825404) at popen.c:128:12
    frame #4: 0x0000000000466850 netdata`pluginsd_worker_thread(arg=0x0000000803824000) at plugins_d.c:732:20
    frame #5: 0x000000000043602f netdata`thread_start(ptr=0x000000080382d0c0) at threads.c:153:19
    frame #6: 0x0000000801fc1036
  thread #13, name = 'PLUGINSD[node.d'
    frame #0: 0x0000000802328aba
    frame #1: 0x000000080222d127
    frame #2: 0x0000000000429659 netdata`custom_popene(command="exec /usr/local/libexec/netdata/plugins.d/node.d.plugin 1 ", pidptr=0x0000000803826c04, env=0x0000000802c62000) at popen.c:71:13
    frame #3: 0x0000000000429565 netdata`mypopen(command="exec /usr/local/libexec/netdata/plugins.d/node.d.plugin 1 ", pidptr=0x0000000803826c04) at popen.c:128:12
    frame #4: 0x0000000000466850 netdata`pluginsd_worker_thread(arg=0x0000000803825800) at plugins_d.c:732:20
    frame #5: 0x000000000043602f netdata`thread_start(ptr=0x000000080382d0f0) at threads.c:153:19
    frame #6: 0x0000000801fc1036
  thread #14, name = 'PLUGINSD[ioping'
    frame #0: 0x0000000802328aba
    frame #1: 0x000000080222d127
    frame #2: 0x0000000000429659 netdata`custom_popene(command="exec /usr/local/libexec/netdata/plugins.d/ioping.plugin 1 ", pidptr=0x0000000803828404, env=0x0000000802c62000) at popen.c:71:13
    frame #3: 0x0000000000429565 netdata`mypopen(command="exec /usr/local/libexec/netdata/plugins.d/ioping.plugin 1 ", pidptr=0x0000000803828404) at popen.c:128:12
    frame #4: 0x0000000000466850 netdata`pluginsd_worker_thread(arg=0x0000000803827000) at plugins_d.c:732:20
    frame #5: 0x000000000043602f netdata`thread_start(ptr=0x000000080382d150) at threads.c:153:19
    frame #6: 0x0000000801fc1036
  thread #15, name = 'STATSD_COLLECTO'
    frame #0: 0x00000008022d9a7a
    frame #1: 0x0000000000431d6f netdata`poll_events(sockets=0x00000000006f9b10, add_callback=(netdata`statsd_add_callback at statsd.c:781), del_callback=(netdata`statsd_del_callback at statsd.c:797), rcv_callback=(netdata`statsd_rcv_callback at statsd.c:818), snd_callback=(netdata`statsd_snd_callback at statsd.c:951), tmr_callback=(netdata`statsd_timer_callback at statsd.c:959), access_list=0x0000000000000000, data=0x0000000804a0e000, tcp_request_timeout_seconds=0, tcp_idle_timeout_seconds=600, timer_milliseconds=1000, timer_data=0x0000000803446000, max_tcp_sockets=176591) at socket.c:1591:18
    frame #2: 0x0000000000493ff3 netdata`statsd_collector_thread(ptr=0x0000000803446000) at statsd.c:1011:5
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x00000008034111b0) at threads.c:153:19
    frame #4: 0x0000000801fc1036
  thread #16, name = 'WEB_SERVER[stat'
    frame #0: 0x00000008022d9a7a
    frame #1: 0x0000000000431d6f netdata`poll_events(sockets=0x00000000006fa140, add_callback=(netdata`web_server_add_callback at static-threaded.c:140), del_callback=(netdata`web_server_del_callback at static-threaded.c:222), rcv_callback=(netdata`web_server_rcv_callback at static-threaded.c:243), snd_callback=(netdata`web_server_snd_callback at static-threaded.c:300), tmr_callback=(netdata`web_server_tmr_callback at static-threaded.c:320), access_list=0x0000000802d5f910, data=0x0000000000000000, tcp_request_timeout_seconds=60, tcp_idle_timeout_seconds=3600, timer_milliseconds=1000, timer_data=0x0000000803611050, max_tcp_sockets=29431) at socket.c:1591:18
    frame #2: 0x00000000004a463b netdata`socket_listen_main_static_threaded_worker(ptr=0x0000000803611050) at static-threaded.c:389:13
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x0000000803613000) at threads.c:153:19
    frame #4: 0x0000000801fc1036
  thread #17, name = 'WEB_SERVER[stat'
    frame #0: 0x00000008022d9a7a
    frame #1: 0x0000000000431d6f netdata`poll_events(sockets=0x00000000006fa140, add_callback=(netdata`web_server_add_callback at static-threaded.c:140), del_callback=(netdata`web_server_del_callback at static-threaded.c:222), rcv_callback=(netdata`web_server_rcv_callback at static-threaded.c:243), snd_callback=(netdata`web_server_snd_callback at static-threaded.c:300), tmr_callback=(netdata`web_server_tmr_callback at static-threaded.c:320), access_list=0x0000000802d5f910, data=0x0000000000000000, tcp_request_timeout_seconds=60, tcp_idle_timeout_seconds=3600, timer_milliseconds=1000, timer_data=0x00000008036110a0, max_tcp_sockets=29431) at socket.c:1591:18
    frame #2: 0x00000000004a463b netdata`socket_listen_main_static_threaded_worker(ptr=0x00000008036110a0) at static-threaded.c:389:13
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x0000000803613030) at threads.c:153:19
    frame #4: 0x0000000801fc1036
  thread #18, name = 'WEB_SERVER[stat'
    frame #0: 0x00000008022d9a7a
    frame #1: 0x0000000000431d6f netdata`poll_events(sockets=0x00000000006fa140, add_callback=(netdata`web_server_add_callback at static-threaded.c:140), del_callback=(netdata`web_server_del_callback at static-threaded.c:222), rcv_callback=(netdata`web_server_rcv_callback at static-threaded.c:243), snd_callback=(netdata`web_server_snd_callback at static-threaded.c:300), tmr_callback=(netdata`web_server_tmr_callback at static-threaded.c:320), access_list=0x0000000802d5f910, data=0x0000000000000000, tcp_request_timeout_seconds=60, tcp_idle_timeout_seconds=3600, timer_milliseconds=1000, timer_data=0x00000008036110f0, max_tcp_sockets=29431) at socket.c:1591:18
    frame #2: 0x00000000004a463b netdata`socket_listen_main_static_threaded_worker(ptr=0x00000008036110f0) at static-threaded.c:389:13
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x0000000803613060) at threads.c:153:19
    frame #4: 0x0000000801fc1036
  thread #19, name = 'WEB_SERVER[stat'
    frame #0: 0x00000008022d9a7a
    frame #1: 0x0000000000431d6f netdata`poll_events(sockets=0x00000000006fa140, add_callback=(netdata`web_server_add_callback at static-threaded.c:140), del_callback=(netdata`web_server_del_callback at static-threaded.c:222), rcv_callback=(netdata`web_server_rcv_callback at static-threaded.c:243), snd_callback=(netdata`web_server_snd_callback at static-threaded.c:300), tmr_callback=(netdata`web_server_tmr_callback at static-threaded.c:320), access_list=0x0000000802d5f910, data=0x0000000000000000, tcp_request_timeout_seconds=60, tcp_idle_timeout_seconds=3600, timer_milliseconds=1000, timer_data=0x0000000803611140, max_tcp_sockets=29431) at socket.c:1591:18
    frame #2: 0x00000000004a463b netdata`socket_listen_main_static_threaded_worker(ptr=0x0000000803611140) at static-threaded.c:389:13
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x0000000803613090) at threads.c:153:19
    frame #4: 0x0000000801fc1036
  thread #20, name = 'WEB_SERVER[stat'
    frame #0: 0x00000008022d9a7a
    frame #1: 0x0000000000431d6f netdata`poll_events(sockets=0x00000000006fa140, add_callback=(netdata`web_server_add_callback at static-threaded.c:140), del_callback=(netdata`web_server_del_callback at static-threaded.c:222), rcv_callback=(netdata`web_server_rcv_callback at static-threaded.c:243), snd_callback=(netdata`web_server_snd_callback at static-threaded.c:300), tmr_callback=(netdata`web_server_tmr_callback at static-threaded.c:320), access_list=0x0000000802d5f910, data=0x0000000000000000, tcp_request_timeout_seconds=60, tcp_idle_timeout_seconds=3600, timer_milliseconds=1000, timer_data=0x0000000803611190, max_tcp_sockets=29431) at socket.c:1591:18
    frame #2: 0x00000000004a463b netdata`socket_listen_main_static_threaded_worker(ptr=0x0000000803611190) at static-threaded.c:389:13
    frame #3: 0x000000000043602f netdata`thread_start(ptr=0x00000008036130c0) at threads.c:153:19
    frame #4: 0x0000000801fc1036
(lldb) frame select 2
frame #2: 0x000000000047c38e netdata`rrdset_done(st=0x00000008008f6000) at rrdset.c:1590:5
   1587	    }
   1588	#endif
   1589
-> 1590	    rrdset_done_interpolate(st
   1591	            , update_every_ut
   1592	            , last_stored_ut
   1593	            , next_store_ut
(lldb) frame variable
(RRDSET *) st = 0x00000008008f6000
(RRDDIM *) rd = 0x0000000000000000
(char) store_this_entry = '\x01'
(char) first_entry = '\0'
(usec_t) last_collect_ut = 1570452102500000
(usec_t) now_collect_ut = 1570452103214315
(usec_t) last_stored_ut = 1570452102000000
(usec_t) next_store_ut = 1570452103000000
(usec_t) update_every_ut = 1000000
(int) dimensions = 5
(uint32_t) storage_flags = 16777216
(time_t) now = 1570452103

(lldb) frame select 1
frame #1: 0x000000000047d09e netdata`rrdset_done_interpolate(st=0x00000008008f6000, update_every_ut=1000000, last_stored_ut=1570452102000000, next_store_ut=1570452103000000, last_collect_ut=1570452102500000, now_collect_ut=1570452103214315, store_this_entry='\x01', storage_flags=16777216) at rrdset.c:1082:17
   1079	            }
   1080
   1081	            if(likely(rd->updated && rd->collections_counter > 1 && iterations < st->gap_when_lost_iterations_above)) {
-> 1082	                rd->state->collect_ops.store_metric(rd, next_store_ut, pack_storage_number(new_value, storage_flags));
   1083	//                rd->values[current_entry] = pack_storage_number(new_value, storage_flags );
   1084	                rd->last_stored_value = new_value;
   1085
(lldb) frame variable
(RRDSET *) st = 0x00000008008f6000
(usec_t) update_every_ut = 1000000
(usec_t) last_stored_ut = 1570452102000000
(usec_t) next_store_ut = 1570452103000000
(usec_t) last_collect_ut = 1570452102500000
(usec_t) now_collect_ut = 1570452103214315
(char) store_this_entry = '\x01'
(uint32_t) storage_flags = 16777216
(RRDDIM *) rd = 0x0000000805ff8000
(size_t) stored_entries = 0
(usec_t) first_ut = 1570452102000000
(usec_t) last_ut = 1570452103000000
(ssize_t) iterations = 1
(size_t) counter = 0
(long) current_entry = 0
(calculated_number) new_value = 2.86396181384248210027
```

### PR DESCRIPTION
**Pull request by samm-git**
##### Summary

fixes #7010

Fix for the issue #7010. I am not 100% sure if it is valid, but i made it in accordance with other plugins in the freebsd collector code. Please review. For me it fix crashe and valgrind report.

##### Component Name

FreeBSD plugin

##### Additional Information
See #7010 and [valgrind report](https://github.com/netdata/netdata/issues/7010#issuecomment-539354446)

### CODE REVIEW

**Comment by vlvkobal** [comment]
It looks like
```
memset(&mib[old_number_of_cpus * 4], 0, sizeof(RRDDIM) * (number_of_cpus - old_number_of_cpus));
```
is causing the crash.

The problem is that if we delete this line, we will have a problem here:
```
int getsysctl_simple(const char *name, int *mib, size_t miblen, void *ptr, size_t len) {
    size_t nlen = len;

    if (unlikely(!mib[0]))
        if (unlikely(getsysctl_mib(name, mib, miblen))
```
and the mib will never be set.

The question is, what's wrong with the `dev.cpu.*.temperature` mib on your machine?

What do you see in the `dev.cpu.*.temperature` chart when `kern.cp_time = no`?

**Comment by samm-git** [comment]
@vlvkobal i see temp. graph with my patch, it works as expected: 
Screenshot 2019-10-08 at 10 25 27


This is my sysctl output:

```
# sysctl -a | grep temperature
dev.cpu.15.temperature: 32.0C
dev.cpu.14.temperature: 32.0C
dev.cpu.13.temperature: 28.0C
dev.cpu.12.temperature: 28.0C
dev.cpu.11.temperature: 39.0C
dev.cpu.10.temperature: 39.0C
dev.cpu.9.temperature: 36.0C
dev.cpu.8.temperature: 36.0C
dev.cpu.7.temperature: 32.0C
dev.cpu.6.temperature: 32.0C
dev.cpu.5.temperature: 33.0C
dev.cpu.4.temperature: 33.0C
dev.cpu.3.temperature: 32.0C
dev.cpu.2.temperature: 32.0C
dev.cpu.1.temperature: 28.0C
dev.cpu.0.temperature: 28.0C
```

**Comment by vlvkobal** [comment]
It looks like a valid result. What if you set `dev.cpu.temperature = no` and `kern.cp_time = yes`? Does Netdata work?

**Comment by samm-git** [comment]
@vlvkobal yes, it works in that case. This is how i found that problem is unrelated to `cp_time` which is +- copypaste of the other functions

**Comment by samm-git** [comment]
@vlvkobal but i see what you mean my PR is not really useful as it is already done 3 lines above, so its kind of noop. However, memset here is broken and causing crash

**Comment by vlvkobal** [comment]
Ok. Just to be sure. If you delete
```
        if (unlikely(number_of_cpus > old_number_of_cpus))
            memset(&mib[old_number_of_cpus * 4], 0, sizeof(RRDDIM) * (number_of_cpus - old_number_of_cpus));
```
from the original code and don't add anything else, does Netdata work? Do you still see correct data in the `cpu.temperature` chart?

**Comment by samm-git** [comment]
Yes, just checked, it works as expected in that case:

```diff
diff --git a/collectors/freebsd.plugin/freebsd_sysctl.c b/collectors/freebsd.plugin/freebsd_sysctl.c
index 402813f..3f15513 100644
--- a/collectors/freebsd.plugin/freebsd_sysctl.c
+++ b/collectors/freebsd.plugin/freebsd_sysctl.c
@@ -469,8 +469,6 @@ int do_dev_cpu_temperature(int update_every, usec_t dt) {
     if (unlikely(number_of_cpus != old_number_of_cpus)) {
         pcpu_temperature = reallocz(pcpu_temperature, sizeof(int) * number_of_cpus);
         mib = reallocz(mib, sizeof(int) * number_of_cpus * 4);
-        if (unlikely(number_of_cpus > old_number_of_cpus))
-            memset(&mib[old_number_of_cpus * 4], 0, sizeof(RRDDIM) * (number_of_cpus - old_number_of_cpus));
     }
     for (i = 0; i < number_of_cpus; i++) {
         if (unlikely(!(mib[i * 4])))
```

Screenshot 2019-10-08 at 10 49 01

**Comment by vlvkobal** [comment]
Hm... What does `sizeof(RRDDIM)` do in an operation with mib? Please try to change it to `4`.

**Comment by samm-git** [comment]
@vlvkobal yes, looks like to be a weird copypaste. With `4` it works fine

**Comment by samm-git** [comment]
@vlvkobal btw, it perfectly explains why we see 0x00 in the stack as frame 0 address. Memset overrides stack and next function call gets jmp to 0x00 instead of actual address.

**Comment by vlvkobal** [comment]
Thank you very much, @samm-git! Good job 👍. Please finish your PR.

**Comment by vlvkobal** [comment]
We use spaces for indentation, not tabs.

**Comment by samm-git** [comment]
@vlvkobal sorry, my editor gets crazy for some reason. Fixed in old good vim :)

I squashed commit, i hope it is good now

**Comment by vlvkobal** [comment]
Yes, it's OK. Let's wait until the checks are complete.

**Comment by thiagoftsm** [comment]
Thank you very much @samm-git !

**Pull request merged**
