### PR TITLE
[WIP] add matrix network health notifications

### PR DESCRIPTION
**Pull request by infl00p**
##### Summary
Hello friends,
I've added a small change to allow health notifications to be sent to a matrix network homeserver.

##### Component Name
Mofified files in health/notifications
alarm-notify.sh.in
health_alarm_notify.conf

Added files in health/notifications
matrix/Makefile.inc
matrix/README.md

##### Additional Information
WIP because:
Matrix network is rather new, documentation on the msg types is lacking.
Not implemented E2E encrypted notifications

### CODE REVIEW

**Comment by binaryplease** [comment]
Any progress on this? Matrix-notifications would be great to have, as a properly configured matrix-bridge allows passing these to a bunch of other protocols

**Comment by binaryplease** [comment]
@infl00p I send you a pull request to your fork, that should make the travis check pass. 
@cakrit In case you don't want to wait, my fork (of his fork) is here: https://github.com/binaryplease/netdata

**Comment by binaryplease** [comment]
> Thanks @binaryplease
> I suggest you do a new PR if @infl00p doesn't respond this week.

I added a new PR as I see no activity on the original one and would like to use this feature

**Comment by cakrit** [comment]
The new PR is #5741, closing this one.

**Pull request closed without merging**
