### PR TITLE
Refactoring dashboard.js, splitting monolithic file into multiple source files.

### PR DESCRIPTION
**Pull request by gmosx**
Refactoring work tracked by issues #4461 and #4479.
Still, work in progress.

### CODE REVIEW

**Comment by gmosx** [comment]
Codacy should ignore files in `web/gui/src`. @paulfantom can you help here?

**Comment by paulfantom** [comment]
Why should it ignore those files? Aren't those files written by us?

**Comment by ktsaou** [comment]
> Why should it ignore those files? Aren't those files written by us?

Until we do better, he plans to provide `dashboard.js` in parts and combined.

LGTM and codacy complain because the parts are not aware of the full thing and several referenced are broken.

So, since he also pushes the combined one, he suggests to only check the combined one to avoid all this mess.

Of course, the right way would be to check the parts. But this may mean that users installing netdata from source will have to install additional packages for combining it properly (webpack or something similar).

The Makefiles have already been updated to re-create the combined one from the parts (via a simple `cat`). So, this may lead to discrepancies and/or errors if for any reason the parts and the combined one are not in sync.

A probably better way could be to revert the makefiles so that they ignore the parts (define them as `noinst_nodist_DATA`), and use git hooks to combine the file properly (using whatever tool required, for ideas check https://github.com/netdata/netdata/issues/4497), when any of its parts is modified. This way we will be sure that the right combined file is submitted. If it is not, the parts will be just ignored (not used by the installer).

For sure, requiring from the users to install webpack, minify, uglify, etc is not an option. So, this has to be done either by a bot or at commit time and checked by CI.

**Comment by paulfantom** [comment]
> So, this has to be done either by a bot or at commit time and checked by CI.

Bot shouldn't commit code as this might lead to unexpected results in the future.

**Comment by paulfantom** [comment]
Also from what I see this will mean that we are shipping duplicated code which I personally don't like. Especially when build system is already able to create combined file from partial ones.

> Until we do better, he plans to provide dashboard.js in parts and combined.

When will this "better" happen?

Here is a PR with updated codacy config: #4515

**Comment by ktsaou** [comment]
> Also from what I see this will mean that we are shipping duplicated code which I personally don't like.

This is common for javascript libraries. Most ship a `combined.js` and a `combined.min.js`. Otherwise, the users would need the toolchain to combine it and minify it.

- An example doing this is https://github.com/bernii/gauge.js - check the `dist` folder.
- An example not doing this is https://github.com/danvk/dygraphs - you have to run `npm install` and `npm build` to generate it. Check https://github.com/danvk/dygraphs/blob/master/package.json to understand what this requires from users to build it.

> When will this "better" happen?

I guess this needs some more work by @gmosx to split it in modules and provide imports/exports for everything.

The "better" way could be:

1. have a script combine it
2. run the script from git hooks - ideally only when any of the split files is altered
3. run the same script at travis and break/stop if the combined file is not the same with the one committed.

**Comment by paulfantom** [comment]
> run the script from git hooks

git hooks aren't portable and they need to be manually attached. This causes higher bar of entry for new developers.

**Comment by ktsaou** [comment]
> git hooks aren't portable and they need to be manually attached. This causes higher bar of entry for new developers.

So, what do you suggest?

**Comment by paulfantom** [comment]
Since
> Makefiles have already been updated to re-create the combined one from the parts

Then it seems like we don't need to include combined file in repository. As we already have a script which combines it. Then just add a simple test which could be run later in CI and remove combined file from repository.

**Comment by ktsaou** [comment]
> Then it seems like we don't need to include combined file in repository. As we already have a script which combines it. Then just add a simple test which could be run later in CI and remove combined file from repository.

You probably missed something.

Today, merging it is a simple `cat`. But LGTM gives hundreds of errors on the parts.

If we split it properly (for LGTM not to complain), then a toolchain is required to merge it. It is unacceptable to request from our users that install netdata from source to have this toolchain on their systems.

So, we will never ship just the parts of it.
We will either ship only the combined, or the combined and its parts.

**Comment by paulfantom** [comment]
Is only LGTM a main consideration here? Because if it is, then ditch it and replace by custom solution run inside a CI system.

I don't treat linter as a design oracle.

**Comment by gmosx** [comment]
The files in `web/gui/src` should be ignored by Codacy, LGTM, and the CI bot. Their only purpose is to generated `dashboard.js`. In the future we may convert `dashboard.js` to TypeScript and build using Webpack. At this point I am not ready to commit on a schedule (or even if we will go down that road).

Let's configure LGTM to ignore `web/gui/src` and CI to skip this directory.

**Comment by paulfantom** [comment]
From what I see in this PR, LGTM doesn't show errors regarding `web/gui/src` directory.
Codacy fix already waits for a review in #4515.
CI (travis) currently doesn't do any linting.
CI can first build and later check (run unit tests) already built file, not partials.

All this means that we are essentially disabling code linting for gui/js files (`dashboard.js` is a generated file and shouldn't be linted due to it's autogenerated nature).

I won't stand in a way of doing that. PRs for disabling this are in place, so just review and accept them.

**Comment by ktsaou** [comment]
Rebased it and tested it.
No findings. Everything seems to be working perfectly.

**Comment by ktsaou** [comment]
Checked that the existing `dashboard.js` in the repo did not have any changes after this PR was created. So, there are no changes that we have missed in this split.

**Comment by ktsaou** [comment]
merged!

**Comment by gmosx** [comment]
Wow, that was brave :)

**Pull request merged**
