### PR TITLE
Docs: Point users to proper configure doc

### PR DESCRIPTION
**Pull request by joelhans**
##### Summary

During the great "docsv2" project, I created a new core document that explains `edit-config` and the Netdata config directory at `/docs/configure/nodes.md`. This PR changes many links to point to this core doc to emphasize that it is the source of truth about configuration, and make further navigation easier.

##### Component Name

area/docs
area/collectors

### CODE REVIEW

**Comment by OdysLam** [comment]
Hey @joelhans,

I would like to start measuring the number of changes that we implement due to community feedback. It's a great feedback for my work. Can we add a new label so I don't have to ping you or you to ping me. WHenever you implement something because of some feedback I gave in the #documentation channel or 1-1 etc, just add the appropriate label. 
Thoughts?

**Review by ilyam8 — APPROVED** [review]

**Review by OdysLam — COMMENTED** [review]
I think this is a good improvement.

**Comment by ilyam8** [comment]
i went trhough the changes, all `step-by-step/step-04` linkes we removed, lgtm 👍

**Comment by joelhans** [comment]
@OdysLam That sounds fine to me. I added the **community-feedback** label and added it here. If you're OK with it, let's get this approved and merged!

**Review by OdysLam — APPROVED** [review]

**Pull request merged**
