### PR TITLE
adding an old direct with a file to redirect users to most recent docs

### PR DESCRIPTION
**Pull request by hugovalente-pm**
##### Summary

Old agent version, like the one below, have the direction to update pointing to https://github.com/netdata/netdata/tree/master/installer/UPDATE.md which no longer existed.
Re-adding this folder and file with a link to the current docs.

image

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by ilyam8** [comment]
This PR adds `installer/` to the project root. @hugovalente-pm do we really need that? I think that few people with ancient agents who suddenly decide to upgrade will be able to find the document with instructions on how to upgrade and won't give up on the 404.

**Comment by Ferroin** [comment]
I would tend to agree with @ilyam8 on this one, adding clutter to the project root just to support users running versions from four and a half years ago seems undesirable, especially since most people typically wouldn’t even expect updating from such an old version to work at all without a reinstall.

**Comment by hugovalente-pm** [comment]
your guys concerns are total valid and also to make a better assessment of impact on users we would probably need to understand the number of the agents with these older versions but don't think we can get that easily (not even sure how far back this folder was removed to see from which version it is like this)

this is a request that came directly from @ktsaou so we probably also need him to chime-in on this

reference of [slack thread](https://netdata-cloud.slack.com/archives/CNLAM2B19/p1689336447480479?thread_ts=1689336215.939179&cid=CNLAM2B19)

**Comment by Ferroin** [comment]
> (not even sure how far back this folder was removed to see from which version it is like this)

`git log -- installer` on a local checkout will do it. Based on that, the directory was moved under `packaging` on 2018-12-19, which actually means that the link _was already broken as of v1.12.0 being released_, which IMO is even stronger reason to not worry about this (IOW, the link had _never_ worked in that version, so it not working now is not any different from what it was like on release).

**Comment by hugovalente-pm** [comment]
this won't be done

**Pull request closed without merging**
