### PR TITLE
Delete docs/cloud/get-started.mdx

### PR DESCRIPTION
**Pull request by Ancairon**
##### Summary

Closes netdata/learn#1299

This file should be removed, as it's info is repeated again in other places of Learn, and we currently don't ingest it in the new version.

### CODE REVIEW

**Comment by ilyam8** [comment]
@Ancairon There are a lot of links to that document. 

```bash
netdata@ilyam8 (master) $ git grep -n "get-started.mdx"
claim/README.md:376:script](/docs/get-started.mdx#install-on-linux-with-one-line-installer).
claim/README.md:396:script](/docs/get-started.mdx#install-on-linux-with-one-line-installer).
docs/cloud/get-started.mdx:5:custom_edit_url: "https://github.com/netdata/learn/blob/master/docs/cloud/get-started.mdx"
docs/collect/application-metrics.md:54:caveat is that you must [install Netdata](/docs/get-started.mdx) on a separate system or a compatible VM because there
docs/collect/how-collectors-work.md:17:when you [install Netdata](/docs/get-started.mdx).
docs/configure/nodes.md:26:installation](/docs/get-started.mdx#install-on-linux-with-one-line-installer), the **Netdata config
docs/dashboard/how-dashboard-works.mdx:17:As soon as you [install Netdata](/docs/get-started.mdx), it autodetects hardware, OS, containers, services, and
docs/get-started.mdx:5:custom_edit_url: "https://github.com/netdata/netdata/edit/master/docs/get-started.mdx"
docs/guides/deploy/ansible.md:14:Netdata's [one-line kickstart](/docs/get-started.mdx) is zero-configuration, highly adaptable, and compatible with tons
docs/guides/monitor/anomaly-detection-python.md:38:- A node running the Netdata Agent. If you don't yet have that, [get Netdata](/docs/get-started.mdx).
docs/guides/monitor/lamp-stack.md:61:kickstart command](/docs/get-started.mdx):
docs/guides/monitor/lamp-stack.md:241:- [Netdata Agent · Get started](/docs/get-started.mdx)
docs/guides/monitor/pi-hole-raspberry-pi.md:102:walkthrough of all its features. For a more expedited tour, see the [get started guide](/docs/get-started.mdx).
docs/guides/monitor/process.md:37:-   One or more Linux nodes running [Netdata](/docs/get-started.mdx). If you need more time to understand Netdata before
docs/guides/monitor/raspberry-pi-anomaly-detection.md:26:  node yet, [get started now](/docs/get-started.mdx).
docs/guides/monitor/raspberry-pi-anomaly-detection.md:122:- [Netdata Agent · Get Netdata](/docs/get-started.mdx)
docs/guides/monitor/statsd.md:33:- A node with the [Netdata](/docs/get-started.mdx) installed.
docs/guides/python-collector.md:32:- A working installation of the free and open-source [Netdata](/docs/get-started.mdx) monitoring agent.
docs/guides/step-by-step/step-00.md:21:straight into code and configurations with our [getting started guide](/docs/get-started.mdx).
docs/overview/netdata-monitoring-stack.md:60:Netdata**](/docs/get-started.mdx).
docs/overview/what-is-netdata.md:21:You can [install](/docs/get-started.mdx) Netdata on most Linux distributions (Ubuntu, Debian, CentOS, and more),
health/notifications/pagerduty/README.md:21:- An installation of the open-source [Netdata](/docs/get-started.mdx) monitoring agent.
```

**Comment by Ancairon** [comment]
If I'm not mistaken, I delete the `/docs/cloud/get-started.mdx`, not the `docs/get-started.mdx`.

**Comment by Ancairon** [comment]
There shouldn't really be any relative links to it, as it was brought over from Learn, and now resides in the `docs/cloud` folder

**Review by cakrit — APPROVED** [review]

**Comment by cakrit** [comment]
@Ancairon looks like you need to resolve the conflicts here.

**Comment by Ancairon** [comment]
Should be rebased now 👍🏻

**Comment by cakrit** [comment]
Still shows conflicts. Don't now why.

**Comment by Ancairon** [comment]
The file was changed again in #14427, will rebase again.

**Pull request merged**
