### PR TITLE
[WIP] rely on codacy for code linting

### PR DESCRIPTION
**Pull request by paulfantom**
##### Summary

- Remove linting stage from travis.
- Remove .codeclimate config as we don't use codeclimate
- Moved cppcheck.sh to contrib

##### Component Name

CI System

##### Additional Information

Codacy uses larger array of linters to check code quality and it checks only parts which are changed which should be faster. As our code is now linted there is no more need for `lint` stage in travis. This should create a faster CI system.
It also removes `cppcheck.sh` script as this check is also implemented in Codacy.

After merging this, `Codacy/PR Quality Review` check will be a `required` check for all PRs.

### CODE REVIEW

**Comment by Ferroin** [comment]
We're going to need to find a way to neuter certain checks Codacy makes if we want to merge this.  A lot of Python modules get merged with failing Codacy checks because Codacy is complaining about things we can't realistically do anything about (like having to parse untrusted XML or use SSL connections with the default context).

**Comment by paulfantom** [comment]
> We're going to need to find a way to neuter certain checks 

1. `.codacy.yml` file
2. In codacy web interface you can ignore checks.

**Comment by ktsaou** [comment]
Could we keep cppcheck in the contrib directory? Clion can use this inline (i.e. while we write code) and provides good insights. It helps to have this inside the repo since most of us have many computers (it is stupid to maintain it outside the repo).

**Comment by ktsaou** [comment]
btw, codacy has this setting:

image

Which I understand let us pick if we will configure rules from their UI or the repo file.
As you can see this is now set to UI.

Let me find a way to give you admin settings to it.

**Comment by ktsaou** [comment]
I see you are already

image

**Comment by paulfantom** [comment]
I was under impression that CLion already has a cppcheck plugin and don't need additional scripts in code: https://plugins.jetbrains.com/plugin/8143-cppcheck


> btw, codacy has this setting:
> Which I understand let us pick if we will configure rules from their UI or the repo file.

If you look closer, you will see that this is not available for cppcheck. Other checks use such config files, ex. eslint.

**Comment by ktsaou** [comment]
I was talking about the removal of `cppcheck.sh`. This script can be used as the `cppcheck` exe in Clion, to run inline with the Clion plugin you are mentioning. So instead of calling the plain vanilla `cppcheck` that is too noisy, this script tries to prepare the required directories and caching `cppheck` objects and calls it with the right parameters to be less chatty.

It is ok to move it off the root. Just don't delete it. I'll make a PR to update it a bit to work from the place you will put it.

Or delete it and I'll add it later to `contrib/` once I fix it. Your call.

**Comment by paulfantom** [comment]
Moved to `contrib`

**Pull request closed without merging**
