### PR TITLE
Un-vendor proprietary dashboard code.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

- Add support for fetching and installing proprietary dashboard code as part of the build process.
    - This involves a new install component called `dashboard` which covers all of the Dashboard code, both proprietary and FOSS.
    - The code will be fetched from the same publicly accessible location that we currently fetch it from for vendoring in the agent repo. The URL for fetching can be overridden for testing purposes with the `DASHBOARD_URL` cache variable.
    - The process will generate the required CMakeLists.txt file for the dashboard code after fetching and extracting it.
    - All handling for this is during the configuration phase instead of the build phase.
- Add CMake option to disable installing dashboard code.
    - This is not specific to the proprietary dashboard code, if used it will disable installation/handling of everything covered by the new `dashboard` component.
    - This has been added for consistency reasons, with the intent of having a CMake option that corresponds to each native package that we ship other than the core `netdata` package.
- Add separate DEB/RPM packages for the dashboard.
    - Like the CMake option, this covers everything in the new `dashboard` component.
    - Currently these have a strict conflict with prior versions of Netdata compared to the current version of the package to ensure that it upgrades cleanly. Once v2.0 is released this will be relaxed to a conflict with versions prior to v2.0.
    - Currently these are a mandatory dependency for the main Netdata Agent package. At some point after the v2.0 release they will probably be relaxed to an optional dependency which is installed by default to allow users who are running Netdata fully headless to avoid installing the dashboard.
- Remove existing proprietary dashboard code from the repo.

##### Test Plan

This requires manual confirmation that the installed dashboard files are all in the same places as they are in existing installs.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @Ferroin ,

Your PR is working as expected on:

-  Slackware current (Source code compilation)
-  Ubuntu 20.04 (Static binary)
-  Ubuntu 20.04 (Deb package)
-  CentOS 9 (RPM)

With the exception of Slackware, on all distributions I created a VM from scratch to test them. Considering the impact of the changes, could you please provide us with a list of distributions to test?

Best regards!

**Review by thiagoftsm — APPROVED** [review]
After our talk last week about environments necessary to test, I retest only on Slackware, and everything is working locally, LGTM!

**Comment by Ferroin** [comment]
Rebased to resolve merge conflict.

**Review by thiagoftsm — APPROVED** [review]
Considering we only had rebase, I only recompile this PR, and everything is working. LGTM!

**Pull request merged**
