### PR TITLE
adaptec_raid python module

### LINKED ISSUE #4396: Feature request: Support for Adaptec RAID
@l2isbad @ktsaou 
Hi,
I mention you because I contact with you last time for this feature.

I can get you all information about this.
Adaptec RAID controller use different cli tools than megacli.
That is arcconf

The actual status of the RAID may be obtained by using the following command:
```
arcconf GETCONFIG 1 LD
```

Output:
```
Controllers found: 1
----------------------------------------------------------------------
Logical device information
----------------------------------------------------------------------
Logical device number 0
   Logical device name                      : LogicalDrv 0
   Block Size of member drives              : 512 Bytes
   RAID level                               : 10
   Unique Identifier                        : 488046B2
   Status of logical device                 : Optimal
   Size                                     : 915446 MB
   Parity space                             : 915456 MB
   Stripe-unit size                         : 256 KB
   Read-cache setting                       : Enabled
   Read-cache status                        : On
   Write-cache setting                      : Enabled
   Write-cache status                       : On
   Partitioned                              : Yes
   Protected by Hot-Spare                   : No
   Bootable                                 : Yes
   Failed stripes                           : No
   Power settings                           : Disabled
   --------------------------------------------------------
   Logical device segment information
   --------------------------------------------------------
   Group 0, Segment 0                       : Present (Controller:1,Connector:0,Device:0) 7CS009RP
   Group 0, Segment 1                       : Present (Controller:1,Connector:0,Device:1) 7CS009RQ
   Group 1, Segment 0                       : Present (Controller:1,Connector:0,Device:2) 7CS00AAD
   Group 1, Segment 1                       : Present (Controller:1,Connector:0,Device:3) 7CS00AAH



Command completed successfully.
```

The status of the drives may be obtained by using the following command:
```
arcconf GETCONFIG 1 PD
```

Output:
```
Controllers found: 1
----------------------------------------------------------------------
Physical Device information
----------------------------------------------------------------------
      Device #0
         Device is a Hard drive
         State                              : Online
         Block Size                         : 512 Bytes
         Supported                          : Yes
         Transfer Speed                     : SATA 6.0 Gb/s
         Reported Channel,Device(T:L)       : 0,0(0:0)
         Reported Location                  : Connector 0, Device 0
         Vendor                             : ATA
         Model                              : XF1230-1A0480
         Firmware                           : ST200354
         Serial number                      : 7CS009RP
         World-wide name                    : 5000C500813BF05B
         Reserved Size                      : 138008 KB
         Used Size                          : 457728 MB
         Unused Size                        : 64 KB
         Total Size                         : 457862 MB
         Write Cache                        : Disabled (write-through)
         FRU                                : None
         S.M.A.R.T.                         : No
         S.M.A.R.T. warnings                : 0
         Power State                        : Full rpm
         Supported Power States             : Full power,Powered off
         SSD                                : Yes
         NCQ status                         : Enabled
      Device #1
         Device is a Hard drive
         State                              : Online
         Block Size                         : 512 Bytes
         Supported                          : Yes
         Transfer Speed                     : SATA 6.0 Gb/s
         Reported Channel,Device(T:L)       : 0,1(1:0)
         Reported Location                  : Connector 0, Device 1
         Vendor                             : ATA
         Model                              : XF1230-1A0480
         Firmware                           : ST200354
         Serial number                      : 7CS009RQ
         World-wide name                    : 5000C500813BF05C
         Reserved Size                      : 138008 KB
         Used Size                          : 457728 MB
         Unused Size                        : 64 KB
         Total Size                         : 457862 MB
         Write Cache                        : Disabled (write-through)
         FRU                                : None
         S.M.A.R.T.                         : No
         S.M.A.R.T. warnings                : 0
         Power State                        : Full rpm
         Supported Power States             : Full power,Powered off
         SSD                                : Yes
         NCQ status                         : Enabled
      Device #2
         Device is a Hard drive
         State                              : Online
         Block Size                         : 512 Bytes
         Supported                          : Yes
         Transfer Speed                     : SATA 6.0 Gb/s
         Reported Channel,Device(T:L)       : 0,2(2:0)
         Reported Location                  : Connector 0, Device 2
         Vendor                             : ATA
         Model                              : XF1230-1A0480
         Firmware                           : ST200354
         Serial number                      : 7CS00AAD
         World-wide name                    : 5000C500813BF320
         Reserved Size                      : 138008 KB
         Used Size                          : 457728 MB
         Unused Size                        : 64 KB
         Total Size                         : 457862 MB
         Write Cache                        : Disabled (write-through)
         FRU                                : None
         S.M.A.R.T.                         : No
         S.M.A.R.T. warnings                : 0
         Power State                        : Full rpm
         Supported Power States             : Full power,Powered off
         SSD                                : Yes
         NCQ status                         : Enabled
      Device #3
         Device is a Hard drive
         State                              : Online
         Block Size                         : 512 Bytes
         Supported                          : Yes
         Transfer Speed                     : SATA 6.0 Gb/s
         Reported Channel,Device(T:L)       : 0,3(3:0)
         Reported Location                  : Connector 0, Device 3
         Vendor                             : ATA
         Model                              : XF1230-1A0480
         Firmware                           : ST200354
         Serial number                      : 7CS00AAH
         World-wide name                    : 5000C500813BF324
         Reserved Size                      : 138008 KB
         Used Size                          : 457728 MB
         Unused Size                        : 64 KB
         Total Size                         : 457862 MB
         Write Cache                        : Disabled (write-through)
         FRU                                : None
         S.M.A.R.T.                         : No
         S.M.A.R.T. warnings                : 0
         Power State                        : Full rpm
         Supported Power States             : Full power,Powered off
         SSD                                : Yes
         NCQ status                         : Enabled


Command completed successfully.
```

As this command also generates a quantity of useless information, it is advisable to filter the output, eg. using:
```
arcconf getconfig 1 pd|egrep "Device #|State\>|Reported Location|Reported Channel|S.M.A.R.T. warnings"
```

Output:
```
Device #0
         State                              : Online
         Reported Channel,Device(T:L)       : 0,0(0:0)
         Reported Location                  : Connector 0, Device 0
         S.M.A.R.T. warnings                : 0
         Power State                        : Full rpm
      Device #1
         State                              : Online
         Reported Channel,Device(T:L)       : 0,1(1:0)
         Reported Location                  : Connector 0, Device 1
         S.M.A.R.T. warnings                : 0
         Power State                        : Full rpm
      Device #2
         State                              : Online
         Reported Channel,Device(T:L)       : 0,2(2:0)
         Reported Location                  : Connector 0, Device 2
         S.M.A.R.T. warnings                : 0
         Power State                        : Full rpm
      Device #3
         State                              : Online
         Reported Channel,Device(T:L)       : 0,3(3:0)
         Reported Location                  : Connector 0, Device 3
         S.M.A.R.T. warnings                : 0
         Power State                        : Full rpm
```

Optional, some adapter have temperature sensor and show temperature for disk. That information was in second command output, and looks like:
`Temperature                        : 42 C/ 107 F`

Alarm must to be set for degraded state. If you check first command output, there is line:
```   Status of logical device                 : Optimal```

If that status **Failed** or **Degraded** must to alarm.

For second command ouput you have line:
`State:` need to alarm if not **Online**, that is information for every disk.
and
`S.M.A.R.T. warnings` for that also you can set alarm.

If you need more information please write me here I will check.

### PR DESCRIPTION
**Pull request by l2isbad**
##### Summary

Fixes #4396
##### Component Name

python `adaptec_raid` module

##### Additional Information

:snake: new python module :snake:

Logical device charts:

- `Status Is Not OK` (Failed or Degraded)

Physical device charts:
- `State Is Not OK` (not Online)
- `S.M.A.R.T warnings` (count)
- `Temperature` (if present)

todo:
- [x] alarms (LD status, PD state, ~~PD S.M.A.R.T warnings~~)

```paste below
```

screenshot:
screenshot_20181022_133914

@petarkozic

### CODE REVIEW

**Comment by ktsaou** [comment]
Please include charts screenshots in README.md files. Paste the screenshots on github to get CDN URLs.

**Comment by paulfantom** [comment]
Can we agree on NOT including binary files (images etc.) in git repository? Or if they are included then by using `git lfs`? Git is not very friendly for binary data and such data easily increase repo size which in turn causes `git clone` to be a very slow command.

**Comment by ktsaou** [comment]
> Can we agree on NOT including binary files (images etc.) in git repository?

yes, I didn't said to include screenshots in the repo. I said to include them in the README.md using github as CDN.

This does not apply for dashboard images. netdata dashboards should be self-contained.

**Comment by ktsaou** [comment]
hm... can't tell what is wrong here.
Probably it needs a commit to trigger travis, or it is just delayed due to github issues.

**Comment by Ferroin** [comment]
For future reference, you can close and then re-open a PR to re-trigger webhooks without adding commits or doing a rebase and force-push.

**Pull request merged**
