### PR TITLE
Report porcelain output

### PR DESCRIPTION
**Pull request by jsoref**
##### Summary
Report dirty files

##### Component Name
build

##### Test Plan

creating a PR into this branch that adds a dirty file should test this change

### CODE REVIEW

**Review by vkalintiris — APPROVED** [review]

**Review by knatsakis — APPROVED** [review]

**Comment by jsoref** [comment]
Do I need to do something here?

**Comment by jsoref** [comment]
@Ferroin: do I need to do something here?

**Comment by jsoref** [comment]
Or @ilyam8 ?

**Comment by vlvkobal** [comment]
A few new required checks have been added to our CI since you made the PR. Please rebase it.

**Review by Ferroin — APPROVED** [review]

**Pull request merged**
