### PR TITLE
create stale bot integration

### LINKED ISSUE #3914: [project management] Introduce Stale bot
Have you considered using [stale bot](https://github.com/probot/stale) to automatically clean backlog of issues a little and reduce number of drive-by contributors?

### PR DESCRIPTION
**Pull request by paulfantom**
It will also need us to enable stale bot integration: https://probot.github.io/apps/stale/

Resolves #3914

### CODE REVIEW

**Comment by ktsaou** [comment]
So, you suggest to merge this and not enable the integration until we are ready?

**Comment by paulfantom** [comment]
ready! let's ship it :shipit:

**Comment by ktsaou** [comment]
Could you please update the description of this PR with the basics of how this works. I know we had discussed this, but I find the related issue and I don't really remember what we had agreed upon.

**Comment by paulfantom** [comment]
@ktsaou go to slack :)

**Comment by paulfantom** [comment]
Changed `daysUntilClose: 0` to `daysUntilClose: false` just to be safe.

**Comment by ktsaou** [comment]
> @ktsaou go to slack :)

slack does not help. Anyway let's do it. We will see it in practice...

**Comment by paulfantom** [comment]
No, really go to slack, to #general channel

**Pull request merged**
