### PR TITLE
Have dashboard.js be able to have multiple data sources per graph

### PR DESCRIPTION
**Pull request by julsemaan**
As discussed in #3761, we were looking to have multiple datapoints to be viewable on the same graph.

This code is far from being clean, I pretty much hacked the library to perform what we want since there is a lot of metadata that relies on the library supporting a single data source per chart.

I'll let the maintainers be the judges on whether or not this is a good thing to integrate in the netdata codebase.

### CODE REVIEW

**Comment by ktsaou** [comment]
This is nice! Give me some time to review this in detail.

**Comment by ktsaou** [comment]
ah! I forgot: **thank you for sharing**!

**Comment by cakrit** [comment]
@julsemaan will you be able to address the issued identified by Codacy and codeclimate? It's been a while, so you'll certainly need to do a rebase as well. If you don't have the time, please let us know so we can plan this differently.

**Comment by ktsaou** [comment]
@julsemaan 	if you don't have time for this, signing the CLA will allow us to use your code to finish it.

**Comment by julsemaan** [comment]
I've just signed the CLA.

I'm fine with you guys adjusting this code and if needed, I can perform adjustments instead.

**Comment by paulfantom** [comment]
This needs to be rebased.

**Comment by gmosx** [comment]
It's extremely hard to merge this, the dashboard.js file is now split into multiple files.
@julsemaan can you apply the changes to the latest version and update this PR?

**Comment by cakrit** [comment]
Closing in favor of #4983

**Pull request closed without merging**
