### PR TITLE
Removed Google Analytics from the docs

### PR DESCRIPTION
**Pull request by kickoke**
This PR removes all Google analytics snippets from the docs for the following reasons: 
- The ingest script strips away the GA snippets anyway
- We can capture all user events with PostHog

So, effectively these are dead code. 

However, I want to raise attention to the fact that there are still code fragments (not docs) that use google analytics. 
Are there plans to update these occurances? Or are they obsolete and they can be removed? 

@stelfrag Can you tag the appropriate person for this matter? 

```
8 results - 8 files

ml/json/test/reports/2016-09-09-nativejson_benchmark/conformance_Nlohmann (C++11).md:
  56  <meta name="google-site-verification" content="ZzhVyEFwb7w3e0-uOTltm8Jsck2F5StVihD0exw2fsA">
  57:     <meta name="google-analytics" content="UA-3769691-2">
  58  

ml/kmeans/dlib/docs/docs/stylesheet.xsl:
  74                 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  75:                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  76  

web/gui/main.js:
  4484                  m.parentNode.insertBefore(a, m)
  4485:             })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
  4486  

web/gui/dashboard/demosites.html:
  1391                  (t[n].q = t[n].q || []).push(arguments)
  1392:             }), t[n].l = +new Date, o = e.createElement(a), i = e.getElementsByTagName(a)[0], o.src = "//www.google-analytics.com/analytics.js", i.parentNode.insertBefore(o, i)
  1393          }(t, r, "script", "ga"), ga("create", "UA-64295674-3", "auto"), ga("send", "pageview", "/site"+window.location.pathname), t.document.addEventListener("click", n)

web/gui/dashboard/demosites2.html:
  1105          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  1106:         })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  1107  

web/gui/dashboard/infographic.html:
  132                  (t[n].q = t[n].q || []).push(arguments)
  133:             }), t[n].l = +new Date, o = e.createElement(a), i = e.getElementsByTagName(a)[0], o.src = "//www.google-analytics.com/analytics.js", i.parentNode.insertBefore(o, i)
  134          }(t, r, "script", "ga"), ga("create", "UA-64295674-3", "auto"), ga("send", "pageview"), t.document.addEventListener("click", n)

web/gui/dashboard/static/js/main.e3f3d31b.chunk.js:
  1  /*! For license information please see main.e3f3d31b.chunk.js.LICENSE */
  2: ⟪ 123205 characters skipped ⟫"script",n="ga",e.GoogleAnalyticsObject=n,e.ga=e.ga||function(){(e.ga.q=e.ga.q||[]).push(arguments)},e.ga.l=1*new Date,r=t.createElement(a),o=t.getElementsByTagName(a)[0],r.async=1,r.src="https://www.google-analytics.com/analytics.js",o.parentNode.insertBefore(r,o),ga("create","UA-64295674-3","auto"),ga("send","pageview","/demosite/"+window.location.host)}),2e3)):notifyForUpdate(),!0===urlOptions.show_alarms&&setTimeout((function(){$("#alarmsModal").modal("show")}),1e3),NETDATA.onresizeCallback=function(){Ps.update(document.getElementById("sidebar"))},NETDATA.onresizeCallback(),null!==window.netdataSnapshotData&&reduxStore.dispatch(Object(_domains_global_actions__WEBPACK_IMPORTED_MODULE_2__.s)({after:window.netdataSnapshotData.after_ms,before:window.netdataSnapshotData.before_ms}))}window.resetDashboardOptions=function(){reduxStore.dispatch(Object(_domains_global_actions__WEBPACK_IMPORTED_MODULE_2__.l)()),urlOptions.update_always=!1,urlOptions.help=!1,urlOptions.theme="slate",urlOptions.hashUpdate(),netdataReload()};var netdataPrepCallback=function(){_utils_is_demo__WEBPACK_IMPORTED_MODULE_14__.a?document.getElementById("masthead").style.display="block":!0===urlOptions.update_alway
  3  //# sourceMappingURL=main.e3f3d31b.chunk.js.map

web/gui/dashboard/static/js/main.e3f3d31b.chunk.js.map:
  1: ⟪ 792303 characters skipped ⟫  m = s.getElementsByTagName(o)[0];\n                a.async = 1;\n                a.src = g;\n                m.parentNode.insertBefore(a, m)\n            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');\n\n            ga('create', 'UA-64295674-3', 'auto');\n            ga('send', 'pageview', '/demosite/' + window.location.host);\n        }, 2000);\n    } else {\n        notifyForUpdate();\n    }\n\n    if (urlOptions.show_alarms === true) {\n        setTimeout(function () {\n            $('#alarmsModal').modal('show');\n        }, 1000);\n    }\n\n    NETDATA.onresizeCallback = function () {\n        Ps.update(document.getElementById('sidebar'));\n    };\n    NETDATA.onresizeCallback();\n\n    if (window.netdataSnapshotData !== null) {\n        reduxStore.dispatch(setGlobalPanAndZoomAction({\n            after: window.netdataSnapshotData.after_ms,\n            before: window.netdataSnapshotData.before_ms,\n        }))\n    }\n}\n\nwindow.resetDashboardOptions = () => {\n    reduxStore.dispatch(resetOptionsAction())\n\n    // it's dirty, but this will be rewritten anyway\n    urlOptions.update_always = false;\n    urlOptions.help = false;\n   

```

### CODE REVIEW

**Review by DShreve2 — APPROVED** [review]

**Comment by stelfrag** [comment]
@vkalintiris there seems to be a reference to GA in the dlib docs

**Comment by vkalintiris** [comment]
> @vkalintiris there seems to be a reference to GA in the dlib docs

Right, one in ml/json and another one in ml/kmeans/dlib. We can just ignore them as they are used only as git submodules of external repositories, ie. they are not hosted in our `netdata` repository.

**Comment by kickoke** [comment]
@vkalintiris But if I understood correctly, we don't use GA anywhere anymore, right? 
So can we remove the code to decrease tech debt?

**Comment by vkalintiris** [comment]
> @vkalintiris But if I understood correctly, we don't use GA anywhere anymore, right?

Right.

> So can we remove the code to decrease tech debt?

The code you see under `ml/json/` and `ml/kmeans/dlib` is not ours, it's code that comes from external dependencies, ie. third-party projects that we don't own.

When you clone the netdata repository with this command:

```
git clone https://github.com/netdata/netdata.git
```

you'll notice that `ml/json` and `ml/kmeans/dlib` are empty. Someone has to run the following
command:

```
git submodule update --init --recursive --force
```

to initialize the contents of these directories. Effectively, behind the scenes this command runs:

```
git clone https://github.com/nlohmann/json.git ml/json
git clone https://github.com/davisking/dlib.git ml/kmeans/dlib
```

ie. it fetches the source code of these external projects and places them under `ml/json` and `ml/kmeans/dlib`.

**Review by andrewm4894 — APPROVED** [review]
LGTM

**Comment by kickoke** [comment]
@vkalintiris Thank you for the clarification!

**Pull request merged**
