### PR TITLE
Developer mode

### LINKED ISSUE #8344: Developer mode
##### Feature idea summary
The eBPF collectors can detect errors reported when functions are called from other software and it also has the capability to get the function return. With these information we can generate logs that help our users and ourselves to remove bugs from software. 

After the discussion done on #8176, we have conditions to bring logs with the following specification:

- We will support both formats, ltsv and json, and the ltsv will be the default format
-  We will use date format as ISO 8601
- instead to have a dev option for the load option, we will have a new variable to enable or disable the developer mode.

##### Expected behavior
To have a log that will help users to remove bugs on their software.

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes #8344 

This PR changes the eBPF collector `ebpf_process` bringing the `developer mode`. This new feature allow the user to have more information about the errors counted on charts. When this feature is enabled inside `ebpf_process.conf`,  Netdata will store details for each error reported inside `/var/log/netdata/developer.log`.

##### Component Name
Collector

##### Test Plan
To test this collector, it will be necessary to install Netdata on a kernel that supports both `eBPF` and `kprobes`, of course, it is also necessary to install Netdata  with support to eBPF. Please, run the following command to install Netdata:

```
./netdata-installer.sh --enable-ebpf --dont-wait --dont-start-it
```

To install this PR is not enough, because we also need to have the newest version of the eBPF programs that were not merged, to get them, please go to link https://github.com/netdata/kernel-collector/actions/runs/60960305 and get the latest version according with your kernel a. Case you are using any version of the kernel `5.x`, please, get the kernel `5.4.20`.

After to get the file, extract the .zip file and after this the tar.xz . Move all the files that have `netdata_ebpf_process.o` in its name and the file `libnetdata_ebpf.so` to `/usr/libexec/netdata/plugins.d`.

After this you can start your Netdata, in this case it is expected that the file `/var/log/netdata/developer.conf` won't be created.

After this we need to change your `ebpf_process.conf` that is inside `/etc/netdata/` to enable the developer mode, the next file demonstrates these steps:

```
[global]                                                                                                                                                                                                                                                                       
    load = return                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    developer mode = yes                                                                                                                                                                                                                                                        
    log format = ltsv  
``` 

Restart your Netdata.  After this you should have the log file and when Netdata detects that an error happened, it will store the information about this error inside it using `ltsv` format.

After this it is necessary to change the `ebpf_process.conf` again, this time changing it to use `json` format:

```
[global]                                                                                                                                                                                                                                                                       
    load = return                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    developer mode = yes                                                                                                                                                                                                                                                        
    log format = json  
``` 

Please, restart your Netdata. The unique difference between the previous step and this, it is the output format expected inside the file `developer.log`.

##### Additional Information
The period of time selected to read information from kernel ring to user ring was based in an environment generating more than 100 error per second, in this situation I never had more than 0.5% of the hash table filled.

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- collectors/ebpf_process.plugin/ebpf_process.c  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5223674&bid=17126840)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- collectors/ebpf_process.plugin/ebpf_process.c  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5223674&bid=17126840)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- collectors/ebpf_process.plugin/ebpf_process.c  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5223674&bid=17126840)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- collectors/ebpf_process.plugin/ebpf_process.c  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5223674&bid=17126840)

**Comment by thiagoftsm** [comment]
We will work with this in another EPIC, considering the necessity to do rebase and also bring integration with apps.groups, we will bring another PR when this is planned.

**Pull request closed without merging**
