### PR TITLE
Assorted build cleanup for external data collection plugins.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

- Add options to disable python.d.plugin and charts.d.plugin at build time. The charts.d plugin is additionally hard-disabled on Windows, as it is not possible to make it run natively there _and_ it also does not include any collectors that are expected to be usable there.
- Properly limit tc.plugin files to only be installed if the plugin is actually built. This means in practice that the `tc-qos-helper.sh` script will only be installed on Linux systems, not other platforms.
- Skip installing loopsleepms script if neither charts.d.plugin nor tc.plugin are being installed, as they are the only things that depend on it. It’s still tied to the main `netdata` component as that is where tc.plugin is handled, but it will be excluded from the list of files to install if both plugins are disabled at build time.
- Tie the config directories for go.d.plugin and python.d.plugin to the install components for those plugins. In practice this means that `/etc/netdata/go.d` should only be present if the Go plugin is enabled and installed, and `/etc/netdata/python.d` should only be present if the Python plugin is installed.

##### Test Plan

Requires simple manual checks that the changes are actually in effect.

### CODE REVIEW

**Comment by ilyam8** [comment]
You can disable installing charts.d.plugin by default.

**Comment by Ferroin** [comment]
> You can disable installing charts.d.plugin by default.

I’ve intentionally left that as a separate PR for the moment with the intent of ensuring this PR does not change any behavior that users should actually be depending on. I do plan to do that as a followup though, likely alongside making most of the external collector plugins optional (but mostly installed by default) dependencies in the native packages.

**Comment by thiagoftsm** [comment]
Hello @Ferroin ,

Please, rebase your PR to resolve the conflicts.

Best regards!

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Review by thiagoftsm — APPROVED** [review]
PR is working as expected. When I installed without any additional option, I did had both plugins, while when I specified, they were not installed.

**Pull request merged**
