### PR TITLE
configure.ac: Unconditionally link against libatomic

### LINKED ISSUE #12319: [Bug]: Release 1.33.1 fails to build from source on riscv64
### Bug description

Hi guys,

As can be seen at [1], netdata fails to build on riscv64 because the gcc command line lacks `-latomic`. Indeed, I checked and none of the conditions in configure.ac line 1526 (my head is at commit c4d2498d7617) allow to set `OPTIONAL_ATOMIC_LIBS`. So there may be a missing condition here to allow riscv64 to set `OPTIONAL_ATOMIC_LIBS`.

But in the meantime, as stated in the comment line in configure.ac:1533, there is no need to make `-latomic` optional because either the atomics are fulfilled by gcc builtins and the library is unused or the library is needed anyway, so I would rather always link against `-latomic` and then get rid of the code that sets `OPTIONAL_ATOMIC_LIBS` (this is actually what I have done at [2] and the build succeeded on all architectures). 

Any comment welcome,

Thanks,

Alex

[1] https://launchpad.net/ubuntu/+source/netdata/1.33.1-1/+build/23168344
[2] https://launchpad.net/~alexghiti/+archive/ubuntu/riscv/+sourcepub/13290580/+listing-archive-extra

### Expected behavior

I expect netdata to build on riscv64.

### Steps to reproduce

Build netdata on riscv64 (one can follow instructions to use a VM at [1] and download a VM at [2])

[1] https://wiki.ubuntu.com/RISC-V
[2] https://cdimage.ubuntu.com/ubuntu-server/daily-preinstalled/pending/

### Installation method

from source

### System info

```shell
ubuntu@ubuntu:~/git/netdata$ uname -a; grep -HvE "^#|URL" /etc/*release
Linux ubuntu 5.13.0-1006-generic #6+22.04.1-Ubuntu SMP Thu Nov 18 16:49:11 UTC 2021 riscv64 riscv64 riscv64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu Jammy Jellyfish (development branch)"
/etc/os-release:PRETTY_NAME="Ubuntu Jammy Jellyfish (development branch)"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04 (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
None
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by AlexGhiti**
##### Summary

The build failed on riscv64 because the build command line lacks libatomic. Fix this by always linking against libatomic since:
- if atomics are not needed, the library will be unused
- if atomics are needed, either atomics are fulfilled by the compiler builtins
  and the library is unused or the library is needed anyway.

Fixes #12319

##### Test Plan

Successfully built on all architectures (https://launchpad.net/~alexghiti/+archive/ubuntu/riscv/+sourcepub/13305735/+listing-archive-extra)

##### Additional Information

Signed-off-by: Alexandre Ghiti <alexandre.ghiti@canonical.com>

### CODE REVIEW

**Comment by schopin-pro** [comment]
Hi there! Would it be possible to approve the CI? We think we've solved the linking issue with musl, and I'd love to have confirmation before uploading this fix to Ubuntu :)

TIA

**Comment by Ferroin** [comment]
AFAICT, the fix here is correct. Failing CI is due to missing dependencies in our package build environments, I’ll get a PR up to fix that shortly (it unfortunately needs to be handled in a different repo) and manually retrigger the CI here once the fix is merged.

**Comment by Ferroin** [comment]
Just realized, this will also need changes to be made to `contrib/debian/control*` and `netdata.spec.in` to properly list libatomic as a hard dependency. The DEB build checks happen to be passing only because `build-essential` pulls in `libatomic1` on Debian and ubuntu, but the packages they will need it at runtime too.

@AlexGhiti I can cover this if you want, or provide whatever assistance you may need if you want to handle it yourself.

**Comment by schopin-pro** [comment]
The Debian package shouldn't need updating, as it has the `${shlibs:Depends}` variable that should automatically pick up any new library.

**Comment by Ferroin** [comment]
> The Debian package shouldn't need updating, as it has the `${shlibs:Depends}` variable that should automatically pick up any new library.

For runtime dependencies yes (and RPM actually does the same thing automatically). The issue is build dependencies, which we try to explicitly list instead of relying on dependency chains like this. IOW, we want to make sure that if `build-essential` ever ends up removing the dependency on libatomic, we get a clean break complaining about a missing dependency instead of a build error like we’re seeing in the RPM packages.

**Comment by Ferroin** [comment]
Manually re-triggered the packaging checks in CI as the dependency issue in the package builder environments has now been resolved.

**Comment by AlexGhiti** [comment]
> me, you probably don’t want to delve into the morass that is our dependency installation code for local builds).

Ok I accept then :) Thanks for all of that

Alex

**Comment by Ferroin** [comment]
> > me, you probably don’t want to delve into the morass that is our dependency installation code for local builds).
> 
> Ok I accept then :) Thanks for all of that
> 
> Alex

Changes for this added. I’ll plan to just take care of the build dependency handling for package builds as a separate PR to keep things simpler to review here (since the package builds are working fine without it right now).

**Comment by Ferroin** [comment]
Fedora 36 package build failure is (unfortunately) expected and unrelated to this PR.

**Comment by vkalintiris** [comment]
@Ferroin what's the status of this? I'm curious because of the upcoming release.

**Review by Ferroin — APPROVED** [review]

**Comment by Ferroin** [comment]
@vkalintiris Ideally needs to go in the release.

Should just need another approval and then we can merge it.

**Review by vkalintiris — APPROVED** [review]

**Comment by Ferroin** [comment]
@AlexGhiti Thanks for the PR, and sorry it took so long to get it merged.

**Comment by vlvkobal** [comment]
As @MrZammler has already mentioned, this doesn't work on macOS
```
ld: library not found for -latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [netdatacli] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
 FAILED
```

**Comment by vkalintiris** [comment]
@Ferroin I think it's better to revert this PR for the upcoming release, and check it again on Linux/MacOS/FreeBSD afterwards.

**Comment by MrZammler** [comment]
I'd say maybe if it only affects arm macos (any issues on x86?) we could fix it afterwards... ? If reverting is too much at this point...

**Comment by vlvkobal** [comment]
> any issues on x86?

**Comment by underhood** [comment]
Just for the record, this also break build on Fedora 34 in case `libatomic` is not installed in system. So it is not MacOS only problem.

**Pull request merged**
