### PR TITLE
Add logparser module

### PR DESCRIPTION
**Pull request by hamedbrd**

### CODE REVIEW

**Comment by paulfantom** [comment]
@hamedbrd please sign CLA.

**Comment by hamedbrd** [comment]
@ktsaou  It's for those kind of logs which generate within applications and if we want to have a monitoring on them, fetching some metrics by regex ,have no dimension with no limitation and also charts

**Comment by l2isbad** [comment]
@hamedbrd i suggest to add `string` search type ('value' in 'row')

In simple cases regex is overkill. 

`re.search(r'.*GET.*', 'LONG ROW')` does same job as `'GET' in 'LONG ROW'` but much slower

```python
import re
import time

r = re.compile('.*MISS.*')

row = '10.6.1.213 - - [15/Apr/2018:07:56:34 +0900] "OPTIONS cacti HTTP/1.1" 200 29 490 0.001 0.001 "health.whatever.whatever" "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0'

s = time.time()
for i in range(100000):
    #'MISS' in row
    r.search(row)
print(time.time() - s)
```

regexp time: `3.2602620124816895`
string match time : `0.01069951057434082`

should be something like

```yaml
foo:
  bar1: 'string=GET'
  bar2: 'string=GOT'
  bar3: 'regex=G[QWERTY]T'
```

**Comment by Ferroin** [comment]
Adding to @l2isbad's comment, you might also consider adding support for prefix and suffix matching.  Both can be done faster in Python with `str.startswith()` and `str.endswith()` than they can be with regexes.  This isn't nearly as big of a performance improvement as having simple substring matching like @l2isbad is requesting, and it's likely to be more of a niche use case, so I wouldn't consider it critical by any means, just nice to have.

**Comment by l2isbad** [comment]
yo @hamedbrd 

Are you going to finish the module?

**Comment by hamedbrd** [comment]
@l2isbad 
Yes ,I'm working on it

**Comment by l2isbad** [comment]
@hamedbrd nice!

**Comment by cakrit** [comment]
@hamedbrd when you're ready, please add "Fixes #3729" to your final commit, so that that ticket can be closed automatically.

**Comment by hamedbrd** [comment]
@cakrit I pull the latest changes from master and change my files according to latest version

I also attempt to add new feature to this plugin in order to fetch metrics for each endpoint but unfortunately i'm busy these days  

Could you please check it out and let me know your feedback

**Comment by cakrit** [comment]
Hi @hamedbrd there seem to be many things wrong with this PR. It's somehow trying to change 1448 files, it has 3 unresolved conflicts and most of the automated checks are failing. It looks like your fork or branch has some issues. If you're not a github wizard like some other people here, it may be simpler to fork again and apply your changes in a new branch.

**Comment by hamedbrd** [comment]
@cakrit I sent a new PR 
https://github.com/netdata/netdata/pull/4900
I think it's much better

**Comment by cakrit** [comment]
Indeed, much cleaner, thanks. Closing this one in favor of #4900

**Pull request closed without merging**
