### PR TITLE
vernemq alarms, dashboard info and godplugin new version

### PR DESCRIPTION
**Pull request by ilyam8**
### Summary

This PR:

- [X] adds `vernemq` icon and gauges to the dashboard_info
- [X] adds `vernemq` alarms
- [X] adds `vernemq` to the collectors list
- [x] updates `godplugin` version to `v0.16.0`

##### Component Name

- `packaging`
- `web`
- `health`
- `docs`

##### Description of testing that the developer performed

By steps:

- installed this branch, no errors during install ✅ 
- new version of `go.d.plugin` was downloaded ✅ 
- all adittions to the `dashboard_info.js` was one the dashboard ✅ 
- all new alarms were up, running and have values (38 in the config, 38 active) ✅

### CODE REVIEW

**Comment by ilyam8** [comment]
> but I did not have Verme MQ to test.

if you want to test something which wasnt tested by me

> docker run -p 1883:1883 -p 8888:8888 -e "DOCKER_VERNEMQ_ACCEPT_EULA=yes" --name vernemq1 -d vernemq/vernemq

**Comment by jacekkolasa** [comment]
dashboard_info.js stuff looks ok

**Comment by ilyam8** [comment]
Oh, both Travis and license/cla stuck in `Waiting for status to be reported` 🙈

**Comment by Ferroin** [comment]
Manually merging at the request of @ilyam8.

* CLA check has been manually verified (@ilyam8 is the only commit author, and is known to have signed).
* Travis check is being ignored, as all the checks that matter for this PR are already happening in GitHub Actions.

**Pull request merged**
