### PR TITLE
Remove temporary allocations when preprocessing a samples buffer

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

This PR replaces two temporary heap allocations with stack arrays. We can do this because our features are produced from single dimensions.

##### Test Plan

- CI job
- Run ML with address sanitizer

### CODE REVIEW

**Comment by andrewm4894** [comment]
dropping and recreating ml-demo nodes and also creating `ml-demo-ml-enabled-rmallocs` on this branch

**Comment by andrewm4894** [comment]
looking here i see a slight consistent improvement in terms of cpu

[link](https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/overview#metrics_correlation=false&after=-7200&before=0&utc=Europe%2FLondon&offset=%2B0&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-overview-chartName=menu_apps_submenu_cpu&6045dc92-0a0c-48d8-960c-d2e0f31aa95d--selectedNodeIds=3d7f3b31-4da5-4065-a052-756c99052a0e%2C6d9bf439-700d-4272-920e-bf6b69e849cf&modalParams=)

image

**Review by andrewm4894 — APPROVED** [review]

**Comment by andrewm4894** [comment]
looking over a longer time frame when nodes all in a sort of steady start it looks like cpu reduction on this branch is actually pretty good in a relative sense:

[link](https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/dashboards/anomaly-detection-diagnostics#metrics_correlation=false&after=-43200&before=0&utc=Europe%2FLondon&offset=%2B0&timezoneName=Edinburgh%2C%20London&modal=&modalTab=&d8a4e0c5-7c79-4145-900e-83a9f06fcb6a-overview-chartName=menu_system_submenu_cpu&6045dc92-0a0c-48d8-960c-d2e0f31aa95d--selectedNodeIds=3d7f3b31-4da5-4065-a052-756c99052a0e%2C65c22710-17e9-4cfe-9fc3-42b56d385aed%2Cd6f413df-9026-40cb-85d9-5a91fca58097%2C6d9bf439-700d-4272-920e-bf6b69e849cf%2Cb8a179f7-1905-496a-96ed-ea204e88d479%2C16068f35-7aa5-43ef-9b70-4a3d0e3a9514%2C28d4b424-7b18-4a5c-a6c0-0a0915d1e120&6045dc92-0a0c-48d8-960c-d2e0f31aa95d-overview-chartName=menu_netdata_submenu_workers&modalParams=)

image

seems like it's mostly in the prediction where savings are:

image

**Review by MrZammler — APPROVED** [review]

**Comment by andrewm4894** [comment]
@vkalintiris you happy to merge?

**Pull request merged**
