### PR TITLE
Add custom e-mail headers

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This was [requested by a user in the community forum](https://community.netdata.cloud/t/custom-headers-in-email-notifications/1489). Although the user seems to have requested it for the cloud e-mails, it is a simple change to also have in agent e-mails. If we need perhaps to also include it in cloud e-mails, we can wait before merging and synchronize as to not create confusion.

The PR adds some custom headers, which can then be used for filtering from an email client.

##### Component Name

Health notifications

##### Test Plan

Raise an alert e-mail notification from an agent. Observe in the e-mail headers e.g.:

```
X-Netdata-Severity: warning
X-Netdata-Alert-Name: exporting_metrics_sent
X-Netdata-Chart: netdata.exporting_my_graphite_instance_bytes
X-Netdata-Family: exporting_my_graphite_instance
X-Netdata-Classification: Workload
X-Netdata-Host: winterland
X-Netdata-Role: dba
```

##### Additional Information

Do we need to edit some piece of documentation to include this feature information?

### CODE REVIEW

**Comment by ilyam8** [comment]
@MrZammler should we update [plain text emails](https://github.com/netdata/netdata/blob/840e95f84081efc61566a576d454b7e823371d6c/health/notifications/alarm-notify.sh.in#L2682-L2687) too?

**Comment by MrZammler** [comment]
> @MrZammler should we update [plain text emails](https://github.com/netdata/netdata/blob/840e95f84081efc61566a576d454b7e823371d6c/health/notifications/alarm-notify.sh.in#L2682-L2687) too?

Hi Ilya! Yes, you're right! Added.

**Comment by MrZammler** [comment]
Also, I've only tested this using sendmail from the ssmtp package. We need to check if other sendmails are also ok with this.

**Comment by MrZammler** [comment]
> Also, I've only tested this using sendmail from the ssmtp package. We need to check if other sendmails are also ok with this.

Real sendmail seems ok too.

**Comment by ilyam8** [comment]
> Do we need to edit some piece of documentation to include this feature information?

I think we need to update this doc https://learn.netdata.cloud/docs/agent/health/notifications/email

**Comment by MrZammler** [comment]
> > Do we need to edit some piece of documentation to include this feature information?
> 
> I think we need to update this doc https://learn.netdata.cloud/docs/agent/health/notifications/email

Thanks @ilyam8 ! We also need to change the email image there, I've constructed a new image we can use (but have no idea really how to upload as static content).

netdata_example_email

**Comment by ilyam8** [comment]
@MrZammler, indeed! That image is really outdated.

> but have no idea really how to upload as static content

You did it. Just replace the link with the one from your post.

> https://user-images.githubusercontent.com/1905463/133216974-a2ca0e4f-787b-4dce-b1b2-9996a8c5f718.png

**Comment by MrZammler** [comment]
Link to the request in community forums: https://community.netdata.cloud/t/custom-headers-in-email-notifications/1489

**Review by ilyam8 — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
LGTM!

**Comment by MrZammler** [comment]
Thank you!

**Pull request merged**
