### PR TITLE
Minor fixes for AWS Kinesis build checks.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

* Bump the Fedora build check to use Fedora 34 instead of Fedora 32.
* Switched to using DNF instead of YUM for CentOS 8 check.

##### Component Name

area/ci

##### Test Plan

Behavior verified on this PR.

### CODE REVIEW

**Review by vkalintiris — DISMISSED** [review]

**Review by vkalintiris — DISMISSED** [review]

**Comment by Ferroin** [comment]
@netdata/agent I’m unfortunately going to need someone with a much better understanding of how our handling of the AWS SDK works to take a look at this: https://github.com/netdata/netdata/pull/11058/checks?check_run_id=2575643270

We appear to be having some issue actually building the AWS SDK prior to actually running the tests, but I’m at a bit of a loss as to why.

**Comment by MrZammler** [comment]
Not an expert by any chance, just looking around: I see it's `Note: switching to 'v0.4.42'.` which could be old... ? Any idea why ? In  https://github.com/awslabs/aws-c-common there is up to 0.5.11.

**Comment by underhood** [comment]
I believe @vlvkobal will be able to help with AWS SDK related questions

**Comment by Ferroin** [comment]
> Not an expert by any chance, just looking around: I see it's `Note: switching to 'v0.4.42'.` which could be old... ? Any idea why ? In https://github.com/awslabs/aws-c-common there is up to 0.5.11.

We seem to be intentionally using an older version of the SDK overall. I actually tried to resolve this by updating the version we are using for testing, but that actually broke things in a completely different way.

**Comment by ilyam8** [comment]
> We seem to be intentionally using an older version of the SDK overall.

Yes, see commits history in the https://github.com/netdata/netdata/pull/10992 😄

**Comment by vlvkobal** [comment]
I think the problem with AWS SDK compilation is because the GCC package was updated to 11.1 in Fedoda 34. The compiler reports a lot of new warnings and
```
cc1: all warnings being treated as errors
```

**Comment by MrZammler** [comment]
@vlvkobal Yes, because `Werror` is used when building `AwsCCommon`. I can't seem to find a way to override this via the cmake command line though....

**Comment by vlvkobal** [comment]
> I can't seem to find a way to override this via the cmake command line though....

Yeah, the same on my part so far.

**Comment by vlvkobal** [comment]
https://github.com/aws/aws-sdk-cpp/issues/1635#issuecomment-832823551
https://github.com/awslabs/aws-c-common/pull/798

**Comment by ilyam8** [comment]
@vlvkobal @Ferroin how about removing the check temporarily? Having it failed for every PR is a little bit annoying, it provides no value.

If I open the PR page - all the PRs are _failed_. In addition it is confusing for contributors.

<details>
<summary>See the screenshot [Click]</summary>

Screenshot 2021-05-19 at 21 02 35

</details>

**Comment by Ferroin** [comment]
It sounds like we need to just update to 1.9.x and get that working properly at this point. Short term though I’m in favor of removing these checks altogether and reimplementing them from scratch.

**Comment by vlvkobal** [comment]
Using 1.9 won't help. The problem with compilation still exists in the latest release of `aws-c-common`. There were no new releases after the fix. Moreover, in the master branch, there is another dependency with the same issue.

We can try to install GCC 10 instead of the default GCC 11. There is a suitable [OpenSuSE package](https://www.rpmfind.net/linux/RPM/opensuse/tumbleweed/x86_64/gcc10-10.3.0+git1587-1.2.x86_64.html).

A specific compiler can be used this way:
```
cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_ONLY=kinesis ./aws-sdk-cpp
```

**Comment by Ferroin** [comment]
> Using 1.9 won't help. The problem with compilation still exists in the latest release of `aws-c-common`. There were no new releases after the fix. Moreover, in the master branch, there is another dependency with the same issue.
> 
> We can try to install GCC 10 instead of the default GCC 11. There is a suitable [OpenSuSE package](https://www.rpmfind.net/linux/RPM/opensuse/tumbleweed/x86_64/gcc10-10.3.0+git1587-1.2.x86_64.html).
> 
> A specific compiler can be used this way:
> 
> ```
> cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_ONLY=kinesis ./aws-sdk-cpp
> ```

I mean, in theory we could just patch the CMakefiles, couldn’t we?

**Comment by MrZammler** [comment]
> I mean, in theory we could just patch the CMakefiles to remove -Werror, couldn’t we?

I don't know if @vlvkobal has a better idea, but I think it's tricky... `aws-c-common` is git cloned during the cmake stage of `aws-sdk-cpp` so when we issue the initial `cmake` command, the various `aws-c-common` files are not there yet... There is a `[ 16%] No patch step for 'AwsCCommon'` but not sure how it's used, of if it can be of help.

There is actually a recent commit in `aws-c-common` that disables the `warnings as errors`....

**Comment by vlvkobal** [comment]
> I don't know if @vlvkobal has a better idea

Another idea
```
CC=gcc-10 CXX=g++-10 cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_ONLY=kinesis ./aws-sdk-cpp
```

**Comment by vlvkobal** [comment]
The main branch of AWS SDK 1.9 with GCC 11.1:
```
/home/vlad/test/aws-sdk-cpp/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:92:44: error: argument 1 of type ‘int16_t[256]’ {aka ‘short int[256]’} with mismatched bound [-Werror=array-parameter=]
   92 | void PQCLEAN_KYBER51290S_CLEAN_ntt(int16_t poly[256]) {
      |                                    ~~~~~~~~^~~~~~~~~
In file included from /home/vlad/test/aws-sdk-cpp/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:1:
/home/vlad/test/aws-sdk-cpp/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.h:9:45: note: previously declared as ‘int16_t *’ {aka ‘short int *’}
    9 | void PQCLEAN_KYBER51290S_CLEAN_ntt(int16_t *poly);
      |                                    ~~~~~~~~~^~~~
/home/vlad/test/aws-sdk-cpp/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:116:47: error: argument 1 of type ‘int16_t[256]’ {aka ‘short int[256]’} with mismatched bound [-Werror=array-parameter=]
  116 | void PQCLEAN_KYBER51290S_CLEAN_invntt(int16_t poly[256]) {
      |                                       ~~~~~~~~^~~~~~~~~
In file included from /home/vlad/test/aws-sdk-cpp/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.c:1:
/home/vlad/test/aws-sdk-cpp/crt/aws-crt-cpp/crt/s2n/pq-crypto/kyber_90s_r2/ntt.h:10:48: note: previously declared as ‘int16_t *’ {aka ‘short int *’}
   10 | void PQCLEAN_KYBER51290S_CLEAN_invntt(int16_t *poly);
      |                                       ~~~~~~~~~^~~~
cc1: all warnings being treated as errors
make[2]: *** [crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/build.make:832: crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/pq-crypto/kyber_90s_r2/ntt.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:491: crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by ilyam8** [comment]
Bump the issue. @vlvkobal https://github.com/netdata/netdata/pull/11058#issuecomment-844344575

**Comment by Ferroin** [comment]
Superseded by #11451

**Pull request closed without merging**
