### PR TITLE
Daemon docs edits

### PR DESCRIPTION
**Pull request by Ancairon**
##### Summary

I proof-read the files and edited a bit. Daemon is the overview and the other one the conf ref

### CODE REVIEW

**Comment by Ancairon** [comment]
@ilyam8 can you or someone from the Agent team document the missing sections mentioned in the issue?

**Comment by ilyam8** [comment]
In what issue?

**Comment by Ancairon** [comment]
issue mentioned in this PR, above :point_up:

**Comment by ilyam8** [comment]
This PR description doesn't mention any issues. Can you be more specific? Link?

**Review by ilyam8 — APPROVED** [review]

**Pull request merged**
