### PR TITLE
Python.d PEP 8 cleanup, modules A-C

### PR DESCRIPTION
**Pull request by Ferroin**
PEP 8 compliance cleanups for python.d modules with names starting with A, B, or C

Touches all modules except couchdb, which is already compliant (but may not quite fit our coding standards).

Relevant: #4167

### CODE REVIEW

**Comment by Ferroin** [comment]
Should have the next set (D-H) within the hour.

**Comment by Ferroin** [comment]
It looks like someone else is going to have to merge this (and the other ones) as I'm not listed as authorized to merge stuff ot the master branch.

**Comment by paulfantom** [comment]
@Ferroin strange, you have the same permissions as everyone else.

**Comment by Ferroin** [comment]
Yeah, definitely odd.  It looks from this end like I can do just about everything _except_ merge PR's (and of course manage permissions, but not being able to do that is expected).

**Comment by paulfantom** [comment]
Could you paste a screenshot of a box with merge button and checks in it, one just above section where you write comments?

**Comment by Ferroin** [comment]
@paulfantom 

screenshot

**Comment by paulfantom** [comment]
Is it working now?

**Comment by Ferroin** [comment]
Yep.

**Pull request merged**
