### PR TITLE
Add a chart for the CPU frequency reported by the hardware

### LINKED ISSUE #13116: [Bug]: CPU Frequency
### Bug description

The CPU Frequency does not report the current clock rate or effective clock rate. This means it display the base frequency that does not change for AMD CPUs. Ideally we should be graphing effective clock rate like HWinfo on Windows, as this is the most useful metric for displaying the real CPU Frequency.

### Expected behavior

CPU Frequency should not always stay at the same value. 

### Steps to reproduce

1. Install latest netdata on Ubuntu 22.04 with AMD 5000 series CPU
2. Run Stress Test
3. look at net data CPU Frequency graph for any changes.
...

### Installation method

kickstart.sh

### System info

```shell
:~# uname -a; grep -HvE "^#|URL" /etc/*release
Linux ubuntu 5.18.3-xanmod1-x64v2 #0~git20220609.f2e6e36 SMP Thu Jun 9 21:37:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_RELEASE=22.04
/etc/lsb-release:DISTRIB_CODENAME=jammy
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
/etc/os-release:PRETTY_NAME="Ubuntu 22.04 LTS"
/etc/os-release:NAME="Ubuntu"
/etc/os-release:VERSION_ID="22.04"
/etc/os-release:VERSION="22.04 LTS (Jammy Jellyfish)"
/etc/os-release:VERSION_CODENAME=jammy
/etc/os-release:ID=ubuntu
/etc/os-release:ID_LIKE=debian
/etc/os-release:UBUNTU_CODENAME=jammy
```

### Netdata build info

```shell
:~# netdata -W buildinfo
Version: netdata v1.35.0-8-nightly
Configure options:  '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--disable-option-checking' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--with-user=netdata' '--with-math' '--with-zlib' '--with-webdir=/var/lib/netdata/www' '--disable-dependency-tracking' 'build_alias=x86_64-linux-gnu' 'CFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -ffile-prefix-map=/usr/src/netdata=. -fstack-protector-strong -Wformat -Werror=format-security'
Install type: binpkg-deb
    Binary architecture: x86_64
    Packaging distro:
Features:
    dbengine:                   YES
    Native HTTPS:               YES
    Netdata Cloud:              YES
    ACLK Next Generation:       YES
    ACLK-NG New Cloud Protocol: YES
    ACLK Legacy:                NO
    TLS Host Verification:      YES
    Machine Learning:           YES
    Stream Compression:         YES
Libraries:
    protobuf:                YES (system)
    jemalloc:                NO
    JSON-C:                  YES
    libcap:                  NO
    libcrypto:               YES
    libm:                    YES
    tcalloc:                 NO
    zlib:                    YES
Plugins:
    apps:                    YES
    cgroup Network Tracking: YES
    CUPS:                    YES
    EBPF:                    YES
    IPMI:                    YES
    NFACCT:                  YES
    perf:                    YES
    slabinfo:                YES
    Xen:                     NO
    Xen VBD Error Tracking:  NO
Exporters:
    AWS Kinesis:             NO
    GCP PubSub:              NO
    MongoDB:                 NO
    Prometheus Remote Write: YES
```

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
`scaling_cur_freq` reports the current CPU frequency as seen by the kernel. It's not the same as the real CPU frequency. We should provide information on the frequency reported by the hardware (`cpuinfo_cur_freq`). The PR adds a new chart `cpu.hw_cpufreq`. It is disabled by default because CPU performance scaling drivers usually read MSR registers to get the information.

Fixes #13116

##### Test Plan
1. Set `hardware cpu frequency = yes` in the `[plugin:proc:/proc/stat]` section of `netdata.conf`.
2. Run Netdata on a Linux system installed on bare metal.
3. Check the `cpu.hw_cpufreq` chart.

### CODE REVIEW

**Review by thiagoftsm — DISMISSED** [review]
On my hardware I do not have the necessary files to test according kernel official documentation:

```sh
cpuinfo_cur_freq

    Current frequency of the CPUs belonging to this policy as obtained from the hardware (in KHz).

    This is expected to be the frequency the hardware actually runs at. If that frequency cannot be determined, this attribute should not be present.
```

, but the logic is correct and other charts were not affected, so LGTM!

**Comment by vlvkobal** [comment]
Hm 🤔 ... Found this in the kernel source
[`cpufreq_freq_attr_ro_perm(cpuinfo_cur_freq, 0400);`](https://elixir.bootlin.com/linux/v5.19/source/drivers/cpufreq/cpufreq.c#L913)
@ilyam8, what do you think?

**Comment by ilyam8** [comment]
I think this PR is wontfix, @vlvkobal 😄

**Comment by vlvkobal** [comment]
I'm closing this because Netdata needs root permissions to read `cpuinfo_cur_freq` so the chart has very limited application.

**Pull request closed without merging**
