### PR TITLE
python.d/gearmand: handle func prefixes in `status\n` response

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

Fixes: #9604

##### Component Name

`python.d/gearmand`

##### Test Plan

@bokutin could you test this PR? [This case](https://github.com/netdata/netdata/issues/9604#issuecomment-664159099) should be handled.

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/gearman/gearman.chart.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5913794&bid=19375944)

**Comment by bokutin** [comment]
I tried running it in my environment.

1. The document output example does not include tabs, is that okay?

> Example output returned from
> _get_raw_data():
> prefix generic_worker4 78      78      500
> generic_worker2 78      78      500
> generic_worker3 0       0       760
> generic_worker1 0       0       500

2. Didn't work.

```
# grep gearman /var/log/netdata/error.log
2020-07-27 17:38:14: python.d WARNING: plugin[main] : gearman[localhost] : unhandled exception on check : AttributeError("'bytes' object has no attribute 'encode'"), skipping the job

```

**Comment by ilyam8** [comment]
@bokutin i guess this is `py2` problem, could you try `py3`?

- py2

> ./python.d.plugin debug gearman -ppython2

- py3
 
> ./python.d.plugin debug gearman -ppython3

**Comment by bokutin** [comment]
I tried it again and it seems to work fine.
It is also displayed on the http://127.0.0.1:19999/

Great!

```
oka root # uname -a
FreeBSD oka 12.1-RELEASE-p6 FreeBSD 12.1-RELEASE-p6 GENERIC  amd64
oka root # pkg info netdata
netdata-1.23.1
Name           : netdata
Version        : 1.23.1
Installed on   : Mon Jul 27 09:47:30 2020 JST
Origin         : net-mgmt/netdata
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : net-mgmt
Licenses       : GPLv3
Maintainer     : ports@FreeBSD.org
WWW            : https://github.com/netdata/netdata
Comment        : Scalable distributed realtime performance and health monitoring
Options        :
        CLOUD          : off
        CUPS           : off
        DBENGINE       : on
        FREEIPMI       : off
        GOPLUGIN       : off
        LTO            : on
Shared Libs required:
        libJudy.so.1
        liblz4.so.1
        libuuid.so.1
        libjson-c.so.5
        libuv.so.1
Annotations    :
        FreeBSD_version: 1201000
        cpe            : cpe:2.3:a:netdata:netdata:1.23.1:::::freebsd12:x64
        repo_type      : binary
        repository     : 121amd64-local-2020Q3
Flat size      : 6.77MiB
Description    :
Netdata is scalable distributed realtime performance & health monitoring system
netdata collects and visualizes metrics.
If it is a number and it can be collected somehow, netdata can visualize it.
Out of the box, it comes with plugins that collect hundreds of
system metrics and metrics of popular applications.
Netdata is very resource efficient and you can control its resource consumption.
It will use some spare CPU cycles, usually just 1-3% of a single core,
the RAM you want it have, and no disk I/O at all, apart its logging.

WWW: https://github.com/netdata/netdata
oka root # pkg info -d netdata
netdata-1.23.1:
        bash-5.0.17
        py37-urllib3-1.25.7,1
        e2fsprogs-libuuid-1.45.6
        python37-3.7.8
        curl-7.71.0
        py37-yaml-5.3.1
        pkgconf-1.7.3,1
        libuv-1.38.0
        Judy-1.0.5_2
        json-c-0.14
        liblz4-1.9.2_1,1
oka root # diff -u /usr/local/libexec/netdata/python.d/gearman.chart.py-00 /usr/local/libexec/netdata/python.d/gearman.chart.py
--- /usr/local/libexec/netdata/python.d/gearman.chart.py-00     2020-07-25 12:00:19.000000000 +0900
+++ /usr/local/libexec/netdata/python.d/gearman.chart.py        2020-07-27 17:35:17.879120000 +0900
@@ -121,6 +121,7 @@

         Example output returned from
         _get_raw_data():
+        prefix generic_worker4 78      78      500
         generic_worker2 78      78      500
         generic_worker3 0       0       760
         generic_worker1 0       0       500
@@ -137,13 +138,24 @@
             self.debug("Gearman returned no data")
             raise GearmanReadException()

-        job_lines = raw.splitlines()[:-1]
-        job_lines = [job.split() for job in sorted(job_lines)]
+        workers = list()

-        for line in job_lines:
-            line[1:] = map(int, line[1:])
+        for line in raw.splitlines()[:-1]:
+            parts = line.split()
+            if not parts:
+                continue

-        return job_lines
+            name = '_'.join(parts[:-3])
+            try:
+                values = [int(w) for w in parts[-3:]]
+            except ValueError:
+                continue
+
+            w = [name]
+            w.extend(values)
+            workers.append(w)
+
+        return workers

     def process_jobs(self, active_jobs):
```

**Pull request merged**
