### PR TITLE
Replace `info` macro with a less generic name

### PR DESCRIPTION
**Pull request by carlocab**
I apologise in advance for the gigantic PR.

##### Summary
The `info` macro is terribly generic, and can cause compilation problems with other software.

In particular, newer versions of Protobuf (22+) pull in Abseil, which defines an `info` function[^1] that is broken by the `info` macro defined in `libnetdata/log/log.h`.

This change will help unblock us at Homebrew, where we are trying to switch our packages to using a newer version of `protobuf`.[^2]

[^1]: https://github.com/abseil/abseil-cpp/blob/e6c09ae4b2acd421a29706f86e66eaa422262ad0/absl/strings/internal/cordz_update_scope.h#L61
[^2]: https://github.com/Homebrew/homebrew-core/pull/133746

##### Test Plan

I successfully built v1.40.0 with a backported version of this patch using the netdata [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/467a1c240301f7179830aeb762ba3baf1e79cecd/Formula/netdata.rb). This build would have failed if I failed to change an instance of the `info` macro to `netdata_log_info`. Similarly, it is very likely that making this change where it was not appropriate would've caused a build failure too.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
This will unblock building against newer versions of Protobuf, which presumably will happen at some point.  

</details>

### CODE REVIEW

**Comment by carlocab** [comment]
Oops, made a last minute change on my first push that I didn't fix everywhere. This should be fine now 🤞.

**Comment by thiagoftsm** [comment]
Hello @carlocab ,

You do not need to apologize for the PR size, we are thankful for your effort and contribution. 
I am sorry for the delay! Unfortunately I was busy past days and I am seeing that your PR has some conflicts after other codes were merged,  can you rebase it?
I am adding [these](https://github.com/netdata/netdata/files/11910380/err.txt) logs for you see current errors during compilation time.

As soon you rebase I will review it as one of my top priorities.

Best regards!

**Comment by carlocab** [comment]
Thanks, @thiagoftsm! Let me rebase this and work on the errors from the log you attached.

**Comment by thiagoftsm** [comment]
> Thanks, @thiagoftsm! Let me rebase this and work on the errors from the log you attached.

I am already reviewing code and compiling again locally. :handshake:

**Review by thiagoftsm — APPROVED** [review]
I ran a `grep` to verify whether some function rename was missed, and I could not find.
I also ran `netdata` during few minutes and I had logs as expected.
Finally, @stelfrag, after to merge this, probably we will need to make another renaming `error` to `netdata_log_error`. :thinking: 

Thank you one more time @carlocab !

**Review by Dim-P — APPROVED** [review]
Thank you for your contribution @carlocab !

All looks good to me (you even changed the commented out code :) ). 

I ran the PR and all works as expected.

**Comment by thiagoftsm** [comment]
Thank you very much @carlocab !
I will make another pr renaming our `error` function next week. :handshake:

**Comment by carlocab** [comment]
Thanks for the lightning-quick review and merge! This was a very pleasant contribution experience.

> I will make another pr renaming our `error` function next week. 🤝

I thought about doing that here too, but I realised it wasn't as necessary as renaming `info` (because leaving it as is didn't cause any build problems for us), and I didn't want to make this PR harder to review that it already was.

Feel free to let me know if you'd like my help doing this!

**Comment by thiagoftsm** [comment]
Hello @carlocab ,

I am glad that you had this feeling after this contribution.

I already made a [PR](https://github.com/netdata/netdata/pull/15296) today to modify `error`. Few free to take a look on it and verify that Homebrew will not have issues after this.

Best regards!

**Pull request merged**
