### PR TITLE
Check in ACLK_NG if --disable-https is used

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Adds a check during configure for ACLK_NG if `--disable-https` is used, thus skipping build of aclk_ng which requires SSL libraries.

##### Component Name

Installer.

##### Test Plan

Ensure `aclk-ng` requirements are there (protobuf, submodules).
Try to build master with `--disable-https`. `aclk-ng` should fail, since it requires openssl libraries
With this PR, if `--disable-https` is used, it will also prevent `aclk-ng` and `aclk-legacy` from being built, but allowing a build to complete.

##### Additional Information

This PR assumes we can not have cloud connectivity without ssl.

### CODE REVIEW

**Comment by Ferroin** [comment]
I would argue that this is _not_ the correct fix here. The dbengine depends on OpenSSL, but the configure script properly handles that even if HTTPS is disabled (last I checked it does at least). The fact that the ACLK-NG code does not handle this case correctly is a bug in the configure script, and should be fixed in the configure script, not in the installer.

**Comment by MrZammler** [comment]
> I would argue that this is _not_ the correct fix here. The dbengine depends on OpenSSL, but the configure script properly handles that even if HTTPS is disabled (last I checked it does at least). The fact that the ACLK-NG code does not handle this case correctly is a bug in the configure script, and should be fixed in the configure script, not in the installer.

I agree with what you're saying, but does `--disable-https` mean don't use openssl libraries? Because even with this option, dbengine does get built if it finds the openssl libraries it needs...

But if `--disable-https` means don't communicate over https, then also setting `--disable-cloud` might be more clean, in a way that we also skip libmosquitto, websockets legacy aclk, and aclk-ng which do not make sense to build in a non-https environment (can they work over plain http?).

I understand your point though, and I'm not firm on the above, and also I could have mis-intepreted what we mean by `--disable-https`

**Comment by Ferroin** [comment]
> > I would argue that this is _not_ the correct fix here. The dbengine depends on OpenSSL, but the configure script properly handles that even if HTTPS is disabled (last I checked it does at least). The fact that the ACLK-NG code does not handle this case correctly is a bug in the configure script, and should be fixed in the configure script, not in the installer.
> 
> I agree with what you're saying, but does `--disable-https` mean don't use openssl libraries? Because even with this option, dbengine does get built if it finds the openssl libraries it needs...
> 
> But if `--disable-https` means don't communicate over https, then also setting `--disable-cloud` might be more clean, in a way that we also skip libmosquitto, websockets legacy aclk, and aclk-ng which do not make sense to build in a non-https environment (can they work over plain http?).
> 
> I understand your point though, and I'm not firm on the above, and also I could have mis-intepreted what we mean by `--disable-https`
> 

AFAIK, the intent of `--disable-https` has always been to disable support in _our integrated webserver_ for HTTPS. It’s a feature that seems to see very limited use to begin with, so confusion surrounding this flag is understandable. The behavior _I_ would expect is for any enable/disable configure options to turn on and off that specific feature, and then for the configure script to figure out what libraries it needs based on what features are enabled/disabled. If we _really_ want to have a switch to globally disable using a TLS library (which I would argue is not something we care about), it should be called something like `--without-tls`.

**Comment by MrZammler** [comment]
Ok, you're the boss :-)

I've reverted the change in the installer, and added instead a check in configure for aclk-ng. It should skip building it now, of course if @underhood has other idea/solution it's welcome!

**Comment by Ferroin** [comment]
My point wasn’t just about where the ‘fix’ was happening, but also that the logic was wrong. If the ACLK-NG code needs a TLS library, it should be looking for one, not just relying on another feature that happens to pull one in being enabled.

**Review by underhood — APPROVED** [review]

**Review by underhood — COMMENTED** [review]
Technically correct but i would like message separate for this case. So the user knows SSL is available but it was disabled.

**Comment by underhood** [comment]
@Ferroin your argument makes sense.... basically you are saying
--disable-https should disable https in web server ... it should not have meaning equivalent with do not link SSL

if we agree it should be so then correct way would be to add linking of SSL in case --disable-https is used and aclk is built and perhaps add another flag like `--disable-crypto`  which would allow user to say no SSL at all?

**Comment by Ferroin** [comment]
> @Ferroin your argument makes sense.... basically you are saying --disable-https should disable https in web server ... it should not have meaning equivalent with do not link SSL
> 
> if we agree it should be so then correct way would be to add linking of SSL in case --disable-https is used and aclk is built and perhaps add another flag like `--disable-crypto` which would allow user to say no SSL at all?

I would definitely include a flag to skip linking any SSL/TLS implementation, though my suggestion would be `--without-tls` to disable linking any SSL/TLS library, as that0s generally the ‘standard’ way to prevent linking libraries that may be used by a number of features.

**Comment by underhood** [comment]
Ok assuming this PR to be irrelevant from now on. As we seem to be in agreement for different solution

**Comment by MrZammler** [comment]
Ok, I agree with the above, and will close this PR without merging. Likely `--disable-https` will need to change what it does now (`--without-tls` will probably do it in it's place).

**Comment by Ferroin** [comment]
> Ok, I agree with the above, and will close this PR without merging. Likely `--disable-https` will need to change what it does now (`--without-tls` will probably do it in it's place).

No, `--disable-https` should still prevent building the HTTPS code in the internal web server, independent of whether we are linking a TLS implementation or not.

**Pull request closed without merging**
