### PR TITLE
exclude web/gui/src from codacy checks

### PR DESCRIPTION
**Pull request by paulfantom**
##### Summary

Remove web/ugi/src from codacy checks

##### Component Name

CI

##### Additional Information

More in #4496

### CODE REVIEW

**Comment by gmosx** [comment]
@paulfantom , I have already done this here:

https://github.com/gmosx/netdata/commit/ead19e8ec9d385e5e452ff21eda8ed18a9c2eb86

Can you please ignore that PR for the moment? Let me finalize the changes to `dashboard.js` first.

**Comment by paulfantom** [comment]
You added lgtm config to a wrong file and with old configuration schema. 

LGTM config is in https://github.com/netdata/netdata/blob/master/.lgtm.yml

**Comment by gmosx** [comment]
@paulfantom 

Is this correct?

https://github.com/gmosx/netdata/commit/51834324682fe31de89144258b739740c71dee18

**Comment by paulfantom** [comment]
Yes, this is correct.

Docs on how to configure LGTM for netdata are in `.lgtm.yml` file with proper links.

**Comment by paulfantom** [comment]
As for ignoring this PR, there is no need as this can be merged before merging your PR with `dashboard.js` refactor. It won't cause CI to fail.

**Comment by gmosx** [comment]
Indeed the comments on the top of the file where very helpful 👍

**Pull request merged**
