### PR TITLE
Fix intermittent permissions issues in some Docker builds.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

Some builds using Podman/Buildah in place of Docker for the build process seem to leave strange permissions in the resultant containers. This adds code to handle those issues and fix them so that the containers still work.

##### Test Plan

Confirm that containers still work correctly with this PR (can’t really test the specific problem case this is fixing as nobody else seems to be able to reproduce it).

##### Additional Information

Fixes: #14237

### CODE REVIEW

**Comment by tkatsoulas** [comment]
Need more time to review this, first thing tomorrow

**Review by Dim-P — APPROVED** [review]
No issues noticed while testing, looks good!

**Review by thiagoftsm — APPROVED** [review]
CI passed with success and I did not have any problems on localhost, LGTM!

**Comment by com6056** [comment]
I'm now getting the following error when the `netdata` container starts up:
```
chmod: /: Operation not permitted
```

Checked and I believe all my permissions are correct, running with `podman` via `docker-compose`:
```
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: plum
    restart: always
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS}
      - PODMAN_HOST=docker-socket-proxy:2375
    user: 1011:1011 # netdata
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - label=disable
    volumes:
      - /var/lib/netdata/etc:/etc/netdata:z
      - /var/lib/netdata/lib:/var/lib/netdata:z
      - /var/lib/netdata/cache:/var/cache/netdata:z
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
```

**Pull request merged**
