### PR TITLE
update netdata.conf for debian build

### PR DESCRIPTION
**Pull request by and0x000**
##### Summary

netdata.conf in directory system was updated but debian build uses old version. The old version is potentially insecure, as it binds to all interfaces by default, thus exposing netdata on public interfaces.

##### Component Name

packaging

### CODE REVIEW

**Comment by prologic** [comment]
Hi @and0x000 I finally have a PR #8468 up for #8405 -- Would you be willing to amend your PR here to reflect the changes I'm making there oto and use the same pattern? I'd rather avoid having multiple copies of files, it gets confusing which is which :)

**Comment by and0x000** [comment]
> Hi @and0x000 I finally have a PR #8468 up for #8405 -- Would you be willing to amend your PR here to reflect the changes I'm making there oto and use the same pattern? I'd rather avoid having multiple copies of files, it gets confusing which is which :)

Yes, a single source of truth is more favorable, I totally agree with you.
I rebased onto your branch for #8468 and used the same schema to pull the netdata.conf file

**Comment by prologic** [comment]
> If you want to include this into your PR right away, feel free to do so and discard my PR.

Thank you. I will! I'll cherry-pick your commits and preserve your authorship. Thank you! I'm still testing and have found further problems that I will fix before getting review and merging.

**Comment by prologic** [comment]
cherry-picked into #8468

**Pull request closed without merging**
