### PR TITLE
[WIP] Web workspaces redirect

### LINKED ISSUE #7023: Redirect `/workspaces/` request to console.html
##### Feature idea summary
The cloud team is bringing a new feature that needs redirects from Netdata agent. Everytime that the agent receives a request for ```https//localhost:19999/workspaces/YYY``` where ```YYY``` is a "random" value, the agent needs to redirect to ```https//localhost:19999/console.html```
##### Expected behavior
Redirects must happen with ```workspaces``` request

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes #7023 

This PR brings a feature requested from cloud team to enable new cloud structure.
##### Component Name
Web

### CODE REVIEW

**Comment by thiagoftsm** [comment]
> Seems to be doing what's needed, however I'm not proficient in C. Maybe this is the way to write web in C, but to me it seems hard to grasp, even such a simple thing as being done here.

Thank you, do not worry the other guys will see the C code, I am glad that I could help you!

**Comment by thiagoftsm** [comment]
We have a meeting talking about this feature and we agreed that this specific PR won't be merged, the [WIP] in its titles is a way to remember us this, but it is done to be used.
I will continue doing the necessary rebase to keep it updated when it is necessary.

**Comment by Ferroin** [comment]
This will require a rebase or merge of the most recent master branch to trigger Travis checks to run.

**Comment by ilyam8** [comment]
@thiagoftsm probably it makes sense to close this one and open a new one as a draft to not get notified on every merge.

**Comment by thiagoftsm** [comment]
The cloud is up and running, so I suppose we do not need to keep more this PR.
@Azein case it is necessary, please, let me know for I update and reopen it.

**Pull request closed without merging**
