### PR TITLE
[BUGFIX] MQTT ARM fix

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Fixes https://github.com/netdata/netdata/issues/14696
##### Test Plan
Needs to be well tested (recommending to test on high load node before merging) as this modifies code that is core.

TLDR:
1. verify this actually fixes bug mentioned above
2. to be paranoid (as ACLK is critical component) verify it runs well preferably on a node with high cloud/agent (ACLK) traffic.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by ilyam8** [comment]
Static arm7l build no longer crashes on an aarch64 node after this PR.

**Review by ilyam8 — APPROVED** [review]

**Review by stelfrag — APPROVED** [review]

**Comment by lara29** [comment]
@underhood thank you for fixing this problem, we're looking forward to it. Do you know when this fix will be released as part of an official release?

**Comment by ilyam8** [comment]
@lara29 v1.43.0 is scheduled for today.

**Comment by lara29** [comment]
@ilyam8 great news, thank you!

**Pull request merged**
