### PR TITLE
Add 1min_node_anomaly_rate alert template

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This PR adds a new alert template called `1min_node_anomaly_rate`. It calculates the average last 1 minute of anomaly rate and is available to be used in the calculation of any other alert. There will be more commits that will add a way for this value (or any alert value) to be printed in info fields of alerts.

The PR adds two new options. One is `localhost-anomaly-rate` in the options of the lookup. When this is present and the template context is `anomaly_detection.anomaly_rate` it will make sure that the template will be attached to the anomaly rate chart produced by the localhost.

The other is an alert option `set-global`. When this is set in an alert, a reference to it will be added to the host's rrdvars for reference from other alerts, using only it's name. Of course this only makes sense when the alert produced is unique, otherwise a random instance will be created.

More info at #14701 

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by MrZammler** [comment]
Added a new variable in info fields, called `${value:`. When this is added, when an alert event is raised, it can print the value of any alert variable into the info field. For example, by setting in alarm `memory_in_use` the following info field:

`info: System memory utilization. Currently the 1min average node anomaly rate is ${value:1min_node_anomaly_rate}%. Swap usage is ${value:system.swap.used_swap}% and last 10 minute cpu usage is ${value:system.cpu.10min_cpu_usage}%.`

We get in the notification:

image

**Comment by andrewm4894** [comment]
@MrZammler any way to see if we can rebase this at some stage - I'm hoping to try resurrect it and see if we can get it to a conclusion in next couple of weeks. 

It's on me that i didn't follow up properly but I'd like to see if we can make another go at it and use the work you have already done here as 1st part of the puzzle.

**Comment by andrewm4894** [comment]
hmm i seem to be getting this error when trying to install:

```
make[2]: Entering directory '/netdata'
  CC       collectors/apps.plugin/apps_plugin.o
In file included from ./libnetdata/locks/locks.h:7,
                 from ./libnetdata/libnetdata.h:810,
                 from ./daemon/common.h:6,
                 from ./collectors/all.h:6,
                 from collectors/apps.plugin/apps_plugin.c:9:
./libnetdata/locks/../clocks/clocks.h:9:8: error: redefinition of 'struct timespec'
    9 | struct timespec {
      |        ^~~~~~~~
In file included from /usr/include/sched.h:32,
                 from /usr/include/pthread.h:22,
                 from ./libnetdata/libnetdata.h:89,
                 from ./daemon/common.h:6,
                 from ./collectors/all.h:6,
                 from collectors/apps.plugin/apps_plugin.c:9:
/usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h:10:8: note: originally defined here
   10 | struct timespec
      |        ^~~~~~~~
In file included from ./libnetdata/locks/locks.h:7,
                 from ./libnetdata/libnetdata.h:810,
                 from ./daemon/common.h:6,
                 from ./collectors/all.h:6,
                 from collectors/apps.plugin/apps_plugin.c:9:
./libnetdata/locks/../clocks/clocks.h:85:5: error: conflicting types for 'clock_gettime'
   85 | int clock_gettime(clockid_t clk_id, struct timespec *ts);
      |     ^~~~~~~~~~~~~
In file included from /usr/include/pthread.h:23,
                 from ./libnetdata/libnetdata.h:89,
                 from ./daemon/common.h:6,
                 from ./collectors/all.h:6,
                 from collectors/apps.plugin/apps_plugin.c:9:
/usr/include/time.h:213:12: note: previous declaration of 'clock_gettime' was here
  213 | extern int clock_gettime (clockid_t __clock_id, struct timespec *__tp) __THROW;
      |            ^~~~~~~~~~~~~
collectors/apps.plugin/apps_plugin.c: In function 'parse_args':
collectors/apps.plugin/apps_plugin.c:4354:40: error: 'VERSION' undeclared (first use in this function); did you mean 'CMD_VERSION'?
 4354 |             printf("apps.plugin %s\n", VERSION);
      |                                        ^~~~~~~
      |                                        CMD_VERSION
collectors/apps.plugin/apps_plugin.c:4354:40: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:7307: collectors/apps.plugin/apps_plugin.o] Error 1
make[2]: Leaving directory '/netdata'
make[1]: *** [Makefile:9671: all-recursive] Error 1
make[1]: Leaving directory '/netdata'
make: *** [Makefile:4352: all] Error 2
 FAILED  ''

 ABORTED  Failed to build Netdata. 
```

**Comment by MrZammler** [comment]
Hmm, weird error... CI passes, and just tried a local build and it was ok, let's check...

**Comment by andrewm4894** [comment]
hmm i got some strange overflow looking thing like this 

image

**Comment by andrewm4894** [comment]
i used the gist from @ralphm to make a dummy alert and trigger it and i see below.

```/health.d/dummy.conf
#
# This creates an alert on a statsd gauge metric named `test`. If the gauge is
# at or over 50, it will trigger a warning, if at or over 100, a critical
# alert. Note that statd gauges are considered no longer collected if there was
# no update for 10 minutes. In this case, this alert also goes away.
#
# To send the value `88` to this metric use this command:
#
#     echo "test:88|g" | nc -w 1 localhost 8125

 template: statsd_test
       on: statsd_test.gauge
    class: Test
     type: System
component: StatsD
       os: linux freebsd
    hosts: *
     calc: $gauge
    units: {foo}
    every: 10s
     warn: $this >= 50
     crit: $this >= 100
     info: Amount of foo (Node AR% ${value:1min_node_anomaly_rate}%)
       to: sysadmin
```

image

**Comment by MrZammler** [comment]
Hmmm, yeah, not pretty... I've added to print 2 decimals only.

Can you check when this alert fired what the value of node anomaly rate was? You can also check that specific value by going to e.g. `http://localhost:19999/api/v1/alarm_variables?chart=system.cpu` there should be an `1min_node_anomaly_rate` entry there.

There is a check to print `null` when the value is inf or nan, but not sure what happened there...

**Comment by andrewm4894** [comment]
@MrZammler added a dummy alert to help us test and iterate on the formatting etc. 

I'll play around a bit and ping you when i think i have something ready to get ready for wider review.

**Comment by andrewm4894** [comment]
@MrZammler this is working as expected for me so feel free to mark as ready for review whenever you happy to. Once this is merged i will create a follow on PR to update some `info` fields in the conf files in `health.d/` to use this new template variable by default in some existing alerts.

**Comment by andrewm4894** [comment]
I actually think we would need to merge this PR first and then update the template to fit with this PR.

https://github.com/netdata/netdata/pull/14687

#14687 basically enables the 1 min node ar as a default alert. Once that is merged then we can rebase this PR to I think basically just add the set global options and maybe the localhost thing too.

**Comment by MrZammler** [comment]
Ok Andy thanks. Let me check the PR again (been a while) to see if anything missing, and will open it for reviews.

**Comment by MrZammler** [comment]
> I actually think we would need to merge this PR first and then update the template to fit with this PR.
> 
> #14687
> 
> #14687 basically enables the 1 min node ar as a default alert. Once that is merged then we can rebase this PR to I think basically just add the set global options and maybe the localhost thing too.

Indeed Andy. In the end we should have only one such alert, will work both as a standalone alert as you want in #14687 and as a source of values to be used in other alerts as we do here.

I can update this PR with the changes you did in #14687 (basically the `warn`) and proceed like this?

**Comment by andrewm4894** [comment]
Let's wait for the other pr and this one can be reviewed in meantime on its own merits. 

Then when other one is merged we just rebase and update the ml.conf file to do the set global stuff as needed etc.

**Pull request closed without merging**
