### PR TITLE
Remove mention saying that .deb packages are experimental

### PR DESCRIPTION
**Pull request by toadjaune**
##### Summary

Since the release of 0.17.0 version, .deb packages are present on the stable repo.
No need to use the edge repo to ged .deb packages.

##### Component Name

N/A

##### Description of testing that the developer performed

None, documentation PR.

### CODE REVIEW

**Comment by joelhans** [comment]
The change LGTM, but requested a review from @Ferroin to confirm that removing the experimental label is OK.

**Comment by Ferroin** [comment]
> The change LGTM, but requested a review from @Ferroin to confirm that removing the experimental label is OK.

I'll be discussing this later today with the rest of the SRE team.

**Comment by joelhans** [comment]
> I'll be discussing this later today with the rest of the SRE team.

Sounds good. We'll hold on this until you all have a decision.

**Comment by Ferroin** [comment]
This will require a rebase or merge of the most recent master branch to trigger Travis checks to run.

**Comment by Ferroin** [comment]
@joelhans The consensus on the SRE team is that this change is correct, and should be merged. If you would care to review it so that we can have an approval from the people responsible for the documentation, that would be great.

@toadjaune As I mentioned in a comment above, this will need either a rebase or a merge of the current master branch so that the CI checks get run correctly before it can be merged. If you want, I can take care of that for you.

**Comment by prologic** [comment]
> @toadjaune As I mentioned in a comment above, this will need either a rebase or a merge of the current master branch so that the CI checks get run correctly before it can be merged. If you want, I can take care of that for you.

@Ferroin We should just enable and require that branches be up-to-date. Its something we can turn on in "Required Checks".

**Comment by toadjaune** [comment]
Seems like I'm back once the problem is solved. Is there anything left to do on my side ?

**Pull request merged**
