### PR TITLE
Allows ACLK NG and Legacy to coexist

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
This allows both ACLK-NG and Legacy to coexist together and agent decides at startup which one will be used based on `aclk implementation` config param of `cloud` section of `netdata.conf`

This has origin in good idea from @Ferroin (asking why can't we have both :D)

Some of the things can be done nicer... e.g. aclk_stats of `NG` and `Legacy` could be merged. This is not done as this should be done with minimal amount of effort as `Legacy` will be removed soon (would be lot of wasted effort) + time pressures.

##### Component Name
ACLK, ACLK-NG

### CODE REVIEW

**Comment by underhood** [comment]
@Ferroin question here would be what do we cover with CI after such a drastic change... + does it make sense to do the work (update the CI) considering in few weeks if everything goes well Legacy ACLK will not exist anymore

**Comment by underhood** [comment]
CI failure on CentOS 8 seems unrelated and also breaks on #11224

**Comment by Ferroin** [comment]
> @Ferroin question here would be what do we cover with CI after such a drastic change... + does it make sense to do the work (update the CI) considering in few weeks if everything goes well Legacy ACLK will not exist anymore

How likely are to leverage this for future revisions to the ACLK functionality? That’s really the deciding factor here IMO.

**Comment by underhood** [comment]
> > @Ferroin question here would be what do we cover with CI after such a drastic change... + does it make sense to do the work (update the CI) considering in few weeks if everything goes well Legacy ACLK will not exist anymore
> 
> How likely are to leverage this for future revisions to the ACLK functionality? That’s really the deciding factor here IMO.

Not at all. The idea is to get rid of legacy ASAP. We are keeping it in case some users have issues we are not aware of yet and which might take longer time to fix/implement. (in which case we can tell to user... we are working on it please use Legacy till then)

**Comment by Ferroin** [comment]
> > > @Ferroin question here would be what do we cover with CI after such a drastic change... + does it make sense to do the work (update the CI) considering in few weeks if everything goes well Legacy ACLK will not exist anymore
> > 
> > 
> > How likely are to leverage this for future revisions to the ACLK functionality? That’s really the deciding factor here IMO.
> 
> Not at all. The idea is to get rid of ACLK-Legacy ASAP. We are keeping it in case some users have issues we are not aware of yet and which might take longer time to fix/implement. (in which case we can tell to user... we are working on it please use Legacy till then)

In that case I see little to no value in special CI for checking the runtime selection.

We obviously ideally do want CI to provide some basic verification of the ACLK code itself though, but that should probably be in the unit tests.

**Review by stelfrag — APPROVED** [review]

**Review by MrZammler — APPROVED** [review]

**Pull request merged**
