### PR TITLE
collectors/python.d: format modules code

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

ssia

This is just auto format python.d modules code

##### Component Name

[/collectors/python.d.plugin/](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin)

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=4876301&bid=16161900)

**Comment by prologic** [comment]
@ilyam8 Can you please share what tool you used to do this? Hopefully you used [Black](https://black.readthedocs.io/en/stable/)?

**Comment by ilyam8** [comment]
@prologic i us jb tools for coding (pycharm/goland) and i use built-in formatters

**Comment by prologic** [comment]
> @prologic i us jb tools for coding (pycharm/goland) and i use built-in formatters

Ahh that's a shame. It'll be a bit tricky to review/validate this PR then. But I'll checkout master and run `black` against the Python codebase and see if it mostly matches up with yours :) -- Maybe your IDE runs `black` anyway?

**Comment by ilyam8** [comment]
> if it mostly matches up with yours

i think it depends on configuration. Most of the changes are indentation changes, they are not tricky to review.

**Pull request merged**
