### PR TITLE
Update dashboard to version v2.21.2.

### PR DESCRIPTION
**Pull request by netdatabot**
See https://github.com/netdata/dashboard/releases/tag/v2.21.2 for changes.

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]

**Comment by stelfrag** [comment]
Is the !, at the end of the sentence on purpose ? 

image

**Comment by AlexNti** [comment]
> Is the !, at the end of the sentence on purpose ?
> 
> image

No, this is not on purpose. I will fix it

**Comment by ilyam8** [comment]
The node is connected, but the button is still gray. I assume it is supposed to get green?
 
Screenshot 2022-03-14 at 21 05 22

**Comment by ilyam8** [comment]
@AlexNti if that is possible, I'd suggest adding some delay for the first check. I get the following after every restart (the node becomes connected in few seconds):
Screenshot 2022-03-14 at 21 08 10

**Comment by AlexNti** [comment]
> The node is connected, but the button is still gray. I assume it is supposed to get green?
> 
> Screenshot 2022-03-14 at 21 05 22

You mean the `Check now`  button?
If so, this is used only for the refresh of the data. We care for the `Take me to the Netdata cloud` to not be gray, in this case it is not

**Comment by ilyam8** [comment]
@AlexNti, sorry for not being clear, I meant "Connection to Cloud" component. I see it has the same color and text regardless of the status, is it expected?

**Comment by AlexNti** [comment]
> @AlexNti, sorry for not being clear, I meant "Connection to Cloud" component. I see it has the same color and text regardless of the status, is it expected?

Oh, no problem :). This button does not change colour is always gray regardeless the connection status

**Comment by AlexNti** [comment]
> @AlexNti if that is possible, I'd suggest adding some delay for the first check. I get the following after every restart (the node becomes connected in a few seconds): Screenshot 2022-03-14 at 21 08 10

hmm, this does not seem to related with this PR. We have to make an investigation and find out where that is coming from.

**Comment by AlexNti** [comment]
We will create a new PR that will solve the typo that @stelfrag metioned.

**Pull request closed without merging**
