### PR TITLE
Fixed option parsing in kickstart.sh.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

The existing code is dependent on options specifically for the kickstart script coming before any options to be passed to the installer, resulting in some options being ignored if the were ordered in certain ways.

This fixes the parsing to explicitly parse _all_ options so that we are not dependent on option order.

##### Component Name

area/packaging

##### Test Plan

1. Create a new install of Netdata in a test environment using the kickstart script with the `--disable-telemetry` option (any option that gets passed to the `netdata-installer.sh` script will work).
2. Try to reinstall in the same environment using the kickstart script by adding `--reinstall` to the end of the command you used in step 1 (note, option order is important here, the `--reinstall` _must_ come after the other options).
3. Without this PR, step 2 will result in the updater script being run (with a message indicating that in the output). With this kickstart script from this PR, it will instead print the message `User requested reinstall instead of update, proceeding.` and not run the updater script.

##### Additional Information

Fixes: #10389 
Relevant to: #10372

### CODE REVIEW

**Review by thiagoftsm — APPROVED** [review]
I executed the same steps described and I also tried to install with other options, everything worked as expected. LGTM!

**Comment by stelfrag** [comment]
I tried this on docker / alpine. The current step (2) to reproduce the message gives me

```
bash-5.0# bash <(curl -Ss https://my-netdata.io/kickstart.sh) --disable-telemetry --reinstall
 --- Found existing install of Netdata under: / --- 
 --- Attempting to update existing install instead of creating a new one --- 
[/]# //usr/libexec/netdata/netdata-updater.sh --not-running-from-cron Checking if a newer version of the updater script is available.
date: invalid date '9999-12-31T23:59:59Z'
//usr/libexec/netdata/netdata-updater.sh: line 168: [: : integer expression expected
Tue Dec 15 17:18:04 UTC 2020 : INFO:  Running on a terminal - (this script also supports running headless from crontab)
Tue Dec 15 17:18:05 UTC 2020 : INFO:  Current Version: 00102600000391
Tue Dec 15 17:18:05 UTC 2020 : INFO:  Latest Version: 00102600000391
Tue Dec 15 17:18:05 UTC 2020 : INFO:  Newest version (current=00102600000391 >= latest=00102600000391) is already installed
 OK  
```

**Review by stelfrag — APPROVED** [review]
This works as describe and correctly processes the --reinstall option

There is however an issue with the updater  -- the date check doesn't seem to work on a docker alpine environment (unknown option) BusyBox v1.31.1

**Comment by Ferroin** [comment]
> This works as described and correctly processes the --reinstall option
> 
> There is however an issue with the updater -- the date check doesn't seem to work on a docker alpine environment (unknown option) BusyBox v1.31.1

I’m not 100% certain that it’s actually Alpine specific. We’re running in bash there just like everywhere else, and `[` is a builtin in bash, so it should work everywhere. The exact message is also usually indicative that _something_ is causing one of the two variables being compared on that line to not be integers. It’s probably just something that we have thus far only seen on Alpine.

**Pull request merged**
