### PR TITLE
Add CI check for building against LibreSSL

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

ssia

##### Component Name

- area/ci

##### Test Plan

- This PR and the new Checks
  - [ ] Should fail on master
  - [ ] Should pass on #8807

##### Additional Information

### CODE REVIEW

**Comment by prologic** [comment]
This works as intended and the CI check fails:

- https://github.com/netdata/netdata/pull/8842/checks?check_run_id=625033374

**Comment by prologic** [comment]
cc @thiagoftsm

**Comment by thiagoftsm** [comment]
Thank you @prologic !

I will rebase #8807 when this is merged.

**Comment by thiagoftsm** [comment]
@prologic I could compile everything on #8807 after to move the file changed here to the PR, please, do a double check.

**Pull request merged**
