### PR TITLE
Fix cachestat on kernel 5.15.x (eBPF)

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
This PR is bringing fix for `cachestat`when users are running kernel `5.15.x`.
It also removes the following warnings from eBPF.plugin changing the way we load eBPF program:

```bash
libbpf: kprobe perf_event_open() failed: No such file or directory
libbpf: prog 'netdata_lookup_fast': failed to create kprobe 'lookup_fast+0x0' perf event: No such file or directory
libbpf: prog 'netdata_md_flush_request': failed to create kprobe 'md_flush_request+0x0' perf event: No such file or directory
```

##### Component Name
ebpf.plugin
##### Test Plan

1 - Compile the branch
2 - Run eBPF.plugin with at least the following configuration:

```conf
[ebpf programs]
    cachestat = yes
    process = yes
    md = yes
```
3 - Run the following command that must have an empty output:

```bash
grep libbpf /var/log/netdata/error.log
```

##### Additional Information

This PR was already tested on

| Linux Distribution | kernel version |
|-------------------|----------------|
| Slackware Current | 5.15.4  |
| Arch Linux        | 5.15.5  |
| Manjaro 21.1 | 5.10.79-1 |
| Ubuntu 18.04 | 5.4.0-91 |
| Ubuntu 18.04 | 4.15.0-163 |
| CentOS 7.9 | 3.10.0-1160.49.1.el7 |

Ideally at least one reviewer (ping @vlvkobal ) needs to test on kernel `5.15.x`.

### CODE REVIEW

**Review by vlvkobal — APPROVED** [review]
I'm approving it, but I don't think we should make 1.32.1 specifically for this fix.

We should also keep in mind that a lot of changes (CO-RE support) were made to `netdata/kernel-collector` since the last release and they will be activated with this PR. They should be harmless, but still - there are a lot of changes.

**Review by iigorkarpov — APPROVED** [review]

**Review by vlvkobal — CHANGES_REQUESTED** [review]
`apps.cachestat_misses` and `mem.cachestat_misses` are always zero after the fix and they aren't in the master.

**Comment by thiagoftsm** [comment]
> `apps.cachestat_misses` and `mem.cachestat_misses` are always zero after the fix while they aren't in the master.

Depending of how long processes are running, it is not be a problem to have misses as zero. I started a VM with `Arch` and I ran `paman -Sc ; pacman -Syu`, because these commands would bring something new to cache, and the results for global charts:

Screenshot_20211203_112513

and for apps:

Screenshot_20211203_112626

were different of zero. An analogous behavior were observed at host where VM was running.

**Review by vlvkobal — APPROVED** [review]
Yep, I've been able to get non-zero values at last. Sorry for the inconvenience.

**Comment by thiagoftsm** [comment]
> Yep, I've been able to get non-zero values at last. Sorry for the inconvenience.

Do not worry, thank you to call attention for this! :)

**Pull request merged**
