### PR TITLE
Remove anomaly detector

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

This PR:

- Removes the anomaly detector
- Refactors the code to add support for multiple training models in a follow-up PR,
- Adds a new, simplified anomaly detection chart based on the rolling average of the host rate chart.

##### Test Plan

TBD.

### CODE REVIEW

**Comment by vkalintiris** [comment]
@andrewm4894 Can you test this?

The new "anomaly detection" logic is configurable with the following default values:

- `host anomaly rate threshold = 1.0`
- `anomaly detection grouping method = average`
- `anomaly detection grouping method = 300`

**Comment by andrewm4894** [comment]
Testing now. Will update here once node has trained and ran steady for a bit.

**Comment by andrewm4894** [comment]
This is working as expected. 

Can see when i trigger an elevated anomaly rate we get expected behaviour on 2nd chart.

Performance overhead characteristics all look as expected too. 

All looks good to me. 

image

**Comment by andrewm4894** [comment]
looks like was some issues today with this same node: https://netdata-cloud.slack.com/archives/C01K28B4V7Y/p1663148721951609

seeing lots of messages like this in log

```
2022-09-14 09:32:50: netdata ERROR : MAIN : Page cache is full. Sleeping for 8 second(s).
2022-09-14 09:32:50: netdata ERROR : PLUGIN[proc] : Page cache is full. Sleeping for 11 second(s).
2022-09-14 09:32:50: netdata ERROR : MAIN : Page cache is full. Sleeping for 13 second(s).
2022-09-14 09:32:54: netdata ERROR : HEALTH : Page cache is full. Sleeping for 14 second(s).
2022-09-14 09:32:55: netdata ERROR : PLUGINSD[apps] : Page cache is full. Sleeping for 3 second(s).
2022-09-14 09:32:55: netdata ERROR : PLUGIN[cgroups] : Page cache is full. Sleeping for 13 second(s).
2022-09-14 09:32:58: netdata ERROR : PLUGINSD[apps] : Page cache is full. Sleeping for 19 second(s).
2022-09-14 09:32:58: netdata ERROR : MAIN : Page cache is full. Sleeping for 14 second(s).
2022-09-14 09:33:01: netdata ERROR : PLUGIN[proc] : Page cache is full. Sleeping for 8 second(s).
2022-09-14 09:33:04: netdata ERROR : MAIN : Page cache is full. Sleeping for 13 second(s).
2022-09-14 09:33:09: netdata ERROR : PLUGIN[cgroups] : Page cache is full. Sleeping for 10 second(s).
2022-09-14 09:33:09: netdata ERROR : HEALTH : Page cache is full. Sleeping for 10 second(s).
2022-09-14 09:33:10: netdata ERROR : PLUGIN[proc] : Page cache is full. Sleeping for 1 second(s).
2022-09-14 09:33:11: netdata ERROR : PLUGIN[proc] : Page cache is full. Sleeping for 7 second(s).
2022-09-14 09:33:13: netdata ERROR : MAIN : Page cache is full. Sleeping for 15 second(s).
2022-09-14 09:33:17: netdata ERROR : PLUGINSD[apps] : Page cache is full. Sleeping for 14 second(s).
2022-09-14 09:33:18: netdata ERROR : MAIN : Page cache is full. Sleeping for 12 second(s).
2022-09-14 09:33:19: netdata ERROR : PLUGIN[proc] : Page cache is full. Sleeping for 2 second(s).
2022-09-14 09:33:19: netdata ERROR : HEALTH : Page cache is full. Sleeping for 16 second(s).
2022-09-14 09:33:20: netdata ERROR : PLUGIN[cgroups] : Page cache is full. Sleeping for 12 second(s).
2022-09-14 09:33:21: netdata ERROR : PLUGIN[proc] : Page cache is full. Sleeping for 18 second(s).
2022-09-14 09:33:28: netdata ERROR : MAIN : Page cache is full. Sleeping for 6 second(s).
2022-09-14 09:33:31: netdata LOG FLOOD PROTECTION too many logs (201 logs in 338 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 862 seconds.
2022-09-14 09:44:21: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:44:26: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:44:31: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:44:36: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:44:41: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:44:58: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:45:13: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:45:28: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:45:43: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:45:58: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:46:26: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
2022-09-14 09:46:56: python.d ERROR: alarms[ml] : Url: http://127.0.0.1:19999/api/v1/alarms?all. Error: HTTPConnectionPool(host='127.0.0.1', port=19999): Max retries exceeded with url: /api/v1/alarms?all (Caused by ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=19999): Read timed out. (read timeout=1)"))
```

image

image

image

image

image

**Comment by vkalintiris** [comment]
@andrewm4894 can you test once more the changes I pushed?

**Comment by andrewm4894** [comment]
testing now - will update here when node alive

**Comment by andrewm4894** [comment]
node is here: https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/nodes/4da9bd5f-1970-4f17-8cf4-3ff0450108a1#highlight_after=1664805574000&highlight_before=1664805721000&after=-600&before=0&utc=Europe%2FLondon&offset=%2B1&timezoneName=Edinburgh%2C%20London&metrics_correlation=false&chartName=menu_system&appliedFilteredIds=&liveNodeIds=&staleNodeIds=&offlineNodeIds=&filteredNodesSearchParams=

will let it train and see how it looks over next 24 hours

**Comment by andrewm4894** [comment]
@vkalintiris it seems like maybe you have renamed the `anomaly_detection.detector_events` to be `anomaly_detection.anomaly_detection`. 

image

i was expecting the name to be the same such that the `ml-demo-ml-enabled-multimodels01` node would just appear on the `anomaly_detection.detector_events` charts. 

Since that would mean not FE change to the AA tab.

I think, if possible we should stick to the `anomaly_detection.detector_events` chart id for backwards compatibility for now.

**Comment by andrewm4894** [comment]
looking as expected in terms of cpu

image

looking better in terms of mem (unsure if that is expected - maybe?): 

image

unsure if this disk reads behaviour is anything to worry about? 

image

writes look similar (with maybe a dead or quiet patch near end):

image

**Comment by andrewm4894** [comment]
Generally looking fine to me but have a look yourself and at above and see what you think.

**Comment by vkalintiris** [comment]
@andrewm4894 thanks for testing this.

> @vkalintiris it seems like maybe you have renamed the anomaly_detection.detector_events to be anomaly_detection.anomaly_detection.

Indeed, I fixed this in the latest (forced) push.

The charts you shared, LGTM.

**Comment by andrewm4894** [comment]
cool - ill drop and recreate and check again over next few hours.

**Comment by andrewm4894** [comment]
behaving as expected now. Will give it a few more hours to fully train and run and if all looking good i guess ready for undraft and review then.

**Comment by andrewm4894** [comment]
all looking good to me

**Review by andrewm4894 — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
I ran this PR during more than 1 hour, and everything worked as expected locally and on cloud. LGTM!

**Pull request merged**
