### PR TITLE
Ceph: Added OSD size collection

### PR DESCRIPTION
**Pull request by elelayan**
##### Summary

Added OSD size (=capacity) collection to the ceph plugin.
This will usually not vary:  an osd has a defined capacity based on the
underlying disk.
So it might not make sense to collect it, contrary to the osd_usage, which is the used space and varies as data is written to ceph.
But not collecting the osd_size prevents from computing used ratio (osd_usage / osd_size) or available space (osd_size - osd_usage), which are useful metrics.

##### Component Name

Ceph python plugin

##### Test Plan

I use the modified plugin on a production cluster:
 - PROXMOX Virtual Environment 6.1-8
 - Ceph version 14.2.8

I verified that the additional data was collected.

##### Additional Information

The 'kb' field has the same format as the 'kb_used' field in `ceph osd df --json` output.

Sample  `ceph osd df --json` output:

    {
      "nodes": [
        {
          "id": 12,
          "device_class": "ssd",
          "name": "osd.12",
          "type": "osd",
          "type_id": 0,
          "crush_weight": 1.8189849853515625,
          "depth": 2,
          "pool_weights": {},
          "reweight": 1,
          "kb": 1953513472,
          "kb_used": 723914120,
          "kb_used_data": 722465792,
          "kb_used_omap": 16,
          "kb_used_meta": 1448303,
          "kb_avail": 1229599352,
          "utilization": 37.05703238682349,
          "var": 0.6282679826388614,
          "pgs": 10,
          "status": "up"
        },
    
        (...)
    
      "stray": [],
      "summary": {
        "total_kb": 42477871104,
        "total_kb_used": 25054656432,
        "total_kb_used_data": 24961224336,
        "total_kb_used_omap": 13949325,
        "total_kb_used_meta": 79482162,
        "total_kb_avail": 17423214672,
        "average_utilization": 58.98284396281971,
        "min_var": 0.6262459694797988,
        "max_var": 1.2928955206659904,
        "dev": 13.779317402301619
      }

### CODE REVIEW

**Comment by ilyam8** [comment]
> But not collecting the osd_size prevents from computing used ratio (osd_usage / osd_size) or available space (osd_size - osd_usage), which are useful metrics.

> So it might not make sense to collect it

We can add them as variables to the `osd_usage` chart, what do you think?

**Comment by elelayan** [comment]
> > But not collecting the osd_size prevents from computing used ratio (osd_usage / osd_size) or available space (osd_size - osd_usage), which are useful metrics.
> 
> > So it might not make sense to collect it
> 
> We can add them as [variables](https://docs.netdata.cloud/collectors/plugins.d/#variable) to the `osd_usage` chart, what do you think?

Thanks for the suggestion. I'm not familiar with VARIABLES in netdata:
 - would that be multiple VARIABLE 'osd_size.1' ... 'osd_size.n'?
 - how would a 'osd_size.1' VARIABLE relate to the 'osd_usage.1' value?
 - could you point me to a similar graph?

**Comment by ilyam8** [comment]
I think having it as a separate chart is acceptable too. I recall we have some problems with vars during exporting data.

As for variables:

```python
...

self.definitions['pool_usage']['lines'].append([pool['name'], pool['name'], 'absolute'])
self.definitions['pool_usage']['variables'].append([pool['name'] + '_kb')
...
        return {osd['name'] + '_kb': float(osd['kb'])}
```

**Comment by elelayan** [comment]
Thanks @ilyam8, I'll experiment a bit more and try variables.

My PR was broken because osd_usage and osd_size had the same key (osd.x) so they overwrote each other, so I've pushed a fix.

**Comment by elelayan** [comment]
I've tried adding size variables to the osd_usage chart.

They would be useable in alarms (visible in `/api/v1/alarm_variables?chart=ceph_storage.osd_usage`).

But they seem unusable from prometheus :
 - I couldn't find them in prometheus query or grafana, even if they appear in the scrape output
 - in the scrape output they have no dimension so it wouldn't be easy to correlate them with usage, contrary to lines, where I could use the query (`netdata_ceph_osd_usage_KiB_average - ignoring(chart) netdata_ceph_osd_size_KiB_average`)
 - they would go stale after some time according to #6470

(output from `/api/v1/allmetrics?format=prometheus_all_hosts&variables=yes`)
variable:
```
netdata_ceph_storage_osd_usage_size_osd_2_kb{instance="server1"} 3906994176.0000000 1587569329000
```
vs line:
```
netdata_ceph_osd_usage_KiB_average{chart="ceph_storage.osd_usage",family="osd",dimension="osd.2",instance="server1"} 2614347000.0000000 1587570190000
```

So I would rather go with the size chart as is in my current PR.
@ilyam8 what do you think?
Thanks,

**Comment by ilyam8** [comment]
> But they seem unusable from prometheus :

Yes, you are right.

**Comment by ilyam8** [comment]
> So I would rather go with the size chart as is in my current PR.

👍

**Comment by elelayan** [comment]
Cool, thanks :-)

**Comment by ilyam8** [comment]
@elelayan we are about to release new version, this PR will be merged after it

**Comment by elelayan** [comment]
Thanks!

**Pull request merged**
