### PR TITLE
Store alert log entries even if alert it is repeating.

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This PR allows repeating alerts to be stored in health log (both in memory and in sqlite). It merely removes code that checked that if the alert is repeating, it should not store it in health log.

If the global option `default repeat warning` or `default repeat critical` is used, then no entries for any alert will be recorded in the health log.

The health code creates a new alarm log entry for every instance of a repeating alert. What this PR changes, is that the first instance of the alert will be stored and recorded in the health log, along with it's initial and removed states when the agent starts and shuts down. 

The entries for the next repeats will not, but will continue to be created and produce a notification.

However, since all it does is remove code that was there to protect from that, I would like some feedback if that has intentional and I'm missing something.

##### Test Plan

Enable the e.g. `default repeat warning` on master. Start the agent and observe that nothing is recorded in the health log (/api/v1/alarm_log).
With this PR, repeat the above. It should now store the entries. Raise an alert (e.g. ram_available) and notice that the first instance of the alert is recorded, but not the repeating ones.

### CODE REVIEW

**Comment by stelfrag** [comment]
> However, since all it does is remove code that was there to protect from that, I would like some feedback if that has intentional and I'm missing something.

I think that not writing the repeated alerts in the health log was intentional. The repeat option was affecting the notification part only. 

@ktsaou do you remember ?

**Comment by thiagoftsm** [comment]
@stelfrag I do not remember the exact motive, but we need to remember that `repeat` can be repeat in a high rate depending of configuration.

@MrZammler I suggest we store only the first time that is raised, and also to add an additional information that this is a repeated alarm.

**Comment by MrZammler** [comment]
> @stelfrag I do not remember the exact motive, but we need to remember that `repeat` can be repeat in a high rate depending of configuration.
> 
> @MrZammler I suggest we store only the first time that is raised, and also to add an additional information that this is a repeated alarm.

Hi @thiagoftsm, yes, this PR does that. Stores the first instance in the log.

**Comment by ktsaou** [comment]
I think it is ok to store it.

**Comment by thiagoftsm** [comment]
Hello @MrZammler ,

I tested your PR now and I got these [alarms.txt](https://github.com/netdata/netdata/files/8145562/alarms.txt), as you can see your PR is working, and we are storing now the `repeat` inside `alarms_log`, but as you can also see I had repeated alarms stored:

```
bash-5.1$ grep alarms.txt  | sort | uniq -c
      3                 "name": "my_example_random0",
      2                 "name": "my_example_random1",
      4                 "name": "my_example_random2",
      2                 "name": "my_example_random3",
```

When I said on unique time, I was saying for we store the first, and insert a field that would store the number of times the alarm was raised.

I am OK to merge this PR with your changes, and we can work in the future to give a summary for repeated alarms, or we can change this PR to already give samples like I said in previous paragraph. What do you prefer?

**Comment by MrZammler** [comment]
> and insert a field that would store the number of times the alarm was raised.

Hmm, hi Thiago!

I don't know if the health log is ok to store the number of times the alarm has repeated, it might complicate things, and not sure of the value.

We could perhaps store it in the RRDCALC structure. We already keep the `last_updated` timestamp there, it should be ok to also add a counter there for each time the specific alert is repeated. Is that what you had in mind?

**Comment by ktsaou** [comment]
Guys, you have to make sure, duplicate transitions are not sent to the cloud. It is going to be a mess if you send all the repeats.

**Comment by MrZammler** [comment]
> Guys, you have to make sure, duplicate transitions are not sent to the cloud. It is going to be a mess if you send all the repeats.

Indeed, yes, this is what it does. Only the first alarm entry for each transition is stored (and queued to the cloud). Repeated instances of that transition do create alarm entries but they are not linked to health log, nor are stored in the db. We will make sure during testing. 

@thiagoftsm I've been thinking about the counter... since we don't have anything to consume this information at this point, it seems like a bit of dead weight (ram) right now... Should we leave it out now, and concentrate on making this PR behave correctly for what we need?

**Comment by thiagoftsm** [comment]
> @thiagoftsm I've been thinking about the counter... since we don't have anything to consume this information at this point, it seems like a bit of dead weight (ram) right now... Should we leave it out now, and concentrate on making this PR behave correctly for what we need?

This is an interesting question. I agree we do not have no any consumer, but we did not have this feature. This could be the first step to create a more detailed report. 

We also need to think that due the fact this was not stored before, nobody had condition to take a look in the logs. Now that we will have this log inside our database, we can give details about it. For other alarms this was not necessary, because they do not have this feature.

I still think we need to store this information.

**Comment by MrZammler** [comment]
> > @thiagoftsm I've been thinking about the counter... since we don't have anything to consume this information at this point, it seems like a bit of dead weight (ram) right now... Should we leave it out now, and concentrate on making this PR behave correctly for what we need?
> 
> This is an interesting question. I agree we do not have no any consumer, but we did not have this feature. This could be the first step to create a more detailed report.
> 
> We also need to think that due the fact this was not stored before, nobody had condition to take a look in the logs. Now that we will have this log inside our database, we can give details about it. For other alarms this was not necessary, because they do not have this feature.
> 
> I still think we need to store this information.

Hi @thiagoftsm ! Ok, it will be stored now, and can be seen on the `/api/v1/alarms` endpoint for each alert.

**Comment by MrZammler** [comment]
Also tested the cloud behavior, and since we only store the first iteration of the status change (i.e. the first alarm entry), only that one is pushed to the cloud.

**Comment by MrZammler** [comment]
Hi guys!

@thiagoftsm had raised some concerns with test alerts and sending them to the cloud. I could not reproduce the issue unfortunately. Thiago, if it is possible, please update the ticket with the case to try and see it again. Thanks!

**Review by vkalintiris — APPROVED** [review]
LGTM.

**Comment by thiagoftsm** [comment]
> @thiagoftsm had raised some concerns with test alerts and sending them to the cloud. I could not reproduce the issue unfortunately. Thiago, if it is possible, please update the ticket with the case to try and see it again. Thanks!

Hello  @MrZammler ,

I think your PR reached the main goal, now about my concerns, let me try to explain it better. When we use some alert like this:

```sh
bash-5.1$ cat system_cpu.conf
 alarm: dev_dim_template
    on: system.cpu
    os: linux
lookup: sum -3s at 0 every 3 percentage foreach *
 units: %
 every: 10s
repeat: critical 1m
  warn: $this > 1
  crit: $this > 4
````

that is not a normal alert, but it is an alert that raises a lot of times. Using it, I receive a lot of messages in my channels, but I do not see them on cloud:

Screenshot_20220419_164316

I am going to approve your PR. because the goal was achieved, but  probably there is a bug that needs more attention.

**Review by thiagoftsm — APPROVED** [review]
I am approving this PR with concerns explained [here](https://github.com/netdata/netdata/pull/12226#issuecomment-1102879581).

**Comment by MrZammler** [comment]
Ok Thiago, thanks a lot. I will add this alert configurion and do some tests, and will let you know. Thank you!

**Comment by MrZammler** [comment]
Hi Thiago. Did a quick check with this config, and under this PR (of course, without this PR they won't appear in the cloud since they are repeating), and I get the alerts on the cloud:

image

I can also see at some points them going from warning to critical, etc almost in par with what I have in the agent.

It's a good test case though, since they frequently change statuses and I will keep it for future tests.. 

It is weird though that you don't get them in the cloud at all... They only sure way to check if they are transmitted to the cloud, is to check the sqlite database. If they are stored in your `health_log_XXXXX_XXXXX` table, they should also appear in the table `aclk_alert_XXXXX_XXXX` one (based on `unique_id` from health_log and `alert_unique_id` field in aclk_alert).

**Comment by MrZammler** [comment]
(Closing and reopen to force checks)

**Comment by MrZammler** [comment]
Thanks all!

**Comment by thiagoftsm** [comment]
> It is weird though that you don't get them in the cloud at all... Th

Yes, I will ping cloud team to verify what is happening on my environment. Thanks to test!

**Pull request merged**
