### PR TITLE
Add option to skip re-initialization of cluster centers.

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

Add an option to skip initializing the cluster centers every time we are training a dimension. 

##### Test Plan

- CI jobs
- testing on staging by @andrewm4894 

##### Additional Information
https://github.com/netdata/netdata/discussions/12308

### CODE REVIEW

**Comment by underhood** [comment]
Codewise this is pretty simple. Did you do any comparisons as you suggested @ https://github.com/netdata/netdata/discussions/12308 ?

**Comment by andrewm4894** [comment]
I'm going to run two nodes in staging one with it on and one with it off. I'm also going to compare the anomaly bits from both to a python based reference implementation. So between all those comparisons we should get a clearer idea of impact on performance and behavior of the scores themselves.

**Comment by andrewm4894** [comment]
Creating these 3 vm's for initial testing. Will share results in here.

`devml` = netdata/netdata:master
`devml1` = vkalintiris/netdata:clusters with default ml config
`devml2` = vkalintiris/netdata:clusters with default ml config and `reuse cluster centers = yes`

**Review by stelfrag — APPROVED** [review]
LGTM

**Review by underhood — APPROVED** [review]
codewise this is ok as per comment above

**Comment by andrewm4894** [comment]
Looking at ram it seems like `devml2` saves some:

**Comment by andrewm4894** [comment]
devml1 = with no reuse cluster centers
devml2 = with reuse cluster centers

Looks like devml2 uses a small bit less ram (but unsure how reliable it is given n=1)
image

In terms of CPU its less clear: 
image

devml1 much clearer in peaks and troughs:
image

devml2 does seem to spread it out better and but shifted maybe a little lower overall:
image

**Review by andrewm4894 — APPROVED** [review]
I think it makes sense to merge this as-is for now as an optional optimization. once its been used in the wild a bit more then we can decide if we want to enable it by default or not. for now I think makes sense to merge as is in the aim of keeping the ml algo as simple as possible for now. 

But i think this will end up being a useful optimization to be able to apply via config.

**Comment by andrewm4894** [comment]
Once merged I will make a small PR to update the docs to add then new param.

**Comment by vkalintiris** [comment]
@andrewm4894 can you double check that the instances are configured properly? ie. the "reuse cluster centers = false" in devml1 & "reuse cluster centers = true" in devml2 under the ml section.

**Comment by vkalintiris** [comment]
> @andrewm4894 can you double check that the instances are configured properly? ie. the "reuse cluster centers = false" in devml1 & "reuse cluster centers = true" in devml2 under the ml section.

Never mind, I double checked myself and the configuration of the nodes LGTM. The results contradict the intuition I had about the resource requirements of the clusters initialization step. I'll profile this piece of code locally to see how much we really gain.

**Comment by vkalintiris** [comment]
@andrewm4894 I don't think we should merge this because we didn't notice any significant CPU improvements. It's better to simply go with https://github.com/netdata/netdata/pull/12494.

**Comment by andrewm4894** [comment]
> @andrewm4894 I don't think we should merge this because we didn't notice any significant CPU improvements. It's better to simply go with #12494.

agree - but may try investigate it again at a later date as really felt like a no brainer to me.

**Comment by vkalintiris** [comment]
> agree - but may try investigate it again at a later date as really felt like a no brainer to me.

Sounds good, I'll close this PR and revisit it later on.

**Pull request closed without merging**
