### PR TITLE
Add git-chglog configuration

### LINKED ISSUE #8117: Automatic changelog generation doesn't work well
##### Bug report summary

CHANGELOG.md was missing tens of PRs this time.  The [log generator we use](https://github.com/github-changelog-generator/github-changelog-generator) is buggy, extremely slow & inefficient and finally proven to be unreliable. 

##### Expected behavior
Let's check to see if we can find a much better changelog generator. If we can't, we'll need to write something ourselves. 

The info we need can be produced by something as simple as the following, as long as can feed it with a list of PRs after the last tag. 

```bash
while read a; do
curl -H "Authorization: token 91303b0a90f2d170da4dfa683f8cb2c912ac666f" -s https://api.github.com/repos/netdata/netdata/pulls/$a |
jq '. | "- \(.title) [#\(.number)](https://github.com/netdata/netdata/pull/\(.number)) ([\(.user.login)](https://github.com/\(.user.login)))"' |
tr -d '"'
done < prlist
```

Of course we would ideally get the PRs organized in categories such as bug fixes, collector improvements etc, but that's a secondary concern. The primary one is having the correct list of PRs after every nightly build.

### LINKED ISSUE #8575: Auto generate the ChangeLog
##### Feature idea summary

The existing tools we use to generate the [ChangeLog](/CHANGELOG.md) are
a bit buggy and unreliable. We need a way to auto-generate this
changelog per release cycle without too much human effort.

##### Requirements

- [ ] Preserve the existing format
- [ ] Skip merge commits, nightlies, package builds, etc.
- [ ] Skip commits whoose PRs were marked `no changelog`.
- [ ] Not suck :)

##### Expected behavior

We have a tool that can automatically update the [ChangeLog](/CHANGELOG.md)
which we will eventually incorporate into the new automated release
workflows.

cc @cakrit

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

Improves our Git ChangeLog generation by using the tool
[git-chglog](https://github.com/git-chglog/git-chglog) which is highly
configurable and generates nice ChagneLog output like you can see here:

https://gist.github.com/prologic/531536e4d861169a1c2daacbc9e22b40

- Fixes #8575
- Fixes #8117
- See #5648

##### Component Name

- area/ci

> Becuase this should be part of the general CI automation and automated release process.

##### Test Plan

- [ ] Run `git-chglo` and verify the output => https://gist.github.com/prologic/531536e4d861169a1c2daacbc9e22b40

##### Additional Information

### CODE REVIEW

**Comment by amoss** [comment]
Great. Love it. Let do it like this:
* We use the tool fully from now on.
* The "misc didn't match section" should be called something like "Wall Of Shame - I Will Fix This Myself Before The Release Deadline And Learn How To Use The Tool" 
* Everybody is responsible for going into the marketing repo and fixing / moving PRs that got flagged.

We will use the release next week as a dry run and then just make it mandatory.

**Comment by prologic** [comment]
@amoss (cc @cakrit) Sorry I've tried and spend far too much time on this. I've tried to hack [this tool](https://github.com/git-chglog/git-chglog) to meet our needs which are mostly there bar two things:

- Author names linked to their Github profiles.
- Uncategorised Commits (_that don't follow our PR Title guidelines_).
- `no changelog" label. -- Although I _think_ we should change how we do this.

I _might_ circle back on this if a have a brilliant 💡moment; but so far I've failed to understand this guy's code and what he was thinking :/

**Comment by amoss** [comment]
So where does this leave us with the release notes for 1.23 - are they complete or missing all of the categorized PRs?

**Comment by prologic** [comment]
We still have a [ChangeLog](https://github.com/netdata/netdata/blob/master/CHANGELOG.md#changelog)

**Comment by amoss** [comment]
But that is completely uncategorized and cannot go in the release notes. How up to date is the copy in the root of the marketing repo?

**Comment by prologic** [comment]
@joelhans Can you answer this? ☝️

**Comment by prologic** [comment]
@amoss @joelhans The other option is we just go with [this](https://gist.github.com/prologic/35ef04cc384d517f8dd5cba570e7e999) -- But it is missing the things I talked about above.

**Comment by prologic** [comment]
I _think_ I can get [this working](https://gist.github.com/prologic/f8a93624dc2c6e8e9524fe55afc6ff49)

It's based off of Kubernetes own Release Notes generator / internal tool and I've been hacking at it to do what we want. Its close, I've solved half the problems I stated above now. Now I just need to lookup each PR's Issue to grok the labels of the Issue(e) the PR Closes/Fixes since that's how we commit our work. I'll keep working on this tomorrow now that I've made progress.

**Comment by prologic** [comment]
This approach has been abandoned using git-chglog. The code is too complicated even though the tool outputs nicely formatted change log; it doesn't suit our needs complete.y

**Pull request closed without merging**
