### PR TITLE
Fix #9089: Prometheus HELP lines incorrectly formatted (when enabled via query parm)

### LINKED ISSUE #9089: Prometheus HELP lines incorrectly formatted (when enabled via query parm)
#### Bug report summary
Related to #9085 but does not break the parser I'm using the way that one does, so less critical from my perspective. Also related to #9088 but this one seems easier to fix.

When the Prometheus backend's optional HELP lines are enabled (by adding `help=yes` to the query parameters), the resulting lines incorrectly start with `# COMMENT` instead of `# HELP` as specified in the [Prometheus project's specification](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#comments-help-text-and-type-information) for the textual exposition format, which states, in part (*emphasis mine*):

> Lines with a `#` as the first non-whitespace character are comments. They are ignored unless the first token after `#` is either `HELP` or `TYPE`. Those lines are treated as follows: *If the token is `HELP`, at least one more token is expected*, which is the metric name. All remaining tokens are *considered the docstring for that metric name*.

The Prometheus docs do not mention a role for the sequence `# COMMENT` so I surmise this is a case of crossed wires during late-night hacking ;)

##### OS / Environment
CentOS 7 in VM (no container in the mix):
```
/etc/centos-release:CentOS Linux release 7.6.1810 (Core) 
/etc/os-release:NAME="CentOS Linux"
/etc/os-release:VERSION="7 (Core)"
/etc/os-release:ID="centos"
/etc/os-release:ID_LIKE="rhel fedora"
/etc/os-release:VERSION_ID="7"
/etc/os-release:PRETTY_NAME="CentOS Linux 7 (Core)"
/etc/os-release:ANSI_COLOR="0;31"
/etc/os-release:CPE_NAME="cpe:/o:centos:centos:7"
/etc/os-release:HOME_URL="https://www.centos.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.centos.org/"
/etc/os-release:
/etc/os-release:CENTOS_MANTISBT_PROJECT="CentOS-7"
/etc/os-release:CENTOS_MANTISBT_PROJECT_VERSION="7"
/etc/os-release:REDHAT_SUPPORT_PRODUCT="centos"
/etc/os-release:REDHAT_SUPPORT_PRODUCT_VERSION="7"
/etc/os-release:
/etc/redhat-release:CentOS Linux release 7.6.1810 (Core) 
/etc/system-release:CentOS Linux release 7.6.1810 (Core) 
```

##### Netdata version
`netdata v1.22.1-55-g140734a`

##### Component Name
`backends/prometheus`

##### Steps To Reproduce
1. Build and install Netdata from master / `e99692f145f710930723081d2e5bbf8868be2080`
2. Start Netdata service
3. Fetch `http://127.0.0.1:19999/api/v1/allmetrics?format=prometheus&help=yes`

##### Expected behavior
Output includes embedded lines of the form:

```
# HELP netdata_disk_avgsz_KiB_operation_average: dimension "writes", value is KiB/operation, gauge, dt 1589833074 to 1589833083 inclusive
```

##### Actual behavior
Output includes embedded lines of the form:

```
# COMMENT netdata_disk_avgsz_KiB_operation_average: dimension "writes", value is KiB/operation, gauge, dt 1589833074 to 1589833083 inclusive
```

### PR DESCRIPTION
**Pull request by jeffgdotorg**
##### Summary
Fixes #9089
Also related to #9085 (which has a separate PR)

Changed HELP lines' second token from `COMMENT` to `HELP`

##### Component Name
`backends/prometheus`

##### Test Plan
See #9089 # steps to reproduce

##### Additional Information
Should be self-explanatory, especially when taken together with #9085. Please mention me if clarification is needed.

### CODE REVIEW

**Comment by vlvkobal** [comment]
I think the change is valid. Please also fix `exporting\prometheus`. The backends subsystem will be deprecated soon and the code from `exporting\prometheus\prometheus.c` will be used instead.

**Comment by ilyam8** [comment]
@vlvkobal could you just push the changes to this PR and we merge it? It looks pretty simple and wont take a lot of time

**Comment by jeffgdotorg** [comment]
Apologies for going quiet on this conversation.
I believe the required changes to `exporting/prometheus/prometheus.c` were already merged with PR netdata#9086. If further changes are needed, I'm happy to make and push them, or for @vlvkobal to do it if that's easier.

**Comment by ilyam8** [comment]
#9086 is `COMMENT TYPE` => `TYPE`

This PR supposed to fix HELP strings: `COMMENT => HELP`

---

Correct format is

```cmd
# HELP metric_name Description of the metric
# TYPE metric_name type
```

---

`/api/v1/allmetrics?format=prometheus&types=yes&help=yes` returns

```
# COMMENT homogeneous chart "services.throttle_io_ops_write", context "services.throttle_io_ops_write", family "disk", units "operations/s"
# COMMENT netdata_services_throttle_io_ops_write_operations_persec_average: dimension "haveged", value is operations/s, gauge, dt 1596812184 to 1596812197 inclusive
# TYPE netdata_services_throttle_io_ops_write_operations_persec_average gauge
netdata_services_throttle_io_ops_write_operations_persec_average{chart="services.throttle_io_ops_write",family="disk",dimension="haveged"} 0.0000000 1596812197000
...
```

`TYPE` format is ok. There are 2 comments, none of them is `HELP` really 🤷‍♂️ 

- 1st comment doesnt follow `HELP metric_name Description of the metric` - no metric name
- 2nd comment kind of follows `HELP metric_name Description of the metric` format but there is no `Description of the metric` in fact. And there is `:` in the end of metric_name.

---

It looks like we dont have `HELP` at all. @jeffgdotorg What do you think?

**Comment by vlvkobal** [comment]
> I believe the required changes to exporting/prometheus/prometheus.c were already merged with PR #9086.

As @ilyam8 already wrote, only `TYPE` has been changed in #9086. Changes for `HELP` still have to be implemented. So, please finish the PR.

**Comment by ilyam8** [comment]
@vlvkobal take a look https://github.com/netdata/netdata/pull/9090#issuecomment-670564652

**Comment by vlvkobal** [comment]
I had a discussion with @ilyam8. We don't follow the format of HELP strings, so we can't simply change COMMENT -> HELP. We can
- Leave everything as it is

(or)
- Remove COMMENTs

(and/or)
- Add HELP strings

The question @ilyam8 asked is still valid
> @jeffgdotorg What do you think?

**Comment by vlvkobal** [comment]
I'm closing this because of https://github.com/netdata/netdata/issues/9089#issuecomment-674889387.

**Pull request closed without merging**
