### PR TITLE
in source Judy

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Integrates Judy into our build

LGTM would have to be silenced on Judy files as they are not our sources.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by Ferroin — DISMISSED** [review]
Approving the `.gitignore` and packaging related changes.

**Comment by MrZammler** [comment]
Hi! Should we remove then the requirement for judy for various distributions? I.e.:

https://github.com/netdata/netdata/blob/fccfc02d2c1966b814b6babcd8dddb0c6e822d45/packaging/installer/install-required-packages.sh#L1115-L1124

**Comment by Ferroin** [comment]
@MrZammler I intentionally am planning on handling that in a separate PR as a followup to this one, as there need to be a handful of changes coordinated across multiple repos for it.

**Comment by underhood** [comment]
@Ferroin my naive attempt here https://github.com/netdata/netdata/pull/13362/commits/612597ae71de9b815b2eff1e6d1a2002114572d8

should I revert this one commit and let you handle it as you mention above?

**Comment by Ferroin** [comment]
@underhood Actually, that appears to cover everything that should be needed here, so it should be fine as-is.

**Review by Ferroin — DISMISSED** [review]
Approving packaging related changes.

**Comment by thiagoftsm** [comment]
@underhood when I compiled your PR, I received this warning:

```sh
libnetdata/libjudy/src/JudyL/JudyLTablesGen.c:263:28: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'long unsigned int' [-Wformat=]
  263 |     fprintf(fd," Leaf1 = %ld\";\n\n", (Word_t)cJL_LEAF1_MAXPOP1);
      |                          ~~^
      |                            |
      |                            long int
      |                          %ld
 OK  ''
```

**Review by thiagoftsm — APPROVED** [review]
I tested and everything is running fine. I am approving considering that `yml` warning is minor, @Ferroin , can you confirm this?

**Comment by underhood** [comment]
@thiagoftsm i had to do some changes to silence that warning... not beautiful but only way to override user CFLAGS provided by CI which enforced that warning (as user CFLAGS are normally added last -> with highest priority)

**Comment by Ferroin** [comment]
@thiagoftsm Indeed, the yamllint warning can be ignored here.

**Review by Ferroin — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
I retest and everything is working as expected, LGTM!

**Pull request merged**
