### PR TITLE
Auto Assign PRs to their Authors

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

Fixes a minor annoyance with the ZenHub UI and Github PRs where by default the Assignee of the PR is "unassigned". IHMO its better that this is the Author of the PR so its more clearly visible in "card form" :)

##### Component Name

area/ci

### CODE REVIEW

**Comment by prologic** [comment]
> Skips the process to add reviewers/assignees since PR type is draft

So I'll have to publish this PR to actually test it :)

**Comment by thiagoftsm** [comment]
Hi @prologic ,

I remember that we had agreed months ago that the PR is not assigned for the author, because he is not the reviewer of it, but I can be wrong, so my suggestion is we assign the product team as reviewer for they give their opinion about this.

**Comment by prologic** [comment]
> I remember that we had agreed months ago that the PR is not assigned for the author, because he is not the reviewer of it, but I can be wrong, so my suggestion is we assign the product team as reviewer for they give their opinion about this.

The reviewers is untouched; it's just the "Assignee" which shows in in ZenHub as I found out :)

Happy to drop this PR though if that's not what we want.

**Comment by prologic** [comment]
For example (_see attached_)

Screen Shot 2020-01-24 at 07 45 15

**Comment by ncmans** [comment]
This is one of the first things I've done every where I've worked. Never quite figured why there is an assignee for a PR to begin with (my only suspect is that PR derives from Issue and hence carries with it all its attributes).

**Comment by thiagoftsm** [comment]
I understood what you are doing here, but I assigned to them the PR for they measure this, because it has an important impact in their work! ;)

**Comment by prologic** [comment]
> I understood what you are doing here, but I assigned to them the PR for they measure this, because it has an important impact in their work! ;)

In order not to break your workflow; this action would have to leave a PR you've already assigned alone right? If 'unassigned" you would be okay with it being set to the PR author?

**Comment by ilyam8** [comment]
> Never quite figured why there is an assignee for a PR to begin with

I think there is no strict definition who is assignee so it is up to the team project to decide who is assignee - pr opener or a person responsible for the specific area (who will merge/close the pr - this more when it is the PR from a contributor).

**Comment by ilyam8** [comment]
So we need to define how we use the assignee field and use it this way. Lack of icon on zenhub sounds like not enough strong point for me but i am personally not against.

**Comment by prologic** [comment]
> So we need to define how we use the assignee field and use it this way. Lack of icon on zenhub sounds like not enough strong point for me but i am personally not against.

I agree completely. And I won't want to sound petty here; but PR(s) I see in "Review/QA" column without a gravatar I recognise visually tend to want to make me go check if its a PR by a Contributor that we've over looked. -- That alone was the premise for exploring this in the first place and hence this PR -- I feel strongly about being responsive to both our users and contributors alike :)

**Comment by prologic** [comment]
As per discussion with @cakrit I'll bring this up in our next retro.

**Pull request closed without merging**
