### PR TITLE
contrib Prometheus alert rules for NetData

### PR DESCRIPTION
**Pull request by mh720**
Contributing some working Prometheus TSDB alert rules when using NetData scrape sources.

### CODE REVIEW

**Comment by paulfantom** [comment]
Wouldn't it be better to include it in docs and not in code?

@ktsaou @cakrit WDYT?

**Comment by ktsaou** [comment]
> Wouldn't it be better to include it in docs and not in code?

I think it is ok to track them through git and reference them from the docs.

Generally, we will eventually need a lot of such things. Even grafana dashboard templates may be contributed. So, I think it it is better to keep them all together somewhere in the repo. The `contrib` directory seems quite fit for such files.

Keep in mind this may have to be added to a makefile for the packaging to pick it - but I don't know for sure - you probably know better.

**Comment by paulfantom** [comment]
> I think it is ok to track them through git

Our docs is git

> Keep in mind this may have to be added to a makefile for the packaging to pick it

That's one of the reasons against putting it into code.

**Comment by ktsaou** [comment]
ok, your call. I just don't find it practical to be scattered all over the place. So, your call. Make room for them somewhere, to have them well organized, and everything will be ok.

**Comment by paulfantom** [comment]
@mh720 could you put it into our wiki as an example? I think it would fit nicely on this page: https://github.com/netdata/netdata/wiki/Using-Netdata-with-Prometheus

**Pull request closed without merging**
