### PR TITLE
Replace references to Google Analytics with Posthog where relevant

### PR DESCRIPTION
**Pull request by andrewm4894**
##### Summary

Swapping out sentence about Google Analytics with a PostHog version of same

##### Component Name

docs/agent/packaging/installer
docs

### CODE REVIEW

**Comment by joelhans** [comment]
Hey @andrewm4894, this change got me wondering if there's other mentions of Google Analytics/GA throughout the repo.

I don't add this to ask you to fix them yourself—I can help with that—but more to ask if you think changing all these references make sense at this point. We probably can't touch the privacy policy without input from @cakrit, but the others shouldn't be difficult.

Here's what I found:

```
18 results - 11 files

agent • netdata-installer.sh:
  421    ${TPUT_YELLOW}${TPUT_BOLD}NOTE${TPUT_RESET}:
  422:   Anonymous usage stats will be collected and sent to Google Analytics.
  423    To opt-out, pass --disable-telemetry option to the installer or export

agent • collectors/python.d.plugin/web_log/README.md:
  14  
  15: Yet, after the appearance of google analytics and similar services, and the recent rise of APM (Application Performance Monitoring) with sophisticated time-series databases that collect and analyze metrics at the application level, all these web server log files are mostly just filling our disks, rotated every night without any use whatsoever.
  16  

agent • docs/anonymous-statistics.md:
   96  
   97: ## Migration from Google Analytics and Google Tag Manager.
   98  
   99: Prior to v1.29.4 we used Google Analytics to capture this information. This led to discomfort with some of our users in sending any product usage data to a third party like Google. It was also not even that useful in terms of generating the insights we needed to help catch bugs early and find opportunities for product improvement as Google Analytics does not allow its users access to the raw underlying data without paying a significant amount of money which would be infeasible for a project like Netdata.
  100  
  101: While we migrate fully away from Google Analytics to PostHog there maybe be a small period of time where we run both in parallel before we remove all Google Analytics related code. This is to ensure we can fully test and validate the Netdata PostHog implementation before fully defaulting to it.
  102  

agent • docs/netdata-security.md:
  211  
  212: Starting with v1.12, Netdata collects anonymous usage information by default and sends it to Google Analytics. Read
  213  about the information collected, and learn how to-opt, on our [anonymous statistics](anonymous-statistics.md) page.

agent • docs/privacy-policy.md:
  33  
  34: Website and Analytics: When you visit our Websites and use our Services, ND collects some information about your activities through tools such as Google Analytics. The type of information that we collect focuses on general information such as country or city where you are located, pages visited, time spent on pages, heat-map of visitors’ activity on the site, information about the browser you are using, etc. ND collects and uses this information pursuant to our legitimate interest in enhancing the security and utility of our Services. The information we gather and process is used in the aggregate to spot trends without deliberately identifying individuals.
  35  
  36: Note that you can learn about Google’s practices in connection with its analytics services and how to opt out of it by downloading the Google Analytics opt-out browser add-on, available at <https://tools.google.com/dlpage/gaoptout>. 
  37  
  38: Information from Cookies: We and our service providers (for example, Google Analytics as described above) may collect information using cookies or similar technologies for the purposes described above and below. Cookies are pieces of information that are stored by your browser on the hard drive or memory of your computer or other Internet access device.  Cookies may enable us to personalize your experience on the Services, maintain a persistent session, passively collect demographic information about your computer, and monitor advertisements and other activities. The Websites may use different kinds of cookies and other types of local storage (such as browser-based or plugin-based local storage).
  39  

  66  
  67: Anonymous Usage Statistics: From Netdata v1.12 and above, anonymous usage information is collected by default on certain events of the ND daemon and send to Google Analytics. Every time the daemon is started or stopped and every time a fatal condition is encountered, Netdata collects system information and sends it to GA via an http call. The information collected for all events is:
  68  

agent • packaging/docker/README.md:
  13  
  14: Starting with v1.12, Netdata collects anonymous usage information by default and sends it to Google Analytics. Read
  15  about the information collected, and learn how to-opt, on our [anonymous statistics](/docs/anonymous-statistics.md)

agent • packaging/installer/README.md:
  23  
  24: Starting with v1.12, Netdata collects anonymous usage information by default and sends it to Google Analytics. Read
  25  about the information collected, and learn how to-opt, on our [anonymous statistics](/docs/anonymous-statistics.md)

agent • packaging/installer/methods/freebsd.md:
  66  
  67: From Netdata v1.12 and above, anonymous usage information is collected by default and sent to Google Analytics. To read
  68  more about the information collected and how to opt-out, check the [anonymous statistics

agent • packaging/makeself/makeself-help-header.txt:
  45  
  46:   Anonymous stat collection and reporting to Google Analytics is enabled
  47    by default. To disable, pass --disable-telemetry option to the installer

agent • web/gui/demosites2.html:
  1099  <script>
  1100:     // google analytics when this is used for the home page of the demo sites
  1101      // you don't need this if you customize this dashboard for your needs

agent • web/gui/main.js:
  4463  
  4464:         // google analytics when this is used for the home page of the demo sites
  4465          // this does not run on user's installations
```

**Comment by andrewm4894** [comment]
Good idea, I'll look at these one by one and try change any of the easier ones and escalate any others.

**Comment by andrewm4894** [comment]
I've renamed this PR and we can try do them all in here.

**Comment by andrewm4894** [comment]
@joelhans @cakrit @Ferroin (as impacts a few places in packaging and installation). 

I have made some changes in this PR to update various places where we mention using Google Analytics to reflect the fact that we will now be using our self hosted PostHog instead. 

Anyone else i have missed that we need to help review here? 

e.g. assuming we will need to run any changes to privacy policy through legal first.

**Comment by vkalintiris** [comment]
What's the status of this? The changes LGTM.

**Review by joelhans — APPROVED** [review]

**Comment by joelhans** [comment]
I got word from @cakrit that the `privacy-policy.md` file here is outdated (the real one is [here](https://www.netdata.cloud/privacy/), so let's not worry about it for this PR. We should be good to go.

I'll create a separate PR in a few hours to remove the `privacy-policy.md` file entirely so there's no more confusion about the source of truth.

**Review by vkalintiris — APPROVED** [review]

**Pull request merged**
