### PR TITLE
Update plugin_nfacct.c

### PR DESCRIPTION
**Pull request by fun04wr0ng**
Fixes: #6099

fix CHART [netfilter.nfacct_bytes/nfacct_packets]: it just show 1 DIMENSION!!!

BEFORE:
```
CHART netfilter.nfacct_packets '' 'Netfilter Accounting Packets' 'packets/s' 'nfacct' '' stacked 8906 1 nfacct.plugin
CHART netfilter.nfacct_packets '' 'Netfilter Accounting Packets' 'packets/s'
DIMENSION pproxy_in '' incremental 1 1
BEGIN netfilter.nfacct_packets
SET pproxy_in = 0
END
CHART netfilter.nfacct_packets '' 'Netfilter Accounting Packets' 'packets/s'
DIMENSION pproxy_out '' incremental 1 1
BEGIN netfilter.nfacct_packets
SET pproxy_out = 2164
END
BEGIN netfilter.nfacct_packets
SET pproxy_in = 0
END
BEGIN netfilter.nfacct_packets
SET pproxy_out = 2164
END
````

NOW:
```
CHART netfilter.nfacct_packets '' 'Netfilter Accounting Packets' 'packets/s' 'nfacct' '' stacked 8906 1 nfacct.plugin
CHART netfilter.nfacct_packets '' 'Netfilter Accounting Packets' 'packets/s'
DIMENSION pproxy_in '' incremental 1 1
DIMENSION pproxy_out '' incremental 1 1
BEGIN netfilter.nfacct_packets
SET pproxy_in = 0
SET pproxy_out = 2164
END
BEGIN netfilter.nfacct_packets
SET pproxy_in = 0
SET pproxy_out = 2164
END
```

### CODE REVIEW

**Comment by fun04wr0ng** [comment]
it seems that all DIMENSIONs must be printed in one ``BEGIN ... END`` section,  there is API result before:
```json
{
   "api": 1,
   "id": "netfilter.nfacct_packets",
   "name": "netfilter.nfacct_packets",
   "view_update_every": 2,
   "update_every": 1,
   "first_entry": 1558604793,
   "last_entry": 1558605985,
   "before": 1558605984,
   "after": 1558605505,
   "dimension_names": ["pproxy_in", "pproxy_out"],
   "dimension_ids": ["pproxy_in", "pproxy_out"],
   "latest_values": [0, null],
   "view_latest_values": [0, null],
   "dimensions": 2,
   "points": 240,
   "format": "json",
   "result": {
 "labels": ["time", "pproxy_in", "pproxy_out"],
    "data":
 [
      [ 1558605506000, 0, null],
      [ 1558605508000, 0, null],
      [ 1558605510000, 0, null],
      [ 1558605512000, 0, null],
      [ 1558605514000, 0, null],
      [ 1558605516000, 0, null],
      [ 1558605518000, 0, null],
      [ 1558605520000, 0, null],
      [ 1558605522000, 0, null]
  ]
},
 "min": 0,
 "max": 0
}
```

**Comment by vlvkobal** [comment]
@fun04wr0ng Please sign the CLA.

**Comment by fun04wr0ng** [comment]
@vlvkobal signed already.  -_-

**Comment by vlvkobal** [comment]
Thanks! I'm waiting for the 1.6.1 have been released and then I'll merge the PR.

**Pull request merged**
