### PR TITLE
Correctly track last num vcpus in xenstat_plugin

### LINKED ISSUE #8019: xenstat plugin flooding error logs
##### Bug report summary
On [XCP-ng](https://xcp-ng.org/), netdata installed from my own packaging (based on your spec file) is flooding the error log.

Extract:
```
2020-02-10 06:42:42: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:42: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:43: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:43: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:43: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:43: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:44: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:44: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:44: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:44: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:45: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:45: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:45: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:45: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:46: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:46: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:46: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:46: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:47: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:47: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:47: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:47: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:48: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:48: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:48: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:48: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:49: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:49: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:49: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:49: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:50: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:50: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:50: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:50: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:51: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:51: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:51: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:51: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:52: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:52: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:52: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:52: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:53: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:53: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:53: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:53: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:54: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:54: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:54: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:54: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:55: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:55: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:55: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:55: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:56: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:56: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:56: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:56: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:57: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:57: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:57: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:57: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 06:42:58: netdata LOG FLOOD PROTECTION too many logs (201 logs in 50 seconds, threshold is set to 200 logs in 1200 seconds). Preventing more logs from process 'netdata' for 1150 seconds.
2020-02-10 07:02:09: netdata LOG FLOOD PROTECTION resuming logging from process 'netdata' (prevented 4604 logs in the last 1200 seconds).
2020-02-10 07:02:09: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 07:02:09: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_from_other_template_xcp_ng_sam_2843a3b0_a068_9880_a6be_8305b528882.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 07:02:09: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_fedora_server_30_xcp_ng_sam_97e1ec1d_6b55_659a_cecb_0c03bd0fc27.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 07:02:09: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_sve_centos_7_uefi_a685e92e_4e9c_385b_d7c9_69711d4d6cd.vcpu' on host 'xcp-ng-sam2' already exists.
2020-02-10 07:02:10: netdata INFO  : PLUGINSD[xenstat] : RRDSET: chart name 'xendomain_domain_0_845f8737_547f_4f2b_b29b_b70f1959eb1.vcpu' on host 'xcp-ng-sam2' already exists.
```

I checked that and reproduced this on all hosts that I checked.

##### OS / Environment
XCP-ng 8.0, XCP-ng 8.1 beta

##### Netdata version
netdata v1.19.0

##### Component Name
xenstat plugin

##### Steps To Reproduce
* Install XCP-ng 8.0
* `yum install netdata-ui`
* watch /var/log/netdata/error.log

##### Expected behavior
I don't know what to expect exactly, but I suppose that the "already exists" information that is filling the error log is probably not useful OR that is reveals a bug.

### PR DESCRIPTION
**Pull request by rushikeshjadhav**
Fixes #8019 

##### Summary
Since Variable `last_num_vcpus` is static, it holds the metric value of vcpu count of previous iteration/virtual machine. This variable is compared before assignment. In most cases this leads to unlikely scenario of `num_vcpus != last_num_vcpus` thus constantly flooding error logs and generating/updating charts.

##### Component Name
collectors/xenstat.plugin

##### Test Plan
Run netdata on any Xen host including XCP-ng/Xenserver and observe error log.

### CODE REVIEW

**Comment by rushikeshjadhav** [comment]
Some checks that were not successful are not related to the patch. Can someone suggest if I need to redo PR?

**Comment by ilyam8** [comment]
@vlvkobal ^^

**Comment by vlvkobal** [comment]
No. I don't think so.

**Comment by rushikeshjadhav** [comment]
Hi @ilyam8 @vlvkobal Do you have a suggestion to move further on this?

**Comment by ilyam8** [comment]
@rushikeshjadhav 👋 
We are in code freeze atm, this PR will be merged a little bit later

**Comment by stormi** [comment]
Are we past the code freeze now?

**Comment by vlvkobal** [comment]
Yes. We can merge it. @thiagoftsm please look at it. I've built the branch on XCP-ng, it works.

**Pull request merged**
