### PR TITLE
add --reinstall-clean flag for kickstart.sh

### PR DESCRIPTION
**Pull request by maneamarius**
##### Summary

Add support for clean reinstall in kickstart script.
##### Test Plan
Installed netdata using kickstart using native, static and build methods, then used kickstart with clean reinstall flag.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by ilyam8** [comment]
@maneamarius and we need to update [our documentation](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#optional-parameters-to-alter-your-installation) too

**Comment by maneamarius** [comment]
> @maneamarius can you please split the changes into 2 commits:
> 
> * add "main" function
> * add "--reinstall-clean" flag for kickstart.sh

What purpose would this serve?

**Review by iigorkarpov — DISMISSED** [review]

**Comment by maneamarius** [comment]
> @maneamarius and we need to update [our documentation](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#optional-parameters-to-alter-your-installation) too

I will find out how this is done and create a PR for the doc, thanks for pointing it out!

**Comment by ilyam8** [comment]
> What purpose would this serve?

This would make the review easier.

**Pull request closed without merging**
