### PR TITLE
Fix typo inside netdata-installer.sh

### LINKED ISSUE #9961: netdatacli not located in /usr/bin/
To stop netdata run:

  /usr/bin/netdatacli shutdown-agent

/usr/bin/netdatacli shutdown-agent
-bash: /usr/bin/netdatacli: No such file or directory

OS:
Debian 11 Sid

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes #9961 

As discussed in the specified issue, this PR is fixing the typo that we have inside `netdata-installer.sh`
##### Component Name
Installer.

##### Test Plan
Install Netdata on an environment that has Netdata is already running and verify that the error is fixed

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]

**Comment by vlvkobal** [comment]
Hm...
```
[vlad@arch-esxi netdata]$ ll /usr/sbin/netdatacli
-rwxr-xr-x 1 root root 1212272 Sep 20 23:32 /usr/sbin/netdatacli
[vlad@arch-esxi netdata]$ ll /usr/bin/netdatacli
-rwxr-xr-x 1 root root 1212272 Sep 20 23:32 /usr/bin/netdatacli
```

**Comment by thiagoftsm** [comment]
@vlvkobal I never had `netdatacli` on my `/usr/bin`, how did you install this Netdata?

**Comment by thiagoftsm** [comment]
@vlvkobal  to complement my previous question, take a look in the Makefie.am:

https://github.com/netdata/netdata/blob/f6a1be4daac668a13c829963351875c236851d79/Makefile.am#L728

how it is expected inside `netdata-claim.sh`:

https://github.com/netdata/netdata/blob/f6a1be4daac668a13c829963351875c236851d79/claim/netdata-claim.sh.in#L92

And finally our uninstaller script:

https://github.com/netdata/netdata/blob/f6a1be4daac668a13c829963351875c236851d79/packaging/installer/netdata-uninstaller.sh#L463

Unless I am missing something, the `netdatacli` is  expected inside `/usr/sbin/`.

**Comment by ilyam8** [comment]
```cmd
0 ~ $ docker run --rm -d netdata/netdata
0681b1b0ea37523584b86bea3f30971229bd8f97bda1405df0329c2c5534163f
0 ~ $ docker exec -it modest_knuth whereis netdatacli
netdatacli: /usr/sbin/netdatacli
```

**Comment by vlvkobal** [comment]
> @vlvkobal I never had netdatacli in my /usr/bin, how did you install this Netdata?

```
[vlad@arch-esxi netdata]$ ll /usr/sbin
lrwxrwxrwx 1 root root 3 Aug 21 14:19 /usr/sbin -> bin
```
That's the peculiarities of Arch Linux :grin:

**Review by prologic — APPROVED** [review]

**Pull request merged**
