### PR TITLE
Claim on Windows

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
This PR is adding the possibility to claim a Windows Agent. To reach this goal, it is modifying the installer and creating `claim.conf` during installation or when a new command is executed.

Screenshot_20240829_173951

##### Test Plan
1. Compile this Branch
2. Generate a installer and use it.
3. Go to `C:\Program Files\Netdata\etc\netdata\` and check the existence of the file `claim.conf`.
4. Access your cloud dashboard, your Windows Host must appear there:

cloud

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by stelfrag** [comment]
When running the command to build the package, i get 

```
cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt': Permission denied
cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem': Permission denied
cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem': Permission denied
cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem': Permission denied
cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/java/cacerts': Permission denied
cp: cannot create regular file '/opt/netdata/usr/bin/bashbug': Permission denied
```

**Comment by thiagoftsm** [comment]
> When running the command to build the package, i get
> 
> ```
> cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt': Permission denied
> cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem': Permission denied
> cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem': Permission denied
> cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem': Permission denied
> cp: cannot create regular file '/opt/netdata/etc/pki/ca-trust/extracted/java/cacerts': Permission denied
> cp: cannot create regular file '/opt/netdata/usr/bin/bashbug': Permission denied
> ```

I will address this in another PR, because it does not have direct relationship with this. For now, please, remove your `/opt/netdata` before to create the package.

**Review by Ferroin — COMMENTED** [review]
The new `src/resoruces` directory should almost certainly instead be `packaging/windows/resources` given that none of it is actually used as part of the build process.

**Comment by thiagoftsm** [comment]
> The new `src/resoruces` directory should almost certainly instead be `packaging/windows/resources` given that none of it is actually used as part of the build process.

I need to generate the object files with `windres`, and after this they are appended to the binaries.

**Comment by ktsaou** [comment]
Please name it `Room(s)`. The field may have a comma separated list of rooms.

**Comment by thiagoftsm** [comment]
> Please name it `Room(s)`. The field may have a comma separated list of rooms.

Done. Last commit renamed everything, and I also updated OP description with current images.

**Review by stelfrag — APPROVED** [review]

**Pull request merged**
