### PR TITLE
Reorganize system directory to better reflect what files are actually used for.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This reorganizes the `system/` directory so that files are sorted into sub-directories based on what they are actually used for. This allows us to avoid the complicated naming gymnastics we have needed thus far for these files, which makes maintaining them somewhat easier, and also allows new contributors to more easily understand what is actually going on.

##### Test Plan

Testing consists of two primary parts:

1. Verifying that all CI is passing on this PR. This is to ensure that the packaging code is picking things up correctly.
2. Installing locally on various systems, and confirming that things like installation as a system service are still working correctly. Essentially, everything should look and behave identically with and without this PR, except for some files being in different places under `/usr/lib/netdata/system`.

##### Additional Information

This PR should result in no functional changes from the perspective of an end-user.

### CODE REVIEW

**Review by cakrit — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
PR is working as expected on:

- Slackware current
- FreeBSD 13.1-RELEASE-p5
- Alma 8.6

LGTM!

**Comment by andrewm4894** [comment]
@Ferroin are these ok?

image

**Comment by Ferroin** [comment]
@andrewm4894 Two bugs mixed in there (will have a commit fixing those in a moment), but the rest is exactly how it should be (almost all of it is matching stuff on the target system, _not_ in our source tree).

**Review by thiagoftsm — DISMISSED** [review]
After last commit, I also tested on:

- Ubuntu 22.10
- Alma 9
- CentOS 7

LGTM!

**Comment by Ferroin** [comment]
Rebased to resolve merge conflict.

**Review by thiagoftsm — APPROVED** [review]
Considering we only have a rebase, LGTM!

**Pull request merged**
