### PR TITLE
Update ObservabilityCon README.md

### PR DESCRIPTION
**Pull request by Aliki92**
##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by Ancairon — APPROVED** [review]
Looks right in both light and dark mode.

**Review by ilyam8 — APPROVED** [review]

**Comment by Ancairon** [comment]
@ilyam8 let's not merge, the image needs to link to the website, at the moment it opens the image in a new tab

**Comment by Ancairon** [comment]
This is very strange, if I set the img element to point to a link that ends in .png, the thing works and directs us to the website, if the link if a github asset link, then we open the image in a new tab...

we need to figure out how to do this, @Aliki92 from where did you get the `#gh-dark-mode-only` part of the link? Does it work elsewhere? Because I can see the current master README doesn't work either :thinking:

**Comment by Ancairon** [comment]
I see @christophidesp had edited the README and the sections up top with the icons before, so he might be able to help

**Comment by christophidesp** [comment]
@Ancairon I had the same issue as you described it. When I had a .svg at my case, that was linked from websites' github it was rendering properly (but there was an issue with privacy), but when immediately uploaded here, the linking stopped working. Also from requirements, for this to work, the image needs to be hosted in github. So basically it wasn't solved as an issue, same happens with the Netdata logo.

**Comment by Ancairon** [comment]
So we merge as is?

**Comment by christophidesp** [comment]
@Ancairon is there a place where we can host the images inside netdata/netdata? Maybe that could work? If not then can merge as is.

**Comment by Ancairon** [comment]
We can even host them at our website repo I reckon and link them from there :thinking:

**Pull request merged**
