### PR TITLE
Regenerate integrations.js

### PR DESCRIPTION
**Pull request by netdatabot**
Regenerate `integrations/integrations.js`, and documentation based on the
latest code.

This PR was auto-generated by
`.github/workflows/generate-integrations.yml`.

### CODE REVIEW

**Review by ilyam8 — DISMISSED** [review]

**Comment by Ancairon** [comment]
This PR should now contain the integrations documentation and autogenerated collectors/COLLECTORS.md.

I will take a look as some manual adjustments might be nice to be added to this PR, and then test it with the ingest script.

**Comment by Ancairon** [comment]
A preview of this PR and https://github.com/netdata/go.d.plugin/pull/1349 can be found at https://staging--netdata-docusaurus.netlify.app/docs/

Check sections:
https://staging--netdata-docusaurus.netlify.app/docs/data-collection/
https://staging--netdata-docusaurus.netlify.app/docs/alerting/notifications/
https://staging--netdata-docusaurus.netlify.app/docs/exporting/

From the checklist of https://github.com/netdata/learn/issues/1767 there is https://github.com/netdata/learn/issues/1784 that is not yet closed.

From that I think only the last one that is assigned to @thiagoftsm about tc.plugin is important to merge before this PR, as the README will be gone, and there is info missing in the yaml file.

The rest can be done after we merge, as by now they are the only thing left.

Some links will be broken due to us not including some READMEs anymore (apps.plugin README for example), but I can pick them out, and either fix the link (preferably) (point the link to a file that is on Learn, first 3 files in Data collection would be the example that links on apps.plugin, cgroups.plugin and the likes can link to from now on) or make a redirect (not so ideal).

**Review by andrewm4894 — APPROVED** [review]

**Review by hugovalente-pm — DISMISSED** [review]

**Comment by thiagoftsm** [comment]
> once we merge #16068 this is good to go.

PR was merged.

**Review by thiagoftsm — APPROVED** [review]

**Review by ilyam8 — CHANGES_REQUESTED** [review]
In my opinion the result (data collection on learn) is unacceptable and super confusing. As a learn user I am against merging (publishing) as is and want to express it with request for changes. Feel free to ignore it but I feel like I need to do it 😀 I will elaborate tomorrow (on mobile now)

**Comment by Ancairon** [comment]
Let's elaborate and try and find a solution, as this is now in the final phase, ingest has been shut down for the release steps and everything is a merge away from publishing

Let's discuss on slack

**Review by sashwathn — APPROVED** [review]

**Review by andrewm4894 — DISMISSED** [review]

**Comment by andrewm4894** [comment]
@Ancairon can you add the latest final preview links to the issue description - just so someone like Costa if looks at this can easily just go have a look.

**Comment by Ancairon** [comment]
Added it up top

**Review by hugovalente-pm — DISMISSED** [review]

**Comment by andrewm4894** [comment]
@ilyam8 i think this is blocked by your change requests 

> Feel free to ignore it but I feel like I need to do it 😀 I will elaborate tomorrow (on mobile now)

So i think we literally can't merge this at the moment. 

Once myself, @Ancairon, @hugovalente-pm, @sashwathn and @shyamvalsan all approve i think that should be enough to merge this given its mainly docs related and something @ktsaou has been asking for asap for for a while (i am 90% sure this PR get's the original ask from @ktsaou done). 

I agree with some of your points for sure but don't quite see them as blockers for this PR more so things we can think about improving on in next iterations. 

I think you might need to approve it (and express your reservations in the msg :) ) or we might have to ask @netdata/agent-sre to red button it (just not sure it actually can be merged with your change requests still outstanding on it) just to work around the GH stuff (or i may very well be misunderstanding if the PR can be merged if enough approve even with outstanding CR's, not sure tbh)

**Review by ilyam8 — COMMENTED** [review]
remove req for changes

**Review by ilyam8 — APPROVED** [review]

**Review by sashwathn — DISMISSED** [review]

**Review by andrewm4894 — APPROVED** [review]

**Review by andrewm4894 — APPROVED** [review]

**Review by Ancairon — APPROVED** [review]

**Comment by Ancairon** [comment]
Let's merge this before any other change happens that triggers a regeneration, as it dumps two manual symlinks I make every time.

**Pull request merged**
