### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**
I'm pretty sure some of the changes will likely cause build failures and some should probably not be touched, but here it goes!

### CODE REVIEW

**Comment by ilyam8** [comment]
Hi, @rex4539. Thanks for the contribution! This PR touches too many areas (see the list of reviewers/code owners).

Can you split it into several PRs? A PR per area would be the best. It will help us to review and merge PRs relatively quickly.

Let's start with collectors and docs.

-  **Docs**: all files that end with '.md' or '.mdx'.

<details>
<summary>docs files [click]</summary>

- "docs/dashboard/import-export-print-snapshot.mdx"
- "docs/guides/monitor/anomaly-detection.md"
- "docs/guides/monitor-cockroachdb.md"
- "docs/guides/monitor/statsd.md"
- "docs/guides/python-collector.md"
- "docs/Running-behind-lighttpd.md"
- "health/notifications/syslog/README.md"
- "health/REFERENCE.md"
- "collectors/ebpf.plugin/README.md"
- "collectors/proc.plugin/README.md"
- "collectors/python.d.plugin/changefinder/README.md"
- "collectors/python.d.plugin/zscores/README.md"
- "collectors/statsd.plugin/README.md"
- "packaging/installer/methods/kickstart.md"
- "packaging/installer/methods/source.md"
- "packaging/installer/methods/synology.md"


</details>

- **Collectors**: everything under 'collectors/' excluding 'collectors/python.d.plugin/python_modules/*' (bundled 3rd party libraries).
 
<details>
<summary>collectors files [click]</summary>

- "collectors/apps.plugin/apps_plugin.c"
- "collectors/cgroups.plugin/sys_fs_cgroup.c"
- "collectors/charts.d.plugin/ap/ap.chart.sh"
- "collectors/charts.d.plugin/apcupsd/apcupsd.chart.sh"
- "collectors/charts.d.plugin/example/example.chart.sh"
- "collectors/charts.d.plugin/libreswan/libreswan.chart.sh"
- "collectors/charts.d.plugin/nut/nut.chart.sh"
- "collectors/charts.d.plugin/opensips/opensips.chart.sh"
- "collectors/charts.d.plugin/sensors/sensors.chart.sh"
- "collectors/ebpf.plugin/ebpf_apps.c"
- "collectors/ebpf.plugin/ebpf.c"
- "collectors/ebpf.plugin/ebpf_cachestat.c"
- "collectors/ebpf.plugin/ebpf_dcstat.c"
- "collectors/ebpf.plugin/ebpf_fd.c"
- "collectors/ebpf.plugin/ebpf_mount.c"
- "collectors/ebpf.plugin/ebpf_oomkill.c"
- "collectors/ebpf.plugin/ebpf_process.c"
- "collectors/ebpf.plugin/ebpf_shm.c"
- "collectors/ebpf.plugin/ebpf_socket.c"
- "collectors/ebpf.plugin/ebpf_swap.c"
- "collectors/ebpf.plugin/ebpf_vfs.c"
- "collectors/node.d.plugin/named/named.node.js"
- "collectors/proc.plugin/proc_net_dev.c"
- "collectors/proc.plugin/proc_pagetypeinfo.c"
- "collectors/proc.plugin/sys_class_infiniband.c"
- "collectors/python.d.plugin/anomalies/anomalies.chart.py"
- "collectors/python.d.plugin/go_expvar/go_expvar.chart.py"
- "collectors/python.d.plugin/mongodb/mongodb.chart.py"
- "collectors/python.d.plugin/postgres/postgres.conf"
- "collectors/python.d.plugin/zscores/zscores.conf"

</details>

**Comment by rex4539** [comment]
Hi @ilyam8. I don't have time to do this (my free time is over) but if anyone else wants to take over, feel free.

But in any case, it shouldn't take more than 5 minutes for someone to review. It's just typos.

**Comment by ilyam8** [comment]
@rex4539 thanks for your time, fixing typos (especially in the documentation) is always a good thing 👍 

> but if anyone else wants to take over, feel free.

I went forward and removed the changes from bundled 3rd party libraries and our dashboard files (which lives in https://github.com/netdata/dashboard and we just copy files to netdata/netdata)

**Comment by ilyam8** [comment]
btw @rex4539 what tool did you use to find all these typos?

**Comment by rex4539** [comment]
> btw @rex4539 what tool did you use to find all these typos?

https://github.com/codespell-project/codespell

**Review by vlvkobal — APPROVED** [review]

**Review by ilyam8 — DISMISSED** [review]

**Review by DShreve2 — DISMISSED** [review]
Approve the .md and .readme fixes. 

Thanks!

**Comment by ilyam8** [comment]
Force push to pick up new ci changes.

**Review by ilyam8 — APPROVED** [review]

**Review by vlvkobal — APPROVED** [review]

**Pull request merged**
