### PR TITLE
Make method in url service configurable

### LINKED ISSUE #4127: httpcheck support for HTTP methods  (e.g. GET, OPTIONS, HEAD, etc...)
Hey

I'm currently evaluating Netstat for monitoring on our systems and have been quite impressed so far.  

We're interested in the new httpcheck plugin in paticular.  Is there any way to specify the http method it uses when making the call?  We typically used HEAD & OPTIONS instead of GET where possible.

Cheers,
R.

### PR DESCRIPTION
**Pull request by ccremer**
Fixes #4127

I took matter in my own hands :)
Verified working:
```yaml
service:
  url: http://localhost:8080/
  method: POST
```
with and without commented method parameter produces the following output on my nginx docker:
```
172.17.0.1 - - [22/Sep/2018:18:38:56 +0000] "GET / HTTP/1.1" 200 612 "-" "-" "-"
172.17.0.1 - - [22/Sep/2018:18:38:57 +0000] "GET / HTTP/1.1" 200 612 "-" "-" "-"
172.17.0.1 - - [22/Sep/2018:18:43:52 +0000] "POST / HTTP/1.1" 405 173 "-" "-" "-"
172.17.0.1 - - [22/Sep/2018:18:43:54 +0000] "POST / HTTP/1.1" 405 173 "-" "-" "-"
172.17.0.1 - - [22/Sep/2018:18:44:39 +0000] "GET / HTTP/1.1" 200 612 "-" "-" "-"
172.17.0.1 - - [22/Sep/2018:18:44:39 +0000] "GET / HTTP/1.1" 200 612 "-" "-" "-"
```
@l2isbad please review

### CODE REVIEW

**Comment by ccremer** [comment]
I forgot to document it.

**Comment by ktsaou** [comment]
> I forgot to document it.

Shall I wait for you, or merge it now?

**Comment by ccremer** [comment]
I did add a comment in the config file. so, merge :)

**Comment by ccremer** [comment]
it takes a whole 30 minutes to do all these checks...

**Comment by paulfantom** [comment]
@ccremer but not all of them are required

**Pull request merged**
