### PR TITLE
node.d/snmp: snmpv3 support

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

Fixes: #1363

SNMPv3 support is merged to the library we use in `snmp` collector

> https://github.com/netdata/netdata/issues/1363#issuecomment-574898634

The change is pretty trivial, according @markabrahams

> There's only one new public API call added to the net-snmp library:
snmp.createV3Session(target, user, [options])

> which you would call for v3 instead of snmp.createSession(target, [community], [options]) for v1 or v2c.

##### Component Name

[`node.d.plugin/snmp`](https://github.com/netdata/netdata/tree/master/collectors/node.d.plugin/snmp)

##### Additional Information

- [X] update `net-snmp` library to the [latest](https://github.com/markabrahams/node-net-snmp)
- [X] add snmpv3 support to the `snmp` collector
- [x] update `snmp` collector documentation

i dont think we really need to test snmpv3 since it would be testing the library.

### CODE REVIEW

**Comment by ilyam8** [comment]
@Stonemage hi, could you help me to test the PR?

**Comment by ilyam8** [comment]
@jacekkolasa this is my first `js` code, do not judge me strictly 😄 

I agree, code style could be better, for me it looks like `c` code written in `js`  😄 I just followed existing code style.

**Comment by jacekkolasa** [comment]
congratulations then! :)
it's just a hint, but yeah, adjusting to current code style is good, too

**Comment by ilyam8** [comment]
@jacekkolasa i used https://jsonlint.com/ to lint json data. I am not really sure about tabs/spaces.

- https://jsonlint.com/ uses tabs
- https://jsonformatter.curiousconcept.com/ uses spaces

Which linter should i use?

**Comment by jacekkolasa** [comment]
i think that neither of them. We have eslint configuration in the repository, which doesn't specify tabs nor spaces, but i think LGTM will complain if we'll have mixed formatting. I see spaces in the PR code (which is good), maybe your IDE automatically transformed that

You can install eslint locally (via npm) and check it, or configure your editor to use that config file, but i think that if LGTM is ok, we don't have to do anything else

**Comment by ilyam8** [comment]
> I see spaces in the PR code (which is good), maybe your IDE automatically transformed that

yes, i formatted code using JB json formatter (`Editor->Code Style->JSON`) with default configuration.

**Comment by jacekkolasa** [comment]
You mean Code Style/JavaScript probably
In Webstorm i normally set `Preferences | Languages & Frameworks | JavaScript | Code Quality Tools | ESLint` to "Automatic ESLint configuration", which detects some settings.

**Comment by ilyam8** [comment]
I use PyCharm Professional working on this PR.

**Comment by ilyam8** [comment]
@jacekkolasa i've finished with the PR, please review/approve again.

**Comment by ilyam8** [comment]
i have server with snmp collector enabled, i installed the PR, nothing is broken, i think it is safe to merge.

**Comment by ilyam8** [comment]
@jacekkolasa 

We updated `net-snmp` library to the latest, as a result:

Debian8 has nodejs v `0.10.29~dfsg-2`, snmp module fails to run and exits with following error

```js
/opt/netdata/usr/libexec/netdata/node.d/node_modules/net-snmp.js:2412
        message.user = authorizer.users.filter(localUser => localUser.name ==
                                                          ^
2020-01-22 06:14:45: node.d.plugin: ERROR: Cannot load module: /opt/netdata/usr/libexec/netdata/plugins.d/../node.d/snmp.node.js exception: SyntaxError: Unexpected token >
```

i guess `0.10.29~dfsg-2` is ancient

After update to `4.7.2~dfsg-2~bpo8+1` (which is in backports) no problem anymore.

Debian10 nodejs version is `10.15.2~dfsg-2`.

___

So if we want snmpv3 and current `net-snmp` module (which looks reasonable) we can break snmp collector for some servers with ancient `net-snmp` module.

@cakrit what do you think?

**Comment by ilyam8** [comment]
We could mention min nodejs version in the README and that is it.

**Comment by cosmix** [comment]
Yes that’s what we should be doing. Very old systems can stay on older versions of Netdata.

**Comment by ilyam8** [comment]
@jacekkolasa could you help me? In which version was this syntax added?

**Comment by jacekkolasa** [comment]
@ilyam8 the arrow functions were added in v4. Full support is in v6, but i've checked the net-snmp code and it should work with v4.

So if you ask for minimal requirement, we could say v4, but highest stable LTS (v12) should be recommended

**Comment by ilyam8** [comment]
@jacekkolasa @amoss please approve again

**Pull request merged**
