### PR TITLE
Remove coredump

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
After to compile from scratch the kernel `6.9.8`, I observed that my hash table was having PIDs with the maximum integer value possible. This value was bigger than value present inside my `/proc/sys/kernel/pid_max` and this result in a coredump:

```sh
(gdb) bt
#0  ebpf_get_pid_entry (pid=-437918235, tgid=0) at /home/thiago/Netdata/netdata/src/collectors/ebpf.plugin/ebpf_apps.c:465
#1  0x000000000043279d in collect_data_for_all_processes (tbl_pid_stats_fd=7, maps_per_core=maps_per_core@entry=1)
    at /home/thiago/Netdata/netdata/src/collectors/ebpf.plugin/ebpf_apps.c:1121
#2  0x0000000000408e81 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/thiago/Netdata/netdata/src/collectors/ebpf.plugin/ebpf.c:4062
```

This PR is modifying internal code avoiding coredumps on systems.

##### Test Plan
I am not sure if this is happening because I had an issue when kernel was generated, but if this is happening on other OS, it will be necessary to test this PR on kernel `6.9.8` or newer, because this behavior was not observed in previous versions.

1. Compile branch
2. Verify eBPF.plugin is running with default options.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by thiagoftsm** [comment]
After I compile my kernel again, I am not having the issue anymore, but considering that it happens, because I had issues with previous compilation, I will still keep this PR.

**Comment by stelfrag** [comment]
> After I compile my kernel again, I am not having the issue anymore, but considering that it happens, because I had issues with previous compilation, I will still keep this PR.

I can't see how this can happen, unless an invalid PID was added there in the first place.

**Comment by thiagoftsm** [comment]
> I can't see how this can happen, unless an invalid PID was added there in the first place.

I agree. My environment can have max PID `32768`, but in hash tables I was having something around 3 million, this was the reason I made this PR.

After this I recompile the kernel and I did not observe event anymore.

**Comment by thiagoftsm** [comment]
After to recompile the kernel yesterday, I did not have more the issue with different branches, so I am going to close this.

**Pull request closed without merging**
