### PR TITLE
overload libc memory allocators with custom ones to trace all allocations

### PR DESCRIPTION
**Pull request by ktsaou**
This completes the work of tracing all netdata memory allocations.

it works like this:

1. It gets function pointers to the existing `malloc()`, `calloc()`, `realloc()`, `reallocarray()`, `strdup()`, `free()`, etc.
2. It defines all these functions to use internal `z` implementations, that report usage per function.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hello @ktsaou ,

Years ago I did not use any function from `dl` library because `musl` compiler did not have complete support, to verify that the issue did not exist anymore I decided to use `Alpine 3.16`, but I had a segmentation fault:

```sh
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000055d483a52600 in malloc_trace_find_or_create (file=file@entry=0x55d483c27bb5 "daemon/static_threads.c", function=function@entry=0x55d483c27c40 <__FUNCTION__.0> "static_threads_concat", line=line@entry=163)
    at libnetdata/libnetdata.c:173
#2  0x000055d483a52936 in callocz_int (nmemb=nmemb@entry=18, size=size@entry=56, file=file@entry=0x55d483c27bb5 "daemon/static_threads.c", function=function@entry=0x55d483c27c40 <__FUNCTION__.0> "static_threads_concat", 
    line=line@entry=163) at libnetdata/libnetdata.c:228
#3  0x000055d483a30941 in static_threads_concat (lhs=0x55d483cbad60 <static_threads_common>, rhs=rhs@entry=0x55d483cbb080 <static_threads_linux>) at daemon/static_threads.c:163
#4  0x000055d483ba6d26 in static_threads_get () at daemon/static_threads_linux.c:61
#5  0x000055d483a2db9e in main (argc=1, argv=0x7ffd25071d28) at daemon/main.c:878
(gdb) 
```

Only to remember, `musl` is the compiler used to generate our static binaries.

**Comment by thiagoftsm** [comment]
On the other hand, I can confirm that your PR is able to run when we compile it using `gcc`.
The safest scenario will be to use the current structure when we are not compiling with `musl`.

@Ferroin am I missing something?

**Comment by ktsaou** [comment]
Try again musl. I had a bug.

**Comment by thiagoftsm** [comment]
Hello @ktsaou ,

Unfortunately the issue persists, and this is what I have from `strace` and `gdb bt`:

```sh
mmap(0x7fc021e07000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0xd000) = 0x7fc021e07000
close(3)                                = 0
mprotect(0x7fc02218d000, 4096, PROT_READ) = 0
mprotect(0x7fc022144000, 176128, PROT_READ) = 0
mprotect(0x7fc021ee6000, 36864, PROT_READ) = 0
mprotect(0x7fc021e70000, 4096, PROT_READ) = 0
mprotect(0x7fc021e67000, 4096, PROT_READ) = 0
mprotect(0x7fc021e3b000, 4096, PROT_READ) = 0
mprotect(0x7fc021e07000, 4096, PROT_READ) = 0
mprotect(0x7fc022222000, 4096, PROT_READ) = 0
mprotect(0x557363a23000, 20480, PROT_READ) = 0
arch_prctl(ARCH_SET_FS, 0x7fc022226240) = 0
set_tid_address(0x7fc022225fb0)         = 10477
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7ffd4cca5ff8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault
alpine316:/home/thiago/Netdata/netdata# gdb /usr/sbin/netdata core
Reading symbols from /usr/sbin/netdata...
[New LWP 10477]
Core was generated by `netdata'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005573637c19f5 in __netdata_rwlock_rdlock (rwlock=rwlock@entry=0x557363a56f50 <malloc_trace_index+16>) at libnetdata/locks/locks.c:217
217     int __netdata_rwlock_rdlock(netdata_rwlock_t *rwlock) {
(gdb) bt
#0  0x00005573637c19f5 in __netdata_rwlock_rdlock (rwlock=rwlock@entry=0x557363a56f50 <malloc_trace_index+16>) at libnetdata/locks/locks.c:217
#1  0x00005573637aab71 in avl_read_lock (t=t@entry=0x557363a56f40 <malloc_trace_index>) at libnetdata/avl/avl.c:324
#2  0x00005573637aac79 in avl_search_lock (tree=tree@entry=0x557363a56f40 <malloc_trace_index>, item=item@entry=0x7ffd4cca6070) at libnetdata/avl/avl.c:387
#3  0x00005573637be5b7 in malloc_trace_find_or_create (file=file@entry=0x55736399c6e8 "libnetdata/libnetdata.c", function=function@entry=0x55736399cbff <__FUNCTION__.40> "malloc", line=line@entry=61) at libnetdata/libnetdata.c:171
#4  0x00005573637be794 in mallocz_int (size=size@entry=152, file=file@entry=0x55736399c6e8 "libnetdata/libnetdata.c", function=function@entry=0x55736399cbff <__FUNCTION__.40> "malloc", line=line@entry=61) at libnetdata/libnetdata.c:210
#5  0x00005573637be864 in malloc (size=size@entry=152) at libnetdata/libnetdata.c:61
#6  0x00007fc0221b23d6 in calloc (m=<optimized out>, n=152) at src/malloc/calloc.c:40
```

and the back trace repeats the last 4 lines.

**Comment by thiagoftsm** [comment]
I found strange the event of repeat last 4 lines many times, so I ran `netdata` again without `strace` and I observed now this:

```sh
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005597b01e258c in malloc_trace_find_or_create (file=file@entry=0x5597b03c06e8 "libnetdata/libnetdata.c", function=function@entry=0x5597b03c0bff <__FUNCTION__.40> "malloc", line=line@entry=61) at libnetdata/libnetdata.c:165
165         struct malloc_trace tmp = {
(gdb) bt
#0  0x00005597b01e258c in malloc_trace_find_or_create (file=file@entry=0x5597b03c06e8 "libnetdata/libnetdata.c", function=function@entry=0x5597b03c0bff <__FUNCTION__.40> "malloc", line=line@entry=61) at libnetdata/libnetdata.c:165
#1  0x00005597b01e2794 in mallocz_int (size=size@entry=152, file=file@entry=0x5597b03c06e8 "libnetdata/libnetdata.c", function=function@entry=0x5597b03c0bff <__FUNCTION__.40> "malloc", line=line@entry=61) at libnetdata/libnetdata.c:210
#2  0x00005597b01e2864 in malloc (size=size@entry=152) at libnetdata/libnetdata.c:61
#3  0x00007f67630793d6 in calloc (m=<optimized out>, n=152) at src/malloc/calloc.c:40
```

So we have different threads dying when they use the same functions.

**Comment by ktsaou** [comment]
@thiagoftsm please try again...

**Comment by thiagoftsm** [comment]
Hello @ktsaou,

I used last commit and we still have the issues:

```sh
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/netdata...
[New LWP 10476]
Core was generated by `netdata'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d3160726bc in malloc_trace_find_or_create (file=file@entry=0x55d31625073a "libnetdata/libnetdata.c", function=function@entry=0x55d316250c1f <__FUNCTION__.40> "malloc", line=line@entry=106) at libnetdata/libnetdata.c:211
211         struct malloc_trace tmp = {
(gdb) bt
#0  0x000055d3160726bc in malloc_trace_find_or_create (file=file@entry=0x55d31625073a "libnetdata/libnetdata.c", function=function@entry=0x55d316250c1f <__FUNCTION__.40> "malloc", line=line@entry=106) at libnetdata/libnetdata.c:211
#1  0x000055d3160728b3 in mallocz_int (size=size@entry=152, file=file@entry=0x55d31625073a "libnetdata/libnetdata.c", function=function@entry=0x55d316250c1f <__FUNCTION__.40> "malloc", line=line@entry=106)
    at libnetdata/libnetdata.c:253
#2  0x000055d316072972 in malloc (size=size@entry=152) at libnetdata/libnetdata.c:106
#3  0x00007f3238a493d6 in calloc (m=<optimized out>, n=152) at src/malloc/calloc.c:40
```

The git log:

```sh
alpine316:/home/thiago/Netdata/netdata# git log
commit 86b93321b460e97f7167dd3c1179f0f08379a279 (HEAD -> pr13810)
Author: Costa Tsaousis <costa@netdata.cloud>
Date:   Wed Oct 12 14:32:36 2022 +0300

    dynamically link every library function when needed for the first time

commit 829264c4c0c2a8c592d0a4b03770861233b172f5
Author: Costa Tsaousis <costa@netdata.cloud>
Date:   Wed Oct 12 13:40:14 2022 +0300

    add optional dl libs

commit 1ecab9b67814f2f96eb25a0d71f7bf8710d13146
Author: Costa Tsaousis <costa@netdata.cloud>
Date:   Wed Oct 12 12:52:34 2022 +0300

    initialize global variable

commit b33e7021bd8b35e4b8c9f798227999adfdb2ae21
Author: Costa Tsaousis <costa@netdata.cloud>
Date:   Wed Oct 12 12:49:25 2022 +0300
```

It looks like that library is recognized on Alpine, but it does not have correct code to properly load symbols/lib.

**Comment by ktsaou** [comment]
Unfortunately on alpine I don't know how to fix it.
i get this:

```
(gdb) bt
#0  0x00005555555a7cbf in malloc_trace_find_or_create (file=<error reading variable: Cannot access memory at address 0x7fffff7fefe8>, function=<error reading variable: Cannot access memory at address 0x7fffff7fefe0>, line=<error reading variable: Cannot access memory at address 0x7fffff7fefd8>) at libnetdata/libnetdata.c:252
#1  0x00005555555a7f8d in mallocz_int (size=152, file=0x5555558328f9 "libnetdata/libnetdata.c", function=0x5555558331b0 <__FUNCTION__.40> "malloc", line=127) at libnetdata/libnetdata.c:295
#2  0x00005555555a790d in malloc (size=152) at libnetdata/libnetdata.c:127
#3  0x00007ffff7f8a3d6 in calloc () from /lib/ld-musl-x86_64.so.1
#4  0x0000000000000000 in ?? ()
```

Somehow the pointers are mangled. The code on `malloc_int` lookds like this:

```c
void *mallocz_int(size_t size, const char *file, const char *function, size_t line) {
    struct malloc_trace *p = malloc_trace_find_or_create(file, function, line);
   ...
}
```

So, the call to `malloc_int()` has valid pointers, but the call to `malloc_trace_find_or_create()` has different ones!
Strange! I can't tell why...

**Comment by ktsaou** [comment]
So, the effect of this PR can only be enabled with `-DNETDATA_TRACE_ALLOCATIONS=1`. Without it, it works on alpine as it was before (no memory tracing).

This is ready to be merged. No harm should be done by it.

**Comment by thiagoftsm** [comment]
Hello @ktsaou ,

As I said this looks like an issue with `musl`,  I will retest your PR now.

Best regards!

**Review by thiagoftsm — APPROVED** [review]
This PR was tested with success on `Slackware current`, and `Alpine 3.16`. LGTM!

**Pull request merged**
