### PR TITLE
Support SOCKS5 in ACLK Challenge/Response and rewrite with LWS

### LINKED ISSUE #8091: ACLK Authentication should support Socks5 Proxies
##### Feature idea summary

The auth endpoints will be implemented as direct calls to the openssl library to perform the requests and retrieve the JSON payloads from the cloud endpoints. This will not easily permit the addition of SOCK5 proxy support as we do not to implement the proxy wrapper ourselves.

* Convert the working auth endpoint calls to the libwebsocket equivalents.
* Use the libwebsockets SOCK5 support to make the requests.
* Use the previously implemented config-file / env-var to decide what to do. 
* Check with Cloud/SRE about the need for authentication credentials.

##### Expected behavior

* SRE team has confirmed that `ssh -D` will be appropriate as a proxy.
* Verify that both endpoints work through a SOCK5 proxy.

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Rewrite Challenge/Repsonse code with LWS to enable SOCKS5 .Fixes #8091

##### Test Plan
Test with Cloud Local Environment
- Cannot connect to target (wrong IP) - OK
- Cannot connect to port (IP correct) - OK
- Local dev env (i.e. without SOCKS5) - working case - OK
- Local dev env (i.e. without SOCKS5) - non-working case (by purposefully sending wrong response). Detected correctly `ACLK_Main : Challenge-response failed` - OK
- SOCKS from VM (running ssh -D) to Local Dev Env - OK
- Using SOCKS5 - with cloud test enviroment.  - OK

### CODE REVIEW

**Comment by cosmix** [comment]
@underhood what is missing from this PR? Why is it a draft?

**Comment by amoss** [comment]
We need to see a list of tests cases in the Test Plan for this PR.
* Local dev env (i.e. without SOCKS5) - working case (valid challenge).
* Local dev env (i.e. without SOCKS5) - non-working case (in-valid challenge).
* Using SOCK5 - working case.
* Using SOCKS5 - non-working case.

What is required to finish the PR -  i.e. get rid of draft / WIP so that it is ready for review?

**Comment by amoss** [comment]
I see this in the logs when I have no proxy configured:
```
2020-03-15 11:25:40: netdata ERROR : ACLK_Main : SEND_HTTPS_REQUEST GET
2020-03-15 11:25:40: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-03-15 11:25:40: netdata INFO  : ACLK_Main : Connecting using SOCKS5 proxy:"env"
2020-03-15 11:25:40: netdata ERROR : ACLK_Main : LWS failed to accept socks proxy. (errno 2, No such file or directory)
2020-03-15 11:25:40: netdata ERROR : ACLK_Main : SEND_HTTPS_REQUEST POST
2020-03-15 11:25:40: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-03-15 11:25:40: netdata INFO  : ACLK_Main : Connecting using SOCKS5 proxy:"env"
2020-03-15 11:25:40: netdata ERROR : ACLK_Main : LWS failed to accept socks proxy. (errno 2, No such file or directory)
```

**Comment by amoss** [comment]
Why are there `strdupz()` calls around the `buffer_tostring()`? The buffer is local an mutable, and then the extra string is freed immediately afterwards. One of them has a TODO with `<PR-BLOCK>` - is there a problem here that needs to be resolved?

**Comment by amoss** [comment]
Including `libwebsockets.h` in `agent_cloud_link.c` is not a good idea, it breaks the encapsulation around the transport layer. Now that `send_https_request` only accesses lws calls it would make more sense to move `send_https_request` into `aclk_lws_wss_client.c` instead.

**Comment by amoss** [comment]
I'm worried by this line:
```
    while( n >= 0 && !data->done && !netdata_exit) n = lws_service(context, 0);
```
If we have an unexpected code-path through the LWS callbacks then the ACLK will never restart. We need some kind of timeout around this and a failure case if the timeout expires.

**Comment by amoss** [comment]
If I set the cloud base url to a different port to force a connection failure on the challenge then I get this in the logs:
```
2020-03-15 12:01:31: netdata ERROR : ACLK_Main : JSON: Invalid json string. (errno 111, Connection refused)
```
The connection failure is not being detected - it should not proceed into the json parsing.

**Comment by amoss** [comment]
If I change the cloud base url to a non-existent host then the thread does not recover and reattempt the link:
```
2020-03-15 12:03:52: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: localp0stoffice 8443 /api/v1/auth/node/99fa2
382-49b3-11ea-b9ff-448a5bd059c8/challenge
2020-03-15 12:03:52: netdata ERROR : ACLK_Main : SEND_HTTPS_REQUEST GET
2020-03-15 12:03:52: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-03-15 12:03:52: netdata INFO  : ACLK_Main : Connecting using SOCKS5 proxy:"env"
2020-03-15 12:03:52: netdata ERROR : ACLK_Main : LWS failed to accept socks proxy. (errno 2, No such file or directory)
2020-03-15 12:03:52: netdata ERROR : ACLK_Main : 2020-03-15 12:03:52: python.d ERROR: traefik[local] : _get_data() returned no
 data or type is not <dict>
```
The last line is confusing, I think it is a truncated output followed by a log line from a different thread.

**Comment by underhood** [comment]
> Why are there `strdupz()` calls around the `buffer_tostring()`? The buffer is local an mutable, and then the extra string is freed immediately afterwards. One of them has a TODO with `<PR-BLOCK>` - is there a problem here that needs to be resolved?

yep the <PR-BLOCK> is my tag marking places that were just hacked and need to be fixed before making PR

**Comment by amoss** [comment]
Next case, an agent that thinks it is claimed, but the cloud does not.
```
==24516== Thread 9 ACLK_Main:
==24516== Invalid read of size 1
==24516==    at 0x4838C62: strlen (vg_replace_strmem.c:460)
==24516==    by 0x52AC9EE: vfprintf (vfprintf.c:1638)
==24516==    by 0x52AD865: buffered_vfprintf (vfprintf.c:2322)
==24516==    by 0x52AAEB1: vfprintf (vfprintf.c:1296)
==24516==    by 0x5363737: __vfprintf_chk (vfprintf_chk.c:33)
==24516==    by 0x1DF8F0: UnknownInlinedFun (stdio2.h:130)
==24516==    by 0x1DF8F0: error_int (log.c:781)
==24516==    by 0x171AD9: aclk_get_challenge (agent_cloud_link.c:1430)
==24516==    by 0x171E64: aclk_try_to_connect (agent_cloud_link.c:1492)
==24516==    by 0x1728E1: aclk_main (agent_cloud_link.c:1569)
==24516==    by 0x1E3783: thread_start (threads.c:170)
==24516==    by 0x523FFA2: start_thread (pthread_create.c:486)
==24516==    by 0x53544CE: clone (clone.S:95)
==24516==  Address 0x5f2ed20 is 0 bytes inside a block of size 1 free'd
==24516==    at 0x48369AB: free (vg_replace_malloc.c:530)
==24516==    by 0x17154E: UnknownInlinedFun (libnetdata.c:173)
==24516==    by 0x17154E: aclk_get_challenge (agent_cloud_link.c:1426)
==24516==    by 0x171E64: aclk_try_to_connect (agent_cloud_link.c:1492)
==24516==    by 0x1728E1: aclk_main (agent_cloud_link.c:1569)
==24516==    by 0x1E3783: thread_start (threads.c:170)
==24516==    by 0x523FFA2: start_thread (pthread_create.c:486)
==24516==    by 0x53544CE: clone (clone.S:95)
==24516==  Block was alloc'd at
==24516==    at 0x483577F: malloc (vg_replace_malloc.c:299)
==24516==    by 0x52E2DB9: strdup (strdup.c:42)
==24516==    by 0x1EC11D: strdupz (libnetdata.c:166)
==24516==    by 0x17151F: aclk_get_challenge (agent_cloud_link.c:1422)
==24516==    by 0x171E64: aclk_try_to_connect (agent_cloud_link.c:1492)
==24516==    by 0x1728E1: aclk_main (agent_cloud_link.c:1569)
==24516==    by 0x1E3783: thread_start (threads.c:170)
==24516==    by 0x523FFA2: start_thread (pthread_create.c:486)
==24516==    by 0x53544CE: clone (clone.S:95)
```
Corresponding logs:
```
2020-03-15 12:24:04: netdata INFO  : ACLK_Main : Attempting to establish the agent cloud link
2020-03-15 12:24:04: netdata INFO  : ACLK_Main : Retrieving challenge from cloud: dev.private.netdata.cloud 8443 /api/v1/auth/
node/99fa2382-49b3-11ea-b9ff-448a5bd059c8/challenge
2020-03-15 12:24:04: netdata ERROR : ACLK_Main : SEND_HTTPS_REQUEST GET
2020-03-15 12:24:04: netdata INFO  : ACLK_Main : Disabling SSL certificate checks
2020-03-15 12:24:04: netdata INFO  : ACLK_Main : Connecting using SOCKS5 proxy:"socks5://127.0.0.1:11081"
2020-03-15 12:24:24: netdata ERROR : ACLK_Main : JSON: Invalid json string. (errno 115, Operation now in progress)
2020-03-15 12:24:24: netdata ERROR : ACLK_Main : Could not parse the json response with the challenge:
2020-03-15 12:24:25: netdata INFO  : ACLK_Main : Retrying to establish the ACLK connection in 1.946 seconds
```
There are different problems shown here:
* The twenty second delay to get back a response
* The memory leak
* The failure to handle the rejection from the cloud properly.

**Comment by underhood** [comment]
the SOCKS5 problem is fixed. I check other things.

**Comment by amoss** [comment]
Running a claimed agent with the socks5 proxy setup I get this:
```
2020-03-15 12:48:09: netdata ERROR : ACLK_Main : JSON: Invalid json string. (errno 115, Operation now in progress)      
2020-03-15 12:48:09: netdata ERROR : ACLK_Main : Could not parse the json response with the challenge: ÀZí<92>âU 
```

**Comment by underhood** [comment]
I was thinking into spliting it into new file because i do not believe  `aclk_lws_wss_client.c` is good place for it (it handles the MQTT/LWS integration)

**Comment by amoss** [comment]
> I was thinking into spliting it into new file because i do not believe `aclk_lws_wss_client.c` is good place for it (it handles the MQTT/LWS integration)

Sounds fine. If you introduce a new file to the build - remember that we have two build systems.

**Comment by underhood** [comment]
Well there is other reason that include was moved and that is function `aclk_wss_set_socks` so that it may be in common and used by both things.

**Comment by underhood** [comment]
Memory leak was already there before this commit:
`aclk_get_challenge` creates new buffer but on error exits it doesn't clean it, I will fix it in my PR.
Code from current master:
```C
    BUFFER *b = buffer_create(NETDATA_WEB_RESPONSE_INITIAL_SIZE);
    // TODO - target host?
    char *agent_id = is_agent_claimed();
    if (agent_id == NULL)
    {
        error("Agent was not claimed - cannot perform challenge/response");
        return;
    }
```

**Pull request merged**
