### PR TITLE
Faster streaming by 25% on the child

### PR DESCRIPTION
**Pull request by ktsaou**
We are testing a child-parent setup where the child tries to push 800k metrics / second to the parent.

Without streaming on the child, this works. It can collect 800k metrics / second for go.d.plugin.
With streaming however, the child cannot push more than 450k metrics / second.

With this PR, the child can push about 600k metrics / second to the parent, about 25% - 30% increase.

My observation is the following:

1. The code uses the shared chart flags for keeping sender flags in them. This requires atomic operations for every single chart. These can be eliminated by having a different `sender_flags` member in RRDSET and using it without atomics (there will be no data race in this case, because the sending thread is fixed for each chart - although many charts use different threads, each of the charts is fixed to one thread).
2. The same is true for host flags. Quite a few atomics probably without reason.
3. `sender_start()` and `sender_commit()` have been implemented in a non-scalable way. Sender commit locks the entire host from sending metrics for way too long, forcing all threads to be serialized. It does not matter if the child has 10 threads collecting the metrics, they will go one by one in this `send_start()`, `sender_commit()` loop. Ideally, there should be a thread `BUFFER *` variable returned by `sender_start()`, which will be filled up and be compressed without any locks, and acquire the mutex for just copying the compressed buffer into the circular buffer for dispatch.

We probably need to re-think streaming. Now the child and parent are doing the same job. The child is pushing collected values and both the parent and the child have to interpolate them to store them in their databases. Probably it would be a lot faster to push from the child interpolated data, which the parent will just get and store. A binary protocol would also benefit the performance a lot.

### CODE REVIEW

**Comment by thiagoftsm** [comment]
@ktsaou I tested this PR during one hour, where the parent was our current `master`, and the children were the PR, and the parent died reporting this:

```sh
=================================================================
==13488==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f08ff2c88c0 at pc 0x00000046f56b bp 0x7f08ff2c7fd0 sp 0x7f08ff2c7790
WRITE of size 56 at 0x7f08ff2c88c0 thread T64
    #0 0x46f56a in unpoison_tm(void*, __sanitizer::__sanitizer_tm*) (/usr/sbin/netdata+0x46f56a)
    #1 0x478a40 in localtime_r (/usr/sbin/netdata+0x478a40)
    #2 0x566fff in log_date libnetdata/log/log.c:464
    #3 0x566fff in info_int libnetdata/log/log.c:769
    #4 0x9cc216 in release_statement database/sqlite/sqlite_functions.c:138
    #5 0x7f092a891e20 in __GI___nptl_deallocate_tsd (/lib64/libc.so.6+0x88e20)
    #6 0x7f092a894e44 in start_thread (/lib64/libc.so.6+0x8be44)
    #7 0x7f092a91f9eb in clone3 (/lib64/libc.so.6+0x1169eb)

Address 0x7f08ff2c88c0 is located in stack of thread T64 at offset 64 in frame
    #0 0x566e96 in info_int libnetdata/log/log.c:751

  This frame has 4 object(s):
    [32, 40) 't' (line 460)
    [64, 120) 'tmbuf' (line 461) <== Memory access at offset 64 is inside this variable
    [160, 184) 'args' (line 752)
    [224, 250) 'date' (line 768)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T64 created by T62 here:
    #0 0x43f5e6 in pthread_create (/usr/sbin/netdata+0x43f5e6)
    #1 0x7f092aadd618 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/usr/lib64/libstdc++.so.6+0xdd618)
    #2 0x918ef7 in ml_new_host ml/ml.cc:55
    #3 0x9afd9c in rrdhost_create database/rrdhost.c:546
    #4 0x9b11a4 in rrdhost_find_or_create database/rrdhost.c:687
    #5 0xbefc51 in rrdpush_receive streaming/receiver.c:515
    #6 0xbf2189 in rrdpush_receiver_thread streaming/receiver.c:777
    #7 0x58531c in thread_start libnetdata/threads/threads.c:199
    #8 0x7f092a894fe9 in start_thread (/lib64/libc.so.6+0x8bfe9)

Thread T62 created by T40 here:
    #0 0x43f5e6 in pthread_create (/usr/sbin/netdata+0x43f5e6)
    #1 0x58597c in netdata_thread_create libnetdata/threads/threads.c:213
    #2 0xbe151d in rrdpush_receiver_thread_spawn streaming/rrdpush.c:869
    #3 0xc0bcb1 in web_client_process_request web/server/web_client.c:1469
    #4 0xc12d9f in web_server_rcv_callback web/server/static/static-threaded.c:304
    #5 0x57d4a6 in poll_process_tcp_read libnetdata/socket/socket.c:1440
    #6 0x57d4a6 in poll_events libnetdata/socket/socket.c:1759
    #7 0xc12708 in socket_listen_main_static_threaded_worker web/server/static/static-threaded.c:427
    #8 0x58531c in thread_start libnetdata/threads/threads.c:199
    #9 0x7f092a894fe9 in start_thread (/lib64/libc.so.6+0x8bfe9)

Thread T40 created by T18 here:
    #0 0x43f5e6 in pthread_create (/usr/sbin/netdata+0x43f5e6)
    #1 0x58597c in netdata_thread_create libnetdata/threads/threads.c:213
    #2 0xc15512 in socket_listen_main_static_threaded web/server/static/static-threaded.c:540
    #3 0x58531c in thread_start libnetdata/threads/threads.c:199
    #4 0x7f092a894fe9 in start_thread (/lib64/libc.so.6+0x8bfe9)

Thread T18 created by T0 here:
    #0 0x43f5e6 in pthread_create (/usr/sbin/netdata+0x43f5e6)
    #1 0x58597c in netdata_thread_create libnetdata/threads/threads.c:213
    #2 0x516df3 in main daemon/main.c:1513
    #3 0x7f092a82c176 in __libc_start_call_main (/lib64/libc.so.6+0x23176)

```

Tomorrow I will test the PR on parent side.

**Comment by thiagoftsm** [comment]
@vkalintiris, please, take a look in [this](https://github.com/netdata/netdata/pull/13708#issuecomment-1255750209) error.

**Comment by ilyam8** [comment]
@thiagoftsm

> where the parent was our current master, and the children were the PR

I guess you didn't check master/master? Is this problem related to this PR?

**Comment by vkalintiris** [comment]
> @vkalintiris, please, take a look in [this](https://github.com/netdata/netdata/pull/13708#issuecomment-1255750209) error.

I don't think this is related to ML code. Can you reproduce this consistently? Is it reproducible when you build without internal checks?

**Comment by ktsaou** [comment]
This is probably related to this:

```
    #4 0x9cc216 in release_statement database/sqlite/sqlite_functions.c:138
```

@stelfrag please have a look

**Comment by ktsaou** [comment]
It seems that the log is using the `statement` which was previously allocated in stack.

**Comment by thiagoftsm** [comment]
> I guess you didn't check master/master? Is this problem related to this PR?

You are right, I did not test master/master yet. And I do not think it has relationship with this PR. I am trying to recreate this issue again in the next minutes, because @vkalintiris asked me this. After this I will test the parent with this PR. Finally I will debug our current master.

**Review by thiagoftsm — APPROVED** [review]
The issue I reported does not have relationship with this. When I tested it on parent and child everything worked as expected.
I also observed the issue only one time when I compiled with `libasan`, I tested the PR without it and I did not observe error.
Considering everything I described, I am approving this PR and I will debug our master branch. LGM!

**Review by stelfrag — APPROVED** [review]

**Comment by thiagoftsm** [comment]
@vkalintiris and @stelfrag  I could replicate the issue again tonight and I will create a new issue for it. I also detected another with FreeBSD that I am investigating.

**Pull request merged**
