### PR TITLE
Improvements to dash-example.html

### PR DESCRIPTION
**Pull request by tnyeanderson**
##### Summary

* Fixes a race condition that caused graphs to not load
* Moves configuration to the top of the file
* Improves docs
* Other small fixes

**NOTE: This file is not maintained by Netdata, it is just meant to be an example of multi-host streaming capabilities**

##### Component Name

`dash-example.html`

##### Test Plan

**NOTE: This file is not maintained by Netdata, it is just meant to be an example of multi-host streaming capabilities**

### CODE REVIEW

**Review by joelhans — APPROVED** [review]
The docs portion of this LGTM.

Since @OdysLam is here, I wonder if this example `.html` and associated docs content would be better suited for the netdata/community repo. I feel like we had a discussion about the best place to put `dash-example.html` a long, long time ago, but the community repo didn't exist at that time.

We don't have to do it immediately, but I'd like to eventually take steps to distinguish between supported methods/processes and those contributed by the community.

**Comment by tnyeanderson** [comment]
Personally, I think it belongs in the community repo as well... but like you said it didn't exist at the time. Would you mind if the changes are merged here, then I can open a separate PR on the community repo to add this stuff to it, and a PR here to remove it. I mostly want it done this way so it is clear that changes were made and not just that the files were moved. But if the netdata team has another preference, that's fine too.

**Comment by OdysLam** [comment]
Hey @joelhans that's a very good idea. @tnyeanderson thanks for helping us with this. I agree completely, let's create a new category in the community repo: `netdata-agent-dashboard/<custom_dashboard_name>`.

If you want any help, we have a whole [category](https://community.netdata.cloud/c/agent-development/9) on our forums dedicated to contributors, so please ping me there! If you got this, just go ahead and create a PR in the community repo!

**Comment by joelhans** [comment]
@jacekkolasa Any feedback on this? This information will eventually leave the repo and go elsewhere, so it's mostly if you notice to recommend stylistically or have any recommendations.

@tnyeanderson I think your plan on merging this, then adding a second PR to remove it, once it's been added to the community repo, makes a lot of sense. We'll try our best to help you get it through in the next few days.

**Comment by jacekkolasa** [comment]
Moving to seperate community repo is a nice idea, the only thing that worries me is that dash-example.html won't be available right after Agent installation.
On the other hand, adding static files to https://github.com/netdata/dashboard allows users to have those files available immediately after installation.

@novykh @amalkov @netdata/cloud-fe any ideas/opinions?

Apart from that I agree it could be merged. Thanks @tnyeanderson!

**Review by jacekkolasa — APPROVED** [review]

**Comment by OdysLam** [comment]
Conceptually I agree, since it will also reduce the area that we have to maintain. I believe that such examples should go to the community, both conceptually and for maintainability.

The less surface that we have, the easier is to maintain and act proactively before users find a feature broken.

I think that this too should be a @netdata/product-driven decision. cc @manos-saratsis

**Comment by manos-saratsis** [comment]
@OdysLam Needs discussion, I am fine if commits like these remain on the community repo but if there is something that can benefit all Netdata users, it could go to netdata/netdata

**Comment by OdysLam** [comment]
Discussed @manos-saratsis about this. Probably a good idea to move it to community repo, since the user value is limited in respect to having another surface to maintain.

Also, conceptually it will fit nicely into the community repo. I will make the PR @jacekkolasa. 

Thanks, @tnyeanderson for inciting this conversation. It was very beneficial for the project as a whole!

**Comment by tnyeanderson** [comment]
@OdysLam Thanks for discussing and coming up with the right spot! Since you are creating the PR, do you need anything else from me for the transition? I'm happy to help if needed :)

**Comment by OdysLam** [comment]
@tnyeanderson

Thanks for suggesting this. Actually, I always prefer that the community makes the PRs. So:
1) Fork the community repo and clone it locally
2) Create a new branch
3) Create a directory `netdata-agent-dashboard/<sample_app_name>`
4) Add readme + dash-example.html into the directory
5) Commit everything and make the PR

I would be happy to help you along the way.  BTW, make sure you sign up to our contributors group ;) https://community.netdata.cloud/g/contributors

**Comment by OdysLam** [comment]
Hey @tnyeanderson, do you need any help with the PR in the community? 

I see that you are 1 PR away from been considered as Netdata Core member, that is with 10 PRs or more in our repos. Dont miss the chance 😎

**Comment by tnyeanderson** [comment]
Hi @OdysLam, I'm so sorry for the delay. I will get those PRs in tonight and will be excited to call myself a Netdata Core member :) thank you so much for your patience and assistance through this and I apologize for taking so long!

**Pull request merged**
