### PR TITLE
Patch release 1.45.5

### PR DESCRIPTION
**Pull request by stelfrag**
##### Summary
- go.d windows add "vnode" to config schema (#17478)
- go.d cockroachdb fix calculation (#17659)
- Fix usage of sha256sum in static builds. (#17495)
- fix sender parsing when receiving remote input (#17696)
- Check for empty dimension id from a plugin (#17690)
- Re-enable ML for RHEL 7 and AL 2 RPM packages. (#17682)
- Fix CentOS 7 builds for ML. (#17667)
- Include the Host in the HTTP header (#17670)
- Improve handling of an alert that transitions to the REMOVED state (#17621)

### CODE REVIEW

**Comment by vkalintiris** [comment]
@stelfrag I'm not sure about releases, but I think we should cherry-pick https://github.com/netdata/netdata/pull/17682 as well.

**Comment by Ferroin** [comment]
This also needs the following PRs added:

- https://github.com/netdata/netdata/pull/17664 (this is a major correctness fix in the build system, and not having it breaks the build on some systems).
- https://github.com/netdata/netdata/pull/17648 (we have customers who were asking about this one, and it technically is a bug fix since the behavior it provides is what was intended in the first place).

**Comment by Ferroin** [comment]
Also, https://github.com/netdata/netdata/pull/17495 needs to be included (it should have been included in v1.45.4, but I forgot about it when we were putting that one together).

**Comment by ilyam8** [comment]
@stelfrag lets add

- #17696
- #17659
- #17478

**Comment by stelfrag** [comment]
> This also needs the following PRs added:
> 
> * [Correctly handle required compilation flags for dependencies. #17664](https://github.com/netdata/netdata/pull/17664) (this is a major correctness fix in the build system, and not having it breaks the build on some systems).
> * [Support offline installs in the updater code. #17648](https://github.com/netdata/netdata/pull/17648) (we have customers who were asking about this one, and it technically is a bug fix since the behavior it provides is what was intended in the first place).

These two have merge conflicts

**Comment by stelfrag** [comment]
> @stelfrag lets add
> 
> * [fix sender parsing when receiving remote input #17696](https://github.com/netdata/netdata/pull/17696)
> * [go.d cockroachdb fix calculation #17659](https://github.com/netdata/netdata/pull/17659)
> * [go.d windows add "vnode" to config schema #17478](https://github.com/netdata/netdata/pull/17478)

This has a merge conflict
 [go.d windows add "vnode" to config schema #17478](https://github.com/netdata/netdata/pull/17478)

**Comment by stelfrag** [comment]
> > @stelfrag lets add
> > 
> > * [fix sender parsing when receiving remote input #17696](https://github.com/netdata/netdata/pull/17696)
> > * [go.d cockroachdb fix calculation #17659](https://github.com/netdata/netdata/pull/17659)
> > * [go.d windows add "vnode" to config schema #17478](https://github.com/netdata/netdata/pull/17478)
> 
> This has a merge conflict [go.d windows add "vnode" to config schema #17478](https://github.com/netdata/netdata/pull/17478)

Resolved conflicts for go.d windows add "vnode" to config schema (#17478)

**Pull request merged**
