### PR TITLE
Adjust alarms count

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Adjust `/api/v1/alarm_count` to match `/api/v1/alarms`.

When we fill the alarms in `health_alarms2json_fill_alarms` we take into account `rrdset_is_available_for_exporting_and_alarms`. Same consideration should be taken when counting them via `health_aggregate_alarms` to match the number of `WARNING` and `CRITICAL` (when of course we don't use the `all` parameter in `/api/v1/alarms`).

##### Test Plan

Will be tested via set team to see if it fixes a discrepancy in tests. cc @dimko

### CODE REVIEW

**Comment by MrZammler** [comment]
@dimko Hey Dimitris, if you have any more feedback, but from a quick check we had it seemed to improve the situation.

**Comment by thiagoftsm** [comment]
In my local tests the code is giving the expected results, I am waiting for @dimko confirmation.

**Review by stelfrag — APPROVED** [review]

**Comment by dimko** [comment]
@MrZammler it seems to improve the situation. I've run the tests multiple times from an image build from this source and haven't noticed the discrepancies. Let's merge it and will come back to you if I see anything weird.

**Comment by MrZammler** [comment]
Thanks guys!

**Pull request merged**
