### PR TITLE
eBPF new charts (user ring)

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
This PR is adding metrics to monitor how eBPF.plugin memory usage. The new metrics will show:

- Total memory allocated for hash table (Same algorithm used by `bpftool`).
- Charts to monitor calls to allocate ARAL and memory allocated per ARAL.

This PR is also renaming ARAL regions to match what is shown on user dashboard.

##### Test Plan
1. Compile this branch with CFLAG `NETDATA_DEV_MODE`
2. Modify your configuration file `/etc/netdata/ebpf.d.conf` and enable integration between eBPF and apps:
```sh
[global]
    apps = yes
    cgroups = yes

```
3. Take a look if charts are shown inside `Netdata Monitoring`.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
Describe the PR affects users: 
- Which area of Netdata is affected by the change? ebpf.plugin
- Can they see the change or is it an under the hood? If they can see it, where? They will see only when compile with CFLAG `NETDATA_DEV_MODE`
- How is the user impacted by the change? We have conditions to monitor and understanding possible issue with memory allocation.
- What are there any benefits of the change?  An easy way to address issue and understanding memory consumption. 
</details>

### CODE REVIEW

**Comment by MrZammler** [comment]
Hi Thiago!

I'm checking this, and I get `netdata.ebpf_kernel_memory` & `netdata.ebpf_hash_tables_count`, but not the ARAL related ones.

I tried to look a bit, and e.g. cachestat seems to run, but I don't think it calls `ebpf_statistic_create_aral_chart` ? Likely `ebpf_aral_cachestat_pid` has not been allocated? Or I'm missing something... ?

**Comment by thiagoftsm** [comment]
> Hi Thiago!
> 
> I'm checking this, and I get `netdata.ebpf_kernel_memory` & `netdata.ebpf_hash_tables_count`, but not the ARAL related ones.
> 
> I tried to look a bit, and e.g. cachestat seems to run, but I don't think it calls `ebpf_statistic_create_aral_chart` ? Likely `ebpf_aral_cachestat_pid` has not been allocated? Or I'm missing something... ?

Hello @MrZammler ,

These charts are shown only when we compile with `-DNETDATA_DEV_MODE=1`, did you specify this `CFLAGS`?

Best regards!

**Comment by MrZammler** [comment]
Yes, did compile with `-DNETDATA_DEV_MODE=1`.

**Comment by thiagoftsm** [comment]
> Yes, did compile with `-DNETDATA_DEV_MODE=1`.

Firstly I apologize for the OP description :facepalm: , I updated it. We need to compile with CFLAGS and also enable integration with `apps`. On my environment this is always enabled and I missed that.

**Review by stelfrag — APPROVED** [review]

**Pull request merged**
