### PR TITLE
Web

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes: #6287
Fixes: #6288

During my work with the Netdata I noted two problems that were described in two issues that are described in "Additional Information". Thanks Ivon support I am sending these fixes, that at least in my side worked correctly.
##### Component Name
WEB Gui
##### Additional Information
The issues that I reported the error were #6287 and #6288 .

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hi @VLegakis , I think I missed something in your comments, are you said that we missed something with LGTM? Chirstopher said me to merge and I did not see any errors with netlify and Travis too. Please, can you explain me better. Thanks!

**Comment by cakrit** [comment]
He means it Looks Good To Me (him) :)

**Comment by VLegakis** [comment]
Thanks @chris this is it!
Sorry @thiago! Too many acronyms :P

**Comment by thiagoftsm** [comment]
No problem @VLegakis, it was a good class about the subject to me! :)

**Pull request merged**
