### PR TITLE
Add more configuration info to the PHP-FM collector readme

### PR DESCRIPTION
**Pull request by cakrit**
Update the README due to the confusion in issue #5964
Add more details on the PHP-FM module configuration.

### CODE REVIEW

**Comment by ilyam8** [comment]
i suggest:
 - update example config adding remote insance (like in [apache readme](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/apache#configuration))
 - add a link to collector configuration file (like [there](https://github.com/ilyam8/go.d.plugin/tree/master/modules/x509check#configuration))

Please do not copy the whole .conf to readme

**Comment by ilyam8** [comment]
There is one more example
https://github.com/netdata/go.d.plugin/tree/master/modules/scaleio

i went further and moved chart to a separate file, i think readme should be small and clear and not wall of text.

**Comment by cakrit** [comment]
> i went further and moved charts to a separate file, i think readme should be small and clear and not wall of text.

This changes the logic of one README.md per collector with effects on the generated html docs as well. If you've moved them, the info will be invisible in the docs site and we'll need to add yet another drop-down (not good, as we already have 4 levels to get to the modules). There's nothing wrong with a long README, though we could definitely format the list of charts in a much better way, so it doesn't take up all this space.  

I'll make changes on this one when I get some free time.

**Comment by cakrit** [comment]
I'm closing this. We'll review with @ilyam8 the collector documentation overall.

**Pull request closed without merging**
