### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by ilyam8** [comment]
Hi, @rex4539. Thanks for the contribution! But the following changes need to be reverted:

- `collectors/python.d.plugin/python_modules/*` (third-party vendor-packages).
- `web/gui/dashboard/*` (bundled https://github.com/netdata/dashboard).

**Comment by rex4539** [comment]
> Hi, @rex4539. Thanks for the contribution! But the following changes need to be reverted:
> 
> * `collectors/python.d.plugin/python_modules/*` (third-party vendor-packages).
> * `web/gui/dashboard/*` (bundled https://github.com/netdata/dashboard).

Reverted

**Review by ilyam8 — APPROVED** [review]
lgtm, @andrewm4894 please check ml/notebooks/netdata_anomaly_detection_deepdive.ipynb changes

**Review by thiagoftsm — APPROVED** [review]
Thank you very much, LGTM!

**Review by andrewm4894 — APPROVED** [review]
thank you!

**Pull request merged**
