### PR TITLE
Remove and/or relocate top-level files.

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

SSIA.

Using `packaging/{cmake,utils}` as a placeholder for file related to building/checking/testing the agent's source code. Not ideal but it'll do for now.

##### Test Plan

- CI jobs.

### CODE REVIEW

**Comment by vkalintiris** [comment]
@Ferroin @tkatsoulas I believe the coverity job fails only because I opened the PR from a branch on my remote fork.

**Review by Ferroin — CHANGES_REQUESTED** [review]
I reiterate the issue I brought up when this was discussed in our daily syncs, having linter configs outside of the repo root is not expected behavior, and thus raises the burden of contribution.

I agree with essentially everything else (and some of it even overlaps with https://github.com/netdata/netdata/pull/16938), but breaking convention on linter configuration is a non-starter from my perspective.

**Comment by Ferroin** [comment]
> @Ferroin @tkatsoulas I believe the coverity job fails only because I opened the PR from a branch on my remote fork.

Yes, you can ignore the failure there.

**Comment by vkalintiris** [comment]
@Ferroin I take it that the main objection here is the shellcheckrc, right?

> and some of it even overlaps with https://github.com/netdata/netdata/pull/16938)

Do you want to cherry-pick the non-overlapping commits into your PR?

**Comment by Ferroin** [comment]
> @Ferroin I take it that the main objection here is the shellcheckrc, right?

Yes, everything else changed here looks fine IMO.

> > and some of it even overlaps with #16938)
> 
> Do you want to cherry-pick the non-overlapping commits into your PR?

If you would prefer to handle it that way I can do so, but I’m also fine with you cherry-picking the non-overlapping stuff from my PR, or even just dropping the overlapping bits there. At minimum I think the way you handled the Coverity script in this one is better than the approach I was taking, so I would preferentially keep that bit from this PR.

**Comment by vkalintiris** [comment]
Closing in favor of https://github.com/netdata/netdata/pull/16938.

**Pull request closed without merging**
