### PR TITLE
Add a 2 minute timeout to stream receiver socket

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This PR adds a 10 minute timeout on the receiver socket for streaming connections.

When this is set, after 10 minutes of no received data from a child it will exit the parser, and declare the child ORPHAN. This could be useful in cases where the child disappears from the network before sending a disconnect.

The default timeout without setting it, is I believe 0, which can cause the connection to remain open. (If anyone knows, please advise).

##### Test Plan

Setup a child and parent. 

Disconnect the child from the network, and observe what happens with and without this PR. With this PR after 10 minutes of inactivity the receiving thread should stop, and the child be considered ORPHAN. If the child returns during this 10 minute span, it should continue normally to stream.

### CODE REVIEW

**Review by Marychoffel22 — APPROVED** [review]
Imapmail@icloud.com

**Comment by MrZammler** [comment]
We should also check if possible with an SSL connection between child and parent (thanks @thiagoftsm ).

**Review by thiagoftsm — DISMISSED** [review]
I tested this PR on two different environments. When I used `slackware current` and TLS compiled with parameters:

```
bash-5.1# openssl version -f
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG
```

I did not observe the expected results, on the other hand, when I tested on `Alma Linux` where openssl was compiled with:

```
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
```

Everything worked as expected. Assuming the problem are options given during openssl compilation, LGTM!

**Comment by stelfrag** [comment]
We may want to consider also the timeout set on the child side. So what happens if the parent is waiting for say 10 minutes but on the child side it will drop the connection in 60 seconds? Would it make sense for those to be the same?

**Comment by MrZammler** [comment]
Agree, 10 minutes seems much, I was mostly playing safe.

We should also consider maybe, since this will affect them, the reach-ability notifications too.

Would 120 seconds be a good compromise? We don't want too little as to not trigger many in/out children reported to the cloud, neither too long to delay a detection of missing child.

**Review by thiagoftsm — APPROVED** [review]
The last commit only updated a variable value, so I am approving this PR without retest it.

**Review by stelfrag — APPROVED** [review]

**Comment by MrZammler** [comment]
Merged, but will get back to it to make it configurable in `stream.conf`.

**Pull request merged**
