### PR TITLE
Move mdstat python module to proc plugin

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
cpuidle python module reads data from files:
`/proc/mdstat`
`/sys/block/*/md/mismatch_cnt`

Since we already have a C plugin that parses files in `/proc` and `/sys`, it is natural to move python code with similar functionality into it.

Partly implements #4541

##### Component Name
`mdstat` python module
`proc` plugin

##### Additional Information
C module parses `mdstat` using `procfile()` capabilities, instead of using regular expressions.

### CODE REVIEW

**Comment by Ferroin** [comment]
Relevant: #4010

**Comment by cakrit** [comment]
Please also update README.md when the module becomes obsolete. Same as with the BASH obsolete modules.

**Comment by ilyam8** [comment]
@vlvkobal ping me whe this is ready, i will test it

**Comment by ktsaou** [comment]
Please rebase this. It broke with the merge of cpuidle.
Is this ready for review?

**Comment by ktsaou** [comment]
@vlvkobal 	just read it. Nice work!

I see only 1 issue:

If we add and remove raid arrays all the time, the plugin will not mark the obsolete ones as `OBSOLETE` in netdata, so netdata will never cleanup. This is a somewhat rare use case, it was probably not supported by the python plugin either, but I think it is relatively easy to be supported here.

So, I suggest to refactor it, like this:

- The structure is mainly needed just for keeping pointers to charts and dimensions. All other data are read from the data source every time. So, I would create a linked list with the pointers, a name and a hash. A function called `find_or_allocate_mdstat_data(const char *name)` could be used to search through the list or create a new entry. This can be done with hashes, to be very fast.

- Each of the nodes in the linked list could have a member called `updated`. This should be set to 1 when `find_or_allocate_mdstat_data()` returns it.

- At the end of each iteration, a loop through the list should identify the nodes that have `updated == 0`, and mark the charts as `OBSOLETE` in netdata (and possibly free that nodes). It should also set `updated = 0` on all nodes, to be ready for the next iteration.

I think the above setup will also simplify it a bit.

What do you think?

**Pull request merged**
