### PR TITLE
Only load required charts for rrdvars

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

This PR changes which charts are loaded for health rrdvars. Instead of loading every chart, only charts that are linked to an alert or charts that are needed by alerts, will be loaded. This can lead to a reduction of memory usage of health.

During alert config loading, the `calc`, `warn` and `crit` attributes will be scanned for variables, and these will be stored in a dictionary. What we are basically looking for here are variables that an alert needs that are from another chart that the alert runs on. An example is alert `system_clock_sync_state` which uses `$system.uptime.uptime`. When the chart `system.uptime` is checked during health's delayed initialization, it will check whether a dimension of it is required on an alert. If yes, it will be added to rrdvars.

##### Test Plan

Needs to be tested in both standalone and parent/child setups to make sure alerts are being calculated as before. In case a variable is missing, the alert will likely have a value of `-`.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  

Reduce the memory usage of the agent.

</details>

### CODE REVIEW

**Review by thiagoftsm — APPROVED** [review]
Alert, streaming and threads are working as expected, LGTM!

**Comment by underhood** [comment]
seems to introduce codacy alert

**Review by underhood — CHANGES_REQUESTED** [review]
codacy error

**Review by underhood — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
I retested after last fix, lgtm!

**Comment by MrZammler** [comment]
Thanks!

**Pull request merged**
