### PR TITLE
remove deprecated fping.plugin in accordance with v1.37.0 deprecation notice 

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

This PR removes the following plugins ([v1.37.0 deprecation notice](https://github.com/netdata/netdata/releases/tag/v1.37.0#v1370-deprecation)):

- fping.plugin

##### Test Plan

- ci.
- `git grep fping`.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by thiagoftsm** [comment]
@ilyam8 is there a specific reason to keep directory `collectors/fping.plugin`?

**Comment by ilyam8** [comment]
@thiagoftsm no, where do you see it?

**Comment by ktsaou** [comment]
Do we have a replacement?

**Comment by thiagoftsm** [comment]
> @thiagoftsm no, where do you see it?

Sorry, it was my fault,  `git` kept directory with files when I changed for your branch :man_facepalming:

**Review by thiagoftsm — APPROVED** [review]

**Review by MrZammler — APPROVED** [review]

**Comment by kingUFU** [comment]
With us you will go to the new world of cryptocurrencies
Hacker attack will not be possible with the new program and solution
The blind spots of small reductions in the accounts are removed

**Pull request merged**
