### PR TITLE
added /api/v2/ilove.svg endpoint

### PR DESCRIPTION
**Pull request by ktsaou**
This endpoint generates SVG images "I love X". Like `/api/v2/ilove.svg?love=TROUBLE`

### CODE REVIEW

**Comment by ilyam8** [comment]
@ktsaou ci fails with

```bash
  configure.ac:1954: error: required file 'web/api/ilove/Makefile.in' not found
  autoreconf: automake failed with exit status: 1
```

**Comment by stelfrag** [comment]
The descenders of the letters e.g. jpyp  are slightly truncated at the bottom

**Comment by ktsaou** [comment]
ok, try again. It is now a bit smarter about second line font size, position, spacing and stretching

**Comment by ktsaou** [comment]
There is a white border, that you can't see by default, like this:

image

Most likely, these will be used with tiny dimensions, so we want them readabale. This is why the message needs to be prominent.

**Comment by ktsaou** [comment]
image
image
image
image
image
image

**Comment by andrewm4894** [comment]
adding zip with some hires images i created just in case ever ends up being handy to link to here

[ilovepng.zip](https://github.com/netdata/netdata/files/12360276/ilovepng.zip)

**Pull request merged**
