### PR TITLE
Revert all recent ml changes

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

Reverts the following, recent ML changes:

- https://github.com/netdata/netdata/pull/14207
- https://github.com/netdata/netdata/pull/14198

##### Test Plan

Just CI jobs. With these reverts we are effectively on a well-known ML state that's known to work correctly.

### CODE REVIEW

**Comment by vkalintiris** [comment]
Created this PR just in case some problem comes up during local testing.

**Comment by andrewm4894** [comment]
cool - i am just rebuilding all ml demo stuff from master again and will update here with any feedback after testing once they are trained.

**Comment by andrewm4894** [comment]
all looking good so far. 

will do a final check in the morning and we can then i think close this if all looks good.

**Comment by andrewm4894** [comment]
All looks good to me. Have made this custom dashboard to make it easier to see stuff i'm looking at. https://app.netdata.cloud/spaces/ml-demo-space/rooms/all-nodes/dashboards/anomaly-detection-diagnostics

**Comment by andrewm4894** [comment]
i think we good to close this

**Pull request closed without merging**
