### PR TITLE
Update the kernel-collector version to v0.2.0

### LINKED ISSUE #9119: Update kernel-collector to v0.2.0 for eBPF Plugin
This brings fixes for some Debian and RHEL systems where the kernel-collector libraires/programs were not correctly working in `v0.1.0`

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

ssia -- See [v0.2.0](https://github.com/netdata/kernel-collector/releases/tag/v0.2.0) release notes.

- Closes #9119

This PR is bringing the eBPF installation by default on the supported Linux OS.

##### Component Name

- area/packaging

##### Test Plan

On one or more supproted systems...

Using [hub](https://github.com/github/hub):

You do not need to specify more the option `--enable-ebpf` to do the compilation.

```#!sh
$ git checkout <this pr url>
$ ./netdata-installer-sh ...
```
This PR should be tested at least on Debian 10.x, CentOS 7.6 or newer and more one Linux distributions using kernel 5.x. We expect to run in each one of these distributions.

This PR is expected to fail in distributions that do not store correct kernel version in the variables that the kernel uses, for these distributions we will need to update the shared library ( We already did this Debian, CentOS and Ubuntu )

- [] Ensure eBPF works.

##### Additional Information

### CODE REVIEW

**Comment by prologic** [comment]
> Everything worked as expected! :)

But of course 🤣We expected this right!

**Comment by mfundul** [comment]
In CentOS 7.7:
```
[eBPF] failed to create a map: 13 Permission denied
2020-05-25 11:55:13: ebpf.plugin ERROR : MAIN : [EBPF_PROCESS] Cannot load program: /usr/libexec/net
data/plugins.d/pnetdata_ebpf_process.3.10.0.o (errno 13, Permission denied)
```
but it works if it's manually run outside of netdata with `/usr/libexec/netdata/plugins.d/ebpf.plugin`.

In Debian 10 it does not work:
```
2020-05-25 18:57:21: ebpf.plugin INFO  : MAIN : [EBPF PROCESS] does not have a configuration file. It is starting with default options.
2020-05-25 18:57:21: ebpf.plugin INFO  : MAIN : [EBPF_PROCESS] Cannot load library /usr/libexec/netdata/plugins.d/libnetdata_ebpf.so.4.19.0-9-amd64
 for the current kernel.
2020-05-25 18:57:21: ebpf.plugin INFO  : MAIN : [EBPF_PROCESS] Default shared library /usr/libexec/netdata/plugins.d/libnetdata_ebpf.so.5.4.20 loaded with success.
[eBPF]bpf_load_program() err=22
2020-05-25 18:57:21: ebpf.plugin ERROR : MAIN : [EBPF_PROCESS] Cannot load program: /usr/libexec/netdata/plugins.d/pnetdata_ebpf_process.5.4.20.o (errno 22, Invalid argument)
```

**Comment by vlvkobal** [comment]
Ubuntu 18.04.4
```
2020-05-25 16:05:01: netdata INFO  : PLUGINSD[ebpf] : thread created with task id 16377
2020-05-25 16:05:01: netdata INFO  : PLUGINSD[ebpf] : set name of thread 16377 to PLUGINSD[ebpf]
2020-05-25 16:05:01: netdata INFO  : PLUGINSD[ebpf] : connected to '/usr/libexec/netdata/plugins.d/ebpf.plugin' running on pid 16380
2020-05-25 16:05:01:  ERROR : MAIN : [EBPF PROCESS] The current collector cannot run on this kernel. (errno 2, No such file or directory)
2020-05-25 16:05:01: netdata ERROR : PLUGINSD[ebpf] : read failed: end of file
2020-05-25 16:05:01: netdata ERROR : PLUGINSD[ebpf] : '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 16380) disconnected after 0 successful data collections (ENDs).
2020-05-25 16:05:01: netdata ERROR : PLUGINSD[ebpf] : child pid 16380 exited with code 1.
2020-05-25 16:05:01: netdata ERROR : PLUGINSD[ebpf] : '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 16380) exited with error code 1 and haven't collected any data. Disabling it.
2020-05-25 16:05:01: netdata INFO  : PLUGINSD[ebpf] : thread with task id 16377 finished
```

**Comment by mfundul** [comment]
It worked for me in Ubuntu 18.04. Maybe try deleting `/etc/netdata/netdata.conf`?

**Comment by vlvkobal** [comment]
I deleted `netdata.conf`. Nothing has changed.

**Comment by vlvkobal** [comment]
I've tested the eBPF plugin and it works on
- Arch
- Fedora 30
- CentOS 7.61810
- Debian 10

**Comment by mfundul** [comment]
> 
> 
> I've tested the eBPF plugin and it works on
> 
>     * Arch
> 
>     * Fedora 30
> 
>     * CentOS 7.61810
> 
>     * Debian 10

So it doesn't work for me in CentOS 7.7 and Debian 10 which work for you, but it works in Ubuntu 18.04.

However, for you Ubuntu 18.04 does not work.

This is wildly inconsistent behaviour.

**Comment by thiagoftsm** [comment]
> In CentOS 7.7:
> 
> ```
> [eBPF] failed to create a map: 13 Permission denied
> 2020-05-25 11:55:13: ebpf.plugin ERROR : MAIN : [EBPF_PROCESS] Cannot load program: /usr/libexec/net
> data/plugins.d/pnetdata_ebpf_process.3.10.0.o (errno 13, Permission denied)
> ```

> 
> but it works if it's manually run outside of netdata with `/usr/libexec/netdata/plugins.d/ebpf.plugin`.
> 

@mfundul case you stop Netdata after boot and you try to start it again, does it work as expected?
@prologic  and @Ferroin I remember to report that I never could start the ebpf.collector during the boot on CentOS 7.x, I suspect the `systemd` is doing something not expected here.

> In Debian 10 it does not work:
> 
> ```
> 2020-05-25 18:57:21: ebpf.plugin INFO  : MAIN : [EBPF PROCESS] does not have a configuration file. It is starting with default options.
> 2020-05-25 18:57:21: ebpf.plugin INFO  : MAIN : [EBPF_PROCESS] Cannot load library /usr/libexec/netdata/plugins.d/libnetdata_ebpf.so.4.19.0-9-amd64
>  for the current kernel.
> 2020-05-25 18:57:21: ebpf.plugin INFO  : MAIN : [EBPF_PROCESS] Default shared library /usr/libexec/netdata/plugins.d/libnetdata_ebpf.so.5.4.20 loaded with success.
> [eBPF]bpf_load_program() err=22
> 2020-05-25 18:57:21: ebpf.plugin ERROR : MAIN : [EBPF_PROCESS] Cannot load program: /usr/libexec/netdata/plugins.d/pnetdata_ebpf_process.5.4.20.o (errno 22, Invalid argument)
> ```

I had success to start on Debian 10.4, what is the specific Debian 10.x that are you testing? Did you try to start int on command line?

**Comment by thiagoftsm** [comment]
> 2020-05-25 16:05:01: netdata INFO  : PLUGINSD[ebpf] : connected to '/usr/libexec/netdata/plugins.d/ebpf.plugin' running on pid 16380
> 2020-05-25 16:05:01:  ERROR : MAIN : [EBPF PROCESS] The current collector cannot run on this kernel. (errno 2, No such file or directory)

@vlvkobal , please, can you confirm that the filesystems are mounted?

VirtualBox_Ubuntu_25_05_2020_18_24_48

Another doubt, does this error happen when the machine is starting? Or does it happen after the installation?

**Comment by thiagoftsm** [comment]
> This is wildly inconsistent behaviour.

Yes, during the initialization we already know the problem, it has relationship with `systemd`, but after it starts I cannot replicate the problem :/ .
All the reported problems here has relationship with either permission or filesystem not mounted.

**Comment by vlvkobal** [comment]
`tracefs` is not mounted
```
vlad@ubuntu-18-04:~$ mount | grep tracefs
vlad@ubuntu-18-04:~$ mount | grep debugfs
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
```

**Comment by thiagoftsm** [comment]
> `tracefs` is not mounted
> 

This was the motive it failed, please, run the following command and try again:

``` 
mount -t tracefs nodev /sys/kernel/tracing
```

@prologic, @Ferroin  and @cosmix  should `netdata-installer.sh` brings an additional feature to mount automatically the necessary filesystems? Our documentation says that both `tracefs` and `debugfs` must be mounted to ebpf.plugin works.

**Comment by vlvkobal** [comment]
```
vlad@ubuntu-18-04:~$ sudo mount -t tracefs nodev /sys/kernel/tracing
vlad@ubuntu-18-04:~$ mount | grep tracefs
nodev on /sys/kernel/tracing type tracefs (rw,relatime)
vlad@ubuntu-18-04:~$ mount | grep debugfs
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
vlad@ubuntu-18-04:~$ sudo systemctl restart netdata
vlad@ubuntu-18-04:~$ grep -i ebpf /var/log/netdata/error.log
2020-05-25 18:53:39: netdata INFO  : PLUGINSD[ebpf] : thread created with task id 5308
2020-05-25 18:53:39: netdata INFO  : PLUGINSD[ebpf] : set name of thread 5308 to PLUGINSD[ebpf]
2020-05-25 18:53:39: netdata INFO  : PLUGINSD[ebpf] : connected to '/usr/libexec/netdata/plugins.d/ebpf.plugin' running on pid 5312
2020-05-25 18:53:39:  ERROR : MAIN : [EBPF PROCESS] The current collector cannot run on this kernel. (errno 2, No such file or directory)
2020-05-25 18:53:39: netdata ERROR : PLUGINSD[ebpf] : read failed: end of file
2020-05-25 18:53:39: apps.plugin INFO  : MAIN : 2020-05-25 18:53:39: netdata ERROR : PLUGINSD[ebpf] : started on pid 5313'/usr/libexec/netdata/plugins.d/ebp .plugin' (pid 5312) disconnected after 0 successful data collections (ENDs).
2020-05-25 18:53:39: netdata ERROR : PLUGINSD[ebpf] : child pid 5312 exited with code 1.
2020-05-25 18:53:39: netdata ERROR : PLUGINSD[ebpf] : '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 5312) exited with error code 1 and haven't collected any data. Disabling it.
2020-05-25 18:53:39: netdata INFO  : PLUGINSD[ebpf] : thread with task id 5308 finished
```

**Comment by thiagoftsm** [comment]
> ```
> vlad@ubuntu-18-04:~$ sudo mount -t tracefs nodev /sys/kernel/tracing
> vlad@ubuntu-18-04:~$ mount | grep tracefs
> nodev on /sys/kernel/tracing type tracefs (rw,relatime)
> vlad@ubuntu-18-04:~$ mount | grep debugfs
> debugfs on /sys/kernel/debug type debugfs (rw,relatime)
> vlad@ubuntu-18-04:~$ sudo systemctl restart netdata
> vlad@ubuntu-18-04:~$ grep -i ebpf /var/log/netdata/error.log
> 2020-05-25 18:53:39: netdata INFO  : PLUGINSD[ebpf] : thread created with task id 5308
> 2020-05-25 18:53:39: netdata INFO  : PLUGINSD[ebpf] : set name of thread 5308 to PLUGINSD[ebpf]
> 2020-05-25 18:53:39: netdata INFO  : PLUGINSD[ebpf] : connected to '/usr/libexec/netdata/plugins.d/ebpf.plugin' running on pid 5312
> 2020-05-25 18:53:39:  ERROR : MAIN : [EBPF PROCESS] The current collector cannot run on this kernel. (errno 2, No such file or directory)
> 2020-05-25 18:53:39: netdata ERROR : PLUGINSD[ebpf] : read failed: end of file
> 2020-05-25 18:53:39: apps.plugin INFO  : MAIN : 2020-05-25 18:53:39: netdata ERROR : PLUGINSD[ebpf] : started on pid 5313'/usr/libexec/netdata/plugins.d/ebp .plugin' (pid 5312) disconnected after 0 successful data collections (ENDs).
> 2020-05-25 18:53:39: netdata ERROR : PLUGINSD[ebpf] : child pid 5312 exited with code 1.
> 2020-05-25 18:53:39: netdata ERROR : PLUGINSD[ebpf] : '/usr/libexec/netdata/plugins.d/ebpf.plugin' (pid 5312) exited with error code 1 and haven't collected any data. Disabling it.
> 2020-05-25 18:53:39: netdata INFO  : PLUGINSD[ebpf] : thread with task id 5308 finished
> ```

This is only expected when you have a kernel older than 4.11, please, can you run the following commands?

VirtualBox_Ubuntu_25_05_2020_19_34_46

I ran this on Ubuntu 18.04-4 updated.

**Comment by prologic** [comment]
> @prologic, @Ferroin and @cosmix should netdata-installer.sh brings an additional feature to mount automatically the necessary filesystems? Our documentation says that both tracefs and debugfs must be mounted to ebpf.plugin works.

Yes. It should. But I will do this in another PR, not here.

**Comment by prologic** [comment]
#9155 to fix adding mount(s) during installation.

**Comment by vlvkobal** [comment]
> This is only expected when you have a kernel older than 4.11, please, can you run the following commands?

```
vlad@ubuntu-18-04:~$ cat /proc/version_signature
Ubuntu 4.15.0-99.100-generic 4.15.18
vlad@ubuntu-18-04:~$ uname -a
Linux ubuntu-18-04 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vlvkobal** [comment]
> I ran this on Ubuntu 18.04-4 updated.

Should I try to update it or do you want me to leave it untouched for a while?

**Pull request merged**
