### PR TITLE
Cleaning up ACLK - part 1

### PR DESCRIPTION
**Pull request by amoss**
##### Summary
Final cleaning up of the branch before it is merged back into master.
This will happen in two parts:
1. Fix the tooling so that we have valgrind / paho in the test environment, and can identify the leaks.
2. Make all the review comment changes to clean up the code.

##### Component Name
ACLK

### CODE REVIEW

**Comment by amoss** [comment]
First thing on the clean-up list is memory leaks, this is the leak report from valgrind after a test sequence that involved killing / restarting the broker with an agent running in the compose. Both clean kills (shutting down the container) and fast kills were used.
```
==1== HEAP SUMMARY:
==1==     in use at exit: 18,865,202 bytes in 33,499 blocks
==1==   total heap usage: 184,442 allocs, 150,946 frees, 245,323,556 bytes allocated
==1== 
==1== Thread 1:
==1== 368 bytes in 1 blocks are possibly lost in loss record 8,899 of 9,260
==1==    at 0x483BB65: calloc (vg_replace_malloc.c:762)
==1==    by 0x40133E1: allocate_dtv (in /usr/lib/ld-2.31.so)
==1==    by 0x4013D51: _dl_allocate_tls (in /usr/lib/ld-2.31.so)
==1==    by 0x4DC015E: pthread_create@@GLIBC_2.2.5 (in /usr/lib/libpthread-2.31.so)
==1==    by 0x144162: netdata_thread_create (threads.c:184)
==1==    by 0x16AF46: pluginsd_main (plugins_d.c:909)
==1==    by 0x143E0E: thread_start (threads.c:170)
==1==    by 0x4DBF46E: start_thread (in /usr/lib/libpthread-2.31.so)
==1==    by 0x4ED73D2: clone (in /usr/lib/libc-2.31.so)
==1== 
==1== 1,035 (720 direct, 315 indirect) bytes in 9 blocks are definitely lost in loss record 9,075 of 9,260
==1==    at 0x483977F: malloc (vg_replace_malloc.c:309)
==1==    by 0x4B7A59A: CRYPTO_zalloc (in /usr/lib/libcrypto.so.1.1)
==1==    by 0x4BE8FE0: UI_create_method (in /usr/lib/libcrypto.so.1.1)
==1==    by 0x1F46D3: setup_ui_method (net_mosq.c:100)
==1==    by 0x1F46D3: net__init (net_mosq.c:147)
==1==    by 0x1F0357: mosquitto_lib_init (mosquitto.c:68)
==1==    by 0x19D546: _mqtt_lib_init (mqtt.c:170)
==1==    by 0x19D9AB: _link_lib_init (mqtt.c:293)
==1==    by 0x19B5C8: aclk_try_to_connect (agent_cloud_link.c:1140)
==1==    by 0x19B8C7: aclk_main (agent_cloud_link.c:995)
==1==    by 0x143E0E: thread_start (threads.c:170)
==1==    by 0x4DBF46E: start_thread (in /usr/lib/libpthread-2.31.so)
==1==    by 0x4ED73D2: clone (in /usr/lib/libc-2.31.so)
==1== 
==1== 8,917 (8,856 direct, 61 indirect) bytes in 9 blocks are definitely lost in loss record 9,231 of 9,260
==1==    at 0x483BB65: calloc (vg_replace_malloc.c:762)
==1==    by 0x1F3593: mosquitto__calloc (memory_mosq.c:55)
==1==    by 0x1F0A53: mosquitto_new (mosquitto.c:100)
==1==    by 0x19D564: _mqtt_lib_init (mqtt.c:176)
==1==    by 0x19D9AB: _link_lib_init (mqtt.c:293)
==1==    by 0x19B5C8: aclk_try_to_connect (agent_cloud_link.c:1140)
==1==    by 0x19B8C7: aclk_main (agent_cloud_link.c:995)
==1==    by 0x143E0E: thread_start (threads.c:170)
==1==    by 0x4DBF46E: start_thread (in /usr/lib/libpthread-2.31.so)
==1==    by 0x4ED73D2: clone (in /usr/lib/libc-2.31.so)
==1== 
==1== LEAK SUMMARY:
==1==    definitely lost: 9,576 bytes in 18 blocks
==1==    indirectly lost: 376 bytes in 20 blocks
==1==      possibly lost: 368 bytes in 1 blocks
==1==    still reachable: 18,854,882 bytes in 33,460 blocks
==1==         suppressed: 0 bytes in 0 blocks
```

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 29
           

Complexity increasing per file
==============================
- build_external/projects/aclk-testing/paho-inspection.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5053498&bid=16636582)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 25
           

Complexity increasing per file
==============================
- build_external/projects/aclk-testing/paho-inspection.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5053498&bid=16636582)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 25
           

Complexity increasing per file
==============================
- build_external/projects/aclk-testing/paho-inspection.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5053498&bid=16636582)

**Comment by amoss** [comment]
Change of plan - I've split the cleaning up into two parts. This part is easy to review as it does not affect the netdata code. This means that we can review / merge it quickly and then merge the branch. This will allow @underhood to complete the proxy support before the code changes too much. Second part will be a PR against master after the proxy support is merged.

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- build_external/projects/aclk-testing/paho-inspection.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5053498&bid=16636582)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- build_external/projects/aclk-testing/paho-inspection.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5053498&bid=16636582)

**Comment by underhood** [comment]
I have to change in `configureVerneMQ.Dockerfile`
line 1 from `FROM vernemq:latest`
to `vernemq/vernemq:latest`

otherwise it fails at pulling vernemq image

**Pull request merged**
