### PR TITLE
Introduced IEC-compliant unit abbreviations #4711

### PR DESCRIPTION
**Pull request by gmosx**
This PR introduced additional, IEC-compliant unit-conversions to dashboard.js

### CODE REVIEW

**Comment by ktsaou** [comment]
I think this is not right.
We should not change `1024` to `1000`.
We should only change `KB` to `KiB`, `MB` to `MiB`, `GB` to `GiB`, etc.

But for this to work, we also have to change how data collection plugins report metrics to netdata. @gmosx 	this has do be done by @ilyam8 	and @vlvkobal 	.

**Comment by cakrit** [comment]
I'll set up a call to discuss what needs to be done.

**Comment by gmosx** [comment]
@cakrit I reverted the coefficients for the older abbreviations, can you check pls?

**Comment by ktsaou** [comment]
If this is not WIP, remove it from the title to merge it.

**Pull request merged**
