### PR TITLE
add autogenerated changelog

### PR DESCRIPTION
**Pull request by paulfantom**
##### Summary

Create changelog based on GitHub labels

##### Component Name

GitHub management

##### Additional Information

Moving old manually created changelog to HISTORICAL_CHANGELOG.md and using command below to create changelog based on github issues, PRs, and labels. This is a preview and in the near future this will be automated and running daily in cron.

```sh
docker run -it -v "$(pwd)":/project markmandel/github-changelog-generator:latest \
     --user "netdata" \
     --project "netdata" \
     --token "${GITHUB_TOKEN}" \
     --since-tag "v1.10.0" \
     --unreleased-label "**Next release**" \
     --no-compare-link \
     --exclude-labels duplicate,question,invalid,wontfix,discussion,documentation
```

### CODE REVIEW

**Comment by paulfantom** [comment]
@Ferroin @l2isbad @ktsaou I think we were talking about this on slack a couple of weeks ago. Here is the updated version which doesn't have a bug causing generation of changelog from the beginning of a netdata project. I relabeled all issues from v1.10.0 to now so they can be easily identified and classified by a generator.

Do we want this to be included in a project instead of writing CHANGELOG.md manually?

**Comment by l2isbad** [comment]
> now so they can be easily identified and classified by a generator
> instead of writing CHANGELOG.md manually

> Do we want this?

Hmm.. :smile:

**Comment by paulfantom** [comment]
Granting ownership of CHANGELOG.md file to @netdatabot

**Comment by Ferroin** [comment]
Having it autogenerated is nice, but we do have to make a point to ensure that everything is properly tagged before it gets merged.

**Comment by paulfantom** [comment]
> everything is properly tagged 

You mean?

This changelog have 3 categories:
- Bug - if a closed **issue** was tagged as bug)
- Issue - every issue which wasn't labelled as `bug`, `duplicate`, `wontfix`, `discussion` or `documentation`)
- Merged Pull Request - Every merged pull request.

There is not much to check and I already went through all issues from v1.10.0 to relabel them.

In the future we just need to ensure to label our issues correctly as they are coming and make PR titles relevant (everyone with write access can change any PR title).

> before it gets merged

Generator doesn't care about a state in which PR was merged. It only cares about a state at which PR is at a time of running generator. This means that changelog can be automatically fixed even after merging a PR. Also due to github rate limiter we cannot run generator after every PR.


---

Also we can remove "Merged Pull Request" section if we want, but this would need more discipline and first creating issues for PRs. Which from project management point of view is a good practice as it shows what are our goals and who is working on what.

**Comment by ktsaou** [comment]
it gives conflicts

**Comment by ktsaou** [comment]
btw, lets try this. It may be good.

**Comment by paulfantom** [comment]
solved conflicts

**Pull request merged**
