### PR TITLE
update postgres dashboard info

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

This PR adds go [Postgres collector](https://github.com/netdata/go.d.plugin/tree/master/modules/postgres#postgresql-monitoring-with-netdata) charts description.

##### Test Plan

Install updated dashboard_info.js, and check the dashboard.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by sashwathn — COMMENTED** [review]
Should be add a new line while describing each dimension?

**Review by sashwathn — APPROVED** [review]
A generic feedback will be to consider adding a new line for every dimension we are describing.

**Comment by ilyam8** [comment]
> Should be add a new line while describing each dimension?

We can end up with the text consuming more space than the charts - also, showing info text can't be disabled via UI. The current pattern (I don't say that this is the best way) is to have 2 paragraphs - the chart description + dimensions.

Screenshot 2022-08-02 at 14 20 45

You can try different approaches and see how it looks.

**Review by thiagoftsm — APPROVED** [review]

**Review by vlvkobal — APPROVED** [review]

**Comment by ilyam8** [comment]
@thiagoftsm please review one more time

**Review by thiagoftsm — APPROVED** [review]

**Pull request merged**
