### PR TITLE
Add support for nonredundant arrays

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
* The `mdstat` module indicates when a nonredundant array disappears from the list of active arrays.
* Charts become obsolete when an array disappears.
* Add configuration options.

Implements #4010

##### Component Name
`proc` plugin

##### Additional Information
There is no possibility to distinguish a disk failure from an intentional shutdown. So, the chart will show a disruption on any of these events.

### CODE REVIEW

**Comment by paulfantom** [comment]
Strange, I wonder why `Travis CI - Branch` check is here. Was this previously on some branch inside netdata repository and moved later to external repo?

**Comment by vlvkobal** [comment]
> Strange, I wonder why Travis CI - Branch check is here. Was this previously on some branch inside netdata repository and moved later to external repo?

Yes. My fault. I accidentally pushed this branch to upstream and then removed it. What should I do to mend this check?

**Comment by paulfantom** [comment]
Just ignore it :)

**Comment by cakrit** [comment]
md looks ok.

**Pull request merged**
