### PR TITLE
Zscores collector

### PR DESCRIPTION
**Pull request by andrewm4894**
##### Summary

Python based collector that generates zscores for specified charts.

##### Component Name

collectors/python.d.plugin/zscores/

##### Additional Information

More detailed information in README.md of the collector.

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/zscores/zscores.chart.py  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6319023&bid=20542051)

**Comment by andrewm4894** [comment]
Marking this to draft as i need to clean it up a bit more and clean up the commits etc too.

**Comment by ilyam8** [comment]
@andrewm4894 closing this in favor of #10673?

**Comment by andrewm4894** [comment]
yep - sorry - closing this in favor of #10673

**Comment by andrewm4894** [comment]
lol this one was a mess of a PR by me :)

**Pull request closed without merging**
