### PR TITLE
Agent dashboard reorganization.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This PR includes preliminary work to support the new unified local dashboard UI based on the Cloud UI.

##### Test Plan

Build and install from this PR, and confirm that the dashboard works correctly.

##### Additional Information

TODO:

- [x] Add `v0/` path for legacy dashboard.
- [x] Move single node dashboard to `v1/` prefix.
- [x] Add new `index.html` to redirect to `v1/index.html` in the short term.
- [x] Update single node dashboard to support running from a directory (needs changes in https://github.com/netdata/dashboard).
- [x] Add new `v2/` path for new Cloud UI dashboard (needs coordination with @netdata/cloud-fe to get compiled files needed for this).
- [x] Add infrastructure for `switch.html` file to handle selection of which dashboard to load.

### CODE REVIEW

**Comment by ktsaou** [comment]
These are the Makefile.am changes to install v1 under directory `v1/`:

```
webv1dir=$(webdir)/v1
dist_webv1_DATA = \
    $(srcdir)/dashboard-react.js \
    $(srcdir)/index.html \
    $(NULL)

webv1staticcssdir=$(webdir)/v1/static/css
dist_webv1staticcss_DATA=$(dist_webstaticcss_DATA)

webv1staticjsdir=$(webdir)/v1/static/js
dist_webv1staticjs_DATA=$(dist_webstaticjs_DATA)

webv1staticmediadir=$(webdir)/v1/static/media
dist_webv1staticmedia_DATA=$(dist_webstaticmedia_DATA)
```

**Comment by ktsaou** [comment]
This version does not work.

Problems:

## `v0` and `old`

It fails because most of its files are inside the `v1` directory. They should be at `/`.

## `v1`

Only `index.html` from `v1` should be inside `v1` directory. All the other files and directories need to be outside, like they were. These files serve several purposes and shouldn't be moved.

## `v2`

It works.

## `index.html`

The new `/index.html` should be called `/v2live.html`. Do not install it yet as `index.html`.
The `/v1/index.html` should be copied as `/index.html`.

**Comment by ktsaou** [comment]
@Ferroin wait. I will work with @novykh tomorrow to clean this mess. Some files belong to v0, some to v1, some need to be at the root. I will come up with better instructions.

**Comment by ktsaou** [comment]
@Ferroin I discussed with @novykh about it.

For the moment we need ONLY a NEW `/v2` directory with everything about the new dashboard in it. Do not change anything else. Just add this directory.

Can you update this PR to do this today?

**Comment by Ferroin** [comment]
Rebased to clean up commit history.

Also updated to address changes requested by @ktsaou.

**Review by ktsaou — DISMISSED** [review]
it works as expected

**Comment by Ferroin** [comment]
Rebased to pull in latest v2 dashboard code.

**Review by stelfrag — APPROVED** [review]

**Pull request merged**
