### PR TITLE
Update codeowners and cleanup .gitignore

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

SSIA.

##### Test Plan

- CI jobs

### CODE REVIEW

**Comment by ilyam8** [comment]
@vkalintiris please add labeler config changes from #16946

**Comment by thiagoftsm** [comment]
Hello @vkalintiris ,

After to compile this PR, I have the following output when I run `git status`:

```sh
bash-5.2$ git status
On branch pr16946
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Makefile
        aclocal.m4
        autom4te.cache/
        claim/
        collectors/Makefile
        collectors/apps.plugin/Makefile
        collectors/cgroups.plugin/Makefile
        collectors/charts.d.plugin/Makefile
        collectors/cups.plugin/Makefile
        collectors/debugfs.plugin/Makefile
        collectors/diskspace.plugin/Makefile
        collectors/ebpf.plugin/Makefile
        collectors/freebsd.plugin/Makefile
        collectors/freeipmi.plugin/Makefile
        collectors/idlejitter.plugin/Makefile
        collectors/ioping.plugin/Makefile
        collectors/log2journal/Makefile
        collectors/macos.plugin/Makefile
        collectors/nfacct.plugin/Makefile
        collectors/perf.plugin/Makefile
        collectors/plugins.d/Makefile
        collectors/proc.plugin/Makefile
        collectors/python.d.plugin/Makefile
        collectors/slabinfo.plugin/Makefile
        collectors/statsd.plugin/Makefile
        collectors/systemd-journal.plugin/Makefile
        collectors/tc.plugin/Makefile
        collectors/timex.plugin/Makefile
        collectors/xenstat.plugin/Makefile
        compile
        config.guess
        config.h
        config.status
        config.sub
        configure
        daemon/
        database/
        depcomp
        diagrams/Makefile
        exporting/
        health/Makefile
        health/notifications/Makefile
        install-sh
        libnetdata/
        logsmanagement/
        missing
        registry/
        spawn/
        stamp-h1
        streaming/
        system/Makefile
        tests/Makefile
        tests/bugs_example/
        web/Makefile
        web/api/Makefile
        web/api/badges/Makefile
        web/api/exporters/Makefile
        web/api/exporters/prometheus/Makefile
        web/api/exporters/shell/Makefile
        web/api/formatters/Makefile
        web/api/formatters/csv/Makefile
        web/api/formatters/json/Makefile
        web/api/formatters/ssv/Makefile
        web/api/formatters/value/Makefile
        web/api/health/Makefile
        web/api/ilove/Makefile
        web/api/queries/Makefile
        web/api/queries/average/Makefile
        web/api/queries/countif/Makefile
        web/api/queries/des/Makefile
        web/api/queries/incremental_sum/Makefile
        web/api/queries/max/Makefile
        web/api/queries/median/Makefile
        web/api/queries/min/Makefile
        web/api/queries/percentile/Makefile
        web/api/queries/ses/Makefile
        web/api/queries/stddev/Makefile
        web/api/queries/sum/Makefile
        web/api/queries/trimmed_mean/Makefile
        web/gui/Makefile
        web/gui/dashboard/
        web/gui/v1/Makefile
        web/gui/v2/Makefile
        web/rtc/Makefile
        web/server/Makefile
        web/server/static/Makefile

nothing added to commit but untracked files present (use "git add" to track)
```

I suppose some of these files should not be in this list.

Best regards!

**Comment by ilyam8** [comment]
@thiagoftsm keep your repo up to date and clean.

**Comment by ilyam8** [comment]
@vkalintiris I think there are more leftovers in .gitignore, for instance:

 - all `system/` entries.
 - all `health/`, `claim/` and `collectors/` entries.

There is more!

**Review by ilyam8 — APPROVED** [review]

**Comment by thiagoftsm** [comment]
> @thiagoftsm keep your fork up to date and clean.

`hub` was not doing what I expected. :/

**Pull request merged**
