### PR TITLE
Prevent legend highlighting

### PR DESCRIPTION
**Pull request by jacekkolasa**
### Summary
Prevent highlighting of legend, when shift+clicking

##### Component Name
dashboard.js

### CODE REVIEW

**Comment by jacekkolasa** [comment]
@cakrit i've done it because the highlighting doesn't look good when you toggle dimensions with shift/ctrl. But on second thought, I think that the css fix haven't been done previously because now the user cannot select the dimension name to copy it to clipboard. Do you agree that we shouldn't block selecting when user wants to copy the name?

I can fix this problem in other way - by clearing the selection when user shift+clicks the legend. This has one drawback though - the selection is visible for part of the second. I'll push the commit with that other solution

**Comment by cakrit** [comment]
Wow, I didn't even know it was a thing. Now that I saw what you're talking about:
- Clicking on the first dimension while holding Shift and then clicking on the 4th dimension should select dimensions 1,2,3,4. 
- Clicking on the first dimension while holding Ctrl and then clicking on the 4th dimension should select dimensions 1,4.
 
Without this change, the first case does two wrong things:
 - Selects 1,4 instead of 1-4
 - Highlights the legend

I don't get why Shift and Click highlights things on any page and I'm not sure what's the ideal solution here, but I get why you did what you did and IMHO it's better than what we have today. Perhaps our UX gents (@ivorjvr @oyabun ) have some ideas

**Comment by jacekkolasa** [comment]
Right now (in current UX) there is no difference between shift and ctrl. Moreover, on MacOS only shift+clicking works. Maybe if you use Ctrl on Windows/Linux, user doesn't see the weird highlighting of text.

Of course by "Selecting" I was only meaning highlighting of text, browser native behaviour.

In the future (i recommend after dashboard refractor) we can Toggle range of dimensions via shift+click and fix Ctrl+click for macOS. That should be easy change

**Comment by cakrit** [comment]
Ok, cancel this PR then, put the LGTM fixes on another PR and discuss with the UX guys what we could/should do in the future. You can tell I'm not a MacOS user :)

**Pull request closed without merging**
