### PR TITLE
Honor disabling of features: aclk cloud ml https

### LINKED ISSUE #11930: [regression] netdata fails to build without any aclk feature
##### Bug report summary

When building lightweigth version with `./configure --without-aclk-legacy --without-aclk-ng --disable-cloud` configure suceeds but make fails.

##### OS / Environment

``
Linux Fedora 32 or CentOS 8
from git/master
```

##### Netdata version
1.32.1 / master

##### Installation method
From git sources

##### Component Name
aclk

##### Steps To Reproduce
Trying to build a static, lightweight netdata agent.

1. Run configure as `./configure  --without-aclk-legacy --without-aclk-ng  --disable-cloud`
2. (full configure is `--with-zlib --with-math --with-bundled-lws --with-bundled-libJudy --without-aclk-legacy --without-aclk-ng --enable-dbengine --enable-lto --disable-cloud --disable-https --disable-ml --disable-ebpf --disable-backend-kinesis --disable-backend-prometheus-remote-write --disable-backend-mongodb --enable-plugin-freeipmi --disable-plugin-nfacct --disable-plugin-xenstat --disable-plugin-cups ` )
3. Run `make`  (or `cmake . && make`) 
 

##### Expected behavior

Build should succeed without ACLK nor Cloud, like in 1.31.

Checking the source code, in 1.31 many features were disabled using `--disable-cloud --without-aclk`, but now many parts of the sourc ecode refers to ACLK nonetheless.
ACLK requires many libs, like openssl, mosquitto or lws.

I guess decisions were made to resume the release of netdata agent, focusing on cloud features, but now I would need to be able to build netdata without them, like before.

### PR DESCRIPTION
**Pull request by Saruspete**
Disable parts of code that should not have been compiled when they are explicitly disabled in configure step.
This is a requirement for building a lightweight binary, without unneeded librairies that would also need external security review.  

Currently, most aclk & cloud code are compiled but disabled at runtime. This still requires external libraries like mqtt, openssl, or alike.

Also includes a basis for CMakeLists.txt to parse the `config.h` file, and maybe enable its generation to completely remove autotools in the future. 

Fixes #11930 

##### Component Name
- Build (makefile & cmake)
- aclk
- daemon
- api_v1
- database
- claim

##### Test Plan

- Build as usual must not be impacted by these changes
- Create new CI target where many components are disabled, especially all ACLK, Cloud, HTTPS, externaldeps:
`--without-aclk-legacy --without-aclk-ng --enable-dbengine --enable-lto --disable-cloud --disable-https --disable-ml --disable-ebpf --disable-backend-kinesis --disable-backend-prometheus-remote-write --disable-backend-mongodb --disable-plugin-nfacct --disable-plugin-xenstat --disable-plugin-cups`

##### Additional Information

More code could be disabled in `daemon/main.c` when `--disable-cloud` is set to avoid messages regarding missing cloud.conf file.

### CODE REVIEW

**Comment by Saruspete** [comment]
Seems `sqlite_functions.c :: compute_chart_hash()`  is using EVP functions from openssl, regardless of HTTPS enabled or not. We could use implementation from https://github.com/B-Con/crypto-algorithms/blob/master/sha256.c which seems to be released in public domain, explicitly without any restriction.

**Comment by vkalintiris** [comment]
> Disable parts of code that should not have been compiled when they are explicitly disabled in configure step.

When you build with `--disable-ml` there's no ML-related code included in the final binary. The `ml_*()` calls are dummy functions that were originally added in order to avoid the excessive number of preprocessor `#ifdef`s that hurt the readability of the code.

**Comment by stelfrag** [comment]
> Seems `sqlite_functions.c :: compute_chart_hash()` is using EVP functions from openssl, regardless of HTTPS enabled or not. We could use implementation from https://github.com/B-Con/crypto-algorithms/blob/master/sha256.c which seems to be released in public domain, explicitly without any restriction.

Passing `--disable-cloud` can safely disable that part of the code

**Comment by ilyam8** [comment]
@Saruspete @stelfrag is this PR still relevant?

**Comment by Saruspete** [comment]
I cloned the latest master, and try to build it without https, but it still needs openssl.
My final goal is to make a portable binary that would work on any OS, without any packege to be installed. One might say to just use the static build, but it's not a good way: it's too tightly bound to modules libnss version.

So I can either:
- Remove all unnecessary components in my use-case. Among them the most changing among dists is openssl.
- Make a semi-static build, where most libraries are static, but libc, libpthread, libdl, libm are dynamic.

The semi-static way would be my preferred, and it would require less changes from the "packaging" section, but the buildchain is a real mess, using files here and there, and needing docker. 

So i'm kinda lost here...

**Comment by thiagoftsm** [comment]
Hello @Saruspete ,

Openssl is also hard dependency for our `dbengine'. We can work to bring support for other TLS libraries, but to remove would be a little bit complicated.  We have options to disable `dbengine` and `https` during compilation time.

Best regards!

**Pull request closed without merging**
