### PR TITLE
dashboard v2.9.2

### LINKED ISSUE #250: date & time range filter ?
Probably related to https://github.com/firehol/netdata/issues/222 but a date and time range filter in dashboard would be nice. So we can narrow in on a specific time range rather than mouse drag back and forth :)

### LINKED ISSUE #8952: New dashboard is missing info about extending history retention
The dashboard doesn't show the dbengine info when we move the chart past the beginning of collection: 
```
Want to extend your history of real-time metrics?
Configure Netdata's history or use the DB engine
```
@dim08 can we re-validate this text and the links therein, ensure they still point to the correct place?
@jacekkolasa can we please show the text in the new dashboard?

### LINKED ISSUE #9286: Is it still intended to be able to resize chart height using touch iOS iPad?
##### Question summary
Not sure if it's just me, can anyone with an iPad or a touch enabled device please confirm whether it's still possible to resize the height of individual charts on the Netdata Dashboard? It stopped working for me around when the new UI was released with the left-side panel.

##### OS / Environment
iOS 13.4.1 Safari and Chrome browsers.
CentOS 7 Virtuozzo Cloud VPS

##### Component Name
Web dashboard

##### Expected results

Ability to drag to resize the height of charts on Netdata Dashboard.

### PR DESCRIPTION
**Pull request by jacekkolasa**
##### Summary
Dashboard v2.9.2 - https://github.com/netdata/dashboard/releases/tag/v2.9.2

Fix/resize chart height on touch
netdata/dashboard#167

Proceeded chart disclaimer
netdata/dashboard#168

Fix/update gauges and pie chart colors based on theme
netdata/dashboard#171

Date-picker
netdata/dashboard#177

align-legend
netdata/dashboard#180

---

Fixes #9286
Fixes #8952
Fixes #250

### CODE REVIEW

**Comment by ilyam8** [comment]
minor ux issue on white theme at least for me, this _green_ color dimensions are hard to read (could be color + decreased font size combination issue).

Screenshot 2020-11-16 at 18 24 47

Before this PR

Screenshot 2020-11-16 at 18 27 39


---

Other then that everything looks ok.

**Review by thiagoftsm — DISMISSED** [review]
Probably we could have an option for the users to select the colors. I tend to agree with @ilyam8 that this can be strange for some users, but except for this concern, everything looked fine on Firefox .

**Comment by stelfrag** [comment]
- Open the date picker
- With the date picker open I tried to resize the window to the right (or left)
- The calendar started drifting to the left !


image

Similar with the following
- Open the date picker
- Enter / leave full screen
- Calendar starts drifting to the left

**Comment by stelfrag** [comment]
I just noticed it happens in production / staging as well

**Comment by jacekkolasa** [comment]
I've added an update to revert back to old colours. We'll make more adjustments to it so let's keep the old colours for now.
@stelfrag thanks for that, i'm not sure if that's a blocker for merge or not. I'll look into it tomorrow morning. We are actually using 3rd party date-picker in a little hacky way, so i don't know how difficult the fix will be

**Review by ilyam8 — APPROVED** [review]

**Review by thiagoftsm — DISMISSED** [review]

**Comment by jacekkolasa** [comment]
@stelfrag the issue with calendar has been fixed here and it will be soon in the cloud, can you please check again? cc @thiagoftsm @ilyam8

**Comment by jacekkolasa** [comment]
> I second @ilyam8’s comment about the green being hard to read on the white theme. I think we need to look at having the chart/line colors be defined per-theme and adjust them to have good contrast (the green-on-white case is pprobably the worst-case right now, but some of the other combinations are sub-part as well).

@Ferroin chart colours are actually different per theme, but of course we will double-check if it can be improved. @AndyWindy actually suggested that we could also have slightly different colours for negative/positive values to differentiate them better, but i don't know if this is easy to do tech-wise.

**Review by VLegakis — APPROVED** [review]

**Review by ilyam8 — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
@jacekkolasa the problem with datepicker was fixed on Firefox.

**Comment by Ferroin** [comment]
Force merged by request of @jacekkolasa due to stuck WIP check.

**Pull request merged**
