### PR TITLE
Add the packaging metadata to build the netdata snap

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
To test this in ubuntu 16.04:

    $ sudo apt install snapcraft git
    $ git clone https://github.com/elopio/netdata
    $ cd netdata
    $ git checkout snapcraft
    $ snapcraft
    $ sudo snap install --dangerous --classic
    $ netdata

Note that there is a big bug here because the path of the build machine gets hardcoded into the snap, so it can only be run in this machine and won't work if installed from the ubuntu store. I'm making this PR as suggested by @ktsaou to see if we can find a good solution.

**Comment by ktsaou** [comment]
thanks!

Regarding the bug: when a snap is installed from the ubuntu store, how it can find its path? At which point the path is known and how?

**Comment by elopio** [comment]
Most projects use [xdg](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), so the paths are not absolute, they are relative to $HOME, which will just work in the snap. When a project doesn't follow xdg, it usually has a flag to specify the data dir. 

When snaps are run they have a set of environment variables that point to the right location for them to store files. You will see in this PR that I'm trying to use the config from $SNAP_USER_DATA/etc/netdata/netdata.conf, but that doesn't work because of the `--install`.

There are many ways to fix it. One way would be to add one option to netdata-installer.sh so we can split installation dir from data dir, and call it something like:

    ./netdata-installer.sh --dont-wait --dont-start-it --install $SNAPCRAFT_PART_INSTALL --data $SNAP_USER_DATA

This `$SNAP_USER_DATA` would have to be expanded only on runtime, and it will point to the right place in the user's home.

Another option would be for netdata to search for the files in `$XDG_DATA_HOME` or `$XDG_CONFIG_HOME`.

'm not really sure if this answers your question.

**Comment by ktsaou** [comment]
ok. The $HOME idea is very nice.

I also need some persistent storage. Something that will remain in the target system and will not be moved with the snap. I use this for 2 simple text files: a machine unique id and the alarms log.

Does snap support this?

**Comment by elopio** [comment]
If it's machine specific, you can put it in $SNAP_COMMON. If it's user specific, you can put it in $SNAP_USER_COMMON. Here you can find more details about the variables: https://snapcraft.io/docs/reference/env I think that fits your use case, but also remember that we are on active development. If you need something that snaps don't yet provide, we'll put it in our backlog.

**Comment by ktsaou** [comment]
ok. I have 3 options:

1. hardcode xdg or whatever in netdata - I don't like it since settings suitable for you, may break something else and forcing xdg in all cases might be too complex.

2. support environment variable look ups for paths - a bit complex to do, to support it properly.

3. provide command line parameters to set all the directories, when starting netdata, so the wrapper script will be able to do whatever it likes.

Will option 3 be good for you?

**Comment by elopio** [comment]
Yes, number 3 sounds like a viable option.


-- 
Enviado con Dekko desde mi dispositivo Ubuntu

**Comment by ktsaou** [comment]
ok, this is what I did:

You can use command line parameters to overwrite any of `netdata.conf` settings.

The `netdata.conf` options that might be of interest for this are:

```
[global]
	config directory = /etc/netdata
	log directory = /var/log/netdata
	plugins directory = /usr/libexec/netdata/plugins.d
	web files directory = /usr/share/netdata/web
	cache directory = /var/cache/netdata
	lib directory = /var/lib/netdata
	home directory = /var/cache/netdata
	host access prefix = 
	run as user = netdata

[web]
	# web files owner = netdata
	# web files group = netdata
	# default port = 19999
	# bind to = *

[plugins]
	PATH environment variable = < by default same as $PATH >
	PYTHONPATH environment variable = < by default empty >
```

In detail:

#### config directory

the directory where all user configuration files should be. The default is determined at compile time.

#### log directory

the directory where netdata will save its log files. The default is determined at compile time.

#### plugins directory

the directory where all netdata plugins are. The default is determined at compile time.

#### web files directory

the directory where all static web files are. The default is determined at compile time.

#### cache directory

the directory where all chart data will be saved to. This is only used when `memory more` is `ram` or `map`. The default is determined at compile time.

I don't know if this should be persistent. If we decide that one one netdata should be running at a host at any given time, these could be persistent.

#### lib directory

the directory where a few key files about of the operation are kept. **This should be persistent**. The default is determined at compile time.

#### home directory

the directory netdata will be while running. It is not used for anything currently. The default is determined at compile time.

#### host access prefix

This is used when running in containers, to access the host's `/proc` or `/sys`. Since the snap will be `--dangerous --classic` we don't need it.


#### run as user

The user to run as.

If netdata is started as root, it will try to switch to this user.
If netdata is not started as root, this is internally set to the user netdata runs as.

#### web files owner and web files group

netdata checks the ownership of the files it serves. If their ownership does match the above, it refuses to serve them.

The default is to use `run as user` for both.

---

the others I think are self-explanatory.

---

## how to set them on the command line

```
/path/to/netdata -W set section "option" "value"
```

You can add this, any number of times.

So, something like:

```
/path/to/netdata \
    -W set global "config directory" "/snap/X/etc" \
    -W set global "log directory" "/snap/X/log" \
    -W set global "plugins directory" "/snap/X/plugins" \
    -W set global "cache directory" "/snap/X/data" \
    -W set global "lib directory" "/path/to/persistent/storage" \
    -W set global "home directory" "/tmp" \
    -W set web "web files owner" "user" \
    -W set web "web files group" "group"
```

netdata also supports the option `-c` that sets the full path to `netdata.conf`. To position of `-c` in the command line is important:

1. If you place `-c /path/to/netdata.conf`, before the all `-W set ...` parameters, the user may use `netdata.conf` to overwrite your command line parameters.
2. If you place it after all `-W set ...` parameters, the user will not be able to overwrite them.

Will these do?

**Comment by NatoBoram** [comment]
Any news on this?

**Comment by cakrit** [comment]
@paulkatsoulakis  can you please review this? It's been around forever.

**Comment by cakrit** [comment]
Closing due to CLA not signed and @paulkatsoulakis' request to move to a different directory not addressed. Please comment if you intend to do another commit and we'll reopen it.

**Pull request closed without merging**
