### PR TITLE
/collectors/python.d.plugin/third_party: patch monotonic synology6

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

Fixes: #7976

`python.d.plugin` doesnt work on synology systems, this patch fixes it (py2).

##### Component Name

[/collectors/python.d.plugin](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/python_modules/third_party)

##### Additional Information

@BH1NBN could you test it?

- `wget https://raw.githubusercontent.com/ilyam8/netdata/monotonic_synology/collectors/python.d.plugin/python_modules/third_party/monotonic.py`
- replace old `monotonic.py` with new one in python.d.plugin thirtd_party dir
- restart netdata

___

Tested by @BH1NBN in https://github.com/netdata/netdata/pull/7980#issuecomment-582281992

### CODE REVIEW

**Comment by BH1NBN** [comment]
> ##### 摘要
> 修复：[＃7976](https://github.com/netdata/netdata/issues/7976)
> 
> `python.d.plugin` 在synology系统上不起作用，此修补程序对其进行了修复（py2）。
> 
> ##### 组件名称
> [/collectors/python.d.plugin](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/python_modules/third_party)
> 
> ##### 附加信息
> @ BH1NBN您可以测试吗？
> 
> * `wget https://raw.githubusercontent.com/ilyam8/netdata/monotonic_synology/collectors/python.d.plugin/python_modules/third_party/monotonic.py`
> * `monotonic.py`在python.d.plugin thirtd_party目录中用新的替换旧的
> * 重新启动netdata

ok But later

**Comment by ilyam8** [comment]
@BH1NBN that is was the fastest answer i have got so far 😄

**Comment by BH1NBN** [comment]
Everything works

QQ截图20200205154551


> @BH1NBN that is was the fastest answer i have got so far

**Comment by ilyam8** [comment]
@BH1NBN a tip for the future - don't post screenshots, copy paste text from the screen and post it using code block syntax😉 

~~~~
```
Put Your Text Between!
```
~~~~

result

```
Put Your Text Between!
```

**Comment by BH1NBN** [comment]
> @ BH1NBN未来的秘诀-不要发布屏幕截图，不要从屏幕上复制粘贴文本并使用代码块语法发布它
> 
> ```
> ```
> Put Your Text Between!
> ```
> ```
> 
> 结果
> 
> ```
> Put Your Text Between!
> ```

ok

**Pull request merged**
