### PR TITLE
Added Docker build tests to PR checks.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This adds PR checks to verify that Docker builds work correctly when PR's change the packaging code. It verifies all four architectures that we currently build Docker images for.

These checks only run on PR's which either modify the workflow itself, or alter the packaging or installer code.

##### Component Name

area/ci
area/packaging

##### Description of testing that the developer performed

Verified that the checks run and pass correctly on my personal fork.

##### Additional Information

This is part of an ongoing conversion from Travis CI to GitHub Actions for CI/CD.

### CODE REVIEW

**Comment by Ferroin** [comment]
Not sure why, but the ARM builds for the Docker images for this are insanely fast compared to Travis. We might want to consider looking at migrating to GitHub Actions sooner rather than later for our nightly Docker images and releases.

**Comment by cosmix** [comment]
That looks good @Ferroin -- let's discuss the Travis → GHA migration at first opportunity.

**Comment by Ferroin** [comment]
For future reference, there _is_ a reason that we require 2 approvals on things before merging, as annoying as it is at times within the small confines of the SRE team.

This actually does not work correctly, and I did not notice until _after_ it got merged. It's very likely it would have been caught if someone else had taken the time to look at this.

**Comment by cosmix** [comment]
Hey @Ferroin

> Verified that the checks run and pass correctly on my personal fork.

Well, I would be more careful when claiming that I 'verified' anything in the future if I were you. Your claim that you had verified its proper function, a review of your (now closed) PRs in your fork and the fact that this was a very small PR were what prompted my merging it.

Thanks.

**Comment by Ferroin** [comment]
> Well, I would be more careful when claiming that I 'verified' anything in the future if I were you. Your claim that you had verified its proper function, a review of your (now closed) PRs in your fork and the fact that this was a very small PR were what prompted my merging it.

Agreed, I should have been more thorough in checking the logs instead of just assuming the checks being green meant everything worked.

**Pull request merged**
