### PR TITLE
Don't overwrite my vscode settings!

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
My development environment stopped working properly.
Upon investigation I discovered my `.vscode/settings.json` which had quite a lot of things in it (lot of settings for intellisense etc.) was overwritten because somebody added this into the source tree.....

Made me cry because poor me no backup had.
Even worse is if me modification makes then git always complains.

Move this into `.vscode_template`. Who wishes to use default ones from repo can create symlink `.vscode->.vscode_template` ?

We should not force developers to adopt our idea of the right settings? Providing useful defaults is good idea but this practically enforces them. Currently every time I want to switch branch my settings will be deleted!

VSCODE has an issue about this https://github.com/microsoft/vscode/issues/40233 until this is solved we should not merge any `.vscode/*` file as that makes it impossible to have "personal workspace settings".

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by andrewm4894** [comment]
This was needed for proper metadata work using the custom schemas.

Idea is it should "just work" so as to make it as easy as possible for contributors etc to make improvements and updates to various metadata yaml files we now have that power the integrations marketplace.

My suggestion would be maybe you should have your own user level vscode settings that you can easily tell vscode to that precedence. There are various was to manage this in vscode. 

Or if your settings are generally useful maybe make a pr to include them in the repo settings.

Is a tricky one for sure. I think it would be nice and we should actually have a standard project level vscode settings so we can all be sure we looking at same screen in vscode as there actually was a bit of manual messing and overhead in the metadata work that was wasteful before we did this.

Sucks that it nuked your existing vscode settings but I think that's likely only going to hit team members who already have existing ones so maybe I wonder if a way to have best of both worlds.

**Comment by andrewm4894** [comment]
This was the pr fyi with some reasoning https://github.com/netdata/netdata/pull/15508

**Comment by underhood** [comment]
> This was needed for proper metadata work using the custom schemas.
> 
> Idea is it should "just work" so as to make it as easy as possible for contributors etc to make improvements and updates to various metadata yaml files we now have that power the integrations marketplace.
> 
> My suggestion would be maybe you should have your own user level vscode settings that you can easily tell vscode to that precedence. There are various was to manage this in vscode.
> 
> Or if your settings are generally useful maybe make a pr to include them in the repo settings.
> 
> Is a tricky one for sure. I think it would be nice and we should actually have a standard project level vscode settings so we can all be sure we looking at same screen in vscode as there actually was a bit of manual messing and overhead in the metadata work that was wasteful before we did this.
> 
> Sucks that it nuked your existing vscode settings but I think that's likely only going to hit team members who already have existing ones so maybe I wonder if a way to have best of both worlds.

there is currently no way to achieve this in vscode. User settings exist but are not specific for a workspace. Unfortunately there is no user-workspace settings. This is not nice thing that vscode doesn't have this but as a consequence we should not force our own settings.json as there are many reasons why particular developer needs/wants his own settings and for those settings to be applied only to that workspace (I have other repos that I work on which make using User settings of vscode not fit for the purpose)

**Comment by ilyam8** [comment]
I agree with @underhood, we shouldn't overwrite workspace settings.

**Review by ilyam8 — APPROVED** [review]

**Review by Dim-P — APPROVED** [review]

**Pull request merged**
