### PR TITLE
Redirect to index.html when a file is not found by web server

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Re-directs to `index.html` when a file requested from netdata web is not found.

##### Test Plan

TBD.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by MrZammler** [comment]
@novykh Not sure if this is what you want, or you want to really serve `index.html` when a file is not found, let us know.

**Comment by Ferroin** [comment]
> @novykh Not sure if this is what you want, or you want to really serve `index.html` when a file is not found, let us know.

If it’s going to behave correctly behind a proxy (which it _needs_ to do, because users rely on it behaving correctly behind a proxy) it needs to be a redirect, not an internal rewrite.

We probably need this to be a temporary redirect though (most likely a 307, not a 302), because we cannot guarantee that any arbitrary path the user requests will _actually_ never be a valid path.

**Comment by underhood** [comment]
We should do this also on h2o server then to keep behaviour consistent

**Comment by novykh** [comment]
> @novykh Not sure if this is what you want, or you want to really serve `index.html` when a file is not found, let us know.

We need to serve the index.html, not to redirect.

**Comment by underhood** [comment]
That sounds very sketchy at least from the point of view of person uninitiated into the deeper reason why this is necessary

**Comment by novykh** [comment]
@underhood this is a common practice for apps with client side routing. Routes on the client side are handled by the SPA, thus the only thing needed by the server is to serve their root file `index.html` and they will handle 404s themselves.

We can and should not render the `index.html` on server routing ie. `/api/*` and on requests to specific files (meaning with extension) ie. `localhost:19999/web/static/someLogo.png`, those should not be handled and should return 404 accordingly.
Is it now more clear?

**Comment by underhood** [comment]
We do have to also make compatible change on h2o side then. Otherwise we will never be able to switch to h2o

**Comment by thiagoftsm** [comment]
Hello @MrZammler ,

It looks like we are not giving everything necessary to load our index, please, take a look in this request:



, as you can see I am using `tls`.

Best regards!

**Comment by thiagoftsm** [comment]
These are the errors I have for latest request:

**Pull request merged**
