### PR TITLE
Create a terminology dictionary for Netdata

### PR DESCRIPTION
**Pull request by Ancairon**
##### Summary

We will use this file to dictate how we call things when we want to refer to a certain section of Netdata.

### CODE REVIEW

**Comment by ilyam8** [comment]
@Ancairon do we need both this new document and [glossary](https://github.com/Ancairon/netdata/blob/d6fb6803b7ca09bced6696a9fe4da290a5f60972/docs/glossary.md)?

**Comment by Ancairon** [comment]
I want to nuke the glossary, but I want to do it separately, as it requires learn-side removal too

**Comment by ilyam8** [comment]
> I want to nuke the glossary

Why? Do you think it's useless?

**Comment by Ancairon** [comment]
We can make it a txt and start pulling some words from it, but most stuff is legacy (David S.) created it back in the day, and I expect some stuff is not usable.

**Review by ilyam8 — APPROVED** [review]

**Pull request merged**
