### PR TITLE
varnish module: add instance_name option

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

Fixes: #5262

##### Component Name

[/collectors/python.d.plugin/varnish](https://github.com/netdata/netdata/blob/master/collectors/python.d.plugin/varnish/varnish.chart.py)

##### Additional Information

Details in https://github.com/netdata/netdata/issues/5262#issue-402818407

### CODE REVIEW

**Comment by ilyam8** [comment]
@feld

please check the fix

**Comment by feld** [comment]
I will test it soon, but this looks correct:

```
        if self.instance_name:
	            self.command = [varnishstat, '-1', '-n', self.instance_name]
	        else:
	            self.command = [varnishstat, '-1']
	        return True
```

**Comment by ilyam8** [comment]
@feld ye, it is an easy fix, and i am sure it will be working, but still better to check

**Comment by ilyam8** [comment]
@feld any news on this?

**Comment by ilyam8** [comment]
@cakrit please approve

**Pull request merged**
