### PR TITLE
remove deprecated node.d modules

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

❗ **should be merged after soft code freeze**

This PR removes the following node.d modules:

 - fronius
 - sma_webbox
 - stiebeleltron
 - named

Removes everything related from:
- documentation
- dashboard_info
- tests/
- codeowners
- installer

Leftovers:
 - [configs.signatures](https://github.com/netdata/netdata/blob/master/configs.signatures): the file content is outdated. I think we need just to remove it. Or not 🤷‍♂️ @netdata/agent-sre just letting you know guys that we have this strange file since I came across it.
 - [package.json](https://github.com/netdata/netdata/blob/master/package.json), [package-lock.json](https://github.com/netdata/netdata/blob/master/package-lock.json): likely a lot of stuff should be removed from these files (everything not remark-lint related?). Don't know how to do it properly. Can be done in a separate PR.

##### Test Plan

- ci checks and local install
- git grep -i <module_name> returns no matches

### CODE REVIEW

**Comment by kickoke** [comment]
First off, thank you for tackling this issue and reducing our tech debt. 
Regarding documentation / communication: We've announced the deprecation in the release notes, and people expect these features to be gone. However, when will this happen? The next scheduled release is in 2 months, but we release nightlies. How often do we release nightly builds? 

When would we communicate these changes?

**Comment by ilyam8** [comment]
- after the end of soft code freeze (we are still waiting in case there are some bugs and we will have to do a patch release (v1.322.1))
- we don't remove the collector's files from existing installs
- only new installs are affected

> How often do we release nightly builds?

Every night (if there are any changes)

**Review by codeguru1 — APPROVED** [review]

**Review by kickoke — APPROVED** [review]
Docs: LGTM 👍

**Comment by ktsaou** [comment]
The motivation here is to removed `node.js` collectors?

Name servers are very important to monitor. We are removing `named`! This is a big loss for all those who run a name server.

Also, in my case, I use `sma_webbox`. This is going to be lost now. Shall we move this code somewhere else as "not supported community collectors" so that people can install them if they need to?

I totally understand to eliminate `node.js` collectors and move everything to `go.d`. But just eliminating collectors without a replacement may seem a bit unfriendly for those who need these collectors. No?

**Comment by ktsaou** [comment]
Great! Thank you @Ferroin .

I didn't notice the bind plugin in go. Sorry. Does this provide all the charts of the node.js one?

Which community repo? This: https://github.com/netdata/community ?

**Comment by ilyam8** [comment]
> Does this provide all the charts of the node.js one?

Yes. From what I remember (been a while) - it provides the same set of charts.

> Which community repo? This: [netdata/community](https://github.com/netdata/community) ?

Yes. We [added a note](https://github.com/netdata/netdata/releases#deprecation-notice) to the release notes.

**Comment by ktsaou** [comment]
Great! Thank you very much guys for the clarifications! Great work!

**Comment by ilyam8** [comment]
rebase to pick latest ci changes and fix merge conflicts

**Comment by ilyam8** [comment]
rebase to resolve conflicts after removing GA links

**Review by kickoke — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]

**Comment by ilyam8** [comment]
will be merged on Mon

**Pull request merged**
