### PR TITLE
Indent generated files

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

SSIA.

##### Test Plan

- CI jobs

### CODE REVIEW

**Comment by ilyam8** [comment]
The subject doesn't say it all - can you please explain why we need this change?

**Comment by Ancairon** [comment]
The actual code was written by Austin, but I would doubt we need to indent it, as it might break things in the parsing done in the different places (in theory it shouldn't, but can't be sure)

**Comment by vkalintiris** [comment]
@ilyam8

> can you please explain why we need this change?

Because large, single-line files are treated as binary files from git (when diffing), ie. after a couple commits, git will add it to pack-files with no delta causing the repository to grow overtime due to their size being ~9 MiB. Secondly, it messes with `git grep` spewing garbage when you are looking for something.

@Ancairon 

> in theory it shouldn't, but can't be sure

There's only one way to find out 😇.

@Ferroin any feedback? If formatting javascript code and json files breaks things, I'd say we have more issues to solve.

**Comment by Ancairon** [comment]
Okay, then yeah, there is only one way to find out as you say, we could merge and see what gets messed up, in theory nothing should break, but I won't bet on it

**Comment by vkalintiris** [comment]
@Ancairon @ilyam8 can I get an approval so that I can merge this?

**Review by Ancairon — APPROVED** [review]
Let's try it

**Pull request merged**
