### PR TITLE
Fix memory mode none not marking dimensions as obsolete.

### LINKED ISSUE #9909: Parent keeps showing child stale (removed) dimensions if the child mem mode is `none`
##### Bug report summary

Parent netdata keeps showing child stale (removed) dimensions if the child mem mode is `none`.

That is test python module i use to reproduce the issue, it charts random[1-3] dimensions first 10 iterations, then it removes them (resends the chart definition with dimensions `obsolete` option set) and keeps charting random[4-7].

<details>
<summary>python script click click</summary>

```python
from random import SystemRandom

from bases.FrameworkServices.SimpleService import SimpleService

priority = 90000

ORDER = [
    'random',
]

CHARTS = {
    'random': {
        'options': [None, 'A random number', 'random number', 'random', 'random', 'line'],
        'lines': [
            ['random1']
        ]
    }
}


class Service(SimpleService):
    def __init__(self, configuration=None, name=None):
        SimpleService.__init__(self, configuration=configuration, name=name)
        self.order = ORDER
        self.definitions = CHARTS
        self.random = SystemRandom()
        self.runs = 0

    @staticmethod
    def check():
        return True

    def get_data(self):
        self.runs += 1
        data = dict()

        if self.runs < 10:
            for i in range(1, 4):
                dim_id = ''.join(['random', str(i)])
                data[dim_id] = self.random.randint(0, 100)
        else:
            for i in range(4, 7):
                dim_id = ''.join(['random', str(i)])
                data[dim_id] = self.random.randint(0, 100)

        for dim_id in data:
            if dim_id not in self.charts['random']:
                self.charts['random'].add_dimension([dim_id])

        for dim in self.charts['random']:
            if dim.id not in data:
                self.charts['random'].del_dimension(dim.id, hide=False)

        return data

```

</details>

<details>
<summary>python.d.plugin debug output click click</summary>

```cmd
2020-09-10 12:11:23: python.d DEBUG: test[test] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
BEGIN test.random 999644
SET 'random1' = 31
SET 'random2' = 6
SET 'random3' = 92
END

BEGIN netdata.runtime_test 999644
SET run_time = 0
END

2020-09-10 12:11:24: python.d DEBUG: test[test] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
CHART test.random '' 'A random number' 'random number' 'random' 'random' line 90000 1 '' 'python.d.plugin' 'test'
DIMENSION 'random1' 'random1' absolute 1 1 ' obsolete'
DIMENSION 'random2' 'random2' absolute 1 1 ' '
DIMENSION 'random3' 'random3' absolute 1 1 ' '
DIMENSION 'random4' 'random4' absolute 1 1 ' '
DIMENSION 'random5' 'random5' absolute 1 1 ' '
DIMENSION 'random6' 'random6' absolute 1 1 ' '

CHART test.random '' 'A random number' 'random number' 'random' 'random' line 90000 1 '' 'python.d.plugin' 'test'
DIMENSION 'random2' 'random2' absolute 1 1 ' '
DIMENSION 'random3' 'random3' absolute 1 1 ' obsolete'
DIMENSION 'random4' 'random4' absolute 1 1 ' '
DIMENSION 'random5' 'random5' absolute 1 1 ' '
DIMENSION 'random6' 'random6' absolute 1 1 ' '

BEGIN test.random 999950
SET 'random4' = 22
SET 'random5' = 98
SET 'random6' = 19
END

BEGIN netdata.runtime_test 999950
SET run_time = 0
END

2020-09-10 12:11:25: python.d DEBUG: test[test] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
CHART test.random '' 'A random number' 'random number' 'random' 'random' line 90000 1 '' 'python.d.plugin' 'test'
DIMENSION 'random2' 'random2' absolute 1 1 ' obsolete'
DIMENSION 'random4' 'random4' absolute 1 1 ' '
DIMENSION 'random5' 'random5' absolute 1 1 ' '
DIMENSION 'random6' 'random6' absolute 1 1 ' '

BEGIN test.random 1000071
SET 'random4' = 11
SET 'random5' = 40
SET 'random6' = 84
END

BEGIN netdata.runtime_test 1000071
SET run_time = 0
END

2020-09-10 12:11:26: python.d DEBUG: test[test] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
BEGIN test.random 1000324
SET 'random4' = 35
SET 'random5' = 48
SET 'random6' = 36
END

BEGIN netdata.runtime_test 1000324
SET run_time = 0
END

2020-09-10 12:11:27: python.d DEBUG: test[test] : update => [OK] (elapsed time: 0, failed retries in a row: 0)
BEGIN test.random 999669
SET 'random4' = 48
SET 'random5' = 4
SET 'random6' = 65
END
```

</details>

The chart (child dashboard, mem mode not `none`, before the test):
Screenshot 2020-09-10 at 12 13 51

That is how that chart looks like if i stream the data to the netdata parent with child memory mode `none` (parent dashboard, durint the test)

Screenshot 2020-09-10 at 12 10 14

As you can see there are old (random[1-3]] dimensions and their last value.

##### OS / Environment

parent: latest docker image

child:
```cmd
[ilyam@ilyam-pc ~]$ uname -a; grep -Hv "^#" /etc/*release
Linux ilyam-pc 5.7.19-2-MANJARO #1 SMP PREEMPT Fri Aug 28 20:22:12 UTC 2020 x86_64 GNU/Linux
/etc/arch-release:Manjaro Linux
/etc/lsb-release:DISTRIB_ID=ManjaroLinux
/etc/lsb-release:DISTRIB_RELEASE=20.1
/etc/lsb-release:DISTRIB_CODENAME=Mikah
/etc/lsb-release:DISTRIB_DESCRIPTION="Manjaro Linux"
/etc/manjaro-release:Manjaro Linux
/etc/os-release:NAME="Manjaro Linux"
/etc/os-release:ID=manjaro
/etc/os-release:ID_LIKE=arch
/etc/os-release:BUILD_ID=rolling
/etc/os-release:PRETTY_NAME="Manjaro Linux"
/etc/os-release:ANSI_COLOR="32;2;24;144;200"
/etc/os-release:HOME_URL="https://manjaro.org/"
/etc/os-release:DOCUMENTATION_URL="https://wiki.manjaro.org/"
/etc/os-release:SUPPORT_URL="https://manjaro.org/"
/etc/os-release:BUG_REPORT_URL="https://bugs.manjaro.org/"
/etc/os-release:LOGO=manjarolinux
```

##### Netdata version

parent:

```cmd
[ilyam@ilyam-pc ~]$ docker exec -it romantic_pike netdata -v
netdata v1.24.0-211-g8f65a4f1
```
 
child:

```cmd
[ilyam@ilyam-pc ~]$ /opt/netdata/usr/sbin/netdata -v
netdata v1.24.0-215-gc1698e87
```

##### Steps To Reproduce

We need parent/child setup, i use docker instance as the parent.

**Parent**:
1. Install netdata parent instance

```cmd
docker run -d -p 19998:19999 netdata/netdata
```

2. Configure parent stream.conf

```cmd
[11111111-2222-3333-4444-555555555555]
    enabled = yes
    allow from = *
    default history = 3600
    default memory mode = ram
    health enabled by default = auto
    default postpone alarms on connect seconds = 60
```

3. Restart netdata parent (docker stop/start)

**Child**:

1. Put the test script (see `bug report` summary section) in the `/usr/libexec/netdata/python.d/`

2. Configure child stream.conf

```cmd
[stream]
    enabled = yes
    destination = 127.0.0.1:19998
    api key = 11111111-2222-3333-4444-555555555555
```

3. Set child memory mode to `none`

```cmd
[global]
	memory mode = none
```

4. Restart netdata child, see the test script chart.

##### Expected behavior

Netdata parent shouldnt show stale data on the charts if netdata child memory mode is `none`

### PR DESCRIPTION
**Pull request by mfundul**
##### Summary
Fixes #9909
##### Component Name
database
##### Test Plan
See the description [here](https://github.com/netdata/netdata/issues/9909#issue-697680196).

### CODE REVIEW

**Review by ilyam8 — APPROVED** [review]

**Comment by vlvkobal** [comment]
```
  CC       database/engine/metadata_log/metadatalog.o
database/rrdset.c: In function 'rrdset_done':
database/rrdset.c:1789:5: warning: 'next_store_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1789 |     rrdset_done_interpolate(st
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
 1790 |             , update_every_ut
      |             ~~~~~~~~~~~~~~~~~
 1791 |             , last_stored_ut
      |             ~~~~~~~~~~~~~~~~
 1792 |             , next_store_ut
      |             ~~~~~~~~~~~~~~~
 1793 |             , last_collect_ut
      |             ~~~~~~~~~~~~~~~~~
 1794 |             , now_collect_ut
      |             ~~~~~~~~~~~~~~~~
 1795 |             , store_this_entry
      |             ~~~~~~~~~~~~~~~~~~
 1796 |             , storage_flags
      |             ~~~~~~~~~~~~~~~
 1797 |     );
      |     ~
database/rrdset.c:1789:5: warning: 'last_stored_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
database/rrdset.c:1789:5: warning: 'now_collect_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
```

**Comment by mfundul** [comment]
> 
> 
> ```
>   CC       database/engine/metadata_log/metadatalog.o
> database/rrdset.c: In function 'rrdset_done':
> database/rrdset.c:1789:5: warning: 'next_store_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
>  1789 |     rrdset_done_interpolate(st
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
>  1790 |             , update_every_ut
>       |             ~~~~~~~~~~~~~~~~~
>  1791 |             , last_stored_ut
>       |             ~~~~~~~~~~~~~~~~
>  1792 |             , next_store_ut
>       |             ~~~~~~~~~~~~~~~
>  1793 |             , last_collect_ut
>       |             ~~~~~~~~~~~~~~~~~
>  1794 |             , now_collect_ut
>       |             ~~~~~~~~~~~~~~~~
>  1795 |             , store_this_entry
>       |             ~~~~~~~~~~~~~~~~~~
>  1796 |             , storage_flags
>       |             ~~~~~~~~~~~~~~~
>  1797 |     );
>       |     ~
> database/rrdset.c:1789:5: warning: 'last_stored_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
> database/rrdset.c:1789:5: warning: 'now_collect_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
> ```

That's a false positive, unless you can find a flaw in the logic.

**Comment by mfundul** [comment]
@vlvkobal so what's the suggested course of action here, should I just set everything to 0 at the beginning and be done with it?

**Comment by thiagoftsm** [comment]
GCC 9.3 gives more details:

```
database/../daemon/../libnetdata/log/log.h:88:26: warning: 'next_store_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
   88 | #define info(args...)    info_int(__FILE__, __FUNCTION__, __LINE__, ##args)
      |                          ^~~~~~~~
database/rrdset.c:1394:13: note: 'next_store_ut' was declared here
 1394 |             next_store_ut,          // the timestamp in microseconds, of the next entry to store in the db
      |             ^~~~~~~~~~~~~
database/rrdset.c:1154:52: warning: 'last_stored_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1154 |     ssize_t iterations = (ssize_t)((now_collect_ut - last_stored_ut) / (update_every_ut));
      |                                    ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
database/rrdset.c:1393:13: note: 'last_stored_ut' was declared here
 1393 |             last_stored_ut,         // the timestamp in microseconds, of the last stored entry in the db
      |             ^~~~~~~~~~~~~~
database/rrdset.c:1155:24: warning: 'now_collect_ut' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1155 |     if((now_collect_ut % (update_every_ut)) == 0) iterations++;
      |        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
database/rrdset.c:1392:13: note: 'now_collect_ut' was declared here
 1392 |             now_collect_ut,         // the timestamp in microseconds, of this collected value (this is NOW)
      |             ^~~~~~~~~~~~~~
```

when I compiled with:

```
CFLAGS="-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1" ./netdata-installer.sh --disable-lto --dont-wait --dont-start-it
```

**Review by vlvkobal — APPROVED** [review]

**Review by thiagoftsm — APPROVED** [review]
The PR is fixing the problem with `memory mode = none` and there was not any changes with `memory mode = dbengine`. LGTM!

**Review by ilyam8 — APPROVED** [review]

**Pull request merged**
