### PR TITLE
make zlib compulsory dep

### LINKED ISSUE #14638: [Bug]: make zlib a compulsory dependency
### Bug description

Make ZLIB a compulsury dependency. Currently `--without-zlib` build fails due to its heavy usage in dbenginev2 and adjacent code.

similar errors in other DBENGINEv2 related files (e.g. `database/engine/rrdengine.c`)
```
database/engine/journalfile.c:1120:5: error: unknown type name 'uLong'; did you mean 'ulong'?
 1120 |     uLong crc;
      |     ^~~~~
      |     ulong
database/engine/journalfile.c:1122:21: error: 'Z_NULL' undeclared (first use in this function); did you mean 'N_NULL'?
 1122 |     crc = crc32(0L, Z_NULL, 0);
      |                     ^~~~~~
      |                     N_NULL
database/engine/journalfile.c: In function 'journalfile_migrate_to_v2_callback':
database/engine/journalfile.c:1262:5: error: unknown type name 'uLong'; did you mean 'ulong'?
 1262 |     uLong crc;
      |     ^~~~~
      |     ulong
database/engine/journalfile.c:1263:21: error: 'Z_NULL' undeclared (first use in this function); did you mean 'N_NULL'?
 1263 |     crc = crc32(0L, Z_NULL, 0);
      |                     ^~~~~~
      |                     N_NULL
```

```
  CC       collectors/apps.plugin/apps_plugin.o
In file included from ./database/engine/rrdengine.h:17,
                 from ./database/engine/rrdengineapi.h:6,
                 from ./database/rrd.h:1382,
                 from ./daemon/global_statistics.h:6,
                 from ./daemon/common.h:36,
                 from ./collectors/all.h:6,
                 from collectors/apps.plugin/apps_plugin.c:9:
./database/engine/rrdenginelib.h:75:40: error: unknown type name ‘uLong’; did you mean ‘ulong’?
   75 | static inline int crc32cmp(void *crcp, uLong crc)
      |                                        ^~~~~
      |                                        ulong
./database/engine/rrdenginelib.h:80:41: error: unknown type name ‘uLong’; did you mean ‘ulong’?
   80 | static inline void crc32set(void *crcp, uLong crc)
      |                                         ^~~~~
      |                                         ulong
make[2]: *** [Makefile:6149: collectors/apps.plugin/apps_plugin.o] Error 1
make[2]: Leaving directory '/home/timo/projects/netdata/netdata'
make[1]: *** [Makefile:7407: all-recursive] Error 1
make[1]: Leaving directory '/home/timo/projects/netdata/netdata'
```

### Steps to reproduce

1. `./configure --without-zlib whateverelseyouneed`
2. no zlib-dev in the system
3.
...

### PR DESCRIPTION
**Pull request by underhood**
##### Summary
Fixes #14638

Makes zlib a compulsory dependency as it is used now even in dbengine v2. We will not support build without zlib anymore.

Configure should detect missing zlib-dev in the system and stop the build with clear error message.

##### Test Plan
If your system has zlib-devel you should build as now all OK.
On system without zlib configure should detect it and print clear error message.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by Dim-P — DISMISSED** [review]
Test on Debian 11, LGTM!

**Review by thiagoftsm — DISMISSED** [review]
I tested locally and netdata is working as expected, LGTM!

**Comment by Ferroin** [comment]
This _should_ be a reasonably safe change, as zlib is available pretty much everywhere (the only people likely to be affected are those building custom systems from the ground up.

That said, this _is_ a breaking change, and as such should not be merged without first announcing it as an upcoming change in the release notes.

**Comment by underhood** [comment]
@stelfrag what do you think about Austins comment above?

**Comment by stelfrag** [comment]
> @stelfrag what do you think about Austins comment above?

Ok, we can do that. Announce it and apply on the next release. As it is now, you can probably build an agent without zlib (custom without dbengine and all)

**Comment by Ferroin** [comment]
Current plan is to merge this tomorrow (waiting one day so we have at least one nighly after the new release without any potentially breaking changes).

**Comment by ilyam8** [comment]
@underhood there are merge conflicts to resolve

**Review by thiagoftsm — APPROVED** [review]
No warnings during compilation time and Netdata is working as expected, LGTM!

**Pull request merged**
