### PR TITLE
Add Clickhouse Python collector

### PR DESCRIPTION
**Pull request by FedericoCeratto**
##### Summary

Collector for ClickHouse database

##### Test Plan

Tested with local database

##### Additional Information

This is an initial version. The selection of metrics could be improved and some metrics could be grouped together. New commits and feedback are welcome!

Implements #4813

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/clickhouse/clickhouse.chart.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5344058&bid=17496125)

**Comment by ilyam8** [comment]
@FedericoCeratto sorry for the delay, busy atm, will review later.

And could you rebase the PR? i think it would fix all the checks

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/clickhouse/clickhouse.chart.py  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=5344058&bid=17496125)

**Comment by ilyam8** [comment]
@FedericoCeratto hey

i understand that this is you way/style of coding, but it is hard to grasp charts creation logic (i understand it works!), and it _doesnt follow_ approach we use:

simple and clear charts definitions with dimensions, like

https://github.com/netdata/netdata/blob/11a19ccf27d665bf1ad795bb4ed64786540d6212/collectors/python.d.plugin/apache/apache.chart.py#L19-L66

^^ it is easy to follow, you read is as text.

I see there is no dynamic charts in your code, i suggest to rewrite charts definitions if you are ok with it.

---

One more thing, i see you added really good chart titles

> Number of queries started to be interpreted and maybe executed. Does not include queries that are failed to parse, that are rejected due to AST size limits; rejected due to quota limits or limits on number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.

Unfortunately netdata chart titles is something hard to read and we have a problem with them in general (mainly because of small font imo), it is common to have short title and move all the details to the `dashboard_info.js` - there you can use hyperlinks, bold font, etc.

**Comment by m1khal3v** [comment]
any news here?

**Comment by m1khal3v** [comment]
any news here?

**Comment by Cimus** [comment]
when will he leave for release?

**Comment by ilyam8** [comment]
@m1khal3v @Cimus thanks for the interest. We are not going to merge this PR (despite the awesome work done by @FedericoCeratto). In general, our plan is to (eventually) get rid of all python collectors. We implement ClickHouse collector in golang. If any of you is able to help us (see #4813) to do it, you are welcome.

**Comment by andrewm4894** [comment]
For anyone who wants to use the version created by @FedericoCeratto i have made a copy of it in here: https://github.com/netdata/community/tree/main/collectors/python.d.plugin/clickhouse

And added some instructions on how to use it here (plus one small fix i had to do): https://github.com/netdata/community/tree/main/collectors/python.d.plugin/clickhouse#installation

I have just tested this out and it seems to work.

So while this is not an offically supported collector and wont be merged into `netdata/netdata` i have made a copy of it in `netdata/community` along with instructions to use it if you so wish. 

Many thanks @FedericoCeratto - am sure this might be useful for some while we try find a sponsor to implement an offical version in Go.

I am also going to update our docs maybe [here](https://learn.netdata.cloud/docs/agent/collectors/python.d.plugin) to make it much clearer how users can use external collectors like this without them needing to have been merged into `netdata/netdata`

**Pull request closed without merging**
