### PR TITLE
fix packaging static build openssl 32bit

### PR DESCRIPTION
**Pull request by ilyam8**
##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Comment by Ferroin** [comment]
@ktsaou  Why, _exactly_ was this merged without waiting for CI to pass completely, let alone without any approving reviews from the people who are actually responsible for this code?

**Comment by ilyam8** [comment]
@Ferroin 

- we tested it by building for non amd64/x86_64 locally.
- we need to get it merged to rebase our PRs to fix ci.

**Comment by ilyam8** [comment]
> Why, exactly was this merged without waiting for CI to pass completely,

Valid question, you are right. We need to explain (comment) when we do it @ktsaou

**Comment by ktsaou** [comment]
It was early in the morning, we tested it locally, the master was already broken.

What we could do worst? It looked like that we had nothing to lose, even this had another issue.

**Pull request merged**
