### PR TITLE
upload artifacts to gcs

### LINKED ISSUE #4628: Store nightly build artifacts somewhere
##### Feature idea summary

Currently nightly builds are creating binaries (makeself and tar.gz archives) but not storing them anywhere. This should be fixed and binaries should be stored somewhere. Preferably in some sort of object storage so we can track how many downloads of particular files there is.

##### Expected behavior

Nightly build artifacts are preserved.

### PR DESCRIPTION
**Pull request by paulfantom**
##### Summary

Upload `*.tar.gz` archive to GCS for futher consumption by an updater script.

Fixes #4628

##### Component Name

packaging
ci

##### Additional Information

Needed:
1. GCS bucket with a name `netdata-nightlies` and following permissions:
   - allUsers: "Storage Object Viewer"
   - allUsers: "Storage Legacy Bucket Reader"
2. Access key and secret key

This uploads only archives created by `make dist` not makeself binaries.

### CODE REVIEW

**Comment by ktsaou** [comment]
I probably lost some discussion. Could you please update the description with the motivation behind this. What are we trying to do?

**Comment by paulfantom** [comment]
@ktsaou this: https://github.com/netdata/netdata/issues/4628

**Comment by paulfantom** [comment]
And motivation is to switch automatic updater script to use those artifacts and not git repo.

**Comment by ktsaou** [comment]
ok, thanks!

**Comment by gmosx** [comment]
I created the bucket for you and emailed you the details.

**Comment by paulfantom** [comment]
Added credentials in encrypted form. Ready to be merged.

**Pull request merged**
