### PR TITLE
removed simley face per Chris since it didn't show up

### PR DESCRIPTION
**Pull request by MeganBishopMoore**

### CODE REVIEW

**Comment by joelhans** [comment]
@MeganBishopMoore or @prologic: Could one of your verify that the emoji shows up properly on this page? https://learn.netdata.cloud/docs/agent/step-by-step/step-03/

I deployed a fix to the Learn site that fixes how we decode the content from GitHub and I'm pretty sure it fixes this emoji and all the others. If we can verify it works, then we can close this issue.

**Comment by MeganBishopMoore** [comment]
Smiley face works now. Chris didn't like the use of the emoji at all, but that's above my paygrade. :)

**Comment by joelhans** [comment]
> Chris didn't like the use of the emoji at all, but that's above my paygrade. :)

Aha! Well, I'm not opposed to removing it. I'm still happy it works properly on the Learn site. We'll keep this open and merge it after the 1.22 release goes out.

**Comment by joelhans** [comment]
Closed & re-opened to try to get the checks running. They appeared to be stalled out.

**Comment by prologic** [comment]
> Closed & re-opened to try to get the checks running. They appeared to be stalled out.

In future jsut do this:

```#!sh
git commit --allow-empty -m "Retrigger CI"
git push
```

**Pull request merged**
