### PR TITLE
Issue #8087

### PR DESCRIPTION
**Pull request by petarkozic**

### CODE REVIEW

**Comment by ilyam8** [comment]
Hi @petarkozic 

I suggest to not use screenshots, it makes readme kind of bloated. Just a list of steps is enough.

And there is a problem with CLA, i see you did commits from 2 accounts.

**Comment by petarkozic** [comment]
Hi @ilyam8 
Ok, I will remove screenshots now and make new PR.

Yes, I open issue by mistake from company account, but continue and want to continue with my private. If you can remove this one with username: kozicpetar

Thank you.

**Comment by ilyam8** [comment]
@petarkozic feel free to close this one and open a new one

**Comment by petarkozic** [comment]
I will open a new one because of SLA issue!

**Pull request closed without merging**
