### PR TITLE
Make atomics a hard-dep.

### PR DESCRIPTION
**Pull request by vkalintiris**
##### Summary

They are used extensively throughout our code base, and not having
support for them does not generate a thread-safe agent.

##### Test Plan

CI jobs.

### CODE REVIEW

**Comment by vkalintiris** [comment]
@Dim-P can you check this branch on your rpi?

@Ferroin how can we test this PR for all arches/distros we support?

**Comment by Ferroin** [comment]
> @Ferroin how can we test this PR for all arches/distros we support?

Default CI covers everything currently in our Core support tier on 64-bit x86.

We can pick up a significant number of distros on ARM in automated testing by explicitly running the full packaging CI (you can do this by putting the exact string `/actions run full ci` in the PR body and then retrigering the packaging workflow),

Beyond that we don’t really have a good way currently to properly test things in an automated way.

For manual cross-CPU testing I would recommend starting with QEMU userspace emulation and Debian’s official Docker images, as that will allow for testing on ARMv5, ARMv7, 64-bit ARMv8, 64-bit MIPS, 64-bit POWER, 64-bit RISC-V (requires Debian Sid images), and System/z.

**Comment by Dim-P** [comment]
@vkalintiris Just tried it and I can confirm it builds now on a 32-bit Raspbian.

**Comment by vkalintiris** [comment]
> Default CI covers everything currently in our Core support tier on 64-bit x86.

I'm marking this as ready for review because we pass the current CI checks for x86_64 and 32-bit raspbian builds with no problems based on @Dim-P's comment.

**Comment by Ferroin** [comment]
I’ve done some cross-arch testing myself on this. checking 64-bit ARM, 64-bit POWER, and 64-bit RISC-V with Debian 11 Docker images, and all three build correctly.

**Comment by vkalintiris** [comment]
@Ferroin do you think it's ok to merge this one?

**Review by Ferroin — APPROVED** [review]

**Comment by Ferroin** [comment]
@vkalintiris Sorry, forgot to approve it when I left the comment regarding what testing I’d done.

**Pull request merged**
