### PR TITLE
Remove fedora 37 from CI

### PR DESCRIPTION
**Pull request by tkatsoulas**
##### Summary

Closes https://github.com/netdata/netdata/issues/16397

DON't merge this before 2023-12-05

##### Test Plan

Skip

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

### CODE REVIEW

**Review by Ferroin — DISMISSED** [review]

**Comment by Neustradamus** [comment]
Fedora 37 is EOL now.

**Comment by ilyam8** [comment]
@tkatsoulas should we postpone the PR until after the release? I think it will be nice if Fedora37 gets v1.44.0

**Comment by vkalintiris** [comment]
@Ferroin & @tkatsoulas as long as we *can* build the agent successfully, why do we have to remove the distro and stop creating packages for our users?

**Comment by Ferroin** [comment]
@vkalintiris This was discussed a bit during the sync, but I’m commenting here also so that it’s publicly visible.

There are ultimately three reasons we completely drop a platform from CI when we stop official support for it:

- We’ve got a limited number of CI jobs that can run concurrently, and each platform corresponds to _at least_ one job that needs to run during both PR checks and the release process. Full release builds already take multiple hours to complete, and they also end up tying up CI runners for a longer period of time overall than most other CI, so it’s desirable to keep the number of jobs running in them to a minimum to reduce their impact on other development work.
- Proactively dropping EoL platforms from CI is much less effort than reactively doing so, because we don’t need to get into potentially complicated investigations to figure out whether an issue with a given build is a result of some transient error or something that actually warrants us finally dropping the platform from CI.
- Proactively dropping EoL platforms from CI also ensures that we don’t pollute CI with useless failure results when the platform eventually does break. This is significant because it’s not a matter of ‘if’ the build breaks there, it’s a matter of ‘when’ it breaks.

**Pull request merged**
