### PR TITLE
samba: properly check if it is allowed to run smbstatus with sudo

### PR DESCRIPTION
**Pull request by ilyam8**
### Summary

Fixes: #7651

We want to be sure we are allowed to run command with sudo before executing it.

Old approach:
 - `sudo -v`

Is not good, see https://github.com/netdata/netdata/issues/7651#issuecomment-570163063

After this PR:
 - execute `sudo -n -l COMMAND`, read output, compare output with `COMMAND`

##### Component Name

[`/collectors/python.d.plugin/samba`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/samba)

##### Additional Information

@camjesus2 could you test it?

- `git clone https://github.com/ilyam8/netdata --branch=samba_check_fix netdata_samba_fix`
- `cd netdata_samba_fix`
- install netdata
- check the dashboard

### CODE REVIEW

**Comment by ktsaou** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/samba/samba.chart.py  1
         

Clones removed
==============
+ collectors/python.d.plugin/samba/samba.chart.py  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=4754689&bid=15858515)

**Comment by camjesus2** [comment]
@ilyam8, I can confirm that your fix works.
Had to explicitly enable samba in `/usr/lib/netdata/conf.d/python.d.conf` by changing `# samba:yes` to `samba:yes` which in itself is non-standard behavior.
error.log now gives ` python.d INFO: plugin[main] : samba[samba] : check success` as it should.
Outstanding job, thanks for your help

Best regards!
Carlos

**Comment by ilyam8** [comment]
> Had to explicitly enable samba in /usr/lib/netdata/conf.d/python.d.conf by changing # samba:yes to samba:yes which in itself is non-standard behavior

Yes yes, see 

> https://github.com/netdata/netdata/pull/4477

it is mentioned in the module readme

> https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/samba#configuration

**Comment by camjesus2** [comment]
> > Had to explicitly enable samba in /usr/lib/netdata/conf.d/python.d.conf by changing # samba:yes to samba:yes which in itself is non-standard behavior
> 
> Yes yes, see
> 
> > #4477
> 
> it is mentioned in the module readme
> 
> > https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/samba#configuration

Yes, it is, and it would be standard to change #samba:no to samba:yes. What I mean is that change #samba:yes to samba:yes is non-standard since usually the displayed option is the default. Not really worth the trouble though....

**Comment by ilyam8** [comment]
It is expected. This is how it works for disabled by default modules.

If modules is disabled by default

https://github.com/netdata/netdata/blob/447e9bdf8f5cc7c37bc0feb9499dfb47d7f9d008/collectors/python.d.plugin/samba/samba.chart.py#L25

it should be **explicitly** enabled in the `python.d.conf`

https://github.com/netdata/netdata/blob/447e9bdf8f5cc7c37bc0feb9499dfb47d7f9d008/collectors/python.d.plugin/python.d.plugin.in#L530-L532

**Comment by ilyam8** [comment]
@Ferroin please approve again 😅

**Pull request merged**
