### PR TITLE
add alarm values collector

### PR DESCRIPTION
**Pull request by andrewm4894**
add a python collector to capture and plot all calculated alarm values over time.

##### Summary

Add a python collector to capture and plot all calculated alarm values over time.

This collector creates an 'Alarm Values' menu with one line plot showing calculated alarm values over time. This can be useful when you want to see how specific calculated alarm values have evolved over time as you troubleshoot.

##### Component Name

/collectors/python.d.plugin/alarm_values/

##### Test Plan

Tested locally on development nodes. 

##### Additional Information

More details in README of the collector.

### CODE REVIEW

**Comment by andrewm4894** [comment]
adding image to link to in the README

image

**Comment by ilyam8** [comment]
@andrewm4894 how about to extend [`alarms`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/alarms#alarms---graphing-netdata-alarm-states-over-time) collector? We use same data here (`http://127.0.0.1:19999/api/v1/alarms?all`).

**Comment by andrewm4894** [comment]
> how about to extend [`alarms`](https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin/alarms#alarms---graphing-netdata-alarm-states-over-time) collector?

Good idea - i will try work this into a addition to alarms collector whereby you can optionally turn the alarm values chart on if you want.

**Comment by andrewm4894** [comment]
converting to draft while i work it into another PR that just includes this functionality as an option in the alarms collector.

**Comment by ilyam8** [comment]
> converting to draft while i work it into another PR

if there is another PR is coming i suggest to close this one as `wontfix`.

**Comment by andrewm4894** [comment]
Closing as superseeded by https://github.com/netdata/netdata/pull/10675

**Pull request closed without merging**
