### PR TITLE
delete package.json

### PR DESCRIPTION
**Pull request by ilyam8**
##### Summary

A lot of packages from [package.json](https://github.com/netdata/netdata/blob/master/package.json) were used by the node.d test suite, which was removed in https://github.com/netdata/netdata/pull/12047.

I don't think we need that file. Having it provides 0 value, but only problems (security alerts, dependabot PRs).

##### Test Plan

ci checks

### CODE REVIEW

**Comment by Ferroin** [comment]
The caveat here is that we _may_ need some of this stuff for the documentation related things, but I’m not sure how much of that we actually care about.

**Comment by ilyam8** [comment]
> The caveat here is that we may need some of this stuff for the documentation related thing

True, I have this in mind. I have no idea how to clean up the file. I think we can delete and see if we need it/something doesn't work - in that case, we just add with only needed packages.

**Comment by Ferroin** [comment]
Yeah, long term I think we would want to not use `package-lock.json` for this type of thing, and just specify _exact_ versions in `package.json`, which should eliminate most of the security alerts (99% of them have been indirect dependencies listed in `package-lock.json`, not thins we’re actually pulling in in `package.json`).

For now, unless @kickoke or @DShreve2 think we should keep it for the docs related stuff, I believe the best approach is to just dump all of this and rebuild from scratch if and when we actually start using the stuff like remark-lint.

**Review by thiagoftsm — APPROVED** [review]
After to talk with @ilyam8 about the `codeowner`, I am approving it. LGTM!

**Review by kickoke — APPROVED** [review]

**Review by Ferroin — APPROVED** [review]

**Pull request merged**
