### PR TITLE
[ReOpen #8626] Improved offline installation instructions to point to correct installation scripts and clarify process

### PR DESCRIPTION
**Pull request by IceCodeNew**
##### Summary
0. Amend an incorrect command in the document, also correct the link to _install-required-packages.sh_ script.(https://github.com/netdata/netdata/blame/9342704a41cbd20a315e55f0b1ff3efd9f039498/packaging/installer/methods/offline.md#L37)

1. Make the parts of the example command that need to be filled by the user be clearly separated from other parts.(https://github.com/IceCodeNew/netdata/commit/e13d9a60a6d587ae80b2bfc7326b9a809aa48d69#diff-40714f9627176dfafc102507b4ffb471R73)

##### Component Name
None.

##### Test Plan
None. It's just a rewording of the document.

##### Additional Information
Re-open [PR#8626](https://github.com/netdata/netdata/pull/8626), As I re-commit this change, the PR was automatically closed. Never thought about such consequence before I issue `git reset --hard HEAD~N` and `git push -f` :-(

### CODE REVIEW

**Comment by IceCodeNew** [comment]
Here's the thing,
I once had sync all commits from Apr 7th till today, and found my repo won't pass all the CI tests.
So I issued `git reset --hard HEAD~N` and cut off all the commits come after "[[PR#8639] Pin mkdocs-material](https://github.com/netdata/netdata/pull/8639)" and re-commit my change to the `offline.md` (which led to the close of [[PR#8626]](https://github.com/netdata/netdata/pull/8626)), but it turns out doesn't solve the problem.

I'm getting confused now, as "[[PR#8636] collectors/python.d/mysql: fix `threads_creation_rate` chart context](https://github.com/netdata/netdata/pull/8639)" is the only commit that comes after Apr 7th but before the "[[PR#8639] Pin mkdocs-material](https://github.com/netdata/netdata/pull/8639)", so it is fair to assume that PR had introduced the only failed check to the repo.
But when I check that PR, I found a comment says:
> Merging, as the only failed checks have nothing to do with this PR.

**Comment by IceCodeNew** [comment]
> I'm getting confused now, as "[[PR#8636] collectors/python.d/mysql: fix `threads_creation_rate` chart context](https://github.com/netdata/netdata/pull/8639)" is the only commit that comes after Apr 7th but before the "[[PR#8639] Pin mkdocs-material](https://github.com/netdata/netdata/pull/8639)", so it is fair to assume that PR had introduced the only failed check to the repo.
> But when I check that PR, I found a comment says:
> 
> > Merging, as the only failed checks have nothing to do with this PR.

@ilyam8 @prologic @joelhans May you guys give me some insight into this problem? I'm so tired of trying to get through all those CI tests.
I'm not sure what's blocking my PR from been merging. But it's reasonably clear that my commit of the document won't introduce a failed check, so maybe we could overwhelm the CI test and merge this PR?

**Comment by IceCodeNew** [comment]
I tried to drop commit from "[[PR#8636] collectors/python.d/mysql: fix `threads_creation_rate` chart context](https://github.com/netdata/netdata/pull/8639)" by doing another rebase. However, it keeps failing anyway.

**Comment by IceCodeNew** [comment]
I think I had exhausted all the methods I can come up with. As every effort turns out in vain, I will now start to wait for a PR that will fix the failing check which I don't know when it was introduced.

**Comment by ilyam8** [comment]
@IceCodeNew ci fails but it is not because of your PR, dont worry.

See [my pr](https://github.com/netdata/netdata/pull/8683), i added a space it ci fails too 😄

**Comment by IceCodeNew** [comment]
> Please rebase this PR :)

I am going to drop the commit [Pin mkdocs-material](https://github.com/netdata/netdata/pull/8680/commits/54aff6e039c9f1112fec892c054812d99105b7cd), due to the version of `mkdocs-material` is no longer fixed, the CI test would probably fail again.
Is it OK for you?

// I really should create a new branch for PR in the initial time. So that I can introduce the upstream change to the master branch and rebase it to the PR branch without changing its SHA hash.

**Comment by prologic** [comment]
> Can we have someone with admin privileges like @Ferroin merge this despite the Netlify failures? The error is completely unrelated to this PR and Netlify should build just fine once merged—a fix for the errors is already present in master.
> 
> Plus, we're only going to be using the old docs site for a few more days now...

I will merge it now...

**Pull request merged**
