### PR TITLE
Add cgroup cpu and memory limits and alarms

### PR DESCRIPTION
**Pull request by vlvkobal**
##### Summary
Add limit variables to cgroup charts. Provide alarms for limited resources. Add charts for resource usage within cgroup limits.
- [x] CPU
- [x] memory

Partly implements #2401

##### Component Name
`cgroups` plugin

##### Additional Information
Disk limits can't be implemented on the existing charts. If we decide to implement them, it will be done in another PR.

### CODE REVIEW

**Comment by vlvkobal** [comment]
I don't use any data from Docker. Look at  [CFS Bandwidth Control](https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt). There are two files to control CPU limits for cgroups: `cpu.cfs_period_us` and `cpu.cfs_quota_us`.

What is "dial"? Is this a type of chart?

**Comment by vlvkobal** [comment]
I tested it with `--cpus=` option. It works. Actually, docker changes the same cgroup files: `cpu.cfs_period_us` and `cpu.cfs_quota_us` when `--cpus=` is set.

**Comment by cakrit** [comment]
Just tested the last changes, it looks good to me.

**Comment by ktsaou** [comment]
Please make sure it is tested under valgrind

**Pull request merged**
