### PR TITLE
Add code for repository configuration packages.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This is the first step in a major overhaul of our installation code. Adding these packages will greatly simplify handling of binary package based installations in the new version of the kickstart script, and also allow us to seamlessly switch over our users if we migrate to a different hosting method for our binary package repositories.

##### Component Name

area/packaging

##### Test Plan

From the root of the Netdata source repository, run `docker run -it --rm -v $PWD:/netdata <distro-image> /netdata/packaging/repoconfig/build-<type>.sh` where `<distro-image>` is the Docker image for the distribution you are building for, and `<type>` is the package type being built (either `deb` or `rpm`).

Once that finishes, you should have an `artifacts` directory in your source tree with two packages in it, one named `netdata-repo` and the other named `netdata-repo-edge`.  The `netdata-repo` package is for the stable repository, and the `netdata-repo-edge` package is for the nightly repository. You can install either one by directly passing the package file to the normal package install command for the distro it was built for.

Note that the packages are expected to be mutually exclusive (you can install one or the other, but not both at the same time). Also, it is expected that you will be prompted about whether to trust a specific GPG key either when installing the package, or when attempting to install Netdata from the newly configured package reposityr.

##### Additional Information

Once this is merged and the packages are live, I’ll be opening two additional PRs relating to this, one to add these packages as a soft dependency of our actual binary packages so they get pulled in automatically on existing installs, and one to update the documentation about binary package installation to use these packages instead of relying on the scripts from PackageCloud.

### CODE REVIEW

**Comment by stelfrag** [comment]
I probably missed something :face_with_head_bandage: 

I typed

`docker run -it --rm -v $PWD:/netdata ubuntu /netdata/packaging/repoconfig/build-deb.sh`

and ended up with 

```
No schema files found: doing nothing.
Setting up manpages (5.05-1) ...
Setting up libssl1.1:amd64 (1.1.1f-1ubuntu2.4) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Setting up libbrotli1:amd64 (1.0.7-6ubuntu0.1) ...
Setting up libsqlite3-0:amd64 (3.31.1-4ubuntu0.2) ...
Setting up libsasl2-modules:amd64 (2.1.27+dfsg-2) ...
Setting up binutils-common:amd64 (2.34-6ubuntu1.1) ...
Setting up libnghttp2-14:amd64 (1.40.0-1build1) ...
Setting up libmagic1:amd64 (1:5.38-4) ...
Setting up linux-libc-dev:amd64 (5.4.0-77.86) ...
Setting up libctf-nobfd0:amd64 (2.34-6ubuntu1.1) ...
Setting up gettext-base (0.19.8.1-10build1) ...
Setting up libnpth0:amd64 (1.6-1) ...
Setting up krb5-locales (1.17-6ubuntu4.1) ...
Setting up file (1:5.38-4) ...
Setting up libassuan0:amd64 (2.5.3-7ubuntu2) ...
Setting up libgomp1:amd64 (10.3.0-1ubuntu1~20.04) ...
Setting up libldap-common (2.4.49+dfsg-2ubuntu1.8) ...
Setting up libfakeroot:amd64 (1.24-1) ...
Setting up libkrb5support0:amd64 (1.17-6ubuntu4.1) ...
Setting up libsasl2-modules-db:amd64 (2.1.27+dfsg-2) ...
Setting up tzdata (2021a-0ubuntu0.20.04) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration questions will narrow this down by presenting a list of cities, representing the time zones in which they are
located.

  1. Africa  2. America  3. Antarctica  4. Australia  5. Arctic  6. Asia  7. Atlantic  8. Europe  9. Indian  10. Pacific  11. SystemV  12. US  13. Etc
Geographic area: 
Progress: [ 59%] [###################################################################################################.....................................................................] 
```


Pressing 8 and 4 (Europe / Athens) it continues and ends up with 

```
make[1]: Leaving directory '/usr/src/repoconfig'
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
 debian/rules binary
dh binary
   dh_testroot
   dh_prep
   dh_auto_install
	make -j12 install DESTDIR=/usr/src/repoconfig/debian/tmp AM_UPDATE_INFO_DIR=no
make[1]: Entering directory '/usr/src/repoconfig'
mkdir -p debian/tmp
cp netdata.list netdata-edge.list netdata-archive-keyring.gpg netdata-edge-archive-keyring.gpg netdata-repoconfig-archive-keyring.gpg debian/tmp/
make[1]: Leaving directory '/usr/src/repoconfig'
   debian/rules override_dh_install
make[1]: Entering directory '/usr/src/repoconfig'
mkdir -p /usr/src/repoconfig/debian/netdata-repo/etc/apt/sources.list.d /usr/src/repoconfig/debian/netdata-repo/etc/apt/trusted.gpg.d/
mv -f /usr/src/repoconfig/debian/tmp/netdata.list /usr/src/repoconfig/debian/netdata-repo/etc/apt/sources.list.d
mv -f /usr/src/repoconfig/debian/tmp/netdata-archive-keyring.gpg /usr/src/repoconfig/debian/netdata-repo/etc/apt/trusted.gpg.d
cp /netdata-repoconfig-archive-keyring.gpg /usr/src/repoconfig/debian/netdata-repo/etc/apt/trusted.gpg.d
cp: cannot stat '/netdata-repoconfig-archive-keyring.gpg': No such file or directory
make[1]: *** [debian/rules:17: override_dh_install] Error 1
make[1]: Leaving directory '/usr/src/repoconfig'
make: *** [debian/rules:8: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

**Comment by Ferroin** [comment]
@stelfrag The interactive prompting is due to an oversight on my part (I’ll be pushing a fix shortly). I’ll need to look a bit further into the other error though.

**Comment by Ferroin** [comment]
@stelfrag Should be fixed now, there was a typo in one of the last-minute changes I had made before committing that I forgot to thoroughly test.

**Review by vkalintiris — APPROVED** [review]
LGTM. Curious why we use `edge` instead of `nightly`.

**Comment by Ferroin** [comment]
> LGTM. Curious why we use `edge` instead of `nightly`.

Not sure, but we’re stuck with it for now.

**Review by stelfrag — DISMISSED** [review]

**Comment by Ferroin** [comment]
Rebased to resolve conflict, merging once all the CI checks are done.

**Review by stelfrag — APPROVED** [review]

**Review by vkalintiris — APPROVED** [review]

**Pull request merged**
