### PR TITLE
Update kickstart script to use new DEB infrastructure.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

This is a followup to #14290 that updates the kickstart script to use the new repositories.

##### Test Plan

Running the kickstart script from this PR on a platform we provide native DEB packages for with the `--native-only` switch should correctly install the agent.

### CODE REVIEW

**Comment by ilyam8** [comment]
I get "No repository configuration package available for debian 11": 

<details>
<summary>install log</summary>

```bash
pve-deb-work ~ $ sudo ./kickstart.sh

 --- Using /tmp/netdata-kickstart-bRuZv2HafF as a temporary directory. ---
 --- Checking for existing installations of Netdata... ---
 --- No existing installations of netdata found, assuming this is a fresh install. ---
 --- Attempting to install using native packages... ---
 --- Checking for availability of repository configuration package. ---
 WARNING  No repository configuration package available for debian 11. Cannot install native packages on this system.

 WARNING  Could not install native binary packages, falling back to alternative installation method
```

</details>

**Comment by Ferroin** [comment]
> I get "No repository configuration package available for debian 11"

Should be fixed now, forgot to actually commit some of the changes for the PR...

**Comment by ilyam8** [comment]
Get the following error in an LXC container (debian11

> Download is performed unsandboxed as root as file '/tmp/netdata-kickstart-WQCdPyksVZ/netdata-repo-edge_2-1+debian11_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

<details>
<summary>more logs</summary>

```bash
N: Download is performed unsandboxed as root as file '/tmp/netdata-kickstart-jKELZkN1u3/netdata-repo-edge_2-1+ubuntu22.04_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
 OK

[/tmp/netdata-kickstart-jKELZkN1u3]# env apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:4 http://repo.netdata.cloud/repos/edge/ubuntu jammy/ InRelease
Ign:5 http://repo.netdata.cloud/repos/repoconfig/ubuntu jammy/ InRelease
Get:6 http://repo.netdata.cloud/repos/edge/ubuntu jammy/ Release [552 B]
Get:7 http://repo.netdata.cloud/repos/repoconfig/ubuntu jammy/ Release [546 B]
Get:8 http://repo.netdata.cloud/repos/edge/ubuntu jammy/ Release.gpg [687 B]
Get:9 http://repo.netdata.cloud/repos/repoconfig/ubuntu jammy/ Release.gpg [687 B]
Get:10 http://repo.netdata.cloud/repos/edge/ubuntu jammy/ Packages [7144 B]
Get:11 http://repo.netdata.cloud/repos/repoconfig/ubuntu jammy/ Packages [736 B]
Fetched 10.4 kB in 2s (4649 B/s)
Reading package lists... Done
 OK

 WARNING  Could not find a usable native package for ubuntu on x86_64.

 --- Attempting to uninstall repository configuration package. ---
[/tmp/netdata-kickstart-jKELZkN1u3]# env apt-get purge netdata-repo-edge
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  debian-archive-keyring
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
  netdata-repo-edge*
0 upgraded, 0 newly installed, 1 to remove and 98 not upgraded.
After this operation, 18.4 kB disk space will be freed.
Do you want to continue? [Y/n]
```

</details>

**Comment by Ferroin** [comment]
> Get the following error in an LXC container (debian11)
> 
> > Download is performed unsandboxed as root as file '/tmp/netdata-kickstart-WQCdPyksVZ/netdata-repo-edge_2-1+debian11_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
> > WARNING  Could not find a usable native package for ubuntu on x86_64.
> 
> more logs

And this should be fixed now too.

**Review by ilyam8 — APPROVED** [review]
tested on debian11 and ubuntu22 (LXC containers)

**Review by thiagoftsm — APPROVED** [review]
It works as expected on Ubuntu, LGTM!

**Pull request merged**
