### PR TITLE
systemd-Journal by file

### PR DESCRIPTION
**Pull request by ktsaou**
Operating systemd-journal file-by-file is about 2x faster compared to the default.

On my tests, the current master version of systemd-journal needs 29.2 seconds, while the new one needs 13.5 seconds, for a given time-frame query.

The changes on this PR:

- [x] maintain a registry of journal files
- [x] add support for volatile journal files, even when netdata runs in a container (`/run/log/journal`)
- [x] display the actual realtime timestamp associated with a log entry. The current master presents the timestamp the log was received by journald, while this PR extracts the actual timestamp the log was generated.
- [x] overloads `fstat64()` libc system call, to speed up libsystemd (https://github.com/systemd/systemd/pull/29261)
- [x] support for multiple log sources (including system and user logs, journald namespaces, logs from remote hosts), allowing the user to select the sources of interest.
- [x] fixed several issues related to forward/backward data-only queries
- [x] support for slicing the logs using journal matches

image

### CODE REVIEW

**Comment by andrewm4894** [comment]
Just wondering, is there anything to be said about some ability to runs queries and randomly sample n% from the sources. had a look and does not look like sampling is a "thing" in systemd-journal. But if i could just tell netdata i want quicker response and am happy with 10% random sample data. If that sample could be done by netdata as low level as possible, might that then mean that you could be very quick as a users on the FE playing around with longer time slices (relative to using the full data) - so long as you happy to take the trade off between fact that n% sample might miss something but be much quicker and still be useful to you as sampling 10% maybe 80% of the time will still show you persistent log events that might be what you are after.

**Comment by ktsaou** [comment]
How is sampling going to help is you want to find a crashdump, or something very unique, rare and abnormal?

I think the use case you have in mind is probably about web server logs of some sort. In these cases sampling is a thing, since it will allow you to quickly spot the some issue (like 5xx errors).

But it want to quickly check for errors like the above and there are fields related to the issue, you could just select them and have an accurate view.

Technically, I can try to implement this, but I am not sure of the use case for systemd journal logs...

**Comment by ktsaou** [comment]
journal-sources

**Comment by ktsaou** [comment]
image

**Comment by ktsaou** [comment]
image

**Comment by ktsaou** [comment]
image

**Comment by ktsaou** [comment]
image

**Comment by Ancairon** [comment]
Morning! Just a note, I see a README file in the additions, (I see you used the old way of adding metadata to it, doesn't work anymore, no worries) I can add it to Learn, under `Data Collection` as its own entry (outside of integrations folders, on the same level as System metrics and the likes. For it to appear as an integration we would need to have it inside `integrations.js` (I feel this is not the goal here, so when this is merged I will add it to the spot I mentioned). Just FYI

**Pull request merged**
