### PR TITLE
Fix command name for getting postfix queue

### PR DESCRIPTION
**Pull request by ghasrfakhri**
##### Summary
Fix command name for getting postfix queue
##### Component Name
python.s.plugin/postfix

##### Test Plan
Change Readme, so not test needed

### CODE REVIEW

**Comment by ilyam8** [comment]
@ghasrfakhri 👋 

Thx for contribution, please sign the CLA

**Comment by prologic** [comment]
@ghasrfakhri Do you mind rebasing this PR?

**Comment by ilyam8** [comment]
@prologic i think this is safe to merge, we dont need rebase and code freeze doesnt affect the PR since it is doc changes

**Comment by prologic** [comment]
Agreed. Merging...

**Pull request merged**
