### PR TITLE
Fix issue where initial value in chart was missing in API.

### PR DESCRIPTION
**Pull request by dkennedy-dejero**
##### Summary

Fix issue where initial value in chart was missing in API.

There is an apparent off-by-one error when (re-)calculating the start time for the chart data.

##### Component Name

web/api

##### Test Plan

* Created a dummy collector that generates a known sequence of values (e.g. 1,2,3,4,...) at 1s collection interval. Chart can be created with store_first or without.
* Configure netdata to use dbengine.
* With netdata stopped, erase dbengine and  metadata.
* Start netdata.
* View chart in default dashboard. OR fetch the chart data via api/1/data.

Actual (prior to change): chart data was missing the first entry.
Expected (after change): chart data includes the first entry.

Note that this only affected the very first entry in the chart, immediately after initial creation. Upon resuming an archived chart, the subsequent initial values were correct.

### CODE REVIEW

**Review by thiagoftsm — APPROVED** [review]
I tested this PR as it was suggested and I could verify that `api/v1/data` is according dashboard information. Thank you very much @dkennedy-dejero !

**Comment by vlvkobal** [comment]
But I confirm that there is a bug in memory mode `dbengine`. For the master tree the sequence starts from `3` for the first time and from `2` after Netdata restart
```
{
 "labels": ["time", "increment"],
    "data":
 [
      [ 1634296558, 5],
      [ 1634296557, 4],
      [ 1634296556, 3],
      [ 1634296555, 2],
      [ 1634296554, null],
      [ 1634296553, null],
      [ 1634296552, 12],
      [ 1634296551, 11],
      [ 1634296550, 10],
      [ 1634296549, 9],
      [ 1634296548, 8],
      [ 1634296547, 7],
      [ 1634296546, 6],
      [ 1634296545, 5],
      [ 1634296544, 4],
      [ 1634296543, 3]
  ]
}
```

**Comment by vlvkobal** [comment]
Hm, interesting. The master branch, `memory mode = save`, first start with a clean cache:
```
{
 "labels": ["time", "increment"],
    "data":
 [
      [ 1634297227, 6],
      [ 1634297226, 5],
      [ 1634297225, 4],
      [ 1634297224, 3],
      [ 1634297223, 2]
  ]
}
```
After Netdata restart:
```
{
 "labels": ["time", "increment"],
    "data":
 [
      [ 1634297237, 4],
      [ 1634297236, 3],
      [ 1634297235, 2],
      [ 1634297234, null],
      [ 1634297233, null],
      [ 1634297232, 11],
      [ 1634297231, 10],
      [ 1634297230, 9],
      [ 1634297229, 8],
      [ 1634297228, 7],
      [ 1634297227, 6],
      [ 1634297226, 5],
      [ 1634297225, 4],
      [ 1634297224, 3]
  ]
}
```

**Comment by vlvkobal** [comment]
@dkennedy-dejero, I'm closing this in favor of #11787. Could you test the new fix?

**Pull request closed without merging**
