### PR TITLE
dash.html

### PR DESCRIPTION
**Pull request by tnyeanderson**
##### Summary
**Multi-Host custom dashboard:** `dash.html` is a single-file solution to show graphs, charts, and alarms from all streamed hosts on one page. It takes one defined set of graphs and charts and replicates it for each host. It is quite simple, but quite effective.

##### Component Name
Custom Dashboards

##### Additional Information
I am open to ideas for improvement, but I want other people to have this because it fills a perfect void in Netdata's usability. Navigating between pages for each streamed host is very inconvenient.

I am not interested in Netdata Cloud. This is self-hosted.

### CODE REVIEW

**Comment by ilyam8** [comment]
> Multi-Host custom dashboard: dash.html is a single-file solution to show graphs, charts, and alarms from all streamed hosts on one page

could you provide some screenshots? :thinking:

**Comment by tnyeanderson** [comment]
dash1
dash2


Some info censored.

This uses https://github.com/vishalok12/jquery-dragarrange (for now, but this will probably be removed for a more bespoke solution). It is MIT licensed. Is that compatible?

**Comment by tnyeanderson** [comment]
To be clear, this is NOT supposed to be a solution that is heavily maintained by the devs, this is just an "example" custom dashboard that folks can use/modify to fit their needs. I made it for my purposes, but I realize this is probably a feature (all hosts on one dashboard) that others will want, and I figure this is the best place for it as it will get the most visibility.

**Comment by ilyam8** [comment]
The whole alarm/host menu is to big imo. Huge font size, huge rectangles.

**Comment by tnyeanderson** [comment]
@cakrit great suggestions. I've been making some incremental improvements since this PR was submitted, so I will work on all of those things and get back with another commit.

Not sure what you mean by the netdata logo? I didn't put any images at all in there, it just loads graphs/charts/alarm badges from each host.... I don't see what you're talking about in the screenshots... could you point it out? Happy to throw a netdata logo in there for branding (maybe at the bottom of the alarms sidebar?)

To clarify, you want a both a yellow balloon and a red balloon for the alarm indicator? So if there are both warnings and alarms, both will show? Hm.... my thought was the indicator "light" would be binary, to tell you whether there is something to check or not. Green is good, red means you got something to look at, gray means not loaded yet.... but I can see how having the yellow for warnings could be useful.

@ilyam8 happy to make the fonts in the alarms section smaller. Do you have a design recommendation? Each rectangle is a host, so I'm not sure how to use less rectangles...

**Comment by tnyeanderson** [comment]
Also if someone could send a screenshot of the Nodes view alarm balloons, that would be great. I don't have access to netdata cloud so I cannot see them. Thanks all!

**Comment by cakrit** [comment]
> Not sure what you mean by the netdata logo?

It's this thing, below, I think it may appear on error or something. I killed netdata to make it appear this time: 
Screenshot from 2019-08-12 19-03-57


> Green is good, red means you got something to look at, gray means not loaded yet

You can make it red if there's at least one alarm in a critical state and orange if all the raised alarms are warnings, then you can stick with a single balloon.

**Comment by tnyeanderson** [comment]
I see. I will likely keep it as one indicator balloon, with it showing orange if all alarms are warnings, as you described.

I see what you are talking about now. I didn't add that image in there, it appears to be a byproduct of loading the graphs.... Most I could do is hide it until the graphs load, but that would probably be better solved at the API level, rather than here (if that's something we want).

I'll get started on all that tonight, hopefully will have a new commit by the end of the week that gets this right! Thanks to everyone for the guidance.

**Comment by tnyeanderson** [comment]
Still don't know how we want to go about getting rid of the netdata logo. I haven't investigated to see where it comes from in the API.

This should fix everything @cakrit suggested except for the logo. Hope the alarms look prettier, let me know if you see anything you want improved!

dash1
dash2
dash5
dash3
dash4

**Comment by tnyeanderson** [comment]
These new commit remove https://github.com/vishalok12/jquery-dragarrange as a dependency, instead using a solution created by be, minified and inline, to reorder/hide hosts. Anyone may of course use or modify this code for any purpose at all, and its unminified source code will be released on my github in the coming days. It was placed inline to keep it as a single-file solution. Minified to save space for what is essentially a plugin.

There are also a few bug fixes here. Hope the team likes it!

**Comment by tnyeanderson** [comment]
picknsort

**Comment by cakrit** [comment]
So @tnyeanderson it's ready for another set of reviews, or are you working on more changes?

**Comment by tnyeanderson** [comment]
Should be good to review, those are all the changes I wanted to see. Still haven't fixed the logo issue, but it should be fixed elsewhere in my view. Not sure why Travis failed?

**Comment by cakrit** [comment]
As for Travis failure, it's unrelated to this PR. @paulkatsoulakis is trying to sort it out.

**Comment by tnyeanderson** [comment]
Thank you very much for the feedback:

- The reason for this is that the height is set by the config variable. The reason it is set that way is so that if a graph fails to load, the vertical space is still occupied to ensure that other graphs will maintain horizontal alignment between hosts. I think I will simply hide those buttons rather than try to make that work. I didn't even think of this issue so thank you!
- I will try my best to figure out the white background on the dials
- I also hate having it minified and inline, so in my mind we have two options:
  - Unminify it, but keep it in the same file (less cryptic, but it will take up an additional ~300 lines. My preferred option)
  - Keep it in a separate, unminified file that is sourced on the page. This makes it NOT a single file solution anymore :(
- Yes the gray line is a little unintuitive. I tried to make it more obvious by having it change color on hover, but it appears that isn't clear enough. I could make the line a little wider and add a `>` icon to it to imply that it collapses the sidebar. Perhaps @ilyam8 has a suggestion for this design?

I'm glad you like it so far!

**Comment by tnyeanderson** [comment]
* Hid the button for resizing graphs
* Fixed chart backgrounds
* Placed unminified source inline
* Changed as shown:

hover

**Comment by tnyeanderson** [comment]
Okay can someone help me? Trying to delete the history here... all these force pushes and review commits need to be removed, then this comment can be removed as well. Really messed up my commits but as long as that's removed we should be back to normal. None of those are in my commit history for `tnyeanderson/netdata`, because I removed them then recommited the changes with `Squashed changes`. Please remove the others

bad

**Comment by ilyam8** [comment]
> Trying to delete the history here... all these force pushes and review commits need to be removed, then this comment can be removed as well.

Why do you want to delete something? All commits will be squashed during PR merging.

**Comment by tnyeanderson** [comment]
Because I accidentally leaked my internal hostname in one of the commits -_-

I gotta pay closer attention, I guess!

**Comment by ilyam8** [comment]
> internal hostname

Haha, hacking you right now... hacked! 😎

**Comment by tnyeanderson** [comment]
So is it possible to delete all that crap? Then delete/hide all these comments? I really gummed up this PR..... If we can't then whatever I guess!

xD

**Comment by ilyam8** [comment]
> So is it possible to delete all that crap? Then delete/hide all these comments?

After merge it will be 1 commit with all the changes (commit msg can be modified). Is it ok?

**Comment by tnyeanderson** [comment]
It will still show up in the PR history on this page, correct? I'd like it to not show there at all (since the PR will be public indefinitely), but that might not be possible and I may just be wasting everyone's time.... If it can't be hidden, then that's fine.

**Comment by ilyam8** [comment]
> It will still show up in the PR history on this page, correct?

Yes, you are right. 

> I'd like it to not show there at all (since the PR will be public indefinitely)

I guess it is possible to fix the mess, before try my suggestion - not a specialist, i use cli seldom.

In theory this should work - do a interactive git rebase. There you can remove all not related to your PR commits (drop) and squash your commits to one. Force push then.

> git rebase -i <commit hash, the one before your first commit>

**Comment by ilyam8** [comment]
ok, i was wondering, i tried it

 - remove all commits not related to PR, squash PR commits to one

```
44 ilyam:netdata (master)$ git log --oneline -4
d7362d52 (HEAD -> master) implement dash.html
0cb8dbff Fixed typo (#6575)
2a2549e9 Build DEB and RPM packages in parallel (#6579)
79e5fd09 netdata/packaging: [ci skip] make slack usage a soft error here (the library should be available though, so this is a workaround fix until i figure out the WOW)
```

 - check changes

```
45 ilyam:netdata (master)$ git whatchanged -1
commit d7362d5259217fb1fb641f165c99f55f50c155e9 (HEAD -> master)
Author: Thomas Anderson <tnyeanderson@users.noreply.github.com>
Date:   Mon Aug 5 18:04:35 2019 -0400

    implement dash.html

:100644 100644 ef8aa05f 84ef6a92 M      web/gui/Makefile.am
:100644 100644 f9ffd255 53f04e36 M      web/gui/custom/README.md
:000000 100644 00000000 c64bbc66 A      web/gui/dash-example.html
```

**Comment by ilyam8** [comment]
i can force push my changes btw, can't guarantee that i didn't mess something

**Comment by tnyeanderson** [comment]
If you want to try the force push, I have the changes backed up elsewhere so if something gets messed up it should be no issue. Thank you very very much for looking into this for me, I won't be making this mistake again! :)

**Comment by tnyeanderson** [comment]
Okay I don't think we will be able to get rid of this. Whatever! Just delete this chain of comments to clean up the conversation please. Sorry for making this so verbose, and thank you for the help! I will commit tonight the last of the changes that had been made, then it will be time for review. Thank you again @ilyam8

**Comment by ilyam8** [comment]
> Okay I don't think we will be able to get rid of this.

Get rid of what? i was thinking we removed all leaked stuff, am i wrong?

**Comment by tnyeanderson** [comment]
> Get rid of what? i was thinking we removed all leaked stuff, am i wrong?

The `Fixes requested changes netdata#6603 (review)` still shows beneath my "Ready for review!" post, and if you click that it shows it. I think because it was a "review" commit, it won't ever disappear... Whatever, I'm done worrying about it, let's just delete all these unnecessary comments and move on with life. Thanks for helping out and sorry for wasting your time! :)

**Comment by tnyeanderson** [comment]
Sorry for the muddy waters, and many thanks to @ilyam8 for being so patient with me. Should be ready for an actual review now!

**Comment by tnyeanderson** [comment]
Any word here? Should be ready for review! 😃

**Comment by cakrit** [comment]
I'm merging. Thanks @tnyeanderson !

**Pull request merged**
