### PR TITLE
apps.plugin: add process group for git-related processes

### PR DESCRIPTION
**Pull request by nodiscc**
##### Summary

Add git/software forge related processes to [apps_groups.conf](https://github.com/netdata/netdata/blob/master/collectors/apps.plugin/apps_groups.conf):
 - Gitea self-hosted Git service https://gitea.io/en-us/
 - Gitlab continuous integration runner https://docs.gitlab.com/runner/

##### Component Name

[/collectors/apps.plugin](https://github.com/netdata/netdata/tree/master/collectors/apps.plugin)

##### Additional Information

Default configuration change. Group called 'git' for lack of a better name.

### CODE REVIEW

**Comment by vlvkobal** [comment]
I think `git` is a bit misleading. `git-services` would be a better name for the group.

**Comment by ilyam8** [comment]
i see `git` is in he `build` group

https://github.com/netdata/netdata/blob/5aa60c67a8dbfaced66d04f9e36798b8a7a7782b/collectors/apps.plugin/apps_groups.conf#L210

I guess it should be moved in the new `git-services` group

**Comment by vlvkobal** [comment]
`git` a tool, not a service.

**Comment by vlvkobal** [comment]
Thank you @nodiscc

**Pull request merged**
