### PR TITLE
Page duty V2

### LINKED ISSUE #10151: Support PagerDuty API v2
##### Feature idea summary

Use [PagerDuty's API v2](https://developer.pagerduty.com/docs/events-api-v2/trigger-events/) to send alerts.

Currently, [Netdata](https://github.com/netdata/netdata/blob/5156fb013fc024d7f62611bed50c4c154033f01a/health/notifications/alarm-notify.sh.in#L1014) uses [PagerDuty's API v1](https://developer.pagerduty.com/docs/events-api-v1/trigger-events/) to trigger and resolve alerts. v1 is quite simplistic and doesn't support all the recent features, namely the alert severity which is often used to decide if an on-call person should be contacted urgently.

### PR DESCRIPTION
**Pull request by thiagoftsm**
##### Summary
Fixes #10151 

The main goal of this PR is to use the API V2 that Pager duty, but as we agreed with @Ferroin we are also using this PR to change the indentation used inside the file.

##### Component Name
Alarm notify
##### Test Plan

1 -  Ask @knatsakis to invite you for Pagerduty.
2 - Create a new service.
3 - Get a key for API V2.
4 - Set the variable `DEFAULT_RECIPIENT_PD` 
5 - Go to `plugins.d` directory `cd /usr/libexec/netdata/plugins.d/`
6 - Run the test: `./alarm-notify.sh test`

##### Additional Information
When I ran the tests, I also kept `telegram`, `slack` and `hangout` enabled, and I received the alarms on all channels.
@knatsakis it was the first time that I worked with `PagerDuty`. I could not see the alarms on the service that I created, but I am  always receiving `202` as you can see

```
*  subject: C=US; ST=California; L=San Francisco; O=PagerDuty, Inc.; CN=*.pagerduty.com
*  start date: Apr  6 00:00:00 2020 GMT
*  expire date: Apr 14 12:00:00 2021 GMT
*  subjectAltName: host "events.pagerduty.com" matched cert's "*.pagerduty.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
} [5 bytes data]
> POST /v2/enqueue HTTP/1.1
> Host: events.pagerduty.com
> User-Agent: curl/7.73.0
> Accept: */*
> Content-Length: 1245
> Content-Type: application/x-www-form-urlencoded
> 
} [1245 bytes data]
* upload completely sent off: 1245 out of 1245 bytes
{ [5 bytes data]
* Mark bundle as not supporting multiuse

< HTTP/1.1 202 Accepted
< Server: nginx
< Date: Tue, 03 Nov 2020 23:04:16 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 64
< Connection: keep-alive
```

I think I am missing something on dashboard configuration.

### CODE REVIEW

**Comment by knatsakis** [comment]
> I think I am missing something on dashboard configuration.

@thiagoftsm, I am not aware of any dashboard configuration needed. It looks to me as if the alerts don't get triggered/accepted by PagerDuty. You can try using the "Netdata Cloud Production (alertmanager)" for a test if you like.

**Review by knatsakis — APPROVED** [review]

**Review by vlvkobal — APPROVED** [review]
The code LGTM.

**Review by ilyam8 — APPROVED** [review]

**Comment by thiagoftsm** [comment]
According the [Pagerduty](https://developer.pagerduty.com/docs/events-api-v2/overview/) page, it is necessary to request access to have this new version enabled, I won't merge this PR until we have conditions to test. It looks like that we are not having any problem, considering the `response code` we are receiving, on the other hand, if we merge this PR, we will be forced  to require access to the new API before to use Pagerduty

**Comment by thiagoftsm** [comment]
@vlvkobal , @ilyam8 and @knatsakis I pushed another commit bringing back the version 1 as default, and I also added another variable for users to select the newest version after they require usage for Pager duty. We will need to move forward with this variable, until Pager Duty set version 2 as default.

**Review by ilyam8 — APPROVED** [review]

**Review by vlvkobal — APPROVED** [review]

**Pull request merged**
