### PR TITLE
Add utm params to url links in notifications

### PR DESCRIPTION
**Pull request by MrZammler**
##### Summary

Adds utm params to url links in notifications.

This will add:

```
    "utm_source" = "alarm-notify-{severity}>" e.g. "alarm-notify-warning"
    "utm_medium" = "{notification-method}" e.g. "slack"
    "utm_campaign" = "{chart}" e.g "web_log_nginx.excluded_requests"
    "utm_term" = "{family}" e.g. "requests"
    "utm_content" = "{alarm}" e.g. "web_log_1m_unmatched"
```

##### Test Plan

Not yet ready to test, we need first to make sure links do not break with this change (cloud?) and that utm_params are digested properly.

### CODE REVIEW

**Comment by andrewm4894** [comment]
@MrZammler this looks good to me in terms of what we sending. Once we have some test events in PostHog i can make sure the utm params being parsed properly on that end.

**Comment by ilyam8** [comment]
@MrZammler, hey. Do we still need the changes?

**Comment by MrZammler** [comment]
> @MrZammler, hey. Do we still need the changes?

Not sure, Andy ? @andrewm4894 ?

**Comment by andrewm4894** [comment]
This would be useful, i should have followed up at some stage. Would this be hard to rebase or ??

Context for needing this is it will enable analytics on dashboard sessions triggered from alerts which could be a great signal for an actual troubleshooting session and be very useful as postential signals like predicting a troubleshooting session ahead of time etc.

**Pull request closed without merging**
