### PR TITLE
Add handling for claiming non-standard install types with kickstart.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

SSIA

##### Test Plan

Can be verified by attempting to use the kickstart script from this PR to claim a node that was installed by a method other than the kickstart script (for example, via the FreeBSD Ports tree, or through Homebrew).

##### Additional Information

This also adds an extra sanity check to the claiming code in the kickstart script so that we provide a more user friendly error message if a usable claiming script cannot be found.

### CODE REVIEW

**Comment by cpipilas** [comment]
--- Attempting to claim existing install at /usr/local. --- 
 --- Attempting to claim agent to https://app.netdata.cloud --- 
 ABORTED  Unable to find usable claiming script.

**Comment by iigorkarpov** [comment]
~/netdata  on relaxed-claim-checks> packaging/installer/kickstart.sh                                                                                                                                                                                            
 --- Using /tmp/netdata-kickstart-XXXXXXXXXX.wIPNfmgH as a temporary directory. ---
 WARNING  Found an existing netdata install at /usr/local, but could not determine the install type.

 WARNING  Unable to find usable updater script, not updating existing install at /usr/local.

 --- Not attempting to claim existing install at /usr/local (no claiming token provided). ---

**Comment by Ferroin** [comment]
Rebased to pick up CI changes and also (probably) fixed issue reported by @cpipilas.

**Comment by Ferroin** [comment]
@iigorkarpov Expected behavior if you don’t provide any claiming options.

**Comment by iigorkarpov** [comment]
@Ferroin Claiming options? Like what?

**Comment by Ferroin** [comment]
> @Ferroin Claiming options? Like what?

https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#connect-node-to-netdata-cloud-during-installation

**Review by kickoke — DISMISSED** [review]
Docs: Looks good to me.

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Review by kickoke — DISMISSED** [review]
Docs: LGTM

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Comment by Ferroin** [comment]
Rebased to resolve merge conflicts.

**Review by maneamarius — APPROVED** [review]

**Review by kickoke — APPROVED** [review]

**Comment by Ferroin** [comment]
Rebased to resolve merge conflict and pick up CI changes.

**Comment by surajnpn** [comment]
> Rebased to resolve merge conflict and pick up CI changes.

Tested on FreeBSD, works. Lets get this merged soon

**Review by iigorkarpov — APPROVED** [review]

**Review by kickoke — APPROVED** [review]

**Pull request merged**
