### PR TITLE
Update freebsd.md

### PR DESCRIPTION
**Pull request by disko**
Install most recent version as of today. Also install ``gmake`` as required permission (installation fails without this).

### CODE REVIEW

**Comment by thiagoftsm** [comment]
Hi @disko ,

Please, sign the [CLA](https://github.com/netdata/netdata/pull/10005#issuecomment-700617085) for we have conditions to merge your PR.

Best regards!

**Review by thiagoftsm — APPROVED** [review]
I removed `gmake` from my FreeBSD VM and I can confirm that we were missing instructions to install Netdata on FreeBSD.

**Review by joelhans — APPROVED** [review]
Approving as well based on the fact the changes are straigtforward and @thiagoftsm tested it! Once the CLA is signed we can merge this. 

Thank you very much, @disko!

**Comment by OdysLam** [comment]
@disko 

Welcome to our community :) Thanks for the contribution, it means tons to us!

If you have any questions, just reach out here via Github issues or in our forums at https://community.netdata.cloud!

**Pull request merged**
