### PR TITLE
Events tab documentation updates

### PR DESCRIPTION
**Pull request by Ancairon**
##### Summary

@netdata/product I need your help in this, I have used the feed from cloud and the agent and can't figure out:

1. If it has the same features
2. I don't know the plan time-limits (who would know?)
3. I don't know the available list of events for the last section.

(I removed the pro plan, but I don't know the rest of the details)

### CODE REVIEW

**Comment by Ancairon** [comment]
cc @ralphm

**Comment by hugovalente-pm** [comment]
> 1. If it has the same features
> 2. I don't know the plan time-limits (who would know?)

What I know is only what is on our pricing page, afaik Agent only has the Alerts history.  [Topology](https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#topology-events) and [Auditing](https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#auditing-events) events are only from Netdata Cloud.

> 3. I don't know the available list of events for the last section.

Do you mean the [Event types and filters](https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#event-types-and-filters)? This was acting as an aggregation of all the other events and adding the tags and available filters. IMO, this probably is to much effort to maintain and we could have just the above sections.

**Review by ralphm — CHANGES_REQUESTED** [review]

**Comment by Ancairon** [comment]
> What I know is only what is on our pricing page, afaik Agent only has the Alerts history. [Topology](https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#topology-events) and [Auditing](https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#auditing-events) events are only from Netdata Cloud.

So, homelab would have the same limits as Business?

**Review by hugovalente-pm — APPROVED** [review]

**Comment by ralphm** [comment]
> > 3. I don't know the available list of events for the last section.
> 
> Do you mean the [Event types and filters](https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#event-types-and-filters)? This was acting as an aggregation of all the other events and adding the tags and available filters. IMO, this probably is to much effort to maintain and we could have just the above sections.

I don't think this has changed much at all. I thought it was kind of nice to show which events a user can expect, as if you only run the Agent you'll only see alert events.

**Comment by hugovalente-pm** [comment]
> I don't think this has changed much at all. I thought it was kind of nice to show which events a user can expect, as if you only run the Agent you'll only see alert events.

I'm not suggesting to remove all the lists of events just this global view https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#event-types-and-filters

**Comment by ralphm** [comment]
> > I don't think this has changed much at all. I thought it was kind of nice to show which events a user can expect, as if you only run the Agent you'll only see alert events.
> 
> I'm not suggesting to remove all the lists of events just this global view https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#event-types-and-filters

Right, but the commits you approved include the removal of those events…

**Comment by hugovalente-pm** [comment]
> Right, but the commits you approved include the removal of those events…

@ralphm actually no, the current file has the sections for:
* [Auditing events](https://github.com/netdata/netdata/blob/0a76c7fdd58e2b723ad5dc9015dc9f9d87262eae/docs/cloud/insights/events-feed.md#auditing-events) - including latest about Silencing Rules and Claiming Token
* [Topology Events](https://github.com/netdata/netdata/blob/0a76c7fdd58e2b723ad5dc9015dc9f9d87262eae/docs/cloud/insights/events-feed.md#topology-events)
* [Alert Events](https://github.com/netdata/netdata/blob/0a76c7fdd58e2b723ad5dc9015dc9f9d87262eae/docs/cloud/insights/events-feed.md#alert-events)

it removed the "global view" that consolidates all the events and adds tags, filtering attributes - https://learn.netdata.cloud/docs/dashboards-and-charts/events-feed#event-types-and-filters
which is what I mentioned 
> this probably is to much effort to maintain and we could have just the above sections

**Review by ralphm — APPROVED** [review]
Ah @hugovalente-pm. Now I understand 👍

**Pull request merged**
