### PR TITLE
Really prevent overwriting netdata.conf on static installs.

### PR DESCRIPTION
**Pull request by Ferroin**
##### Summary

The previous fix was incompletely tested and didn't actually workdue to
using an incorrect variable name. This fixes that.

##### Component Name

area/packaging

##### Test Plan

Original testing only looked at intermediate stages, this one is now confirmed by testing the final output.

##### Additional Information

Fixes: #8531

### CODE REVIEW

**Comment by prologic** [comment]
If there are two ticks from @knatsakis it must be good :) Approved!

**Comment by Ferroin** [comment]
@prologic You're right this does indeed not work on top of PR #9165, though I'm not sure why. However, testing just by itself, it does indeed appear to do as advertised and not overwrite `/opt/netdata/etc/netdata.conf`.

**Comment by prologic** [comment]
> @prologic You're right this does indeed not work on top of PR #9165, though I'm not sure why. However, testing just by itself, it does indeed appear to do as advertised and not overwrite `/opt/netdata/etc/netdata.conf`.

Let's discuss in tonight sync or we can chat anytime you are available.

**Comment by prologic** [comment]
Based on in-person discussion I'm approving this as I cannot see any other place where this wwould be misbehaving.

**Pull request merged**
